### ISSUE TITLE
Issue with v0.19.4 tag place

### ISSUE THREAD

**Issue by ahlinc** [tree-sitter/tree-sitter#1003]
```
$ git loa -12
* 56c7c6b3 5 hours ago Max Brunsfeld (origin/master, origin/HEAD) Add zenodo citation badge to readme
* 810d10fa 7 hours ago Max Brunsfeld 0.19.4
* 5f313689 7 hours ago Max Brunsfeld rust: 0.19.4
* 2a991081 7 hours ago Max Brunsfeld web: 0.19.2
*   a440e111 7 hours ago Max Brunsfeld Merge pull request #996 from ahlinc/fix/test-precondition
|\
| * 148680b3 34 hours ago A H (mine/fix/test-precondition, master) fix: assertion in highlight::tests::test_parse_style test
* |   e94b208d 25 hours ago Max Brunsfeld Merge pull request #999 from BonaBeavis/patch-2
|\ \
| * | f96612c7 26 hours ago BonaBeavis sparql and turtle parsers are stable
|/ /
| | * 6dd41e2e 7 hours ago Max Brunsfeld (tag: v0.19.4) 0.19.4
| | * f741eaa2 7 hours ago Max Brunsfeld rust: 0.19.4
| | * 9ee49da0 7 hours ago Max Brunsfeld web: 0.19.2
| |/
|/|
* |   beaa0233 29 hours ago Max Brunsfeld Merge pull request #998 from tree-sitter/node-kind-fix
|\ \
```
@maxbrunsfeld I see weirdness with the latest `v0.19.4` release tag, it's on `6dd41e2e` commit that is out of the `master` branch flow what didn't happen before. I guess you wanted to fix the tests before the release but did the release on 6 minutes earlier, so there are duplicate of three commits in the tagged released branch and on the master branch.
Could you force push the tag to `810d10fa` or at least merge the current tag place on `6dd41e2e` to the master branch to resolve this, please?

Also it's unclear for me and I wonder why do you make separate versions for the web part, now it has v0.19.2 while other parts have v0.19.4?

And it'd be awesome to have annotated tags (`git tag -a`) here in the repo to make `git describe` command to work fine, this may help to refer this tree-sitter commits more meaningful when this repo would be used some else as embedded.

**Comment by maxbrunsfeld** [comment]
Yeah, I updated that tag. It must have accidentally left it after rebasing the master branch. Thanks!

**Comment by maxbrunsfeld** [comment]
> Also it's unclear for me and I wonder why do you make separate versions for the web part, now it has v0.19.2 while other parts have v0.19.4?

The `web-tree-sitter` package is a separate package on NPM from the CLI, so it has a different version number. We could just always update them in lock-step, but I also think it's fine for them to be independent. I generally have updated the minor version (`19` currently) in correspondence with the parser ABI version, but I don't know if it'll always need to be that way. At some point, the parser ABI will just stop changing, hopefully.
