### ISSUE TITLE
Release 0.19.4 has no assets which breaks install.js

### ISSUE THREAD

**Issue by Hoffs** [tree-sitter/tree-sitter#1006]
Since assets are not available for 0.19.4 tag the scripts are unable to download correct archive which means that both installation methods are broken.

In cargo it fails with
```
  thread 'main' panicked at 'assertion failed: repo_path.pop()', /.../tree-sitter-cli-0.14.5/build.rs:22:13
  stack backtrace:
     0: std::panicking::begin_panic
     1: build_script_build::read_git_sha
     2: build_script_build::main
     3: core::ops::function::FnOnce::call_once
```
and in node with a bit more obvious error
```
> node install.js

Downloading https://github.com/tree-sitter/tree-sitter/releases/download/v0.19.4/tree-sitter-linux-x64.gz
Download failed

url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.19.4/tree-sitter-linux-x64.gz
status: 404
```

**Comment by ahlinc** [comment]
Sorry, this is related to #1003 where I asked to move the tag. Didn't know that Github would remove all assets in this case. @maxbrunsfeld could you regenerate all assets on the current release tag?

**Comment by maxbrunsfeld** [comment]
No, that wasn't your fault @ahlinc; it was just an error on my part to leave the release in a draft state. Apologies for the confusion, @Hoffs. Thanks for the report.

**Comment by ahlinc** [comment]
@maxbrunsfeld no problem, thanks for the fix!

**Comment by kobboi** [comment]
@maxbrunsfeld Could you in the future just make a differently versioned release tarball? I think downstream package managers would appreciate that :) 

2021-04-06 19:07:25 (6,01 MB/s) - ‘/var/cache/distfiles/tree-sitter-0.19.4.tar.gz.__download__’ saved [2869856/2869856]

!!! Fetched file: tree-sitter-0.19.4.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      2869856
!!! Expected: 2869774
Refetching..
