### ISSUE TITLE
Failed assertion in `ts_query__analyze_patterns`

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#1007]
The latest `c-sharp` grammar and query patterns from Emacs package `csharp-tree-sitter` [crash Emacs](https://github.com/ubolonton/emacs-tree-sitter/issues/125).

`tree-sitter`: https://github.com/tree-sitter/tree-sitter/commit/56c7c6b39d908c2df059e2c7f75860f819010671
`tree-sitter-c-sharp`: https://github.com/tree-sitter/tree-sitter-c-sharp/commit/70fd2cba742506903589b5e046c32e0e3e06404a

```bash
echo '(prefix_unary_expression (identifier)* @variable)' | tree-sitter query /dev/stdin /tmp/empty.cs
Assertion failed: (exists), function ts_query__analyze_patterns, file src/./query.c, line 1236.
[1]    3970 done       echo '(prefix_unary_expression (identifier)* @variable)' |
       3971 abort      tree-sitter query /dev/stdin /tmp/empty.cs
```

**Comment by maxbrunsfeld** [comment]
Thanks for the report. Taking a look this morning.

**Comment by maxbrunsfeld** [comment]
Fixed on master.
