### ISSUE TITLE
Unable to install tree-sitter using linuxbrew

### ISSUE THREAD

**Issue by lalitmee** [tree-sitter/tree-sitter#1009]
I am facing an issue while installing tree-sitter using Linux brew. I have installed and updated it a lot of times but for new version of tree-sitter which is `0.19.4`, I am not able to install it. It is giving me the following error:

```log
❯ brew install tree-sitter
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Downloading https://github.com/tree-sitter/tree-sitter/archive/v0.19.4.tar.gz
==> Downloading from https://codeload.github.com/tree-sitter/tree-sitter/tar.gz/v0.19.4
      # -=#=- #     #
Error: SHA256 mismatch
Expected: b90c1107a3e09b2dbef9ba317db9fde18f7222898d8470782f539cee286eebad
  Actual: 98e6b7f77d277235ef43023a8eee37745d1bc315c138481ed1b054cff158e817
    File: /home/lalitmee/.cache/Homebrew/downloads/bae893027c031d3ca00b3d1a71f2159823f39f0e9d53f1e844e1a65b68c079c9--tree-sitter-0.19.4.tar.gz
To retry an incomplete download, remove the file above.

```

What should I do?

**Comment by patrickt** [comment]
This looks like an error in the Homebrew formula: running `shasum -a 256` on the artifact downloaded from `https://github.com/tree-sitter/tree-sitter/archive/v0.19.4.tar.gz` produces the `98e6b7` hash. Since we don’t control the Homebrew formula, I’d recommend filing a bug against https://github.com/Homebrew/homebrew-core. Until that’s fixed, you could try building from source.

**Comment by ahlinc** [comment]
@lalitmee this is related to #1003 #1006.
It seems the Homebrew have some automation for quick tree-sitter new version releases and the Homebrew package now contains checksum for the old tree-sitter assets before its regeneration. As @patrickt said, please ask Homebrew maintainers to update the package checksums.
And thank you for the heads up, I've already suggested to make improvements to the tree-sitter releasing process and also will do more suggestions to eliminate such situations in the future.
