### ISSUE TITLE
Need help to define a specific query

### ISSUE THREAD

**Issue by doums** [tree-sitter/tree-sitter#1010]
Hi,

For C language I'm trying to define a custom query that matches the name of a macro (eg defined with `#define`) after `#undef` directive and capture it:

```
#undef MACRO_NAME
//     ^^^^^^^^^^
```

I tried this but without success
```
(preproc_call
  argument: (preproc_arg
    type: (type_identifier) @macro_name))

; or

(((type_identifier) @property)
 (#has-ancestor? @macro_name preproc_call)
 (#has-ancestor? @property field_declaration)
 (#not-has-ancestor? @property function_declarator))
```
I use nvim-treesitter with the playground module, thank to it I can see the tree:
```
  preproc_call [25, 0] - [27, 0]
    directive: preproc_directive [25, 0] - [25, 6]
    argument: preproc_arg [25, 6] - [25, 11]
      type: type_identifier [25, 7] - [25, 11]
```
The corresponding node of the macro name is `type_identifier`.

But I fail to find the right syntax to capture it.

**Comment by ahlinc** [comment]
@doums I'd suggest to try to identify what versions of the `tree-sitter` core library and the `tree-sitter-c` language are used by `nvim-treesitter`, cause your tree representation looks different from the representation generated in the [playground](https://tree-sitter.github.io/tree-sitter/playground) that uses pretty new versions of mentioned components.
Try to use the next in the mentioned playground:
- **Language**: `C`
- **Code**:
```c
#undef MACRO_NAME
// 1   ^^^^^^^^^^
#define MACRO2
// 2    ^^^^^^
#define M3(x) x + 1 \
              + 123
// 3    ^^
```
- **Query**:
```
(preproc_call argument: (preproc_arg) @macro.name)
(preproc_def name: (identifier) @macro.name)
(preproc_function_def name: (identifier) @macro.name)
```
If the query is correct you'll see that interested parts would by highlighted by some random color. The same color is used for all occurrences of the same matching name.

**Comment by doums** [comment]
Hi @ahlinc,

> @doums I can't reproduce the same output for your snippet

Yeah this is because the output was taken from `nvim-treesitter`'s playground with self injected parser tuned on.. with self injected parser turned off I get
```
preproc_call [25, 0] - [27, 0]
    directive: preproc_directive [25, 0] - [25, 6]
    argument: preproc_arg [25, 6] - [25, 11]
```
and the query `(preproc_call argument: (preproc_arg) @macro.name)` seems to works as expected.

My problem seems to be caused by some kind of conflicts between queries and I suppose the problem is probably located in `nvim-treesitter` side. See https://github.com/nvim-treesitter/nvim-treesitter/issues/1084

I close this is issue for now. Thanks for the help anyway :)
