### ISSUE TITLE
Alternative ebnf to write parsers

### ISSUE THREAD

**Issue by mingodad** [tree-sitter/tree-sitter#1013]
Would be nice if we have an alternative way to write parsers like using `EBNF` (like the one used in https://www.bottlecaps.de/rr/ui ) so we could have visual insight when writing the grammar.

Actually the `Javascript` interface to write parsers is only used to write a json structured in a way expected by the parser generator and it seems to be a lot more verbose/obscure than plain `EBNF` (or another variant of BNF).

Has someone already done or know an `ebnf2json` that can output a `Json` like the one expected by the parser generator ?

**Comment by mingodad** [comment]
Also for the existing grammars would be nice to have a `json2ebnf` that would get the `grammar.json` and output an `EBNF`.

**Comment by patrickt** [comment]
I think there are a lot of advantages to using JS rather than an EBNF notation:
* every editor already has good JS support;
* you can write helper functions and define variables, which is very useful for complicated grammars like Haskell;
* tree-sitter itself is closely tied to npm;
* there are multiple competing standards for EBNF (W3C, ISO, IETF, BSI), as well as the ad-hoc BNF syntaxes that many languages use in their grammar descriptions;
* BNF makes operator precedence implicit in its rules, whereas tree-sitter uses explicit numeric precedence;
* tree-sitter allows giving explicit names to subfields within a node, with the `field` function, which doesn’t fit well into BNF notation, at least not that I’ve seen.

The only real advantages I see of EBNF over JS is that EBNF is more concise, given its use of juxtaposition for `seq` and `|` and `?` for `choice` and `optional`. However, I think tree-sitter grammars are already plenty concise. A third-party tool that generated a `grammar.json` sounds like a cool project, though!

**Comment by mingodad** [comment]
Thank you for your comments !
And here is a naive Javascript (QuickJS) program that converts the generated "src/grammar.json" to an `EBNF` format that can be used on https://www.bottlecaps.de/rr/ui (**some grammars still require a bit of manual editing the generated EBNF**) :
```
import * as std from "std";
import * as os from "os";

//print(typeof process);
//if(typeof std == "undefined") {
//}

const fname =
	//"src/grammar.json"
	//"A_grammars/tree-sitter/tree-sitter-lua/src/grammar.json"
	//"A_grammars/tree-sitter/tree-sitter-lbnf/src/grammar.json"
	//"A_grammars/tree-sitter/tree-sitter-kotlin/src/grammar.json"
	//"A_grammars/tree-sitter/tree-sitter-julia/src/grammar.json"
	//"A_grammars/tree-sitter/tree-sitter-javascript/src/grammar.json"
	//"A_grammars/tree-sitter/tree-sitter-fortran/src/grammar.json"
	"A_grammars/tree-sitter/tree-sitter-html/src/grammar.json"
	;

let fd = std.open(fname, "r");
let json = fd.readAsString();
fd.close();

json = JSON.parse(json);
print(json);

function manageRule(name, rule) {
	//print(name, rule.type); //, typeof rule);
	switch(rule.type)
	{
		case "ALIAS":
			std.printf(" ( ");
			manageRule(rule.type, rule.content);
			std.printf(" ) ");
		break;
		case "BLANK":
			print(rule.type);
		break;
		case "CHOICE": {
			let members = rule.members;
			let isOptional = members.length == 2 && members[1].type == "BLANK";
			if(isOptional) {
				std.printf(" (");
				manageRule(rule.type, members[0]);
				std.printf(" )? ");
			}
			else
			{
				std.printf(" (");
				for(var idx in members) {
					if(idx > 0) std.printf(" | ");
					manageRule(rule.type, members[idx]);
				}
				std.printf(" ) ");
			}
		}
		break;
		case "FIELD":
			//print(rule.type, rule.name);
			std.printf(" ( ");
			manageRule(rule.type, rule.content);
			std.printf(" ) ");
		break;
		case "IMMEDIATE_TOKEN":
			std.printf(" ( ");
			manageRule(rule.type, rule.content);
			std.printf(" ) ");
		break;
		case "PATTERN": {
			let value = rule.value.replace("\\d", "[0-9]");
			std.printf(" %s", value);
		}
		break;
		case "PREC":
		case "PREC_DYNAMIC":
		case "PREC_LEFT":
		case "PREC_RIGHT":
			std.printf("  ( ");
			manageRule(rule.type, rule.content);
			std.printf(" ) ");
		break;
		case "REPEAT":
			std.printf(" ( ");
			manageRule(rule.type, rule.content);
			std.printf(" )* ");
		break;
		case "REPEAT1":
			std.printf(" (");
			manageRule(rule.type, rule.content);
			std.printf(" )+ ");
		break;
		case "SEQ": {
			let members = rule.members;
			std.printf(" (");
			for(var idx in members) {
				manageRule(rule.type, members[idx]);
			}
			std.printf(" ) ");
		}
		break;

		case "STRING": {
			let value = rule.value;
			//print(rule.type, value);
			value = value.replace("\\", "\\\\");
			if(value.indexOf("'") >= 0) std.printf(" \"%s\" ", value);
			else std.printf(" '%s' ", value);
		}
		break;

		case "SYMBOL":
			//print(rule.type, rule.name);
			std.printf(" %s", rule.name);
		break;

		case "TOKEN":
			std.printf(" ( ");
			manageRule(rule.type, rule.content);
			std.printf(" )* ");
		break;

		default:
			throw("Unknown rule type: " + rule.type);
	}
}

let rules = json.rules;
for(var idx in rules) {
	let rule = rules[idx];
	//print(rule);
	std.printf("%s ::= ", idx);
	manageRule(idx, rule);
	std.printf("\n\n");
}
```
And here is a sample from https://github.com/tree-sitter/tree-sitter-html:
```
fragment ::=  (  _node )* 

doctype ::=  ( '<!'  (  _doctype )  [^>]+ '>'  ) 

_doctype ::=  [Dd][Oo][Cc][Tt][Yy][Pp][Ee]

_node ::=  ( doctype |  text |  element |  script_element |  style_element |  erroneous_end_tag ) 

element ::=  ( ( start_tag (  _node )*  ( end_tag |  _implicit_end_tag )  )  |  self_closing_tag ) 

script_element ::=  ( (  script_start_tag )  ( raw_text )?  end_tag ) 

style_element ::=  ( (  style_start_tag )  ( raw_text )?  end_tag ) 

start_tag ::=  ( '<'  (  _start_tag_name )  (  attribute )*  '>'  ) 

script_start_tag ::=  ( '<'  (  _script_start_tag_name )  (  attribute )*  '>'  ) 

style_start_tag ::=  ( '<'  (  _style_start_tag_name )  (  attribute )*  '>'  ) 

self_closing_tag ::=  ( '<'  (  _start_tag_name )  (  attribute )*  '/>'  ) 

end_tag ::=  ( '</'  (  _end_tag_name )  '>'  ) 

erroneous_end_tag ::=  ( '</'  erroneous_end_tag_name '>'  ) 

attribute ::=  ( attribute_name ( ( '='  ( attribute_value |  quoted_attribute_value )  )  )?  ) 

attribute_name ::=  [^<>"'/=\s]+

attribute_value ::=  [^<>"'=\s]+

quoted_attribute_value ::=  ( ( "'"  ( (  [^']+ )  )?  "'"  )  |  ( '"'  ( (  [^"]+ )  )?  '"'  )  ) 

text ::=  [^<>]+
```

**Comment by theHamsta** [comment]
@mingodad you could use your script and Github Actions to render EBNF and the diagrams on a static website. Would be really useful for people writing query for languages.

**Comment by mingodad** [comment]
Hello Stephan !
I was thinking about doing it and after your message I started it here https://github.com/mingodad/plgh any comment/suggestion is welcome.

**Comment by stephe-ada-guru** [comment]
Domingo Alvarez Duarte ***@***.***> writes:

> Would be nice if we have an alternative way to write parsers like
> using `EBNF` (like the one used in https://www.bottlecaps.de/rr/ui )
> so we could have visual insight when writing the grammar.

My parser generator WisiToken supports reading EBNF and outputting
tree-sitter grammar file syntax.

(I wrote that to try to compare the error correction quality of the
WisiToken parser to the tree-sitter parser).

This feature is not in a release version yet, but I'd be happy to help
you use the devel version to try this out.

The conversion is done by a command-line tool.

-- 
-- Stephe

**Comment by mingodad** [comment]
Hello Stephen !
Of course I want to try it out !
I'm looking right now on http://stephe-leake.org/ada/wisitoken.html

**Comment by mingodad** [comment]
Hello again Stephen !
First road block it's in ADA and there isn't binaries ready to use and the installation is not straight forward for non ADA experts !

**Comment by mingodad** [comment]
What I saw so far that could be interesting is http://bnfparser2.sourceforge.net/index.html (defunct), https://github.com/katef/kgt and http://www.colm.net/open-source/colm/ .
Does anyone knows anything like bnfparser2 ?

**Comment by maxbrunsfeld** [comment]
How would the EBNF syntax express things like `field`, `alias`, `prec`, and `prec.dynamic`? It seems like you would need to build out a custom extension to EBNF, and then grammar authors would have to learn a custom, non-standard language.

**Comment by mingodad** [comment]
As you've mention probably would be a need to somehow customize/extend an EBNF like syntax but that can remain the same in the core son few things to learn.

For example one way could be (purely for start the conversation) adding those extra attributes hidden inside comments this way they are invisible to already existing tools like https://www.bottlecaps.de/rr/ui and we still get overall a very declarative way to describe the grammar.

Snippets from the Javascript grammar:
```
    export_statement: $ => choice(
      seq(
        'export',
        choice(
          seq('*', $._from_clause, $._semicolon),
          seq($.export_clause, $._from_clause, $._semicolon),
          seq($.export_clause, $._semicolon)
        )
      ),
      seq(
        repeat(field('decorator', $.decorator)),
        'export',
        choice(
          field('declaration', $._declaration),
          seq(
            'default',
            field('value', $._expression),
            $._semicolon
          )
        )
      ),
    ),

    continue_statement: $ => seq(
      'continue',
      field('label', optional(alias($.identifier, $.statement_identifier))),
      $._semicolon
    ),

    labeled_statement: $ => prec.dynamic(-1, seq(
      field('label', alias(choice($.identifier, $._reserved_identifier), $.statement_identifier)),
      ':',
      $._statement
    )),
```
Pseudo enhanced EBNF:
```
export_statement
	 ::= 'export' ( '*' _from_clause | export_clause _from_clause? ) _semicolon
           | decorator/*filed:decorator*/* 'export' ( _declaration/*field:declaration*/ | 'default' _expression _semicolon )

continue_statement
         ::= 'continue' (identifier/*alias:.bar*/?)/*field:label*/ _semicolon

labeled_statement
         ::= ((( identifier | _reserved_identifier )/*alias:._reserved_identifier*/)/*field:label*/ ':' _statement)/*prec.dynamic:-1*/
```

**Comment by maxbrunsfeld** [comment]
Overall, I don’t think I’m interested in adding something like this. It does not seem like an improvement over the existing JavaScript DSL at all.

I think there are some pain points in writing grammars, but the use of JS really isn’t one of them; people generally have an easy time picking it up, and it’s well supported by tooling.

**Comment by eatkins** [comment]
If anyone is interested, I recently wrote my own [tool](https://github.com/eatkins/tree-sitter-ebnf-generator) that defines a custom EBNF syntax based on the [w3c standard](https://www.w3.org/TR/xml/#sec-notation) that supports the entirety of the javascript dsl https://github.com/eatkins/tree-sitter-ebnf-generator. It works by transliterating the EBNF format into a grammar.js file so it requires no upstream changes from tree-sitter to use. The syntax that I added for things like precedence and fields is quite ad hoc, but I find that it works quite well. [Here](https://github.com/eatkins/tree-sitter-ebnf-generator/blob/master/examples/handwritten-scala/scala.ebnf) is an example of the grammar defined in [tree-sitter-scala](https://github.com/tree-sitter/tree-sitter-scala/blob/master/grammar.js) after I converted it to the EBNF syntax (with a reverse translation script).

>  Overall, I don’t think I’m interested in adding something like this. It does not seem like an improvement over the existing JavaScript DSL at all.
I think there are some pain points in writing grammars, but the use of JS really isn’t one of them; people generally have an easy time picking it up, and it’s well supported by tooling.

I personally did find the js dsl a pain point, which is why the linked project exists.

**Comment by mingodad** [comment]
Hello Ethan !
Thank you so much for your great work in figuring out a declarative grammar description for `tree-sitter` !
I hope other people will jump in and help spread/improve it, myself included !
