### ISSUE TITLE
Program freezes on query

### ISSUE THREAD

**Issue by luminr** [tree-sitter/tree-sitter#1018]
Hi! If you query this bash code
```
a=$b
```
with this string
```
name: (variable_name) @q
```
The program freezes and crashes.

<img width="640" alt="Screen Shot 2021-03-25 at 20 00 28" src="https://user-images.githubusercontent.com/3368501/112463134-38620400-8da5-11eb-96f4-10e514626bbf.png">

It happens with both wasm and node binding on win 10. :(

**Comment by Razzeee** [comment]
Should probably be handled in the bash grammar repo https://github.com/tree-sitter/tree-sitter-bash

**Comment by maxbrunsfeld** [comment]
Sorry for the bad bug, and thank you for the nice reproduction case!
