### ISSUE TITLE
Can we get a web-tree-sitter update?

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#1021]
Hey there,

we're kind of waiting on the release of 0.19.2 for https://www.npmjs.com/package/web-tree-sitter

Specifically for the fix in https://github.com/tree-sitter/tree-sitter/pull/989

Cheers

**Comment by Razzeee** [comment]
@maxbrunsfeld any thoughts on this?

**Comment by ganezdragon** [comment]
+1 would need it to fix the "WebAssembly.Memory(): could not allocate memory error"

**Comment by Razzeee** [comment]
@maxbrunsfeld we still seem to have users, that run into problems that should be fixed with the latest version. Please consider a release.
