### ISSUE TITLE
out-of-order parsing

### ISSUE THREAD

**Issue by jbyuki** [tree-sitter/tree-sitter#1026]
Hey,

I wanted to parse a tangled file with tree-sitter. Obviously there is no
built-in support but I was seeing how I could still parse such a file.

I noticed that when passing ranges to `ts_parser_set_included_ranges`,
the order is not preserved. For example a simple HTML document containing
embedded JS.

```html
<script>
    if(a) {
</script>
<script>
        a = null
    }
</script>
```

If I obtain the two included ranges through queries, and I pass them to
`ts_parser_set_included_ranges`, no matter the order, the parsing
will be done in the line order.

I was wondering if it's possible to reorder included ranges in some way. I suspect
it's not possible because there are no real use cases. Maybe I'm also missing
something because I know very little of tree-sitter.

**Comment by maxbrunsfeld** [comment]
Yeah, you’re right that the ranges need to be in order. I think this is needed in order for the syntax nodes to have a consistent order and set of positions.

**Comment by jbyuki** [comment]
Thank you for the quick response!
I will look for other workarounds then.
