### ISSUE TITLE
Infinite loop with `inline`

### ISSUE THREAD

**Issue by AnyhowStep** [tree-sitter/tree-sitter#1029]
I'm using `tree-sitter@0.19.0` from `npm`.

I was trying to understand the difference between using `inline` and using `_leading_underscore`.
Intuitively, they seemed to have the same effect.

So, I wrote a test grammar,
```js
module.exports = grammar({
    name: 'YOUR_LANGUAGE_NAME',
  
    inline: $ => [
        $.symbol2,
    ],
    rules: {
        source_file: $ => $.symbol2,
        symbol2: $ => "symbol2",
    },
});
```

Running `tree-sitter generate` on this `grammar.js` file appears to cause an infinite loop.
No output. Just hangs.

-----

I tried a different grammar,
```js
module.exports = grammar({
    name: 'YOUR_LANGUAGE_NAME',
  
    inline: $ => [
        $.symbol2,
    ],
    rules: {
        source_file: $ => choice(
            $._symbol1,
            $.symbol2,
        ),
        _symbol1: $ => "symbol1",
        symbol2: $ => "symbol2",
    },
});
```

The output I get is,
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', cli/src/generate/prepare_grammar/process_inlines.rs:103:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

-----

I'm filing the issue here because the error message I get makes it seem like it isn't a problem with `node-tree-sitter`.

**Comment by ahelwer** [comment]
I have run into something similar except grammar generation just takes much longer with `inline` than putting an underscore before the rule name.

**Comment by amaanq** [comment]
Running `generate` on the example(s) above display the following error without hanging or crashing:

```
Token `symbol2` cannot be inlined`
```

So i think we can close this out.
