### ISSUE TITLE
Emcc error while building .wasm

### ISSUE THREAD

**Issue by Lereena** [tree-sitter/tree-sitter#1039]
Hello. 
I have this error while building .wasm for [PascalABC.NET grammar](https://github.com/Lereena/tree-sitter-pascalabcnet):

```
npx tree-sitter build-wasm tree-sitter-pascalabcnet/

emcc command failed - emcc: error: '/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -DEMSCRIPTEN -fignore-exceptions -fno-inline-functions -fPIC -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=16 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -flegacy-pass-manager -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -Os -fno-exceptions -Isrc src/parser.c -c -o /tmp/emscripten_temp_6tps2fmd/parser_0.o' failed (-9)
```

It appears on tree-sitter-cli 0.18.* and 0.19.*
My OS: Ubuntu 20.04.2 LTS

**Comment by maxbrunsfeld** [comment]
There's not much to go on here. Maybe try running that command directly, and see if there is any additional output? If you can't learn any more, maybe open an issue on the [Emscripten](https://github.com/emscripten-core/emscripten) repository.

**Comment by Lereena** [comment]
I was unable to get additional output and run this command directly (because it runs on a temporary file), so I opened [an issue](https://github.com/emscripten-core/emscripten/issues/13960) on the Emscripten. 
People there are trying to help me get a more detailed description of the error, and now they asked me about what build system is used here, but I don't know. Can you please tell me which one? 
There must be some output from the clang before this error. Maybe there is a way to make tree-sitter not suppress intermediate logging?

**Comment by sbc100** [comment]
Is the stderr from emscripten somehow being swallowed or filtered here?  There should always be some kind of error message that proceeds the error that you are seeing here.  i.e. clang itself should have printed something to stderr.

**Comment by Lereena** [comment]
@maxbrunsfeld As a result, it turned out that this error was caused by emcc process killing caused by a lack of RAM. Could it be possible to somehow show a message about it to the tree-sitter user? 
(By the way, it turned out that really a lot of memory is required. I realize that my grammar is quite large, but 24 gigabytes. Wow :D)

**Comment by Lereena** [comment]
Yes, `src/parser.c` is about 25 megabytes in size and generated on quite complex grammar.

**Comment by sbc100** [comment]
Well I guess that makes sense then that clang would use crazy amounts of memory :)
