### ISSUE TITLE
\n should match line separators

### ISSUE THREAD

**Issue by joshvera** [tree-sitter/tree-sitter#105]
I _think_ \n should match unicode line separators such as http://www.fileformat.info/info/unicode/char/2028/index.htm.

**Comment by maxbrunsfeld** [comment]
I don't think this would match the ECMAScript regex spec -

```js
/\n/.test(String.fromCharCode(0x2028)) // => false
```

In general, since `\n` refers to a specific character (as opposed to a character class like `\s`), we probably need to interpret as meaning meaning *just* that one character.

**Comment by joshvera** [comment]
@maxbrunsfeld oh you’re right. Maybe this is just about line terminators in source code then http://www.ecma-international.org/ecma-262/6.0/#sec-line-terminators.

**Comment by maxbrunsfeld** [comment]
Yeah, we probably just need to handle that character like a `\n` in the JavaScript (and TypeScript) grammar.

**Comment by Arcanemagus** [comment]
Related to this: https://github.com/AtomLinter/linter-eslint/issues/746

Although fixing that issue is more than just tokenizing the code correctly.
