### ISSUE TITLE
Atom: Incompatible language version. Compatible range: 9 - 12. Got: 13

### ISSUE THREAD

**Issue by BonaBeavis** [tree-sitter/tree-sitter#1055]
I think this error should have his own issue.
Problem is that parsers build with tree-sitter 0.19 upwards have abi version 13, while atom is only compatible until abi 12.

Issue where the bug is mentioned: https://github.com/tree-sitter/tree-sitter/issues/966#issuecomment-813016444

Is updating atoms tree-sitter dependency the only solution, or can I build my language-turtle (which depende on tree-sitter-turtle build with 19.3) package in a way, that it targets the needed atom abi version?

**Comment by amaanq** [comment]
Closing since atom has been sunsetted
