### ISSUE TITLE
Java newline braces not showing code navigation

### ISSUE THREAD

**Issue by SuperRonanCraft** [tree-sitter/tree-sitter#1056]
So I've been trying to get this dev to change their coding style to not use newline braces, which tree-sitter does not support.
I was hoping to get support for this so this massive project written in Java can be supported to easily navigate around.
Here's the resource in question: https://github.com/TechFortress/GriefPrevention/tree/master/src/main/java/me/ryanhamshire/GriefPrevention

**Comment by ahelwer** [comment]
@SuperRonanCraft you probably want to file this issue with either the Java extension for whatever IDE you're using, or the Java language server it's using, or the Java tree-sitter grammar itself.

**Comment by SuperRonanCraft** [comment]
> @SuperRonanCraft you probably want to file this issue with either the Java extension for whatever IDE you're using, or the Java language server it's using, or the Java tree-sitter grammar itself.

What now??

**Comment by maxbrunsfeld** [comment]
This sounds like a tree-sitter-java issue. Can you reopen this on that repo, and give a specific code example that does not parse correctly?

**Comment by SuperRonanCraft** [comment]
The entire project doesn't have code navigation. Just take a look

**Comment by maxbrunsfeld** [comment]
Ok, I think this is a question for GitHub support, not a tree-sitter issue.
