### ISSUE TITLE
GLR parsing not triggering when precedence is defined

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/tree-sitter#1061]
Using tree-sitter-cli 0.19.4.

Consider a basic language consisting of a series of definitions:
```tla
foo == 1 + 2
bar == 3 + 4
```
Each definition is not delimited; this would not be a problem, except each `+` operator can be prefixed with a series of nested namespaces separated by `!` symbols to identify its origin:
```tla
foo == 1 a!b!c!+ 2
bar == 3 + 4
```
So now there's an obvious conflict with the following series of symbols:
```
identifier  '=='  _expr  •  identifier  …
```
Since the second identifier could either be a namespace prefix or the start of a new definition. No worries! Add a conflict to trigger GLR parsing. All is well.

Things become more complicated when additional infix operators need to be defined, beyond `+`. The `*` operator should have higher precedence than `+`, so this is specified using `prec.left(n, ...` where `n > 0` for both `+` and `*`. However, now for some reason GLR parsing doesn't trigger, and instead there's an error as the parser always assumes an identifier is part of a namespace prefix! Here's the full parser:

```js
function infixOpPrec(level, prefix, expr, symbol) {
  return prec.left(level, seq(
    field('lhs',    expr),
    field('prefix', repeat(prefix)),
    field('symbol', symbol),
    field('rhs',    expr)
  ))
}

module.exports = grammar({
  name: 'tlaplus',

  conflicts: $ => [
    [$.op_def, $.infix_op],
  ],

  rules: {
    source_file: $ => repeat($.op_def),

    op_def: $ => seq($.identifier, '==', $._expr),

    identifier: $ => /[A-Za-z]+/,

    _expr: $ => choice(
      $.number,
      $.infix_op
    ),

    number: $ => /\d+/,

    infix_op: $ => choice(
      infixOpPrec(10, $.instance_prefix, $._expr, $.add),
    ),

    add: $ => '+',

    instance_prefix: $ => seq($.identifier, '!'),
  }
});
```
Given the following file:
```tla
foo == 1 + 2
bar == 3 + 4
```
It will produce the following parse with an error:
```
(source_file [0, 0] - [1, 12]
  (op_def [0, 0] - [1, 12]
    (identifier [0, 0] - [0, 3])
    (infix_op [0, 7] - [1, 12]
      lhs: (infix_op [0, 7] - [0, 12]
        lhs: (number [0, 7] - [0, 8])
        symbol: (add [0, 9] - [0, 10])
        rhs: (number [0, 11] - [0, 12]))
      (ERROR [1, 0] - [1, 8]
        (identifier [1, 0] - [1, 3])
        (number [1, 7] - [1, 8]))
      symbol: (add [1, 9] - [1, 10])
      rhs: (number [1, 11] - [1, 12]))))
```
How do I force GLR parsing? I also can't just make `op_def` a higher precedence than any `infix_op`, because then tree-sitter always assumes that `instance_prefix` identifiers are actually the start of a new `op_def`.

**Comment by maxbrunsfeld** [comment]
I agree; it can be a very difficult to control where GLR is used when using the integer precedences. I recently added a new feature that makes this easier, but I haven't written docs for it yet. I described it in the body of this PR: https://github.com/tree-sitter/tree-sitter/pull/939 (and [this PR comment](https://github.com/tree-sitter/tree-sitter/pull/939#issuecomment-790143286)).

I think that this way of using precedence might make your problem easier to solve, but I'm not 100% sure I've understood the problem correctly. Maybe take a look at that feature, and let me know if you think that there's away to avoid the *accidental* precedence relationships that you're describing.

**Comment by ahelwer** [comment]
Thanks @maxbrunsfeld that seems like exactly what is needed! Precedence defined between different infix operators, but precedence not defined between infix operators and operator definitions.

I tried it out but it still seems not to trigger GLR parsing; I fear I might be doing something wrong. Here's the updated grammar:
```
function infixOpPrec(level, prefix, expr, symbol) {
  return prec.left(level, seq(
    field('lhs',    expr),
    field('prefix', repeat(prefix)),
    field('symbol', symbol),
    field('rhs',    expr)
  ))
}

module.exports = grammar({
  name: 'tlaplus',

  conflicts: $ => [
    [$.op_def, $.infix_op],
  ],

  precedences: () => [
    ['multiply', 'add']
  ],

  rules: {
    source_file: $ => repeat($.op_def),

    op_def: $ => seq($.identifier, '==', $._expr),

    identifier: $ => /[A-Za-z]+/,

    _expr: $ => choice(
      $.number,
      $.infix_op
    ),

    number: $ => /\d+/,

    infix_op: $ => choice(
      infixOpPrec('add', $.instance_prefix, $._expr, $.add),
      infixOpPrec('multiply', $.instance_prefix, $._expr, $.multiply),
    ),

    add: $ => '+',

    multiply: $ => '*',

    instance_prefix: $ => seq($.identifier, '!'),
  }
});
```
It will correctly parse this file:
```
foo = 1 * 2 + 3
```
So I know precedence is being defined at some level, but it still fails to parse the file I had a problem with above:
```
foo == 1 + 2
bar == 3 + 4
```
Error:
```
source_file [0, 0] - [2, 0]
  (op_def [0, 0] - [1, 12]
    (identifier [0, 0] - [0, 3])
    (infix_op [0, 7] - [1, 12]
      lhs: (infix_op [0, 7] - [0, 12]
        lhs: (number [0, 7] - [0, 8])
        symbol: (add [0, 9] - [0, 10])
        rhs: (number [0, 11] - [0, 12]))
      (ERROR [1, 0] - [1, 8]
        (identifier [1, 0] - [1, 3])
        (number [1, 7] - [1, 8]))
      symbol: (add [1, 9] - [1, 10])
      rhs: (number [1, 11] - [1, 12]))))
```
