### ISSUE TITLE
Mutate tree sitter AST from Rust? (Is tree sitter suitable for transformations/code instrumentation)

### ISSUE THREAD

**Issue by vedantroy** [tree-sitter/tree-sitter#1085]
I'm trying to use tree sitter to
- Parse source code into an AST
- Mutate the AST in certain places (for example, maybe inject a logging statement before every function call)
- Write the AST back to disk

Is this parse --> transform --> write use case supported well by tree sitter?

**Comment by ahlinc** [comment]
It's not supported, tree-sitter's nodes are immutable objects, this allows to share parsing trees  between threads and do tree traversals or run queries on trees in parallel, simultaneusly from multiple threads.

You may try to build your own serializable representation above tree-sitter's tree by making tree traversal after parsing.
