### ISSUE TITLE
How to prevent extras from matching in a string?

### ISSUE THREAD

**Issue by keidax** [tree-sitter/tree-sitter#1087]
I can't figure out how to allow comments in `extras` while keeping them out of strings. Here's a minimal grammar that shows the problem:
``` javascript
module.exports = grammar({
  name: 'crystal',

  extras: $ => [/\s/, $.comment],

  rules: {
    source_file: $ => repeat($._statement),

    _statement: $ => choice(
      $.string,
    ),

    comment: $ => /#.*\n/,

    string: $ => seq(
      '"',
      repeat(
        token.immediate(/./),
      ),
      token.immediate('"'),
    ),
  }
});
```

If I try to parse text such as
``` crystal
"string"
# comment
"#"
```
then the parser produces an error
```
(source_file [0, 0] - [3, 0]
  (string [0, 0] - [0, 8])
  (comment [1, 0] - [2, 0])
  (string [2, 0] - [3, 0]
    (comment [2, 1] - [3, 0])))
example.cr	0 ms	(MISSING """ [3, 0] - [3, 0])
```

This is a similar issue to https://github.com/tree-sitter/tree-sitter/issues/861, but the workaround there seems to require `$.comment` being an external. Is it possible to keep extras out of rules which aren't externals?

**Comment by alemuller** [comment]
You have to set the comment to have lower precedence than [conflicting tokens](https://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens).

```js
comment: $ => token(prec(-1,/#.*\n/)),
```

Also. You probably want
```
token.immediate(/[^"]/),
```

instead of
```
token.immediate(/./),
```

**Comment by keidax** [comment]
Your first suggestion works! I had tried setting a negative precedence, but I didn't realize it was necessary to use `token` as well. 

Could you explain why these rules don't work? I'm not sure how to reason about the order of composition.
``` javascript
    comment: $ => prec(-1, /#.*\n/),
```
``` javascript
    comment: $ => prec(-1, token(/#.*\n/)),
```

**Comment by theHamsta** [comment]
You probably want to end stings on line end (or can they be Multi-Line?) You could take the rule of tree-sitter-c

**Comment by keidax** [comment]
@alemuller When re-reading the documentation, I guess I missed this sentence:
> 2. Lexical Precedence - When the precedence functions described above _are used within the token function_, the given precedence values serve as instructions to the lexer.

So it seems that `prec(1, ...)` applies the precedence to the grammar rule, and `token(prec(1, ...))` applies the precedence in the lexer. Makes sense now.
