### ISSUE TITLE
wasm bindings don't work with emscripten 2.0.18

### ISSUE THREAD

**Issue by dcreager** [tree-sitter/tree-sitter#1088]
emscripten 2.0.18 was released recently, which causes a regression with our wasm bindings:

- before, [succeeds on 2.0.17](https://github.com/dcreager/tree-sitter-test/runs/2441087580):
- after, [fails on 2.0.18](https://github.com/dcreager/tree-sitter-test/runs/2441025964)

```
RuntimeError: function signature mismatch
    at <anonymous>:wasm-function[80]:0x16cb7
    at <anonymous>:wasm-function[131]:0x26333
    at ts_parser_parse_wasm (<anonymous>:wasm-function[243]:0x2d8fd)
    at Object.Module._ts_parser_parse_wasm (/home/runner/work/tree-sitter-test/tree-sitter-test/node_modules/web-tree-sitter/tree-sitter.js:1:18760)
    at Parser.parse (/home/runner/work/tree-sitter-test/tree-sitter-test/node_modules/web-tree-sitter/tree-sitter.js:1:33876)
    at /home/runner/work/tree-sitter-test/tree-sitter-test/index.js:13:10
```

I think the issue is [here](https://github.com/tree-sitter/tree-sitter/blob/fe5a29a1c64e011de570960ced069c7dab648d40/lib/binding_web/binding.js#L126), where we call `ts_parser_parse_wasm` with the wrong number of parameters.  @maxbrunsfeld, should we call a different function there to reset the parser state?

**Comment by maxbrunsfeld** [comment]
> I think the issue is here, where we call ts_parser_parse_wasm with the wrong number of parameters.

Wow, I'm not sure how that code could have ever worked. Maybe that was a typo and it was always intended to call [`ts_parser_reset`](https://github.com/tree-sitter/tree-sitter/blob/fe5a29a1c64e011de570960ced069c7dab648d40/lib/include/tree_sitter/api.h#L279-L288)?

**Comment by dcreager** [comment]
I could've sworn I did a quick search for something like `ts_parser_reset`, not sure why I didn't find it... :cold_sweat: 

I'll whip up a patch for that.
