### ISSUE TITLE
`tree-sitter generate` doesn't update cargo dependencies if binding exist

### ISSUE THREAD

**Issue by RRethy** [tree-sitter/tree-sitter#1093]
Due to [this check for existing rust bindings](https://github.com/tree-sitter/tree-sitter/blob/335190cc1d95baa7f9b50c4c4dee86173c46cc0a/cli/src/generate/binding_files.rs#L25), the `tree-sitter` dependency won't get upgraded to the most recent version which causes version mismatch for `tree_sitter::Language`. 

For example, [tree-sitter-dart](https://github.com/UserNobody14/tree-sitter-dart) has a Cargo.toml with `tree-sitter = "0.17.0"`, `tree-sitter generate` does not update this to `tree-sitter = "0.19.3"` which breaks using this parser with other parsers in the same crate.

**Comment by Razzeee** [comment]
I guess that might be best as an additional flag? Your probably looking to run this in CI too?

I still have custom made rust bindings from before https://github.com/elm-tooling/tree-sitter-elm/tree/main/rust and just overwriting them and getting rid of the additional stuff (just some tests in my case) would be frustrating.
But okay in my case, but I'm guessing, that there are people with more customized bindings out there.

**Comment by RRethy** [comment]
Not looking to run in CI, just looking to use the parsers as cargo dependencies in a rust crate, but some of them (fennel, haskell, kotlin, etc.) aren't using the same `tree_sitter::Language` type (because they're using an older version of tree-sitter) and so can't be used together.

**Comment by RRethy** [comment]
Dup of #1032
