### ISSUE TITLE
Can't use the parser

### ISSUE THREAD

**Issue by ghost** [tree-sitter/tree-sitter#1097]
Dear developers for tree sitter,
I ran into the following problem when I was trying to create my own language.
I ran the command` tree-sitter parse example-file`. But it seems to be that the tree-sitter-client was not able to load the corresponding dll.

```
Error opening dynamic library "C:\\Users\\zachn\\.tree-sitter\\bin\\treesitternlay.dll"
Details:
```

**Comment by ahlinc** [comment]
Could you provide more context?
Did you try to call it from a repo root folder of your language?
I'm not familiar with tree-sitter behaviour on the Win platform, but a name of the dll looks strange, I expect it shoud contain dashes in the name. Could you tell how your languge folder is named, cause there is a requirement for naming?
