### ISSUE TITLE
Question: Existing work on tree-sitter-sql

### ISSUE THREAD

**Issue by sfc-gh-pkommini** [tree-sitter/tree-sitter#1106]
Hi Community,

I was wondering if there is any ongoing work on building out a `tree-sitter-sql`. Also, is anyone aware of how one can take a textmate grammar and covert it to a tree-sitter grammar? What constructs in textmate grammar map to what constructs in tree-sitter grammar and what constructs do not map.

We wanted to start work tree-sitter-sql and would appreciate any guidance on this.

**Comment by ahlinc** [comment]
Except for [the main official documentation](https://tree-sitter.github.io/tree-sitter/#available-parsers), a good place to lookup what languages exist for tree-sitter is [a dependents list](https://github.com/tree-sitter/tree-sitter/network/dependents) on Insights tab. For the SQL there are [several](https://github.com/DerekStride/tree-sitter-sql) [options](https://github.com/tjdevries/tree-sitter-sql) [,](https://github.com/tk-shirasaka/tree-sitter-sql) but I can't tell anything about thees quality and completeness.

> Also, is anyone aware of how one can take a textmate grammar and covert it to a tree-sitter grammar? What constructs in textmate grammar map to what constructs in tree-sitter grammar.

TextMate grammars are regex-based with sophisticated regex rules and scopes capturing that isn't ideal and can't solve all language constructions, tree-sitter also can't solve everything correctly, I hope yet, like conditional pre processor directives in C language, but that's another story. IMO it's not feasible to make direct conversion, I'd didn't saw anything similar in the field, yet.

> We wanted to start work tree-sitter-sql and would appreciate any guidance on this.

It would be awesome to have SQL grammar for tree-sitter with conformance to SQL standards and support for parsing SQL flavors for popular DBMS. For inspiration you may look at how [Typescript grammar based on JS grammar](https://github.com/tree-sitter/tree-sitter-typescript/blob/master/common/define-grammar.js).

**Comment by sfc-gh-pkommini** [comment]
@ahlinc Thank you for your detailed response. I'll go through the material and try and contribute to one of those existing tree-sitter-sql options. 🙏

**Comment by ahlinc** [comment]
@sfc-gh-pkommini I'm not sure about quality and approaches in implementation for the mentioned language implementations. If you're going to build solid SQL parser on tree-sitter, I'd say it makes sense to estimate existing implementations and if they doesn't good for some parameters than may be it makes sense to start another one implementation from scratch with taking into account flaws of existing ones.

**Comment by sfc-gh-pkommini** [comment]
I've started conversations with the authors regarding the process and will try to understand what base SQL grammar they used for their implementation. I will fork/create from scratch if not on a solid foundation.

Right now the big piece I'm missing is how to make production rules from an existing grammar to tree-sitter grammar. Which grammar allows for such a mapping. I was able to find a ANSI compliant base grammar [here.](https://github.com/jgarzik/sqlfun/blob/master/sql.y) Do you think these production rules might help towards building the tree-sitter grammar from scratch?

**Comment by sfc-gh-pkommini** [comment]
Also, I wanted to understand how antlr4 grammars related to tree-sitter grammars. I think understanding this relationship might help folks contribute easily in terms of reducing the learning curve for tree-sitter grammar.

**Comment by ahlinc** [comment]
> I was able to find a ANSI compliant base grammar [here](https://github.com/jgarzik/sqlfun/blob/master/sql.y) (yacc & bison). Do you think these production rules might help towards building the tree-sitter grammar from scratch?

Yes, any **LR** implementations may be helpful in writing tree-sitter's analog. You may also look at PostgreSQL [grammar](https://github.com/postgres/postgres/blob/master/src/backend/parser/gram.y#L826) and it's [lexer](https://github.com/postgres/postgres/blob/master/src/backend/parser/scan.l) cause it uses _bison + flex_. MySQL's _yacc_ based [grammar](https://github.com/mysql/mysql-server/blob/8.0/sql/sql_yacc.yy#L2152) may also be helpful, but I'm not sure about their hand written [scanner](https://github.com/mysql/mysql-server/blob/8.0/sql/sql_lex.cc).

> Also, I wanted to understand how antlr4 grammars relate to tree-sitter grammars. I think understanding this relationship might help folks contribute easily in terms of reducing the learning curve for tree-sitter grammar.

Antlr4 relates to another class of **LL** parsers and I don't know an easy way how to map **LL** grammar to **LR** grammar, such conversion requires significant efforts cause even at the first look **LL** grammar [may look similar ](https://github.com/prestodb/presto/blob/master/presto-parser/src/main/antlr4/com/facebook/presto/sql/parser/SqlBase.g4#L33), but it uses anther than **LR** grammars approach in rules definition, where in each **LL** rule it's needed to enumerate all possible terminal continuations or if used another rule than it should start from a terminal in case of _LL(1_) grammar or all terminals should be not far than _N_ for _LL(N)_.
