### ISSUE TITLE
Workaround for webpack configuration

### ISSUE THREAD

**Issue by ZZYSonny** [tree-sitter/tree-sitter#1121]
Currently webpack does not have great support for wasm. When I use create-react-app, the wasm file does not seems to be properly loaded under default settings. I tried all configurations on the web (craco) but none of them worked.
![image](https://user-images.githubusercontent.com/28442838/119143160-df97aa80-ba79-11eb-9e22-f50fc2991bbe.png)
![image](https://user-images.githubusercontent.com/28442838/119143233-f2aa7a80-ba79-11eb-91ab-ac05b9281cc1.png)

Maybe we can workaround this issue by downloading the wasm via URL instead of local file? So no hassle on the webpack.

**Comment by ZZYSonny** [comment]
I have hacked the js to use cdn wasm instead of local wasm file. It works. No error message is shown.
![image](https://user-images.githubusercontent.com/28442838/119147082-d8729b80-ba7d-11eb-941d-41e0c43f7820.png)

I believe it is best done on the js source side instead of this hacky way.

**Comment by ZZYSonny** [comment]
BTW how can I query ERROR nodes with query?
![image](https://user-images.githubusercontent.com/28442838/119165675-5475df00-ba90-11eb-9084-2733e2409fe0.png)

**Comment by ahlinc** [comment]
You need to assign a capture name like `(ERROR) @error`

**Comment by ZZYSonny** [comment]
Sorry for the amount of question. How can I query "MISSING ;" here? It seems the query can not parse "MISSING ;" as a whole here.
![image](https://user-images.githubusercontent.com/28442838/119212497-6638a000-baeb-11eb-9eb5-404b4a6f2c31.png)

**Comment by Darkclainer** [comment]
To solve problem with wasm file loading with webpack I used following sollution:

1. Add wasm to webpack rules

```js
return {
        // ...
        module: {
            rules: [
                {
                    test: /\.wasm$/,
                    loader: "file-loader",
                    type: "javascript/auto",
                },
               // ...
            ],
         },
}
```

2. Use module options while initializing Parse module

```js
import Parser from 'web-tree-sitter';

import treeSitterWasmUrl from "web-tree-sitter/tree-sitter.wasm";

(async () => {
    const Module = {
        locateFile: (path, prefix) => {
            if (path === 'tree-sitter.wasm') {
                return treeSitterWasmUrl;
            }
            return '';
        },
    };
    await Parser.init(Module);
})();
```
