### ISSUE TITLE
tree-sitter-highlight 0.19.2 does not compile with tree-sitter 0.19.5

### ISSUE THREAD

**Issue by nitsky** [tree-sitter/tree-sitter#1122]
`tree-sitter` 0.19.4 contains a breaking change vs 0.19.3. The `QueryCaptures` struct now takes two generic lifetime arguments instead of one.

`QueryCaptures` in 0.19.4: https://docs.rs/tree-sitter/0.19.4/tree_sitter/struct.QueryCaptures.html
`QueryCaptures` in 0.19.3: https://docs.rs/tree-sitter/0.19.3/tree_sitter/struct.QueryCaptures.html

This broke my build when I ran `cargo update` on a codebase with the following in its `Cargo.toml`:

```
tree-sitter = "0.19"
tree-sitter-highlight = "0.19"
```

The latest published version of `tree-sitter` is 0.19.5 and the latest published version of `tree-sitter-highlight` is 0.19.2. `tree-sitter-highlight` 0.19.2 depends on the defintion of `QueryCaptures` from `tree-sitter` 0.19.2. Here is the compile error:

```
tree-sitter-highlight-0.19.2/src/lib.rs:104:30
104 |     captures: iter::Peekable<QueryCaptures<'a, &'a [u8]>>,
    |                              ^^^^^^^^^^^^^ -- supplied 1 lifetime argument
    |                              |
    |                              expected 2 lifetime arguments
```

Possible solutions:
* Publish `tree-sitter-highlight` with the latest code.
* Yank 0.19.4 and 0.19.5 and publish 0.20. 

I look forward to tree-sitter reaching 1.0!

**Comment by ahlinc** [comment]
@nitsky In the https://github.com/tree-sitter/tree-sitter/issues/1363#issuecomment-911163367 I've described a workaroud.

**Comment by ahlinc** [comment]
`tree-sitter-highlight` was updated to v0.20.0, so closing this.
