### ISSUE TITLE
tree-sitter-cli 0.19.5 does not build with docker

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#1124]
I usually use docker to build the wasm, not emmc

```
> @elm-tooling/elm-language-server@2.1.0 build-tree-sitter
> tree-sitter build-wasm ./node_modules/@elm-tooling/tree-sitter-elm


emcc was not found on PATH
```

This is using 
```
"tree-sitter-cli": "^0.19.5",
```

when I downgrade to 
```
"tree-sitter-cli": "^0.19.4",
```
I can build successfully again.

**Comment by ahlinc** [comment]
@Razzeee As temporary workaround with the 0.19.5 version you may call wasm building with `--docker` flag.
