### ISSUE TITLE
On ERROR, parser stops and doesn't proceed further, when external scanner is present.

### ISSUE THREAD

**Issue by ganezdragon** [tree-sitter/tree-sitter#1128]
hi developers and maintainers,

I'm developing a parser for perl using tree-sitter (repo mentioned below).  It all works great, I have been writing the grammar one by one.

But lately I'm facing a issue, when there is a `ERROR` while parsing a perl code, the parser just stops there and exits for that file. Upon debugging, I found that it is due to presence of  external scanners. And when I comment that out, It just works back again. And particularly, it is because of `lexer->advance(lexer, false);`. Even though the externals are not called, it just goes inside `if (valid_symbols[ANYTHING]) {`. condition.

Repository - https://github.com/ganezdragon/tree-sitter-perl
Sample perl code:
```
sub something {
  print "something logging here";
  my $string = '', # should be semi colon expected instead of comma

  print "but parser doesnt reach here";
}
```
Error I'm getting:
```
tree-sitter parse examples/test.pl
(source_file [1, 0] - [9, 0]
  (ERROR [1, 0] - [9, 0]
    (identifier [1, 4] - [1, 13])
    (variable_declaration [2, 2] - [2, 17]
      (scope [2, 2] - [2, 4])
      (single_var_declaration [2, 5] - [2, 11]
          name: (scalar_variable [2, 5] - [2, 11]))
      value: (special_variable [2, 14] - [2, 16])
      (semi_colon [2, 16] - [2, 17]))
    (call_expression [3, 2] - [3, 30]
      function_name: (identifier [3, 2] - [3, 7])
      args: (argument [3, 8] - [3, 30]
        (string_double_quoted [3, 8] - [3, 30])))
    (semi_colon [3, 30] - [3, 31])
    (scope [4, 2] - [4, 4])
    (single_var_declaration [4, 5] - [4, 12]
        name: (scalar_variable [4, 5] - [4, 12]))
    value: (string_single_quoted [4, 15] - [4, 17])))
examples/test.pl        0 ms    (ERROR [1, 0] - [9, 0])
```
Notice that the parser stops at line 4 itself.

Can someone please help me out here?

**Comment by maxbrunsfeld** [comment]
You may need to change the logic in your external scanner to make sure that your code doesn't cause problems in the case of an error. Right after an error, the scanner will get called with every `valid_symbols` entry set to `true`. Depending on what kind of logic you have in your `scan` function, you may need to add special logic to *prevent*  certain code paths from executing if every external scanner is valid.

**Comment by ganezdragon** [comment]
Okay that explains it. Let me put up a logic and get back here!

**Comment by ganezdragon** [comment]
Fixed it by adding a if condition for all `valid_symbols` to be true.

```
if (
        valid_symbols[START_DELIMITER]
        && valid_symbols[END_DELIMITER]
        && valid_symbols[STRING_CONTENT]
        && valid_symbols[STRING_SINGLE_QUOTED_CONTENT]
        && valid_symbols[STRING_QQ_QUOTED_CONTENT]
        && valid_symbols[POD_CONTENT]
) {
        return false;
}
```

For my usecase, none of the above tokens would be true at the same time. So this logic works best for me.

@maxbrunsfeld , thank you for the help :) Please feel free to close the issue.

**Comment by maxbrunsfeld** [comment]
Awesome!
