### ISSUE TITLE
web-tree-sitter parser.parse exits abruptly

### ISSUE THREAD

**Issue by ganezdragon** [tree-sitter/tree-sitter#1129]
hi developers, maintainers,

I'm using `web-tree-sitter` to load a `.wasm` binding file of perl created from here - https://github.com/ganezdragon/tree-sitter-perl

And I'm using this in a vs code extension here - https://github.com/ganezdragon/perl-language-server/blob/master/server/src/analyzer.ts#L46

I have faced this issue before, wherein, when I try to load a huge workspace (50k per files), the parser just fails. And I have fixed it earlier by using a `tree.delete()` (I guessed it from lot of trial and error)

Now I have updated my perl parser with new `.wasm` file, and I'm again facing this issue. And this time, `tree.delete()` doesn't fix the issue.

Some info:

- Nodejs version - v10.19.0
- Environment - Linux
- web-tree-sitter - 0.19.3
- tree-sitter-cli - 0.19.4
- Note: **vscode server just resets the connection, and no readable error is thrown**

I'm guessing this could be something related to memory handling, since it is working perfectly for a smaller workspace (maybe 100 files)

Can someone help me out here? Hope this is a known issue.

**Comment by ahlinc** [comment]
As temporary workaround I'd suggest to try to create the parser instance per parsing task.
A set of problems within the WASM binding pushed me to switch to other binding option.
To try to debug this I'd suggest to try to enable tree-sitter parser logging and write it to a file to see at least what last happened in the parser.

**Comment by ganezdragon** [comment]
@ahlinc , so how do we enable parser logging? I couldn't find it in the docs before.

**Comment by ahlinc** [comment]
You need to implement an own logging function and pass it to the parser.

_For WASM:_
```ts
const Parser = require('web-tree-sitter') as WasmParser;
const parser = new Parser();
const logger: WasmParser.Logger = (message, isLexMessage) => {
    let type = isLexMessage ? 'lex' : 'parse';
    if (type === 'lex') type += '  ';
    console.log(type, message);
}
parser.setLogger(logger);
```
_For node.js:_
```ts
const Parser = require('tree-sitter') as NodeParser;
const parser = new Parser();
const logger: NodeParser.Logger = (message, params, type) => {
    if (type === 'lex') type += '  ';
    console.log(type, message, Object.entries(params).map(([k, v]) => `${k}:${v}`).join(', '));
}
parser.setLogger(logger);
```

**Comment by ganezdragon** [comment]
okay let me try this out and get back!

**Comment by ganezdragon** [comment]
@ahlinc , after a combination of a debugger and using the logger object as you mentioned above, I could see the following output at the very end,

```
"shift state:2280"
"process version:0, version_count:1, state:2280, row:92, col:0"
"reduce sym:string_qq_quoted_repeat1, child_count:2"

```

And this is printing on and on in a loop until the server dies. 

I see that there is a string_qq_quoted token that I'm expecting in line no 37, and that this source file has row number 92 in total. Apart from this, I couldn't figure out anything from the logs.

The entire file for reference:
```
package Devel::REPL::Plugin::LexEnv;

use Devel::REPL::Plugin;
use namespace::autoclean;
use Lexical::Persistence;

sub BEFORE_PLUGIN {
    my $self = shift;
    $self->load_plugin('FindVariable');
}

has 'lexical_environment' => (
  isa => 'Lexical::Persistence',
  is => 'rw',
  required => 1,
  lazy => 1,
  default => sub { Lexical::Persistence->new }
);

has '_hints' => (
  isa => "ArrayRef",
  is => "rw",
  predicate => '_has_hints',
);

around 'mangle_line' => sub {
  my $orig = shift;
  my ($self, @rest) = @_;
  my $line = $self->$orig(@rest);
  my $lp = $self->lexical_environment;
  # Collate my declarations for all LP context vars then add '';
  # so an empty statement doesn't return anything (with a no warnings
  # to prevent "Useless use ..." warning)
  return join('',
    'BEGIN { if ( $_REPL->_has_hints ) { ( $^H, %^H ) = @{ $_REPL->_hints } } }',
    ( map { "my $_;\n" } keys %{$lp->get_context('_')} ),
    qq{{ no warnings 'void'; ''; }\n},
    $line,
    '; BEGIN { $_REPL->_hints([ $^H, %^H ]) }',
  );
};

around 'execute' => sub {
  my $orig = shift;
  my ($self, $to_exec, @rest) = @_;
  my $wrapped = $self->lexical_environment->wrap($to_exec);
  return $self->$orig($wrapped, @rest);
};

# this doesn't work! yarg. we now just check $self->can('lexical_environment')
# in FindVariable

#around 'find_variable' => sub {
#  my $orig = shift;
#  my ($self, $name) = @_;
#
#  return \( $self->lexical_environment->get_context('_')->{$name} )
#    if exists $self->lexical_environment->get_context('_')->{$name};
#
#  return $orig->(@_);
#};

1;

__END__

=head1 NAME

Devel::REPL::Plugin::LexEnv - Provide a lexical environment for the REPL

=head1 SYNOPSIS

 # in your re.pl file:
 use Devel::REPL;
 my $repl = Devel::REPL->new;
 $repl->load_plugin('LexEnv');

 $repl->lexical_environment->do(<<'CODEZ');
 use FindBin;
 use lib "$FindBin::Bin/../lib";
 use MyApp::Schema;
 my $s = MyApp::Schema->connect('dbi:Pg:dbname=foo','broseph','elided');
 CODEZ

 $repl->run;

 # after you run re.pl:
 $ warn $s->resultset('User')->first->first_name # <-- note that $s works

=cut

```

@ahlinc , could you help me figure out from the above log messages ?

**Comment by ganezdragon** [comment]
And if I comment out the `qq{{ no warnings 'void'; ''; }\n},` in line 37, it doesn't go into the loop, and it works just fine.

But ideally `parse` should have returned successfully for this token.

**Comment by ahlinc** [comment]
It hard to say something definitely, I suspect there some issue [in the external scanner](https://github.com/ganezdragon/tree-sitter-perl/blob/master/src/scanner.cc#L103). But I can't reproduce your issue with your latest grammar:
```sh
git clone https://github.com/ganezdragon/tree-sitter-perl
cd tree-sitter-perl
npm i
npm i --no-save tree-sitter-cli
time npx tree-sitter generate
npx tree-sitter build-wasm
npx tree-sitter web-ui
```
In the opened playground I've put your file example and it parses without crashes.
But I see many `ERROR` nodes in multiple places, so it seems there are many other parsing issues.
Regarding the line 37, I see such repetitions in the log mentioned by you:
```log
process version:0, version_count:1, state:2275, row:37, col:7
lex_external state:2, row:37, column:7
  consume character:'{'
lexed_lookahead sym:_string_qq_quoted_content, size:1
shift state:2273
process version:0, version_count:1, state:2273, row:37, col:8
lex_external state:2, row:37, column:8
  consume character:' '
lexed_lookahead sym:_string_qq_quoted_content, size:1
shift state:2250
process version:0, version_count:1, state:2250, row:37, col:9
lex_external state:2, row:37, column:9
  consume character:'n'
lexed_lookahead sym:_string_qq_quoted_content, size:1
reduce sym:string_qq_quoted_repeat1, child_count:2
shift state:2250
process version:0, version_count:1, state:2250, row:37, col:10
lex_external state:2, row:37, column:10
  consume character:'o'
lexed_lookahead sym:_string_qq_quoted_content, size:1
reduce sym:string_qq_quoted_repeat1, child_count:2
shift state:2250
process version:0, version_count:1, state:2250, row:37, col:11
lex_external state:2, row:37, column:11
  consume character:' '
lexed_lookahead sym:_string_qq_quoted_content, size:1
reduce sym:string_qq_quoted_repeat1, child_count:2
shift state:2250
process version:0, version_count:1, state:2250, row:37, col:12
lex_external state:2, row:37, column:12
  consume character:'w'
lexed_lookahead sym:_string_qq_quoted_content, size:1
reduce sym:string_qq_quoted_repeat1, child_count:2
shift state:2250
process version:0, version_count:1, state:2250, row:37, col:13
lex_external state:2, row:37, column:13
  consume character:'a'
lexed_lookahead sym:_string_qq_quoted_content, size:1
```
But these aren't endless there just a lot of the same repetitions because external lexer produces `_string_qq_quoted_content` token for every single char in the interpolation on the line 37, I suppose this happens cause the external scanner on line [180](https://github.com/ganezdragon/tree-sitter-perl/blob/master/src/scanner.cc#L180) doesn't advance lexer to consume all characters between delimiters in a loop. And I suppose It's not expected behavior.

**Comment by ganezdragon** [comment]
@ahlinc I didn't know the playground could be spawned that way.. Let me try this out.

Yea those `ERROR`s are expected, since those token are not implemented yet in the grammar, but that should stop web-tree-sitter from working.

Also from your logs I could see either the row or col is getting incremented `process version:0, version_count:1, state:2250, row:37, col:13`. But in my logs, the row and col is always the same, which seems the parser is stuck in a single cursor point.

So as you said, it could be the problem with the external scanner. So let me try something out and get back with more information.

Thanks for the analysis, much appreciated.

**Comment by ganezdragon** [comment]
@ahlinc , you were right, the problem was with line [180](https://github.com/ganezdragon/tree-sitter-perl/blob/018270837ec4caf4756e7a7cede0a9f4aa120a36/src/scanner.cc#L180). The advance was simply trying to advance even if there is no character in the lookahead.

So added the following simple logic
```
if (!lexer->lookahead) {
    lexer->mark_end(lexer);
    return false;
}
```

And it worked :)

Thank you a lot. This was really helpful. Please feel free to close this issue.

**Comment by maxbrunsfeld** [comment]
Glad you got it working @ganezdragon. Awesome debugging work @ahlinc.
