### ISSUE TITLE
clang "uninitialized" warnings on `error_start_position` etc. in `parser__lex`

### ISSUE THREAD

**Issue by gnprice** [tree-sitter/tree-sitter#113]
When building tree-sitter, I get a 75-line block of clang warnings that look like this:
```
In file included from ../vendor/tree-sitter/src/runtime/length.h:6:0,
                 from ../vendor/tree-sitter/src/runtime/tree.h:11,
                 from ../vendor/tree-sitter/src/runtime/stack.h:9,
                 from ../vendor/tree-sitter/src/runtime/parser.h:8,
                 from ../vendor/tree-sitter/src/runtime/parser.c:1:
../vendor/tree-sitter/src/runtime/parser.c: In function ‘parser__get_lookahead’:
../vendor/tree-sitter/src/runtime/point.h:22:12: warning: ‘error_end_position.extent.column’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     return point__new(0, a.column - b.column);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vendor/tree-sitter/src/runtime/parser.c:322:32: note: ‘error_end_position.extent.column’ was declared here
   Length error_start_position, error_end_position;
                                ^~~~~~~~~~~~~~~~~~
[...]
```
where the rest are the same thing for different fields of `error_end_position` and its friend `error_start_position`.

Looking closer, it takes only a minute to see in the code that these definitely (unless I'm missing something clang is seeing!) can't actually be used uninitialized. The only place these fields can be used is here:
```
  if (skipped_error) {
    Length padding = length_sub(error_start_position, start_position);
    Length size = length_sub(error_end_position, error_start_position);
    [...]
```
and the only place `skipped_error` gets set to true is immediately followed by initializing these variables.

But this sure is some spew from the compiler -- which makes the build look less solid than it is, and also if clang were to start warning about something else, this could mask that. So it'd be great to work out how to satisfy the uninitialized-checker, or to tell it to ignore this particular spot.

**Comment by maxbrunsfeld** [comment]
Thanks for raising this. I came to the same conclusion that you did, and was just putting off dealing with it.
