### ISSUE TITLE
WASM library fails to build with emscripten 2.0.23, 2.0.24

### ISSUE THREAD

**Issue by carlocab** [tree-sitter/tree-sitter#1131]
Running `./script/build-wasm` from the tree-sitter 0.19.5 tarball with emscripten 2.0.23 produces the following error:

```
emcc: error: undefined exported symbol: "__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_" [-Wundefined] [-Werror]
```

This occurs on macOS Mojave (10.14.6), Catalina (10.15.7) and Big Sur (11.3.1, both Intel and ARM). See https://github.com/Homebrew/homebrew-core/pull/78307.

Build logs available at https://github.com/Homebrew/homebrew-core/actions/runs/887494523. The error on Intel Big Sur starts at https://github.com/Homebrew/homebrew-core/runs/2699349013?check_suite_focus=true#step:7:62.

**Comment by carlocab** [comment]
Not that this should come as a surprise to anybody, but trying to build with emscripten 2.0.24 also fails with what looks to be the same error. See Homebrew/homebrew-core#79571.

**Comment by ahlinc** [comment]
@carlocab FYI, there is a PR with a workaround: https://github.com/tree-sitter/tree-sitter/pull/1180
You may find more info with context here: https://github.com/tree-sitter/tree-sitter/issues/1179#issuecomment-863863576

**Comment by carlocab** [comment]
Thanks for the hint. I had been thinking about building with an older version of Emscripten.

Though I suspect it'll be more likely that we'll just stop shipping the WASM library entirely, as anyone interested in using it shouldn't have any trouble compiling it on their own.

My only hesitation here is that it seems that what features are enabled in the CLI depends on whether you've built the WASM library before the CLI, so not shipping the WASM library probably entails disabling some features of the CLI. (But, again, I imagine the CLI is of interest only to those who wouldn't have trouble building this all for themselves.)
