### ISSUE TITLE
[Question] How to run query and see logs in the playground

### ISSUE THREAD

**Issue by Symbolk** [tree-sitter/tree-sitter#1133]
The playground is nice to quickly see the parsing results! However, as there are two check boxes `Log` and `Query`, it is confusing how to use them. Obviously, when check the `Log`, nothing happens; when checking the `Query`, there is an input box for query, but typing queries results into nothing! 

I tried Chrome and Safari, hopefully it is a browser-issue but it is not. Maybe it is better to have a `Run Query` button and highlight the matches?

![image](https://user-images.githubusercontent.com/14107297/120164285-fe8dfd80-c22c-11eb-908f-4cf77646e28d.png)

**Comment by ahlinc** [comment]
Yep, it's confusing, the log writes to a browser's devtools log. Queries highlight by underscores issues in it and to see results as highlighted parts in the source you need to assign `@capture.names` to interested parts of the query.

**Comment by Symbolk** [comment]
> Yep, it's confusing, the log writes to a browser's devtools log. Queries highlight by underscores issues in it and to see results as highlighted parts in the source you need to assign `@capture.names` to interested parts of the query.

Brilliant! Now I get it. A doc is really in need for a friendly playground.
![image](https://user-images.githubusercontent.com/14107297/120167080-e66bad80-c22f-11eb-9e4d-a0c39091e5e9.png)

**Comment by ahlinc** [comment]
I also thought that way at the beginning, but the button wouldn't be better because TS playground is fully interactive and all things recompute on every key stroke. But I agree that it requires improvements to be less confusing.

**Comment by calicoday** [comment]
A paragraph of plain text at the top of the playground page describing what you can do and expect to see would be a big help. Underline is sufficient marking if you know to look for it but I really didn't think it was working (in Chrome. In my very old safari, the page shows nothing at all and for a week I thought the playground must be planned but not yet implemented).

**Comment by ahlinc** [comment]
I'm closing this issue cause the main question was answered and the last suggestion will be handled in #1305.

**Comment by FFdhorkin** [comment]
I think the playground's query might be broken. Clicking on code chunks does select the corresponding spot in the tree, but even a query with a capture doesn't seem to do anything, and even with log enabled, I don't see anything in my dev console.

It does seem to validate the query (since I get an underline if I have something invalid), but it doesn't underline or highlight matching elements in the tree as described above.

![image](https://github.com/tree-sitter/tree-sitter/assets/59899746/b23ee3ca-cad4-43e6-8d5e-621e53b9507c)

**Comment by Bennet-Sunder** [comment]
@ahlinc @Symbolk 

Maybe I'm not reading the thread right. But is viewing the currently captured variable supported in tree sitter playground. Have been using this for a while and still not able to figure it out. 

<img width="1728" alt="image" src="https://github.com/tree-sitter/tree-sitter/assets/55491132/1d1cd0ba-ef25-4382-8f8e-2623858c4147">
