### ISSUE TITLE
Generate simple markdown parser

### ISSUE THREAD

**Issue by danymat** [tree-sitter/tree-sitter#1139]
I'm in the process of creating an lsp for Zettelkasten, which uses markdown for creating notes, and links with the format `[[link here]]` in order to link to a other note.

I want to create a tree-sitter rule that will try to find the links. I created this:

```
 module.exports = grammar({ 
     name: 'Zettelkasten',

     rules: {
     ¦   source_file: $ => repeat($._markdown_definition),

     ¦   _markdown_definition: $ => choice(
     ¦   ¦   $.link,
     ¦   ¦   $.text
     ¦   ),

     ¦   link: $ => seq(
     ¦   ¦   '[[',
     ¦   ¦   $.text,
     ¦   ¦   ']]'
     ¦   ),

     ¦   text: $ => prec.left(2,repeat1($._word)),

     ¦   _word: $ =>  /\w+/,

     }
 });
```

But testing here:

```
[[salut]]
[[salut]]
[[salut jes suis ]]
tjon pere
```

I get this

```
(source_file [0, 0] - [4, 0]
  (link [0, 0] - [0, 9]
    (text [0, 2] - [0, 7]))
  (link [1, 0] - [1, 9]
    (text [1, 2] - [1, 7]))
  (link [2, 0] - [2, 19]
    (text [2, 2] - [2, 16]))
  (text [3, 0] - [3, 4])
  (text [3, 5] - [3, 9]))
```

I don't know why the last line has `text text`. Can somebody help me? Is this grammar a correct one?

**Comment by ahlinc** [comment]
Try to rewrite the `text` rule as:
```js
text: $ => prec.left(2,seq(repeat1($._word))),
```

**Comment by danymat** [comment]
Hello @ahlinc , I tried to rewrite text with this rule
> ```js
> prec.left(2,seq(repeat1($._word))),
> ```

And I still get the same thing. I still don't get it

**Comment by danymat** [comment]
I thought about doing a simple grammar similar to this one but only fetching the link, and all the things that are not links are junk. Like this:

```
junk
link
junk 
```

Is it possible to do?

**Comment by ahlinc** [comment]
**For your first question:**
You need to give a reason for the parser to be greedy that is what `$._LF` doing or instead the parser will cycle over first `repeat` in the `source_file` rule by consuming only one `_word` cause it satisfies your initial grammar.
```js
module.exports = grammar({
    name: 'Zettelkasten',

    rules: {
        source_file: $ => repeat($._markdown_definition),

        _markdown_definition: $ => choice(
            $.link,
            $._text,
        ),

        link: $ => seq(
            '[[',
            $.text,
            ']]'
        ),

        _LF: $ => "\n",
        _text: $ => seq($.text, $._LF),
        text: $ => prec.left(2, repeat1($._word)),

        _word: $ => /\w+/,

    }
});
```
![Screenshot from 2021-06-06 03-06-57](https://user-images.githubusercontent.com/14666676/120908587-546f0500-c674-11eb-8abb-be9662ea299d.png)

---

**For the second question:**
```js
module.exports = grammar({
    name: 'Zettelkasten',

    rules: {
        source_file: $ => repeat($._markdown_definition),

        _markdown_definition: $ => choice(
            $.link,
            $._junk,
        ),

        link: $ => seq(
            '[[',
            alias($._text, $.text), // Replace this to the "$._text" to throw away `text` nodes under the `link` nodes.
            ']]'
        ),

        _LF: $ => "\n",
        _junk: $ => seq($._text, $._LF),
        _text: $ => prec.left(2, repeat1($._word)),

        _word: $ => /\w+/,

    }
});
```

![Screenshot from 2021-06-06 03-08-07](https://user-images.githubusercontent.com/14666676/120908603-7cf6ff00-c674-11eb-8571-5e1e6614e6df.png)

**Comment by ahlinc** [comment]
@maxbrunsfeld I think this issue can be closed, as I see @danymat [choose](https://github.com/danymat/tree-sitter-zettelkasten/blob/72c353671691f2e6564bc88dbf5aa10e3971eb53/grammar.js) second proposed option.

**Comment by ahlinc** [comment]
By the way, I was curious what is Zettelkasten and it looks interesting and useful. @danymat you may ask any related questions in [Q&A](https://github.com/tree-sitter/tree-sitter/discussions/categories/q-a) section in the [Discussions](https://github.com/tree-sitter/tree-sitter/discussions) tab of this repo.

**Comment by danymat** [comment]
> @maxbrunsfeld I think this issue can be closed, as I see @danymat [choose](https://github.com/danymat/tree-sitter-zettelkasten/blob/72c353671691f2e6564bc88dbf5aa10e3971eb53/grammar.js) second proposed option.

Oh yes sorry, I was busy this week I didn't have time to respond.
Thank you a lot for your help

> By the way, I was curious what is Zettelkasten and it looks interesting and useful. @danymat you may ask any related questions in [Q&A](https://github.com/tree-sitter/tree-sitter/discussions/categories/q-a) section in the [Discussions](https://github.com/tree-sitter/tree-sitter/discussions) tab of this repo.

Zettelkasten is a way for me to take notes. It allows random creativity to flow because the structure of the notes are based on links between notes rather than being grouped by folder (or whatever). You can checkout out this link for some insight: https://zettelkasten.de/posts/overview/
I did manage to create a simple lap for it: https://github.com/danymat/lsp-zettelkasten, but at the moment without tree-sitter features
