### ISSUE TITLE
[Question] How to build autocomplete feature using tree-sitter ?

### ISSUE THREAD

**Issue by KShivendu** [tree-sitter/tree-sitter#1144]
Hi,
I'm working on a project which is about building a custom search query language and keeping it accessible. This custom search query language has to be translated to Elasticsearch DSL and while writing the system should have autocomplete feature to guide the users. I could find some similar projects using ANTLR but I would prefer to build it using tree-sitter. 

I'm a beginner when it comes to building parsers and autocomplete features. So forgive me if I missed something obvious. Please comment below if you have any idea/resources about how to implement it using tree-sitter :)

Thank you

**Comment by Razzeee** [comment]
Well, you can use tree-sitter to access the tokens in your code. But you will need to handle which completions are valid at any given time. So this is only slightly connected to tree-sitter in the end.

I basically do it like this:
1. Parse all my files with tree-sitter
2. Collect some more data like imports and how files relate to each other
3. Access the collected data to output completions via the language server protocol
