### ISSUE TITLE
Update regex parser

### ISSUE THREAD

**Issue by rewinfrey** [tree-sitter/tree-sitter#115]
Today the regex parser looks for `\a` and parses this as `[a-zA-Z]`. Unfortunately this is a bit misleading as `\a` matches against an alert or bell character (reference: https://www.regular-expressions.info/refcharclass.html).

I haven't done an exhaustive check of tree-sitter language repos this will impact, but will impact Python's [grammar.js](https://github.com/tree-sitter/tree-sitter-python/blob/master/grammar.js#L774).

**Comment by Arcanemagus** [comment]
Actually, `\a` isn't a valid escape code for ECMAScript RegExp, the flavor of RegExp [used here](https://github.com/tree-sitter/tree-sitter/blame/fbcefe25f742437c78acb1b21d4e02b9f9ba859a/README.md#L115). So you could argue the fact that it's matching anything other than `a` (useless escape of `a`) is the bug...

**Comment by maxbrunsfeld** [comment]
Yeah, we should simply delete the code that you linked. I don't know what gave me the idea that `\a` had special meaning in a ECMAScript regex.
