### ISSUE TITLE
Missing nodes for tokens matched by patterns (as of tree-sitter 0.19)

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter#1151]
In the CST accessible via the C API, tokens that match a pattern construct (e.g. `/[a-z]+/`) don't produce a node. However, constants like `'goto'` do, as do named rules like `$.expression`.

Other constructs (`seq()`, `choice()`, ...) in general don't produce a node either, which in ocaml-tree-sitter we [recover by complex means](https://github.com/returntocorp/ocaml-tree-sitter/blob/1f2675b07b74730c80f9d59b8ec986e525db2d3c/doc/parsing.md). Unfortunately we don't have a way to recover the token matched by a pattern efficiently. The way we solve this is by rewriting `grammar.json` by creating a rule for each pattern, with an automatically-generated name. For example, an occurrence of `/[a-z]+/` anywhere but at the root of a rule is replaced by something like `$.pat_21098ba8` and we add the rule `pat_21098ba8: $ => /[a-z]+/`.

A few remarks:
1. I'm not aware of a convenient way to print the CST in a complete fashion using the `tree-sitter` command. Having json output from a command like `tree-sitter parse foo.ext --json` would be awesome for us users of the C API. It would make it easier to report this issue. Or maybe extending `-x` with XML elements to represent individual tokens could work as well. See #1154. 
2. Our workaround consisting in introducing a rule for each pattern has been working for us so far, which makes this issue a lower priority as far as I'm concerned.

Here's a sample grammar:
```
// grammar.js
module.exports = grammar({
  name: 'debug',
  rules: {
    program: $ => choice(
      'a',  // ok
      /b/,  // missing node
    ),
  }
});
```
Commands:
```
$ cat a.in


  a


$ cat b.in


  b


$ tree-sitter generate
$ tree-sitter parse a.in -x
(program [2, 2] - [5, 0])
<program>a


</program>

$ tree-sitter parse b.in -x
(program [2, 2] - [5, 0])
<program>b</program>

```
Note that the whitespace in the XML output differs between inputs `a.in` and `b.in` but this doesn't tell us much.

Here's the json output we get from our own program that uses the C API is the following for `a.in`:
```
{
  "type": "program",
  "startPosition": { "row": 2, "column": 2 },
  "endPosition": { "row": 5, "column": 0 },
  "children": [
    {
      "type": "a",
      "startPosition": { "row": 2, "column": 2 },
      "endPosition": { "row": 2, "column": 3 },
      "kind": [ "Literal", "a" ],
      "id": 1
    }
  ],
  "kind": [ "Name", "program" ]
}
```

For `b.in` we get:
```
{
  "type": "program",
  "startPosition": { "row": 2, "column": 2 },
  "endPosition": { "row": 5, "column": 0 },
  "children": [],
  "kind": [ "Name", "program" ]
}
```
^ Like for `a.in`, we would like one child that represents the token `b` matched by the pattern `/b/`, together with an unambiguous identifier for the pattern. The `"kind"` and `"id"` nodes are added by our program, but other nodes are faithful to the C API. The distinction between `Literal` (constant like `'a'`) and `Name` (rule name like `$.a`) is important; this is currently inferred from the presence or absence of children. Similarly, we'd need to be able to determine if a node is pattern. Our `kind` field for this would be something like `[ "Pattern", "[a-z]+" ]`. A node matched by a pattern would look close to this:
```
    {
      "type": "[a-z]",
      "startPosition": { "row": 2, "column": 2 },
      "endPosition": { "row": 2, "column": 3 },
      "kind": [ "Pattern", "[a-z]+" ]
    }
```
`"kind": [ "Pattern", "[a-z]+" ]`, if not provided by the C API, would have to be somehow provided by the other fields. It is not the case right now since `"type"` alone is ambiguous.

**Comment by mjambon** [comment]
It's possible that it's an oversight is in the [ocaml bindings to the C API](https://github.com/onivim/reason-tree-sitter/blob/master/src/bindings.c) or our use of it. Without a complete dump of the tree from an official tool (`tree-sitter parse`), it's hard to tell. I'm creating a ticket for this.

**Comment by ahlinc** [comment]
@mjambon I've mentioned about a new tree rendering in https://github.com/tree-sitter/tree-sitter/issues/1154#issuecomment-858150403, may be it will be useful for your investigation even in its current state.

**Comment by mjambon** [comment]
@ahlinc it's beautiful! Here's the output I get for the examples above:

![image](https://user-images.githubusercontent.com/343265/121449107-f67d3e80-c94d-11eb-9677-a4388fb5963e.png)

**Comment by mjambon** [comment]
Here's a potential workaround that allows patterns to stay inline and have a node in the CST:
```
// grammar.js
//
// Demonstrate the use of an alias to obtain a node where a token matches
// a pattern (regexp) while keeping it inline.
//
//   $ tree-sitter generate
//   $ tree-sitter parse <(echo 'c')
//   (program [0, 0] - [1, 0]
//     (c [0, 0] - [0, 1]))
//
module.exports = grammar({
  name: 'pattern_alias',
  rules: {
    program: $ => choice(
      'a',              // ok
      /b/,              // missing node
      alias(/c/, $.c),  // ok
    ),
    c: $ => /c/,  // could as well be anything on the right-hand side
  }
});
```

Using `alias(/c/, $.c)` rather than just `$.c` keeps the pattern inline. This is important to avoid changing the parsing semantics, which happens in some cases.

**Comment by amaanq** [comment]
I would say this is intentional - I don't think exposing patterns as their own token-like rule in the APIs makes much sense, since they should, in general, belong to a node that is visible (e.g. identifier, string_content, etc), so you can then get the text from *that* node. There is also a `-c` flag merged in master that does have "pretty printing" to easily debug this, so I'll consider this resolved.
