### ISSUE TITLE
[Question] Operator Nodes

### ISSUE THREAD

**Issue by tinygiant98** [tree-sitter/tree-sitter#1155]
I created a grammar for a new language and successfully parsed and highlighted it using the generated files.   However, as I was viewing the concrete syntax tree, I noticed that the operator nodes (such as plus, minus, etc) weren't part of the assignment expression nodes, even though the other fields (left, right) are included. Is this a common occurrences?

**Comment by ahelwer** [comment]
If you have string literals as part of `seq` or `choice` then they won't be output in the syntax tree. If you want them to be output, then you need to move the literals into their own rule.

**Comment by maxbrunsfeld** [comment]
String literals are in the tree, they just have a boolean `named` field set to false, and they don't get printed out at the command line when running `tree-sitter parse`.

**Comment by tinygiant98** [comment]
Thanks for the help, I'll try to get a rule setup.

**Comment by tinygiant98** [comment]
> String literals are in the tree, they just have a boolean `named` field set to false, and they don't get printed out at the command line when running `tree-sitter parse`.

Is that a hard-coded setting?  If not, where can I set it?

**Comment by ahlinc** [comment]
@tinygiant98 it's impossible for standard `tree-sitter parse` command, but you can make your own from a branch for this PR: https://github.com/ahlinc/tree-sitter/pull/4
It's work in progress and will be fully reimplemented to speed up rendering and implement many other planned features.

**Comment by tinygiant98** [comment]
> @tinygiant98 it's impossible for standard `tree-sitter parse` command, but you can make your own from a branch for this PR: [ahlinc#4](https://github.com/ahlinc/tree-sitter/pull/4)
> It's work in progress and will be fully reimplemented to speed up rendering and implement many other planned features.
> And I need to say there no setings yet in the mentioned implementation, it just shows everything right like you need.

Thanks for the pointer.  I'll check it out.  Also, is there a place I can go for help with finding out why the wasm produced from the tree-sitter parser won't work within a vscode extension (that is already setup to use wasm for other languages)?  Seems like a niche requirement, so I'm not really sure where to turn for integration help.

**Comment by ahlinc** [comment]
@tinygiant98 about WASM your issues may be related to this https://github.com/tree-sitter/tree-sitter-haskell/issues/35#issuecomment-857387920.
Feel free to ask any tree-sitter related questions in the Discussions [Q&A](https://github.com/tree-sitter/tree-sitter/discussions/categories/q-a) section.

**Comment by tinygiant98** [comment]
> @tinygiant98 about WASM your issues may be related to this [tree-sitter/tree-sitter-haskell#35 (comment)](https://github.com/tree-sitter/tree-sitter-haskell/issues/35#issuecomment-857387920).
> Feel free to ask any tree-sitter related questions in the Discussions [Q&A](https://github.com/tree-sitter/tree-sitter/discussions/categories/q-a) section.

Thanks for your help.  Debugging shows that it's erroring out in tree-sitter.js, looking for a file that doesn't exist (and shouldn't), and using a member that's not defined.  I'll get a better write up and open an issue if I can't get by it.  Thanks again, I'll read through the discussion you linked and join the Q&A.
