### ISSUE TITLE
Parser hang with null character in grammar

### ISSUE THREAD

**Issue by CyberShadow** [tree-sitter/tree-sitter#1167]
Grammar:
```js
module.exports = grammar({
  name: 'bugcase',

  rules: {
    source_file: $ => 'hello',

    _unused: $ => token(
      seq(
        repeat(/./),
        "\0",
      ),
    ),
  }
});
```
Source file:
```
hello // hello
```

Note that the definition of `_unused` is not even referenced anywhere in the grammar, but its presence and definition still affects the outcome.

Full test case: https://gist.github.com/CyberShadow/25b704c90211f0e69e843083b566194c (`npm install && node_modules/.bin/tree-sitter generate && node_modules/.bin/tree-sitter parse source.bugcase`).

**Comment by ahlinc** [comment]
There were mention in #924 that Tree-sitter isn't intended to parse binary data and it's unexpected that `\0` bytes are present in text data. But have some fuse in the generator would be good.

**Comment by CyberShadow** [comment]
> and it's unexpected that `\0` bytes are present in text data

FWIW, null characters are part of the grammar of the language I'm trying to implement:
https://dlang.org/spec/lex.html#end_of_file

But I agree that in practice they would be unexpected - I was just trying to match the official grammar and behavior of the reference implementation (compiler).

**Comment by ahlinc** [comment]
> null characters are part of the grammar of the language

Nice :slightly_smiling_face: 
```
EndOfFile:
    physical end of the file
    \u0000
    \u001A
```
From official Unicode code charts doc:
```
\u0000 = NULL
\u001A = SUBSTITUTE → FFFD  replacement character
```
@CyberShadow thanks! I didn't see before that some language spec would be defined in such way.

For tree-sitter analog of the grammar there no need to mention such characters and any explicit termination rule (actually there no one).

**Comment by ahlinc** [comment]
Another case of of this issue was in #1311, a description is in https://github.com/AbstractMachinesLab/tree-sitter-erlang/pull/10.
**As a resume:** the `\x00` bytes shouldn't be allowed in the regexp also.

**Comment by amaanq** [comment]
Can't reproduce with the latest version, so I'll assume it's fixed 🙂
