### ISSUE TITLE
ValueError: Incompatible Language version 12. Must be between 13 and 13

### ISSUE THREAD

**Issue by bdqnghi** [tree-sitter/tree-sitter#1207]
I'm trying to parse Rust code using tree_sitter. The current version is 0.19.0 and got this error.

```
parser.set_language(lang)
ValueError: Incompatible Language version 12. Must be between 13 and 13
```

Any idea to solve this?, thanks.

**Comment by ahlinc** [comment]
You need to regenerate your grammar with latest tree-sitter CLI version.
