### ISSUE TITLE
WASM parser returning an error, while test suite doesn't

### ISSUE THREAD

**Issue by razzeee** [tree-sitter/tree-sitter#1211]
I'm having users report parsing errors when parsing deeply nested trees. That usually hints at the external scanner, as we  mostly use it for indentation.

However, this time it (again) parses fine if I hand it to the test suite in tree-sitter-elm itself. But the code fails to parse in the language server, which uses the wasm + web-tree-sitter bindings.

https://github.com/elm-tooling/elm-language-server/issues/608
https://github.com/elm-tooling/elm-language-server/issues/610

I think this might be connected to this somehow (again) as this seems to have been introduced with the latest version.
> If you're calling this through web-tree-sitter, there will generally be two bytes per character (because JavaScript strings are UTF16, and web-tree-sitter encodes them this way).

https://github.com/tree-sitter/tree-sitter/issues/1099#issuecomment-850933229

At this point, I've checked https://github.com/elm-tooling/tree-sitter-elm/blob/main/src/scanner.cc multiple times, either there is nothing wrong or my c++ is too rusty.

**Comment by Razzeee** [comment]
Any idea how to get debug this? Can tests be run against a build wasm file somehow?

**Comment by Razzeee** [comment]
Another way to show this error is now via https://elm-tooling.github.io/tree-sitter-elm/

The nodes will error, but it does not error in if I parse the same code via `tree-sitter parse`

**Comment by ahelwer** [comment]
I'm having a rough time with the combination of an external scanner with emscripten as well, see https://github.com/tree-sitter/tree-sitter/issues/1300

**Comment by Razzeee** [comment]
No, I don't think that's possible, as the only way to trigger it is via one of the external scanners functions.

**Comment by razzeee** [comment]
Seems to be fixed by https://github.com/tree-sitter/tree-sitter/pull/1581
Will do some more research and report back
