### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by carlocab** [tree-sitter/tree-sitter#1216]
Hi there, Homebrew maintainer here. Is there any possibility of your cutting a new release tag that includes 6ed42747a4e0faee9b65edbbacc86ed0caeae05c soon? Ideally, this would be before the release of Neovim 0.5 on Friday, but I understand that is probably too soon.

The reason is that Neovim 0.5 will depend on tree-sitter but won't build with the latest 0.19.5 tag. Instead, Neovim uses a [version of tree-sitter](https://github.com/neovim/neovim/blob/f83c25942dd8b94ad5218ce78b9e6fb86d2f0358/third-party/CMakeLists.txt#L213) from the commit hash referenced above. See neovim/neovim#14915 for details. I imagine other package managers (e.g. nixpkgs, see NixOS/nixpkgs#110837) would find this helpful as well.

Thanks for your work on tree-sitter!

**Comment by maxbrunsfeld** [comment]
Yes, that makes a lot of sense. I will try to get one out today.

**Comment by dcreager** [comment]
@maxbrunsfeld Just a reminder that it will need to be 0.20.0 because of the backwards-incompatible changes since the last release.

**Comment by maxbrunsfeld** [comment]
> it will need to be 0.20.0

Yeah, good point.

@carlocab I'm going to release a version 0.20.0 of the CLI and of the Rust & Wasm libraries.

**Comment by maxbrunsfeld** [comment]
Tree-sitter 0.20 is out.

**Comment by carlocab** [comment]
Thanks very much.

**Comment by ahlinc** [comment]
@maxbrunsfeld thank you for awesome release and many merged PRs! :tada: :tada: :tada:

**Comment by Razzeee** [comment]
will web-tree-sitter and tree-sitter-cli also get updated?
