### ISSUE TITLE
Setting TREE_SITTER_DIR causes ENOENT on tree-sitter 0.20.0 + macOS

### ISSUE THREAD

**Issue by Julian** [tree-sitter/tree-sitter#1222]
When trying to run either `tree-sitter test` or `tree-sitter generate` on macOS, I get:

```
~/Desktop/tree-sitter-lean is a git repository on main 
⊙  ../tree-sitter-macos-x64 test                                                   julian@Airm
No such file or directory (os error 2)

~/Desktop/tree-sitter-lean is a git repository on main 
⊙  ../tree-sitter-macos-x64 generate                                               julian@Airm
No such file or directory (os error 2)
```

which is due to having `TREE_SITTER_DIR` set to tell tree-sitter where to put its files.

Either `brew install tree-sitter` or the official release (`wget https://github.com/tree-sitter/tree-sitter/releases/download/v0.20.0/tree-sitter-macos-x64.gz`) seem to do so for me.

Minimal reproducer run on [a tree sitter project](https://github.com/Julian/tree-sitter-lean/):

```

~/Desktop/tree-sitter-lean is a git repository on main 
⊙  ls                                                                                                                                                                               julian@Airm
bindings  grammar  src  test  COPYING  Cargo.toml  README.rst  binding.gyp  grammar.js  package-lock.json  package.json

~/Desktop/tree-sitter-lean is a git repository on main 
⊙  mkdir foo                                                                                                                                                                        julian@Airm

~/Desktop/tree-sitter-lean is a git repository on main 
⊙  env -i TREE_SITTER_DIR=$PWD/foo =tree-sitter test | tail -n3                                                                                                                     julian@Airm
No such file or directory (os error 2)

~/Desktop/tree-sitter-lean is a git repository on main 
⊙  env -i =tree-sitter test | tail -n3                                                                                                                                              julian@Airm
    ✓ Interpolation
    ✓ Interpolation With Function Application
    ✓ Interpolation With Escape Sequences

~/Desktop/tree-sitter-lean is a git repository on main 
⊙  env -i TREE_SITTER_DIR= =tree-sitter test | tail -n3                                                                                                                             julian@Airm
No such file or directory (os error 2)
```

**Comment by CyberShadow** [comment]
> which is due to having `TREE_SITTER_DIR` set to tell tree-sitter where to put its files.

What does this refer to (where is the expectation for the behavior described here come from)?

Looking at the code, `TREE_SITTER_DIR` seems to be used only to indicate the location of a `config.json` file:
https://github.com/tree-sitter/tree-sitter/search?q=TREE_SITTER_DIR&type=code
If the variable is set, then it is expected to point to a valid location.

**Comment by Julian** [comment]
I've been doing it since https://github.com/tree-sitter/tree-sitter/issues/628#issuecomment-826306190 (and it worked with previous releases)

**Comment by Julian** [comment]
It looks like #1157 means I don't need to set it anymore, since now the files will default to `~/Library/ApplicationSupport` which is where I was putting them, but I suspect someone else may run into the above.
