### ISSUE TITLE
Highlighting entirely broken in CLI v0.20.0

### ISSUE THREAD

**Issue by ahlinc** [tree-sitter/tree-sitter#1232]
Highlighting were broken in the next piece of code:
https://github.com/tree-sitter/tree-sitter/commit/e841fcfa1#diff-37970e7d817d4316a093bb967d74ff7e26d9c6c01d93f5a79d3d195ba9f6155bR375-R393

The next line overrides the real config and deserializes into an empty `Theme` struct:
https://github.com/tree-sitter/tree-sitter/blob/e841fcfa1bb9c19021e83763956aa8dc936e22f1/cli/src/main.rs#L377
So none of `theme` definitions in the `~/.config/tree-sitter/config.json` works properly at this moment.

#1229 may be related.

**Comment by maxbrunsfeld** [comment]
thanks @ahlinc!

/cc @dcreager

**Comment by ahlinc** [comment]
@maxbrunsfeld The PR to fix this already is here: #1233
