### ISSUE TITLE
Low performance for Elixir 

### ISSUE THREAD

**Issue by fuelen** [tree-sitter/tree-sitter#1242]
repo: https://github.com/ananthakumaran/tree-sitter-elixir
related issue: https://github.com/nvim-treesitter/nvim-treesitter/issues/1486

Benchmarks with different versions of tree-sitter. They were changed in package.json of tree-sitter-elixir repo.
This is what I've got when running tree-sitter using version from node_modules folder
small file - 13 LOC
big file - 2084 LOC

0.18.3, small file:
```
  Time (mean ± σ):     842.6 ms ±   6.0 ms    [User: 851.2 ms, System: 45.5 ms]
  Range (min … max):   833.5 ms … 852.5 ms    10 runs
```
0.18.3, big file:
```
  Time (mean ± σ):     893.4 ms ±   7.4 ms    [User: 897.8 ms, System: 50.1 ms]
  Range (min … max):   883.4 ms … 907.4 ms    10 runs
```

0.19.4, small file:
```
  Time (mean ± σ):     761.6 ms ±  17.6 ms    [User: 773.1 ms, System: 42.7 ms]
  Range (min … max):   746.5 ms … 806.7 ms    10 runs
```

0.19.4, big file:
```
  Time (mean ± σ):     799.7 ms ±   6.3 ms    [User: 800.2 ms, System: 53.2 ms]
  Range (min … max):   793.2 ms … 813.1 ms    10 runs
```
0.20.0, small file:
```
  Time (mean ± σ):     762.2 ms ±   6.8 ms    [User: 766.0 ms, System: 50.3 ms]
  Range (min … max):   753.7 ms … 773.5 ms    10 runs
```
0.20.0, big file:
```
  Time (mean ± σ):     825.2 ms ±   9.1 ms    [User: 823.7 ms, System: 55.6 ms]
  Range (min … max):   811.4 ms … 836.1 ms    10 runs
```

the interesting thing is that system (Arch Linux) tree-sitter 0.20.0 is faster
small file:
```
  Time (mean ± σ):     645.3 ms ±   8.3 ms    [User: 640.0 ms, System: 3.8 ms]
  Range (min … max):   632.4 ms … 657.3 ms    10 runs
```
big file:
```
  Time (mean ± σ):     694.3 ms ±   5.0 ms    [User: 681.0 ms, System: 12.1 ms]
  Range (min … max):   683.2 ms … 699.8 ms    10 runs
```

Anyway, with these results, tree-sitter for Elixir is not really usable.

**Comment by theHamsta** [comment]
Is it only for `tree-sitter parse` or `tree-sitter query`? If query which query file are you using can the file be reduced to a minimal example?

**Comment by fuelen** [comment]
it is for tree-sitter query.
query file: ~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/elixir/highlights.scm

I'm not sure that I understand what do you mean by reducing a query file.

**Comment by theHamsta** [comment]
Just use a few lines of this query file. Try to determine whether the first half of this file is slower as the second half.

**Comment by fuelen** [comment]
elixir file has only 1 word `when`.
Initial run:
```
  Time (mean ± σ):     465.3 ms ±   3.2 ms    [User: 461.8 ms, System: 2.7 ms]
  Range (min … max):   460.5 ms … 471.1 ms    10 runs
```

having only this part takes 64.7 ms:
```
(binary_op
 operator: _ @operator)
```
227.5ms:
```
(call function: (function_identifier) @keyword
      [(call
        function: (function_identifier) @function
        (arguments
         [(identifier) @variable.parameter
          (_ (identifier) @variable.parameter)
          (_ (_ (identifier) @variable.parameter))
          (_ (_ (_ (identifier) @variable.parameter)))
          (_ (_ (_ (_ (identifier) @variable.parameter))))
          (_ (_ (_ (_ (_ (identifier) @variable.parameter)))))]))
       (binary_op
        left:
        (call
         function: (function_identifier) @function
         (arguments
          [(identifier) @variable.parameter
           (_ (identifier) @variable.parameter)
           (_ (_ (identifier) @variable.parameter))
           (_ (_ (_ (identifier) @variable.parameter)))
           (_ (_ (_ (_ (identifier) @variable.parameter))))
           (_ (_ (_ (_ (_ (identifier) @variable.parameter)))))]))
        operator: "when")
       (binary_op
        left: (identifier) @variable.parameter
        operator: _ @function
        right: (identifier) @variable.parameter)]
      (#match? @keyword "^(defp|def|defmacrop|defmacro|defguardp|defguard|defdelegate)$"))
```
if I remove 2 binary_op from the query above, then it takes 35ms.
first binary_op - 116ms, only the second - 93ms.


129.5 ms:
```
(call (function_identifier) @keyword
      [(call
        function: (function_identifier) @function)
       (identifier) @function
       (binary_op
        left:
        [(call
          function: (function_identifier) @function)
         (identifier) @function]
        operator: "when")]
      (#match? @keyword "^(defp|def|defmacrop|defmacro|defguardp|defguard|defdelegate)$"))
```
Internal binary_op takes 106.6 ms

**Comment by ahlinc** [comment]
Try to split your one big query to a series of queries stored in the same file. For performance reasons it better to have dozens of small queries with minimal context that uses minimal nesting and no nested alternatives in square brackets.

**Comment by ahlinc** [comment]
I recalled context of this #1096

**Comment by archseer** [comment]
https://github.com/tree-sitter/tree-sitter/pull/1589 improved the performance quite significantly. See also https://github.com/tree-sitter/tree-sitter/pull/1578

**Comment by ahlinc** [comment]
Closing because the nvim-treesitter/nvim-treesitter#1486 issue is resolved and performance was improved.
