### ISSUE TITLE
Difference between `_` and `(_)`

### ISSUE THREAD

**Issue by stsewd** [tree-sitter/tree-sitter#1253]
Right now, only `(_)` is documented https://tree-sitter.github.io/tree-sitter/using-parsers#query-syntax, but I noticed [the elixir grammar](https://github.com/ananthakumaran/tree-sitter-elixir) uses `_` too.

I thought they were the same, but this query gives an error

```
(call (function_identifier) @keyword.function
 (binary_op
  left: (identifier) @parameter
  operator: (_) @function
  right: (identifier) @parameter))
```

And this one doesn't

```
(call (function_identifier) @keyword.function
 (binary_op
  left: (identifier) @parameter
  operator: _ @function
  right: (identifier) @parameter))
```

**Comment by ahlinc** [comment]
It seems that `(_)` matches only named nodes while `_` matches both named and unnnamed leaf nodes.

![Screenshot from 2021-07-11 06-57-49](https://user-images.githubusercontent.com/14666676/125182284-73cdf480-e215-11eb-9266-90b83818efac.png)

**Comment by stsewd** [comment]
Thanks! I was able to check this with a more simple example in python


```python
a = "string"
```

This matches the `"`

```
(string _ @foo)
```

This doesn't match `"`

```
(string (_) @foo)
```
