### ISSUE TITLE
tree-sitter calls external scanner with all symbols marked valid

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/tree-sitter#1259]
**Version Info**
Windows 10
tree-sitter-cli 0.20.0 (also occurs on 0.19.5)

**What happens?**
During GLR parsing, if a parse branch encounters an error then tree-sitter sometimes calls the external scanner with every symbol marked as valid - even if that symbol isn't used in the grammar (checked by commenting out its use).

**What did you expect to happen?**
I expected tree-sitter to only call the external scanner with contextually-relevant symbols marked as valid.

**Steps to reproduce**
1. `git clone https://github.com/tlaplus-community/tree-sitter-tlaplus tree-sitter-tlaplus`
2. `cd tree-sitter-tlaplus`
2. `git checkout ext-scanner-glr-bug`
3. `npm install`
4. `tree-sitter parse -d .\test\examples\BugTrigger.tla`
5. This should trigger an assert in `src/scanner.cc` I added that not every symbol is marked valid at once.

**Workaround**
In the external scanner, check whether every symbol is marked as valid; if so, immediately return false.

**Discussion**
I've been trying to narrow down when this happens; I thought it was related to [this question of mine](https://github.com/tree-sitter/tree-sitter/discussions/1257) but I've removed that phenomenon from the equation and it still happens. All I can tell is it occurs when tree-sitter is doing GLR parsing and one of the branches encounters a token it didn't expect, except instead of that terminating the GLR branch tree-sitter then calls into the external scanner with every symbol marked as valid. This hasn't yet resulted in an incorrect parse, just very strange parse debug logs since one of the symbols has the scanner read until either it sees a certain string or the end of the file - so massive debug logs are generated with the external scanner continually reading to the end of the file before that parse branch is aborted.

For now I've just added an if-statement at the top of my scan method to detect that every symbol is marked valid (which should never be the case) then immediately bail out.

**Comment by maxbrunsfeld** [comment]
This means that the parser is starting to recover from an error, so it doesn't know which tokens are valid (right after the error). This has been confusing in a couple of cases, so it probably deserves some docs.

**Comment by ahelwer** [comment]
@maxbrunsfeld ah okay good to know, I'm still in the beginning stages of getting my external scanner to play nice with error recovery. So in GLR parsing a single error isn't fatal to a branch, but it does attempt error recovery (probably with a large score penalty)?

**Comment by maxbrunsfeld** [comment]
This will only happen if there's actually a syntax error (not just an error on a particular GLR branch).
