### ISSUE TITLE
tree-sitter-cli doesn't support multiple scanner source files

### ISSUE THREAD

**Issue by jneem** [tree-sitter/tree-sitter#1262]
This is a follow-up from the discussion #1261, and seems related to #1246.

I'm trying to update a project from tree-sitter 0.13 to 0.19, and the scanner code has multiple source files (`src/scanner.cc`, `src/scanner_keywords.cc`, etc). It appears that tree-sitter-cli only compiles one of them; based on the discussion in #1246, this behavior is hard-coded.

Would you take a PR to make tree-sitter-cli take a list of source paths? It could be specified as a setting in `package.json`.

**Comment by ahlinc** [comment]
I'm  :+1:  for a PR.
But there couple of questions:
- Do such settings in the `package.json` to be required or optional?
  - If to make it required than there should be added a logic that would update `package.json` automatically for all existing grammars.
    - But when to do this? On the `tree-sitter generate`, on the `tree-sitter parse`, or on both?
      - If only on the `tree-sitter generate` than the `tree-sitter parse` should silently behave as before and try to compile the `scanner.cc` or the `scanner.c` if one of such files exist and there no explicit `tree-sitter.scanner` setting in the `package.json` file?
- What settings structure needs to be supported in the `package.json` file?
  ```json
  {
    "tree-sitter": {
      "scanner": ???
    }
  }
  ```
  Does it make sense to support separate compilation flags per scanner file or some common flags for all files would be enough?

**Comment by jneem** [comment]
I guess the easiest behavior to implement would be that the `package.json` supports the optional key
```
{
    "tree-sitter": {
        "scanner-sources": [ "src/scanner.cc", "src/scanner_extra.cc"]
    }
}
```

If this key is found, the files listed are the scanner source files. If this key is not found, the current behavior is used (`src/scanner.c` if it exists, or if not then `src/scanner.cc` if it exists).

I think it's fine to use common flags for all files; in fact, I was planning to just compile all files in the same compiler invocation. If the build system needs to get much fancier than that, it probably makes sense to start using an external build system.

By the way, [the docs](http://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners) say that you need to add the scanner sources to `binding.gyp`. Is this still the case?

**Comment by ahlinc** [comment]
> By the way, [the docs](http://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners) say that you need to add the scanner sources to `binding.gyp`. Is this still the case?

Yes, the `binding.gyp` file is required when you're compiling a grammar with the `node-gyp` tool to build a `node.js` native module. And it has no relation to what the `tree-sitter parse` command builds for own needs.

**Comment by ahlinc** [comment]
I'd suggest the `package.json` structure similar to something like:
```json
{
  "tree-sitter": {
    "scanner": {
       "flags": "...",
       "sources" [...],
  }
}
```

**Comment by jneem** [comment]
Sure, that makes sense. Flags would need to be platform-dependent, though. Do you have a preference for how to encode that?

**Comment by ahlinc** [comment]
> Flags would need to be platform-dependent, though.

Good note, I don't have preferences cause I mostly use Macos and Linux systems and didn't tried to use Tree-sitter on Windows yet. I suppose the `flags` and the `sources` keys both would be optional and there would be some builtin defaults for both.

**Comment by jneem** [comment]
I tried to implement this, but ran into trouble updating the [`languages_at_path`](https://github.com/tree-sitter/tree-sitter/blob/c7998d93d0d180e0c11924e3f1543e1b0e4487be/cli/loader/src/lib.rs#L165) function. It seems that there can be multiple `LanguageConfiguration`s that share the same `language_id`. What's the use-case for this? I ask because if the scanner sources become part of the `LanguageConfiguration` then potentially for one `language_id` you could have multiple different choices for the scanner sources, and then we would want to load them all?

**Comment by ahlinc** [comment]
Notes for a future implementation:
* Good example of an issue with a mix of C/C++ files: https://github.com/tree-sitter/tree-sitter-haskell/issues/51#issuecomment-983825691. The cause is that `gcc` and `clang` actually don't support such mixing and require firstly to build `*.o` object files with separate commands and link them with another compiler call. Compilers only allow to build into one `*.o` object file multiple other object files or several source files of the same type.
* #1518 Think about how to support specifying flags for compilers and allow build with GCC and Clang.

**Comment by amaanq** [comment]
You may now specify an `external-files` array in the `tree-sitter` field of your grammar's package.json to have it account for checking *any* of those files' mtimes for recompilation. This does not mean it will *compile* these files - we want to keep that to just `scanner.c`, but rather you can include another c/header file directly and have the cli track this file as well. Hope that helps for your use case.
