### ISSUE TITLE
Tokens matching empty strings are allowed, and cause infinite loop

### ISSUE THREAD

**Issue by CyberShadow** [tree-sitter/tree-sitter#1271]
Grammar:
```js
module.exports = grammar({
  name: 'bugcase',

  rules: {
    source_file: $ => $.identifier,
    identifier: $ => token(repeat(/a/))
  }
});
```
Source file:
```
b
```

Full test case: https://gist.github.com/CyberShadow/fe5ce672cc68f065210a97ab116d69a7 (`npm install && node_modules/.bin/tree-sitter generate && node_modules/.bin/tree-sitter parse source.bugcase`).

Expected output (same as without `token(...)`):

```
The rule `identifier` matches the empty string.

Tree-sitter does not support syntactic rules that match the empty string
unless they are used only as the grammar's start rule.
```

Actual output:

The grammar compiles successfully, and upon attempting to parse the source file, `tree-sitter parse` loops infinitely until it consumes all available memory.

**Comment by ahlinc** [comment]
It seems you find another example similar to #1111.
