### ISSUE TITLE
"/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:347: No handler for any-of?"

### ISSUE THREAD

**Issue by christianparpart** [tree-sitter/tree-sitter#1272]
Hey,

since a OS update last night my neovim (latest master branch) keeps blaming at me like so:

![image](https://user-images.githubusercontent.com/56763/125853178-c60fe4d3-6b6e-4055-96f5-ca18785f8843.png)

Updating neovim, fully recompiling, updating respective python module, updating treesitter and reinstalling c/cpp plugins, nothing helped. I am kinda clueless what to do from here on.

What does this message tell me, and how can it be mitigated?

**Comment by stsewd** [comment]
@christianparpart please report this to the nvim-treesitter repo https://github.com/tree-sitter/tree-sitter/, and looks like you are missing updating the runtime files, try `make clean` before re-compiling.

**Comment by christianparpart** [comment]
Ah damn it. Sorry :)
