### ISSUE TITLE
Limit visibility of symbols in shared library to public API

### ISSUE THREAD

**Issue by jamessan** [tree-sitter/tree-sitter#1276]
As I understand `lib/src/*.h` are internal and shouldn't be considered part of the stable, public API of the shared library.  The public API is solely that described by `lib/include/tree_sitter/*.h`.  However, the symbols for those non-static inline functions in `lib/src/*.h` are exposed in the shared library:

```
$ nm -D libtree-sitter.so.0 | grep ts_subtree
0000000000020cc0 T ts_subtree_array_clear
0000000000020690 T ts_subtree_array_copy
0000000000020d00 T ts_subtree_array_delete
000000000001f1a0 T ts_subtree_array_remove_trailing_extras
000000000001f160 T ts_subtree_array_reverse
000000000001fe30 T ts_subtree_balance
0000000000020760 T ts_subtree_clone
0000000000020e90 T ts_subtree_compare
0000000000020fb0 T ts_subtree_edit
0000000000020d70 T ts_subtree_eq
0000000000022030 T ts_subtree_external_scanner_state_eq
0000000000005910 T ts_subtree_get_changed_ranges
0000000000021a30 T ts_subtree_last_external_token
0000000000020d30 T ts_subtree_make_mut
000000000001f760 T ts_subtree_new_error
00000000000205a0 T ts_subtree_new_error_node
000000000001f3f0 T ts_subtree_new_leaf
00000000000205d0 T ts_subtree_new_missing_leaf
0000000000020460 T ts_subtree_new_node
000000000001f370 T ts_subtree_pool_delete
000000000001f2f0 T ts_subtree_pool_new
0000000000021b60 T ts_subtree__print_dot_graph
0000000000021fb0 T ts_subtree_print_dot_graph
0000000000020880 T ts_subtree_release
0000000000020630 T ts_subtree_retain
000000000001f6b0 T ts_subtree_set_symbol
0000000000021a90 T ts_subtree_string
000000000001f7b0 T ts_subtree_summarize_children
```

GCC defaults to making all symbols visible, but this can be controlled by the [`-fvisibility` option](https://gcc.gnu.org/onlinedocs/gcc-11.1.0/gcc/Code-Gen-Options.html#Code-Gen-Options).  Setting default visibility to hidden and explicitly exposing the public API also better matches the default behavior of MSVC.

The GCC wiki gives some [suggestions](https://gcc.gnu.org/wiki/Visibility) on how to implement "hidden by default".

**Comment by ahlinc** [comment]
@jamessan Thank you for the GCC wiki link and for the issue reporting!
