### ISSUE TITLE
Tree-sitter on large files

### ISSUE THREAD

**Issue by casouri** [tree-sitter/tree-sitter#1277]
I tried to parse a 1.6MB JSON file with tree-sitter, and it took about 1.2s for a full-parse, and 0.7s for a re-parse (with no change to the text). Does these numbers make sense? Maybe I'm missing something, because I expected the re-parse to be much faster than that.

Also, I found that the two parse tree from the two parses take about 300MB. Is that about right?

Here is my program, it loads the JSON file into a buffer and parses it twice:

```C
#include <string.h>
#include <stdio.h>
#include <tree_sitter/api.h>

TSLanguage *tree_sitter_json();

struct buffer {
  char *buf;
  long len;
};

const char *read_file(void *payload, uint32_t byte_index,
                TSPoint position, uint32_t *bytes_read) {
  if (byte_index >= ((struct buffer *) payload)->len) {
    *bytes_read = 0;
    return (char *) "";
  } else {
    *bytes_read = 1;
    return (char *) (((struct buffer *) payload)->buf) + byte_index;
  }
}

int main() {
  TSParser *parser = ts_parser_new();
  ts_parser_set_language(parser, tree_sitter_json());

  /* Copy the file into BUFFER. */
  FILE *file = fopen("benchmark.2.json", "rb");
  fseek(file, 0, SEEK_END);
  long length = ftell (file);
  fseek(file, 0, SEEK_SET);
  char *buffer = malloc (length);
  fread(buffer, 1, length, file);
  fclose (file);

  struct buffer buf = {buffer, length};
  TSInput input = {&buf, read_file, TSInputEncodingUTF8};
  
  TSTree *tree = ts_parser_parse(parser, NULL, input);
  TSTree *new_tree = ts_parser_parse(parser, tree, input);
  
  free(buffer);
  ts_tree_delete(tree);
  ts_tree_delete(new_tree);
  ts_parser_delete(parser);

  return 0;
}
```

**Comment by ahelwer** [comment]
Haven't yet gotten to the point of using the tree-sitter grammar I'm writing in the way you're using one here, but isn't the value of tree-sitter that it has fast incremental reparse when you specify the scope of the changes? As far as I can tell you're just telling it to parse the entire file again, vs. in an editor a user only edits a single line so you tell tree-sitter to reparse only those specific changes.

**Comment by casouri** [comment]
I might be missing something. According to the documentation, incremental parsing is done by first updating the old tree and then calling ts_parser_parse again. That’s what I’m doing in the C program. 

Maybe it’s because my read function is bad? It reads one byte a time (I’m cheating here, the Json file only contains ascii characters.

**Comment by QnnOkabayashi** [comment]
> Maybe it’s because my read function is bad? It reads one byte a time.

I think this is the issue, since tree-sitter has to call `read` for every single character.

My interpretation is that the read function is meant for programs that don't have the whole input in a contiguous slice of memory at once, e.g. streaming or a rope. If you have the whole input in a buffer, you may as well let `read` view the rest of the buffer each time its called.

**Comment by amaanq** [comment]
Yeah, as Quinn mentioned, your read function only returning 1 byte at a time is most likely the cause for the slowdown. I would expect the parse time to reduce dramatically if you just wrote the remaining string length.
