### ISSUE TITLE
cflags in binding.gyp do not affect scanner.c compilation.

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#1279]
I have added two flags to the `cflags_c` in the `binding.gyp` file.
Currently it looks like follows:
```
{
  "targets": [
    {
      "target_name": "tree_sitter_fbdl_binding",
      "include_dirs": [
        "<!(node -e \"require('nan')\")",
        "src"
      ],
      "sources": [
        "bindings/node/binding.cc",
        "src/parser.c",
        # If your language uses an external scanner, add it here.
        "src/scanner.c",
      ],
      "cflags_c": [
        "-std=c99",
        "-Wall",
        "-Werror",
      ]
    }
  ]
}
```

In one of the `scanner.c` functions I have written simple code that should generate warning treated as error:
```C
unsigned tree_sitter_fbdl_external_scanner_serialize(
	void *payload,
	char *buffer
) {
	int i = 5;
	char c = 3;

	c = i;

	return 0;
}
```
The `scanner.c` file is compiled when user runs `tree-sitter test`. However no warning/error resulting from `-Wall` and `-Werror` is reported.  Like the flags were not taken into account during `scanner.c` compilation.

**Comment by ahelwer** [comment]
See https://github.com/tree-sitter/tree-sitter/issues/1246 and https://github.com/tree-sitter/tree-sitter/discussions/1184. `tree-sitter test` and `tree-sitter parse` do not use the binding.gyp file for compilation.
