### ISSUE TITLE
The simplest way to write tests for nodes that can not appear at root

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#1284]
What is the simplest way to write tests for nodes that can not appear at root?

For example, let assume following rule
```javascript
    decimal_literal: $ => /[1-9]([0-9]|_)*/,
```

`decimal_literal` is not in a choice of root node, so the following test file always fails:

```
===============
Integer literal
===============

123

---
```

**Comment by ahelwer** [comment]
As far as I know, your test cases always have to match the entire tree starting from `source_file`; you can't just test rules in isolation.
