### ISSUE TITLE
Highlighting error for C++ grammar

### ISSUE THREAD

**Issue by jasonhan-vassar** [tree-sitter/tree-sitter#1285]
Hi, so I'm getting this error below when highlighting with the C++ grammar at https://github.com/tree-sitter/tree-sitter-cpp. I am running `tree-sitter test` below:

<img width="745" alt="Screen Shot 2021-07-20 at 6 50 29 PM" src="https://user-images.githubusercontent.com/34594853/126405202-7f58810b-333c-48e9-ab48-e6cb2dcad61d.png">

The grammar itself works when running `parse`, but `highlight` and the highlighting portion of `test` fail. I am using the latest version of 0.20.0 (59cd1c3), which fixes #1232. Can anyone reproduce this?

### System Info
- tree-sitter 0.20.0 (59cd1c3962d5b39e07bff3d5e5449c8b78e7cf61)
- macOS 11.1

**Comment by ahlinc** [comment]
It seems you need to run `npm install` in your `tree-sitter-cpp` repository folder first to install dependencies.

**Comment by jasonhan-vassar** [comment]
Thank you! I should've realized this was a Node issue. Is the C++ grammar the only one that has Node dependencies/modules?

**Comment by ahlinc** [comment]
The issue was happen because the C++ grammar based on the C grammar and requires the last as dependency. This is relevant for some other grammars, for ex. Typescript grammar uses JS grammar as the base too.

**Comment by andrewtbiehl** [comment]
In case it would be helpful for anyone else, I also had this issue and came up with a kind of hack that allowed me to resolve it without the need for a Node.js installation (which was preferable for my use case). Namely, if you download the C parser library directly and create a symbolic link to its parent by the name of `node_modules` inside of the C++ parser library, then everything will work.

For example, I have both the C and C++ parser libraries downloaded to the same parent directory, `~/parsers`, so running this command fixes the issue for me:

```shell
ln -s .. ~/parsers/tree-sitter-cpp/node_modules
```

An analogous workaround also works for TypeScript and JavaScript.
