### ISSUE TITLE
Feature request: Hashicorp Config Language (HCL) support

### ISSUE THREAD

**Issue by mike-sol** [tree-sitter/tree-sitter#1290]
Hello there! I found this project by way of diff-sitter, where I opened a similar issue and it was suggested I come here instead: https://github.com/afnanenayet/diffsitter/issues/153

I'd like to suggest the inclusion of Hashicorp Config Language (HCL) support if possible. HCL is used by Terraform, Packer, and other Hashicorp open-source products and drives infrastructure for a tremendous number of teams. Being able to diff two files in HCL while only actually comparing real changes would be tremendously useful.

The HCL language / Go parser itself is here: https://github.com/hashicorp/hcl

**Comment by maxbrunsfeld** [comment]
Here’s one https://github.com/mitchellh/tree-sitter-hcl

**Comment by mike-sol** [comment]
Oh, wow, amazing. Thanks for finding that. Now to see if I can get the diffsitter guys to roll that in somehow! Thanks.
