### ISSUE TITLE
Playground: Rename query to highlighting

### ISSUE THREAD

**Issue by razzeee** [tree-sitter/tree-sitter#1305]
I think query is too confusing, just had to check the code to find out what it does. I think something like `highlighting` might be a bit better.

Is that something, that would be accepted?

**Comment by stsewd** [comment]
Do you mean this part of the playground?

![Screenshot 2021-07-29 at 20-41-26 Tree-sitter｜Playground](https://user-images.githubusercontent.com/4975310/127587081-87d0f540-b109-4d49-960e-e622ea2ac51f.png)

**Comment by Razzeee** [comment]
Correct.

**Comment by ahlinc** [comment]
May be it would be better to add some text explaining what to expect from correct provided queries than rename it to the highlighting. An observable highlighting, as I understand, is just a good demonstration of correct queries applied to some text but it's not equal in behavior to the `tree-sitter highlight` command.

**Comment by Razzeee** [comment]
I think it is? It needs the `@name.of.highlight` thingy in the query to even work.

Another improvement would be, to set an example highlight query on load.

**Comment by ahelwer** [comment]
Query makes sense to me. The `@name.of.highlight` (captures) are just a way of graphically showing what your queries pick up.

**Comment by stsewd** [comment]
same, I think query makes sense, and we should add more information on usage instead of renaming it. For nvim-treesitter we added this help text

https://github.com/nvim-treesitter/playground/blob/deb887b3f49d66654d9faa9778e8949fe0d80bc3/lua/nvim-treesitter-playground/internal.lua#L289-L292

**Comment by calicoday** [comment]
A button or link so you can call up small recorded examples in 2 or 3 langs would be a help. Can't remember now if the playground first comes up with an example but if so, it was lost as soon as I tried my own. One should be exactly the example in the query section of the docs, so it's clear it's THAT 'query', and one that isn't, to show query expressions are specific to each lang grammar.

**Comment by maxbrunsfeld** [comment]
I'm definitely open to adding some more explanatory text to the playground. I do think that we should keep using the term "query", because that's the name of this feature of Tree-sitter. Highlighting is related, but it's not the only use for queries.
