### ISSUE TITLE
tree-sitter highlight - segfaults on an old version of injected language

### ISSUE THREAD

**Issue by ahlinc** [tree-sitter/tree-sitter#1318]
I found that the `tree-sitter highlight` ~**breaks without any errors**~ **segfaults** after the first 3 lines for the following correct handcrafted file:

<details><summary><i>foobar.js</i></summary>

```js
const fs = require('fs');
const Parser = require('tree-sitter');
const FOOBAR = require('.');
const parser = new Parser();

// comment that breaks highlighting

function print(o) {
    console.log(JSON.stringify(o, null, 2));
}
```
</details>

After several experiments I've found that the issue happening due to the presence of a `comment` node in the parsing tree, so if to remove the comment from the above code then highlighting works fine. I didn't find something special in the `tree-sitter-javascript` grammar the comment query is trivial: `(comment) @comment`.

At the same time `tree-sitter parse` command parses the file without any errors.

I use _tree-sitter-cli: v0.20.0_ and a standard theme generated by `tree-sitter init-config` command.

**Edit 1:**
```console
tree-sitter # target/debug/tree-sitter highlight foobar.js 
const fs = require('fs');
const Parser = require('tree-sitter');
const FOOBAR = require('.');
Segmentation fault (core dumped)
```

_**Another issue is with a node.js wrapper around tree-sitter CLI executable, it hides segmentation fault message and complicates understanding what's going on:**_ 
```console
tree-sitter # cli/npm/cli.js highlight foobar.js 
const fs = require('fs');
const Parser = require('tree-sitter');
const FOOBAR = require('.');
tree-sitter #
```

**Comment by ahelwer** [comment]
Does your version of tree-sitter-cli have the highlighting fix commit or something? It continues to not work at all for 0.20.0 (a hotfix would be nice!)

**Comment by ahlinc** [comment]
@ahelwer Unfortunately, I don't have a fix for this yet. It doesn't work on both the current master branch and on the v0.20.0 tag.

**Comment by maxbrunsfeld** [comment]
I can't reproduce this with the master branch of `tree-sitter` and `tree-sitter-javascript`. Do you have any other languages installed locally that injects highlighting into comments?

**Comment by ahlinc** [comment]
@maxbrunsfeld Thanks for the check, your assumption allows me to figure out what's going on.
You were very close to the issue, I have JSDoc parser installed but it were on the old commit https://github.com/tree-sitter/tree-sitter-jsdoc/commit/77e7785739ad3e90c3de8ed5a55418a5fd2b8225 and that was the reason of the segfault. The root cause of the segfault is that there is no check in the `ts_query_new` of what language version is used.

_Traceback:_
```
ts_language_symbol_metadata (/home/user1/Code/tree-sitter/lib/src/language.c:47)
ts_language_symbol_for_name (/home/user1/Code/tree-sitter/lib/src/language.c:83)
ts_query__parse_pattern (/home/user1/Code/tree-sitter/lib/src/query.c:1757)
ts_query_new (/home/user1/Code/tree-sitter/lib/src/query.c:2101)
new (/home/user1/Code/tree-sitter/lib/binding_rust/lib.rs:1223)
new (/home/user1/Code/tree-sitter/highlight/src/lib.rs:198)
{{closure}} (/home/user1/Code/tree-sitter/cli/loader/src/lib.rs:664)
get_or_try_init<core::option::Option<tree_sitter_highlight::HighlightConfiguration>,closure-0,anyhow::Error> (/home/user1/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.7.0/src/lib.rs:497)
highlight_config (/home/user1/Code/tree-sitter/cli/loader/src/lib.rs:651)
highlight_config_for_injection_string (/home/user1/Code/tree-sitter/cli/loader/src/lib.rs:447)
{{closure}} (/home/user1/Code/tree-sitter/cli/src/highlight.rs:352)
next<closure-0> (/home/user1/Code/tree-sitter/highlight/src/lib.rs:698)
ansi (/home/user1/Code/tree-sitter/cli/src/highlight.rs:356)
run (/home/user1/Code/tree-sitter/cli/src/main.rs:492)
main (/home/user1/Code/tree-sitter/cli/src/main.rs:16)
call_once<fn(),()> (@core::ops::function::FnOnce::call_once::h79d67d07a76d7e3e:6)
__rust_begin_short_backtrace<fn(),()> (@std::sys_common::backtrace::__rust_begin_short_backtrace::h44ed952514581ee4:6)
{{closure}}<()> (@std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h30f5885d5559e34e:7)
core::ops::function::impls::_$LT$impl$u20$core..ops..function..FnOnce$LT$A$GT$$u20$for$u20$$RF$F$GT$::call_once (@std::rt::lang_start_internal::h22ac7383c516f93e:175)
std::panicking::try::do_call (@std::rt::lang_start_internal::h22ac7383c516f93e:173)
```
