### ISSUE TITLE
impl Send for Node

### ISSUE THREAD

**Issue by amircodota** [tree-sitter/tree-sitter#1320]
Hi,

I'm trying to use tree-sitter rust binding in a rust tokio app (using async-await).

I have this function signature, which causes a compilation error

`    async fn find(&self, _node: &Node) -> Option<JavaType> {`

```
error: future cannot be sent between threads safely
  --> language-annotations/src/java/java_types.rs:26:60
   |
26 |       async fn find(&self, _node: &Node) -> Option<JavaType> {
   |  ____________________________________________________________^
27 | |         None
28 | |     }
   | |_____^ future created by async block is not `Send`
   |
   = help: within `tree_sitter::Node<'_>`, the trait `Sync` is not implemented for `*const tree_sitter::ffi::TSTree`
note: captured value is not `Send` because `&` references cannot be sent unless their referent is `Sync`

```

Looking at the rust binding code, I see most structs implement `Send` and `Sync` but `Node` does not.

```
unsafe impl Send for Language {}
unsafe impl Send for Parser {}
unsafe impl Send for Query {}
unsafe impl Send for QueryCursor {}
unsafe impl Send for Tree {}
unsafe impl Sync for Language {}
unsafe impl Sync for Parser {}
unsafe impl Sync for Query {}
unsafe impl Sync for QueryCursor {}
unsafe impl Sync for Tree {}
```

I wonder if it is an oversight, or if this was done on purpose. If on purpose, any advice on how to handle this?

Thanks
Amir

**Comment by ahlinc** [comment]
Duplicates: #1241

**Comment by ahlinc** [comment]
@amircodota I'd suggest you to try to reorganize your approach to working with the AST, cause I'm not sure that the `Node` could be made `Sync` or `Send` _(see my comments in duplicated issue)._ If your `_node: &Node` is actually the root node of a tree, than you can simply share a cheap clone the `Tree` to your async function (that may be scheduled into another thread).
```rust
async fn find(&self, _tree: Tree) -> Option<JavaType>;

let tree = parser.parse(source_code, None).unwrap();
let java_type = ___.find(tree.clone()).await;
```
Also note that the parsing itself is a CPU-bound operation so it's better to perform it in a dedicated threads pool by using [`tokio::task::spawn_blocking`](https://docs.rs/tokio/0.2.22/tokio/task/fn.spawn_blocking.html).

**Comment by amircodota** [comment]
Thanks, I'll try :+1:
