### ISSUE TITLE
Treesitter colorscheme produces weird highlighting

### ISSUE THREAD

**Issue by hqkhan** [tree-sitter/tree-sitter#1323]
Hi, I installed treesitter and wanted to use gruvbox colorscheme. I found [this](https://github.com/npxbr/gruvbox.nvim) colorscheme that supports treesitter. Installing it produces the image below: 

![image](https://user-images.githubusercontent.com/22674069/128406476-fb9a5669-960d-40b2-bab4-753fb48c0622.png)

The "comments" are not properly being rendered. I have tried reverting back to [morhetz/gruvbox](https://github.com/morhetz/gruvbox) which is for "non-treesitter" and this works perfectly fine. Is there a particular reason why this is happening? Other colorschemes that "support" treesitter produce the same issue. 

Thanks.

**Comment by hqkhan** [comment]
Apologies. I neglected to mention that I was using `tmux`. It was the `term` and adding the code below to tmux config fixed it:

```
# True color support
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*256col*:Tc"
```

**Comment by stsewd** [comment]
Also,  please report this kind of problems to https://github.com/nvim-treesitter/nvim-treesitter instead of here :)

**Comment by hqkhan** [comment]
@stsewd Oh! Sorry about that and will do for the future!
