### ISSUE TITLE
Incorrect tree structure with coment starting in same line as closing bracket of a function

### ISSUE THREAD

**Issue by marcosboggia** [tree-sitter/tree-sitter#1333]
I've found an incorrect tree structure when there is a comment in the same line of a closing bracket from a function body:
![Screenshot from 2021-08-11 16-30-24](https://user-images.githubusercontent.com/18308502/129091644-e7ce5e0e-c02c-420e-af62-3e579a864f37.png)
As we can see, tree-sitter finds the "weird comment" inside the body of foo1 function even though this comment is written after the closing bracket of the body function. A semicolon or writting the comment below would fix the issue, but still this corner case could happen eventually since not everybody uses semicolon or maybe a misplaced line break accidentally falls in that place and breaks the tree structure.
Thanks!

**Comment by ahelwer** [comment]
This issue should probably be filed with the specific tree-sitter grammar being used here, not tree-sitter itself, unless you think this is a bug with the parser generator?

**Comment by marcosboggia** [comment]
Well, I see this bug in their webpage: https://tree-sitter.github.io/tree-sitter/playground
with this example:
```javascript
class Docstring {
 
    /** DOCSTRING */
    foo1() {
      return;
     }         /*** WEIRD
     
     DOCSTRING
     ***/
    foo2() {
      return;
    }
}
```
I wouldn't know where this bug could be coming from.

**Comment by sogaiu** [comment]
I tried the example out using "Java" as the language.  A brief examination of the tree suggested may be that's what was used.

May be the [tree-sitter-java](https://github.com/tree-sitter/tree-sitter-java) repository is a relevant location?

**Comment by marcosboggia** [comment]
Sorry, I didn't understand you very well but I tried it with "Java" as the language and this issue didn't happened. The thing is that I need this working with javascript. Just to add more info, using Typescript as language reproduces the same bug as with Javascript.

**Comment by sogaiu** [comment]
@marcosboggia I think you wrote:

> I wouldn't know where this bug could be coming from.

It's often the case that the grammar for each programming language has its own repository.  FWIW, many of those are listed here: https://tree-sitter.github.io/tree-sitter/#available-parsers

I didn't see that you mentioned "JavaScript" in your [original post](https://github.com/tree-sitter/tree-sitter/issues/1333#issue-967346056), so I took a quick guess, but that guess was mistaken :)

When you tried your original example, if you chose "JavaScript" and that's what has an issue, then a relevant repository to report that to may be [tree-sitter-javascript](https://github.com/tree-sitter/tree-sitter-javascript/).

**Comment by ahlinc** [comment]
After looking on the `tree-sitter-javascript` [grammar file](https://github.com/tree-sitter/tree-sitter-javascript/blob/master/grammar.js), it's seems that in a case of there are some trailing optionals in a rule definition that don't match it may be reasonable that it make sense that any lexied extras that trails of some sequence of rule candidate tokens to be excluded from reducing action and to be included into an outer rule.

**Comment by marcosboggia** [comment]
Cool, moved to https://github.com/tree-sitter/tree-sitter-javascript/issues/188.
Thanks for your answers! :slightly_smiling_face:

**Comment by ahelwer** [comment]
Thanks @marcosboggia! Could you also close this issue?

**Comment by ahlinc** [comment]
I wasn't clearly explain in my previous comment that I think that @marcosboggia found a corner case in the tree-sitter behavior and that it's related to the tree-sitter's C library. I'm pretty sure that this case can't be solved on the grammar level, so I'll reopen it for now.
@maxbrunsfeld Could you confirm or refute my assumption?

**Comment by maxbrunsfeld** [comment]
I think this is a JavaScript-specific bug, where an `_automatic_semicolon` node is getting created *after* the comment, causing the comment to become part of the `statement_block`.

So I *think* we can close this out in favor of https://github.com/tree-sitter/tree-sitter-javascript/issues/188.
