### ISSUE TITLE
Library storage path cannot be customized in newer versions of tree-sitter-cli

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#1336]
Emacs's [tree-sitter language bundle](https://github.com/emacs-tree-sitter/tree-sitter-langs/) uses tree-sitter-cli to compile language grammars. For predictability, it needs to customize the CLI's library storage path. This was possible (indirectly) by setting the environment variable `TREE_SITTER_DIR`.

#1157 removed that, so newer versions of the CLI cannot be used for this purpose.

I think the library storage path should be explicitly customizable, through either a setting in the config file, a CLI argument, or an environment variable. If we are ok with adding that functionality, I can create a PR for it.

**Comment by maxbrunsfeld** [comment]
Oh, sorry for letting that regress. I'm definitely in favor of adding some way of customizing the directory. I think we should do whatever feels the most standard. Do you have a suggested way of customizing it?

**Comment by ubolonton** [comment]
I think we can support 2 layers of configuration:
- A flag `--lib-dir`.
- A setting in the system-wide `config.json` file: `library-directories`.

**Comment by kiennq** [comment]
Friendly ping on this, do we have a way to configure the lib storage path?
