### ISSUE TITLE
Bug while parsing C++ code with operators declarations

### ISSUE THREAD

**Issue by AlexNisnevich** [tree-sitter/tree-sitter#1338]
I've been playing around with the [tree-sitter playground](https://tree-sitter.github.io/tree-sitter/playground) and have been running into issues parsing some C++ files. I've narrowed the issue down to this minimum viable example:
```cpp
struct A {
	bool operator ==(A other) {
		return true;
	}
};

class B {
	bool operator ==(B other);
};
```

When pasting this valid C++ code into the playground, I get the following tree:
```
translation_unit [0, 0] - [10, 0]
  ERROR [0, 0] - [8, 2]
    type_identifier [0, 7] - [0, 8]
    field_declaration [1, 1] - [4, 2]
      type: primitive_type [1, 1] - [1, 5]
      declarator: field_identifier [1, 6] - [1, 14]
      ERROR [1, 15] - [1, 16]
      default_value: compound_literal_expression [1, 17] - [3, 2]
        ERROR [1, 18] - [1, 19]
          identifier [1, 18] - [1, 19]
        type: type_descriptor [1, 20] - [1, 25]
          type: type_identifier [1, 20] - [1, 25]
        value: initializer_list [1, 27] - [3, 2]
          identifier [2, 2] - [2, 8]
          ERROR [2, 9] - [2, 14]
            true [2, 9] - [2, 13]
      ERROR [4, 0] - [4, 1]
    field_declaration [6, 0] - [8, 2]
      type: class_specifier [6, 0] - [8, 1]
        name: type_identifier [6, 6] - [6, 7]
        body: field_declaration_list [6, 8] - [8, 1]
          field_declaration [7, 1] - [7, 27]
            type: primitive_type [7, 1] - [7, 5]
            declarator: field_identifier [7, 6] - [7, 14]
            ERROR [7, 15] - [7, 16]
            default_value: parenthesized_expression [7, 17] - [7, 26]
              ERROR [7, 18] - [7, 19]
                identifier [7, 18] - [7, 19]
              identifier [7, 20] - [7, 25]
```

Notably, both the `struct_specifier` and `class_specifier` are missing, and the top-level node (under `translation_unit`) is an `ERROR` node.

Interestingly, I can remove either the struct or the class from this example and the parse works fine, but having them both together somehow breaks the parser. 

It appears that the issue has something to do with the `==` operator declarations, because replacing the operator declarations with regular method declarations makes the parse work.

**Comment by ahlinc** [comment]
@AlexNisnevich I think this issue should be moved to a relevant C++ grammar [repository](https://github.com/tree-sitter/tree-sitter-cpp). It's awesome that you've found small reproducing sample.

**Comment by AlexNisnevich** [comment]
Ah good call, reposted to https://github.com/tree-sitter/tree-sitter-cpp/issues/125
