### ISSUE TITLE
tree-sitter tutorial

### ISSUE THREAD

**Issue by guillaumechaumet** [tree-sitter/tree-sitter#135]
Dear Github team,
I want to produce a tree-sitter for R language. Could give me some tips or links to a tutorial ?

Best,

**Comment by maxbrunsfeld** [comment]
Hi @guillaumechaumet! An R parser for Tree-sitter would be great. Here is the current docs site: http://tree-sitter.github.io/tree-sitter. There's not much yet, but I'll be working on improving the docs in the next few months.

**Comment by maxbrunsfeld** [comment]
The source for this documentation is here: https://github.com/tree-sitter/tree-sitter/tree/master/docs.
