### ISSUE TITLE
Error while using parser with Windows x64

### ISSUE THREAD

**Issue by vzytoi** [tree-sitter/tree-sitter#1351]
Hello, I have a weird error when using tree-sitter on windows ...
OS: `Windows 10 (x64)`
Neovim version:
```
NVIM v0.6.0-dev+96-g5f01714b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compilé par runneradmin@fv-az152-272

Features: -acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM\sysinit.vim"
               $VIM par défaut : "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
Here is the error message when i tried to open a files using with tree-sitter enabled : `E5108: Error executing lua Failed to load parser: uv_dlopen: ~\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\parser\javascript.so is not a valid Win32 app`
My tree-sitter configuration: 
````
require('nvim-treesitter.configs').setup({
    ensure_installed = "maintained",
    highlight = {
        enable = true
    },
    indent = {
        enable = true
    },
    autopairs = {
        enable = true
    },
    autotag = {
        enable = true
    }
})
```
Thank you!

**Comment by stsewd** [comment]
Hi, this should be reported to the https://github.com/nvim-treesitter/nvim-treesitter repo, and you can check the wiki for windows support at https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support

**Comment by vzytoi** [comment]
> Hi, this should be reported to the https://github.com/nvim-treesitter/nvim-treesitter repo, and you can check the wiki for windows support at https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support

Ok, thank you
