### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by rjahrj** [tree-sitter/tree-sitter#1352]
Any plans on ARM support. Trying to setup svelte on nvim and its not working, so i went to InstallFromGrammer with the cli and found that it wasnt supported on ARM

**Comment by ahlinc** [comment]
@rjahrj Could you provide some error output?
Did you try to build tree-sitter CLI from sources with the `cargo build --release` command?

**Comment by rjahrj** [comment]
Hey sorry for the late response! I manages to fix my issue! It wasnt on treesitter.
![cargo-treesitter](https://user-images.githubusercontent.com/20189326/130430948-b9de4782-e9bb-4e49-99a7-1fc08e23d74f.png)
![pnpm-tree](https://user-images.githubusercontent.com/20189326/130430969-d2c0808b-d1a4-4116-a993-1a4e2f335675.png)

**Comment by rjahrj** [comment]
I will now try to build from source

**Comment by ahlinc** [comment]
@rjahrj thanks for the update, above is a known issue with crates testing and distribution #1223, I hope it will be fixed with the next release. For workaround you can install CLI with the following command right from the sources:
```
cargo install --git https://github.com/tree-sitter/tree-sitter
```

**Comment by rjahrj** [comment]
That worked for me! Little confusion cuz i was using asdf and didnt realize i had to reshim the rust package!
