### ISSUE TITLE
How to skip any count of children in the tree with query?

### ISSUE THREAD

**Issue by cranberry-clockworks** [tree-sitter/tree-sitter#1355]
Is there a way to skip any count of sub-nodes in the query expression? I know about wildcard node `_` or `(_)` but it skips only one node in the tree. I think I looking for something similar to `.*` in terms of the regular expression.

For example
```scheme
((method_declaration 
  ;... match anywhere in the sub-tree
  (throw_statement) @throw ) @method)
```

**Comment by sogaiu** [comment]
Not quite sure I follow but are you looking for something like this? https://github.com/tree-sitter/tree-sitter/discussions/981

**Comment by amaanq** [comment]
Duplicate of #880
