### ISSUE TITLE
C documentation/tutorial for tree_sitter_highlight?

### ISSUE THREAD

**Issue by ancientstraits** [tree-sitter/tree-sitter#1359]
I wanted to make a program in C that used syntax highlighting, and I thought tree-sitter would be a good option. However, I realized the only documentation for tree_sitter_highlight was for Rust, and for C, there was only a header file `highlight.h`. I thought I could just understand the C functions, but some stuff in `highlight.h` did not make sense, compared to the Rust tutorial:

```c
// Construct a `TSHighlighter` by providing a list of strings containing
// the HTML attributes that should be applied for each highlight value.
TSHighlighter *ts_highlighter_new(
  const char **highlight_names,
  const char **attribute_strings,
  uint32_t highlight_count
);
```

I understand how to use `highlight_names`, but I don't understand what data I should write for `attribute-strings`. I know what a HTML attribute is, and the function is probably asking for a list of them, but I don't understand what the key or value of the HTML  attribute should be.

I also realized that the entirety of the tree_sitter_highlight library is written in Rust, so I am wondering how I am supposed to link the Rust library into C.

I thought I could maybe just use Rust to make the whole project and add `tree-sitter-highlight` as a dependency. However, the `README.md` isn't that great, since it mentions a `tree-sitter-html` crate that doesn't exist anywhere.

After removing `tree-sitter-html` as a dependency, I tried to run `cargo build`, but `tree-sitter-highlight` wont even compile:
```
error[E0107]: this struct takes 2 lifetime arguments but only 1 lifetime argument was supplied
   --> /home/MY_USERNAME/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tree-sitter-highlight-0.19.2/src/lib.rs:104:30
```

So I am wondering how I can even use this library at all.

**Comment by ancientstraits** [comment]
OK. Right now, I am getting done with finally creating a C program that highlights the code, which only uses the treesitter-core library. I think it would be better to write the `tree-sitter-highlight` library in C instead of Rust, since at most you would have 3 stages of abstraction:
`tree-sitter core (C) -> tree-sitter-highlight (C) -> tree-sitter-highlight (Rust)`
Compared to what we have now, which is four layers:
`tree-sitter-core (C) -> tree-sitter-core (Rust) -> tree-sitter-highlight (Rust) -> tree-sitter-core (C)`.

I doubt if anyone has actually used the `tree-sitter-highlight` library in C, and I am not able to compile it successfully until it is finally put on crates.io with version 0.20.0, I do not think the contributors to tree-sitter should work actively on porting `tree-sitter-highlight` to C, I just think it should be a thought in someone's mind.

Right now, my program is nearly done with syntax highlighting, but it doesn't do the whole document. I will keep working on it until it does what I want.

**Comment by ahlinc** [comment]
@ancientstraits Here in the #1363 was a related conversation.

**Comment by ahlinc** [comment]
@ancientstraits You can find a workaround of your compilation error in https://github.com/tree-sitter/tree-sitter/issues/1363#issuecomment-911163367

**Comment by ancientstraits** [comment]
Am not using tree-sitter at this moment, but will see later.
