### ISSUE TITLE
Hidden rule with alias causes an endless loop on generation if put in `externals`

### ISSUE THREAD

**Issue by vigoux** [tree-sitter/tree-sitter#1371]
So when working on [tree-sitter-viml](https://github.com/vigoux/tree-sitter-viml) and especially [this PR](https://github.com/vigoux/tree-sitter-viml/pull/12) I came across the bug mentioned in the title.

After some work on minimizing the example, here is the minimal `grammar.js` that I could make:
```js
module.exports = grammar({
  name: 'foo',

  extras: ($) => [$._weird_alias],

  rules: {
    script: ($) => repeat1('foobar'),
    _weird_alias: ($) => alias('bar', '\\'),
  },
});
```

# Reproducting steps

1. Put this file in your `grammar.js`
2. `tree-sitter generate`
3. Observe the hang

**Comment by CyberShadow** [comment]
Looks very similar to https://github.com/tree-sitter/tree-sitter/issues/1165 and #1062

**Comment by vigoux** [comment]
Any plan on having this issue solved ?
