### ISSUE TITLE
Highlighting test groups priority

### ISSUE THREAD

**Issue by nkrkv** [tree-sitter/tree-sitter#1374]
Hello! I’m not sure whether this belongs to `tree-sitter` or `nvim-treesitter`. I see a mismatch between these on how they arrange `highlights.scm` queries by priority.

I’m making a Tree-sitter parser for the ReScript language and use the `test/highlight` facilities to ensure highlight queries capture things right. So far so good until I have a syntax subtree that is matched by several queries at once. In this case, the test runner of `tree-sitter` takes the first match as the result. And in `nvim-treesitter` highlight is exactly the opposite: the last query effectively wins.

As an example, I’ve compared `highlights.scm` for JavaScript. And indeed,  `tree-sitter/tree-sitter-javascript/queries/highlights.scm` looks like this:

```scheme
(function
  name: (identifier) @function)

; ... la la la

(identifier) @variable
```

whereas `nvim-treesitter/nvim-treesitter/queries/ecma/highlights.scm` looks like:

```scheme
; the very first query
(identifier) @variable

; ... la la la

(function
  name: (identifier) @function)
```

An `(identifier)` indeed might be a variable name or function name depending on the context. And if I swap the order in `nvim-treesitter` the `@variable` group will win and all `(identifier)`’s used as function names will be colored as variables no matter what.

Similarly, if I swap the order in `tree-sitter-javascript`, the tests fail because function names now are captured as simple `@variable` as it goes first.

So, I see no way to satisfy both at once: the original test runner and nvim highlighter.

Is this by design? Should I maintain a different `highlights.scm` for nvim which is reverse of the original?

**Comment by ahlinc** [comment]
I think it's mostly the question for the nvim team, they use only C parts of tree-sitter and built own highligting logic on top of tree-sitter queries. Nvim highlighting has no relation to the `tree-sitter-highlight` Rust library which is used by tree-sitter CLI.

**Comment by nkrkv** [comment]
Thanks for the quick reply. Now I see the difference. I was fooled because the query file is named `highlights.scm` here and there while they have quite different meanings.

It would be great if the test runner was allowed to check for “anywhere in chain” and “exact this chain” matches. So that the same toolchain might be used to develop a general-purpose parser and nvim-specific at the same time. Something like this:

```js
const fn = (x) => x + 1;
//     ^ function!   -- the only exact match
//     ^ [function variable]!  -- exact match
//     ^ [variable]   -- somewhere in chain match
//     ^ [function variable]  -- somewhere in chain sequence match
```

Yep, that’s another story. Just sharing my thoughts.
