### ISSUE TITLE
Arch Linux Neovim 0.5 Tree-Sitter Interface error 

### ISSUE THREAD

**Issue by dedguy21** [tree-sitter/tree-sitter#1375]
Neovim checkhealth:
ERROR: Impossible to load parser for interface: Failed to load parser:             uv_dlsym: /usr/share/nvim/runtime/parser/interface.so: undefined symbol:             tree_sitter_interface

Not sure what the issue is, or how to resolve it.

**Comment by bfredl** [comment]
Probably more relevant to post this at https://github.com/nvim-treesitter/nvim-treesitter/
