### ISSUE TITLE
Strict parsing vs relaxed parsing

### ISSUE THREAD

**Issue by nkrkv** [tree-sitter/tree-sitter#1380]
Hello! I’m working on a parser for the ReScript language and there’s one question I ask myself again and again: how strict should I be about the grammar, is it OK to intentionally allow invalid AST?

Imagine, there’s a language that has constructors. Constructors have formal parameters. There might be from 0 to infinity parameters. And that’s expressed in `grammar.js`.

Then, I’m adding support for another concept: exceptions. Imagine the exceptions are very like constructors but they are allowed to have exactly one parameter. So, here’s a decision point. I either:

- Explain the exceptions strictly having one parameter. So that if a user makes a mistake providing two or zero (just typing), he potentially breaks the whole highlighting/folds/etc right from the mistake point. At the very best, he breaks highlighting after the first parameter until the closing `)`
- Reuse the very similar `$.constructor_parameters` rule (possibly with an alias) and let the exceptions have any number of parameters (which is formally incorrect), make highlighting more stable, and rely on the LSP/compiler to show that it’s invalid to a user

It’s a pretty synthetic example but I hope it explains the idea. I’ve stumbled on this question several times already. Is there an idiomatic way recommended by Tree-sitter authors?

**Comment by maxbrunsfeld** [comment]
You should make the grammar less strict and simpler.

If the user accidentally writes an exception with more than one parameter, it's better to treat that as a *semantic* error, not a syntax error. You probably want an error message like `Exceptions can only have one parameter` (which you could generate yourself, in your own code, by inspecting the valid syntax tree). I don't think you want an error message like `Syntax error, unexpected comma`, which is the best you could really do if you encoded this constraint in the grammar.

**Comment by nkrkv** [comment]
Makes perfect sense, thank you!
