### ISSUE TITLE
Need a way to enable assertions with `tree-sitter build-wasm`

### ISSUE THREAD

**Issue by hsenag** [tree-sitter/tree-sitter#1389]
I'm getting an error from tree-sitter running in wasm:

`RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.`

Unfortunately I can't find a way to actually build with `-s ASSERTIONS=1`, which I believe should be passed to `emcc`. We build the wasm via `npx tree-sitter build-wasm --docker` and having looked at [the code for that](https://github.com/tree-sitter/tree-sitter/blob/e7d3b294709f9fdb1bcff4062f296b943527d2e6/cli/src/wasm.rs#L73), I don't see a way to pass any extra flags.

The [`build-wasm` script](https://github.com/tree-sitter/tree-sitter/blob/4d64c2b939d4bb1074b5ae5631cf2616368f78d8/script/build-wasm#L22), which I think builds tree-sitter itself rather than a specific grammar, does actually have a `--debug` flag that will do this, so maybe the right way to do this is to add a similar flag?

**Comment by patrickt** [comment]
Yeah, the right thing to do is to provide a boolean flag to `compile_language_to_wasm` that determines whether or not `-s ASSERTIONS=1` is passed. The callsite is [here](https://github.com/tree-sitter/tree-sitter/blob/6c66b5ee296de5207eec732ca8e58c99b8ea1dd3/cli/src/main.rs#L500-L503), so you’d just put the argument-matching code there and pass the derived boolean.

**Comment by hsenag** [comment]
Plus I think it'd need a `.arg` [here](https://github.com/tree-sitter/tree-sitter/blob/6c66b5ee296de5207eec732ca8e58c99b8ea1dd3/cli/src/main.rs#L209).

**Comment by maxbrunsfeld** [comment]
I think it’s the core library that needs to be comped with assertions enabled, not the language-specific parser.

you can do this by running ‘script/build-wasm —debug’ in the tree-sitter repo. The JS and WASM output files get created in the ‘lib/binding-web’ folder.

**Comment by hsenag** [comment]
Thanks! Yes, you're right, just doing that was enough to get rid of part of the message about `-s ASSERTIONS=1`. Sadly now I just have `RuntimeError: abort(Assertion failed: undefined).` and a longer useless stack trace in `worker.js` so it didn't actually help :-)
