### ISSUE TITLE
get_column seems to return byte count, not codepoint count

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/tree-sitter#1405]
Using tree-sitter-cli 0.20.0. From [the docs](https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners) (emphasis mine):
 > `uint32_t (*get_column)(TSLexer *)` - (Experimental) A function for querying the current column position of the lexer. **It returns the number of unicode code points (not bytes) since the start of the current line.**

I tested this with the following grammar, which will match any sequence of `x` (U+0078) and `∧` (U+2227), where the `external_token` consumes nothing but is used to print out `get_column` values:
```js
module.exports = grammar({
  name: 'test',
  
  externals: $ => [
    $.external_token
  ],

  rules: {
    source_file: $ => repeat(seq($.external_token, $.codepoint)),
    codepoint: $ => choice('x', '∧')
  }
})
```
and the following `scanner.cc`:
```c++
#include <tree_sitter/parser.h>
#include <cstdio>

enum TokenType {
  EXTERNAL_TOKEN
};

extern "C" {
  void * tree_sitter_test_external_scanner_create() { return NULL; }
  void tree_sitter_test_external_scanner_destroy(void *payload) {}
  unsigned tree_sitter_test_external_scanner_serialize(void *payload, char *buffer) { return 0; }
  void tree_sitter_test_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {}

  bool tree_sitter_test_external_scanner_scan(
    void *payload,
    TSLexer *lexer,
    const bool *valid_symbols
  ) {
    while (' ' == lexer->lookahead) { lexer->advance(lexer, true); }
    uint32_t col = lexer->get_column(lexer);
    printf("NEXT: [%X] COL: [%d]\n", lexer->lookahead, col);
    return !lexer->eof(lexer);
  }
```
When tested on a file containing `x∧x∧`, the output of `tree-sitter parse` is:
>NEXT: [78] COL: [0]
NEXT: [2227] COL: [1]
NEXT: [78] COL: [4]
NEXT: [2227] COL: [5]
NEXT: [0] COL: [8]
(source_file [0, 0] - [0, 8]
  (external_token [0, 0] - [0, 0])
  (codepoint [0, 0] - [0, 1])
  (external_token [0, 1] - [0, 1])
  (codepoint [0, 1] - [0, 4])
  (external_token [0, 4] - [0, 4])
  (codepoint [0, 4] - [0, 5])
  (external_token [0, 5] - [0, 5])
  (codepoint [0, 5] - [0, 8])

So `get_column` prints out the bytes, not the codepoints, since the start of the line.

**Comment by maxbrunsfeld** [comment]
Oh yeah, we need to change the docs. `get_column` returns the column in bytes now.

**Comment by maxbrunsfeld** [comment]
Sorry for the wrong docs.

**Comment by ahelwer** [comment]
@maxbrunsfeld was this part of that change that improved the runtime performance of `get_column`? Unfortunate... I often need to know the column position in TLA+, in terms of codepoints. Is there any workaround you can think of?

**Comment by maxbrunsfeld** [comment]
Are you just using `get_column` to detect indentation level?

If so, I would recommend not using `get_column` at all, and counting the leading whitespace characters in your external scanner, starting from the beginning of the line. Would that work for your use case?

**Comment by ahelwer** [comment]
@maxbrunsfeld unfortunately not quite. I have nested conjunction lists of this type:
```
op ≜ ∧ A
     ∧ ∧ B
       ∧ C
     ∧ D
```
Where the B/C conjunction list is decided by the vertical alignment of the `∧` character (the font used by github doesn't render `∧` or `≜` in monospace which somewhat ruins this effect). I suppose what I could do is add something like `seq(/\r?\n/, $._external_token)` to my `extras`, then after every newline there will be a call into my external scanner where I just read the entire line into the scanner state; I can then later traverse this string to determine the number of codepoints prior to the `get_column` byte index, or something like that. It will be difficult to get this to play well with the rest of my external scanner though, which itself usually reads past newlines.

**Comment by ahelwer** [comment]
@maxbrunsfeld would you be interested in a PR to turn `get_column` back into a codepoint counter, if it were possible to do that without any performance impact? Or was there a different reason why it switched to being a byte counter?

**Comment by maxbrunsfeld** [comment]
Yeah, I'd be open to it. The main reason that I switched it to counting bytes were for simplicity and performance, and since all other `column` values in Tree-sitter are bytes. But I can see how code points could be more useful.

**Comment by ahelwer** [comment]
@maxbrunsfeld would it be considerably more complicated than adding an extra field to the lexer keeping track of the number of times advance has been called since seeing a newline? Would it also require some logic to handle resetting that value upon calling goto on the lexer?

**Comment by ahlinc** [comment]
I'd suggest to consider an option to extend the `get_column()` and add there a flag that would allow to choice what to return, count of bytes or unicode code points.

**Comment by maxbrunsfeld** [comment]
> Would it also require some logic to handle resetting that value upon calling goto on the lexer?

Yes, this will be the challenge. The lexer frequently gets reset back to an arbitrary byte offset in the source code. We don't store character counts in the syntax tree, because it would bloat the memory footprint of the syntax tree significantly. So I think the best approach is to do some extra work when `get_column()` is called, to rederive the character count from the byte offset.

We used to do this, but it was buggy. In https://github.com/tree-sitter/tree-sitter/pull/978 (along with other fixes to the tracking of column changes), I decided to eliminate the character-counting bug by simply removing that feature and returning the byte count. Maybe this was the wrong move though.

It's definitely doable to restore the old character-counting behavior and just fix the bug.

**Comment by ahelwer** [comment]
@maxbrunsfeld given the performance cost and additional complexity, do you think it's worth defining a separate `get_codepoint_column()` method or a flag as suggested by @ahlinc? Is the C library in `lib` distributed with grammars themselves, or linked to in some way?

**Comment by ahelwer** [comment]
Since I need to use this feature in the immediate future for a demo, I've thrown together a fork release here:
- https://github.com/tlaplus-community/tree-sitter/tree/get-codepoint-column
- https://github.com/tlaplus-community/tree-sitter/releases/tag/v0.20.1-1
- https://www.npmjs.com/package/@tlaplus/tree-sitter-cli/v/0.20.1-1

and built a fork release of neovim 0.5.1 with the updated tree-sitter library here:
- https://github.com/tlaplus-community/neovim/releases/tag/v0.5.2

I'll publish a PR of the changes once I get good test coverage. To that end @maxbrunsfeld since I'm developing this on Windows, could you check out these PRs so I don't need to sort through the CRLF test failures?
- https://github.com/tree-sitter/tree-sitter-ruby/pull/189
- https://github.com/tree-sitter/tree-sitter/pull/1412 (hold off on signing off on this one until the ruby changes are merged, I want to add windows tests to the github CI to prevent regressions)

Isn't open source great? I can just do all this stuff without waiting for it to work its way through the release pipeline!

**Comment by maxbrunsfeld** [comment]
Nice work @ahelwer! I merged that Tree-sitter-ruby PR.

You're right that we can't change the signature of `get_column`. If we added a separate `get_codepoint_column` method, then we'd need to bump the `TREE_SITTER_LANGUAGE_VERSION` constant in `api.h`, so that grammars *using* the new method would fail to load with previous versions of the library.

I actually think that we should just change the behavior of the existing method. Not many grammars use it, it is marked as "experimental" in the docs, and in an earlier version of the library, it used to return the number code points.

**Comment by maxbrunsfeld** [comment]
@ahelwer Just checking in about this - is everything working fine in your testing of the new behavior in your fork of Neovim?

**Comment by ahelwer** [comment]
@maxbrunsfeld just tried it out with neovim nightly - works great!

![image](https://user-images.githubusercontent.com/718765/150805801-6778988c-4c6c-42b5-b5fd-23c8f0d089da.png)

The `∧` symbols are only highlighted brown if they have the same `get_column` value as the one above them.
