### ISSUE TITLE
Refactored playground.js

### ISSUE THREAD

**Issue by calicoday** [tree-sitter/tree-sitter#1418]
I've refactored the playground.js to DRY it up a little and distinguish the bits that relate to the browser UI and those that relate to Tree-sitter. I think the way to offer material is a pull request (even if it may be of no interest at all) but I haven't done that before, so I'm checking here first. 

I believe I've matched the current behaviour but that I:
- added a flag to disable load/save state and use a fixed input sample.
- added a flag to add the parse count to the parse time display.
- left in `const scriptURL = ...` but commented out (isn't used in the file but I don't know what it's meant to be for)

You can see my version in this gist:

https://gist.github.com/calicoday/9fc904ee620bfaeffb8d5dfc6fe98a28

**Comment by dundargoc** [comment]
PRs welcome

**Comment by calicoday** [comment]
Thanks. Been trying to find time to do that since I posted (haven't set up to submit PRs before). It was here in case someone else wanted to take it farther. :-)
