### ISSUE TITLE
Failed to load the grammar package

### ISSUE THREAD

**Issue by banacorn** [tree-sitter/tree-sitter#143]
I'm working on a tree-sitter grammar for Agda.
But then I came across this error when I was trying to load the developing grammar package.

```
The module '/Users/banacorn/node/tree-sitter-agda/build/Release/tree_sitter_agda_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`). in /Users/banacorn/.atom/dev/packages/language-agda/grammars/tree-sitter-xagda.cson
```
I've followed the instructions of [this thread](https://discuss.atom.io/t/help-setting-up-tree-sitter-grammar-development/52113) and spent hours fiddling with stuff but end up with nothing :(

Here's the version of Atom I'm running:
```
Atom    : 1.25.0-beta3
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0 
```

**Comment by maxbrunsfeld** [comment]
You can use the `apm rebuild` command to rebuild an Atom package's dependencies to compile against Atom's version of node. So if you have a package called `language-agda` that uses `tree-sitter-agda` as a dependency, you could run `apm rebuild` from the `language-agda` directory.

**Comment by banacorn** [comment]
I ran `apm-beta rebuild` in `language-agda` and then `atom-beta -d` to see if the package has been loaded, but then the whole editor (atom-beta) became frozen and not responding.

From `atom-beta -v`:
```
Atom    : 1.25.0-beta3
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```
From `apm-beta -v`:
```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0-beta3
python 2.7.10
git 2.14.3
```

**Comment by clojj** [comment]
same here
![versions](https://user-images.githubusercontent.com/4367963/37390028-c2fd0edc-2766-11e8-8a4c-fbe18c377015.png)
see also https://github.com/tree-sitter/tree-sitter-haskell/issues/10

**Comment by banacorn** [comment]
@clojj I've also tried `electron-rebuild` and ended up the same way.

**Comment by clojj** [comment]
> same way
meaning still this error ?
for me the error was gone

**Comment by banacorn** [comment]
@clojj sorry for my late reply.
I'm considering closing this issue as the problem seems to have gone away since the release of Atom 1.25 yesterday. Would you mind opening another issue if there's still any?
