### ISSUE TITLE
Unicode categories are missing some CJK characters that are formatted differently in the Unicode data tables

### ISSUE THREAD

**Issue by razzeee** [tree-sitter/tree-sitter#1432]
Hey everybody,

I've been using `\p{Lu}[_\d\p{L}]*` since https://github.com/tree-sitter/tree-sitter/pull/906 landed.
Now a user came up with this issue: https://github.com/elm-tooling/tree-sitter-elm/issues/105

I'm not to sure if that should work or not. Testing with https://regex101.com/ gives various results, depending on the engine used.

And tree sitter being it's own engine, leads to me being unsure, what's expected.

**Comment by maxbrunsfeld** [comment]
That's interesting.

[This](https://github.com/tree-sitter/tree-sitter/blob/master/script/generate-unicode-categories-json) is the script that we use to build the mappings from those character categories into sets of concrete code points. If you're interested, you could consult the unicode sources that the script pulls from, and see if that japanese character is intended to belong to that category.

Maybe there is some tweak that we could make to the way that we interpret the categories.

**Comment by razzeee** [comment]
Are there any plans to work on this? I have more and more users finding this in different languages.

**Comment by razzeee** [comment]
FYI, I'll just revert this for the time being https://github.com/elm-tooling/tree-sitter-elm/pull/112

**Comment by alemuller** [comment]
By the way, there is Unicode Technical Standard for regular expressions: [UTS #18](https://unicode.org/reports/tr18/).

**Comment by invrainbow** [comment]
I got this working in tree-sitter-go with an external scanner:
https://github.com/tree-sitter/tree-sitter/issues/1726#issuecomment-1113927439

**Comment by amaanq** [comment]
Fixed in https://github.com/tree-sitter/tree-sitter/pull/3831, now we no longer bundle these unicode tables.
