### ISSUE TITLE
Query with mismatched parentheses parses but does not match anything

### ISSUE THREAD

**Issue by tausbn** [tree-sitter/tree-sitter#1436]
The following query (when applied to, say, the Python source `+5`) produces no output, but does not cause any errors either, even though it is missing a parenthesis:
```
[ 
    (unary_operator (_) @operand) 
    (not_operator (_) @operand
] @unaryop
```
If the missing parenthesis is added back, then it works as expected (and finds a match in the aforementioned source code).

**Comment by maxbrunsfeld** [comment]
Oops! Thanks for the report Taus. Fixed on master.
