### ISSUE TITLE
possible to generate 'flat' expressions?

### ISSUE THREAD

**Issue by bostick** [tree-sitter/tree-sitter#1451]
I am learning about Tree-sitter and I am trying to create a grammar that has a wide variety of rules.

One problem that I am wondering about is generating 'flat' expressions.

I mean given the input:

`a + b + c`

being able to generate the tree:

```
(source_file [0, 0] - [1, 0]
  (infix_expression [0, 0] - [0, 9]
    (identifier [0, 0] - [0, 1])
    (identifier [0, 4] - [0, 5])
    (identifier [0, 8] - [0, 9])))
```

You see that all 3 identifiers are at the same level.

e.g., naively trying this does not work:

```
infix_expression: $ => choice(
    prec(86, seq($._expression, repeat1(seq('+', $._expression)))),
),
```

That rule still results in the nested tree structure:

```
(source_file [0, 0] - [1, 0]
  (infix_expression [0, 0] - [0, 9]
    (identifier [0, 0] - [0, 1])
    (infix_expression [0, 4] - [0, 9]
      (identifier [0, 4] - [0, 5])
      (identifier [0, 8] - [0, 9]))))
```

And that makes sense, because 1 repeat does satisfy the rule.

But I am wondering if it is possible to express this 'flatness' with Tree-sitter grammar.

**Comment by ahelwer** [comment]
https://github.com/tree-sitter/tree-sitter/discussions/1429
