### ISSUE TITLE
Playground freezes when specifying named fields on wildcard nodes

### ISSUE THREAD

**Issue by tausbn** [tree-sitter/tree-sitter#1458]
Take the following Python code
```python
1
```
and the following query
```
(binary_operator
    left: (integer)
)
```
If we change `binary_operator` to `_`, then the playground freezes and the page has to be forcibly reloaded.

Curiously, this does not appear to happen when run using the CLI, which suggests that perhaps this bug has been fixed already, and that all that is needed is an update of the website.

**Comment by maxbrunsfeld** [comment]
Ok, this appears to be resolved after updating the `.wasm` file on [tree-sitter.github.io](https://github.com/tree-sitter/tree-sitter.github.io). Thank you!
