### ISSUE TITLE
Should tree-sitter-cli really be added as one of dependencies in parser?

### ISSUE THREAD

**Issue by yudai-nkt** [tree-sitter/tree-sitter#146]
Since Atom 1.25.0 has been released a few hours ago, I started learning tree-sitter and read the documentation. In the [Installing the tools](https://tree-sitter.github.io/tree-sitter/creating-parsers.html#installing-the-tools) section, I found the following statement.

> Add `tree-sitter-cli` to the `dependencies` section of `package.json`

In my understanding, however, `tree-sitter-cli` serves as kind of a build tool and is not of much use for the end users (e.g., authors of Atom's language packages). Therefore, I suppose it should be added as a `devDependencies` just like the libraries in this organization do.

I could prepare a PR regarding this point, but before that I want to know if I'm right or not.

**Comment by maxbrunsfeld** [comment]
The `tree-sitter-cli` module (which serves as a build tool, as you say) is *not* a dependency of Atom. There is a separate npm module called `tree-sitter` that implements Tree-sitter's runtime API. That module is a production dependency of Atom.

**Comment by yudai-nkt** [comment]
Sorry, the issue title was wrong. I understand the difference between `tree-sitter` and `tree-sitter-cli` and was talking about the latter. The quoted text in my opening post seems to indicate something like

```json
{
  "name": "tree-sitter-whatever",
  "version": "0.0.0",
  "description": "Whatever grammar for tree-sitter",
  "main": "index.js",
  "dependencies": {
    "tree-sitter-cli": "x.y.z"
  }
}
```
Taking `tree-sitter-go` for example, its `package.json` uses `devDependencies` field to describe the dependency on `tree-sitter-cli` and I think this is the right place.

In other words, `tree-sitter-cli` is needed to develop `tree-sitter-whatever`, not in order to use it, doesn't it?

**Comment by maxbrunsfeld** [comment]
Oh I’m sorry; I didn’t realize you were talking about an error in the docs. You’re totally right; the docs should be changed to suggest devDependencies, not dependencies.
