### ISSUE TITLE
validate scanner compilation object in tree-sitter generate

### ISSUE THREAD

**Issue by milahu** [tree-sitter/tree-sitter#1465]
`tree-sitter generate` should validate the compilation result of

```
gcc -c scanner.c
g++ -c scanner.cpp
...
```

```
nm scanner.o | grep _external_scanner_
0000000000000d00 T tree_sitter_some_parser_external_scanner_create
0000000000000ec0 T tree_sitter_some_parser_external_scanner_deserialize
0000000000000e40 T tree_sitter_some_parser_external_scanner_destroy
0000000000001020 T tree_sitter_some_parser_external_scanner_scan
000000000000002c t tree_sitter_some_parser_external_scanner_scan.cold
0000000000000d30 T tree_sitter_some_parser_external_scanner_serialize
```

in this case, `some_parser` MUST match the parser name, as declared in `grammar.js`

```js
  // grammar.js
  name: 'some_parser',
```

... otherwise using the parser throws

```
undefined symbol: tree_sitter_some_parser_external_scanner_create
```

related https://stackoverflow.com/questions/61868994/how-do-i-compile-tree-sitter-parsers/69768181#69768181

**Comment by woolsweater** [comment]
+1 This is a mild workflow irritation when working on a grammar. Running `tree-sitter generate` appears to succeed, then running `tree-sitter test` fails with an error in the external scanner. It would be preferable to have the build step build the whole language.

**Comment by amaanq** [comment]
Hey, I've implemented this for Unix-like operating systems, but not Windows. Hope that helps!

**Comment by milahu** [comment]
ideally this check should be more strict
to avoid build errors in downstream projects
where multiple parsers are linked into one binary

the parsers should export only the required symbols
`tree_sitter_some_parser_external_scanner_create` etc
and all other symbols should be private = static helper functions

see also
https://github.com/tree-sitter/tree-sitter-html/issues/63
https://github.com/grantjenks/py-tree-sitter-languages/issues/55

**Comment by amaanq** [comment]
@milahu we have a warning I added kinda recently to check for the usage of non static symbols that are *not* `tree_sitter_xxx`, here's an example

![image](https://github.com/tree-sitter/tree-sitter/assets/29718261/fe5b2178-aa08-4f75-acb1-3bd4ef844087)

I don't think this should be an error personally but I'm open to being convinced, the motivation for the warning was literally from those conflicts i solved in html/php :)

**Comment by milahu** [comment]
aah, nice : )

> I don't think this should be an error

true, its better to show a warning

i have fixed https://github.com/grantjenks/py-tree-sitter-languages/issues/55
by keeping each parser in a separate binary
so this also works with "broken" parsers
