### ISSUE TITLE
parsing token by token or parsing chunk by chunk of text

### ISSUE THREAD

**Issue by JessicaLopezEspejel** [tree-sitter/tree-sitter#1481]
Hello, how can I use your parser to work as I explain in the following lines?

``` 
code = 'System'
code = 'System.'
code = 'System.out'
code = 'System.out.' 
code = 'System.out.println' 
code = 'System.println('
code = 'System.println("hello")
```

It means, the parser should be able to detect that the java syntax is doing well at each time I add one or more tokens. I tried using tree-sitter, but it did work and I do not know if there is a trick.

The code I tested is:

```
from tree_sitter import Language, Parser
JAVA_LANGUAGE = Language('parser/my-languages.so', 'java') 
parser = Parser() 
parser.set_language(JAVA_LANGUAGE)
code = 'System.' #.out.println("hello");  
tree = parser.parse(bytes(code,'utf8')).root_node 
subtree= [x[0] for x in get_all_sub_trees(tree)]
```

When  ```code = 'System.out.println("hello"); ``` works, but when ```code = 'System' ``` fails

Thank you in advance

**Comment by maxbrunsfeld** [comment]
With Tree-sitter, you need to have the entire text available before you can start parsing. It doesn't all need to be stored in a single string/buffer, but you do need to have it available via a callback.

I think there are some other parsing systems where you can externally "drive" the parsing process with partial content, but Tree-sitter isn't currently designed to do that. Good luck!
