### ISSUE TITLE
documentation:  end of input signaled to an external scanner as '\0' lookahead character

### ISSUE THREAD

**Issue by dneto0** [tree-sitter/tree-sitter#1482]
I was reviewing an external scanner and confused by the handling of a `\0` lookahead.
See [this line](https://github.com/tree-sitter/tree-sitter-rust/blob/cc7bdd3e6d14677e8aa77da64f6a3f57b6f8b00a/src/scanner.c#L153) in the rust scanner.

At first I though it was trying to handle NUL character on the input stream.

But then, after reading the treesitter lexer code, it seems end of input is signaled by TSLexer  `lookahead = '\0` and lookahead_size = 1
Example: 
* https://github.com/tree-sitter/tree-sitter/blob/67de9435b109f9bd8bf5957d11ff13161966d262/lib/src/lexer.c#L150
* https://github.com/tree-sitter/tree-sitter/blob/master/lib/src/lexer.c#L79
* https://github.com/tree-sitter/tree-sitter/blob/master/lib/src/lexer.c#L203

I think this is missing from the description of the API for extenernal scanners: https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners

**Comment by razzeee** [comment]
I think they should use `eof` instead

https://github.com/elm-tooling/tree-sitter-elm/commit/efd8f9d250e0af844158e3a6f119461756e59048

**Comment by amaanq** [comment]
Yeah, to check if we're truly at `eof` and not just the `NUL` byte in the source code, you should call the `eof` function on the lexer.
