### ISSUE TITLE
`tree-sitter test` fails with "Stderr: Undefined symbols for architecture x86_64"

### ISSUE THREAD

**Issue by matthew-dean** [tree-sitter/tree-sitter#1497]
I'm just getting started trying out tree-sitter, and when I run `tree-sitter test` on a simple grammar (just extending the `css` grammar), I get:
```
Stderr: Undefined symbols for architecture x86_64:
  "_tree_sitter_less_external_scanner_create", referenced from:
      _tree_sitter_less.language in parser-aa10e0.o
  "_tree_sitter_less_external_scanner_deserialize", referenced from:
      _tree_sitter_less.language in parser-aa10e0.o
  "_tree_sitter_less_external_scanner_destroy", referenced from:
      _tree_sitter_less.language in parser-aa10e0.o
  "_tree_sitter_less_external_scanner_scan", referenced from:
      _tree_sitter_less.language in parser-aa10e0.o
  "_tree_sitter_less_external_scanner_serialize", referenced from:
      _tree_sitter_less.language in parser-aa10e0.o
ld: symbol(s) not found for architecture x86_64**
**
```
I don't see anything in https://tree-sitter.github.io/tree-sitter/creating-parsers that I missed, in terms of setup.

My system is macOS 11.6 with Xcode command line tools installed.

**Comment by matthew-dean** [comment]
Oh. It's caused by doing:
```
const css = require('tree-sitter-css/grammar')
module.exports = grammar(css, { ...
```
I was following the thread here: https://github.com/tree-sitter/tree-sitter/issues/645

Is this because of a mis-matched version of `tree-sitter`? What must be done to make a grammar extendable / compilable?

**Comment by matthew-dean** [comment]
It looks like the use of an external scanner in `tree-sitter-css` might cause the tree-sitter bug.

**Comment by maxbrunsfeld** [comment]
You just need to define the external scanner functions for less.

Did you copy and paste the CSS external scanner file? The function names need to match your language’s name.

**Comment by matthew-dean** [comment]
No, I didn't create or define external scanner functions, so there are none to reference. By requiring a project that _has_ external scanner functions, it seems to think those particular functions exist.

**Comment by maxbrunsfeld** [comment]
Ok, so you need an external scanner for this since the CSS grammar, which you’re extending, declares external tokens, using the 'externals’ field.

**Comment by matthew-dean** [comment]
Hmm ok
