### ISSUE TITLE
Playground is down

### ISSUE THREAD

**Issue by sguillia** [tree-sitter/tree-sitter#1498]
Hi!
Playground is down
![Capture du 2021-11-22 10-32-07](https://user-images.githubusercontent.com/15984272/142836915-ae411e1c-b1cd-4f43-a18f-03cab1f1413c.png)
https://tree-sitter.github.io/tree-sitter/playground

HTTP 404 - GET https://tree-sitter.github.io/tree-sitter/assets/js/tree-sitter.wasm

**Comment by maxbrunsfeld** [comment]
Thanks!  Fixed in https://github.com/tree-sitter/tree-sitter/commit/224e79ca27a2d1d7c0ea4b312ba850ea69e37c40.
