### ISSUE TITLE
Parsing HTML templates in JavaScript as HTML

### ISSUE THREAD

**Issue by bennypowers** [tree-sitter/tree-sitter#150]
Hello All!

Was super excited to download 1.25 and switch on the tree-sitter parser flag. So far so good! 👍 👍 

I'm using a neat new library called [lit-html]() to build HTML templates in Javascript. A typical lit-html template might look like this:

```js
const breadcrumbTemplate = ({name}) => html`
  <ul id="breadcrumb" aria-label="Breadcrumb">
    <li><a href="/">Home</a></li>
    <li aria-current="page">${name}</li>
  </ul>
`;
```

or like this (if using the lit-extended variety)
```js
const restaurantView = (restaurant = {}) => html`
  <restaurant-view restaurant="${restaurant}" on-review-submitted="${event => updateReviews(event}">
    ${restaurantId ? fetchReviews(restaurantId).then(reviewsList) : Promise.resolve([])}
  </restaurant-view>
`;
```

Maybe you can see right here in this issue how GitLab Flavoured Markdown parses the contents of the html-tagged template string as html code. That's basically my request here:

How can I hook it up so that tree-sitter parses the html in the template as html, but still shows the js expressions inside the `${}`s as JS?

Here's how it looks on my screen right now.

<img width="794" alt="screen shot 2018-03-18 at 19 15 22" src="https://user-images.githubusercontent.com/1466420/37568649-c738446c-2ae0-11e8-85a7-49d105e13741.png">

A follow on from this specific (syntax highlighting) request would be to fold html within the template, as current behavior folds the entire template (even if it's many paragraphs long) whenever I fold anywhere in the template string.

I'm happy to contribute, but would appreciate a little guidance on where to start looking, since I'm relatively unfamiliar with the atom codebase.

Thanks for considering this issue and keep up the great work!

**Comment by bennypowers** [comment]
I just discovered this behavior:

Step 1: add a single quoted string to template

<img width="872" alt="screen shot 2018-03-23 at 12 39 54" src="https://user-images.githubusercontent.com/1466420/37822417-69457f54-2e97-11e8-9dd5-00f6ead2af3b.png">

Step 2: open the quote, see html highlighting

<img width="866" alt="screen shot 2018-03-23 at 12 40 00" src="https://user-images.githubusercontent.com/1466420/37822447-83d273e0-2e97-11e8-8243-38f475b53940.png">

I supposed this changes this issue from a feature request to a bug report

**Comment by maxbrunsfeld** [comment]
Hey, sorry for the lack of response. Just letting you know that we're going to be starting on this feature (and other cases of language nesting, like JS inside of script tags) this week. I'm not sure how long it'll take before it's shipped in Atom.

**Comment by maxbrunsfeld** [comment]
This feature was implemented in https://github.com/atom/atom/pull/17551. It will ship in Atom 1.30, or 1.30-beta if you're so inclined.

**Comment by maxbrunsfeld** [comment]
There is now explicit documentation for this library feature: http://tree-sitter.github.io/tree-sitter/using-parsers#multi-language-documents.
