### ISSUE TITLE
run-fuzzer is broken

### ISSUE THREAD

**Issue by MDeiml** [tree-sitter/tree-sitter#1501]
I think `script/run-fuzzer` is broken at the moment since it still expects fuzzers to be built in halt and recovery mode. But this is not the case since 7de36a33eba1a911118623e5b5c51ada99ae17d3.

**Comment by maxbrunsfeld** [comment]
Yeah, thanks for pointing that out. Ideally, I'd love to make it as easy as possible to fuzz a Tree-sitter parser, but I'm not very familiar with the current best tools for fuzzing. Those scripts were maintained by the security team at GitHub for a while, but now nobody is maintaining them.

If you have suggestions for Tree-sitter CLI features that would make it easier to fuzz your parser, let me know.

**Comment by amaanq** [comment]
I've updated the fuzzer script
