### ISSUE TITLE
Can I use multiple ts_tree_edit calls before calling ts_parser_parse_string_encoding?

### ISSUE THREAD

**Issue by gregnis** [tree-sitter/tree-sitter#1505]
I couldn't find anything in the source code or documentation about this but my scenario is that I have multiple edits, the old tree, and the new buffer (the result of these edits). My approach is:

for (auto edit : *inputEdits)
{
       ts_tree_edit(pOldTree, &edit);
}
tree = ts_parser_parse_string_encoding(_parser, pOldTree, (const char*)buf, sz, TSInputEncoding::TSInputEncodingUTF16);

This often works but sometimes does not (the code above is executed form a lazy thread after several edits have accumulated). Is this a valid approach?

Thanks.

**Comment by amaanq** [comment]
Yes, this is allowed.
