### ISSUE TITLE
cursor.goToParent does not work

### ISSUE THREAD

**Issue by sguillia** [tree-sitter/tree-sitter#1506]
Hi!

It seems like `ts_tree_cursor_goto_parent` cannot go to parent, even when the current node has a parent.

Here is an example repo. It contains a minimal example with both node and wasm bindings.
https://github.com/sguillia/tree-sitter-repro-II

As it affects several bindings, I assume the issue affects tree-sitter core and not a specific binding

```js
const tree = parser.parse("let a = 0")

const cursor = tree.rootNode.firstChild.walk() // lexical_declaration

console.log(cursor.gotoParent()) // why false?
```

**Actual behavior**
prints false

**Expected behavior**
prints true

In the case this is intended behavior (cursors cannot walk above the node at which the cursor was created) then perhaps the [documentation](https://tree-sitter.github.io/tree-sitter/using-parsers#walking-trees-with-tree-cursors) could mention the limitation?

Thank you

**Comment by ahlinc** [comment]
Duplicates #567
