### ISSUE TITLE
Sibling Captures

### ISSUE THREAD

**Issue by caojoshua** [tree-sitter/tree-sitter#1508]
Is it possible to capture a list of sibling nodes? For example

With python code:
```
#foo
#bar
```

And query:
```
(
    (comment)
    (comment)
) @foo
```

Only matches the first comment `#foo`, but not second comment `#bar`. This applies the same for other languages in playground.

I believe the same applies to `*` and `+` quantification operators in that only one node is matched in each capture.

My understanding is that `TSQueryCapture` is associated with only a single node, which would make this impossible. Is this all expected behavior? Is there possibility of associating a capture with an array of nodes?

**Comment by Symbolk** [comment]
Agreed, this could be really useful for queries like "all methods with comments before it", for now I failed to do this with the following query:
```java
(class_body 
	(
        (block_comment)
        (method_declaration)
    ) @only_comment_captured
)
```

**Comment by maxbrunsfeld** [comment]
To capture two adjacent comments (both with the capture name `foo`):

```clj
(
  (comment) @foo
  .
  (comment) @foo
)
```

To capture an arbitrary number of adjacent comments, all with the capture name `foo`:

```clj
(comment)* @foo
```

To capture a block comment adjacent to a method declaration:

```clj
(class_body 
  (block_comment) @comment
  .
  (method_declaration) @method
)
```

**Comment by Symbolk** [comment]
> To capture two adjacent comments (both with the capture name `foo`):
> 
> ```clojure
> (
>   (comment) @foo
>   .
>   (comment) @foo
> )
> ```
> 
> To capture an arbitrary number of adjacent comments, all with the capture name `foo`:
> 
> ```clojure
> (comment)* @foo
> ```
> 
> To capture a block comment adjacent to a method declaration:
> 
> ```clojure
> (class_body 
>   (block_comment) @comment
>   .
>   (method_declaration) @method
> )
> ```

Works like a magic! Thanks!

**Comment by nerdypepper** [comment]
> To capture two adjacent comments (both with the capture name `foo`):
> 
> ```clojure
> (
>   (comment) @foo
>   .
>   (comment) @foo
> )
> ```

IMO this does not address the fact that two sibling nodes cannot be captured in a single capture. With this query, two captures are created, and the user of the queries must group the captures with the same name as required. 

For this reason (seemingly), tree-sitter-tags seems to use a custom `#select-adjacent!` predicate to group sibling nodes. Would it be possible to add this to the builtin capture mechanism?

**Comment by maxbrunsfeld** [comment]
The `select-adjacent!` thing is just to filter out the siblings to only the ones that appear on adjacent *lines*, with no blank lines in between.

> this does not address the fact that two sibling nodes cannot be captured in a single capture

I'm not sure what you mean by this. A capture is a name (e.g. `foo`) associated with a specific node.

**Comment by nerdypepper** [comment]
>The select-adjacent! thing is just to filter out the siblings to only the ones that appear on adjacent lines, with no blank lines in between.

Ah I see, thanks for the explanation, I was mistaken.

>I'm not sure what you mean by this. A capture is a name (e.g. foo) associated with a specific node.

Right, take the following code for example:

```rust
let src = "fn a() {}";
let query_text = "
(
    (parameters) @capture
    .
    (block) @capture
) 
";

let query = Query::new(tree_sitter_rust::language(), query_text).unwrap();

QueryCursor::new()
    .matches(&query, root_node, src.as_bytes())
    .flat_map(|match_| match_.captures)
    .for_each(|capture| println!("{:?}", capture.node.byte_range()));
```

The output is (because two separate nodes are captured):

```
4..6
7..9
```

Assuming sibling captures are supported, the following query:

```
(
    (parameters)
    .
    (block)
)  @capture
```

Should output:

```
4..9
```

But we get:

```
4..6 
```

In any case, I do believe the output of the second query is misleading because the node it captures is only the first node in the list of siblings: `(parameters)`.

**Comment by mawkler** [comment]
I'm trying to achieve something similar and stumbled across this thread. I'm trying to capture both the `-` and the `[ ]` (or `[x]`) in markdown checkboxes as one single capture. Here's a file example:

```markdown
- [x] foo
- [ ] bar
  - [ ] baz
```

What I want is to conceal them in Neovim, i.e. replace them with a single unicode character, and for that I need _one_ single capture that encaptures them both.

[Here's a link to the discussion page where I explain in more detail](https://github.com/tree-sitter/tree-sitter/discussions/2674).

**Comment by setop** [comment]
Too bad it's been closed without a solution.

There is still no way to put too sibling nodes in the same capture.
