### ISSUE TITLE
Hiding rule that is MISSING falsely changes the result of parsing to success.

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#1515]
version: `tree-sitter 0.20.1 (062421dece3315bd6f228ad6d468cba083d0a2d5)`

I have some grammar, and I have realized that hiding a `MISSING` rule falsely changes the result of parsing to success (actually after a few hours I have discovered that unhinding the rule gives expected failed result). I find it as a severe bug.

I know that I am not allowed to demand or even expect anything, but I was wondering whether all issues (or at least this one) related with `MISSING` are going to be resolved anytime soon? Some known issues related with `MISSING` are almost 2 years old. I am not complaining or blaming anyone. I am just stuck in a dead end. I either need to implement some long, cumbersome workarounds that also slow down the compilation process, or I need to abandon the tree-sitter usage (which I really do not want).

**Comment by alemuller** [comment]
I its a known issue. See #1043 and chained issues.

**Comment by amaanq** [comment]
This was fixed in https://github.com/tree-sitter/tree-sitter/pull/2577
