### ISSUE TITLE
Nonstandard builds using CLI

### ISSUE THREAD

**Issue by wenkokke** [tree-sitter/tree-sitter#1518]
The [tree-sitter-haskell](https://github.com/tree-sitter/tree-sitter-haskell) grammar requires compilation with `-std=c++14`.

Is there currently a way to ensure that, e.g., commands such as `tree-sitter parse` and `tree-sitter build-wasm` pass this flag correctly to whatever tool they're using for compilation?

**Comment by wenkokke** [comment]
See https://github.com/tree-sitter/tree-sitter-haskell/issues/51.

**Comment by amaanq** [comment]
haskell scanner is in C now

**Comment by wenkokke** [comment]
Is there no plan to extend the language support to cover C++ (or other languages)? That's more what this issue was about.

**Comment by ahlinc** [comment]
> Is there no plan to extend the language support to cover C++ (or other languages)? That's more what this issue was about.

There is such plan to add support configuration for compiler parameters in the `package.json`.
