### ISSUE TITLE
S-expression whitespace syntax

### ISSUE THREAD

**Issue by Aerijo** [tree-sitter/tree-sitter#152]
In the docs, it says

> The exact placement of whitespace in the S-expression doesn't matter, but ideally the syntax tree should be legible.

In my tests though, something that results in the tree `(program(text_mode))` would succeed when the following test tree was used
```
(program
  (text_mode))
```

but not when this is used
```
(program
  (text_mode)
)
```

Is this by design, or a bug? I assumed "placement of whitespace ... doesn't matter" applied to line breaks as well, so I was confused when it told me the tests failed.

**Comment by Pike** [comment]
This is about https://github.com/tree-sitter/tree-sitter-cli/blob/3c0e1ba4decdf725aa33ca554fc9e1555c9b6645/lib/cli/test.js#L86, right?

I guess that the newline is normalized to " ", whereas it might be useful to also normalize ") )" to "))" ?

**Comment by maxbrunsfeld** [comment]
> I guess that the newline is normalized to " ", whereas it might be useful to also normalize ") )" to "))" ?

Yeah, that's exactly right. A fix is published in tree-sitter-cli version 0.11.1.
