### ISSUE TITLE
`tree-sitter playground` is broken when building without wasm library

### ISSUE THREAD

**Issue by alebastr** [tree-sitter/tree-sitter#1523]
Preface: I'm working on packaging `tree-sitter-cli` for Fedora Linux. The process comes with certain distribution enforced policies and restrictions, such as being unable to use any build dependency outside of the existing packages. One of those missing deps is `emscripten`, and as a result we have to skip building any `.wasm` binaries.

The problem: playground requires following 4 resource files: `playground.html`, `playground.js`, `tree-sitter.js`, `tree-sitter.wasm`. Since we are unable to build the Web Assembly binary, the build script cannot find some of the files and decides to create empty resources for all the files (`TREE_SITTER_EMBED_WASM_BINDING` is unset).

Latter 3 of the files have fallback to https://tree-sitter.github.io. The first one, `playground.html`, haven't. I.e., for example, if you build the binary with `cargo install tree-sitter-cli`, it always serve an empty page instead of `playground.html`.

I can imagine two possible fixes for the issue: either unconditionally embed `playground.html` into the binary or add a fallback to the html hosted on the github pages. It's up to you to choose, but I'd love to see one of those implemented.

**Comment by maxbrunsfeld** [comment]
Thanks for the report. 👍

**Comment by maxbrunsfeld** [comment]
This is fixed on master.

**Comment by alebastr** [comment]
@maxbrunsfeld, thanks for a quick fix!

I just found that https://github.com/tree-sitter/tree-sitter/commit/9f535f95bdfa12fa1240d5c33d2c20de2da7d357 is causing a different issue: since it looks for `../../cli/src/playground.html`, the code fails to compile as a standalone crate.

**Comment by maxbrunsfeld** [comment]
Oops, thanks. That is now fixed on master too.
