### ISSUE TITLE
Docs website doesn't handle dark mode correctly

### ISSUE THREAD

**Issue by razzeee** [tree-sitter/tree-sitter#1525]
![image](https://user-images.githubusercontent.com/5943908/145269635-017c9b40-cacd-4915-95e4-175858355dba.png)

**Comment by maxbrunsfeld** [comment]
Thanks for the report.

**Comment by dundargoc** [comment]
How do you even enable dark mode in the docs website?

**Comment by razzeee** [comment]
No idea, guess it was removed or just a css bug in the first place

**Comment by sogaiu** [comment]
On a tangential note...darkreader :)
