### ISSUE TITLE
0.20.1 breaks error case

### ISSUE THREAD

**Issue by razzeee** [tree-sitter/tree-sitter#1527]
Going from 0.20.0 to 0.20.1 breaks one of my tests.

It seems to be kind of weird too, as it's creating way too many nodes, at first glance.

https://github.com/elm-tooling/tree-sitter-elm/runs/4477922513?check_suite_focus=true

```
================================================================================
Case without branches followed by newline
================================================================================

-- Works in v4.5.0
update msg =
    case msg of

--------------------------------------------------------------------------------

(file
  (line_comment)
  (ERROR
    (function_declaration_left
      (lower_case_identifier)
      (lower_pattern
        (lower_case_identifier)))
    (eq)
    (case)
    (value_expr
      (value_qid
        (lower_case_identifier)))
    (of)))
```

https://github.com/elm-tooling/tree-sitter-elm/pull/108

**Comment by ahelwer** [comment]
Is error output supposed to be stable?

**Comment by razzeee** [comment]
Can't answer that, but it shouldn't be random I think. I might be out of the loop on reading the test diffs, but I'm not sure where it could even get those nodes from.

**Comment by ahelwer** [comment]
The output really is quite something!

**Comment by maxbrunsfeld** [comment]
Oh it's not parsing your test file correctly because there's a newline inside of one of the test names. I'll fix it up.

**Comment by maxbrunsfeld** [comment]
Thanks for the bug report @razzeee.

**Comment by razzeee** [comment]
Great find, thank you
