### ISSUE TITLE
Octal escape sequence

### ISSUE THREAD

**Issue by alemuller** [tree-sitter/tree-sitter#1529]
Tree-sitter assumes backslash followed by numbers are backreference. In PCRE, backslash followed by a numbers with leading zero are always octal escape sequence (numbers greater than 10 without leading zero are ambiguous).

```js
module.exports = grammar({
   name: 'foobar',
   rules: {
     foo: $ => /\0/,
   }
})
```

```
$ tree-sitter generate
Error processing rule foo_token1

Caused by:
    regex parse error:
        \0
        ^^
    error: backreferences are not supported
```

**Comment by amaanq** [comment]
Since strict mode doesn't allow this and it's not allowed in Rust regex in general, I'm going to close this as a "wont fix". I think we want to align our current regex behavior to **one** flavor, that being Rust.
