### ISSUE TITLE
Bindings for Java/Kotlin

### ISSUE THREAD

**Issue by oxisto** [tree-sitter/tree-sitter#1531]
Big fan of this project! We are currently trying to use tree-sitter instead of eclipse CDT in our Kotlin/Java-based project. For this purpose, I have created bindings for Kotlin (currently only for the JVM, but potentially also for native) in a separate repository
 (https://github.com/oxisto/kotlintree). It is basically using JNA to access the native functions and using the JNAs extensibility to create classes that have a more "Kotlin"-feel to it rather than just using the pure C api. 

Is there any interest in providing those bindings as an "official" part of the project? If yes, I would try to prepare a PR for it, otherwise, it will probably life as an independent project. Let me know what you think.

**Comment by maxbrunsfeld** [comment]
Nice work! I think it makes sense to keep it as an independent project, but to add a link to it from the Tree-sitter docs. I would definitely merge a PR adding a link to your project on [this page](https://github.com/tree-sitter/tree-sitter/blob/master/docs/index.md), if you're interested in opening one.

Also, I recently found out about this  project: https://github.com/serenadeai/java-tree-sitter (which I should probably link to also) There may be some similarities between that and your project.
