### ISSUE TITLE
Print full C compiler invocation when compilation fails

### ISSUE THREAD

**Issue by cpitclaudel** [tree-sitter/tree-sitter#1533]
Hi there,

I'm going through the tree-sitter "Creating a parser" tutorial.

I'm trying to run `tree-sitter parse`, but it complains about not finding the C compiler.  I have `gcc`, `g++`, `clang`, and `clang++` in my path, and `cc` points to `gcc`.

Running `node_modules/.bin/tree-sitter parse hello` prints the following message:

```
Failed to load language in current directory

Caused by:
    0: Failed to execute C compiler
    1: The system cannot find the file specified. (os error 2)
```

Is there a way to print the full command line that was used to invoke the C compiler?

**Comment by milahu** [comment]
the compiler arguments are rather predictable

https://github.com/tree-sitter/tree-sitter/blob/c51896d32dcc11a38e41f36e3deb1a6a9c4f4b14/cli/loader/src/lib.rs#L375-L422

so its always something like

> ```gcc -shared -fPIC -fno-exceptions -g -I src/tree_sitter -o parser.so -O2 -DTREE_SITTER_INTERNAL_BUILD src/scanner.cc -xc src/parser.c```

but instead of `parser.so` tree-sitter will produce
`$HOME/.cache/tree-sitter/lib/${language_name}.so`

## strace

what i dont understand is that with `strace`, i dont see the `execve` call to `gcc`

```
rm src/parser.c; strace -f -v -s 999 -e verbose=all tree-sitter generate &> build.log
```

maybe its using the numeric syscall for execve?
but then i still should see arguments like `-DTREE_SITTER_INTERNAL_BUILD`

maybe there is another code path? at least i can see that `libgcc_s.so` is loaded

**Comment by sogaiu** [comment]
I don't know about another path, but I think [this](https://github.com/tree-sitter/tree-sitter/discussions/2106#discussioncomment-5117923) might be helpful for the original post.

**Comment by amaanq** [comment]
> the compiler arguments are rather predictable
> 
> https://github.com/tree-sitter/tree-sitter/blob/c51896d32dcc11a38e41f36e3deb1a6a9c4f4b14/cli/loader/src/lib.rs#L375-L422
> 
> so its always something like
> 
> > `gcc -shared -fPIC -fno-exceptions -g -I src/tree_sitter -o parser.so -O2 -DTREE_SITTER_INTERNAL_BUILD src/scanner.cc -xc src/parser.c`
> 
> but instead of `parser.so` tree-sitter will produce `$HOME/.cache/tree-sitter/lib/${language_name}.so`
> 
> ## strace
> what i dont understand is that with `strace`, i dont see the `execve` call to `gcc`
> 
> ```
> rm src/parser.c; strace -f -v -s 999 -e verbose=all tree-sitter generate &> build.log
> ```
> 
> maybe its using the numeric syscall for execve? but then i still should see arguments like `-DTREE_SITTER_INTERNAL_BUILD`
> 
> maybe there is another code path? at least i can see that `libgcc_s.so` is loaded

It won't build the compiler until you actually need to use it ;) i.e., parse a source code file with the `parse` subcommand, at which case it'll compare the mtimes of your parser/scanner and the currently built parser if any stored in your cache, and if its newer *then* it'll recompile, I can confirm `strace` shows that now, no manual loading of the syscall number done here :grin:. Anyways there's now feedback as to what your compilation arguments were if it does fail
