### ISSUE TITLE
Allow swapping malloc implementation at runtime

### ISSUE THREAD

**Issue by casouri** [tree-sitter/tree-sitter#1535]
Not being able to swap malloc implementation at runtime is blocking us from merging tree-sitter support into Emacs. It is quite reasonable to expect the system to provide tree-sitter library and matching language libraries. On the other hand, embedding tree-sitter into Emacs is both a maintenance burden and a potential risk: Emacs' tree-sitter might not match the language libraries provided by the system. So we really want to link tree-sitter dynamically, and we need to be able to change malloc at runtime to do that. Could you consider adding this feature to tree-sitter? TIA.

**Comment by maxbrunsfeld** [comment]
I think this functionality can be built on *top* of Tree-sitter's statically-configurable malloc implementation. You could define your own dynamically-configurable malloc function that uses a mutable function pointer, and tell Tree-sitter to use that function by defining the [`ts_malloc`/`ts_free`](https://github.com/tree-sitter/tree-sitter/blob/836d753c73d41659a5c7f7958807dde4fabb2322/lib/src/alloc.h#L29-L40) macros.

**Comment by casouri** [comment]
We want to use the tree-sitter library provided by the system in the form of a dynamic library, instead of pulling it into our code base and modify the `ts_malloc` and `ts_free` macros, because that spares us from maintaining tree-sitter in-tree. And it's no different from other libraries we use, eg, librsvg, libpng, etc. They all provide means to change malloc at runtime. I think it only makes sense for tree-sitter to also provide that feature if it wants to be used as a dynamic library.

Of course, if there is a way to change malloc implementation without modifying tree-sitter's source in its current form, I'm very interested to know.

**Comment by alemuller** [comment]
Had this issue as well, but thought was too niche to open an issue. The standard way to change the allocator at runtime is with the  `LD_PRELOAD` envvar (see [mimalloc](https://github.com/microsoft/mimalloc) or any allocator doc).

**Comment by Eli-Zaretskii** [comment]
The `LD_PRELOAD` trick only works on Posix platforms.  On MS-Windows, something like this cannot work at all, because when a library, such as tree-sitter, is compiled and linked into a DLL, it records the `malloc` functions the linker finds at that time, so it will use the Microsoft original runtime even if the program that calls tree-sitter overrides the `malloc` implementation by different functions.

So we really *must* have a capability of asking tree-sitter to use our `malloc`, `free`, and friends, and we really would like to avoid telling our users to modify the sources of tree-sitter and building their own version of the tree-sitter library, when they build Emacs.

AFAIU, it should be a simple matter to provide an API call for setting custom allocation functions, which tree-sitter will call instead if `malloc` etc., and we hope something like that could be part of tree-sitter soon.

Alternatively, perhaps tree-sitter could provide a callback it will call when `malloc` returns `NULL`, to allow the calling program to handle that gracefully instead of just exiting.  Emacs could use such a callback, as it already has machinery in place to DTRT in such cases.

**Comment by netjune** [comment]
Could someone open a PR for this?

**Comment by mkvoya** [comment]
@casouri I added a draft implementation in the PR #1544. Can Emacs change the global variable before any allocation happens in tree-sitter?

**Comment by Eli-Zaretskii** [comment]
> Can Emacs change the global variable before any allocation happens in tree-sitter?

I don't think I understand the question, and it isn't a tree-sitter issue anyway, so perhaps should be discussed on the Emacs mailing list.

**Comment by mkvoya** [comment]
> I don't think I understand the question, and it isn't a tree-sitter issue anyway, so perhaps should be discussed on the Emacs mailing list.

My apology. It's not a tree-sitter issue. I am writing to ask @casouri whether my MR could solve the problems he met in Emacs.

**Comment by cireu** [comment]
An alternate idea: Make allocator API a weak symbol, and override it in link time.

**Comment by Eli-Zaretskii** [comment]
> Make allocator API a weak symbol

Isn't that specific to systems that use ELF binary format?

**Comment by casouri** [comment]
> @casouri I added a draft implementation in the PR #1544. Can Emacs change the global variable before any allocation happens in tree-sitter?

Thanks, trying it right now.

**Comment by maxbrunsfeld** [comment]
Ok, I'm open to adding an API for swapping out the allocator dynamically. How about an API like this, which applications would call at initialization time?

```c
void tree_sitter_set_allocator(
  void *(*malloc)(size_t),
  void *(*calloc)(size_t, size_t);
  void *(*realloc)(void *, size_t);
  void (*free)(void *);
);

**Comment by mkvoya** [comment]
> Ok, I'm open to adding an API for swapping out the allocator dynamically. How about an API like this, which applications would call at initialization time?
> 
> ```c
> void tree_sitter_set_allocator(
>   void *(*malloc)(size_t),
>   void *(*calloc)(size_t, size_t);
>   void *(*realloc)(void *, size_t);
>   void (*free)(void *);
> );
> ```

I have added the following in `./lib/include/tree_sitter/api.h` (in #1544). The global variable `ts_allocator` is set to the default allocator, thus existing applications don't need to change anything.


```c
typedef struct {
   void *(*malloc)(size_t);
   void *(*calloc)(size_t, size_t);
   void *(*realloc)(void *, size_t);
   void (*free)(void *);
 } TSAllocator;

// ...

 /**
  * The allocator.
  */
 extern TSAllocator *ts_allocator;

 /**
  * Switch to a new allocator.
  *
  * Returns the old allocator. The caller needs to take care of any allocated
  * memory managed by the old allocator.
  */
 TSAllocator *ts_set_allocator(TSAllocator *new_alloc);

**Comment by casouri** [comment]
Maybe internalize the struct and only expose the function?

**Comment by mkvoya** [comment]
> Maybe internalize the struct and only expose the function?

Make sense. Updated in the PR.

**Comment by Eli-Zaretskii** [comment]
Thanks, this would be perfect, and will allow Emacs to use its own allocators, which already know how to deal with the out-of-memory condition.

**Comment by maxbrunsfeld** [comment]
This feature is now on the master branch. I'll be curious to hear how it goes, using Tree-sitter in Emacs.

**Comment by casouri** [comment]
I've written wrapper functions and manual nodes for tree-sitter, and some basic integration framework for font-locking and indentation. Here is a blog post describing the progress: [blog post](https://archive.casouri.cat/note/2021/emacs-tree-sitter/index.html), here is the manual preview: [manual](https://archive.casouri.cat/note/2021/emacs-tree-sitter/Parsing-Program-Source.html).

BTW, when I try to set allocators, the test program throws
```
dyld[83892]: missing symbol called
fish: Job 1, './main-c' terminated by signal SIGABRT (Abort)
```
(I'm on a Mac)

Here is the source of my test program: [source](https://gist.github.com/casouri/14ef96fb201eff28993b1e44f73de926). It simply reads a C file and parses it. If I comment out line 27 `ts_set_allocator(malloc, calloc, realloc, free);`, the program runs fine.

**Comment by mkvoya** [comment]
I try to reproduce the issue but everything works fine here.

```
bash-3.2$ gcc a.c tree-sitter-c/src/parser.c /usr/local/Cellar/tree-sitter/HEAD-5d8a1ac/lib/libtree-sitter.a
bash-3.2$ ./a.out
bash-3.2$ echo $?
0
```

`a.c` is the source code you provided. I am using the head version tree-sitter built by homebrew.I am also on a Mac.

**Comment by maxbrunsfeld** [comment]
@casouri were you using an old version of the tree-sitter library that didn’t yet have the new allocator API?

**Comment by casouri** [comment]
I figured out why. The program was linked to the library in `/usr/local/lib`—an old tree-sitter library was installed to that location unnoticed.
