### ISSUE TITLE
Documenting comments in c++

### ISSUE THREAD

**Issue by ruzito** [tree-sitter/tree-sitter#1551]
Hi,
when using tree-sitter syntax highlighter on c++ code I don't see any highlighting on doxygen keywords.

Not sure if any other languages have this issue.

Potentially helpful would be to have the ability to nest language grammars into each other like html, css and javascript. I'm not sure how that works exactly but this thing would easily be able to extend to documenting comments in other languages.

So I would like to see a doxygen grammar (ideally genericaly) nested into all supported languages.

But do what you will with this wish.

:-)

**Comment by theHamsta** [comment]
Language injection is an editor feature or an feature implemented by the application that's using tree-sitter. Tree-sitter supports to set (sub-)ranges in a document that should be parsed by a parser for a specific language. Atom and Neovim support language injection that are described by a `injections.scm` but they could also be triggered in a different way. Emacs-tree-sitter not yet.

**Comment by ruzito** [comment]
Ok

**Comment by theHamsta** [comment]
This would be what you suggested for JSDoc https://github.com/tree-sitter/tree-sitter-jsdoc/blob/master/README.md
