### ISSUE TITLE
Repetition quantifiers with empty maximum not greedy

### ISSUE THREAD

**Issue by alemuller** [tree-sitter/tree-sitter#1552]
I expected the `/l{n,}/` to either match `n` or more repetition of the literal, or to emit an error during generation.

Grammar:
```js
module.exports = grammar({
  name: 'foobar',

  extras: $ => [],

  rules: {
    top: $ => repeat(seq($.tok,'\n')),

    tok: $ => /x{1,}/,
  }
})
```

Input (with trailing \n):
```
x
xx
```

Actual output:
```
(top [0, 0] - [2, 0]
  (tok [0, 0] - [0, 1])
  (tok [1, 0] - [1, 1])
  (ERROR [1, 1] - [1, 2]))
```

Expected output:
```
(top [0, 0] - [2, 0]
  (tok [0, 0] - [0, 1])
  (tok [1, 0] - [1, 2]))
```

**Comment by ahelwer** [comment]
To be clear, this behavior does not occur when the regex is `/x+/`?

**Comment by alemuller** [comment]
> To be clear, this behavior does not occur when the regex is /x+/?

The issue does not happen when repetitions is done with meta characters.

**Comment by amaanq** [comment]
Fixed in https://github.com/tree-sitter/tree-sitter/pull/3831, this was subtle "UB" before.
