### ISSUE TITLE
How is it possible to parse non-CFLs with tree-sitter?

### ISSUE THREAD

**Issue by glyh** [tree-sitter/tree-sitter#1557]
I'm trying to write some tree-sitter grammar for some other languages. In the grammar, it uses the following operations:
- lookaheads/lookbehinds (Just like in regex)
- ordered choices (Just like in PEG)
- except operator(`A \ B` matches iff `A` matches and `B` fails)

While none of them seems to be context-free. I notice that some existing parsers are parsing non-CFLs, for example, Python, C++. How is that possible? (I think the answer to this question can solve my problem above)

If they are using approximations, how do we know whether an approximation is good enough?

This is more of a question, rather than issues or proposals. I'm sorry if I should not post it here and I'll try elsewhere. But this seems to be the best place.

**Comment by ahelwer** [comment]
You can write an external scanner in C or C++, see https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners
You can see the file src/scanner.c or src/scanner.cc in the repos for those grammars you mentioned.

**Comment by glyh** [comment]
Thank you for responding. But I think scanner alone can't resolve the problem. For example, as this stackoverflow problem points out([is c context-free or context-sensitive](https://stackoverflow.com/questions/14589346/is-c-context-free-or-context-sensitive)), we can't parse the following structure, without the knowledge on  A and B: 
```
A * B;
``` 
this can mean A multiplied by B, while it also may mean a pointer of type A, named B.

**Comment by ahelwer** [comment]
Oh, I see. I don't believe tree-sitter can solve this problem as it parses single files at a time and to disambiguate `A * B` you need to keep around a list of all types defined in all dependencies. The general design philosophy is that tree-sitter grammars should give an approximately-correct parse, in line with their use-case for highlighting and light syntax-aware language tooling. Usually you will see grammars being more permissive than the language spec, accepting invalid syntax for ease of parsing and the like.

**Comment by glyh** [comment]
Thanks, I got it. I'm closing this.
