### ISSUE TITLE
Flag for tree-sitter parse and test which use the generated wasm

### ISSUE THREAD

**Issue by wenkokke** [tree-sitter/tree-sitter#1565]
Currently, testing the generated was requires you to write the JavaScript yourself, which makes it a little bit tricky to do, and as such I don’t suspect that many parsers do so.

Unfortunately, the generated wasm can run into a number of errors that are not encountered with the native versions:

- https://github.com/tree-sitter/tree-sitter-haskell/issues/53
- https://github.com/tree-sitter/tree-sitter/issues/1560
- https://github.com/tree-sitter/tree-sitter-python/issues/133
- https://github.com/tree-sitter/tree-sitter/issues/1389
- etc.

it should be easy enough to ship tree-sitter with the required JavaScript to load a language from the generated wasm, and parse any number of files, e.g., a version of [tree-sitter-parse.js](https://github.com/tree-sitter/tree-sitter-haskell/blob/master/script/tree-sitter-parse.js) abstracted over the wasm file name, and link this to `tree-sitter parse —wasm <paths…>`.

**Comment by maxbrunsfeld** [comment]
This is a good idea. I guess when using the `--wasm` flag, we would just require that `node` be available on the `PATH`, similar to how `tree-sitter generate` works.

**Comment by amaanq** [comment]
The parse and test commands have a `--wasm` flag now, but require the cli to be built with the `wasm` feature enabled.
