### ISSUE TITLE
Unable to load parser for c help

### ISSUE THREAD

**Issue by morphykuffour** [tree-sitter/tree-sitter#1569]
Hello I wanted to experiment with lua's bindings for treesitter but the demo in the readme does not work. I don't know where to find or generate the **C shared object file**. Any help would be appreciated. Please see attached screenshoot.

![image](https://user-images.githubusercontent.com/23323356/147878914-7fffd439-891d-4f3a-abfa-4354f2540bc0.png)

**Comment by theHamsta** [comment]
You can clone tree-sitter/tree-sitter-c and run a command like `cc -Isrc src/parser.c -o c.so -shared` to compile the shared object file for a language parser (did not check, I'm on my cellphone). Or download a precompiled .so from our pipeline for your platform https://github.com/nvim-treesitter/nvim-treesitter/actions/runs/1635602265


You should probably post the issue at the repository for the Lua bindings as it's an independent project.

**Comment by morphykuffour** [comment]
Thanks I’ll try that when I get home.
