### ISSUE TITLE
Treesitter not working in some places in html

### ISSUE THREAD

**Issue by melsiir** [tree-sitter/tree-sitter#1582]
![Screenshot_٢٠٢٢٠١١١-١٤٤١٤٠_Termux](https://user-images.githubusercontent.com/73516767/149007193-c7aa1350-bdf4-4ec2-b07b-aa033e3ee4ea.jpg)
![Screenshot_٢٠٢٢٠١١١-١٢٠٤٤٨_Termux](https://user-images.githubusercontent.com/73516767/149007227-2ad13e2f-63f9-4b40-8124-09bcf833c8da.jpg)

When I am editing html file the treesitter randomly not highlighting 

https://user-images.githubusercontent.com/73516767/149007460-daf4995f-6909-4297-b751-69bbaff41813.mp4

Here is my config :

use {
      "nvim-treesitter/nvim-treesitter",
      event = "BufRead",
      config = override_req("nvim_treesitter", "plugins.configs.treesitter"),
   }

And the treesitter setup :

local present, ts_config = pcall(require, "nvim-treesitter.configs")

if not present then
   return
end

ts_config.setup {
   ensure_installed = {
      "lua",
      "vim",
      "css",
      "typescript", "javascript",
      "tsx", "graphql", "html",
      "scss", "python", "dockerfile",
      "dot", "json", "bash", "fish",
      "hjson", "vue", "svelt",
   },
   highlight = {
      enable = true,
      use_languagetree = true,
   },
   autotag = {
    enable = true,
  }
}

**Comment by ahelwer** [comment]
You probably want to open this issue on the nvim-treesitter repo.

**Comment by maxbrunsfeld** [comment]
It sounds like you're using Neovim. Can you report this on the Neovim or nvim-treesitter repositories? Tree-sitter is just a library that Neovim is using.
