### ISSUE TITLE
Released web bindings are incompatible with newest emscripten

### ISSUE THREAD

**Issue by jessesna** [tree-sitter/tree-sitter#1593]
Maybe this is more of a info than a bugreport because it's already common knowledge but i couldn't find any info about the constraints of the released file and hope it might help someone?

I'm on Windows and couldn't get a language compiled with emscripten to work together with the `tree-sitter.js` and `tree-sitter.wasm` files from [the latest GitHub release](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.20.2) as described [here](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web) with some basic test code:

```
const Parser = require('web-tree-sitter');
Parser.init().then(() => {
    (async function(a, b) {
        const language = await Parser.Language.load('tree-sitter-g_code_sinumerik.wasm');
        const parser = new Parser;
```

I always got the error
```
Assertion failed: undefined
node_modules/web-tree-sitter/tree-sitter.js:1
Uncaught RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.
```

Turns out this is because the emcc i'm using

`emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.0 (8e1e305519e1027726a48861a1fec5662f7e18a2)`

is too new or because i'm on windows?

When i compare a `wasm` i get through `npm install`, f.e. `tree-sitter-javascript.wasm` with my own, there's a difference in the `dylink` secion.
The former is at
```
wasm-objdump -h tree-sitter-javascript.wasm
tree-sitter-javascript.wasm:    file format wasm 0x1
Sections:
   Custom start=0x0000000a end=0x00000018 (size=0x0000000e) "dylink"
```
and mine at
`   Custom start=0x0000000e end=0x0000001e (size=0x00000010) "dylink.0"`

After rebuilding `tree-sitter.js` and `tree-sitter.wasm` the error disappeared because the checks done in [loadModule](https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/binding.js#L905) (they look like [these here at line 370 ff](https://git.sprintf.io/emscripten-ports/emscripten/commit/65271b0ed8e77d07ced7f6873c3582b6b0ae2719?style=split&whitespace=)) now match the expectations.

**Comment by cherryleafroad** [comment]
I also encountered this. As you said, rebuilding it against the latest emscripten fixed the problems

**Comment by swarnimarun** [comment]
Yep, went through the same yesterday(cost me most of the day), anyways, I think this information should be added to the docs, I could add it to the docs in a PR too if no one else wants to, and if the maintainers think that's deserved as well.

**Comment by kevinbarabash** [comment]
I worked around the issue by using version 2.0.24 of emscripten.  I found this version number in https://github.com/tree-sitter/tree-sitter/blob/master/cli/emscripten-version.

**Comment by maxbrunsfeld** [comment]
I'll update the web bindings to use the latest emscripten

**Comment by maxbrunsfeld** [comment]
Newer versions of Emscripten have a regression that causes many unnecessary imports and exports to be generated when building dynamic libraries: https://github.com/emscripten-core/emscripten/issues/15487 that use C++ (like `tree-sitter-html` does in its external scanner).

This is somewhat unfortunate, and I'm wondering if it'd be better to wait until this is fixed.

**Comment by koliyo** [comment]
I just ran into this exact problem! It took a while to trace why my wasm modules worked on one machine but crashed when building on another.

It turned out I had emscripten installed on one machine, via homebrew. And after finding this issue, and then uninstalling emscripten, I now get working wasm modules again!

I will add the `--docker` flag to `build-wasm` as part of my wasm build scripts to prevent this from happening.
