### ISSUE TITLE
there is no function to get a tsnode's name

### ISSUE THREAD

**Issue by shi-yan** [tree-sitter/tree-sitter#1594]
tree-sitter has a function to get current node type:
const char *ts_node_type(TSNode);
but it doesn't have an equivalent for getting a node's name?

const char *ts_node_name(TSNode);

I found this inconvenient.

the tree cursor has const char *ts_tree_cursor_current_field_name(const TSTreeCursor *);
but tsnode doesn't have anything similar.

**Comment by PhilippeNoel1** [comment]
Totally agree with this proposition!

**Comment by ahelwer** [comment]
I think this is because names are a property of the parent's relation to the child node rather than the child node itself.

**Comment by ahlinc** [comment]
The `ts_node_type` actually returns a name of a node, in bindings it's called `kind` of a node.

**Comment by ahlinc** [comment]
I close the issue as there is nothing to improve.

**Comment by PhilippeNoel1** [comment]
Not totally sure about what @shi-yan said, but I understand like this.

If you take this code in python:
``` python
def foo(first: int = 5):
	print(first)
```
The corresponding AST is the following:
```
module [0, 0] - [2, 0]
  function_definition [0, 0] - [1, 13]
    name: identifier [0, 4] - [0, 7]
    parameters: parameters [0, 7] - [0, 23]
      typed_default_parameter [0, 8] - [0, 22]
        name: identifier [0, 8] - [0, 13]
        type: type [0, 15] - [0, 18]
          identifier [0, 15] - [0, 18]
        value: integer [0, 21] - [0, 22]
    body: block [1, 1] - [1, 13]
      expression_statement [1, 1] - [1, 13]
        call [1, 1] - [1, 13]
          function: identifier [1, 1] - [1, 6]
          arguments: argument_list [1, 6] - [1, 13]
            identifier [1, 7] - [1, 12]
```
If you take the third node of `typed_default_parameter`, you get ` value: integer [0, 21] - [0, 22]`. The kind of this node is effectively `integer`, but I search for the name `value`. 
I a not sure about the terms, but I guess it's the real name of the node, and `integer` is it's "kind"

This can be useful, because "name" (e.g. "identifier", "value", ...) are the same every time, but "kind" depends of the parsed code.

**Comment by ahlinc** [comment]
> but I search for the name value.
> I a not sure about the terms, but I guess it's the real name of the node, and integer is it's "kind"

No, the `value:` is the field name, the `integer` is a node _name_ (aka the `type` in C API and the `kind` in bindings).
Fields may occur on any node and they seen as a prefix followed by a colon.
Things like `parameters: parameters` looks like tautology but  the `parameters: ` field name was assigned to have an index style access to the `parameters` node.

> This can be useful, because "name" (e.g. "identifier", "value", ...) are the same every time, but "kind" depends of the parsed code.
They are not the same, don't mix field names (`value:`) with node types (`integer`). Node types and field names depends on how a concrete language grammar was defined.
