### ISSUE TITLE
allow `#is-not? local` to gate multiple captures in a stanza?

### ISSUE THREAD

**Issue by the-mikedavis** [tree-sitter/tree-sitter#1597]
Currently the property predicate `(#is-not? local)` may only apply to a node that is a local reference, as in the ruby queries:

```tsq
((identifier) @function.method
 (#is-not? local))
(identifier) @variable
```

If you try to use `(#is-not? local)` on multiple captures, for example:

```tsq
((field_access
   record: (identifier) @module
   field: (label) @function)
 (#is-not? local))
```

then the first capture (`@module`) is correctly gated on whether or not `(identifier)` is local, but the second capture (`@function`) always matches, even when the `(identifier)` is local.

I think it is possible to fix this case while keeping the current "locals info can be parsed and used in a single pass" behavior like so (in [this](https://github.com/tree-sitter/tree-sitter/blob/e96ee19901947d8550abbcf425791c2a411c8d97/highlight/src/lib.rs#L834-L850) block):

```diff
diff --git a/highlight/src/lib.rs b/highlight/src/lib.rs
index 58d7e88c..0d097201 100644
--- a/highlight/src/lib.rs
+++ b/highlight/src/lib.rs
@@ -835,6 +835,7 @@ where
             // highlighting patterns that are disabled for local variables.
             if definition_highlight.is_some() || reference_highlight.is_some() {
                 while layer.config.non_local_variable_patterns[match_.pattern_index] {
+                    match_.remove();
                     if let Some((next_match, next_capture_index)) = layer.captures.peek() {
                         let next_capture = next_match.captures[*next_capture_index];
                         if next_capture.node == capture.node {
```

When the capture that is not local is skipped over, we `.remove()` the match (which calls `ts_query_cursor_remove_match` from `lib/src/query.c`). This is used [higher in the same function](https://github.com/tree-sitter/tree-sitter/blob/e96ee19901947d8550abbcf425791c2a411c8d97/highlight/src/lib.rs#L691-L693) for injections. I tried this locally but despite the `.remove()`, I still see the `@function` capture being emitted by the `layer.captures` peekable :thinking:

Am I on the right track to fixing this? Is this something that even should be fixed, or should locals info only be used to highlight/not-highlight the node interpreted as a local definition/reference?

**Comment by maxbrunsfeld** [comment]
I think you're right that this should be fixed; I'm not sure why your patch doesn't work, but if you figure it out, I'd merge a PR that changes the behavior in that way.
