### ISSUE TITLE
The version of tree-sitter in pkg-config file doesn't match real version number.

### ISSUE THREAD

**Issue by cireu** [tree-sitter/tree-sitter#1608]
The version of .pc file use `VERSION` variable in Makefile, maybe tree-sitter maintainer forget to update it?

https://github.com/tree-sitter/tree-sitter/blob/master/Makefile#L1

**Comment by robmoss** [comment]
I've experienced this issue when trying to build Emacs 29 with the built-in tree-sitter module.

**Comment by seanfarley** [comment]
> I've experienced this issue when trying to build Emacs 29 with the built-in tree-sitter module (which requires tree-sitter >= 0.20.2).

Ha, I came here to report the same issue and found it the exact same way
