### ISSUE TITLE
Query causing Tree-sitter to freeze

### ISSUE THREAD

**Issue by RRethy** [tree-sitter/tree-sitter#1611]
When using https://github.com/tree-sitter/tree-sitter-ruby, this query causes tree-sitter to freeze:

```
(ERROR (
"if" @indent
. (_) @cursor
. (then)? @cursor
. (["elsif" (elsif)]? @cursor)*
. ["else" (else)]? @cursor
))
```

You can try it out in https://tree-sitter.github.io/tree-sitter/playground, it will freeze the webpage (not a webpage issue, it also happens in Neovim).

Edit: It appears to be a side-effect of using `?` inside the `*`, that's actually reasonable for the state machine to loop on that. Will close.

**Comment by theHamsta** [comment]
Even though the query is mal-formed, tree-sitter shouldn't loop for ever but have some timeout for that or detect that during query loading.
