### ISSUE TITLE
tree-sitter version bump to v0.20.4

### ISSUE THREAD

**Issue by carlosala** [tree-sitter/tree-sitter#1614]
Hi!
Could tree-sitter be also updated to v0.20.4? Now only tree-sitter-cli has been updated, and this is going to block package repos (such as the arch one) from updating it.
Thanks!

**Comment by maxbrunsfeld** [comment]
There have been no changes to the Tree-sitter library since 0.20.3. Could you clarify what needs to be updated, and why the update is blocked?

**Comment by carlosala** [comment]
The arch package is updated when there is a release of `tree-sitter`, and it also updates `tree-sitter-cli`. Most package repos work like that, and this release is quite important as some parsers doesn't get installed with neovim and `tree-sitter-cli` v0.20.4

**Comment by maxbrunsfeld** [comment]
Ok, the library and the CLI are versioned separately, and in general they won't always be released at the same version or at the same time. Can you raise this issue with the maintainer of the Arch package?

**Comment by carlosala** [comment]
yes, sure. I thought both library and CLI were using the same versioning
