### ISSUE TITLE
Feature request: provide grammar.js for the built-in query language

### ISSUE THREAD

**Issue by geert56** [tree-sitter/tree-sitter#1629]
As far as I know (by browsing the source) the query language is only verbally described in the documentation and implemented in the query.c source. Since it is a language (like Lisp S-Expressions) and tree-sitter is a prog. language tool that provides parsers for many languages, it would be natural to assume that the query language itself is defined by a tree-sitter grammar. For one that is a helpful part of the documentation.
Moreover, it would open the way to have a different implementation approach: use the generate scanner/parser and define the query semantics (now in query.c) on top of it.

[ I made a stab at defining the query grammar in Txl, but have not finished that endavour. It for sure is not easy to extract the grammar from the query.c source code.]

**Comment by theHamsta** [comment]
We have an unofficial tree-sitter for the query language that we use for some tooling: https://github.com/nvim-treesitter/tree-sitter-query it is not guaranteed to show 100% the same behavior than the C-parser but it worked correctly (and is tested) for all queries in https://github.com/nvim-treesitter/nvim-treesitter I know that this is only slightly related to what you want to achieve. Hope that is still useful.

**Comment by geert56** [comment]
Thanks a lot for pointing that out. I already stole the newer Lua parser that was mentioned on the nvim site. I should have searched some more for "tree-sitter-query". For me, we can close this issue now.

**Comment by geert56** [comment]
Dear Stephan,
Just a few remarks about query grammar.js.
In rule for list:
    list: $ => seq("[", repeat(choice($._definition)), "]", quantifier($), captures($)),
why is there a cjoice with only 1 argument?
Also, in:
function captures($) {
  return optional(repeat($.capture));
}

Why have optional here whereas repeat already allows for the empty string?
Kind Regards,
Geert

    On Sunday, January 30, 2022, 1:00:51 PM EST, Stephan Seitz ***@***.***> wrote:  
 
 


We have an unofficial tree-sitter for the query language that we use for some tooling: https://github.com/nvim-treesitter/tree-sitter-query it is not guaranteed to show 100% the same behavior than the C-parser but it worked correctly (and is tested) for all queries in https://github.com/nvim-treesitter/nvim-treesitter I know that this is only slightly related to what you want to achieve. Hope that is still useful.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by geert56** [comment]
Another one Stephan,
The anchor (.) can only occur at the beginning of the children list, at the end, or somewhere inbetween.I don't see how the latter is possible given the syntax:
    named_node: $ => seq(
      "(",
      field("name", $._node_identifier),
      optional(
        seq(
          optional("."),
          choice(
            repeat1($._named_node_expression),
            seq(
              repeat($._named_node_expression),
              seq($._named_node_expression, "."),
            )
          ),
        ),
      ),

    On Sunday, January 30, 2022, 1:00:51 PM EST, Stephan Seitz ***@***.***> wrote:  
 
 


We have an unofficial tree-sitter for the query language that we use for some tooling: https://github.com/nvim-treesitter/tree-sitter-query it is not guaranteed to show 100% the same behavior than the C-parser but it worked correctly (and is tested) for all queries in https://github.com/nvim-treesitter/nvim-treesitter I know that this is only slightly related to what you want to achieve. Hope that is still useful.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by geert56** [comment]
Oops sorry, I take the last back.I see now that immediate_child takes care of the "inbetween" anchor.

    On Sunday, January 30, 2022, 1:00:51 PM EST, Stephan Seitz ***@***.***> wrote:  
 
 


We have an unofficial tree-sitter for the query language that we use for some tooling: https://github.com/nvim-treesitter/tree-sitter-query it is not guaranteed to show 100% the same behavior than the C-parser but it worked correctly (and is tested) for all queries in https://github.com/nvim-treesitter/nvim-treesitter I know that this is only slightly related to what you want to achieve. Hope that is still useful.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by stsewd** [comment]
> why is there a choice with only 1 argument?
> Why have optional here whereas repeat already allows for the empty string?

No reason, we should remove those :)
