### ISSUE TITLE
Unable to load wasm file from JS

### ISSUE THREAD

**Issue by esgott** [tree-sitter/tree-sitter#1652]
I've tried to minimalize the example where this happens. I have a very basic grammar, and when I try to load the wasm file from JS, it fails with `RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.`

The minimal example can be found [here](https://github.com/esgott/tree-sitter-wasm-load)

Steps to reproduce:
```bash
 $ cd tree-sitter-grammar
 $ tree-sitter generate
 $ tree-sitter build-wasm
 $ cd ..
 $ npm install
 $ npm start
```

**Comment by Darkclainer** [comment]
Wasn't able to reproduce problem with your instruction (node v16.7.0).

Also, have you seen recommendation? https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/README.md#running-wasm-in-nodejs

**Comment by esgott** [comment]
Yes, I used node here because it was easy to demonstrate like this. I get the same error e.g. when I load it in a browser like this:
```html
<head>
  <script src="tree-sitter.js"></script>
  <script>
    async function f() {
      const Parser = window.TreeSitter;
      await Parser.init();
      await Parser.Language.load('tree-sitter-grammar/tree-sitter-grammar.wasm');
    }

    f();
  </script>
</head>
<body></body>
```
I committed my wasm file to that repo, can you give that a try? Just to know if the problem is with my wasm, or with the environment. https://github.com/esgott/tree-sitter-wasm-load/blob/with-wasm/tree-sitter-grammar/tree-sitter-grammar.wasm

**Comment by Darkclainer** [comment]
I tried it and got the error you mentioned, then rebuilt wasm myself and the error have disapearred. I'm using tree-sitter v0.20.4

**Comment by esgott** [comment]
I'm also using tree-sitter v0.20.4. Tried it on OSX and on Arch linux, with the same results.
Could it be clang or emscripten?
OSX:
```bash
 $ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.3-git
 $ clang --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.3.0
```
Arch:
```bash
$ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.2-git (a77b559a8b40b7e89fc8c17e41034128df9543e4)
 $ clang --version
clang version 13.0.1
Target: x86_64-pc-linux-gnu
```

**Comment by ahelwer** [comment]
Use emcc 2.0.17 or earlier: https://github.com/tree-sitter/tree-sitter/issues/1098#issuecomment-842326203

If you have an external scanner that imports things not imported by the emcc build that can also cause errors.

**Comment by esgott** [comment]
@ahelwer That solves it. It might worth to put a check into `build-wasm` for emscripten version. 
Thanks for the help!
