### ISSUE TITLE
Win CMD: Issues with Escape Sequences and Special Chars

### ISSUE THREAD

**Issue by tajmone** [tree-sitter/tree-sitter#1658]
I hope this is not a duplicate (I searched through the Issues and didn't seem to find anything on this).

When running Tree-sitter CLI (Rust binary) under Windows 10 CDM, using the `tree-sitter test` command, escape characters are not represented correctly:

```
D:\tree-sitter-mylang>tree-sitter test
  basic:
    ✓ ←[32mLine Comments←[0m
```

where the `✓` character is not shown due to missing glyph in default font, and the escape sequences are actually _rendered_ as a character (`←` with CHCP 437, some garbage chars with other CHCP code pages, including 65001/UTF-8) instead of _functioning_ as the escape char (it's probably being escaped or something).

The same command prints out as expected, and nicely coloured, when using Bash for Windows:

```
  basic:
    ✓ Line Comments
```

I'm aware that the CLI app can't really have fine control regard whether it's being invoked using Windows CMD, PowerShell, Bash or other terminals, especially in regard to code page settings in the CMD.

But it would be nice to have a dedicated option (e.g. `--ascii`) to disable escape sequences (ANSI colours, etc.) and avoid using characters which are not found in all monospace fonts, replacing them by ASCII versions (e.g. `[v]` instead of `✓`, `[x]` for the failure cross, etc.). This option would at least ensure a good experience with any kind of terminal. It would also be useful in automation, e.g. if storing output logs or parsing them, where colours escapes and fancy characters are not helpful.

I wonder if it is indeed possible for the Windows CLI app to query the environment and detect if it's running under CMD or Bash (the latter exposes the `MinGW*` env var, so it should be doable), because I believe it should be possible to preserve ANSI colours by tweaking the way escape characters are sent to STDOUT/STDERR under CMD — either that or a dedicated `--cmd` option (windows only) to enforce "DOS like" escape sequences.

To be clear, I often experience similar problems with Node.js applications, although some seem to manage better than others control over escape sequences and page code settings. So it's a problem commonly encountered when running cross-platform CLI tools under Windows, but also one for which there are probably some workarounds too.

I don't mind working with the Bash that ships with Git for Windows, since it natively adopts UTF-8 and has many cool commands and features, but it's slightly less performant than using the CMD, and doesn't overlap 100% with the CMD in terms of environment and available commands. I've also noticed that long running sessions often lead to the Bash becoming non respondent.

**Comment by tajmone** [comment]
# Rake Note

Interesting, I use Rake to automate my grammar repository:

```ruby
task :test do
  sh "tree-sitter test"
end
```

when invoked via Rake, the `tree-sitter test` command produces correct output in both Bash and CMD. Unlike when invoking it directly from CMD, via Rake the escape characters are correctly evaluated, leading to ANSI-coloured text in the output.

**Comment by amaanq** [comment]
I wonder if 0.12.1 of ansi_term fixed this, mind checking?

**Comment by tajmone** [comment]
> I wonder if 0.12.1 of ansi_term fixed this, mind checking?

I'm not sure what the above refers to (is that a library used by tree-sitter?), but I've tested it again using tree-sitter 0.20.8 and the behavior is unchanged, as described in the original post.

**Comment by sogaiu** [comment]
I think he might have been referring to [this](https://github.com/tree-sitter/tree-sitter/blob/89c2ab926fda33a9ee6b2e70e3b4f02eb2fa196d/cli/Cargo.toml#L23).

So may be testing out the master branch will do?

**Comment by sogaiu** [comment]
On a side note, a work-around I've been using for some other programs on Windows is to use [ansicon](https://github.com/adoxa/ansicon) -- that seems to help sometimes.

**Comment by amaanq** [comment]
Yeah, try out master

**Comment by sogaiu** [comment]
I gave it a try with 89c2ab926fda33a9ee6b2e70e3b4f02eb2fa196d and still see the issue.

With ansicon, it's a bit better.  I see color for each sub-item of test output, but I don't see the nice checkmarks.  Possibly the checkmark bits not working is something local.

**Comment by sogaiu** [comment]
Regarding the rake comment -- [this](https://rubyonwindowsguides.github.io/book/ch01-02.html) mentions ansicon...may be it (or something similar) gets used under the covers?

**Comment by tajmone** [comment]
I think that finding a universal solution for this on Windows (i.e. that works as expected with the CMD and using scripting languages) might be tricky. Probably a fix for the CMD would make these special characters show wrongly on Bash, not to mention problems with piping, etc.

I still think that the best solution would be to have an `--ascii` option (or something like that) to disable colors and special characters (checkboxes, etc.). This would be a safe solution to use with CMD, and also useful when the user wishes to redirect output to a file, etc.

**Comment by sogaiu** [comment]
For reference, there is [this](https://no-color.org/).

**Comment by amaanq** [comment]
tree-sitter supports `NO_COLOR` now - so I think this can be closed out. I think supporting pure ascii would be really painful since a variety of unicode characters are used in different spots, it'd be a lot of extra checks for one platform + terminal combo.
