### ISSUE TITLE
Libruntime API documentation

### ISSUE THREAD

**Issue by bizzyman** [tree-sitter/tree-sitter#166]
Is there any chance for an API documentation for tree-sitter?

**Comment by maxbrunsfeld** [comment]
Yes, apologies that there currently is none. What kind of documentation are you looking for? Would comments in the header file suffice?

**Comment by bizzyman** [comment]
> Would comments in the header file

That would be awesome! 

And maybe the libruntime API can have its own page in the docs folder in the future at some point?

**Comment by maxbrunsfeld** [comment]
Ok, [the docs site](http://tree-sitter.github.io/tree-sitter/) is now better organized and there's room to put a lot more information about the runtime API. I still need to actually *add* this information though.

**Comment by TheBB** [comment]
@maxbrunsfeld This is nice but I'm missing some documentation on object lifetimes. I'd like to build some bindings to tree-sitter from a dynamic language, and I can't necessarily guarantee that node objects won't be kept alive while the document is being edited. I'm assuming that

- a `TSTree*` will be invalidated when re-parsed (that is, when used as the `old_tree` argument to a parsing function), and that
- a `TSNode` is only as good as the `TSTree*` it came from.

It looks like I can create a new `TSTree*` with `ts_tree_copy`, that this is not an expensive operation (the actual *data* is not copied but shared), and that I can hang on to the copy, expose it to user interaction, and re-parse the original if I so desire, and that tree-sitter has internal refcounting logic to keep everything consistent?

**Comment by maxbrunsfeld** [comment]
> This is nice but I'm missing some documentation on object lifetimes. 

Yeah, I need explicit docs for this on each function. For now, I'll answer your specific questions here.

> a `TSTree *` will be invalidated when re-parsed (that is, when used as the old_tree argument to a parsing function)

No, that actually doesn't consume the `old_tree`; it just borrows it. The `old_tree` remains valid and you have to call `ts_tree_delete` to dispose of it.

> a `TSNode` is only as good as the `TSTree *` it came from

That's exactly right.

> It looks like I can create a new TSTree* with ts_tree_copy, that this is not an expensive operation (the actual data is not copied but shared), and that I can hang on to the copy, expose it to user interaction, and re-parse the original if I so desire, and that tree-sitter has internal refcounting logic to keep everything consistent?

Yes, exactly. That's what we do in Atom, using [node-tree-sitter](https://github.com/tree-sitter/node-tree-sitter).

**Comment by albfan** [comment]
I'm using ruby-tree-sitter (because it has a console) and discover the start_position, end_position and row, column. 

I'm trying to locate all elements foldable in a code, but not sure what to look for

document node_type names would be great

**Comment by clojj** [comment]
Hi,
Also relating to the runtime API documentation:
for me, the edit-related API is difficult to comprehend... from some tests I can see various usages of ts_tree_edit and ts_node_edit.
But still the general concepts are not obvious. In some tests, ts_tree_edit AND ts_node_edit are called, is that the recommended approach ?
How does TSInputEdit, which reports only edited _areas_ of the source, tell the parser about the actual changed contents of the source ?

Maybe it is easier to document this by a dedicated example...
1) parsing source initially
2) edit the source (as string!)
3) call whatever ts_*_edit is necessary for tree-sitter
4) call ts_parser_parse (is it ?)
5) show, in what TSTree/TSNodes the change results manifest

**Comment by clojj** [comment]
sorry, I think it just dawned on me..
The source-string or TSInput of the parser-call is actually changed (its just pointers)

So the TSInputEdit is just pointing the machinery to where the change happened.

**Comment by maxbrunsfeld** [comment]
No, The content of the string is not needed until you parse again. At that point, you again pass in the input.

**Comment by clojj** [comment]
I see.. either pass input again, or the updated char*
...depending on the 2 variants of ts_parser_parse

**Comment by clojj** [comment]
...and the fog begins to clear up ;)
thx for your patience

**Comment by clojj** [comment]
Just to be clear: the TSInputEdit is just a hint, so the parser can be more efficient, correct ?
a call to ts_parser_parse_string for example would also work, without it ?

**Comment by maxbrunsfeld** [comment]
When you parse, you have the option of parsing incrementally, by passing the old tree. This is much much faster than parsing from scratch.

If you do pass the old tree, the old tree needs to “line up” with the current text. When the text changes, you must edit the old tree in order to keep the tree in sync with the text.

**Comment by clojj** [comment]
yep, verified.. didn't read these C signatures carefully enough , thx

https://github.com/clojj/haskell-tree-sitter/commit/a1a335e97e229c96313ef255719f7ef24527f783

**Comment by clojj** [comment]
now.... on to integrating some of this stuff into some (Haskell-) editor for live-edit + tree-visualization... 
...fingers's crossed

**Comment by clojj** [comment]
thanks for updating the official docs

**Comment by maxbrunsfeld** [comment]
Header docs are in!

**Comment by ayazhafiz** [comment]
Would adding documentation to the library's source be the something the project finds useful? It's pretty easy to read, but it might be helpful to have more documentation of the library's inner workings.

Additionally, are the [runtime implementation docs](http://tree-sitter.github.io/tree-sitter/implementation#the-runtime) being actively worked on?
