### ISSUE TITLE
Rewrite core library in rust

### ISSUE THREAD

**Issue by rugk** [tree-sitter/tree-sitter#1670]
Why is the Core library written in C and Rust just a wrapper here?

I guess a rewrite, even if it (needs to) uses unsafe Rust to some extend at least, may still be potentially more safe against all kinds of memory overflow and other usual C problems.

Note how [The Linux kernel is partially rewritten in Rust](https://github.com/Rust-for-Linux/linux) and [libimagequant](https://github.com/ImageOptim/libimagequant) e.g. [went to converting their code to Rust](https://pngquant.org/rust.html). There are converters like [C2Rust available](https://c2rust.com/) that may make that easier.

**Comment by sogaiu** [comment]
For reference: https://github.com/tree-sitter/tree-sitter/pull/638

**Comment by dcreager** [comment]
Closing as a dup of #575 and #638.  As [mentioned there](https://github.com/tree-sitter/tree-sitter/issues/575#issuecomment-597278679), there are quite a few consumers of tree-sitter that benefit from only needing a C compiler.
