### ISSUE TITLE
Failed to highlight return type in C

### ISSUE THREAD

**Issue by itrishansh** [tree-sitter/tree-sitter#1681]
If additional attributes are present then tree-sitter is failed to highlight return type.

Example code:
#define __maybe_unused  __attribute__((unused))
static __maybe_unused void hello() {
}
static void hello1() {
}

**Comment by itrishansh** [comment]
![image](https://user-images.githubusercontent.com/5218066/156984496-bfc416ea-24d4-4a0f-8dc0-95b029bf6fac.png)

**Comment by ahelwer** [comment]
This should be closed here and the. opened against the nvim-treesitter repo. Look up the maintainer of the C grammar in that repo's readme and tag them in the issue.

**Comment by theHamsta** [comment]
I think any parsing errors due to marco usage are difficult to avoid in tree-sitter-c/tree-sitter-cpp. See https://github.com/tree-sitter/tree-sitter-cpp/issues/85 and closed related issues in this thread.

**Comment by dundargoc** [comment]
Looks like this should be opened in nvim-treesitter instead.
