### ISSUE TITLE
Allow configurable toolchain binaries

### ISSUE THREAD

**Issue by sluongng** [tree-sitter/tree-sitter#1686]
Currently tree-sitter infer the `node` binary location using of the PATH environment variable.
However in Build System(such as Bazel) who are (1) strict in how environment variable is managed and (2) manage their own NodeJS toolchain (i.e. Bazel's rules_nodejs), separate from the host, there may be a need to bring your own NodeJS binary.

Allowing passing the absolute path of the nodejs library through a flag of `tree-sitter` CLI would be much desirable for this use case.

Taking a look at current implementation, I see there are other tools which might be needed as well https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/tree-sitter/tree-sitter%24+Command::new&patternType=literal (docker, dot, id, emcc...). I can imagine we would also want to do the same for these toolchains in the future.

If it's not possible/too hard to use a flag, I can make do with a specific environment variable (i.e. `TREE_SITTER_NODE_PATH`) so that I avoid having to override PATH.

Let me know what you think.

**Comment by jakesarjeant** [comment]
FYI, I've implemented a (partial) solution to this in #2403, specifically the ability to specify a custom Node.js binary.
