### ISSUE TITLE
tree-sitter-cli@0.20.6 build wasm fail

### ISSUE THREAD

**Issue by SparkElf** [tree-sitter/tree-sitter#1696]
PS C:\Users\37465\Desktop\project\react-blog> npx tree-sitter build-wasm node_modules/tree-sitter-javascript   
emcc command failed - emcc: error: src\scanner.c: No such file or directory ("src\scanner.c" was expected to be an input file, based on the commandline arguments provided)

-tree-sitter-javascript:@0.19.0
-windows10
-docker

**Comment by frexsdev** [comment]
Not worry, it is just Windows. I think the only solution is to use Linux 😈

**Comment by amaanq** [comment]
I think this is probably fixed now if you actually had scanner.c in the proper path because the emcc compilation logic was reworked slightly. If not, then it's possibly because you accidentally removed it. I tested it myself and `tree-sitter build-wasm` works.
