### ISSUE TITLE
npm install tree-sitter-cli fails on linux ubuntu arm64

### ISSUE THREAD

**Issue by Alencar26** [tree-sitter/tree-sitter#1699]
### tree-sitter-cli is a dependency of lunarvim, during installation I'm getting this error:

``` bash
Cannot install tree-sitter-cli for platform linux, architecture arm64
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-cli@0.20.6 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter-cli@0.20.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-04T18_44_38_999Z-debug.log
```

**OS info:**
Ubuntu 20.04 LTS aarch64
kernel 5.1

**Log:**
[2022-04-04T18_44_38_999Z-debug.log](https://github.com/tree-sitter/tree-sitter/files/8412430/2022-04-04T18_44_38_999Z-debug.log)

**Comment by reportaman** [comment]
I have the same problem for ArchLinux arm64, tested under parallels apple m1.

**Comment by frexsdev** [comment]
What is your node version ? Try reinstalling it

**Comment by nettrino** [comment]
Same here with node 18.8.0

**Comment by charles-d-burton** [comment]
Same here, looks like they have the M1 arm64 support added but not the Linux support.

```npm ERR! Cannot install tree-sitter-cli for platform linux, architecture arm64````

**Comment by amaanq** [comment]
Safely assuming it's fixed as our CI can run it now

**Comment by zqudm** [comment]
root@autodl-container-d25111943c-47a1a17b:~/tree_sitter# npm -v
6.14.4
root@autodl-container-d25111943c-47a1a17b:~/tree_sitter# node -v
v10.19.0
root@autodl-container-d25111943c-47a1a17b:~/tree_sitter# npm install tree-sitter-cli

> tree-sitter-cli@0.20.8 install /root/node_modules/tree-sitter-cli
> node install.js

Downloading https://github.com/tree-sitter/tree-sitter/releases/download/v0.20.8/tree-sitter-linux-x64.gz
Download failed

url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.20.8/tree-sitter-linux-x64.gz
status: 503
headers: {
  "content-length": "0",
  "date": "Sat, 12 Aug 2023 07:38:02 GMT",
  "x-cache": "MISS from cache.autodl.com",
  "x-cache-lookup": "MISS from cache.autodl.com:12798",
  "connection": "close"
}

npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-cli@0.20.8 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-cli@0.20.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-12T07_38_06_085Z-debug.log
