### ISSUE TITLE
CSS Syntax highlighting

### ISSUE THREAD

**Issue by vinn2010** [tree-sitter/tree-sitter#1709]
I managed to get the syntax working for HTML/JS but the CSS syntax doesn't work for the keywords 

<img width="445" alt="1" src="https://user-images.githubusercontent.com/71597180/163658807-aaa2dfe4-e292-4390-855d-542566ab11d8.png">

how do I switch this on?

Apologies if this is the wrong place for this sort of issue.

**Comment by ahelwer** [comment]
The correct place is probably the neovim repo while tagging the people listed as maintainers of the css tree-sitter grammar. Before doing that though does your colorscheme actually map the keywords to a color? Try cycling through a few different color schemes to check. The neovim repo readme/wiki also has a list of recommended color schemes.

**Comment by frexsdev** [comment]
No on the Helix editor have the same problem it is the tree-sitter grammar not Neovim

**Comment by maxbrunsfeld** [comment]
What application are you using, Neovim? If so, can you open an issue there?

If you have specifically determined that the CSS is not *parsed* correctly, then open an issue on the [`tree-sitter-css`](https://github.com/tree-sitter/tree-sitter-css) repository, and report the source code, the expected parse tree, and the parse tree you're seeing.

**Comment by theHamsta** [comment]
@frexsdev the Helix editor has borrowed the queries from our repo. If we made a mistake it is likely that it has been copied over to Helix. Both nvim-treesitter and Helix have a `highlight.scm` in their repos that determines how the source code is highlighted.
