### ISSUE TITLE
version 0.20.6 produces incompatible libs on M1 mac

### ISSUE THREAD

**Issue by BrianHicks** [tree-sitter/tree-sitter#1713]
Following the instructions for creating a new parser (https://tree-sitter.github.io/tree-sitter/creating-parsers) I end up with tree-sitter-cli 0.20.6. When I try to run `tree-sitter test` with the "hello" grammar from that page, I get the following errors:

```
$ tree-sitter test
Error opening dynamic library "/Users/brianhicks/Library/Caches/tree-sitter/lib/fern.so"

Caused by:
    dlopen(/Users/brianhicks/Library/Caches/tree-sitter/lib/fern.so, 0x0005): tried: '/Users/brianhicks/Library/Caches/tree-sitter/lib/fern.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

$ file ~/Library/Caches/tree-sitter/lib/fern.so
/Users/brianhicks/Library/Caches/tree-sitter/lib/fern.so: Mach-O 64-bit dynamically linked shared library arm64
```

is this something I'm configuring wrong, or is it some quirk of the M1 architecture that hasn't been ironed out yet?

**Comment by maxbrunsfeld** [comment]
Tree-sitter is just shelling out to your systems default C compiler using default flags. Is there something unusual about how you have clang installed? This isn’t normally an issue with M1 macs; that’s what I use.

**Comment by BrianHicks** [comment]
I facepalmed at first—it totally makes sense that I'd be using the wrong compiler. However, it looks like `clang --version` reports clang 11.1.0 and aarch64-apple-darwin. I'm managing non-npm dependencies with Nix so that could potentially be it, though.

Anyway when I run `file node_modules/tree-sitter-cli/tree-sitter`, it does say it's an x86_64 executable. 🤔  Have you seen that before? Any idea how it could happen?

**Comment by BrianHicks** [comment]
I'm not sure what was going on here, but the problem went away when I started using the nixpkgs version of tree-sitter instead of the version the npm package downloads. Does looks like it might be some Rosetta issue. I'm not gonna ask you to debug why this is being weird for me though!
