### ISSUE TITLE
Is `repeat` left-associative or right-associative?

### ISSUE THREAD

**Issue by banacorn** [tree-sitter/tree-sitter#173]
I'm not sure if this is relevant to parsing or not.

However, there could be two ways of defining `repeat`. 
I'm wondering which is the case for the built-in combinator `repeat`.

## Left-associative:

```
Rules : {- empty -}
      | Rules Terminal
```
```javascript
function repeat(rule){
    return option(
        seq(repeat(rule), rule)
    )
}
```

## Right-associative:
```
Rules : {- empty -}
      | Terminal Rules
```

```javascript
function repeat(rule){
    return option(
        seq(rule, repeat(rule))
    )
}
```

**Comment by 314eter** [comment]
`repeat` is rewritten in terms of `repeat1`:
https://github.com/tree-sitter/tree-sitter/blob/64fd5d0b4b6fa6d1fc10f2cea0d60bcc51a94263/src/compiler/parse_grammar.cc#L98
and expanded here:
https://github.com/tree-sitter/tree-sitter/blob/8b70cb85f70c3b2b92fc6d7a0d8bde835fb45414/src/compiler/prepare_grammar/expand_repeats.cc#L59-L62

**Comment by banacorn** [comment]
@314eter Thanks! But I can't quite understand what those lines implies.

However, in the same file, could this be what I'm looking for?
https://github.com/tree-sitter/tree-sitter/blob/8b70cb85f70c3b2b92fc6d7a0d8bde835fb45414/src/compiler/prepare_grammar/expand_repeats.cc#L98-L101
Judging from these lines alone, `repeat`seems to be *left-associative*.

**Comment by 314eter** [comment]
No, that's not the expansion itself. The expansion is equivalent to
```js
function repeat(rule) {
    return optional(repeat1(rule))
}

function repeat1(rule) {
    return choice(
        seq(repeat1(rule), repeat1(rule)),
        rule
    )
}
```

**Comment by banacorn** [comment]
Another question about `repeat`: is it "privileged"? In the sense that it's a primitive with a special and dedicated implementation, hence better performance?

I'm asking this because it's tempting to define a `repeat`-like combinator with other primitives such as `choice` and `seq`. This is the case in many parser combinators of Haskell. They even tell people to implement their own `repeat` as a practice in tutorials, and that's pretty okay in Haskell because the compiler is smart enough to smooth it out.

**Comment by maxbrunsfeld** [comment]
> In the sense that it's a primitive with a special and dedicated implementation, hence better performance?

Good question. Repeats are indeed handled specially by Tree-sitter. In many ways, `repeat1` is equivalent to defining your own left-recursive rule. The differences are:

1. Recursion does not work inside of the `token` function, but `repeat` does. In the context of *lexer* generation, it is its own primitive construct. It's used internally to implement the `*` operator in regexes, for example.

1. By default, a left recursive rule with many repetitions would produce a very *unbalanced* syntax tree. The tree's structure would look almost like a linked list. By using `repeat`, you are instructing Tree-sitter that you explicitly do not care about the associativity, so Tree-sitter is free to balance the syntax tree for you, which produces massive performance improvements when incrementally updating syntax trees for large files.

For example, when parsing a long JavaScript array literal, Tree-sitter would produce this tree:

![balanced-tree](https://user-images.githubusercontent.com/326587/40992186-ed6c9342-68aa-11e8-8991-6f01e178ff3c.png)

**Comment by banacorn** [comment]
Thanks, good to know that!
I see how the question I asked is difficult to answer. 

The users should only use `repeat` to parse repetitive structures that are both **left and right-associative**, because `repeat` would use that property to rearrange the representation of the structure as it sees fit.
