### ISSUE TITLE
404 link in documentation

### ISSUE THREAD

**Issue by sodiboo** [tree-sitter/tree-sitter#1730]
The link to "Percent strings in Ruby" under the documentation pages site, which is located under the navigation sidebar at Creating Parsers > Lexical Analysis > External Scanners ([link to source](https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-3-creating-parsers.md#external-scanners)) goes to a page that returns 404 not found

**Comment by sogaiu** [comment]
Looks like the following might work as a substitute: https://docs.ruby-lang.org/en/2.5.0/syntax/literals_rdoc.html#label-Percent+Strings

**Comment by frexsdev** [comment]
Now you can do a pull request

**Comment by dundargoc** [comment]
Works for me now.
