### ISSUE TITLE
New javascript backend for tree-sitter instead of C

### ISSUE THREAD

**Issue by aryx** [tree-sitter/tree-sitter#1734]
@maxbrunsfeld did you ever consider generating .JS code directly from the tree-sitter grammars?

I would like to run semgrep in the browser, but some of the generated C code for certain grammars are really huge,
which would lead to big downloads and waiting time for the user (I guess the .wasm generated from those parser.c is also big).

Have you considered generating some more compact parser.js? It would be ok to generate simpler and slower code, as long
as the generated code is far smaller in size.

**Comment by ahelwer** [comment]
WASM files generally aren't big. My grammar's generated C file is like 30+ MB but the WASM is only around 3 MB.

**Comment by aryx** [comment]
"Only 3MB" ... do you many websites that require you to download 3MB of JS/wasm before being able to use it? 3MB in the web world is huge.

**Comment by ahelwer** [comment]
Anyway, how would this proposed solution handle external scanners?

**Comment by maxbrunsfeld** [comment]
The C#, C++, and TypeScript parsers are currently the biggest downloads, weighing it at 214k, 161k, and 154k gzipped:

![Screen Shot 2022-05-03 at 10 18 52 AM](https://user-images.githubusercontent.com/326587/166505371-b57e9452-fe65-4b6b-b4fe-82e27cabe067.png)

I'd love to make them as small as possible, but this is already well within the expected range for highly-cacheable assets on a web page.

For comparison, when I hit `semgrep.dev` with an empty cache, there's already a much larger amount of JavaScript downloaded :

![Screen Shot 2022-05-03 at 10 21 31 AM](https://user-images.githubusercontent.com/326587/166505908-896894db-c926-4ecb-bfc0-43a14115c07d.png)

**Comment by aryx** [comment]
haha, good point :)

**Comment by aryx** [comment]
BTW how frequently is updated the tree-sitter playground? Does it use the latest versions of the language grammars?
