### ISSUE TITLE
Native Apple Silicon (M1, .etc) support?

### ISSUE THREAD

**Issue by imWildCat** [tree-sitter/tree-sitter#1737]
As of now, we only have x86 build for M1 Macs: 

```js
// ARM macs can run x64 binaries via Rosetta. Rely on that for now.
if (platformName === 'macos' && process.arch === 'arm64') {
  archName = 'x64';
}
```

Commit: <https://github.com/tree-sitter/tree-sitter/issues/942>

Any reason?

**Comment by typesanitizer** [comment]
I don't know the reason but I suspect it is because GitHub Actions don't have M1 Mac runners. Cross-compiling from x86_64 to arm64 is generally more tedious with C code IME. Running the tests on the arm64 binary would also require QEMU or similar.

**Comment by imWildCat** [comment]
Thanks!

Did we try something like https://github.com/messense/cargo-zigbuild ?

If not, I can start to try it!

**Comment by typesanitizer** [comment]
I don't know (I just saw this issue as I was passing by) but that would only resolve the build aspect (which might be OK, I'm not sure if that was the main blocker or if the ability to run tests was).

**Comment by amaanq** [comment]
I'm gonna safely close this as it seems to work now in our CI and works on my Mac
