### ISSUE TITLE
Add support for my language 👍🏻

### ISSUE THREAD

**Issue by frexsdev** [tree-sitter/tree-sitter#1755]
# Idea

I've created my own programming language and I have no time to create a tree-sitter grammar 😞 Who can do this for me please ?

- The github: https://github.com/frexsdev/bang
- The website: https://bang-lang.vercel.app/

Thanks !

**Comment by ahelwer** [comment]
lol nobody is going to do this for you.

**Comment by frexsdev** [comment]
> lol nobody is going to do this for you.

Maybe but, now, you know about it and many other people will discover hit 🐀

**Comment by rhysd** [comment]
> I have no time to create a tree-sitter grammar 😞

That's not a problem of tree-sitter. This issue should be created in your project so that some people interested in your language can notice the issue.
