### ISSUE TITLE
Getting the current character using external scanner

### ISSUE THREAD

**Issue by Jomy10** [tree-sitter/tree-sitter#1756]
I'm trying to figure out how to write an external parser. I've  looked at the source code of other tree sitters for popular languages, but I could not find a solution for this.

So let's say I want to parse `8)` as a token type.

in te `external_scanner_scan` function I put the following code:

```c
printf("%c", lexer->lookahead);
return false;
```

When I now run this on a source file just containing `8)`, I get the following output:

```
)
```

So, how can I access the current character?

**Comment by ahelwer** [comment]
The lookahead *is* the current character for all intents and purposes. The 8 must have been consumed by something before calling into the external scanner.

**Comment by Jomy10** [comment]
I stripped away everything and that indeed gave mee the correct result. Thanks for the tip. 

I think what the problem was that it was picking up the tokens defined after the "program", which I didn't account for.
