### ISSUE TITLE
web-tree-sitter 0.20.5 breaking test suite

### ISSUE THREAD

**Issue by razzeee** [tree-sitter/tree-sitter#1770]
I've tried to update web-tree-sitter to 0.20.5 and while it seems fine in most cases, there is one test case, where it's not happy anymore.
https://github.com/elm-tooling/elm-language-server/pull/715

Would I need to bump any of the other deps too? I've tried with the newest versions of each, but that doesn't help, the error still exists. https://github.com/elm-tooling/elm-language-server/pull/704

So it could be a regression in web-tree-sitter. A version 0.20.4 would probably be helpful to bisect this some more.

**Comment by amaanq** [comment]
Is this still an issue?

**Comment by razzeee** [comment]
No, we figured something out three month ago. Sorry for not closing.
