### ISSUE TITLE
Testing multiple queries

### ISSUE THREAD

**Issue by vigoux** [tree-sitter/tree-sitter#1790]
Hi,

When developping a tree-sitter parser for [viml](https://github.com/vigoux/tree-sitter-viml) (especially https://github.com/vigoux/tree-sitter-viml/pull/107), I wanted to start testing mutiple queries in a format similar to highligh tests.

To do this I had to come up with [this ugly hack](https://github.com/vigoux/tree-sitter-viml/commit/4e1f656a69310a1603b78089f8ce83d33801a4b5) and I wonder if there is a way to make the testing a bit more elegant, maybe by specifying queries in a directory, and tests machting the name of a given query in another directory.

If this is not planned, I would be glad to implement it as, from what I see, the code should be pretty much ready for something like this.

**Comment by amaanq** [comment]
Was closed by #3674
