### ISSUE TITLE
[tracking] Randomized test failures

### ISSUE THREAD

**Issue by maxbrunsfeld** [tree-sitter/tree-sitter#18]
Gonna leave this open, as a persistent place to put these:

| Seed | Language | Example | URL |
|------|-------|----------|------|
| 1598044656 | cpp | Nested template calls | [appveyor](https://ci.appveyor.com/project/maxbrunsfeld/tree-sitter/builds/34791094/job/y4u85hwi2g5jkvv6) |
| 1558054205 | go | Type switch statements - trial 2 | [travis](https://travis-ci.org/tree-sitter/tree-sitter/jobs/533585024)
| 1558389555 | go |  Type switch statements - trial 10 | [appveyor](https://ci.appveyor.com/project/maxbrunsfeld/tree-sitter/builds/24683112/job/9fs2903r6giydx2q)

**Comment by ahlinc** [comment]
I'm closing this as totally out of date issue:
- There are no more AppVeyor and Travis CI in use in this repo.
- There were a lot of improvements done to make CI/CD reliable.
  - The current behavior is to run all flaky tests with 10 retries.
- The support of TREE_SITTER_TEST_TRIAL_FILTER env var was removed in 7170ec7c.
