### ISSUE TITLE
can't derive grammar from a base grammar which uses an external scanner

### ISSUE THREAD

**Issue by orzechowskid** [tree-sitter/tree-sitter#1808]
I'm attempting to create a grammar derived from tree-sitter's CSS grammar and, based on the suggestions in [this comment](https://github.com/tree-sitter/tree-sitter/issues/646#issuecomment-647781353), have come up with (basically) the following:

```
// tree-sitter-css/my_grammar/grammar.js

module.exports = grammar(require('../grammar'), {
  name: 'my_grammar",

  rules: {
    x: seq('foo', 'bar'),
    _block_item: ($, original) => choice(original, $.x)
  }
});
```
I'm able to `cd my_grammar` and run `tree-sitter generate` without errors; subsequent running of `npx node-gyp configure` and `npx node-gyp build` also finishes without errors.  but running `tree-sitter test` or `tree-sitter parse foo.txt` give me this error:

```
Error opening dynamic library "/home/orzechowskid/.tree-sitter/bin/my_grammar.so"
Details:
  /home/orzechowskid/.tree-sitter/bin/my_grammar.so: undefined symbol: tree_sitter_my_grammar_external_scanner_create
```

this derived grammar has no need for an external scanner, though the base grammar it derives from does.  is there a way to configure some combination of tree-sitter, node-gyp, and my grammar file to use tree-sitter-css' external scanner?

thanks!

**Comment by amaanq** [comment]
currently you need to just copy the scanner over and rename the relevant tree_sitter_LANG_external_scanner_ACTION functions w/ your language name, but this should be done automatically if there's no scanner file maybe

**Comment by ahlinc** [comment]
> "/home/orzechowskid/.tree-sitter/bin/my_grammar.so"

For now this looks like old Tree-sitter CLI, update your CLI to the latest.

> is there a way to configure some combination of tree-sitter, node-gyp, and my grammar file to use tree-sitter-css' external scanner?

It's possible to put most of the base external scanner impl into a separate file like `scanner_impl.c` except `tree_sitter_LANG_external_scanner_ACTION` functions. And in the `scanner.c` it would be possible to do:
```c
#include "scanner_impl.c"

void *tree_sitter_css_external_scanner_create() { return NULL; }
void tree_sitter_css_external_scanner_destroy(void *p) {}
void tree_sitter_css_external_scanner_reset(void *p) {}
unsigned tree_sitter_css_external_scanner_serialize(void *p, char *buffer) { return 0; }
void tree_sitter_css_external_scanner_deserialize(void *p, const char *b, unsigned n) {}
```

Then in derived scanner it would be possible to write:

```c
#include "../../src/scanner_impl.c"

void *tree_sitter_my_grammar_external_scanner_create() { return NULL; }
void tree_sitter_my_grammar_external_scanner_destroy(void *p) {}
void tree_sitter_my_grammar_external_scanner_reset(void *p) {}
unsigned tree_sitter_my_grammar_external_scanner_serialize(void *p, char *buffer) { return 0; }
void tree_sitter_my_grammar_external_scanner_deserialize(void *p, const char *b, unsigned n) {}
```

_Also don't forget to define all non `tree_sitter_` functions as `static` to avoid name clashes with static linking of multiple grammars into a one binary._
