### ISSUE TITLE
RegEx: Not matching decimal_number.

### ISSUE THREAD

**Issue by thchha** [tree-sitter/tree-sitter#1812]
Hey Max.
Thank you for researching about and creating tree-sitter.

I am working on a grammar which is accessible at: https://gitlab.com/thchha/tree-sitter-r5rs
I try to keep the depth flat but conform to the specification.
I do not translate the existing grammar _as it_.

Within this grammar, I declared a rule to match `decimal_number`, which should conform to `R5RS` (https://www.schemers.org/Documents/Standards/R5RS/HTML/r5rs-Z-H-10.html#). Anyhow, the prompted rule is unable to resolve _simple_ decimal numbers. Therefore I prepended the `seq` with a regex which _resolves the issue, but raises concerns_ at the current state.

The used RegEx is working at https://www.regexr.com , but within the parser.
It resolves the _difficult_ matches, but the last member of the declared group (`_real_d:`).
The actual definition should be listed as: 
```javascript
    decimal_number: $ =>
      seq(
        optional(
          choice(
            /(#(d|D))(#(e|E|i|I))?/,
            /(#(e|E|i|I))?(#(d|D))/,
          ),
        ),
        choice(
          $._real_d,
          seq($._real_d, /@/, $._real_d),
          seq($._real_d, $._real_d),
          seq($._real_d, $._real_d, /i/),
          seq($._real_d, /i|\+i|\-i/ ),
          /\+i|\-i/,
        ),
      ),
```
> this differs to the repository, since I wanted to make the tests pass.

It is either a bug, a documentation issue or I need assistance.

Additionally I am able to match (as a suffix): `/\+i|\-i/` but a `/i/` when parsing _any_ of the declared numbers (binary, octal, decimal, hexadecimal).

Thank you in advance (and all contributors as well).

Sincerly,
Thomas

**Comment by ahelwer** [comment]
What is the definition of `$._real_d`? What is an input you expect to be recognized by the rule, but is not recognized?

**Comment by thchha** [comment]
Very much appreciate the fast reply!
The definition is at: https://gitlab.com/thchha/tree-sitter-r5rs/-/blob/master/grammar.js#L230 .
I expect the following input to be recognized:

`4`
`-1`
`+3`

They are not recognized.
Maybe there lies the error: I assumed `#` was a character. I did not escape this character, but used it explicitly within the grammar.
Escaping from `#` (read, using `\#`), does not resolve it.

**Comment by thchha** [comment]
I resolved the issue, by declaring a hidden parent rule, which explicitly matches without a prefix.
This resolved not matching the simple numbers.
Then, I had to tell within my sequences that my tokens follow immediately without whitespaces.
So both problems were due to not studying carefully.
Thanks and sorry.
