### ISSUE TITLE
How to align tests by characters rather than bytes?

### ISSUE THREAD

**Issue by mr-martian** [tree-sitter/tree-sitter#1826]
So I have a highlighting test that currently looks like this:
```
        a e ä i o ö u ü y ý ;
!                               ^ punctuation.delimiter
```
According to the test runner, the caret is pointing at the semicolon since the non-ASCII ä, ö, ü, and ý are each 2 bytes rather than 1.

Would it be possible to have it align columns based on characters rather than bytes, either in general or as a configuration option somewhere?

**Comment by amaanq** [comment]
This was fixed by #3610
