### ISSUE TITLE
Playground assertion

### ISSUE THREAD

**Issue by shaded-enmity** [tree-sitter/tree-sitter#1829]
I'm using `tree-sitter 0.20.6 (3739b7794e381582c8f4a37b2ccec756c3504984)` and when I `generate && build-wasm && playground` and open the browser and enter some text nothing happens and this is what I see in the console.

```
RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.
```

The debugger points at this line in `playground.js`:

```javascript
326: const node = tree.rootNode.namedDescendantForPosition(start, end);
                  ^^^^ undefined
```

I tried building with `cargo build -s ASSERTIONS=1` which didn't work and yeah, cargo doesn't really support `-s` so it must be some intermediate toolchain asking for this (perhaps `emcc`?). 

What is the best way to ensure proper toolchain receives that argument?

**Comment by ahelwer** [comment]
Is this similar to your issue? Currently you can only use certain libraries in your scanner: https://github.com/tree-sitter/tree-sitter/issues/1300

**Comment by sogaiu** [comment]
Regarding `-s`, for reference: https://emscripten.org/docs/tools_reference/emcc.html#emcc-s-option-value

**Comment by shaded-enmity** [comment]
@ahelwer The symptoms look similar, however I'm not using external scanners -- for reference I'm working on this grammar: https://github.com/shaded-enmity/tree-sitter-rego/blob/complete-ebnf-grammar/grammar.js

@sogaiu Thanks, I'm gonna try it out with the assertions and see where that leads.

**Comment by shaded-enmity** [comment]
Tried it out with the following patch but no dice, still the same error message.

```diff
--- a/cli/src/wasm.rs
+++ b/cli/src/wasm.rs
@@ -75,6 +75,8 @@ pub fn compile_language_to_wasm(language_dir: &Path, force_docker: bool) -> Resu
         &output_filename,
         "-Os",
         "-s",
+        "ASSERTIONS=1",
+        "-s",
         "WASM=1",
         "-s",
         "SIDE_MODULE=1",
```

**Comment by ahelwer** [comment]
What version of emcc are you using? AFAIK you need to use <= 2.0.17, see https://github.com/tree-sitter/tree-sitter/issues/1098#issuecomment-842326203

**Comment by shaded-enmity** [comment]
@ahelwer Thanks that was it :+1: I was using the latest.
```
$ emcc --version
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.17 (fbc532773d84d2bd7da876275671970e792ad1cd)
```

Then I switched with `emsdk install 2.0.17 && emsdk activate 2.0.17` and voila, playground works!

Is there a reason why newer `emcc` is not supported, apart from the incompatibility issues? I'm wondering if this is something I could help fix.

**Comment by dundargoc** [comment]
This still a problem?

**Comment by dundargoc** [comment]
> The specific issue isn't a problem but it is still a problem that we are required to use an old version of emscripten because people will keep being bit by that, so maybe track that issue elsewhere

Oh, I see what you mean. Yes, thanks.

**Comment by dundargoc** [comment]
@sogaiu that's a good idea. Mind checking the issues to see if it's been suggested, and if not write a feature request?

**Comment by amaanq** [comment]
I can confirm this is no longer a problem using 0.23.0 of tree-sitter with emcc v3.1.61-git
