### ISSUE TITLE
Token mismatch with external scanner

### ISSUE THREAD

**Issue by notoria** [tree-sitter/tree-sitter#1830]
I'm trying to create a parser following the example. This is the [repository](https://github.com/notoria/tree-sitter-prolog).

And I have the following issue (all the files are on the repository):
```
$ tree-sitter generate; tree-sitter parse test.pl
Warning: You have not configured any parser directories!
Please run `tree-sitter init-config` and edit the resulting
configuration file to indicate where we should look for
language grammars.

token layout
token in: 0x61 'a'
token out: 0x61 'a'
token alphanumeric (name)
token in: 0x62 'b'
token out: 0x0a '
'
token layout
token in: 0x00 ''
token out: 0x00 ''
(source_file [0, 0] - [1, 0]
  (end [0, 1] - [0, 4]))
$ cat test.pl
 abc
$
```
The `end` token is accepted instead of `layout` and `letter_digit`. I'm very surprise, maybe I'm triggering some undefined behavior but I have no idea why.

Any help is welcome.

**Comment by ahelwer** [comment]
In the event of a parse error your external scanner will be called with all symbols marked as valid. Does your scanner handle that?

**Comment by notoria** [comment]
The implementation is incomplete, I'm still writing it and I'm testing with `test.pl`. I don't understand, what is the parse error in this case. If a token isn't recognized then the scan function return false.

Does this mean that I have to write the parse incrementally? I can't enable all token types and recognize a subset.

**Comment by notoria** [comment]
Thank you. I should have read the fine print.
