### ISSUE TITLE
Alias of an extra affects all appearances of the extra

### ISSUE THREAD

**Issue by nmote** [tree-sitter/tree-sitter#1834]
Aliasing an extra in any rule in the grammar (even an unused rule) changes the name of the extra everywhere it is reported. My understanding is that an alias is meant to apply locally, to only the part of the grammar where it is used, and not to make any global changes to the name of the rule being aliased.

I came across this because I am addressing https://github.com/returntocorp/ocaml-tree-sitter-core/issues/36. One of the extras in the Swift grammar also appears in another rule. Currently, ocaml-tree-sitter-core cannot handle this, because to construct a typed CST it needs to discard extras first. I am adding a pass which rewrites the grammar to alias any extras that appear in ordinary rules so ocaml-tree-sitter-core can distinguish those extras from others. Unfortunately, due to this issue, the alias causes all instances of that extra to be renamed, so it's still impossible to tell which extras need to be discarded.

Here is a concrete example:

`grammar.js`:

```
module.exports = grammar({
  name: "extra_test",
  extras: $ => [
    $.comma,
    "\n"
  ],
  rules: {
    program: $ => "foo",
    comma: $ => ",",
    unused: $ => alias($.comma, $.comma_other),
  }
});
```

`testfile`:
```
,foo,
```

Output of `tree-sitter parse testfile`:

```
(program [0, 0] - [1, 0]
  (comma_other [0, 0] - [0, 1])
  (comma_other [0, 4] - [0, 5]))
```

Expected output of `tree-sitter parse testfile`:

```
(program [0, 0] - [1, 0]
  (comma [0, 0] - [0, 1])
  (comma [0, 4] - [0, 5]))
```

**Comment by maxbrunsfeld** [comment]
Great bug report. Thank you!

**Comment by nmote** [comment]
Do you have a sense for when/if this might be addressed, and how involved the fix would be?

**Comment by nmote** [comment]
I believe I've found a workaround, but it's not pretty. Tree sitter uses the first alias it encounters to rename the extra, so I can insert unused rules just below the first rule that alias the extra to itself:

```
module.exports = grammar({
  name: "extra_test",
  extras: $ => [
    $.comma,
    "\n"
  ],
  rules: {
    program: $ => "foo",
    unused2: $ => alias($.comma, $.comma),
    comma: $ => ",",
    unused: $ => alias($.comma, $.comma_other),
  }
});
```

This appears to lead to the desired result, even in the more complicated real-world grammar I am dealing with. This won't work if the extra appears in the very first rule, but that seems unlikely to occur in practice. If it did, we could probably extend the workaround by inserting a new first rule that consists only of the old first rule, followed by the list of aliased extras, followed by the old first rule.

It would still be great to get this fixed, though. If nobody more familiar with tree sitter has a chance to work on it, I'd be happy to give it a try if someone can point me in the right direction.

**Comment by nmote** [comment]
I put up a PR to fix: https://github.com/tree-sitter/tree-sitter/pull/1836
