### ISSUE TITLE
Query to highlight node when it matches some string

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#1838]
I have a simple node:
```js
    basic_identifier: $ => token(seq(
      /[a-zA-Z]/,
      repeat(seq(
        optional('_'),
        /[a-zA-Z0-9]/
      ))
    )),
```
This node should be highlighted only if it matches some string pattern, for example `foo`. Is it doable without introducing an extra node and making a choice?

**Comment by ahelwer** [comment]
If your highlighting system implements an appropriate predicate you could use that, but otherwise no.

**Comment by m-kru** [comment]
So, it all depends on the editor implementation, doesn't it?

**Comment by ahelwer** [comment]
Yes.
