### ISSUE TITLE
Gen Parser passes but build-wasm fails

### ISSUE THREAD

**Issue by vjerci** [tree-sitter/tree-sitter#1840]
Using `tree-sitter gen` of parser passes but using `tree-sitter build-wasm` fails
Any reason for that or how to fix it?

Full issue is explained here:
https://github.com/m-novikov/tree-sitter-sql/issues/66

Seems like c++ version is wrong somehow.

**Comment by ahelwer** [comment]
Yeah I don't think you can use any features after C++99 in your external scanner. Also you have to be pretty restrictive with which stdlibs you include.

**Comment by vjerci** [comment]
Thank you for your swift response.
I'll try to update parser.

**Comment by ahlinc** [comment]
This will be resolved with #1262

**Comment by amaanq** [comment]
C++ scanners are deprecated and will be unsupported soon - if you'd like to make use of array-like data structures an array header is now built into the `src/tree_sitter` directory when you run `generate`.
