### ISSUE TITLE
Segmentation fault on parse error

### ISSUE THREAD

**Issue by camdencheek** [tree-sitter/tree-sitter#1842]
I just received [a report](https://github.com/camdencheek/tree-sitter-dockerfile/issues/22#issuecomment-1219024273) of a segmentation fault on the Dockerfile grammar I maintain. There are definitely issues with how newlines are handled in the grammar, but I wouldn't expect tree-sitter to segfault during errors. 

The issue is reproducible on a Mac M1 system, and I cannot reproduce the issue on a Linux x86_64 system. 

Reproduction steps (credit @kopecs):

```bash
git clone git@github.com:camdencheek/tree-sitter-dockerfile.git \
    && cd tree-sitter-dockerfile \
    && printf 'LABEL A=$B' > Dockerfile \
    && tree-sitter generate \
    && tree-sitter parse Dockerfile
```

Environment: 
MacOS 12.5.1
```bash
clang --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0
Thread model: posix
```

Happy to provide some more debugging information if needed.

**Comment by ahelwer** [comment]
Does the grammar have an external scanner? Have you checked whether the segfault is coming from there?

**Comment by camdencheek** [comment]
There is no external scanner for the Dockerfile grammar, only code generated by the `grammar.js`

**Comment by aryx** [comment]
cc @maxbrunsfeld , seems pretty bad to get a segfault.
This actually completely crashes semgrep because there's no easy way to recover from a segfault.

**Comment by jaskaransinghdr6j** [comment]
Any update on this? This is blocking a lot of downstream automation.

**Comment by melsabagh-kw** [comment]
This doesn't seem limited to Dockerfile. I am experiencing the same issue on Java files as well on macOS 12.4 x86. Running `semgrep` on the attached [akp.java.txt](https://github.com/tree-sitter/tree-sitter/files/10037390/akp.java.txt) file produces the same error:

```shell
$ semgrep scan --max-target-bytes 0 --config 'r/java.' akp.java.txt
...
Error while running rules: 0 bytes read on a total of 2 expected bytes
```

**Comment by camdencheek** [comment]
I can no longer reproduce this with tree-sitter 0.20.7. Is anyone else still getting this error?

**Comment by amaanq** [comment]
I can't either, will close for now unless someone else has another reproducer
