### ISSUE TITLE
How to use the parser in Javascript?

### ISSUE THREAD

**Issue by wongjiahau** [tree-sitter/tree-sitter#185]
Based on the documentation, if I'm not mistaken, the only way to use the parser is via C, but my current language development uses Javascript to do code generation. So, I'm wondering if it is possible to output the syntax tree generated by parser(generated using tree-sitter) into JSON? Because I'm considering to switch from [jison](https://github.com/zaach/jison) to tree-sitter after watching [this video](https://www.youtube.com/watch?v=a1rC79DHpmY).

**Comment by wongjiahau** [comment]
I just found the answer at [https://github.com/tree-sitter/node-tree-sitter](https://github.com/tree-sitter/node-tree-sitter).

**Comment by maxbrunsfeld** [comment]
Yeah, sorry the docs are a work in progress. Glad you found it!

**Comment by wongjiahau** [comment]
@maxbrunsfeld I have one problem, how do I know what is the name for the language? For example, I tried to generate the grammer for this `arithmetic` language (based on the [README.md of tree-sitter-cli](https://github.com/tree-sitter/tree-sitter-cli)). 

Then I have this `binding.gyp` file, but how do I import it in to Javascript file?  The example given [here](https://github.com/tree-sitter/node-tree-sitter) is 
```js
const Parser = require('tree-sitter');
const JS = require('tree-sitter-javascript'); // <--- How do I know what name to use??

const parser = new Parser();
parser.setLanguage(JS);
```
Where does the name comes from?

**Comment by wongjiahau** [comment]
@maxbrunsfeld  No worries, I would try to help out if I figured out how to use the parser in Javascript.

**Comment by wongjiahau** [comment]
Finally I found out how to do it. Will close this once I created a PR for the documentation.

**Comment by maxbrunsfeld** [comment]
Ok, the [section](http://tree-sitter.github.io/tree-sitter/using-parsers#using-parsers) of the docs about  using the parsers now links to `node-tree-sitter` explicitly. I'm going to close this one out. Thanks for pointing out some missing pieces on this.
