### ISSUE TITLE
Loading a pre-compiled parser without its associated source tree?

### ISSUE THREAD

**Issue by gwerbin** [tree-sitter/tree-sitter#1850]
## Feature request

Is it possible (or can it be easily made possible) to run the Tree Sitter CLI with *just* compiled parsers and not the associated `grammar.json`, etc. files that you'd find in a parser source tree?

Does the design of Tree Sitter allow for this, or does the CLI tool require the metadata from the source tree to provide functionality such as `query`, `highlight`, and `tags`?

If not, what are the minimum required files that an end-user (as opposed to a developer) needs on their machine in order to use a grammar without generating or compiling anything?

## Use case

I would like to use the Tree Sitter CLI itself for light-duty scripting and CLI-based workflows. `tree-sitter query`, `tree-sitter tags`, and `tree-sitter highlight` are more than good enough for me!

Ideally I'd be able to download pre-built parsers from a package registry like MacPorts and not have to worry about maintaining a big pile of Git source repos + Node, Gyp, `NODE_PATH=~/src/tree-sitter-parsers`, and my own script to build it all from source and keep the source repos up to date. I'd like to be able to just `sudo port install tree-sitter-javascript` and not have to think any harder about it.

I think a lot of current users are developers of language tooling, so maybe this isn't something that a lot of you all might find useful. But I think this feature could make life a lot easier for "consumers" of Tree Sitter.

**Comment by amaanq** [comment]
Yeah, you don't need `grammar.json` and friends to use the CLI's commands such as `parse`, `query`, `tags`, and `highlight`. All you need is the compiled parser (as a shared library), and the query you want to use. Note that you would have to put the compiled parser in the standard cache path for your operating system (as you mentioned MacPorts, I'm assuming you're using macOS, and as such that can be found in `~/Library/Caches/tree-sitter` I believe, and compiled parsers go in the `lib` folder in there).
