### ISSUE TITLE
Question about ESM / grammar.js format

### ISSUE THREAD

**Issue by drwpow** [tree-sitter/tree-sitter#1854]
Hello! I’ve been experimenting with tree-sitter and web-tree-sitter for modern, efficient syntax highlighting in browsers (mostly in JS frameworks like Svelte and Vue). I notice most of the code still uses CommonJS rather than ESM. While this doesn’t make compiling in a modern build tool like Vite impossible, it does make it a bit more unwieldy. Are there any plans to update code to ESM? _This would still work in Node and webpack now that both support ESM natively_

A second question was around importing `grammar.js` in tree-sitter-javascript`, etc. Those files have a `grammar()` function global that make consuming those files individually hard to do without first transforming it. What is the reason for the global function (rather than, say, `import { grammar } from 'tree-shaker'`, e.g.)?

Thanks for the project! I’ve really enjoyed reading all the well-written docs and philosophy behind it.

**Comment by theHamsta** [comment]
> A second question was around importing grammar.js in tree-sitter-javascript, etc. Those files have a grammar()function global that make consuming those files individually hard to do without first transforming it. What is the reason for the global function (rather than, say,import { grammar } from 'tree-shaker'`, e.g.)?

You don't need grammar.js or the `grammar` function at all. grammar.js is just for code generation of the parser. The steps are
 - grammar.js (NodeJS) -> node-type.json (via Rust) -> parser.c (via emscipten) -> wasm module
 You would use the final wasm module for webapps. All other previous steps are handled by tree-sitter-cli and are just compilation steps that don't affect your webapp.

**Comment by drwpow** [comment]
Ah thanks for the explanation! I guess I should have clarified I was actually interested in the grammar itself, because I was trying to follow all the steps the parser generation took. Just to satisfy my own curiosity.

**Comment by drwpow** [comment]
Looked into this a bit more and I understand how the parser works a bit better now. Upgrading to ESM would be nice for portability, but it would be a breaking change to the grammar format (`module.exports` becomes `export default` but that’s it).

If that breaking change were to happen it might be good to make that sooner rather than later, but I’ll let y’all decide if that’s worth pursuing. Since this ticket was just a question I’ll close it. Thanks! 🙂
