### ISSUE TITLE
Question about large Wasm files for web

### ISSUE THREAD

**Issue by drwpow** [tree-sitter/tree-sitter#1860]
I’ve been really excited about the possibility of tree-sitter on the web, especially for things like OSS docs and code snippets. But when I look at the size of the generated `wasm` files it seems to pose an issue:

- TypeScript alone is `1.2 MB` unpacked (not gzip, also incl. `tree-sitter.wasm`)
- Adding JS + HTML + YAML is ~`1.6 MB` unpacked
- Playground doesn’t have JS framework languages but I’d assume TSX is another ~`1 MB` (since it’s the same as TypeScript). Haven’t profiled grammars for Svelte/Vue.

I’m thinking for the practical usecase of OSS documentation where there are typically 5–6 syntaxes, and dozens of snippets per-page where all 6 languages could appear. With so much else going on on the page, several MBs just for syntax highlighting isn’t ideal.

I’m also thinking about usage in SSR via lambda functions or edge workers that may not have the same memory/resource limits and it could struggle with too many large Wasm files loaded in memory.

Are the filesizes in part due to the translation through C + emscripten? In my experience wasm-pack is extremely-efficient size-wise, but I know that the grammars depend on C and not Rust. My question isn’t around changing that architectural decision, rather, I wanted to understand where some of the size could be coming from and how it could potentially be better-optimized for web, that’s all!

**Comment by ghishadow** [comment]
you might like https://lezer.codemirror.net/ which is inspired by tree-sitter and made for web.

**Comment by ahelwer** [comment]
You can always render the syntax server-side or during the website compilation process, depending on your static site generator.

**Comment by maxbrunsfeld** [comment]
The `.wasm` files compress very well with gzip (and especially with brotli); not sure if you've already tried that. If you look at the download sizes when using the playground, they're pretty reasonable. That's with gzip, because GH doesn't support brotli compression, but they're quite a bit smaller if you use brotli.

![Screen Shot 2022-09-07 at 9 29 16 AM](https://user-images.githubusercontent.com/326587/188931286-27859bc5-37f7-457c-bcbd-bcd27ce48f97.png)

**Comment by maxbrunsfeld** [comment]
Just for context, the large binary size is something that we've put in a fair amount of work in to mitigate, and I'd love for the sizes to be be smaller. I think that there is more work we could do on the parser-generation side to figure out smart optimizations, but I don't think there are that  many super *easy* opportunities for optimizing it. The challenge is just that we have a very large state machine that we need to store, using fairly large static arrays.

**Comment by drwpow** [comment]
Thanks all for the info and additional context! Completely understand that there aren’t many “quick wins” here. As this issue was just a question, I think it’s been answered! 🙂 Now I’m interested to dive a bit deeper into the parser generation process. This is such an interesting project it’s been fun to learn from!

**Comment by ahelwer** [comment]
@drwpow you may be interested in this that was just posted: https://github.com/tree-sitter/tree-sitter/discussions/1861
