### ISSUE TITLE
Precedence on choice does take effect

### ISSUE THREAD

**Issue by asmyers** [tree-sitter/tree-sitter#1863]
Using `tree-sitter` 0.20.7 installed through cargo this grammar for a simple predicate calculus parser results in a conflict error when running generate:

```javascript
module.exports = grammar({
    name: 'Predicate_Calculus',

    rules: {
      // TODO: add the actual grammar rules
      source_file: $ => repeat($._expression),
      _expression: $ => choice($.identifier,
                               $._unary_expression,
                               $._binary_expression,
                               seq('(', $._expression, ')')),
      _binary_expression: $ => choice(
        $.and,
        $.or
      ),
      _unary_expression: $ => prec(2, choice(
        $.not
      )),
      not: $ => seq('~', $._expression),
      and: $ => prec.left(seq($._expression, "/\\", $._expression)),
      or: $ => prec.left(seq($._expression, "\\/", $._expression)),
      identifier: $ => /[a-z_]+/

    }
  });
```

```
╰─➤ tree-sitter generate
Unresolved conflict for symbol sequence:

  '~'  _expression  •  '/\'  …

Possible interpretations:

  1:  '~'  (and  _expression  •  '/\'  _expression)  (precedence: 0, associativity: Left)
  2:  (not  '~'  _expression)  •  '/\'  …

Possible resolutions:

  1:  Specify a higher precedence in `and` than in the other rules.
  2:  Specify a higher precedence in `not` than in the other rules.
  3:  Specify a left or right associativity in `not`
  4:  Add a conflict for these rules: `not`, `and`
```

I believe the `prec(2, choice($.not))` should implement the suggestion number 2 but it apparently does not.  I found that moving the `prec` into the `not` rule does and results in a working grammar.

```javascript
      _unary_expression: $ => choice(
        $.not
      ),
      not: $ => prec(2, seq('~', $._expression)),
```

Is this intended behavior that's not documented?  This is very close to being a copy of the precedence example in the documentation here: https://tree-sitter.github.io/tree-sitter/creating-parsers#using-precedence

Thanks for the great library!

**Comment by maxbrunsfeld** [comment]
Yeah, this is the expected behavior: the precedence needs to be *in* the `not` rule in order to resolve the conflict.

A precedence in `unary_expression` doesn't resolve the conflict, because in the state where the conflict is detected, `unary_expression` is not one of the possible things we're trying to construct (a `not` would need to be constructed first).
