### ISSUE TITLE
`namedDescendantForPosition()` can't find 0 width node

### ISSUE THREAD

**Issue by RedCMD** [tree-sitter/tree-sitter#1871]
Given this example on http://tree-sitter.github.io/tree-sitter/playground
![image](https://user-images.githubusercontent.com/33529441/190597565-eeffe9b9-e343-4aec-8da4-4d34810cee34.png)
at the current cursor position `descendantForPosition()` prioritizes the `}` over the 0width node
which one might say is expected
(pretend the `MISSING identifier` is an actual node)

the problem in my custom language, is that the 0width node is named and `${}` (template_substitution) is not
and I am instead using `namedDescendantForPosition()`
I would have expected tree sitter to return the 0width node as it is the only named node there that starts at or contains the position
but instead it returns named parent node

I think this is a problem of `<` vs `<=`

I am able to find the node through normal means of `.nextSibling` and `.child(0)` etc

> `descendantForPosition()` finds a node that starts or contains the given position

```js
alias(
    token.immediate(
        repeat(
            choice(
                /\\./,
                /[^\\"\r\n]+/,
            ),
        ),
    ),
    $.value
),
```

**Comment by amaanq** [comment]
Is this still a problem @RedCMD? I'd like to fix this but a reproducer would be immensely helpful

**Comment by RedCMD** [comment]
`grammar.js`
```js
module.exports = grammar({
	name: "zerowidth",
	extras: $ => [ ],
	externals: $ => [
		$._forceStringNode, // Forces a 0width empty node if it is before a double quote " . Useful when querying the resulting syntax tree
		$.ERROR,
	],

	rules: {
		root: $ => repeat(
			$._string,
		),
		_string: $ => seq(
			'"',
			alias(
				choice(
					$._forceStringNode,
					/[a-z]+/,
				),
				$.string_content,
			),
			'"',
		),
	}
});
```

`scanner.c`
```c
#include <tree_sitter/parser.h>

enum TokenType
{
	_FORCESTRINGNODE,
	ERROR
};

void* tree_sitter_jsontm_external_scanner_create() { return 0; }
void tree_sitter_jsontm_external_scanner_destroy(void* payload) {}
unsigned tree_sitter_jsontm_external_scanner_serialize(void* payload, char* buffer) { return 0; }
void tree_sitter_jsontm_external_scanner_deserialize(void* payload, const char* buffer, unsigned length) {}

bool tree_sitter_jsontm_external_scanner_scan(void* payload, TSLexer* lexer, const bool* valid_symbols) {
	if (valid_symbols[ERROR]) {
		return false;
	}

	if (valid_symbols[_FORCESTRINGNODE] && (lexer->lookahead == '"')) {
		lexer->result_symbol = _FORCESTRINGNODE;
		return true;
	}

	return false;
}
```

`example.txt`
```
""
```

run code on the resulting tree
```js
rootNode.namedDescendantForPosition({ row: 0, column: 1 });
```

Expected:
Return the 0width named `string_content` node

Actual:
Returns the `root` node

`web-tree-sitter: 0.23.0`

**Comment by amaanq** [comment]
thank you!
