### ISSUE TITLE
A number of integer type mismatches are producing warnings

### ISSUE THREAD

**Issue by mattmassicotte** [tree-sitter/tree-sitter#1880]
On my machine, I see a number of warnings about integer sizings. I've kinda just been living with them, but today I had a little time, and started looking.

`Array.size` and `Array.capacity` are defined as `uint32_t`, but frequently interact with `size_t`, which will not be 32 bits on all platforms.

Because of the underlying allocator implementation, I was tempted to change the `Array` definition to use `size_t`. This is potentially the "most correct" change, but it introduces a lot of knock-on warnings that would have to be addressed. It also change the in-memory layout in a way that I wasn't sure was safe.

Next, the query system performs a number of pointer arithmetic operations with explicit `uint32_t`. That also will cause issues on platforms with non-32 bit pointers. This is what `ptrdiff_t` and `intptr_t` were introduced to address.

I was particularly hesitant to make changes here, because I always mess this stuff up.

So, I decided to just open up a [PR](https://github.com/tree-sitter/tree-sitter/pull/1879) for the most straightforward fix for one of the warnings. I thought we could use this issue to discuss the other issues. The least work is just to add explicit casts. But, these warnings are here for a reason - the existing types allow potentially incorrect truncation.

**Comment by maxbrunsfeld** [comment]
What compiler and flags are you using to see these warnings?

**Comment by mattmassicotte** [comment]
This come up when building with clang, targeting arm64 (and x86_64 too I'm sure). The flags being used are:

```
-Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-implicit-fallthrough
```

The flag that catches these particular errors is `-Wshorten-64-to-32`. Adding this to the Makefile flags will catch it.

These aren't caught by default because the Makefile uses only `-Wall` and `-Wextra`, which for better or worse are only defined to turn on a very specific set of warnings. See: https://releases.llvm.org/9.0.0/tools/clang/docs/DiagnosticsReference.html

**Comment by maxbrunsfeld** [comment]
Great, that's helpful.

Regarding the use of `uint32_t` - Tree-sitter represents byte offsets within strings as 32-bit unsigned integers because concrete syntax trees generally need to store many thousands of these values (to record the position and size of every node), so the memory savings is significant. And it's extremely rare (possibly unheard of?) for a single source code file to be larger than 4GB in size. Similarly, we similarly assume that a single syntax node won't have more than 4 billion children, and use a `uint32_t` for node child counts.

> Next, the query system performs a number of pointer arithmetic operations with explicit uint32_t. That also will cause issues on platforms with non-32 bit pointers. This is what `ptrdiff_t` and `intptr_t` were introduced to address.

I don't think there are actual bugs because of these (assuming queries aren't > 4GB in length, which is a pretty safe assumption), but rather just some implicit casts that we need to make explicit if we want to silence this warning. Obviously, most platforms these days have 64 bit pointers (except for wasm32, which we also do test against on CI), but let me know if you see a bug that I'm  missing. Either way, I'd be open to a PR that addresses these warnings.

**Comment by mattmassicotte** [comment]
Ok, this all matches more or less what I was guessing. A compressed integer representation makes tons of sense!

Given this, I'm going to begin working on some more fixes. I'll keep my bias towards casting and leaving the underlying structures as-is. Now that we've spoken about it, I'm fine closing. Individual issues can be addressed in the forthcoming PRs.

**Comment by jraah555** [comment]
> On my machine, I see a number of warnings about integer sizings. I've kinda just been living with them, but today I had a little time, and started looking.
> 
> `Array.size` and `Array.capacity` are defined as `uint32_t`, but frequently interact with `size_t`, which will not be 32 bits on all platforms.
> 
> Because of the underlying allocator implementation, I was tempted to change the `Array` definition to use `size_t`. This is potentially the "most correct" change, but it introduces a lot of knock-on warnings that would have to be addressed. It also change the in-memory layout in a way that I wasn't sure was safe.
> 
> Next, the query system performs a number of pointer arithmetic operations with explicit `uint32_t`. That also will cause issues on platforms with non-32 bit pointers. This is what `ptrdiff_t` and `intptr_t` were introduced to address.
> 
> I was particularly hesitant to make changes here, because I always mess this stuff up.
> 
> So, I decided to just open up a [PR](https://github.com/tree-sitter/tree-sitter/pull/1879) for the most straightforward fix for one of the warnings. I thought we could use this issue to discuss the other issues. The least work is just to add explicit casts. But, these warnings are here for a reason - the existing types allow potentially incorrect truncation.
