### ISSUE TITLE
Please publish v0.20.7 of node-tree-sitter

### ISSUE THREAD

**Issue by jspears** [tree-sitter/tree-sitter#1882]
New versions are publishing to v14 of the protocol, which won't work with
the currently published version of node-tree-sitter.  An issue is already open on that repo
was hoping this to remind the maintainers here.

[previous request](https://github.com/tree-sitter/tree-sitter/issues/1628)
[reproducible issue](https://github.com/jspears/tree-sitter-swift-version-issue)
[node-tree-sitter](https://github.com/tree-sitter/node-tree-sitter/issues/111)

**Comment by dylanireland** [comment]
Still an active issue. Latest npm release is version 0.20.1; doesn't support language version 14.
