### ISSUE TITLE
panic if using external token to return 'final'

### ISSUE THREAD

**Issue by gdamore** [tree-sitter/tree-sitter#1887]
I am writing a grammar for D, and I have an external lexer that returns 'final' sometimes.

Like this:

```
externals: $ => [ ... 'final', ... ],

rules: {
  _storage_class: $ => choice(
     'auto', ... , 'final', ... ),
}
```

A workaround is to use a symbol instead of a word in the externals, e.g.

```
externals $ => [ ..., $.k_final, ... ],  
``

and then I can use an alias($.k_final, 'final') to refer to it.  
 
```
thread 'main' panicked at 'no entry found for key', cli/src/generate/render.rs:1049:17
stack backtrace:
   0:        0x1002daa48 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9e1f971b6c458057
   1:        0x1002ea100 - core::fmt::write::hff50bf5ab34a8e88
   2:        0x1002bea08 - std::io::Write::write_fmt::h4b4cac536910ac0e
   3:        0x1002c41f0 - std::panicking::default_hook::{{closure}}::h6afa39fd0b64edb8
   4:        0x1002c3ea4 - std::panicking::default_hook::h0ab5dc1706bc4227
   5:        0x1002c4704 - std::panicking::rust_panic_with_hook::h4f2beaf7e17e9f84
   6:        0x1002db2e0 - std::panicking::begin_panic_handler::{{closure}}::h7bfd5963e591c8e8
   7:        0x1002dab5c - std::sys_common::backtrace::__rust_end_short_backtrace::ha8dd13728d5f8e85
   8:        0x1002c4304 - _rust_begin_unwind
   9:        0x10031c5ec - core::panicking::panic_fmt::hd0caa445cceef50a
  10:        0x1002f03ec - core::panicking::panic_display::h5cac88df6a6930ba
  11:        0x1002f03b0 - core::panicking::panic_str::hcb10e60760985b81
  12:        0x10031c694 - core::option::expect_failed::h08153458c235061a
  13:        0x1000d7160 - tree_sitter_cli::generate::render::Generator::generate::h9e4662789f08cc69
  14:        0x1000e5470 - tree_sitter_cli::generate::render::render_c_code::h9b2da9f8e6a34c5d
  15:        0x1001109cc - tree_sitter_cli::generate::generate_parser_for_grammar_with_opts::h70a9a9a1683fce98
```

**Comment by gdamore** [comment]
Note: I see similar behavior for using rules associated with '&', '+', and '-' thus far.

**Comment by gdamore** [comment]
❯ tree-sitter --version
tree-sitter 0.20.7

**Comment by gdamore** [comment]
So it appears having the lexer return keywords is probably not recommended.  I think having it returns literals at all (anything that isn't a symbol) is probably doing to be dodgy at best.  It might just be best to document this as a limitation.

**Comment by amaanq** [comment]
:thinking: I can't seem to reproduce this based on your snippets, it'd be nice if I had a full reproducer, or maybe this has just been fixed since this issue was filed. It'd be great if I could have confirmation, but it's not needed. Parsing tokens with the external scanner _should_ be supported.
