### ISSUE TITLE
Investigate memory usage of parser generator

### ISSUE THREAD

**Issue by fr4wanglei** [tree-sitter/tree-sitter#1890]
When I execute the tree-sitter generate command, no error is reported but it does not take effect, 
how can find syntax errors in grammar.js

**Comment by ahelwer** [comment]
What do you mean it does not take effect? No file is generated at src/parser.c?

**Comment by fr4wanglei** [comment]
Yes. parser.c was not changed

**Comment by keynmol** [comment]
Howdy!

We think we're hitting on the same issue.

The PR where I'm currently fighting this issue is here: https://github.com/tree-sitter/tree-sitter-scala/pull/87

We're trying to generate the parser from scratch on CI.

To confirm the problem we're seeing, I basically just did this:

```
          shasum src/parser.c
          rm src/parser.c
          npm install tree-sitter-cli
          npm run build
          shasum src/parser.c
```

And indeed the file is not regenerated at all, and there are no errors reported by NPM:

![image](https://user-images.githubusercontent.com/1052965/211162917-05ce8811-3592-496b-b6ee-36973d520844.png)

We're only seeing this behaviour on Linux - currently parser regeneration seems to work on MacOS, where our CI currently runs - but it takes 13 minutes to generate the grammar, as opposed to Linux's 2, so we would like to figure out what's going on.

**Comment by ahlinc** [comment]
![Screenshot from 2023-01-07 20-59-45](https://user-images.githubusercontent.com/14666676/211166428-cdb65358-dbd8-453e-8fbf-03ba7b281a27.png)
@keynmol `tree-sitter generate` on my Linux machine takes more than 34Gb of memory. Could you check `dmesg` that tree-sitter wasn't killed by OOM?

The parser was correctly generated on my machine:
![Screenshot from 2023-01-07 21-06-22](https://user-images.githubusercontent.com/14666676/211166626-be96c02a-effe-4db7-ae2b-a3a34db0336f.png)

**Comment by keynmol** [comment]
Ohhhh that would be a decent explanation as to what is happening and why we killed several GHA runners!

I've just run the rust CLI directly and I can see both the memory usage and when it gets killed on my machine.

Thank you!

--- 

Before I depart in shame, are there any techniques I can read about for investigating what makes the parser take so much memory to generate and how to reduce it?

**Comment by ahlinc** [comment]
At this time there are two options `--log` and [`--report-states-for-rule`](https://github.com/tree-sitter/tree-sitter/discussions/1387#discussioncomment-1329775) [:link:1](https://github.com/tree-sitter/tree-sitter/discussions/994#discussioncomment-486310) [:link:2](https://github.com/tree-sitter/tree-sitter/pull/334#issuecomment-499719715) that may give some light on that.
But for me they don't give good explanation why so much memory consumed during generation phase.

**Comment by eed3si9n** [comment]
@ahlinc Thanks for this info! I am not quite sure what I was doing but running 

```
$  node_modules/.bin/tree-sitter generate --report-states-for-rule compilation_unit
class_definition                3728
function_definition             2214
ascription_expression           1442
infix_expression                1412
assignment_expression           1412
....
```

gave the above, and by poking around the `class_definition` I was able to bring down the memory usage down to 11GB in https://github.com/tree-sitter/tree-sitter-scala/pull/102. This is now under macos-latest's physical RAM 14GB, so codegen that used to take 23 minutes on Github Actions now finishes in 3 minutes, and on local Linux box `time npm run build` finishes in 40s.

**Comment by eed3si9n** [comment]
I kept applying the same trick to other constructs with high state count, and now the memory usage is down to 1GB after https://github.com/tree-sitter/tree-sitter-scala/pull/106.

I am not sure if this can be generalized to other grammars, but for Scala at least:
1. Avoid `prec.right`, and when it's necessary minimize it to a smaller token.
2. If there's a common pattern, such as (name, type_parameter, parameters), immediately after a keyword, factor those out to a token.

**Comment by ahlinc** [comment]
@eed3si9n It's awesome that you've able to achieve such great improvements! Thank you for sharing your experience!

**Comment by dundargoc** [comment]
I deleted that label completely since it wasn't used except for in this issue I think. I'm not saying it's not OOM, just that the label doesn't seem very useful.
