### ISSUE TITLE
WASM build on Windows using incorrect path separators for POSIX target container

### ISSUE THREAD

**Issue by aheber** [tree-sitter/tree-sitter#1892]
https://github.com/tree-sitter/tree-sitter/blob/d62adbe3a9c760a17cbd93bd04e64ad3886a7fe8/cli/src/wasm.rs#L20

When I run `tree-sitter build-wasm --docker` the generated command is:
`"[path...]\docker.exe" run --rm --workdir /src\apex --volume C:\Users\[userhome]\dev\tree-sitter-sfapex:/src:Z emscripten/emsdk:2.0.24 emcc -o tree-sitter-apex.wasm -Os -s WASM=1 -s SIDE_MODULE=1 -s TOTAL_MEMORY=33554432 -s NODEJS_CATCH_EXIT=0 -s EXPORTED_FUNCTIONS=[\"_tree_sitter_apex\"] -fno-exceptions -I src src\parser.c`

You'll notice `/src\apex` and `src\parser.c` are using the Windows path separator but these paths end up being consumed by the Docker container so should be using POSIX separator `/` in both cases.

Successful command is:
`"[path...]\docker.exe" run --rm --workdir /src/apex --volume C:\Users\[userhome]\dev\tree-sitter-sfapex:/src:Z emscripten/emsdk:2.0.24 emcc -o tree-sitter-apex.wasm -Os -s WASM=1 -s SIDE_MODULE=1 -s TOTAL_MEMORY=33554432 -s NODEJS_CATCH_EXIT=0 -s EXPORTED_FUNCTIONS=[\"_tree_sitter_apex\"] -fno-exceptions -I src src/parser.c`

I'm not much of a Rust dev or I would submit a PR for it.

**Comment by joelspadin** [comment]
I believe this was fixed in #2183. (The fix still hasn't been included in a release though.)
