### ISSUE TITLE
wasm parser side modules can depend on non-exported library functions

### ISSUE THREAD

**Issue by dstoc** [tree-sitter/tree-sitter#1906]
I'm trying to use wasm bindings for https://github.com/MDeiml/tree-sitter-markdown. This is generally working fine, but I encountered errors when parsing markdown containing HTML tags.

I traced this down to the custom scanner (https://github.com/MDeiml/tree-sitter-markdown/blob/e375ba95ff9a12418f9b9e7c190f549d08b5380a/tree-sitter-markdown/src/scanner.cc#L1137) using `isalpha` and other library functions that are not exported from the main tree-sitter module in https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/exports.json

What's the right solution here, should more exports be added?

**Comment by ahelwer** [comment]
The solution for my scanner was to remove those functions in favor of others or writing my own. In this case I think `iswalpha` in `wtype.h` is included.

**Comment by dstoc** [comment]
Thanks. The full list seems to be `isalpha`, `tolower`, `strcmp`, `isalnum` (from "Import" section in `wasm-objdump -x tree-sitter-markdown.wasm`). Of those `tolower` and `strcmp` don't have an alternative in the current exports.

FYI @mdeiml

**Comment by maxbrunsfeld** [comment]
Yeah, this is a problem that I don't have a great solution to. I guess we should add `towlower` and `strcmp` to the set of exports.

**Comment by MDeiml** [comment]
Is there a simple solution to add exports as the author of the grammar / binding? I guess that would be the preferable solution.

**Comment by MDeiml** [comment]
> Is there a simple solution to add exports as the author of the grammar / binding? I guess that would be the preferable solution.

Answering my own question: This doesn't seem to be possible that simply. Parsers are compiled as node native addons (no possibility to export e.g. `isalpha`) while tree-sitter is compiled to wasm.

**Comment by savetheclocktower** [comment]
I'd love to figure out a solution to this. Pulsar is all-in on web-tree-sitter, but I'm routinely encountering parsers that fail when I run `tree-sitter playground`, but work fine on all other bindings.

The first-party parsers are less likely to be affected by this — except that I've filed issues in [tree-sitter-html](https://github.com/tree-sitter/tree-sitter-html/issues/55) and [tree-sitter-ruby](https://github.com/tree-sitter/tree-sitter-ruby/issues/236) that ultimately seem to stem from those parsers using C/C++ library functions that aren't exported by web-tree-sitter.

As a workaround, Pulsar can build its own version of web-tree-sitter and edit `exports.json` to include references to all functions known to be needed by our built-in language packages' parsers, but that's only a slight improvement. The vast majority of parsers (just look at [neovim's list](https://github.com/nvim-treesitter/nvim-treesitter#supported-languages)) are too obscure to be bundled. So a developer who wanted to maintain their own `language-foo` package might have Pulsar as a blocker: file an issue, wait for us to add some function to our `exports.json`, and so on, as our custom build grows over time to export the superset of all C functions that could be called by at least one external scanner in the tree-sitter ecosystem.

The approach suggested by @ahlinc in #949 seems good, but I don't know if there's an architectural blocker here, or if it's just a matter of someone doing the work.  I've got nowhere near enough experience with systems programming to tackle this, but I can contribute in whatever other way would be helpful.

**Comment by ahlinc** [comment]
> but I don't know if there's an architectural blocker here

Yeah the `tree-sitter-loader` crate needs to be improved and compiling logic consolidated into a separate module that would be reused for compiling native and _wasm_ libraries from different CLI commands + available to be used programatically.

**Comment by TylerLeonhardt** [comment]
@sogaiu mentioned this issue in my issue: https://github.com/tree-sitter/tree-sitter/issues/2338... do you all think mine is a duplicate?

We use `web-tree-sitter` for [localization of VS Code extensions](https://github.com/microsoft/vscode-l10n/tree/main/l10n-dev) and what we've noticed is that upgrading to Node.js 19 causes similar issues to this issue to happen. I don't know much about the inner workings of tree-sitter, but if there's anything I can do to help, let me know!

VS Code will move to newer versions of Electron, which mean recommending a newer versions of Node when deving for extensions, so the issue I described is on the horizon and I'd like to prevent it from being a problem when we bump Electron.

**Comment by sogaiu** [comment]
I tried building `.wasm` files for both typescript and tsx using `tree-sitter build-wasm`.  They both seemed to compile with no issues and both seemed to work via web browser tabs that open as a result of running `tree-sitter playground`.

FWIW, I used emsdk 3.1.37 to do the `.wasm` file building, but the version here can very much matter depending on the version of the tree-sitter cli one is using.

I didn't succeed in determining what version of emsdk vscode-l10n uses when trying to run `tree-sitter build-wasm` in [these lines](https://github.com/microsoft/vscode-l10n/blob/9cd98097e05913ecd7ae695b774b2bef0a4832cc/l10n-dev/package.json#L52-L53).

**Comment by TylerLeonhardt** [comment]
@sogaiu did you try loading these in node.js by chance? That's the environment I see the issues in.

**Comment by sogaiu** [comment]
No I didn't.

Looking through [this](https://github.com/tree-sitter/tree-sitter-typescript/issues/244) it's not obvious to me how one might go about reproducing the issue.

May be there are some steps somewhere I missed (^^;  Along those lines, having a minimal reproduction case might help with investigation.

**Comment by sogaiu** [comment]
Ok, I think I was able to reproduce.

I also rebuilt `web-tree-sitter` bits using `script/build-wasm --debug` and used the results instead of `web-tree-sitter` fetched via `npm` in order to get better output.

The result was this:

```
$ node sample.js 
Aborted(Assertion failed: undefined symbol `tree_sitter_typescript_external_scanner_create`. perhaps a side module was not linked in? if this global was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment)
/tmp/binding_web/tree-sitter.js:480
     var e = new WebAssembly.RuntimeError(what);
             ^

RuntimeError: Aborted(Assertion failed: undefined symbol `tree_sitter_typescript_external_scanner_create`. perhaps a side module was not linked in? if this global was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment)
    at abort (/tmp/binding_web/tree-sitter.js:480:14)
    at assert (/tmp/binding_web/tree-sitter.js:286:7)
    at reportUndefinedSymbols (/tmp/binding_web/tree-sitter.js:1483:8)
    at postInstantiation (/tmp/binding_web/tree-sitter.js:1302:9)
    at /tmp/binding_web/tree-sitter.js:1350:68
    at async tsx_do (/tmp/tree-sitter-issue-2338/sample.js:14:22)

Node.js v19.9.0
```

`sample.js` had the content:

```javascript
const Parser = require("web-tree-sitter");
const path = require("path");

////////////////////////////////////////////////////////////////////////

const tsx_wasm_path = 
      path.join(process.cwd(),
                "node_modules/tree-sitter-typescript/tsx",
                "tree-sitter-tsx.wasm");

async function tsx_do() {
    const p = await Parser.init();

    const tsx_lang = await Parser.Language.load(tsx_wasm_path);

    const tsx_p = new Parser();

    tsx_p.setLanguage(tsx_lang);

    const tsx_text = "<Element<T>>hi</Element>;\n" +
                     "<Element<T> />;\n" +
                     "<>fragment</>;";

    const tsx_tree = tsx_p.parse(tsx_text);

    console.log(tsx_tree.rootNode);
}

tsx_do();

////////////////////////////////////////////////////////////////////////

const ts_wasm_path = 
      path.join(process.cwd(),
                "node_modules/tree-sitter-typescript/typescript",
                "tree-sitter-typescript.wasm");

async function ts_do() {
    const p = await Parser.init();

    const ts_lang = await Parser.Language.load(ts_wasm_path);

    const ts_p = new Parser();

    ts_p.setLanguage(ts_lang);

    const ts_text = "<A>b;\n" +
                    "<C<D>>e.f;";

    const ts_tree = ts_p.parse(ts_text);

    console.log(ts_tree.rootNode);
}

ts_do();
```

Note that commenting out one of `ts_do();` or `tsx_do();` leads to no error.  It seems that it's only a problem when both are done.  Further, node 18.14.1 did not exhibit the issue.

FWIW, the `package.json` I used was:

```javascript
{
    "name": "tree-sitter-issue-2338",
    "version": "0.0.1",
    "dependencies": {
        "web-tree-sitter": "0.20.8",
        "tree-sitter-cli": "0.20.8",
        "tree-sitter-typescript": "git+https://github.com/tree-sitter/tree-sitter-typescript.git#b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf"
    },
    "scripts": {
        "build-wasm": "npm run build-typescript-wasm && npm run build-tsx-wasm",
        "build-typescript-wasm": "cd node_modules/tree-sitter-typescript/typescript && npx tree-sitter build-wasm",
        "build-tsx-wasm": "cd node_modules/tree-sitter-typescript/tsx && npx tree-sitter build-wasm"
  }
}
```

Note that something like `source emsdk_env.sh` (in the emsdk source directory) is necessary before running `npm run build-wasm` to build the `.wasm` files unless one's environment is already setup with emsdk appropriately.

Also, for some reason `npm install` seems to take a rather long time when using nodejs 19.x or 20.y, so I recommed using `npm --verbose install` to see some amount of progress.

Environment details for reproducing the issue:

```
web-tree-sitter: 0.20.8
tree-sitter-cli: 0.20.8
tree-sitter-typescript: tree-sitter-typescript commit b1bf4825
node: v19.9.0, v20.5.0
Emscripten SDK: 3.1.37
OS: Ubuntu 22.04.2
```

**Comment by sogaiu** [comment]
I've put together [a repository](https://github.com/sogaiu/tree-sitter-issue-2338) to help with reproducing.

Prerequisites are:

* git
* nodejs 19 (or 20) with appropriate npm
* typical dev Linux machine

There's a script in the repository named `doit.sh`.  Executing this reproduces the issue here.  Perhaps it will work for others too.

Note that `emsdk` is included in the repository and the script should take care of getting that part setup (to build the `.wasm` files) -- so arranging for `emsdk` separately should not be needed.

**Comment by TylerLeonhardt** [comment]
Thank you so much for putting that together @sogaiu! I experienced the same. Node.js 19 and higher had the issue.

**Comment by sogaiu** [comment]
Thanks for confirming that it works.

I did a little bit more investigation, but I'll report on that over at #2338.

**Comment by sogaiu** [comment]
To answer:

> do you all think mine is a duplicate?

I don't think it is.

I'm not sure if #2338 is a tree-sitter, emsdk, Nodejs, or V8 issue (or some combination), but as hinted at before, likely it makes sense to continue discussion elsewhere (at #2338 seems sensible).

**Comment by amaanq** [comment]
With the addition of the `array` and `allocation` header by default in the `src/tree_sitter` directory for users to leverage, as well as deprecating and nearly getting rid of C++ scanners, I think this can be closed out. The comprehensive list of C stdlib symbols that are *available* to users can be found [here](https://github.com/nvim-treesitter/nvim-treesitter/issues/2282). We can always add more, but the desired function needs to have a compelling reason to be added.

**Comment by sogaiu** [comment]
> The comprehensive list of C stdlib symbols that are available to users can be found [here](https://github.com/nvim-treesitter/nvim-treesitter/issues/2282).

@amaanq Did you by intend to post a different url?  I'm not succeeding in finding a list of C stdlib symbols via the url above.  May be I'm missing something?
