### ISSUE TITLE
`ts_query_cursor_next_capture` out of bounds array access

### ISSUE THREAD

**Issue by t-dean** [tree-sitter/tree-sitter#1907]
`ts_query_cursor_next_capture` in `lib/src/query.c` can read out of the bounds of the `TSQueryCursor::states` array.

[query.c:3872](https://github.com/tree-sitter/tree-sitter/blob/8751fa08530a0b2922dbba7bf2b5a8004b3a7fe4/lib/src/query.c#L3872) indexes into `states` by `first_unfinished_state_index` which may still be its original value (`UINT32_MAX`) from initialization in [`ts_query_cursor__first_in_progress_capture`](https://github.com/tree-sitter/tree-sitter/blob/8751fa08530a0b2922dbba7bf2b5a8004b3a7fe4/lib/src/query.c#L2925).

I'm not familiar enough with the tree-sitter internals to suggest what `ts_query_cursor_next_capture` should do in this scenario. However, I have found the following patch to prevent the out of bounds read:

```patch
diff --git a/lib/src/query.c b/lib/src/query.c
index 710a9209..a8d6b573 100644
--- a/lib/src/query.c
+++ b/lib/src/query.c
@@ -3860,7 +3860,10 @@ bool ts_query_cursor_next_capture(
       return true;
     }

-    if (capture_list_pool_is_empty(&self->capture_list_pool)) {
+    if (
+      capture_list_pool_is_empty(&self->capture_list_pool) &&
+      first_unfinished_capture_byte != UINT32_MAX
+    ) {
       LOG(
         "  abandon state. index:%u, pattern:%u, offset:%u.\n",
         first_unfinished_state_index,
```

**Comment by amaanq** [comment]
Fixed in https://github.com/tree-sitter/tree-sitter/pull/3727, thanks
