### ISSUE TITLE
ts_query_new seems to spin forever with this input

### ISSUE THREAD

**Issue by mattmassicotte** [tree-sitter/tree-sitter#1916]
I've been experimenting with the swift parser (https://github.com/alex-pinkus/tree-sitter-swift), and I ran into issues with a query. I cannot quite tell if the runtime is in an infinite loop, but I let it run for a long time and it never completed a call to `ts_query_new` with the following input:

```
(function_declaration
  "func" @structure.anchor
  body: (function_body
    "{" @structure.open
    "}" @structure.close))
```

It has something to do with the `body` field. I'm using 0.20.07 and the latest build of this parser, so this means ABI 14. I know there were some changes here, but I don't yet know if ABI 13 makes a difference.

**Comment by WillLillis** [comment]
Can no long repo on latest `tree-sitter` and `tree-sitter-swift` versions. Tested via the Rust bindings:

![image](https://github.com/user-attachments/assets/56556b1e-2270-495b-a226-d2dff05baf48)

**Comment by amaanq** [comment]
Still does take a while for me with the CLI (around 15-17 seconds), but it does not just hang, that's for sure. It's likely an issue in the grammar itself that needs to be worked out, so I'll close this.

**Comment by mattmassicotte** [comment]
Thanks for looking at this one! I'm excited to try out a new version with the fix!
