### ISSUE TITLE
Comments in tree-sitter.

### ISSUE THREAD

**Issue by iwatakeshi** [tree-sitter/tree-sitter#192]
Hi. I was playing around with tree-sitter and noticed that comments from a JavaScript code do not have location properties as shown below.

JavaScript file:
```js
/**
 * comment
 */

function a() {

}
```

TypeScript program:
```ts
import * as Parser from 'tree-sitter';
import * as JavaScript from 'tree-sitter-javascript';
import * as FS from 'fs';

const parser = new Parser();
parser.setLanguage(JavaScript);


const tree = parser.parse(FS.readFileSync(`${process.cwd()}/example.js`, 'utf-8'));
console.log(tree.rootNode.children[0])
```

Output: 
```
SyntaxNode {
  type: comment,
  startPosition: {row: 0, column: 0},
  endPosition: {row: 0, column: 0},
  childCount: 0,
}
```

Would it be possible to keep those properties or is there an option to add those properties?

**Comment by maxbrunsfeld** [comment]
What properties are missing? Every node should have a `startPosition`, `endPosition`, `startIndex` and `endIndex`, regardless of whether it's a comment or some other type of node.

By the way, the output made me realize that there was a typo in the syntax node's `inspect` method; it was printing out the `startPosition` value twice instead of printing out the actual `endPosition`. That is fixed in the latest version, v0.13.4.

**Comment by iwatakeshi** [comment]
I’m sorry. I meant that I was expecting a position’s row and column value to be greater than 0. I’m considering to use this library to parse leading comments, but I need to know the location of the comment and the context. By the way, awesome project!

**Comment by maxbrunsfeld** [comment]
Thanks! Yeah the locations are zero-indexed, so row 0 is the first line in the file.

**Comment by iwatakeshi** [comment]
After adding another comment block, I realized that you're right. 😆 But, I would also have thought that the end row would be 8? Or maybe, I'm just not thinking right 😆 . Here's what I got after adding another comment block and function:

Example file:
```js
/**
 * Description
 * 
 * # API
 * 
 * ```
 * @function a
 * ```
 */

function a() {

}

/**
 * Description
 * 
 * # API
 * 
 * ```
 * @function b
 * ```
 */

 function b() {

 }
```

Typescript program snippet:
```
// ...
console.log(tree.rootNode.children[2])
```

Output:
```
SyntaxNode {
  type: comment,
  startPosition: {row: 14, column: 0},
  endPosition: {row: 14, column: 0},
  childCount: 0,
}
```

Checking with Visual Studio Code, the start position is definitely correct. However, the end row should be 23?

<img width="176" alt="screen shot 2018-08-02 at 11 24 01 pm" src="https://user-images.githubusercontent.com/1505448/43625673-7f6ba4a8-96ab-11e8-8b16-327dd9f36d28.png">

**Comment by iwatakeshi** [comment]
You know what, I just installed the latest version and it seems like the problem is fixed 😆 .

**Comment by iwatakeshi** [comment]
It's strange that npm isn't pointing to `0.13.4`. All I did was `npm install --save tree-sitter`...

**Comment by maxbrunsfeld** [comment]
> It's strange that npm isn't pointing to 0.13.4

Yeah, I literally [just fixed the typo](https://github.com/tree-sitter/node-tree-sitter/commit/e8eb8ff440e1fd0b10131ee1f82c4b7f143314ee) in the pretty-printing code after your initial comment, so `0.13.3` was probably the latest at the time that you installed.

**Comment by iwatakeshi** [comment]
Ah. Well, that solves the problem then. Thank you!
