### ISSUE TITLE
Lifetimes are too restrictive in `QueryCursor::matches`

### ISSUE THREAD

**Issue by oberblastmeister** [tree-sitter/tree-sitter#1922]
In https://docs.rs/tree-sitter/latest/tree_sitter/struct.QueryCursor.html#method.matches the `text_provider` gets bound as
```rust
T: TextProvider<'a> + 'a
```
However, the method also takes 
```rust
&'a mut self
```
So the cursor is required to have the same lifetime as the `TextProvider`, but it may not be able to. I made this change https://github.com/oberblastmeister/tree-sitter/blob/lifetime/lib/binding_rust/lib.rs#L175, but I wanted to ask first.

**Comment by amaanq** [comment]
Is this still an issue on master? TextProvider got reworked

**Comment by ahlinc** [comment]
I think this can be closed because `TextProvider` doesn't depend from lifetimes directly anymore.
Related:
* #2431 
* #2464
