### ISSUE TITLE
Is it possible to restrict the result set of queries?

### ISSUE THREAD

**Issue by mainrs** [tree-sitter/tree-sitter#1932]
I use queries to define insertion points into existing source code files. Lets say I have a Rust source file and query for the imported modules in it.

```rust
use std::path::PathBuf;

mod a;
mod b;
mod c;

// ....
```
And my query queries for all the `mod` items: `(mod_item name: (_)) @point.insertion`. I somehow want to be able to tell the query to return the first, last, or n-ith item of module imports. Can this be done using queries?

**Comment by amaanq** [comment]
Sure you can accomplish this, but not directly via some query syntax. You would just have to collect all your queries using captures or matches based on what your needs are, and then simply iterate over your results. Implementing this at the query level sounds like it'd be a lot more work than it's worth imo, so I'll close this out. Hopefully post-processing the results is okay for your use case
