### ISSUE TITLE
Allow query to capture partial tokens

### ISSUE THREAD

**Issue by andremarianiello** [tree-sitter/tree-sitter#1944]
I am working on adding support for injection parsing using nvim-treesitter. Specifically, I want to support highlighting raw Go string literals as another language. However, I am stuck on the fact that raw_string_literal in Go is a single token, which includes the surrounding backticks. This means that if I capture that token, those backticks are included as part of the input to the injected grammar. But this is not what I want. I only want to syntax highlight the contents of the raw string, not the whole thing.

This is the query that I am currently using
```
(raw_string_literal) @mylang
```
This tells nvim-treesitter to highlight the entire token as if it was mylang. I want to be able to capture just the contents. If it was not a single token I could do
```
(raw_string_literal "`" _ @mylang "`")
```
but this is not how the Go grammar is written. I could alter the Go grammar or my injected grammar to work with this, but I feel like it is a mistake to couple them together in any way. Ideally, the query syntax could support capturing just the contents of the raw string literal. Perhaps it could look something like
```
(raw_string_literal
  (#match! @mylang "/[^`]*/"))
```
or whatever makes sense. If I could write a query that does this I could keep the two grammar completely separate.

**Comment by andremarianiello** [comment]
I see that's nvim-treesitter has some custom predicates. If that is a better way to handle this situation, feel free to close this.

**Comment by andremarianiello** [comment]
For anyone with a similar issue, neovim has a builtin directive `offset!` which adjusts the bounds of the matched range.

**Comment by meldafert** [comment]
Thanks! This works for me for neovim.
However, I do think that it would be useful to support this in tree-sitter itself.
