### ISSUE TITLE
Using "extras" rule in another rule should cause conflict, but instead always chooses to reduce

### ISSUE THREAD

**Issue by andremarianiello** [tree-sitter/tree-sitter#1950]
I wrote a small dummy grammar to illustrate the issue.

```
module.exports = grammar({
  name: 'test',

  extras: $ => [$._space, $.newline],
  rules: {
    source: $ => choice(
      $.compound_expr,
      $.declaration,
    ),
    declaration: $ => seq(
      field('name', $.identifier),
      '=',
      field('value', $.compound_expr),
      $.newline,
    ),
    compound_expr: $ => seq(
      $.identifier,
      repeat(seq(
        //optional($.newline),
        $.identifier,
      )),
    ),
    identifier: _ => /[a-z]+/,
    _space: _ => / /,
    newline: _ => /\n/,
  }
});
```

And I use it to parse the following text
```
b c d e f
```
producing
```
(source [0, 0] - [1, 0]
  (compound_expr [0, 0] - [0, 9]
    (identifier [0, 0] - [0, 1])
    (identifier [0, 2] - [0, 3])
    (identifier [0, 4] - [0, 5])
    (identifier [0, 6] - [0, 7])
    (identifier [0, 8] - [0, 9]))
  (newline [0, 9] - [1, 0]))
```
as expected.

Since I have newlines included in extras, I can insert a newline without breaking the parse tree.
```
b c
  d e f
```
produces
```
(source [0, 0] - [2, 0]
  (compound_expr [0, 0] - [1, 7]
    (identifier [0, 0] - [0, 1])
    (identifier [0, 2] - [0, 3])
    (newline [0, 3] - [1, 0])
    (identifier [1, 2] - [1, 3])
    (identifier [1, 4] - [1, 5])
    (identifier [1, 6] - [1, 7]))
  (newline [1, 7] - [2, 0]))
```
as expected.

However, this guarantee breaks down when parsing declarations due to the required newline at the end of the declaration.

Example (parses successfully):
```
a = b c d e f
```
as
```
(source [0, 0] - [1, 0]
  (declaration [0, 0] - [1, 0]
    name: (identifier [0, 0] - [0, 1])
    value: (compound_expr [0, 4] - [0, 13]
      (identifier [0, 4] - [0, 5])
      (identifier [0, 6] - [0, 7])
      (identifier [0, 8] - [0, 9])
      (identifier [0, 10] - [0, 11])
      (identifier [0, 12] - [0, 13]))
    (newline [0, 13] - [1, 0])))
```

but
```
a = b c
    d e f
```
fails to parse successfully, producing
```
(source [0, 0] - [2, 0]
  (declaration [0, 0] - [2, 0]
    name: (identifier [0, 0] - [0, 1])
    (ERROR [0, 4] - [1, 0]
      (compound_expr [0, 4] - [0, 7]
        (identifier [0, 4] - [0, 5])
        (identifier [0, 6] - [0, 7]))
      (newline [0, 7] - [1, 0]))
    value: (compound_expr [1, 4] - [1, 9]
      (identifier [1, 4] - [1, 5])
      (identifier [1, 6] - [1, 7])
      (identifier [1, 8] - [1, 9]))
    (newline [1, 9] - [2, 0])))
test.test       0 ms    (ERROR [0, 4] - [1, 0])
```
even though I simply inserted an extra into the same place in a compound_expr. This behavior is caused by the `$.newline` rule usage in compound_expr. The parser generator seems to assume that at that point in a parse the a newline token must trigger a reduction, with no consideration that it may be an extra token that can be skipped. Is this the intended behavior?

To further illustrate what is happening, I can explicitly add optional newlines into compound_expr where they were already implicitly allowed, by uncommenting a line from the original grammar

```
module.exports = grammar({
  name: 'test',

  extras: $ => [$._space, $.newline],
  rules: {
    source: $ => choice(
      $.compound_expr,
      $.declaration,
    ),
    declaration: $ => seq(
      field('name', $.identifier),
      '=',
      field('value', $.compound_expr),
      $.newline,
    ),
    compound_expr: $ => seq(
      $.identifier,
      repeat(seq(
        optional($.newline), // NEW - this shouldn't change the grammar, right?
        $.identifier,
      )),
    ),
    identifier: _ => /[a-z]+/,
    _space: _ => / /,
    newline: _ => /\n/,
  }
});
```
And now parser generation correctly detects a conflict, as you would have expected earlier
```
Unresolved conflict for symbol sequence:

  identifier  '='  identifier  _  newline  _

Possible interpretations:

  1:  identifier  '='  (compound_expr  identifier  _  compound_expr_repeat1)
  2:  identifier  '='  (compound_expr  identifier)  _  newline  _

Possible resolutions:

  1:  Specify a left or right associativity in `compound_expr`
  2:  Add a conflict for these rules: `compound_expr`
```

**Comment by alemuller** [comment]
I believe that's the expected behavior.

The "Context-aware Lexing" (see [creating-parsers#conflicting-tokens](https://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens)) has highest priority. 

As far as I understand, `extras` are only tried if everything else fails.

Maybe `extras` could be included in the table on the article above?

**Comment by andremarianiello** [comment]
Can I control the precedence of extras rules/tokens with `prec`? Or are they always considered last?

**Comment by alemuller** [comment]
Yes, you can.

Grammar:
```js grammar.js
const NLF = /\r?\n/;

module.exports = grammar({
  name: 'test',

  extras: $ => [
    NLF,
    $.tk_prec2
  ],

  rules: {
    top: $ => repeat($.tk_prec1),

    tk_prec1: $ => token(prec(1, 'x')),
    tk_prec2: $ => token(prec(2, 'x')),
  }

});
```

I included `NLF` in `extras` because most editors adds a newline at end of file by default (vim does). See PITFALL bellow.

Test:
```txt test.test
xxx
```

stdout:
```txt stdout
(top [0, 0] - [1, 0]
  (tk_prec2 [0, 0] - [0, 1])
  (tk_prec2 [0, 1] - [0, 2])
  (tk_prec2 [0, 2] - [0, 3]))
```
---

:warning: **Note**: To change the _precedence of the token_, `prec` shall be inside `token` (like in the grammar above), when outside it means the rule precedence. 

:warning: **PITFALL**: Languages that use a `NLF` as delimiter usually expects a `NLF` before the `EOF`.
However, test cases in the test files (example bellow) replaces the new line before the separator with `EOF`.

`./test/foo.test`:
```scm ./test/foo.test
xxx
---
(top
  (tk_prec2))
```
If your language expects `NLF` before `EOF`, you need to insert a blank line before the separator:

```scm ./test/foo.test
xxx

---
(top
  (tk_prec2))
```

There maybe a flag for that nowadays, I haven't looked into that in a while.

**Comment by amaanq** [comment]
I believe @alemuller's fantastic reply answers the issue, tl;dr unless you explicitly handle this situation in a scanner or via giving the literal a higher lexical precedence when used in the extras you will have other usages of the same literal (string/regex) preferred over the extra if possible.
