### ISSUE TITLE
Support timeout for query.

### ISSUE THREAD

**Issue by 5c4lar** [tree-sitter/tree-sitter#1957]
Some large files may be parsed fine but it will takes too long to query. It may be hard to optimize the query logic to accelerate the query? But a timeout option can allow us to simply ignore those strange files.

The problematic file can be find here https://github.com/google/google-ctf/blob/master/third_party/edk2/MdeModulePkg/Library/BrotliCustomDecompressLib/common/dictionary.c

**Comment by AndersHogqvist** [comment]
I second this! Just ran into this problem while working on a tree-sitter based language server for Structured Text. It worked perfectly fine until tried to parse a particular file with a super long assignment statement that takes several minutes to process.

**Comment by alemuller** [comment]
I does make sense to add timeout.

But it shouldn't take that long to transverse the tree. It looks like there is something wrong elsewhere. I'll do some debugging.

--------------------------------------------------------------------------------

Instruction on how to reproduce the issue with tree-sitter cli:

<pre><samp>$ <kbd>echo "(number_literal) @number" | time tree-sitter <strong>query</strong> /dev/stdin <a href="https://github.com/google/google-ctf/blob/7a1621eac5c647f0e205df2d7228e95455659d64/third_party/edk2/MdeModulePkg/Library/BrotliCustomDecompressLib/common/dictionary.c">dictionary.c</a></kbd></pre></samp>

I killed the process after waiting 4 minutes.

With highlight, we can actually *see* the performance:
<pre><samp>$ <kbd>tree-sitter <strong>highlight</strong> <a href="https://github.com/google/google-ctf/blob/7a1621eac5c647f0e205df2d7228e95455659d64/third_party/edk2/MdeModulePkg/Library/BrotliCustomDecompressLib/common/dictionary.c">dictionary.c</a></kbd>.</pre></samp>

--------------------------------------------------------------------------------

Related improvements oportunities on tree-sitter cli:
* Add `--timeout` option to subcommand `query`;
* Add `--timeout` option to subcommand `highlight`;
* Add `--time` flag to subcommand `query`;

Current flags and options:
<details>
<summary><kbd>tree-sitter <strong>parse</strong> --help | sed -ne '/^FLAGS/, /^$/p' -e '/^OPTIONS/, /^$/{/^$/!p}'</kbd></summary>
<pre><samp>FLAGS:
    -d, --debug          Show parsing debug log
    -0, --debug-build    Compile a parser in debug mode
    -D, --debug-graph    Produce the log.html file with debug graphs
    -x, --xml            
    -s, --stat           Show parsing statistic
    -t, --time           Measure execution time
    -q, --quiet          Suppress main output
    -h, --help           Prints help information
    -V, --version        Prints version information
<br />
OPTIONS:
        --paths &lt;paths-file&gt;    The path to a file with paths to source file(s)
        --scope &lt;scope&gt;         Select a language by the scope instead of a file extension
        --timeout &lt;timeout&gt;     Interrupt the parsing process by timeout (µs)
    -e, --edit &lt;edits&gt;...       Apply edits in the format: "row,col del_count insert_text"
</samp></pre>
</details>

<details>
<summary><kbd>tree-sitter <strong>query</strong> --help | sed -ne '/^FLAGS/, /^$/p' -e '/^OPTIONS/, /^$/{/^$/!p}'</kbd></summary>
<pre><samp>FLAGS:
    -c, --captures    
        --test        
    -h, --help        Prints help information
    -V, --version     Prints version information
<br />
OPTIONS:
        --paths &lt;paths-file&gt;         The path to a file with paths to source file(s)
        --byte-range &lt;byte-range&gt;    The range of byte offsets in which the query will be executed
        --scope &lt;scope&gt;              Select a language by the scope instead of a file extension
</samp></pre>
</details>

<details>
<summary><kbd>tree-sitter <strong>highlight</strong> --help | sed -ne '/^FLAGS/, /^$/p' -e '/^OPTIONS/, /^$/{/^$/!p}'</kbd></summary>
<pre><samp>FLAGS:
    -H, --html       Generate highlighting as an HTML document
    -t, --time       Measure execution time
    -q, --quiet      Suppress main output
    -h, --help       Prints help information
    -V, --version    Prints version information
<br />
OPTIONS:
        --scope &lt;scope&gt;         Select a language by the scope instead of a file extension
        --paths &lt;paths-file&gt;    The path to a file with paths to source file(s)
</samp></pre>
</details>

--------------------------------------------------------------------------------

Enviroment
<pre><samp>$ <kbd>tree-sitter --version</kbd>
tree-sitter 0.20.7 (fb5fbdd78700b20754da5e6b4f2b4317a912e2d2)
$ <kbd>pwd</kbd>
/home/alemuller/git/tree-sitter-c
$ <kbd>git rev-parse master</kbd>
7175a6dd5fc1cee660dce6fe23f6043d75af424a</pre></samp>

**Comment by alemuller** [comment]
From a quick look, the slowdown isn't caused by the length of the rule. It seems to be related with the `ERROR`s.

Tree-sitter-c struggles with the C preprocessor directives, and they often fail. Expanding the macros, tree-sitter works fine.

Preprocess, only include `dictionary.c` content.
<pre><samp>$ <kbd>gcc -E dictionary.c | tac | sed -n '0,/^#/{x;p}' | tac > dictionary_no_macro.c</kbd></samp></pre>

<pre><samp>$ <kbd>$ tree-sitter highlight -t -q dictionary_no_macro.c</kbd>
Time: 292ms</samp></pre>

**Comment by AndersHogqvist** [comment]
If a query timeout is added at some point it would be nice if that found its way into web-tree-sitter as well since that's what I'm using in my project.

In my case the issue is a combination of poorly written grammar and an insane piece of code 🙂

**Comment by alemuller** [comment]
I haven't looked at the wasm backend and I don't know much about JS.

Wouldn't be possible to create a DOM from the AST and use the browser infrastructure to match the queries?
