### ISSUE TITLE
how can i build ABS modeling language using tree sitter

### ISSUE THREAD

**Issue by Yasqader** [tree-sitter/tree-sitter#1961]
hello every body,
i want to build an abs modeling language project using tree-sitter but i don't know how and from where to begin. can anybody help me to solve this problem?
by the way cargo and a C++ compiler are installed on  computer.

**Comment by ahelwer** [comment]
Have you seen https://tree-sitter.github.io/tree-sitter/creating-parsers ?

You would also want to find a spec for your language describing the basic grammar, precedence, how to handle strange corner cases, etc.

**Comment by Yasqader** [comment]
Thank you, i think it's better to use Emacs, i think its easier comparing to tree-sitter. In fact i have Emacs on machine but i dont know where is its init file to add Melpa.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by amaanq** [comment]
It's a bit unclear as to what you're actually asking, the documentation on getting started with creating and developing a parser has been provided to you, and your follow-up is an emacs question of sorts, so I'll close this out. If you still have a tree-sitter question that's a bit more concrete and clear, feel free to open another issue.
