### ISSUE TITLE
Support for lightweight program analysis tool on top of tree-sitter?

### ISSUE THREAD

**Issue by smith-co** [tree-sitter/tree-sitter#1971]
Came across tree-sitter recently. Looks like an awesome library to parse any programming language.

But can it be used to do basic lightweight program analysis such as to extract basic def-use chain for intraprocedural and interprocedural analysis.

Any idea/plan/help is welcome.

**Comment by maxbrunsfeld** [comment]
Maybe check GitHub's *stack graphs* system. Blog post: https://github.blog/2021-12-09-introducing-stack-graphs, repo: https://github.com/github/stack-graphs. That's one approach.

For further discussion, consider opening a discussion thread instead of an issue.
