### ISSUE TITLE
Helix hangs while trying to open file containing unusual unicode character

### ISSUE THREAD

**Issue by sioodmy** [tree-sitter/tree-sitter#1977]
I were told that its not a helix issue

steps to reproduce: open [this file](https://git.sioodmy.dev/sioodmy/dotfiles/src/branch/main/modules/home/waybar/default.nix) with helix with treesitter enabled 

![image](https://user-images.githubusercontent.com/81568712/205507871-cac5f37d-f42f-446b-abbb-49279414b57b.png)
(helix froze at the moment of previewing waybar/default.nix file)

Is there any workaround for that?

**Comment by ahelwer** [comment]
Sad to redirect you again but you're probably looking for one of the tree-sitter-nix repos. Whichever you're using there.

**Comment by ahlinc** [comment]
I can't confirm, tree-sitter correctly parses mentioned file with the the latest version of the grammar.
