### ISSUE TITLE
Sequence rules without `extras` in it

### ISSUE THREAD

**Issue by AntoineBalaine** [tree-sitter/tree-sitter#1979]
Hello,

It would be fantastic to have a way to specify non-whitespace-containing sequences. 
  
```javascript 
extras: $ => [/[\s\n]/],
rules: {
  group: $ =>
    seq_no_extras(
      $.first_rule,
      $.second_rule,
      $.third_rule,
      // etc.
    )
}
```

This would allow for WS-sensitive markdowns to have tight groups and still have WS everywhere else.
Currently, the alternative is only to have no `extras` at all and handle all the WS explicitly - which makes the syntax really-ugly and error-prone.

I understand this request is kind of outside of the scope of traditionnal programming languages, though.

**Comment by leotrs** [comment]
Do you want `group` to match a sequence of `(first_rule)(second_rule)(thid_rule)`, with absolutely no whitespace in between them?

Have you tried

```js
  group: $ =>
    seq_no_extras(
      $.first_rule,
      token.immediate($.second_rule),
      token.immediate($.third_rule),
      // etc.
    )
```

**Comment by AntoineBalaine** [comment]
I have, but it doesn't work:
```javascript
    _pitch: $ => seq(
      optional($.alteration), 
      token.immediate($.note_letter), 
      repeat(token.immediate($.octave))),
```
yields an err:
```bash
$ tree-sitter generate
Error processing rule _pitch_token1

Caused by:
    Grammar error: Unexpected rule Symbol(Symbol { kind: NonTerminal, index: 34 })
```
I think it's because it not possible to use `token.immediate` with named rules.

**Comment by ahlinc** [comment]
Duplicates #931, the more general approach was described in its [comment](https://github.com/tree-sitter/tree-sitter/issues/931#issuecomment-782905634).

**Comment by leotrs** [comment]
Related to https://github.com/tree-sitter/tree-sitter/discussions/1902#discussion-4448750
