### ISSUE TITLE
How to export the grammar?

### ISSUE THREAD

**Issue by boggle** [tree-sitter/tree-sitter#198]
Is there a standardized format for exposing the grammar produced by tree-sitter-cli? I'm aware of the JSON file but haven't found documentation for it. Is there a way to export it to ANTLR for use in a context where a C based parser is not available? What are the plans around this? I'm new to this so sorry if the question is ignorant of established realities.

**Comment by Arcanemagus** [comment]
The documentation on [Creating a Parser](http://tree-sitter.github.io/tree-sitter/creating-parsers) looks to answer most of your questions, the tl;dr though is that what you are specifically asking is impossible as Tree-sitter is its own parsing engine that isn't compatible with ANTLR.

**Comment by maxbrunsfeld** [comment]
Yeah, currently there aren't plans to generate parsers in languages other than C. The reason is that Tree-sitter also has a runtime library that would need to be translated, and it just isn't worth it currently. The good thing about C though is that you can use it from most other languages. What language are you using?

**Comment by boggle** [comment]
I can think of three environments for which this policy is problematic (1) JVM (2) .NET, to a lesser extent (3) the browser unless someone builds a C-to-webassembly that works with tree-sitter. Without addressing these platforms, tree-sitter will not be able to act as a truely generic next-generation parsing framework. For comparison, ANTLR outputs parses in different target languages (but isn't incremental AFAIK).

Because of that exporting the grammar (and not the javascript DSL used to describe) the grammar would be really useful. I don't buy the argument that GLR parsers are soo different that that's not worth it. Firstly, even a grammar in tree-sitter could just be LL(1) in which case this point becomes moot. Secondly, there are other GLR based systems. Thirdly, e.g. ANTLR implements ALL(*) which is also capable of handling ambiguous grammar. Being able to output the grammar in a reasonable format certainly would help parting parsers over if that can't be done automatically. Lastly, having a proper documented grammar externalization is nice for other tools, e.g. for generating railroad diagrams for inclusion in documentation.

**Comment by maxbrunsfeld** [comment]
> I can think of three environments for which this policy is problematic (1) JVM (2) .NET, to a lesser extent (3) the browser unless someone builds a C-to-webassembly that works with tree-sitter.

For JVM and .NET, calling into C is pretty easy, so the existing C library could definitely be used, similar to what we do with other languages. For the browser, producing WebAssembly is definitely not too difficult and I do plan to publish ready-to-use WebAssembly builds at some point. People have already compiled the Tree-sitter runtime and parsers to `asm.js`, the pre-cursor to WebAssembly, but I have not yet automated this as part of my CI.

> I don't buy the argument that GLR parsers are soo different that that's not worth it.

Yeah, I'm quite skeptical that it would be worthwhile, as opposed to just rewriting grammars in ANTLR's DSL if you want to use ANTLR. I would love to be proven wrong.

If you wanted to do that, I think that the logic could be made completely separate from Tree-sitter's core codebase; as you mentioned, you could consume the `grammar.json` file. It isn't documented directly, but its schema is formally specified [here](https://github.com/tree-sitter/tree-sitter/blob/master/src/compiler/grammar-schema.json), and each field's rule is described [here](http://tree-sitter.github.io/tree-sitter/creating-parsers#using-the-grammar-dsl).

**Comment by boggle** [comment]
Thanks for the links, kind-of what I was looking for. Regarding JVM, technically going to C is of course possible and a valid route in some cases but for many situations it will complicate deployment to the point where people will simply not think that it's worth it. tree-sitter-wasm would be nice, that might even open another way for running on the JVM (there's a wasm-to-bytecode cross compiler, not sure how mature).
