### ISSUE TITLE
How to reduce the execution time of the "tree-sitter generate" command

### ISSUE THREAD

**Issue by yutaro-sakamoto** [tree-sitter/tree-sitter#1982]
I am trying to develop a COBOL85 parser in [my repository](https://github.com/yutaro-sakamoto/tree-sitter-cobol/tree/improve_compile_time).
It takes 25 senconds to complete ```tree-sitter generate``` command on my machine.
Additionally, it takes 3 minutes to complete ```tree-sitter generate``` if I uncomment the following lines.

https://github.com/yutaro-sakamoto/tree-sitter-cobol/blob/cc9241e131480412b54320fd0d6f070d24e53326/grammar.js#L1049-L1062

As the development progresses, the time may increase rapidly.
Please tell me the way to reduce the time it takes to generate a parser.

**Comment by ahelwer** [comment]
There are no hard and fast rules. Just test how much generation time/space is added for each additional rule or feature you add, and weigh whether it is worth adding. Sometimes you might want to be a bit less strict with what syntax you accept, for example.

**Comment by yutaro-sakamoto** [comment]
Your response helped me to reduce the time it takes to generate a parser.
Thank you so much!
