### ISSUE TITLE
typescript-tree-sitter doesn't support `+` in mapped types

### ISSUE THREAD

**Issue by kevinbarabash** [tree-sitter/tree-sitter#1983]
TypeScript support `+` or `-` with `readonly` and `?` in mapped types, e.g.
```
type Foo<T, K extends keyof T> = {
    +readonly [P in K]+?: T[P]
};
```
This currently produces an error with the Typescript tree-sitter grammar.

**Comment by kevinbarabash** [comment]
I think the following could work:
```
index_signature: ($) =>
  seq(
    optional(seq(field("readonly_sign", optional(choice("+", "-"))), "readonly")),
    "[",
    choice(
      seq(
        field(
          "name",
          choice($.identifier, alias($._reserved_identifier, $.identifier))
        ),
        ":",
        field("index_type", $._type)
      ),
      $.mapped_type_clause
    ),
    "]",
    optional(seq(field("optional_sign", optional(choice("+", "-"))), "?")),
    field("type", $.type_annotation)
  ),
```

**Comment by ahelwer** [comment]
Sad to redirect you but you'll want to close this issue and open one in the typescript tree-sitter grammar repo. This repo is for the parser generator itself, not parsers people have written with it.

**Comment by kevinbarabash** [comment]
Sorry, I didn't realize there was a separate repo for the grammar.  Thanks!
