### ISSUE TITLE
Can "tree-sitter parse <file>" print also anonymous nodes?

### ISSUE THREAD

**Issue by leotrs** [tree-sitter/tree-sitter#1984]
Is this possible? I looked into the (documented) options and couldn't get this to work.

It seems that when using the `-x` flag, it will include the anonymous nodes in the XML output. However, this doesn't include the start/end point numbers.

**Comment by ahelwer** [comment]
This feature does not exist. PS if you feel this answer is sufficient please close this issue; we have the discussions tab for any future questions you might have.
