### ISSUE TITLE
Adding keyword extraction breaks MISSING node

### ISSUE THREAD

**Issue by rockorager** [tree-sitter/tree-sitter#1993]
Hey, I'm not sure if filing a github issue is appropriate for this, but I wasn't sure where to go for support.

I am working on a grammar and am running into an issue with `MISSING` and `ERROR` nodes. The easiest way to replicate is this:

```js
module.exports = grammar({
  name: "language",
  // word: ($) => $.identifier,
  rules: {
    source_file: ($) => repeat($.use_statement),

    use_statement: ($) =>
      seq(
        "use",
        field("module", $.identifier),
        ";",
      ),

    identifier: ($) => /[a-zA-Z_]\w*/,
  },
});
```

Simple test:
```
======================
Use Statement
======================
use a
use a;
----------------------
(source_file
  (use_statement
    (identifier)
    (MISSING ";"))
  (use_statement
    (identifier)))
```

This test passes, but if I uncomment the `word` definition, it fails with:
```
(source_file
  (use_statement
    (identifier)
    (ERROR
      (identifier)
      (identifier))))
```

I looked through the rust grammar, and it has a very similar layout, and even bypassing many rules to directly get to the use_declaration, this test would pass. I can't figure out what else in the rust grammar is changing this parsing from an `ERROR` to a `MISSING ";"` node.

Thanks in advance!

**Comment by ahelwer** [comment]
Tree-sitter error recovery is a bit of a black box at this point; see #1870 

Personally I would not really pay attention to it and just write your grammar so that it correctly parses valid syntax.

Also this repo has a discussions tab.

**Comment by rockorager** [comment]
Thanks! I'll close this and carry on :).
