### ISSUE TITLE
Parse tree differs using tree-sitter playground

### ISSUE THREAD

**Issue by mkramanathan** [tree-sitter/tree-sitter#1997]
For the following code: 
```
DWORD WINAPI foo()
{
}
```

the tree-sitter parse using tree-sitter client version (0.20.7) and [tree-sitter-cpp](https://github.com/tree-sitter/tree-sitter-cpp) (5ead1e) is as follows:

```
(translation_unit [0, 0] - [3, 0]
  (function_definition [0, 0] - [2, 1]
    type: (type_identifier [0, 0] - [0, 5])
    (ERROR [0, 6] - [0, 12]
      (identifier [0, 6] - [0, 12]))
    declarator: (function_declarator [0, 13] - [0, 18]
      declarator: (identifier [0, 13] - [0, 16])
      parameters: (parameter_list [0, 16] - [0, 18]))
    body: (compound_statement [1, 0] - [2, 1])))
```

Trying this on tree-sitter [playground](https://tree-sitter.github.io/tree-sitter/playground) with C++ parsing shows

```
(translation_unit) [0, 0] - [3, 0]
  (function_definition) [0, 0] - [2, 1]
    type: (type_identifier) [0, 0] - [0, 5]
    declarator: (function_declarator) [0, 6] - [0, 18]
      declarator: (qualified_identifier) [0, 6] - [0, 16]
        scope: (namespace_identifier) [0, 6] - [0, 12]
        (MISSING ::) [0, 12] - [0, 12]
        name: (identifier) [0, 13] - [0, 16]
      parameters: (parameter_list) [0, 16] - [0, 18]
    body: (compound_statement) [1, 0] - [2, 1] 
```

Parsing this code as C on the playground results in the parse tree similar to the local tree-sitter invocation using the cpp build. 

Any inputs on how to detect the client version and cpp binding used by the playground?

**Comment by mkramanathan** [comment]
Thanks @sogaiu. @maxbrunsfeld, can you please help with the above question?

**Comment by nickeb96** [comment]
The parsers on the playground are outdated by over a year.  I ran into this issue this morning while I was trying to fix one of the Rust queries.  It looks like the documentation isn't up to date either.

You'll probably have to download and install tree sitter and any dependencies locally to test out parsers.

Side note: Does anyone know where to find up to date documentation?

**Comment by ahlinc** [comment]
> The parsers on the playground are outdated by about a year.  I ran into this issue this morning while I was trying to fix one of the Rust queries.  It looks like the documentation isn't up to date either.

Documentation is pretty up to date with things covered in it. But docs' playground is a separate thing that  don't update regularly yet.

> You'll probably have to download and install tree sitter and any dependencies locally to test out parsers.

It's possible to use a CLI integrated playground.

> Side note: Does anyone know where to find up to date documentation?

On the official docs page and additional info on a wiki tab in the repo.
