### ISSUE TITLE
Help resolving abiguity.

### ISSUE THREAD

**Issue by christopherroyshields** [tree-sitter/tree-sitter#2004]
I'm having trouble understanding how to resolve ambiguity in my grammar.  If I have a choice between two rules that sometimes both match, how di I give one rule precedence?  For example I have two rules:

```js
    foo: $ => "baz",
    bar: $ => /[bB][aA][zZ]/,
```

```js
choice(
        $.foo,
        $.bar,
)
```

Is there a way to prefer foo over bar?  I've been reading the docs and trying `prec` and conflicts etc. but so far I can't get the results I need.

**Comment by ahelwer** [comment]
Look up token(prec(...))

**Comment by christopherroyshields** [comment]
That helped. Thank you very much.
