### ISSUE TITLE
Most recent cargo tree-sitter-cli version 0.20.7 breaks node usage.

### ISSUE THREAD

**Issue by ilevyor** [tree-sitter/tree-sitter#2008]
To reproduce `cargo install tree-sitter-cli` and follow the instructions instructions for creating a language here: https://tree-sitter.github.io/tree-sitter/creating-parsers

then in a sister directory init a node project with the following in package.json
```json
{
  "name": "simple",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "tree-sitter": "^0.20.1",
    "tree-sitter-hello": "file:../tree-sitter-hello/",
  }
}
```
and  the following in index.js

```js
const Parser = require('tree-sitter');
const Grit = require('tree-sitter-hello');

const parser = new Parser();
parser.setLanguage(Grit);

const sourceCode = 'hello';
const tree = parser.parse(sourceCode);
console.log(tree.rootNode.toString());
```
running `node index.js`
will result in the following error:
``` 
~/simple/node_modules/tree-sitter/index.js:259
  setLanguage.call(this, language);
              ^

RangeError: Incompatible language version. Compatible range: 13 - 13. Got: 14
```

language version can be found on line 8 of parser.c `#define LANGUAGE_VERSION 14`
using 0.20.6 of the rust cli resolves the issue.

**Comment by sogaiu** [comment]
I reproduced.

Within the test project, looking inside  `node_modules/tree-sitter/vendor/tree-sitter/lib/include/tree_sitter/api.h` I got after `npm install`, I see:

```c
#define TREE_SITTER_LANGUAGE_VERSION 13
```

May be that corresponds to: https://github.com/tree-sitter/tree-sitter/blob/3d554ecf6b68ad2c267c1e90b6ef9aa68ae88bcd/lib/include/tree_sitter/api.h#L24

It looks to me like `node-tree-sitter` has vendored a specific tree-sitter: https://github.com/tree-sitter/node-tree-sitter/tree/master/vendor

Note the [tree-sitter @ 3d554ec](https://github.com/tree-sitter/tree-sitter/tree/3d554ecf6b68ad2c267c1e90b6ef9aa68ae88bcd)

IIUC, tree-sitter (the Rust cli) 0.20.7 is based off of b268e412ad4848380166af153300464e5a1cf83f and that commit is not that many after https://github.com/tree-sitter/tree-sitter/commit/e2fe380a08408ff42eada21f8723f653e6da6606 (Generte parsers with ABI version 14 by default).

I think the following are related issues:

* https://github.com/tree-sitter/tree-sitter/issues/1882
* https://github.com/tree-sitter/tree-sitter/issues/1628

**Comment by verhovsky** [comment]
This should be fixed by node-tree-sitter (simply "tree-sitter" on npm) version 0.20.3

https://github.com/tree-sitter/node-tree-sitter/pull/146
