### ISSUE TITLE
node version of CLI fails on my M1 MacBook Pro

### ISSUE THREAD

**Issue by ilevyor** [tree-sitter/tree-sitter#2009]
unfortunately was not able to reproduce on  other similar machines maybe unique to me?
On my machine running
`npm install --save-dev tree-sitter-cli`
followed by
`./node_modules/.bin/tree-sitter`
resulting in the following error
```
node:internal/child_process:413
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:743:9)
    at Object.<anonymous> (~/tree-sitter-hello/node_modules/tree-sitter-cli/cli.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47 {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```
expected output is a help menu from the cli. Other commands produce the same output.

**Comment by sogaiu** [comment]
Apparently:

>  on M1, 86 is "unknown arch".

according to: https://github.com/pa11y/pa11y/issues/619#issuecomment-986182745

**Comment by ahlinc** [comment]
The issue is because Tree-sitter CLI isn't compiled for M1 yet and `npm install` installs wrong version.

**Comment by ahlinc** [comment]
https://github.com/tree-sitter/tree-sitter/blob/25680274ccc8f45eb4c61b277bcbd71c55b75a4e/cli/npm/install.js#L22-L25

Try to install Rosetta 2 by executing in a terminal:
```
softwareupdate --install-rosetta
```

**Comment by clason** [comment]
For that to work, you need to be running an x86_64 terminal (not the native M1 terminal.app or iTerm2).

**Comment by ahlinc** [comment]
> For that to work, you need to be running an x86_64 terminal (not the native M1 terminal.app or iTerm2).
> 
> But I don't quite understand; tree-sitter CLI works fine (natively) on my M1 via homebrew? I think that "lying" snippet is not needed (anymore).

I suppose Homebrew distributes native M1 arm build ...
@clason what `file $(which tree-sitter)` tells for you?

**Comment by clason** [comment]
> I suppose Homebrew distributes native M1 arm build ... @clason what `file $(which tree-sitter)` tells for you?

`/opt/homebrew/bin/tree-sitter: Mach-O 64-bit executable arm64`

I assume that homebrew is building via `cargo`, though; I must admit that the polyglot monorepo structure of the project is somewhat confusing to me.

**Comment by ahlinc** [comment]
>  I must admit that the polyglot monorepo structure of the project is somewhat confusing to me.

@clason could you explain in more details?

**Comment by clason** [comment]
I don't understand how the different parts (C library, Rust crate, node package, CLI, etc.) play together.

**Comment by clason** [comment]
OK, tested a bit, and you can build M1 tree-sitter CLI just fine, but then the build workflow fails on the `generate fixtures` step:
https://github.com/clason/tree-sitter/actions/runs/4628911380/jobs/8188563345

Since this step only generates but not builds parsers (right?), that should not be a blocker; but it means that you'd have to restructure the matrix to have a "universal macos" runner that builds the CLI for both architectures (and only uses the x86 CLI for the generation).

**Comment by clason** [comment]
(or just skip everything but building and publishing on `macos-arm64` -- if that is acceptable, I can open a PR!)

**Comment by ahlinc** [comment]
The `tree-sitter-cli` [v0.20.8](https://www.npmjs.com/package/tree-sitter-cli/v/0.20.8) was published on npm so this issue completely resolved.
