### ISSUE TITLE
Incorrect result of ts_node_first_child_for_byte

### ISSUE THREAD

**Issue by sogaiu** [tree-sitter/tree-sitter#2012]
There are 2 reports of `ts_node_first_child_for_byte` returning what appears to be an incorrect result:

* https://github.com/tree-sitter/tree-sitter-bash/issues/139
* https://github.com/sogaiu/tree-sitter-clojure/issues/32

I investigated both issues and posted [a writeup](https://github.com/tree-sitter/tree-sitter-bash/issues/139#issuecomment-1364675904) to the fomer issue explaining my findings.  ATM, I think `ts_node_first_child_for_byte` doesn't handle certain specific cases.

I went searching for use of `ts_node_first_child_for_byte`, but apart from Emacs 29+, I did not find any use.  Does anyone know of other uses of this function?

cc @casouri @dannyfreeman

**Comment by casouri** [comment]
I just interacted from the first child like @sogaiu did in their writeup ;-)

**Comment by sogaiu** [comment]
For interested parties, [here](https://github.com/sogaiu/tree-sitter-issue-2012) is a repository that one can use to reproduce, at least for tree-sitter-clojure.
