### ISSUE TITLE
Confusion about automatic compilation via subcommands and documentation

### ISSUE THREAD

**Issue by sogaiu** [tree-sitter/tree-sitter#2017]
I've been puzzled from time to time about "automatic compilation" and when it might be triggered.

There is a section in the docs about [Automatic Compilation](https://tree-sitter.github.io/tree-sitter/creating-parsers#automatic-compilation) which currently reads:

> You might notice that the first time you run tree-sitter test after regenerating your parser, it takes some extra time. This is because Tree-sitter automatically compiles your C code into a dynamically-loadable library. It recompiles your parser as-needed whenever you update it by re-running tree-sitter generate.

Indeed, I have observed running `tree-sitter test` after `tree-sitter generate` leading to compilation (easily observable evidence is the appearance of a replacement `.so` file), but automatic compilation seems to occur under other circumstances as well. 

From some empirical tests and reading of source, the following are subcommands I think can trigger compilation:

* `generate` -- in 2023-01 `--build` was added; if it's present, yes
* `highlight`
* `parse` -- added thanks to ahlinc's comment
* `query`
* `tags`
* `test`

Does ti seem worth mentioning in the docs that other subcommands can trigger automatic compilation?

It's a feature which can be convenient but I suspect it has contributed to confusion at times.

**Comment by ahelwer** [comment]
Also `npm install`

**Comment by sogaiu** [comment]
Hmm, I'm not seeing the same sort of results as for the aforementioned subcommands -- i.e. no resulting `.so` in a place `tree-sitter` can find it.

May be you meant something else?

I do see some binding-related compilation that IIUC results from `node-gyp rebuild` being triggered by `npm install` because there's a `binding.gyp` file, but that seems to be a different thing from the "automatic compilation" related to `tree-sitter`.  I can see it being "automatic" and "compilation" for sure.

FWIW, I made attempts with tree-sitter-clojure and tree-sitter-tlaplus

**Comment by ahelwer** [comment]
Oh I just noticed that it was possible for npm install to return compilation errors when run. So it must be building something, don't know what though

**Comment by sogaiu** [comment]
I ran `npm clean-install --verbose` in the repository root and examined the output.

IIUC, since there is a `binding.gyp` in the project root, `node-gyp rebuild` gets triggered.  I think that leads to compilation of node bindings with the resulting bits being placed under `build` (created if not already there), e.g for tree-sitter-clojure that might look like:
```
$ tree build/
build/
├── binding.Makefile
├── config.gypi
├── Makefile
├── Release
│   ├── obj.target
│   │   ├── tree_sitter_clojure_binding
│   │   │   ├── bindings
│   │   │   │   └── node
│   │   │   │       └── binding.o
│   │   │   └── src
│   │   │       └── parser.o
│   │   └── tree_sitter_clojure_binding.node
│   └── tree_sitter_clojure_binding.node
└── tree_sitter_clojure_binding.target.mk
```
I compared the post-command directory to a fresh clone and that was the only difference I noticed (other than the existence of `node_modules`).  Prior to running the command I deleted `clojure.so` from where it typically lives and a new one had not appeared after the command.

So far the evidence suggests to me that `npm install` and friends don't lead to the grammar shared object getting compiled.  Compilation can occur but that appears to be for the node bindings only.

(Perhaps I will remove `binding.gyp` as I don't use the node bindings nor do I know of others who do either.)

**Comment by ahlinc** [comment]
Automatic compilation may trigger on every subcommand that requires a parser for its function, that happens in the `tree-sitter-loader` crate.

**Comment by sogaiu** [comment]
Thanks for the explanation.  That makes sense.

I will add `parse` as well (which I confirmed) to my notes.

---

On a side note, occasionally I notice that an unexpected version of a shared object gets put into place.  (Though I have never noticed this happening for the `test` subcommand.)

I think I tracked that down to being influenced by the "scanning" / "probing" that's done to directories that have names beginning with `tree-sitter-` that live under each of the directories set by `parsrer-directories` (as mentioned in `config.json`).

It happens that I sometimes have alternate versions of a grammar in sibling directories and that those versions are named something like:

* `tree-sitter-<name>.alice`
* `tree-sitter-<name>.bob`

I didn't figure out a nice way to turn off the "scanning" and only consider the current grammar project (essentially get the same behavior as for the `test` subcommand).  I don't suppose there's an easy way [1] to accomplish this?

---

[1] What I've hit upon recently is the following hack:

* Set `TREE_SITTER_DIR` to correspond to a specific subdirectory of a grammar's project directory.
* Have a corresponding custom `config.json` (that lives in the aforementioned subdirectory) with a `parser-directories` that has a single entry which is ".":
    ```
      "parser-directories": [
        "."
      ],
    ```
* Have a symlink in the specific grammar's project directory named like `tree-sitter-<name>` that points at `.`

That seems to work, but it seems quite awkward.

I started investigating the automatic compilation because while testing I became quite confused when the results I was seeing seemed to be from older or alternate grammars.

I learned recently that using the `dump-languages` subcommand can make it clearer which `tree-sitter-` directories have been considered.

**Comment by sogaiu** [comment]
I looked into:

> Though I have never noticed this happening for the test subcommand.

May be this is because `test` and `generate` use:

```rust
loader.languages_at_path(&current_dir)?;
```
while, `parse`, `query`, `tags`, and `highlight` all do:

```rust
loader.find_all_languages(&loader_config)?;
```

**Comment by sogaiu** [comment]
I think https://github.com/tree-sitter/tree-sitter/issues/732#issuecomment-1383692051 is an example of some folks experiencing confusion that is related to what's been discussed here.

I think the suggestion in that comment:

> Make Highlight behave just like test.

is sort of along the lines of one way I'd like to use the `tree-sitter` cli.

That is, just for one grammar at a time, the one corresponding to the grammar repository directory I have locally where I'm executing the `tree-sitter` cli from.  I think this type of use case is likely to be pretty common.

The method I described in the footnote [earlier in this issue](https://github.com/tree-sitter/tree-sitter/issues/2017#issuecomment-1375796247) is an attempt along these lines.

But it seems clear that there are other uses where folks are trying to run the cli with more than one grammar being relevant per `tree-sitter` invocation.  I presume that the scanning of things living under `parser-directories` is for these kinds of purposes.

Haven't thought of a good way for these two use cases to be served with reduced confusion but I'm interested in exploring :)

Or perhaps there's already a pretty good way to do this?

**Comment by sogaiu** [comment]
@ahlinc 

So for the use case of working with only one language (though possibly with different versions / branches), I tried the following modification to [the current code](https://github.com/tree-sitter/tree-sitter/blob/eb970a83a107cbaba52e31588355c0b09b3a308a/cli/loader/src/lib.rs#L144-L168):
```
diff --git a/cli/loader/src/lib.rs b/cli/loader/src/lib.rs
index 029da451..efd9a566 100644
--- a/cli/loader/src/lib.rs
+++ b/cli/loader/src/lib.rs
@@ -148,6 +148,7 @@ impl Loader {
             eprintln!("configuration file to indicate where we should look for");
             eprintln!("language grammars.");
             eprintln!("");
+            self.find_language_configurations_at_path(&PathBuf::from(".")).ok();
         }
         for parser_container_dir in &config.parser_directories {
             if let Ok(entries) = fs::read_dir(parser_container_dir) {
```

This combined with making `parser-directories` in `config.json` empty seems to work nicely.

IIUC, now if I invoke `tree-sitter test` at the root of a grammar repository I'm working on it will only make use of the corresponding information from the directory the `test` subcommand is invoked from and not any other sibling directory (which is what can happen otherwise, depending on one's configuration and the existence of certain other directories).

I'm not sure if there are some drawbacks to this approach, but at the moment it seems to be working pretty well.

What do you think of this idea?

**Comment by ahelwer** [comment]
@sogaiu where are the built .so files actually output? I'd like to compile them manually with a bunch of sanitizers.

**Comment by sogaiu** [comment]
@ahelwer If you haven't set `TREE_SITTER_DIR` or `TREE_SITTER_LIBDIR` and are using a relatively recent `tree-sitter`, I think that's right.

**Comment by ahelwer** [comment]
@sogaiu unfortunately I can't get `TREE_SITTER_DIR` or TREE_SITTER_LIBDIR` to work, `tree-sitter test` just keeps recompiling the file and putting it in `~/.cache/tree-sitter/lib`. So I guess that's the move.

**Comment by sogaiu** [comment]
@ahelwer FWIW, `TREE_SITTER_LIBDIR` doesn't work with any released version of the `tree-sitter` cli.  Sorry that wasn't clear above.

If you don't mind using what's on master, I think that will work.

With the latest `tree-sitter` cli, I believe you can use the `generate` subcommand with `--libdir` option and `--build` flag to get compilation to occur.

For example, here:
```
$ cd ~/src/tree-sitter-clojure

$ rm .tree-sitter/lib/clojure.so 

$ tree-sitter.master generate --build --libdir .tree-sitter/lib

$ ls .tree-sitter/lib/
clojure.so
```

**Comment by sogaiu** [comment]
It may be necessary to set env vars (or arrange for an appropriate `config.json`) to have a newly created `.so` file to be used.

Hmm, seems like it could be handy to be able to tell `parse` and other friend `subcommands` exactly which `.so` file to use...

**Comment by woolsweater** [comment]
Being able to run `tree-sitter test` against an already-built grammar would also aid the cause of writing external scanners in other languages -- without the CLI having to gain  knowledge about other build systems.

Right now I can link together an .so/.dylib from 'parser.c' and any other object file I want that exports the `tree_sitter_mylang_external_scanner_*` symbols. And I can load that and use it for highlighting. But then I lose access to the tree-sitter test runner, which is a big loss.
