### ISSUE TITLE
Strange rule name `known_macro_invocation_repeat2`, and why `tree-sitter generate` fails while `tree-sitter build-wasm` and `tree-sitter parse ...` works?

### ISSUE THREAD

**Issue by crsov** [tree-sitter/tree-sitter#2029]
### Discussed in https://github.com/tree-sitter/tree-sitter/discussions/2028

<div type='discussions-op-text'>

<sup>Originally posted by **crsov** January 14, 2023</sup>
I have the [following](https://aruthecrsov.com/files/for-tree-sitter-discussion/grammar.js) grammar forked from [tree-sitter-rust](https://github.com/tree-sitter/tree-sitter-rust), which in turn `require`s [generated.js](https://aruthecrsov.com/files/for-tree-sitter-discussion/generated.js) (I am generating this file using an external program).

`tree-sitter generate` fails with this output:
```
The rule `known_macro_invocation_repeat2` matches the empty string.

Tree-sitter does not support syntactic rules that match the empty string
unless they are used only as the grammar's start rule.
```

What is `known_macro_invocation_repeat2`? There is only `known_macro_invocation` rule in generated.js. How does `known_macro_invocation_repeat2` relate to `known_macro_invocation`?
</div>

While `tree-sitter generate` fails, both `tree-sitter build-wasm` (built wasm works correctly) and `tree-sitter parse <SOMERUSTFILE>` (parser works correctly) works...

EDIT: I am using latest 0.20.7 version of cli
EDIT2: I have also tried `tree-sitter build-wasm` and `tree-sitter parse ...` after clearing the cache located at `~/.cache/tree-sitter` (I am using linux), and both commands work while `tree-sitter generate` doesn't

**Comment by ahelwer** [comment]
Build-WASM and parse both use the existing generated parser.c file. When you try to generate a new parser.c it fails. Your other question is answered in the discussion thread you made.

**Comment by ahlinc** [comment]
Please, don't make double posting, it doesn't get more attention.
