### ISSUE TITLE
CLI's init-config doesn't account for TREE_SITTER_DIR

### ISSUE THREAD

**Issue by sogaiu** [tree-sitter/tree-sitter#2030]
At the moment I think the `tree-sitter` cli's `init-config` subcommand isn't affected by the value of the `TREE_SITTER_DIR`environment variable:

https://github.com/tree-sitter/tree-sitter/blob/ca38c32d368ffd84e686b0cf41fef754044351a9/cli/src/main.rs#L265-L274

https://github.com/tree-sitter/tree-sitter/blob/ca38c32d368ffd84e686b0cf41fef754044351a9/cli/config/src/lib.rs#L82-L87

Would it make sense to take into account the value of the `TREE_SITTER_DIR` environment variable?

May be something like:

```rust
diff --git a/cli/config/src/lib.rs b/cli/config/src/lib.rs
index 0a5eba54..bec7b4ce 100644
--- a/cli/config/src/lib.rs
+++ b/cli/config/src/lib.rs
@@ -79,7 +79,14 @@ impl Config {
     ///
     /// (Note that this is typically only done by the `tree-sitter init-config` command.)
     pub fn initial() -> Result<Config> {
-        let location = Self::xdg_config_file()?;
+        let location =
+            if let Ok(path) = env::var("TREE_SITTER_DIR") {
+                let mut path = PathBuf::from(path);
+                path.push("config.json");
+                path
+            } else {
+                Self::xdg_config_file()?
+            };
         let config = serde_json::json!({});
         Ok(Config { location, config })
     }
```

**Comment by ahlinc** [comment]
Sure, it makes sense, a PR is welcome!

**Comment by sogaiu** [comment]
Since #2035 has been merged, I'm going to close this.
