### ISSUE TITLE
Sometimes cli won't create config even if `TREE_SITTER_DIR` set to point elsewhere

### ISSUE THREAD

**Issue by sogaiu** [tree-sitter/tree-sitter#2033]
Currently, if there is a `config.json` say under `~/.config/tree-sitter/` already (say for Linux), a new one will not be created when `TREE_SITTER_DIR` is set to point elsewhere:

```
$ ls ~/.config/tree-sitter/config.json 
/home/user/.config/tree-sitter/config.json

$ cd /tmp

$ TREE_SITTER_DIR=/tmp/.tree-sitter tree-sitter init-config
Remove your existing config file first: /home/user/.config/tree-sitter/config.json
```
IIUC, in the current code, if `TREE_SITTER_DIR` is set and no `config.json` is found in a corresponding location, checking continues to look elsewhere:

https://github.com/tree-sitter/tree-sitter/blob/eb970a83a107cbaba52e31588355c0b09b3a308a/cli/config/src/lib.rs#L25-L36

I think it makes more sense for it to stop looking in this case.

If that sounds good, I can work on a PR.

**Comment by ahlinc** [comment]
👍 it sounds good and would be nice to have a PR.

**Comment by sogaiu** [comment]
As #2035 has been merged, I'm going to close this.
