### ISSUE TITLE
Cannot set property 'refutedProperties' of undefined on web-tree-sitter

### ISSUE THREAD

**Issue by mauricioszabo** [tree-sitter/tree-sitter#2045]
Maybe related to https://github.com/tree-sitter/tree-sitter/issues/1968?

Basically, I installed `web-tree-sitter` and tried to parse a Ruby grammar. I exported the WASM file with: `tree-sitter build-wasm --docker node_modules/tree-sitter-javascript/`

Then I moved the resulting WASM file into `/tmp/grammars/ruby/grammar.wasm` and all queries to `/tmp/grammars/ruby/queries`, and tried to run this code:

```js
const Parser = require('web-tree-sitter');

let parser
Parser.init().then(() => {
  parser = new Parser()
  return Parser.Language.load('/tmp/grammars/ruby/grammar.wasm')
}).then(language => {
  let syntaxQuery = fs.readFileSync('/tmp/grammars/ruby/queries/highlights.scm', 'utf-8')
  parser.setLanguage(language)
  syntaxQuery = language.query(syntaxQuery)
  const tree = parser.parse('a = 1')
  global.highlights = syntaxQuery.matches(tree.rootNode)
})
```

This last line gave me the error `Cannot set property 'refutedProperties' of undefined`. The code is minified, so I'm not sure what should I have it there, but when I try to open on devtools (I'm running this code on Electron, but it fails on Node the same) I see this code:

```js
const e = this.setProperties[r];
e && (i[t].setProperties = e);
const n = this.assertedProperties[r];
n && (i[t].assertedProperties = n);
const s = this.refutedProperties[r];
s && (i[t].refutedProperties = s)
```

`s` is basically `{local: null}` and `i` is an array of 1 element. Problem is that `t` is `3`, so it's trying to find the 3rd element of a 1-size array.

**Comment by mauricioszabo** [comment]
Question - shouldn't these lines (https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/binding.js#L991) that have `result[i]` be actually `result[filteredCount]` (with filtered count not being incremented in the beginning)?

**Comment by ahelwer** [comment]
Did you use a specific earlier version of emscripten when you ran build-wasm

**Comment by sogaiu** [comment]
I believe what ahelwer is hinting at is that depending on which version of the tree-sitter cli was used for execution of the `build-wasm` subcommand, the version of emscripten used to compile the `.wasm` file may matter.

If using a tree-sitter cli based off of master, I think emsdk 3.1.29 should work, but if it's before 0.20.7 but post 0.20.0, then 2.0.24 may work better.  If I'm off on that may be someone can point that out.

I have a summary of some version highlights [here](https://github.com/sogaiu/tree-sitter-clojure/blob/dev-notes/doc/dev-notes.md#some-tree-sitter-version-highlights).

**Comment by sogaiu** [comment]
About the code, it looks like the indeces all used to be `i` only: https://github.com/tree-sitter/tree-sitter/blob/f65b499a7ce411650d2e9b45fb64d787b9ef26ba/lib/binding_web/binding.js#L983-L991

and that changed in [this commit](https://github.com/tree-sitter/tree-sitter/commit/41e9af245690f3e6cbedddef05ec3f740d90d64b).

**Comment by ahelwer** [comment]
I use emsdk 2.0.17 but I'm not sure when it starts breaking exactly. Good to know this will be fixed in the next release!

**Comment by mauricioszabo** [comment]
@ahelwer I used `--docker` toggle because newer emscripten can't actually compile a valid grammar. It does generate the WASM version, but loading it fails this error from this PR: https://github.com/tree-sitter/tree-sitter/pull/1913.

So, what exactly I should be doing? I'm already on latest versions of both the CLI, the `web-tree-sitter` NPM module, and `tree-sitter-ruby`. Should I compile one from `master`, do I wait for a new release, is it really a bug that needs to be fixed or is it already fixed on master?

**Comment by ahelwer** [comment]
I would use emscripten 2.0.17, it works for me. Whenever a new tree-sitter-cli release happens I'll regenerate my grammar with it and try newer versions of emscripten.

**Comment by mauricioszabo** [comment]
Same error with Emscripten 2.0.17.
