### ISSUE TITLE
Edit within node

### ISSUE THREAD

**Issue by rspencer01** [tree-sitter/tree-sitter#2046]
Is there a way (possibly not in the public API) to reparse a particular _node_ and its subtree?

That is, I have an edit that is guaranteed to be contained in the range of a particular node. Can I reparse the tree rooted at that node? Nodes that are after the edited node may move forwards or backwards (depending on the edit) but not change type or the number of characters they contain. Elements of the subtree rooted at our selected node might be clobbered by the edit. If the node cannot be parsed in isolation, I'd expect it to become `ERROR`.

**Comment by ahelwer** [comment]
The ordinary incremental re-parse logic does do something similar to what you want.

**Comment by rspencer01** [comment]
Can I force tree-sitter to contain the errors though?

For example if I change
```
def function {
 ... lines here ...
}
```
to
```
def function {
 {
 ... lines here ...
}
```
then I'd like the parser to stop at the `}` and declare the internal of `function` an ERROR, rather than attempting to match the extra brace I've added with later close braces.

**Comment by ahelwer** [comment]
Unfortunately not really, there is limited control over error recovery.

**Comment by rspencer01** [comment]
Thanks, @ahelwer
