### ISSUE TITLE
Aarch64 musl alpine fails to compile due to atomic_inc using a undefined function __sync_add_and_fetch

### ISSUE THREAD

**Issue by stevenvandenbrandenstift** [tree-sitter/tree-sitter#2052]
Since there is no define for musl I would suggest to change the code to something like this:

https://github.com/tree-sitter/tree-sitter/blob/master/lib/src/atomic.h#L48

from:
```
static inline uint32_t atomic_inc(volatile uint32_t *p) {
  return __sync_add_and_fetch(p, 1u);
}
```
to
```
static inline uint32_t atomic_inc(volatile uint32_t *p) {
#ifdef __GLIBC__
  return __sync_add_and_fetch(p, 1u);
#else
   uint32_t res = __atomic_add_fetch(p, 1u, __ATOMIC_RELEASE);
   __sync_synchronize();
   return res;
#endif
}
```

I did not test that this also works fine on glibc yet, but would like to have some review/comments before opening a pull request for this.

**Comment by stevenvandenbrandenstift** [comment]
btw inspiration taken from here:
https://github.com/openjdk/jdk/commit/d735f919#diff-122a48c5f9efdec852caee6ea86866694bbafc38c8c334141ca418fd52054d50

**Comment by ahlinc** [comment]
Thank you for suggestion, such improvements have sense. I saw similar issues when tried to compile Tree-sitter on Android.

**Comment by amaanq** [comment]
Alright I was able to confirm it works fine in a docker container on Alpine Linux for a while now, let me know if not with steps to reproduce, ideally via a Docker container.
