### ISSUE TITLE
alpine musl aarch64 linker issue (help wanted)

### ISSUE THREAD

**Issue by stevenvandenbrandenstift** [tree-sitter/tree-sitter#2053]
Hello,

Trying to compile tree-sitter with a rust toolchain downloaded via rustup (aarch64-unknown-linux).
(note i did make a fix for tree-sitter atomic (other issue opened)).

I get this linking error:
```
  = note: "cc" "/home/user/.rustup/toolchains/stable-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o" .... -> long command
  
  = note: /usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: /home/user/git/lapce/target/release/deps/libtree_sitter-18bfe0f59073b11a.rlib(lib.o): in function `ts_subtree_release':
          lib.c:(.text.ts_subtree_release+0x2c): undefined reference to `__aarch64_ldadd4_sync'
          /usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: lib.c:(.text.ts_subtree_release+0xf4): undefined reference to `__aarch64_ldadd4_sync'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `lapce` due to previous error
```

Does anyone know how to fix that?

**Comment by sogaiu** [comment]
Don't know but I found `__aarch64_ldadd4_sync` mentioned at the following:

* https://www.mail-archive.com/gcc-patches@gcc.gnu.org/msg284537.html
* https://github.com/gcc-mirror/gcc/blob/master/gcc/testsuite/gcc.target/aarch64/sync-op-full-ool.c

BTW, doesn't this path `/home/user/git/lapce/` mean the compilation is an attempt to get [lapce](https://github.com/lapce/lapce) to work?

Don't know if you had a look already, but they have a [guide](https://github.com/lapce/lapce/blob/master/docs/building-from-source.md) that mentions a minimum rust version.

**Comment by stevenvandenbrandenstift** [comment]
Oh indeed, I was multitasking, and it seems I am not good at that. But since it complains about tree-sitter that is using this symbol i thought i could ask here. Is there a other forum (eg matrix/irc) to ask these questions before opening an issue? I will try to build tree-sitter manually as well.

**Comment by sogaiu** [comment]
For generic tree-sitter discussions I'm only aware of the [Discussions section of this repository](https://github.com/tree-sitter/tree-sitter/discussions) and a recently started discord server (mentioned here: https://github.com/tree-sitter/tree-sitter/discussions/2027).

Various editor communities seem to have their own discussions that touch on tree-sitter too.

**Comment by clason** [comment]
I've mentioned setting up a Matrix room for cross-editor tree-sitter dev discussions, and I'd be happy to do so -- but only if there's going to be something of a reliable presence from (some of) the core tree-sitter contributors. Do you think there'd be interest in that?

**Comment by stevenvandenbrandenstift** [comment]
not sure about that but i am able to compile now with rust toolchain from apk repo, so must have done something wrong
