### ISSUE TITLE
Error in `playground.html`

### ISSUE THREAD

**Issue by ad-chaos** [tree-sitter/tree-sitter#2062]
I believe this
https://github.com/tree-sitter/tree-sitter/blob/6f42c78f2d0173f64d9346b30f0e8c46b5a9b7a6/cli/src/playground.html#L33

Should actually be
```html
<option value="parser">THE_LANGUAGE_NAME</option> 
```

**Comment by ahlinc** [comment]
I think it's a stub for a future improvement of a playground builtin in the CLI. But currently it doesn't have effect due to `display: none` on a line above.

**Comment by ad-chaos** [comment]
I see, I thought playground was already a part of the CLI and that the options were hidden under the assumption it would be invoked from a just a single project.

Currently running `tree-sitter build-wasm; tree-sitter playground` leads to a lot of errors because the parser isn't correctly initialised and subsequently the `tree` remains `null` even though the project root contains the wasm file.

Is there a tracking issue for the improvement of the `playground` cli?
Thanks!

**Comment by sogaiu** [comment]
Which versions of the tree-sitter cli and Emscripten are you using?

**Comment by ad-chaos** [comment]
`tree-sitter 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f)`
```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.31 (e88336121cfe6da4a96c88e46f314552f07dfed0)
clang version 17.0.0 (https://github.com/llvm/llvm-project 1142e6c7c795de7f80774325a07ed49bc95a48c9)
Target: wasm32-unknown-emscripten
Thread model: posix
```

**Comment by sogaiu** [comment]
I think it's possible that version of the tree-sitter cli will not work with a grammar's `.wasm` built with that version of Emscripten -- 3.1.31 IIUC.

If you want to stay at 0.20.7 for tree-sitter, I think it may be that Emscripten 2.0.24 may work (see [this file](https://github.com/tree-sitter/tree-sitter/blob/b268e412ad4848380166af153300464e5a1cf83f/cli/emscripten-version) from the commit corresponding to what your version string indicated).

If you build from master I'm pretty sure Emscripten 3.1.29 will work (that's what I've been using) -- I think for the 3.1.x series, the initial support was for [3.1.25](https://github.com/tree-sitter/tree-sitter/commit/1f36bf091e1faaec5d9282f47c9dab00f7435e06).  Perhaps you know how to do this already, but for reference, there are instructions [here](https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-6-contributing.md#building) -- there's an extra step of `script/build-wasm` that may be of interest.

**Comment by ad-chaos** [comment]
Ah! I did not know about the discrepancy between versions, I shall try that out and let you know.
Thanks!

**Comment by ad-chaos** [comment]
Hmm, looks like things are still broken. I believe the error happens because the [`languageSelect`](https://github.com/tree-sitter/tree-sitter/blob/master/docs/assets/js/playground.js#L24) variable references the html select element with the `language-select` id which points to `Parser` instead of `THE_LANGUAGE_NAME`.

The browser then tries to load [`tree-sitter-Parser.wasm`](https://github.com/tree-sitter/tree-sitter/blob/master/docs/assets/js/playground.js#L85) which is non-existent.

**Comment by sogaiu** [comment]
Hmm...I just tried with tree-sitter 0.20.7 and Emscripten 2.0.24 and the combination worked (at least for tree-sitter-clojure).

Is there a specific grammar repository you are trying with and do you have some error output you could share?

**Comment by sogaiu** [comment]
Don't know if it's relevant but I came across this: https://github.com/tree-sitter/tree-sitter-haskell/issues/35#issuecomment-857387920

**Comment by ad-chaos** [comment]
I installed `tree-sitter-clojure` and on the same environment as yours.
Then ran `ts build-wasm; ts web-ui` and the subsequent webpage had the following errors.
```
Uncaught (in promise) RuntimeError: null function or function signature mismatch
    at tree-sitter.wasm:0x16cbb
    at tree-sitter.wasm:0x2638d
    at tree-sitter.wasm:0x2d957
    at Module._ts_parser_parse_wasm (tree-sitter.js:1:18760)
    at Parser.parse (tree-sitter.js:1:33876)
    at handleCodeChange (playground.js:115:28)
    at handleLanguageChange (playground.js:101:5)
    at async playground.js:78:3
tree-sitter.wasm:0x16cbb Uncaught (in promise) RuntimeError: null function or function signature mismatch
    at tree-sitter.wasm:0x16cbb
    at tree-sitter.wasm:0x2638d
    at tree-sitter.wasm:0x2d957
    at Parser.parse (tree-sitter.js:1:33876)
    at handleCodeChange (playground.js:115:28)
    at it (codemirror.min.js:1:17760)
    at jn (codemirror.min.js:1:65062)
    at codemirror.min.js:1:61536
    at codemirror.min.js:1:61545
    at codemirror.min.js:1:61216
playground.js:326 Uncaught TypeError: Cannot read properties of null (reading 'rootNode')
    at handleCursorMovement (playground.js:326:23)
    at later (playground.js:453:30)
127.0.0.1/:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

> Don't know if it's relevant but I came across this: https://github.com/tree-sitter/tree-sitter-haskell/issues/35#issuecomment-857387920

> Good luck -- off to sleep :)

Thanks for your time! Appreciate it :)

**Comment by ad-chaos** [comment]
I am on an arm64 machine, and since you aren't facing such problems I am led to believe that all of this fuss is coming from that :/

**Comment by sogaiu** [comment]
I found [this](https://github.com/tree-sitter/tree-sitter/issues/1737), but am unsure of the status regarding support for arm64 / M*.

Along those lines, may be there isn't support yet, possibly hinted at in this recently modified [text](https://tree-sitter.github.io/tree-sitter/creating-parsers#installation):

> Install the tree-sitter-cli [Node.js module](https://www.npmjs.com/package/tree-sitter-cli) using [npm](https://docs.npmjs.com/), the Node package manager. This approach is fast, but is only works on certain platforms, because it relies on pre-built binaries.


May be someone else knows though.

**Comment by ad-chaos** [comment]
Alright, I'll just not use the `web-ui` until then :( 

Thanks a lot for your time! I really appreciate it! 😄

**Comment by sogaiu** [comment]
I found the following [comment](https://github.com/tree-sitter/tree-sitter/commit/46cdc512b75727fd07608e95a3388da9bc4e55e1#diff-536cac8e025525a8e86692463d9eeea3b4940eafe5a9fde127dcfba11e6d5b95R21):

> // ARM macs can run x64 binaries via Rosetta. Rely on that for now.

I guess may be some things work but not everything...may be it's worth a separate issue?  I'd consider creating an issue but don't have any suitable hardware to test with.

As far as work-arounds go, if you happen to use Neovim, there's nvim-treesitter's [playground](https://github.com/nvim-treesitter/playground) that is somewhat like the playground / web-ui subcommand.

Or if you are ok with Emacs, the upcoming version 29 [1] also has [something similar](https://github.com/emacs-mirror/emacs/blob/8360e12f0ea3a3ccf0305adab3c7ea7e38af36c1/lisp/treesit.el#L2654-L2659).

Possibly other editors might have similar support...

---

[1] Might not even need to manually compile from source: https://github.com/d12frosted/homebrew-emacs-plus

**Comment by ad-chaos** [comment]
> if you happen to use Neovim, there's nvim-treesitter's [playground](https://github.com/nvim-treesitter/playground)

I was indeed using that before, but the syntax tree didn't update as I edited the buffer, but looking at the issue you linked earlier from the haskell parser, looks like you should be able to get live updates even in the tree-sitter playground. I did try messing around with the `updatetime` parameter to see if it was just too slow, but that also didn't result in anything.

I saw on the documentation website that I could get live updates on a playground so decided to try it out. But alas, that only resulted in a lot of errors.

As for emacs, uhh I think I've already spent enough time on this. I _can_ manually update the tree using `R` in the buffer. I might just stick to that. Its plently functional, just not very nice looking ;)

As for creating a new issue, I'll wait till the playground subcommand is stable (because looks like it isn't given ahlinc's previous comment) and see if it persists after that as well.

**Comment by ahlinc** [comment]
There are many opened issues that cover your case, I tested the Clojure grammar with tree-sitter CLI from the master branch and it works. It seems you need to update all pieces in your environment and use the latest emsdk version or a docker flag to compile grammar in the docker.

**Comment by heyvito** [comment]
Just got bitten by this as well. Another thread recommended Emscripten 2.0.17, which has no prebuilt binaries for arm64. 2.0.24 works, though! 

What you folks think about adding some notes regarding that version requirement? Perhaps in [lib/binding_web/README.md](https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/README.md)?

**Comment by sogaiu** [comment]
In the mean time, perhaps [this](https://github.com/sogaiu/ts-questions/blob/master/questions/which-version-of-emscripten-should-be-used-for-the-playground/README.md) might be of interest.

**Comment by heyvito** [comment]
Whoa! Great work there, @sogaiu! Will keep that link in my personal notes. Thank you so much!
