### ISSUE TITLE
External scanner is not serialized unless `scan()` returns `true`

### ISSUE THREAD

**Issue by ben-clayton** [tree-sitter/tree-sitter#2063]
Currently the external scanner state is only serialized if `scan` returns `true`. This makes modification of the state highly restrictive.

External scanners may wish to perform look-ahead computations while the scanner has more look-ahead context, without forcing the current token to resolve to an external token.

I propose adding a `bool force_serialize_state;` field to `TSLexer`, which can be set to `true` in `scan` to signal that the state should be serialized, even if `scan` returns `false`. This field would be set to `false` before each call to `scan`.

This makes the new behavior (and potentially costly) serialization opt-in.

I have a PR that prototypes this proposal which I will post shortly.

**Comment by ahelwer** [comment]
I return a zero-width token. It works pretty well and keeps the door from being opened to very weird bugs.

**Comment by ben-clayton** [comment]
Unfortunately in my case, I need to have the scanner fall back to the 'internal' token scanner while performing look-ahead computations. Attempts to return a placeholder external token adds substantial, unwanted complexity to my grammar.

**Comment by ahelwer** [comment]
So it's more about not wanting to sprinkle hidden zero-width external tokens throughout your grammar rather than lack of capability?

**Comment by maxbrunsfeld** [comment]
I left some comments on #2064. I don't think we can make that particular change, but open to discussing other options.

**Comment by ben-clayton** [comment]
Maybe - I haven't seriously considered adding hidden zero-width tokens in all the places I need to mutate state. There's a bunch of them.

Some background: I'm experimenting with adding template-argument-list vs less-than / greater-than disambiguation to WebGPU's shading language, WGSL.

The look-ahead needs to trigger on the `identifier` of an `identifier` `<` pair of tokens, and markup future `<` and `>` token pairs. Later the `<` and `>` tokens are either preserved (`scan` returns `false`), or replaced with external *template* tokens - either way the scanner state needs to mutate (we're popping from a queue created by the initial look-ahead scan).

My very rough scanner so far is: https://github.com/ben-clayton/gpuweb/blob/custom-template-scanner/wgsl/scanner.cc. This uses the new functionality in https://github.com/tree-sitter/tree-sitter/pull/2064, and works well.

Before resorting to adding the `force_serialize_state` field, I experimented with having the scanner return an external identifier, but this seemingly does not play nice with the grammar's [`word:`](https://tree-sitter.github.io/tree-sitter/creating-parsers#keyword-extraction) matching. The state mutation on the `<` and `>` tokens when `scan` returned `false`, was also an issue.

Sprinkling hidden zero-width external tokens throughout the grammar could work, but it would be messy, and is made much more tricky as the `grammar.js` is currently generated from the WGSL specification. I'm also fairly certain it wouldn't be accepted by the working group.

I'll take a look at your PR comments. Thanks.

**Comment by maxbrunsfeld** [comment]
Hmm, I don't understand why scanner needs to return false. I would have thought that you'd have two variants of the `<` token (one representing the operator, and one representing the template bracket), and the scanner would return one or the other based on its stack.

**Comment by ben-clayton** [comment]
For the `scan()` of `<` and `>` - yes, I could have two pairs of external tokens. I was just trying to introduce the new template tokens while preserving the existing less-than / greater-than grammar. Let's consider that aspect solved.

Having the look-ahead trigger on the `identifier` of an `identifier` `<` pair of tokens is more troublesome. Returning an external token for the `identifier` is messy, and AFAICT, there's no look-back that I can use to trigger on the `<` if it follows an `identifier` (possible feature request? 😄 ).

I guess I can try experimenting with the hidden zero-width external token approach tomorrow. Off the top my head, does this seem like a viable solution?

1. Change the grammar to optionally consume a new external `save_state_external_token` before each `identifier`

2. When `scan` triggers on the `identifier` of an `identifier` `<` pair:
   * Do the look-ahead computations.
   * Set a `skip_next_token` flag in the state. 
   * Return `true`, with `result_symbol` set to `save_state_external_token`. 

3. When `scan()` is called with `skip_next_token == true`, clear it and immediately return `false`. This preserves the `identifier` token as an 'internal' token.

Thank you for your help!

**Comment by maxbrunsfeld** [comment]
Could you explain why the scanner needs to start scanning at the start of the identifier, as opposed to at the angle bracket?

If you do need that, I think it could maybe be simplified. Could you have a zero-width token called `template_instantiation_start` that is required in the grammar before the identifier in a template instantiation? Then your scanner would always know whether to produce this token or not, based on whether a `template_instantionat_start` was in the set of valid lookaheads or not.

**Comment by ben-clayton** [comment]
> Could you explain why the scanner needs to start scanning at the start of the identifier, as opposed to at the angle bracket?

Because we want to constrain the template disambiguation to `identifier` `<`. Matching just off `<` is too general, and would consider more tokens as templates than we want.

I like your suggestion - yes, that's more elegant than what I had proposed.

For the zero-width `_template_instantiation_start` token - I presume `scan` will be called twice at the start of the identifier, and I still need to do some sort of `skip_next_token` trickery in the scanner?

Thank you again for your help!

**Comment by maxbrunsfeld** [comment]
From my understanding, you shouldn’t need to do the before-the-identifier thing, since the template bracket is only grammatically valid after an identifier anyway.

**Comment by ben-clayton** [comment]
Thank you for all your help here. I think I've got enough to go on for more experimentation.

I really appreciate the quick feedback and really thoughtful suggestions. Fantastic project and support!

Cheers,
Ben

**Comment by ahelwer** [comment]
Possibly related, not sure why I didn't think of this earlier but I had this idea for a "notify" function where the internal grammar notifies the external grammar it has seen a token, and it is thus able to modify its state: https://github.com/tree-sitter/tree-sitter/discussions/1428

**Comment by ben-clayton** [comment]
Just an update: I managed to get this going, using a zero-length token, but the end result is far more messy than I'd like.

General feedback:

Issues I hit:
* As discussed before, having the external scanner emit [`template_start`, `template_end`, `less-than`, `greater-than`] tokens instead of just [`template_start`, `template_end`] fixes the state serialization issue - however, because I'm now always externally scanning these tokens, I now have to deal with splitting of `<<`, `<=`, `<<=`, `>>`, `>=`, `>>=`. This added a bunch more complexity, which was unfortunate.
* `mark_end` needs to be called at the specific code point you want the token to end at. This clashed with lookahead disambiguation in interesting ways, forcing the use of a zero-length token so I could just call `mark_end` once at the start of `scan()`, then look-ahead to my heart's content. If I could have looked ahead, **then** picked the place to end the token, I believe I could have dropped the zero-length token.
* The placement of the zero-length token in the grammar needs to be carefully considered, as I found I was emitting the zero-length token based on the `valid_symbols` signal, but this then forced the grammar down a dead ends, resulting in errors. I had to move the zero-length token to somewhere that had uniform "control flow".
* Reconstructing the identifier scanner which makes use of the `XID_Start` and `XID_Continue` unicode sets is a substantial amount of the scanner's code. It would be great if there was some way to take advantage of tree-sitter's logic for these sets.

The combination of:
* No serialization unless you emit an external token.
* No look-back.
* No look-ahead then `mark_end` somewhere before the current token.

Caused a bunch of hoop jumping. Relaxing some of these could have dramatically reduced the complexity.

Thank you again for your help. You saved me hours / days.

**Comment by ahelwer** [comment]
For an alternative to look-back I've found it useful to include state like "has seen keyword".

**Comment by ben-clayton** [comment]
> For an alternative to look-back I've found it useful to include state like "has seen keyword".

But you still need to emit a token from the external scanner in order to remember that you've seen that keyword :-)

**Comment by ahelwer** [comment]
You do, I alternate between the zero-width token strategy and just moving that keyword into the external scanner.
