### ISSUE TITLE
Running concurrent instances of `tree-sitter parse` can hang on MacOS

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/tree-sitter#2068]
I've seen this manifest in my CI runs on macOS when I try to parse a whole bunch of files, and also reproduced this on my own macbook. Trying to run `tree-sitter parse` on multiple files concurrently can cause a hang. This might have something to do with compilation. Sometimes this resolves itself in a few minutes, sometimes it never seems to resolve. Here's a CI run where it happened: https://github.com/tlaplus-community/tree-sitter-tlaplus/actions/runs/4092649220/jobs/7057527393
Steps to reproduce:
1. Clone https://github.com/tlaplus-community/tree-sitter-tlaplus with `--recurse-submodules` parameter and run `npm install` in repo root
2. From bash in root of repo, run `./test/run-corpus.sh`; it runs this bash script:
```sh
specs=$(find "test/examples" -name "*.tla")
ncpu=$(command -v nproc > /dev/null && nproc || echo 1)
failures=$(echo "$specs" | xargs -P $ncpu -I {} ./node_modules/.bin/tree-sitter parse -q {})
if test -z "$failures"; then
  exit 0
else
  echo "$failures"
  exit 1
fi
```
Possibly related: https://github.com/tree-sitter/tree-sitter/issues/2041

**Comment by amaanq** [comment]
Probably fixed with the introduction of lockfiles to synchronize compilation.

**Comment by ahelwer** [comment]
I added some pretty clear steps to reproduce, do you think you could test it yourself before closing?

**Comment by amaanq** [comment]
Yeah I just don't always have access to a Mac, that's why. It works great on my Linux machine but I can test on a Mac pretty soon.

**Comment by amaanq** [comment]
Alright I can confirm on my Mac it's no longer an issue; after trying it more than 10 times while also removing the parser before running the script (making it recompile everytime)
