### ISSUE TITLE
RULE cannot be inlined

### ISSUE THREAD

**Issue by teto** [tree-sitter/tree-sitter#2078]
Apologies if it's a misunderstanding. 

I've tried to build a grammar with : 
```
  inline: $ => [ 
    $._whitespace,
    $.name
  ],
  
  rules: {

      name: (_) => /[A-Za-z0-9_-]+/,
}
```
then building with `tree-sitter generate  returned:  `name cannot be inlined `. Now if I rename name to _name that works. The doc doesn't seem to mention this: 
```
inline - an array of rule names that should be automatically removed from the grammar by replacing all of their usages with a copy of their definition. This is useful for rules that are used in multiple places but for which you don’t want to create syntax tree nodes at runtime.
```
it would be nice if there error message could be improved to "make the rule 'name' unnamed first before inlining" (if that's indeed the desired behavior).

**Comment by ahelwer** [comment]
I honestly just always use the underscore syntax instead of the inline array. I recall there being significant performance issues when using the inline array.
