### ISSUE TITLE
Query statement cannot match string.

### ISSUE THREAD

**Issue by wcy1997** [tree-sitter/tree-sitter#2079]
I want to capture a "string_literal" node and the value of this node is equal to "hello world". But the following syntax doesn't work well:
```
((binary_expression left:(_) operator:"<<" right:(string_literal) @0) (#eq? @0 "hello world"))
((binary_expression left:(_) operator:"<<" right:(string_literal) @0) (#eq? @0 "\"hello world\""))
```
I wonder how tree-sitter can match a string literal.

**Comment by amaanq** [comment]
Using `\"` to escape quotes works with the cli, if you're writing your own app and processing your own predicates then it's on you to handle this.
