### ISSUE TITLE
Code Folding is Unreliable with Tree Parson in Atom 1.32.0

### ISSUE THREAD

**Issue by JosephTLyons** [tree-sitter/tree-sitter#208]
I'm not sure if I should be reporting here or in the Atom Github issues, but I'm having issues with code folding with Tree Parser enabled (it is on by default in 1.32.0).

If I turn off Tree Parser, I have the options to fold code as usual, in all the expected places:

<img width="782" alt="screen shot 2018-10-25 at 6 17 05 am" src="https://user-images.githubusercontent.com/19867440/47493611-b52bd500-d81d-11e8-8b7c-48ed34d7af33.png">

After I turn on tree parser, many of the folding options disappear:

<img width="795" alt="screen shot 2018-10-25 at 6 17 40 am" src="https://user-images.githubusercontent.com/19867440/47493652-cb399580-d81d-11e8-85bd-4cabf89d540d.png">

Even more strange, some code folding goes out of the scope:

Before:

<img width="681" alt="screen shot 2018-10-25 at 6 19 17 am" src="https://user-images.githubusercontent.com/19867440/47493717-fcb26100-d81d-11e8-9e4a-e15855a31fe9.png">

After:

<img width="866" alt="screen shot 2018-10-25 at 6 19 24 am" src="https://user-images.githubusercontent.com/19867440/47493722-00de7e80-d81e-11e8-89af-bbbf9de6cdfc.png">

If you can tell, the code was folded past the for loop, outside of the method, and into the next function's signature.

Versions:

Atom 1.32.0
macOS Mojave 10.14

Language: C++

**Comment by maxbrunsfeld** [comment]
Oh no, that sounds very bad; my apologies.

It sounds like there's something in your code which our C++ parser is confused about. Are you able to share the file that you're working on? If so, that'd be very helpful in tracking this down.

**Comment by maxbrunsfeld** [comment]
One other possible source of problems: does it say `C` or `C++` in the status bar? Atom might be trying to parse your C++ code as C, in which case it's going to get confused.

**Comment by JosephTLyons** [comment]
Atom recognizes it as a C++ file, but the exact extension is `.cc`.  I don't currently have permission to share all of the code in the file i originally took screenshots of, so I'll try to reduce it to the code that I can show and that still (hopefully) demonstrates the issue).

**Comment by JosephTLyons** [comment]
This definitely has to do with the file extension `.cc`, if I simply resave the file from `.cc` to `.cpp`, all the code folding issues go away:

1) The scoped sections that are missing folding options now have the options to fold
2) The previous for loop that was collapsing code past the scope is now not collapsing code past its scope.

So, it seems that the rules defined for `.cc` files aren't working.  A `.cc` file is still a C++ file, so it should just be as simple as giving it the same rules as `.cpp`?

**Comment by JosephTLyons** [comment]
Scratch my previous statement, I think I'm seeing the error in `.cpp` files as well.  If you check this file, you'll notice the two if statement and for loop can't collapse when tree sitter is enabled:

```cpp
#include <iostream>

void extraFunction();

int main()
{
    std::cout << "Hello, World" << std::endl;

    if ((2 % 2) == 0)
        std::cout << "This is a test." << std::endl;

    std::cout << "This is a test." << std::endl;

    for (int i = 0; i < 10; i++)
        std::cout << "This is a test." << std::endl;

    return 0;
}

void extraFunction()
{
    // Do Nothing
}
```

[main.cpp.zip](https://github.com/tree-sitter/tree-sitter/files/2517256/main.cpp.zip)

**Comment by Ben3eeE** [comment]
@JosephTLyons You can send it in an email to atom@github.com include a reference to this issue.

**Comment by JosephTLyons** [comment]
Thanks @Ben3eeE , I sent an email with the code.

**Comment by maxbrunsfeld** [comment]
Hey @JosephTLyons. This parsing error has been fixed and will ship in the next Atom release, 1.32.1, which will probably go out this week. Thanks for your help addressing the issue.

**Comment by JosephTLyons** [comment]
Awesome, that was a very quick fix!  Can’t wait to check it out! :)

**Comment by JosephTLyons** [comment]
I realize that this isn’t probably the best place to put this, but I figure instead of wasting other people’s time opening a new issue, that this would be preferable.

1) For a given language, does tree sitter take precedence over the other grammar packages that use regex?

2) Does tree sitter open up any new possibilities (in the future) for identifying syntax errors?  Or is that sort of thing outside the scope of what it can detect?

**Comment by Ben3eeE** [comment]
> For a given language, does tree sitter take precedence over the other grammar packages that use regex?

Yes, but you can configure it https://github.com/gandm/language-babel/issues/510#issuecomment-433466949

**Comment by JosephTLyons** [comment]
@maxbrunsfeld I'm on Atom 1.32.1 and what I'm seeing now is that code that has a single line in the body without braces isn't collapsable.  Is that correct?  I think everything else correctly has the ability to fold now, but single body statements do not.  I know in the regex packages that single line bodies can fold, but at the same time, it doesn't make a ton of sense to me, so I could understand if it simply is a choice made to not fold single lines that don't have braces, but since I'm not sure, I'm reporting it here.

**Comment by Ben3eeE** [comment]
Yeah that's expected since it doesn't really make sense to fold one line.
