### ISSUE TITLE
Test for expected failures/invalid syntax?

### ISSUE THREAD

**Issue by ZedThree** [tree-sitter/tree-sitter#2082]
Apologies if I just missed this in the docs, but is there a way to write tests for snippets that are expected to fail? Is it just as simple as putting in `(ERROR)` nodes?

**Comment by sogaiu** [comment]
That's what I see being done -- I searched across some locally fetched repositories to check.

For example tree-sitter-go has [this](https://github.com/tree-sitter/tree-sitter-go/blob/64457ea6b73ef5422ed1687178d4545c3e91334a/corpus/declarations.txt#L369-L386):

```
func f[A int|string, B ~int, C ~int|~string]()
```

```
  (function_declaration
    (identifier)
    (type_parameter_list
      (parameter_declaration
        (identifier)
        (ERROR
          (identifier))
        (type_identifier))
      (parameter_declaration
        (identifier)
        (ERROR)
        (type_identifier))
      (parameter_declaration
        (identifier)
        (ERROR
          (identifier))
        (type_identifier)))
    (parameter_list)))
```

I think some grammar repositories also look for `MISSING`, though that appears to be less common.

As an example, [here is something](https://github.com/tree-sitter/tree-sitter-haskell/blob/3bdba07c7a8eec23f87fa59ce9eb2ea4823348b3/test/corpus/th.txt#L142-L150) from tree-sitter-haskell:
```
================================================================================
template haskell: error: incomplete quote
================================================================================

a = [a|

---

(haskell (function (variable) (quasiquote (quasiquote_start) (quoter) (quasiquote_bar) (MISSING "|]"))))
```

This is just from corpus testing though.

---

On a side note, IIUC, it's not uncommon to test against samples from the "real world".  I do this on a large collection of samples using `tree-sitter`' s `parse` subcommand and investigate when `ERROR` shows up, but I suppose it's possible to do something more sophisticated.  It's true that this is not the same as testing for expected issues, but I have found that it can identify patterns in failures (e.g. template files), which might then be adapted to live among one's corpus tests.

**Comment by ZedThree** [comment]
Thanks @sogaiu! That should be sufficient for my needs! It turns out the particular thing I wanted to test against (permutations) is explicitly not supported by tree-sitter anyway. Oh well!

**Comment by sogaiu** [comment]
Good luck in your endeavors!

Regarding having tests for `ERROR` and/or `MISSING`, I came across [this](https://github.com/tree-sitter/tree-sitter/issues/1993#issuecomment-1356296610) and thought it might be worth being aware of.  Specifically the comment after the first post (given the content of the first post).
