### ISSUE TITLE
Tree-Sitter Python 0.20.1 - parsing variable assignment with var tuple gives incorrect output

### ISSUE THREAD

**Issue by mischab** [tree-sitter/tree-sitter#2092]
Hey, 

there seems to be a small bug, when assigning tuples with vars to other variables. Please see the examples below.

Given this input:
<code>parser = Parser()
    parser.set_language(PY_LANGUAGE)
    tree = parser.parse(bytes("""  
    x=1,        
    g="test"
    """, "utf8"))
    print(tree.root_node.sexp())
</code>
output as expected:
`(module (expression_statement (assignment left: (identifier) right: (expression_list (integer)))) (expression_statement (assignment left: (identifier) right: (string))))`

Given this input:
  <code> tree = parser.parse(bytes("""
    x=test,
    g="test"
    """, "utf8"))
</code>

output incorrect:
`(module (expression_statement (assignment left: (identifier) right: (assignment left: (pattern_list (identifier) (identifier)) right: (string)))))`

**Comment by ahelwer** [comment]
You'll want to close this issue and open it against the tree-sitter-Python rep itself.

**Comment by mischab** [comment]
moving to tree-sitter-python rep
