### ISSUE TITLE
Enforce assumptions about grammar.json files?

### ISSUE THREAD

**Issue by Pat-Lafon** [tree-sitter/tree-sitter#2098]
https://github.com/tree-sitter/tree-sitter/blob/ca38c32d368ffd84e686b0cf41fef754044351a9/cli/loader/src/lib.rs#L305 seems to make certain assumptions about my `grammar.json` file(where it's located, in `src`, and that it is named `grammar.json`).

I have seemingly violated both of these assumptions when I called `tree-sitter generate ../bril-sitter/tree_sitter_bril.json`. Maybe this should be warned/errored on? My guess would be to do some sanitization/assumption checking at https://github.com/tree-sitter/tree-sitter/blob/c51896d32dcc11a38e41f36e3deb1a6a9c4f4b14/cli/loader/src/lib.rs#L123

I'm probably doing something else wrong, apologies if so.

**Comment by sogaiu** [comment]
I sometimes use a `grammar.json` built from a custom process that ends up in the root of the grammar / parser repository (so one level about `src` in a typical setup).

I haven't noticed any issues so far with the `generate` subcommand when applying it to this `grammar.json` file.  I typically invoke the subcommand from the root of the repository.

Haven't tried a file with a different name.

This is with relatively recent commits of the tree-sitter cli though -- I'm not sure about other versions.

**Comment by ahlinc** [comment]
@Pat-Lafon did you get some error output from `tree-sitter` CLI? I tested your case and it just works and fills a dir from where `tree-sitter generate` was called with all expected files.

**Comment by Pat-Lafon** [comment]
@sogaiu Yeah, I am using a grammar I generated from https://crates.io/crates/rust-sitter to play around with tree-sitter. So the parser to Rust structs is built is in one folder(which also generates the grammar file) and then I was using a different folder for the rest of the tree-sitter tooling(Inspired by pr's I've seen to create vs-code extensions with tree-sitter).

I've only been using these tools for the past few days, so I certainly could be making mistakes.

**Comment by Pat-Lafon** [comment]
Sorry I didn't clarify the error being on parse, not on generate.

**Comment by ahlinc** [comment]
> Sorry I didn't clarify the error being on parse, not on generate.

So what error did you see?

**Comment by Pat-Lafon** [comment]
```shell
Failed to load language for file name test.bril

Caused by:
    0: Failed to read grammar.json
    1: No such file or directory (os error 2)
```
