### ISSUE TITLE
[question] How atom prioritizes grammar selection? 

### ISSUE THREAD

**Issue by mgtitimoli** [tree-sitter/tree-sitter#211]
Hi there,

Given an issue I've recently experienced in **language-babel**, I was wondering if the reason why **language-typescript** and **language-javascript** have precedence over the former is because they both expose tree-sitter definitions while **language-babel** doesn't?

Is my assumption correct, or if it's not, would be mind giving me a bit of insight into the reason behind this.

Thanks!

**Comment by maxbrunsfeld** [comment]
I'm going to close this out since it's mainly an Atom issue (as opposed to an issue with the Tree-sitter library itself). Sorry for the confusion @mgtitimoli; it wasn't our intention to disrupt your workflow like this.

**Comment by mgtitimoli** [comment]
Thanks for your feedback @maxbrunsfeld.

Yep, it's what I supposed.

Thanks for the suggestions, I went with the 2nd.

I'm gonna open an issue in the **language-babel** repo to propose them to generate a tree-sitter config.

Thanks again for all your feedback @maxbrunsfeld, I really appreciated it!

**Comment by mgtitimoli** [comment]
One last question/suggestion @maxbrunsfeld, I know that currently by doing that change in config, you can overcome this issue, but I was wondering if there are any plans to provide a way to link a certain language package with a scope in case there is more than 1 that provides support of a certain grammar, as for me is not so clear the implications of that change in config that fixed this issue.

**Comment by maxbrunsfeld** [comment]
> I'm gonna open an issue in the language-babel repo to propose them to generate a tree-sitter config.

I think that the package won't be needed anymore, as soon as we add Tree-sitter parsers for GraphQL and CSS. Our built-in parsers are built to handle the whole messy, evolving JavaScript language. If you're interested, and can live w/o GraphQL and CSS highlighting for a day to try it out, it'd be great to get your feedback!

**Comment by mgtitimoli** [comment]
I'm really excited about atom giving a builtin support for all the stuff currently supported in language-babel, and for sure will switch to this setup as soon everything gets covered by default.

I tried it yesterday and some stuff was not correctly highlighted, mostly on the flow side.

**Comment by mgtitimoli** [comment]
To give you a better understanding of what I'm saying, have a look:

**language-typescript**
![image](https://user-images.githubusercontent.com/4404683/47580588-a16b9600-d925-11e8-871a-3124b6601ea5.png)

**language-javascript**
![image](https://user-images.githubusercontent.com/4404683/47580609-b0eadf00-d925-11e8-8207-de7ad4f8e131.png)

**language-babel**
![image](https://user-images.githubusercontent.com/4404683/47580628-bf38fb00-d925-11e8-8b24-3e137cc70f7f.png)

**Comment by maxbrunsfeld** [comment]
Yeah, for flow, I would expect it to use the `Flow JavaScript` grammar, show first. It's added via the `language-typescript` package currently because Flow and TypeScript have largely the same syntax, so we use a common parser for both. But the name of the package that contains the grammar shouldn't affect anything user-facing (as far as I'm aware).

That highlighting looks pretty complete to me, but it looks like a bug that the keyword `type` is getting highlighted as if it were an actual Type. Thanks for the detailed information, and I'll let you know when that problem is corrected.

**Comment by mgtitimoli** [comment]
Thanks @maxbrunsfeld, I hope I can get some time to help/contribute as well, meanwhile the only thing I can help you with is with testing, so if you ever need help checking something, just ping me.

**Comment by maxbrunsfeld** [comment]
Just revising my comment from above, the scope name for `language-babel` is `source.js.jsx`, not `source.jsx`:

```coffee
"*":
  core:
    customFileTypes:
      "source.js.jsx": [
        "js"
      ]
```

**Comment by mgtitimoli** [comment]
Nice @maxbrunsfeld, thanks.

Have you spotted the other difference? (function highlighting is different in **language-babel**)

**Comment by carloscuesta** [comment]
Thanks god I've found this issue! 🙏

**Comment by maxbrunsfeld** [comment]
1.32.1 is out, and a lot of the problems with the built-in Flow grammar have been fixed.

**Comment by edahlseng** [comment]
FYI, filed https://github.com/atom/language-javascript/issues/634 regarding the CSS grammar bug.
