### ISSUE TITLE
0.20.8 release did not get completed

### ISSUE THREAD

**Issue by chenrui333** [tree-sitter/tree-sitter#2125]
👋 it looks like the 0.20.8 release was not listed as latest release, just create this issue to confirm if that is intended latest release. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/125565

**Comment by clason** [comment]
I guess because of the failing tests, which just got fixed on master? (Note that the tag got moved to point to a new commit that passes the tests, so the PR probably needs adjusting.)

@ahlinc

**Comment by clason** [comment]
@ahlinc please don't move and especially not delete tags; this breaks all downstream consumers 😭 

(tags are cheap; just make a new 0.20.9 if 0.20.8 is not fit to release)

**Comment by ahlinc** [comment]
There were annoying issues with tests and all things were broken in upstream also like in downstreams.
I decided to temporary disable a part of flaky tests at all #2131 because they start to fail more often due a to upstream grammar changes. And part of TS release artifacts build on Appveyor :exploding_head: and I can't touch it to rerun a failing workflow.

If everything related to the release broken in the Tree-sitter repo then it's not a surprise that it should be broken on downstreams.

@clason Could you explain how downstreams work and why it's critical for them that failed tag isn't deleted or moved?
I didn't have thoughts to delete or to move a tag related to a completed release and I will not touch tags anymore. But if release was broken I'd like to don't leave a broken tag in the repo. How downstream monitor a release process in the TS repo and why they do any builds until here wouldn't be seen a completed (non draft) release?

**Comment by clason** [comment]
@ahlinc We have our own tests, which passed, and track individual commits during the development cycle to test features and fixes early. When a tag gets set, I prefer that to an un-tagged commit (but still prefer proper releases for our own release, of course).

If a tag is referred to in our manifest but suddenly changes or disappears, this then retroactively breaks previously working commits, in particular ALL our CI.

(TL;DR: Tags are supposed to be light-weight but immutable; if they're not fit for release, just don't release them, and people will draw the right conclusion. In this sense they're not much different than any commit on master; they just have a more human-friendly name.)

**Comment by ahlinc** [comment]
@clason could you give me links where I can see all your CI workflows? May be I'll find useful parts to improve workflow in this repo.

I have a plan how to improve all CI / tests / versioning and releasing workflows here in TS but there are hard tasks like flaky tests that are roadblocks to resolve all things.

Currently TS releasing tied to tags, so tags appear first in the repo what doesn't mean that release will be completed by the CI.
I'd like to don't manually manage tags at all and see tags managed by CI and as a result of a completed release workflow that would be triggered by a commit with a special message.

**Comment by clason** [comment]
> @clason could you give me links where I can see all your CI workflows? May be I'll find useful parts to improve workflow in this repo.

Sure: https://github.com/neovim/neovim/tree/master/.github (but you need a @dundargoc to make sense of it...)

> Currently TS releasing tied to tags, so tags appear first in the repo what doesn't mean that release will be completed by the CI.

Of course; the responsibility of using them (or not) is with us; the only guarantee I expect is that they don't suddenly vanish again ;) 

> I'd like to don't manually manage tags at all and see tags managed by CI and as a result of a completed release workflow that would be triggered by a commit with a special message.

You might be interested in https://github.com/google-github-actions/release-please-action then; you can see an example here: https://github.com/folke/lazy.nvim/pull/653

**Comment by ahlinc** [comment]
@maxbrunsfeld there is an issue with Appveyor and without it it's not possible to create a Windows x86 image to publish on the _Releases_ page.

**Comment by ahlinc** [comment]
It fails like this https://ci.appveyor.com/project/maxbrunsfeld/tree-sitter/builds/46511238/job/990qvbhssnfomgbl

**Comment by ahlinc** [comment]
@maxbrunsfeld I'd suggest to skip the v0.20.8 release and make a v0.20.9 release on a current fresh master if you know how to make manually all Release artifacts for Windows files. And please bump CLI version to 0.20.9.

**Comment by clason** [comment]
Now that you've already burninated the 0.20.8 tag, you might as well release v0.20.8 -- otherwise this was all in vain ;)

**Comment by chenrui333** [comment]
Agree, I think we can just skip 0.20.8 and go for 0.20.9 release.

**Comment by carlocab** [comment]
> @ahlinc please don't move and especially not delete tags; this breaks all downstream consumers 😭
> 
> (tags are cheap; just make a new 0.20.9 if 0.20.8 is not fit to release)

Chiming in to re-emphasise this. The Git docs even have some rather strong words about re-tagging: https://git-scm.com/docs/git-tag#_on_re_tagging

**Comment by ahlinc** [comment]
> The Git docs even have some rather strong words about re-tagging

Thanks about the docs' note, I use git from its early days when it doesn't have such strong words :smile:. As I said before version tags shouldn't be managed manually and release triggering process _shouldn't be based on a version tag pushing_ (while it is suggested in different places). In any way we'll move away from this approach and I hope this happens very soon.

**Comment by ahlinc** [comment]
First step to make a releasing process reliable are done:
- [x] https://github.com/tree-sitter/tree-sitter/pull/2135

The next and the last step is to drop unreliable AppVeyor CI that from time to time doesn't able to download crates:
- [ ] **Drop AppVeyor and fully migrate on Github CI for Windows builds.**

I hope to finish with above today and forget about all this CI nightmare.

**Comment by clason** [comment]
@ahlinc friendly ping about the release?

**Comment by ahlinc** [comment]
@clason I've done with building / testing of all components for all required targets and need to finish with a release logic. I'll try to finish with all of this in a couple of days.

**Comment by clason** [comment]
Thank you! If there's a release this week, that would be really great for us at Neovim!
