### ISSUE TITLE
Add SVG version of the logo

### ISSUE THREAD

**Issue by zimmski** [tree-sitter/tree-sitter#2139]
The TreeSitter logo is currently only available as a PNG https://github.com/tree-sitter/tree-sitter/tree/master/docs/assets/images. It would be great to have the logo as an SVG, so one can do publicity work with a higher quality. The website would also benefit when viewers have a higher resolution. Whoever create the logo has hopefully still the original file around :-)

To give an example: we are in the process of announcing that we have migrated to TreeSitter by publishing a blog post. I just wanted to upload a basic banner graphics for that article. Now i have a pixelated logo because i cannot easily scale it, and the file size is huge. Having an SVG can solve these problems.

**Comment by amaanq** [comment]
I don't think we have one unfortunately, you'll have to make do with the pngs :grimacing: sorry
