### ISSUE TITLE
takes too long time to parse json

### ISSUE THREAD

**Issue by baoti** [tree-sitter/tree-sitter#2144]
see 
https://github.com/tree-sitter/tree-sitter-json/issues/31

**Comment by ahelwer** [comment]
Please close this issue and keep discussion on the relevant grammar. Grammars for specific languages are usually community-driven so if an issue is impacting you it is likely you will have to either fix it yourself or use interpersonal skills to convince someone they should spend time fixing it for you.

**Comment by ahlinc** [comment]
@baoti Tree-sitter has a timeout facility to avoid catastrophic CPU bound locking on a bad input. I think in a production use cases Tree-sitters' parser should been always used with a set timeout and I'm not sure that this needs to be fixed somehow in Tree-sitters' core because for many algorithms it's possible to craft an input that would trigger a worse performance case.

**Comment by baoti** [comment]
@ahlinc I had this problem when use Helix and Lapce. When I open a 500KB json file, the program freeze 50 seconds.
But the vscode takes only 1 seconds in this case.

**Comment by sogaiu** [comment]
May be it's worth asking some Helix and Lapce folks about whether they are using the timeout feature.  Perhaps it's [this](https://github.com/tree-sitter/tree-sitter/blob/1b1c3974f789a9bfaa31f493e6eaa212f13bdfb9/lib/src/parser.c#L1836-L1838).

**Comment by ahlinc** [comment]
> But the vscode takes only 1 seconds in this case.

That's  may be because VSCode don't use real parsing and uses regex based highlighting.

**Comment by ahlinc** [comment]
Overall I agree that Tree-sitter may be improved and it may have an additional mode where on some threshold of errors frequency it would decline to try to do errors recovering and does simple tokenization as it's possible with shortest tokens, it would be sufficient for base highlighting and would improve performance for invalid inputs.

**Comment by ahelwer** [comment]
Possibly related: fuzzing on the tlaplus grammar found an input where error recovery seemingly enters an infinite loop until OOM: https://github.com/tree-sitter/tree-sitter/discussions/2073

**Comment by ObserverOfTime** [comment]
This doesn't seem to happen anymore.
