### ISSUE TITLE
Web-Tree-Sitter: Parsing text with a previous instance of the tree causes offsets to not change

### ISSUE THREAD

**Issue by Coolroo** [tree-sitter/tree-sitter#2145]
Hi there. I'm working with tree-sitter and when I call parse and provide an old tree, it does not update the offsets of nodes.

I am extracting text from the nodes so this is causing issues as the text is changing, but the offsets are not so the text is not being accurately represented

Steps to reproduce:
```
newTree =  parser.parse(text, tree) as Tree;
```
comparing nodes in newTree and tree show that any node that is placed after where additional text was inserted/deleted has offsets that do not accurately reflect the actual text content

**Comment by Coolroo** [comment]
> To be clear, are you expecting tree to be updated in place? I think only newTree is expected to have correct offsets.

No I am not expecting in place changes, when checking newTree the offsets are wrong

**Comment by ahlinc** [comment]
@Coolroo could you provide a real reproducible code example instead of a one line of a code?

**Comment by Coolroo** [comment]
> @Coolroo could you provide a real reproducible code example instead of a one line of a code?

For sure! For reference here is the input file: 
```java
public class test {

    
    /**
     * The testjava function tests the java implementation of the function.
     
     *
     *
     * @return A void
     *
     * @docauthor Trelent
     */
    public testjava(){

    }

    /*
    * this is a docstring
    */
    public void test(){

    }

    public void testt(){
        
    }

}
```

pass it into the function below, along with the text to the file above

The setup below can be used to do this. Load the language in loadLanguage, and parse the file contents using parseText
```ts
const parser = new Parser();
let loadedLanguages: any = {};

export const loadLanguage = (langName: string, path: string) => {
  loadedLanguages[langName] = parser.Language.load(path);
}

export const parseText = async (
  text: string,
  langName: string,
  tree: Tree | undefined = undefined
) => {
  // Set the parser language
  parser.setLanguage(loadedLanguages[langName]);

  //Parse the document
  if(tree){
    return parser.parse(text, tree) as Tree;
  }
  return parser.parse(text) as Tree;
};
```

Now below is the issue: If you add a character anywhere in the file, and re-parse with the old tree, the offsets will not change, but the node text does.

An example of what I mean is if you rename the function `test` to `testing`, all nodes whose offsets are below the insertion point will not have updated offsets.

this means that if I capture the name of the `testt` function, the text content in the new syntax node will be ' test' instead of 'testt'

**Comment by savetheclocktower** [comment]
Are you editing the old tree with each change [as described here](https://tree-sitter.github.io/tree-sitter/using-parsers#editing)?

**Comment by Coolroo** [comment]
> Are you editing the old tree with each change [as described here](https://tree-sitter.github.io/tree-sitter/using-parsers#editing)?

That was exactly the problem, I'll close this. Thanks so much for your help
