### ISSUE TITLE
V8 torque Support

### ISSUE THREAD

**Issue by zdaiot** [tree-sitter/tree-sitter#2147]
First of all, thank you for your work. I need to parse the syntax of torque recently. Can you provide support for the language? 
The link to this syntax is: https://v8.dev/docs/torque. 
I tried to parse using the backend of js and ts, but failed.

**Comment by ahelwer** [comment]
Hello, parsers are developed on a community basis. If somebody wants a parser for a language they are generally the one who develops it.

**Comment by sogaiu** [comment]
Apart from the tree-sitter "official" grammars, it seems most others were written by interested parties that are / were not officially connected to the tree-sitter project.  Looking at [this list](https://github.com/sogaiu/ts-questions/blob/master/ts-grammar-repositories.txt), I think it's clear that most are not living under the tree-sitter organization.

May be there is someone interested in putting something together.

According to the V8 Torque docs, it looks like there is a sort of specification-in-code [here](https://source.chromium.org/chromium/chromium/src/+/main:v8/src/torque/torque-parser.cc?q=TorqueGrammar::TorqueGrammar).

**Comment by zdaiot** [comment]
Thanks a lot
