### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [tree-sitter/tree-sitter#215]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [ts_tree_new](https://github.com/tree-sitter/tree-sitter/blob/af01846fd7a665ffbcfe96d7700e276e02133d6c/src/runtime/tree.c#L10)
- [realloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/realloc.html "Memory reallocation") ⇒ [ts_lexer_set_included_ranges](https://github.com/tree-sitter/tree-sitter/blob/dadd100fc3971e8d9c9b58dc5104dcef591e551b/src/runtime/lexer.c#L278)

**Comment by maxbrunsfeld** [comment]
I used to try and handle out-of-memory errors and return meaningful error codes, but [I removed it](https://github.com/tree-sitter/tree-sitter/pull/43), in favor of simply aborting if malloc fails. The reasons I did this are:

* `malloc` never returns null on macOS or Linux, in the default system configuration. Instead, it "overcommits" and returns memory that will cause errors to access. AFAICT, windows is the only 
 major platform where malloc returns null on OOM by default.
* Handling OOM errors gracefully adds a lot of complexity.
* Aborting on OOM matches the behavior of a lot of other systems.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers "Do not dereference null pointers.")?

**Comment by maxbrunsfeld** [comment]
We don't dereference null pointers. If `malloc` returns `NULL`, [we check that condition, and abort](https://github.com/tree-sitter/tree-sitter/blob/master/src/runtime/alloc.h#L49-L54). Is that what you're asking about?

**Comment by elfring** [comment]
Will an other program error code be more appropriate?
