### ISSUE TITLE
Can this be used to tokenize code?

### ISSUE THREAD

**Issue by tonijarjour** [tree-sitter/tree-sitter#2150]
Hi, I'd like a tool that will tokenize code and describe it based on its syntax. Can tree-sitter do this? If not, can you suggest a tool that can?
Example:
```json
"output" : [{ "token": "let", "type": "keyword" },
{ "token": "myVar", "type": "name" },
{ "token": "=", "type": "operator" },
{ "token": "\"Hello, World\"", "type": "string" },
{ "token": ";", "type": "punctuation" },
{ "token": "\n", "type": "whitespace" }]
```

**Comment by ahelwer** [comment]
Yes, the parse tree is represented as a tree but you can walk it in order to flatten it.
