### ISSUE TITLE
[help] How to uniquely identify a node's syntax?

### ISSUE THREAD

**Issue by tonijarjour** [tree-sitter/tree-sitter#2174]
Here is my [code](https://github.com/tonijarjour/apricot/blob/main/src/main.rs) so far. 

In short I am flattening the tree and giving each node a kind of `parent_kind_node_kind`.
This yields `variable_declarator_identifier` for both a variable name and an arrow function definition name.
```js
// sayHello is variable_declarator_identifier
const sayHello = () => {}

// name is variable_declarator_identifier
const name = "jolyne"
```

So I'd like to know how to tell them apart since in my text editor (nvim) `sayHello` is colored differently from `name`

**Comment by ahelwer** [comment]
I don't understand what you're trying to do, could you please expand your explanation?

**Comment by tonijarjour** [comment]
I'm trying to make a syntax highlighter for my website. I need to generate an output where each part of the code is surrounded in a `span` and given a class/style with its syntax string.

So I thought I could use the `kind` method that the rust bindings provide to function as the syntax names. Using only the node's kind wasn't good enough since for example a lot of things are called `identifier`.
So I tried to also include the parent's kind, but that also doesn't uniquely describe the syntax.
[This](https://github.com/tonijarjour/apricot/blob/main/src/main.rs#L118) is where this is happening.
```rs
        structure.push(Fragment {
            start: cursor.node().start_byte(),
            end: cursor.node().end_byte(),
            kind: format!("{}_{}", parent_kind, kind),
        });
```
Once I have all the nodes flattened into the structure vector, I loop over it and output each fragment with a span and each span is given a styling with the combined parent and node kinds. See [here.](https://github.com/tonijarjour/apricot/blob/main/src/main.rs#L74)
```rs
                print!(
                    "{}<span style=\"color: --ts-{}\">{:>spaces$}</span>",
                    new_lines, fragment.kind, text
                );
```

**Comment by ahelwer** [comment]
Have you looked at how other projects implement highlighting with tree-sitter using queries?

**Comment by tonijarjour** [comment]
Alright Im trying to use `HtmlRenderer` but I'm not sure what the closure parameter in `render` is supposed to do. I tried looking at a project that used it but couldn't figure out how to implement it.
https://github.com/tonijarjour/apricot/blob/main/src/main.rs#L52

**Comment by tonijarjour** [comment]
I got it. Thanks anyway.
