### ISSUE TITLE
C Syntax Tree needs to be Updated

### ISSUE THREAD

**Issue by Raghva89** [tree-sitter/tree-sitter#2193]
C Language syntax tree hierarchy should be modified for the functions which returns pointer. 
C function definition with pointer type nodes are expected to be part of the "type: primitive_type". But in current implementation pointer declarator out of the primitive type node as shown in the example below.

Because of this node entry which is out of the primitive type **common query to list all the function definitions is not able to identify it as a function definition**.

### example function definition:
`const char ** fn_returns_pointer()
{
}`

### parsed AST:
```
translation_unit [0, 0] - [3, 0]
  function_definition [0, 0] - [2, 1]
    type_qualifier [0, 0] - [0, 5]
    type: primitive_type [0, 6] - [0, 10]
    declarator: pointer_declarator [0, 11] - [0, 34] ---------------------
      declarator: pointer_declarator [0, 12] - [0, 34]                   | these pointer_declarators are not expected to be here
        declarator: function_declarator [0, 14] - [0, 34]-----------------
          declarator: identifier [0, 14] - [0, 32]
          parameters: parameter_list [0, 32] - [0, 34]
    body: compound_statement [1, 0] - [2, 1]
```

**Comment by sogaiu** [comment]
May be it would be good to report this at the [tree-sitter-c repository](https://github.com/tree-sitter/tree-sitter-c)?

**Comment by Raghva89** [comment]
ohh yeah my bad, I will report in that repository.
thanks.
