### ISSUE TITLE
TreeCursor.currentNode is a property in Node but a function in the browser

### ISSUE THREAD

**Issue by verhovsky** [tree-sitter/tree-sitter#2195]
At least in the types. Compare Node:

https://github.com/tree-sitter/node-tree-sitter/blob/16f7319c993e07a4b28afad354b80624237c6660/tree-sitter.d.ts#L107

With binding_web:

https://github.com/tree-sitter/tree-sitter/blob/c6d663f3936aea4fb9a12e093fbaa25e762fa902/lib/binding_web/tree-sitter-web.d.ts#L118

**Comment by ahlinc** [comment]
@verhovsky Yeah it's a know feature / issue that some things looks slightly different on different (platforms / bindings). I plan someday to fix this differences as mush as possible for a future [`v1.0.0`](https://github.com/tree-sitter/tree-sitter/issues/930) release.

**Comment by verhovsky** [comment]
I was just thinking about this the other day, I think it makes sense to put node-tree-sitter in the main tree-sitter repo as `binding_node` and have them share an index.d.ts file to make sure it's always identical. And today I run into an issue from them not being the same :)

**Comment by ahlinc** [comment]
I think Max didn't do so because code in the [node-tree-sitter](https://github.com/tree-sitter/node-tree-sitter) repo is only Node specific and in the main repo there is only a code that mostly portable and related to a parser core and tooling for it.

**Comment by ahlinc** [comment]
@verhovsky I saw you made many PRs for the [node-tree-sitter](https://github.com/tree-sitter/node-tree-sitter) repo, I can help to merge them and actualize the Node binding. But it would be good to sync on this process somehow. Could you join a [Discord](https://github.com/tree-sitter/tree-sitter/discussions/2027) server or email me if you prefer?
