### ISSUE TITLE
[Community] Need a list of `Node.js` reports on various architectures

### ISSUE THREAD

**Issue by ahlinc** [tree-sitter/tree-sitter#2196]
This is continuation for https://github.com/tree-sitter/tree-sitter/issues/1366#issuecomment-1502248428

To improve Tree-sitter CLI installation process it's required to know what `node.js` reports on different machine architectures.

Please run the bellow snippet on your machine and post a report as a comment bellow if there is no a report for the same architecture.
```sh
uname -p; uname -i; uname -srvmo; node -e 'const os = require("os"); for (var fn of ["type", "machine", "endianness", "platform", "arch"]) { console.log(fn, eval(`os.${fn} && os.${fn}()`)) }; console.log("node", process.version);'
```

On **Windows** in non **WSL** environment use only a `node.js` call in **CMD**:
```sh
node -e "const os = require('os'); for (var fn of ['type', 'machine', 'endianness', 'platform', 'arch']) { console.log(fn, eval(`os.${fn} && os.${fn}()`)) }; console.log('node', process.version);"
```

---
## Very wanted
ARM, MIPS, Big Endian arches and other targeted by triples from tables: [1](https://github.com/cross-rs/cross#supported-targets), [2](https://github.com/cross-rs/cross-toolchains#targets).

---
**Edit:** Preliminary collected results based on posted info.

## Results
| Description                                                                                | Platform | Arch      | Machine   | Endianness | Node version |
| ---                                                                                                 | ---             | ---          | ---               | ---                  | ---                     |
| [Linux (amd64)](#issuecomment-1502364791)                  | linux        | x64       | x86_64       | LE                 | v18.15.0         |
| [Android SDM845 (arm64)](#issuecomment-1502365840) | android | arm64 | aarch64     | LE                 | v19.6.1           |
| [macOS 13.4 (amd64)](#issuecomment-1502375197)       | darwin    | x64        | x86_64       | LE                 | v19.8.1          |
| [macOS 22.3 (amd64)](#issuecomment-1502390584)       | darwin    | x64      | _undefined_ | LE                | v18.3.0          |
| [macOS 13.3 (M1)](#issuecomment-1503087736)              | darwin    | arm64   | arm64       | LE                 | v19.8.1          |
| [Win WSL (amd64)](#issuecomment-1502412903)             | linux        | x64       | x86_64        | LE                 | v18.15.0        |
| [Win 11 (amd64)](#issuecomment-1502426437)                 | win32      | x64      | _undefined_ | LE               | v16.13.0        |
| [armel (chroot arm64)](#issuecomment-1502465386)       | linux        | arm      | armv8l       | LE                 | v18.13.0        |
| [armhf](#issuecomment-1502465386)                                  | linux        | arm      | armv7l       | LE                 | v18.13.0        |
| [riscv64](#issuecomment-1502465386)                                 | linux       | riscv64 | riscv64       | LE                 | v18.13.0        |
| [mipsel (chroot mips64el)](#issuecomment-1502465386) | linux        | mipsel | mips          | LE                 | v18.13.0        |
| [mips64el](#issuecomment-1502465386)                             | linux    | mips64el | mips64     | LE                 | v18.13.0        |
| [ppc64](#issuecomment-1502465386)                                 | linux         | ppc64   | ppc64       | **BE**        | v18.13.0        |
| [ppc64el](#issuecomment-1502465386)                              | linux         | ppc64   | ppc64le    | LE                | v18.13.0        |
| [s390x](#issuecomment-1502465386)                                 | linux         | s390x   | s390x         | **BE**       | v18.13.0        |
| [RPi 3 (64-bit)](1366#issuecomment-1502935800)            | linux         | arm64  | **N/A** _(aarch64)_ | LE| v12.x.x        |
| [Debian (Chromebook Duet)](#issuecomment-1509884456) | linux  | arm64  | aarch64     | LE               | v18.16.0         |
**Notes:**
- On _RPi 3_ and in other cases where machine unknown _node.js_ may call `uname -m` to extract machine name.

**Additional useful info:**
- https://blog.cloudflare.com/porting-our-software-to-arm64/
- https://github.com/golang/go/wiki/GoArm

**Comment by ahlinc** [comment]
Termux on Android _(Samsung Galaxy Note 9)_:
```
Linux 4.9.186-22990479 #1 SMP PREEMPT Fri Jul 22 08:26:36 KST 2022 aarch64 unknown unknown Android
type Linux
machine aarch64
endianness LE
platform android
arch arm64
```

**Comment by clason** [comment]
macOS 13.4 (Intel):
```
uname: illegal option -- i
usage: uname [-amnoprsv]
type Darwin
machine x86_64
endianness LE
platform darwin
arch x64
```

**Comment by ahlinc** [comment]
MacOS 22.3 (Intel)
```
i386 unknown
Darwin 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64 Darwin
type Darwin
machine undefined
endianness LE
platform darwin
arch x64
```

**Comment by dundargoc** [comment]
WSL - Ubuntu 22.04 LTS

```
x86_64 x86_64
Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux
type Linux
machine x86_64
endianness LE
platform linux
arch x64
node v18.15.0
```

**Comment by ahlinc** [comment]
Window 11 (Intel)
```
type Windows_NT
machine undefined
endianness LE
platform win32
arch x64
node v16.13.0
```

**Comment by ahlinc** [comment]
@dundargoc on Windows please use CMD and a second snippet from updated description. Thank you for attention and the info!

**Comment by jamessan** [comment]
Here's everything from the Debian Linux porterboxes I have access to which also can install both nodejs and rust.

<details><summary>armel (chroot on an arm64 system)</summary>

```
unknown unknown
Linux 5.10.0-21-arm64 #1 SMP Debian 5.10.162-1 (2023-01-21) armv8l GNU/Linux
type Linux
machine armv8l
endianness LE
platform linux
arch arm
node v18.13.0
```
</details>

<details><summary>armhf</summary>

```
unknown unknown
Linux 4.19.0-21-armmp-lpae #1 SMP Debian 4.19.249-2 (2022-06-30) armv7l GNU/Linux
type Linux
machine armv7l
endianness LE
platform linux
arch arm
node v18.13.0
```
</details>

<details>
<summary>riscv64</summary>

```
unknown unknown
Linux 6.1.0-4-riscv64 #1 SMP Debian 6.1.11-1 (2023-02-09) riscv64 GNU/Linux
type Linux
machine riscv64
endianness LE
platform linux
arch riscv64
node v18.13.0
```
</details>

<details>
<summary>mipsel</summary>

```
unknown unknown
Linux 4.19.0-21-octeon #1 SMP Debian 4.19.249-2 (2022-06-30) mips GNU/Linux
type Linux
machine mips
endianness LE
platform linux
arch mipsel
node v18.13.0
```
</details>

<details>
<summary>ppc64</summary>

```
unknown unknown
Linux 6.1.0-7-powerpc64 #1 SMP Debian 6.1.20-1 (2023-03-19) ppc64 GNU/Linux
type Linux
machine ppc64
endianness BE
platform linux
arch ppc64
node v18.13.0
```
</details>

<details>
<summary>ppc64el</summary>

```
unknown unknown
Linux 5.10.0-21-powerpc64le #1 SMP Debian 5.10.162-1 (2023-01-21) ppc64le GNU/Linux
type Linux
machine ppc64le
endianness LE
platform linux
arch ppc64
node v18.13.0
```
</details>

<details>
<summary>s390x</summary>

```
unknown unknown
Linux 5.10.0-21-s390x #1 SMP Debian 5.10.162-1 (2023-01-21) s390x GNU/Linux
type Linux
machine s390x
endianness BE
platform linux
arch s390x
node v18.13.0
```
</details>

**Comment by ahlinc** [comment]
@jamessan thank you very much for such a lot info! It definitely will help to add more compilation targets.

As I thought a combination of `platform` / `arch` may be not enough and for s390x the difference is only in `endianness`.

**Comment by clason** [comment]
macOS 13.3 (M1):

```
uname: illegal option -- i
usage: uname [-amnoprsv]
Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64
type Darwin
machine arm64
endianness LE
platform darwin
arch arm64
node v19.8.1
```

**Comment by unpWn4bL3** [comment]
Debian bullseye on aarch64(Chrombook Duet):
```
unknown
unknown
Linux 5.15.103-17395-g0cac768bd8ce #1 SMP PREEMPT Sat Apr 1 18:57:39 PDT 2023 aarch64 GNU/Linux
type Linux
machine aarch64
endianness LE
platform linux
arch arm64
node v18.16.0
```

**Comment by KSST88** [comment]
> これは#1366の続きです[(コメント)](https://github.com/tree-sitter/tree-sitter/issues/1366#issuecomment-1502248428)
> 
> ツリーシッターCLIのインストールプロセスを改善するには、`node.js`がさまざまなマシンアーキテクチャで何を報告しているかを知る必要があります。
> 
> 同じアーキテクチャのレポートがない場合は、マシンでベロースニペットを実行し、コメントとしてレポートを投稿してください。
> 
> ```shell
> uname -p; uname -i; uname -srvmo; node -e 'const os = require("os"); for (var fn of ["type", "machine", "endianness", "platform", "arch"]) { console.log(fn, eval(`os.${fn} && os.${fn}()`)) }; console.log("node", process.version);'
> ```
> 
> **WSL**以外の環境の**Windows**では、**CMD**で`node.js`呼び出しのみを使用します。
> 
> ```shell
> node -e "const os = require('os'); for (var fn of ['type', 'machine', 'endianness', 'platform', 'arch']) { console.log(fn, eval(`os.${fn} && os.${fn}()`)) }; console.log('node', process.version);"
> ```
> 
> ## とても欲しかった
> ARM、MIPS、ビッグエンディアンアーチ、その他は、テーブルからトリプルがターゲットにされています。1、2。
> 
> **編集: **投稿された情報に基づいて予備的に収集された結果。
> 
> ## 結果
> 説明	プラットフォーム	アーチ	機械	エンディアンネス	ノードバージョン
> [Linux (amd64)](#issuecomment-1502364791)	リナックス	x64	x86_64	LE	v18.15.0です
> [アンドロイドSDM845(arm64)](#issuecomment-1502365840)	アンドロイド	アーム64	アーチ64	LE	v19.6.1
> [macOS 13.4 (amd64)](#issuecomment-1502375197)	ダーウィン	x64	x86_64	LE	v19.8.1です
> [macOS 22.3 (amd64)](#issuecomment-1502390584)	ダーウィン	x64	_未定義_	LE	v18.3.0
> [macOS 13.3 (M1)](#issuecomment-1503087736)	ダーウィン	アーム64	アーム64	LE	v19.8.1です
> [WSLに勝つ(amd64)](#issuecomment-1502412903)	リナックス	x64	x86_64	LE	v18.15.0です
> [ウィン11(amd64)](#issuecomment-1502426437)	ウィン32	x64	_未定義_	LE	v16.13.0
> [アーメル(chroot arm64)](#issuecomment-1502465386)	リナックス	腕	アームv8l	LE	v18.13.0
> [armhf](#issuecomment-1502465386)	リナックス	腕	アームv7l	LE	v18.13.0
> [riscv64](#issuecomment-1502465386)	リナックス	riscv64	riscv64	LE	v18.13.0
> [ミプセル(chroot mips64el)](#issuecomment-1502465386)	リナックス	ミプセル	ミップス	LE	v18.13.0
> [ミップス64エル](#issuecomment-1502465386)	リナックス	ミップス64エル	ミップス64	LE	v18.13.0
> [ppc64です](#issuecomment-1502465386)	リナックス	ppc64です	ppc64です	**BE**	v18.13.0
> [ppc64el](#issuecomment-1502465386)	リナックス	ppc64です	ppc64le	LE	v18.13.0
> [s390x](#issuecomment-1502465386)	リナックス	s390x	s390x	**BE**	v18.13.0
> [RPi 3（64ビット）](1366#issuecomment-1502935800)	リナックス	アーム64	**N/A**_(aarch64)_	LE	v12.x.x
> [Debian (Chromebook Duet)](#issuecomment-1509884456)	リナックス	アーム64	アーチ64	LE	v18.16.0
> **ノート：**					
> * _RPi 3_やその他のケースでは、マシンunknownnode_.js_が`uname -m`を呼び出すとマシン名を抽出する可能性があります。
> 
> **その他の有用な情報:**
> 
> * https://blog.cloudflare.com/porting-our-software-to-arm64/
> * https://github.com/golang/go/wiki/GoArm

**Comment by ahlinc** [comment]
Thank you very much for everyone who participated in this community request! :heart: 
Provided information is pretty enough for further improvements so I close this issue.
