### ISSUE TITLE
Citing tree-sitter

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#2204]
Is there any publication on tree-sitter that one can cite in papers, or anything else that you would like one to reference except GitHub tree-sitter url?

**Comment by ahelwer** [comment]
Yes, see the DOI sticker at the top of the repo's README.md.

**Comment by ahlinc** [comment]
Try to Google through a [Github blog](https://www.google.com/search?q=site:https://github.blog/+tree-sitter).
And look for related posts on a @dcreager's blog https://dcreager.net/archive/
