### ISSUE TITLE
yarn having error install tree-sitter-cli on aarch64 due to released package name

### ISSUE THREAD

**Issue by unpWn4bL3** [tree-sitter/tree-sitter#2208]
When installing tree-sitter-cli on aarch64 device (like a Chromebook Duet), yarn tries to fetch package which ends name with "arm64". However in release tag package name ends with "aarch64", which cause an installation error. 
Can this be fixed by publishing a correctly-named package?
![Screenshot 2023-04-15 9 27 34 AM](https://user-images.githubusercontent.com/13286957/232176856-95755572-2e7a-4eea-a053-3d5ca871c406.png)

**Comment by ahlinc** [comment]
Thank you for the report! I've updated the file.
It was the first release that provides support for additional platforms on ARM cpus and I didn't thought that that would become useful so quickly :slightly_smiling_face:

@unpWn4bL3  could I ask you to report an info about your platform in the #2196 issue, it would be also helpful.

**Comment by unpWn4bL3** [comment]
@ahlinc Thanks for help! I've upload platform information in #2196 :)
