### ISSUE TITLE
tree-sitter-latex

### ISSUE THREAD

**Issue by Astrantia** [tree-sitter/tree-sitter#221]
Any plans to add latex to existing parsers?

**Comment by maxbrunsfeld** [comment]
I would love to see this created, but I personally don't have plans to create it in the near term. If you're interested in creating it, that'd be great!

**Comment by patrickt** [comment]
LaTeX can be very difficult to parse, as it can reprogram macros in real-time. It’s certainly possible, but it would be a lot of work :( https://tex.stackexchange.com/questions/4201/is-there-a-bnf-grammar-of-the-tex-language

**Comment by maxbrunsfeld** [comment]
I think we could write a grammar that would give us better syntax highlighting, code folding, etc than whatever TextMate grammar people are currently using.

Granted, the parser won't work on LaTeX code that, say, redefines category codes to switch the meaning of `[` and `]` (as that answer points out is possible 🤔 ), but that code would never have syntax-highlighted properly anyway, so I don't think that matters.

**Comment by thomasjo** [comment]
I'm trying to get the ball rolling on a canonical Tree-sitter grammar for LaTeX. As mentioned, correctly parsing LaTeX can be very difficult, but supporting the basics and simply ignoring the difficult parts will make it feasible with not too much effort.

At this point, I've essentially only added the core scaffolding, and need to begin defining a grammar.
You can follow the progress at https://github.com/thomasjo/tree-sitter-latex.

**Comment by gracile-fr** [comment]
FWIW https://github.com/yitzchak/tree-sitter-latex

**Comment by joe733** [comment]
Both of these projects https://github.com/yitzchak/tree-sitter-latex & https://github.com/thomasjo/tree-sitter-latex are dead :confused:

**Comment by ahelwer** [comment]
https://github.com/latex-lsp/tree-sitter-latex
