### ISSUE TITLE
Version mismatch in Makefile in 0.20.8 release

### ISSUE THREAD

**Issue by msva** [tree-sitter/tree-sitter#2210]
Hi there!
Makefile in 0.20.8 tag states `VERSION := 0.20.9`.

This looks like a mismatch.

Isn't it was supposed to be 0.20.8 at the momennt of the tag, and become 0.20.9 right after that tag, for example?

**Comment by msva** [comment]
@ahlinc You've set cersion in makefile to 0.20.10, but last release is still .8
Do you plan to skip .9 and will next release be .10?

Otherwise, this version change will repeat the mismatch issue in next release (if it will be .9 with makefile stating .10)

**Comment by ahlinc** [comment]
I've set it to the actual version from lib's `Cargo.toml`, releases seen on GH releases are CLI versions and they currently is out of sync with the core lib.
