### ISSUE TITLE
Feature request: add `punctuation.separator.key-value` highlight

### ISSUE THREAD

**Issue by datsfilipe** [tree-sitter/tree-sitter#2234]
In VS Code theme creation we can use `punctuation.separator.key-value` highlight to style the separator between `key` and `value`, but when I tried to change it for the theme I'm creating, I didn't found it. With `TSCaptureUnderCursor`:

![image](https://user-images.githubusercontent.com/76636791/235364972-4bb02a90-dfa2-497c-a6ad-8911751fcf2b.png)

The command shows that the highlight is `punctuation.delimiter`, but It doesn't have the same behaviour as the proposed highlight, since the `punctuation.separator.key-value` would only highlight the `:` character.

***Note: I'm a beginner in Neovim theme creation so some things might not be very accurate and if the feature being requested isn't needed (if I can do it in some other way for example), I'm sorry for the inconvenience***

**Comment by ahelwer** [comment]
Capture names are defined by each specific grammar and are kind of arbitrary, although each tree-sitter consumer (github, neovim, etc.) has a list of capture names they consider standard. Anyway if this is regarding tree-sitter integration with VS Code then you will either need to write your own queries for each grammar you want to support or use existing queries like the neovim ones and adapt what capture names you're using. Alternatively if this is about adding another capture name to the set of standard neovim capture names then you'll want to open a discussion in the nvim-treesitter repo.

**Comment by datsfilipe** [comment]
seems to be the last option for me, I should have opened the issue there then, thanks.
