### ISSUE TITLE
tree-sitter-config and other crates are way out of date

### ISSUE THREAD

**Issue by vinoski** [tree-sitter/tree-sitter#2237]
PR #2035  fixed `TREE_SITTER_DIR` handling and it's part of the 0.20.8 sources, but unfortunately the `tree-sitter-config` crate is stuck at [0.19.0 on crates.io](https://crates.io/crates/tree-sitter-config) and so is way out of date. The result is that `cargo install tree-sitter-cli@0.20.8` doesn't actually provide the `TREE_SITTER_DIR` fix. [The `tree-sitter-loader` crate](https://crates.io/search?q=tree-sitter-loader), at 0.20.0, is also out of date.

**Comment by ahlinc** [comment]
Thank you for the report and the clear explanation. This will be fixed on the next release.

As a workaround for now try to use: `cargo install --git https://github.com/tree-sitter/tree-sitter --tag v0.20.8`

**Comment by ahlinc** [comment]
**TODO:**
* [ ] In a versioning policy and automation take into account that `cargo install ...` solely relies on versioned published crates, while the `cargo build --release` that actually relies on sources that may be patched and been forgotten to be released.

**Comment by vinoski** [comment]
> As a workaround for now try to use: `cargo install --git https://github.com/tree-sitter/tree-sitter --tag v0.20.8`

Thanks for the workaround!

**Comment by XVilka** [comment]
@amaanq, since 0.20.9 was released, can this one be closed?

**Comment by dundargoc** [comment]
This has been fixed.
