### ISSUE TITLE
add API: ts_node_ancestors

### ISSUE THREAD

**Issue by champignoom** [tree-sitter/tree-sitter#2267]
`ts_node_parent()` effectively finds all ancestors and drops all but the last one.  It's a waste to call it recursively if one wants to find the ancestors in the first place.

https://github.com/tree-sitter/tree-sitter/blob/a62bac5370dc5c76c75935834ef083457a6dd0e1/lib/src/node.c#L461-L490

**Comment by clason** [comment]
So what's your ask here? Do you want to have a recursion-free `ts_node_parent`?

Or do you want to turn this into a `ts_node_ancestors` function, which `ts_node_parent` wraps? That would be even more wasteful since you'd need to also _store_ nodes you're later throwing away...

In any case, if you have a plan, why not make a PR?

**Comment by ahlinc** [comment]
@champignoom _previously you used the right place for the questions:_ https://github.com/tree-sitter/tree-sitter/discussions/2250

Regarding the `ts_node_parent()` it exists here for backward compatibility from times when there was no _Cursor API_.

If you wonder about decisions that were made in the project I'd suggest to use a search across closed issues and PRs, there are a lot of interesting info: https://github.com/search?q=repo%3Atree-sitter%2Ftree-sitter+immutable+&type=pullrequests

Related to the `ts_node_parent()`:
- https://github.com/tree-sitter/tree-sitter/pull/172
- https://github.com/tree-sitter/tree-sitter/pull/1119

Cursor API appears here:
- https://github.com/tree-sitter/tree-sitter/pull/165

**Comment by ahlinc** [comment]
Feel free to reopen the issue, but please provide a real description why such API method would be useful with a real use cases.

**Comment by clason** [comment]
This reminds me: I've often pined for a proper reference documentation of the tree-sitter API. The docs linked from the readme are nice as an introduction/tutorial, but they don't really help when trying to find out what methods you can call on a node or a tree.

**Comment by lewis6991** [comment]
api.h is my goto 😉. I think it's just a case of doxygen'ing it into html (or whatever doctool).
