### ISSUE TITLE
Error "/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found"

### ISSUE THREAD

**Issue by eed3si9n** [tree-sitter/tree-sitter#2272]
## steps

https://github.com/tree-sitter/tree-sitter-scala/blob/7d348f51e442563f4ab2b6c3e136dac658649f93/package.json

Create a parser with npm file:

```json
  "devDependencies": {
    "tree-sitter-cli": "^0.20.7"
  },
```

## problem

Without any changes to our code, CI started failing on Ubuntu 20.04 with:

```bash
/home/runner/work/tree-sitter-scala/tree-sitter-scala/node_modules/tree-sitter-cli/tree-sitter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/runner/work/tree-sitter-scala/tree-sitter-scala/node_modules/tree-sitter-cli/tree-sitter)
/home/runner/work/tree-sitter-scala/tree-sitter-scala/node_modules/tree-sitter-cli/tree-sitter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/runner/work/tree-sitter-scala/tree-sitter-scala/node_modules/tree-sitter-cli/tree-sitter)
/home/runner/work/tree-sitter-scala/tree-sitter-scala/node_modules/tree-sitter-cli/tree-sitter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/runner/work/tree-sitter-scala/tree-sitter-scala/node_modules/tree-sitter-cli/tree-sitter)
```

## expectation

The build continues to work.

## note

0.20.8 was the first release after GitHub Actions changed `ubuntu-latest` to Ubuntu 22.04 in October 2022 - https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/.

Could we either roll back to using Ubuntu 20.04 or bump up the minor version to 0.21.x since 0.20.8 is not backward compatible with 0.20.7 please?

**Comment by ahlinc** [comment]
I can rollback runner version to Ubuntu 20.04 and update an artifact for the v0.20.8 version also.
@eed3si9n Does this required for x86 32-bit architecture or not?

**Comment by ahlinc** [comment]
@eed3si9n I've downgraded **glibc** version  from _GLIBC_2.34_ to _GLIBC_2.29_ for `tree-sitter-linux-x64.gz` artifact for `v0.20.8` released version.
