### ISSUE TITLE
json grammar fails

### ISSUE THREAD

**Issue by albfan** [tree-sitter/tree-sitter#228]
I need to disable json grammar to get tree-sitter compiled

I use steps in https://github.com/albfan/tree-sitter-c-parser-example README.md to try it

If that's not the way to get a libruntime.a, any tip is appreciated

**Comment by maxbrunsfeld** [comment]
Hi, I added better instructions for how to build the runtime library. They are here: http://tree-sitter.github.io/tree-sitter/using-parsers#building-the-runtime-library.

The `configure` scripts (and `gyp`) are only used when developing the library. They aren't necessary for most users.
