### ISSUE TITLE
tag tests: negative assertions

### ISSUE THREAD

**Issue by avodonosov** [tree-sitter/tree-sitter#2304]
It's desirable to be able to test that a certain place in the code is NOT tagged with unneeded tag.

For example, in Lisp, function calls are list literals with first element being a symbol: `(some-fn arg1 arg2)`.
However, there are cases where such list literals are not function calls. For example, formal parameters in a function definition: `(defun some-fn (param1 param2) ...)`. I'd like to have an assertion in tests that the `(param1 param2)` is not recognized as a function call.

Something like
```
(defun some-fn (param1 param2)
   ;;   ^ definition.function
   ;;           ^ NONE
 ...)

```

Or

```
(defun some-fn (param1 param2)
   ;;   ^ definition.function
   ;;           ^ ! reference.call
 ...)

```
when we want to make sure the `param1` is not tagged as `reference.call`, but allow it to be tagged in some other way - so NONE is not suitable.

**Comment by amaanq** [comment]
this would be useful, I agree. would it be fine to make the `!` right next to capture names though?

**Comment by avodonosov** [comment]
@amaanq, thank you
