### ISSUE TITLE
How to resolve conflict on the boundary of two repetitions?

### ISSUE THREAD

**Issue by lykahb** [tree-sitter/tree-sitter#2306]
I have a grammar where there is a list of fields that are followed by an optional list of attributes. The conflict is between an attribute name and a field name. 

The examples in the documentation describe setting precedences for recursive grammars where prec.left or prec.right decides where to put the parentheses. The problem I ran into is rather where to put the boundary between two repetitions. If I prioritize the `fields` rule by adding a `conflict` for `fields`, the name of the first attribute gets parsed as a field and the following "=" causes an error.

One workaround I found is to parse the key name together with "=" as a single token. That disambiguates it from field, but makes highlighting look odd.

``` js
{
...
  rules: {
    source_file: $ => seq($.fields, optional($.attributes)),

    fields: $ => repeat1($.field),
    // The kv_attr goes first because the "=" makes it unambiguous from a field
    attributes: $ => seq($.kv_attr, repeat(choice($.attr, $.kv_attr))),

    field: $ => $.identifier,
    attr: $ => $.identifier,
    kv_attr: $ => seq($.attr, '=', $.integer),

    identifier: _ => /[a-z0-9]+/,
    integer: _ => /[1-9][0-9]*/
  }
}
```

```
Unresolved conflict for symbol sequence:

  fields_repeat1  •  identifier  …

Possible interpretations:

  1:  (fields  fields_repeat1)  •  identifier  …
  2:  (fields_repeat1  fields_repeat1  •  fields_repeat1)
```

Here is the desired syntax tree

```
================================================================================
Conflict
================================================================================

f1 f2 attr=1 attr2

--------------------------------------------------------------------------------

(source_file
  (fields
    (field
      (identifier))
    (field
      (identifier)))
  (attributes
    (kv_attr
      (attr
        (identifier))
      (integer))
    (attr
      (identifier))))
```

**Comment by ahelwer** [comment]
Have you tried using the conflicts array to trigger GLR parsing with dynamic precedence instead of using static precedence?

**Comment by lykahb** [comment]
@ahelwer Thank you for you answer. I tried using the array of conflicts with `[$.fields, $.kv_attr]` and `[$.fields, $.attr]`. But there was still an unresolved conflict. After putting `[$.fields]` in there just for an experiment, the conflict got resolved and the parser works as intended.

I still do not understand what exactly `conflicts` describes. The documentation says "Each inner array represents a set of rules that’s involved in an LR(1) conflict that is intended to exist in the grammar". So, it is intuitive that a conflict should involve multiple rules (field and attribute) that are in conflict. Not sure how putting one rule in there solved the problem. I wish the documentation could give more details.

**Comment by ahelwer** [comment]
If you have something analogous to a `seq(repeat(rule), repeat(rule))` then the rule can conflict with itself is I think what that solves. It helps to look at the generated conflicting sequence of tokens (it takes some practice to understand what it's saying) and imagine how that would be parsed by your grammar and where it gets confused.

**Comment by amaanq** [comment]
It's because of a standalone repeat1 rule, when should it end? As late as it can, or as early as it can (that being right/left associativity), or you can just mark it as a conflict and let it resolve itself at runtime...
