### ISSUE TITLE
Different outputs for test, parse and test -f

### ISSUE THREAD

**Issue by acristoffers** [tree-sitter/tree-sitter#2310]
Hi there,

I'm writing a [parser for MATLAB](https://github.com/acristoffers/tree-sitter-matlab) and just came across a problem: `tree-sitter test` is generating a different output from `tree-sitter test -f Command` and `tree-sitter parse test.m`. The file `test.m` is not in the repo, but I simply got the body of the failing test:

```matlab
pwd
pwd,
pwd;

disp !
disp ! ;
disp !s;

cd ../something
disp some text

cvx_begin sdp % quiet
    cvx_solver Mosek
    variable P(n, n) semidefinite
    variable Y(n, p, 4)
    variable K(n, p, 4)
    subject to
cvx_end
```

`tree-sitter test -d0u` also generates the correct output.

Basically when I run just `tree-sitter test` it is matching all `pwd` lines as `identifier` (internal) instead of the correct `command` (external). Something seems to be affecting the way the scanner runs since it works with other flags and the `parse`  subcommand.

**Comment by ahelwer** [comment]
Are you making sure you fully reset your scanner state from the serialized state input?

**Comment by acristoffers** [comment]
Yes, I have three tokens that the scanner can detect: `COMMENT`, `COMMAND_NAME` and `COMMAND_ARGUMENT`. The scanner has 2 states: `is_inside_command` and `line_continuation`, which are used to select what tokens are valid at this point.

At first only `COMMENT` and `COMMAND_NAME` are valid, and `COMMAND_NAME` sets `is_inside_command` if it matches, causing only `COMMAND_ARGUMENT` to be valid next. If I run `tree-sitter test -d` I can see that my scanner is consuming `10` (new line?) and returning false, meaning that `COMMAND_NAME` did not enter, but this is the if for that:

```c
    if (valid_symbols[COMMAND_NAME] && !is_inside_command) {
        is_inside_command = false;
        return scan_command(lexer);
    }
```

so it should enter as `is_inside_command` is false by default and `COMMAND_NAME` should be a valid symbol at this point.

The comment rule comes before, but it is guarded, so it would not match, since `lexer->lookahead` is 10 and not `%` nor `.`:

```c
if ((line_continuation || !is_inside_command) && valid_symbols[COMMENT] && (lexer->lookahead == '%' || lexer->lookahead == '.')) {
        return scan_comment(lexer);
}
```

But what really bothers me is that all other commands run correctly and returns the correct result, except `tree-sitter test`. Even `tree-sitter test -f Command` works correctly. Do you think it has to do with the reuse of the parser for a new file? I can see the scan fail if the following is true:

1. The states are correctly initialized to false.
2. *Only* `COMMENT` is enabled.
3. The scanner returns false, because it is not a comment.
4. The internal scanner identifies the `identifier` token and the parser takes it.

That would be wrong since the scanner would identify a command if run with `COMMAND_NAME` enabled, and I don't know if that is the case because, again, `tree-sitter parse test.m` and `tree-sitter test -f Command` works without problems.

**Comment by acristoffers** [comment]
Wait, I think I see the problem, I may have misunderstood something: does tree-sitter deserialize the state before every operation? I thought it worked like this:

1. scanner is loaded into memory
2. `tree_sitter_my_language_external_scanner_create` is called
3. `tree_sitter_my_language_external_scanner_serialize` is called
4. `tree_sitter_my_language_external_scanner_deserialize` is called
5. `tree_sitter_my_language_external_scanner_scan` is called
6. `tree_sitter_my_language_external_scanner_serialize` is called *only if a token was generated*
7. loop from 4

But that does not seem to be the case for every invocation of the `scan` function, which is causing my state to be wrong. I was assuming `deserialize` was being called on every invocation, which would fix the state, but if that is not true, than I'm carrying over a wrong state from one test to the next. I'll fix that and see if it solves the problem.

**Comment by acristoffers** [comment]
Yep, it works now. The scanner was setting `is_inside_command` to true when I got to a point that it would always be the case, unless it was not a command, so I had the impression that it would stick only if I returned true from the scanner, and would get overritten if I returned false, but that's not how it works, the state was sticking around and a previous test had `eig (A)` which went in enough to set the flag, but then bailed out when it saw the `(` char, leving the flag set.
