### ISSUE TITLE
Troubles resolving conflicts

### ISSUE THREAD

**Issue by george-hopkins** [tree-sitter/tree-sitter#233]
I'm trying to create my first parser with `tree-sitter`. I'd like to parse files which look like this:
```plain
def = a b ccc
foo = ddd eee bar = fff
```

Expected output:
```plain
(source_file
  (definition
    (identifier "def")
    (identifier "a")
    (identifier "b")
    (identifier "ccc"))
  (definition
    (identifier "foo")
    (identifier "ddd")
    (identifier "eee"))
  (definition
    (identifier "bar")
    (identifier "fff")))
```

I played around with all kinds of associativies and precedences. However, all my attempts to resolve conflicts failed. My parser:
```javascript
module.exports = grammar({
  name: 'def',
  rules: {
    source_file: $ => repeat1($.definition),
    definition: $ => seq($.identifier, '=', repeat1($.identifier)),
    identifier: $ => /[a-zA-Z0-9_]+/,
  }
});
```

Is there a way to build such a parser or is this kind of grammar out of scope?

**Comment by maxbrunsfeld** [comment]
Yeah, there's definitely a way.

Is this a language that you designed? It looks like the way the language works, it fundamentally requires looking ahead by more than one token at all times.

This is doable with Tree-sitter using the `conflicts` feature. Sorry that this is not fully documented yet. There are examples in other grammars like [this one](https://github.com/tree-sitter/tree-sitter-c/blob/05f62b9f84e91a5bfb3e768c0d1271f20ac8ee35/grammar.js#L41-L48) and [this one](https://github.com/tree-sitter/tree-sitter-javascript/blob/7ee00973bbbd7a0bae6efda28d3bbfab030d7f3e/grammar.js#L54-L63).

You should be able to take the conflict suggested by the error message and add it to the `conflicts` array.

**Comment by george-hopkins** [comment]
Thank you for the detailed explanation! With the help of the provided examples, my parser is working :tada:

**Comment by matthuszagh** [comment]
@george-hopkins any chance you still have the code you used? I'm new to this and trying to understand conflicts myself and think your minimal example might help. Thanks!

**Comment by ridilculous** [comment]
In case someone comes here wondering how the solution looked, it might be this one:

```javascript
conflicts: $ => [ [$.definition] ],
```
