### ISSUE TITLE
web-tree-sitter fails in Node.js 19 and higher: `Error: bad export type for tree_sitter_tsx_external_scanner_create: undefined`

### ISSUE THREAD

**Issue by TylerLeonhardt** [tree-sitter/tree-sitter#2338]
👋  I'm coming from https://github.com/tree-sitter/tree-sitter-typescript/issues/244#issuecomment-1580662106 which was originally called out to be a [node-tree-sitter](https://github.com/tree-sitter/node-tree-sitter/pull/134) issue... until I remembered that I don't use `node-tree-sitter` but rather `web-tree-sitter` in Node.js (because it's easier to distribute in a CLI).

This seems to be the repo for `web-tree-sitter` so I am opening a similar issue here for web-tree-sitter in case it also needs a fix. 

I wanted to add another detail... you can easily reproduce this issue by running using Node.js 19+ as well:

```
npx @vscode/l10n-dev export ./folderWithTSFiles
```
```
Error: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined
    at reportUndefinedSymbols (/home/codespace/.npm/_npx/68546583dcb2c24b/node_modules/web-tree-sitter/tree-sitter.js:1:19748)
    at postInstantiation (/home/codespace/.npm/_npx/68546583dcb2c24b/node_modules/web-tree-sitter/tree-sitter.js:1:17027)
    at /home/codespace/.npm/_npx/68546583dcb2c24b/node_modules/web-tree-sitter/tree-sitter.js:1:17752
    at async /home/codespace/.npm/_npx/68546583dcb2c24b/node_modules/@vscode/l10n-dev/dist/cli.js:269:10
```

@deepak1556 gave some advice:

> Decompiled the problematic tree-sitter-tsx.wasm file with wasm-decompile and verified that the symbol tree_sitter_typescript_external_scanner_create was defined, however emscripten ends up reporting it as undefined at https://github.com/emscripten-core/emscripten/blob/6f0238367348f5e33605b3f0a42455fb3a2d739f/src/library_dylink.js#L232 , next good step to debug is to recompile the wasm module with assertions and see what went wrong.
>
> It not working in Node 19 as well definitely hints to a v8 breakage. Electron 22 and Node 19 both use V8 10.8.

Also gonna @maxbrunsfeld and @verhovsky here since they have been really helpful over in the node-tree-sitter repo and might know what's required here 🙏

**Comment by ahelwer** [comment]
Have you taken a look at the previous threads about how only certain imports are allowed in the external scanners if you want them to work with web-tree-sitter?

**Comment by TylerLeonhardt** [comment]
@ahelwer got any links for me?

I should be clear that I just use tree-sitter & ts/tsx grammars from an API perspective. I don't know much about their interactions with each other. I opened this issue since @hendrikvanantwerpen mentioned in the linked issue that the issue didn't seem related to `tree-sitter-typescript` but rather `tree-sitter` itself ... so here I am.

That said, I can try to help how I can.

**Comment by sogaiu** [comment]
Possibly of relevance:

* https://github.com/tree-sitter/tree-sitter/issues/1906
* https://github.com/tree-sitter/tree-sitter/discussions/1325
* https://github.com/tree-sitter/tree-sitter/issues/1300

**Comment by sogaiu** [comment]
There is now a repository with code and instructions on how to reproduce this issue [here](https://github.com/sogaiu/tree-sitter-issue-2338/).

(There is also a bit of background [here](https://github.com/tree-sitter/tree-sitter/issues/1906#issuecomment-1647212137) followed by some possibly relevant comments.)

Subsequent to creating the repository, I looked into things a bit more and found that adding `await` appropriately results in their being no error.

This can be observed via [a branch of the aforementioned repository](https://github.com/sogaiu/tree-sitter-issue-2338/tree/web-tree-sitter-debug) that uses a debug version of `web-tree-sitter` (in the hopes that the error output is easier to make sense of).

In the `web-tree-sitter-debug` branch, in the file `reproduces-with-node-19-or-20.js`, there is a function:

```javascript
async function main() {
    await Parser.init();

    // XXX: if `await` is added below, will not get error
    tsx_do();
    //await tsx_do();

    await ts_do();
}
```

If as mentioned in the comment in the code:

```javascript
tsx_do();
```

is replaced by:

```javascript
await tsx_do();
```

subsequent invocations do not result in an error (at least not here).

**Comment by sogaiu** [comment]
I tried tweaking the `web-tree-sitter-debug` branch so that `tree-sitter-c` and `tree-sitter-typescript` were both used and that seemed fine (even without `await`).

**Comment by sogaiu** [comment]
Looking through @TylerLeonhardt's previous quote from [here](https://github.com/tree-sitter/tree-sitter-typescript/issues/244#issuecomment-1528149425):

> @deepak1556 gave some advice:

>    Decompiled the problematic tree-sitter-tsx.wasm file with wasm-decompile and verified that the symbol tree_sitter_typescript_external_scanner_create was defined, however emscripten ends up reporting it as undefined at https://github.com/emscripten-core/emscripten/blob/6f0238367348f5e33605b3f0a42455fb3a2d739f/src/library_dylink.js#L232 , next good step to debug is to recompile the wasm module with assertions and see what went wrong.

>    It not working in Node 19 as well definitely hints to a v8 breakage. Electron 22 and Node 19 both use V8 10.8.

I gave `wasm-decompile` (presumably from [wabt](https://github.com/WebAssembly/wabt)) a try and found differently.  (Invocation is like `wasm-decompile tree-sitter-tsx.wasm > some-appropriate-file.c`.)

AFAICT, for the local `tree-sitter-tsx.wasm` file, there is no definition of `tree_sitter_typescript_external_scanner_create`.

Searching for `_external_scanner_create` turns up:

```c
import global GOT_func_tree_sitter_tsx_external_scanner_create:int;
```

```c
  (env_memory_base + 1004736)[0]:int =
    GOT_func_tree_sitter_tsx_external_scanner_create;
```

```c
export function tree_sitter_tsx_external_scanner_create():int {
  return 0
}
```

These are all expected lines AFAICT.

From here it looks like `tree_sitter_typescript_external_scanner_create` being reported as `undefined` is correct (and expected to begin with).  Though possibly the `wasm-decompile` I used is not appropriate (version 1.0.27).

Perhaps the problem is instead that that symbol is being looked for at all.

IIUC, some code that leads to that lives in `tree-sitter.js` (code from below is based on the debug version):

```javascript
    function reportUndefinedSymbols() {
     for (var symName in GOT) {
      if (GOT[symName].value == 0) {
       var value = resolveGlobalSymbol(symName, true).sym;
       if (!value && !GOT[symName].required) {
        continue;
       }
       assert(value, "undefined symbol `" + symName + "`. perhaps a side module was not linked in? if this global was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment");
       if (typeof value == "function") {
        GOT[symName].value = addFunction(value, value.sig);
       } else if (typeof value == "number") {
        GOT[symName].value = value;
       } else {
        throw new Error("bad export type for `" + symName + "`: " + typeof value);
       }
      }
     }
    }
```

So a natural question to ask is how `tree_sitter_typescript_external_scanner_create` ended up in `GOT`...

**Comment by sogaiu** [comment]
I modified `tree-sitter.js` to get a listing of what keys `GOT` had, and among them were:

```
tree_sitter_typescript_external_scanner_create
tree_sitter_typescript_external_scanner_destroy
tree_sitter_typescript_external_scanner_scan
tree_sitter_typescript_external_scanner_serialize
tree_sitter_typescript_external_scanner_deserialize
```

None of those appear in the `wasm-decompile` output of the local `tree-sitter-tsx.wasm`.

**Comment by sogaiu** [comment]
IIUC, [`Parser.Language.load()`'s definition](https://github.com/tree-sitter/tree-sitter/blob/a809274009953c9d3c314c7dd27909b1347635f8/lib/binding_web/binding.js#L877-L924) [1] is:

```javascript
  static load(input) {
    let bytes;
    if (input instanceof Uint8Array) {
      bytes = Promise.resolve(input);
    } else {
      const url = input;
      if (
        typeof process !== 'undefined' &&
        process.versions &&
        process.versions.node
      ) {
        const fs = require('fs');
        bytes = Promise.resolve(fs.readFileSync(url));
      } else {
        bytes = fetch(url)
          .then(response => response.arrayBuffer()
            .then(buffer => {
              if (response.ok) {
                return new Uint8Array(buffer);
              } else {
                const body = new TextDecoder('utf-8').decode(buffer);
                throw new Error(`Language.load failed with status ${response.status}.\n\n${body}`)
              }
            }));
      }
    }

    // emscripten-core/emscripten#12969
    const loadModule =
      typeof loadSideModule === 'function'
      ? loadSideModule
      : loadWebAssemblyModule;

    return bytes
      .then(bytes => loadModule(bytes, {loadAsync: true}))
      .then(mod => {
        const symbolNames = Object.keys(mod)
        const functionName = symbolNames.find(key =>
          LANGUAGE_FUNCTION_REGEX.test(key) &&
          !key.includes("external_scanner_")
        );
        if (!functionName) {
          console.log(`Couldn't find language function in WASM file. Symbols:\n${JSON.stringify(symbolNames, null, 2)}`)
        }
        const languageAddress = mod[functionName]();
        return new Language(INTERNAL, languageAddress);
      });
  }
```

Not sure if it's a good idea, but changing:

```javascript
      .then(bytes => loadModule(bytes, {loadAsync: true}))
```

to:


```javascript
      .then(bytes => loadModule(bytes, {loadAsync: true, allowUndefined: true}))
```

results in no errors.

---

FWIW, I think this was hinted at in [tree-sitter/tree-sitter-typescript#244](https://github.com/tree-sitter/tree-sitter-typescript/issues/244#issue-1689047027) by @PF4Public:

>         if (!flags.allowUndefined) {
>          reportUndefinedSymbols();
>        }

> But I couldn't find, where does flags.allowUndefined come from. 

I think we have an answer to that -- it looks like `{loadAsync: true}` is `flags` (and `!flags.allowUndefined` is `true` in `tree-sitter.js`).

---

[1] `binding.js` is one of the pieces that goes into making `tree-sitter.js`.

**Comment by adamrodger** [comment]
I'm getting the same issue again on latest VS Code using the [Cucumber Language Server](https://github.com/cucumber/language-server):

```
[Error - 11:51:05 AM] Server initialization failed.
  Message: Request initialize failed with message: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined
  Code: -32603 
[Error - 11:51:05 AM] Cucumber Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: bad export type for `tree_sitter_c_sharp_external_scanner_create`: undefined
  Code: -32603 
```
