### ISSUE TITLE
I occurred an exception when build the laguage wasm file follow the docs.

### ISSUE THREAD

**Issue by goneXII** [tree-sitter/tree-sitter#2348]
I occurred an exception, when build the laguage wasm file  (tree-sitter-javascript) and I has been installed all dependences

platform: windows10
arch: x86_64
node: v18.16.1
command:  npx tree-sitter build-wasm ./node_modules/tree-sitter-javascript
shell: windows powershell by administrator
output:
emcc command failed - emcc: error: src\scanner.c: No such file or directory ("src\scanner.c" was expected to be an input file, based on the commandline arguments provided)

**Comment by StKali** [comment]
I'm having the same problem and I wonder if we can get the built wasm language files.

**Comment by amaanq** [comment]
cannot reproduce - ensure your tree-sitter version is up to date and ensure you didn't delete scanner.c in src

**Comment by sogaiu** [comment]
Possibly of some use might be [this](https://github.com/sogaiu/ts-questions/blob/master/questions/which-version-of-emscripten-should-be-used-for-the-playground/README.md), though as mentioned above, ensuring that `scanner.c` exists is necessary so that should be verified.

**Comment by hodayaGruzm** [comment]
happend to me with tree-sitter-python, 
and i also got a problem on mac:
image with reference docker.io/emscripten/emsdk:3.1.29 was found but does not match the specified platform: wanted linux/arm64/v8, actual: linux/amd64.

did anybody has an idea how to solve one of those bugs?
