### ISSUE TITLE
Syntax highlighting unit test always passing

### ISSUE THREAD

**Issue by AnHeuermann** [tree-sitter/tree-sitter#2349]
My unit tests for the tree-sitter highlighting are always passing (0 assertions), though the test should fail and I'm not sure what I'm doing wrong.

I have unit test `records_01.mo`:

```
tree-sitter-metamodelica
└── test
    └── highlight
        └── records_01.mo
```

```modelica
record RECORD_A
// <- keyword
//     ^ type
  Bool x;
  // <- function
  Integer y;
  // <- type.builtin
end RECORD_A;
// <- keyword
//  ^ type
```

Here `Bool x;` is wrong and won't be highlighted:
![grafik](https://github.com/tree-sitter/tree-sitter/assets/38031952/2a955252-2f9f-455e-a482-a55cd754677a)
Especially it is not highlighted as `function`.

Running the test I get:

```bash
$ npx tree-sitter test
  records_01:
    ✓ Record definition 01
syntax highlighting:
  ✓ records_01.mo (0 assertions)
```

<details>
<summary>tree for `records_01.mo` (comments removed)</summary>

```
(source_file [0, 0] - [4, 0]
  record: (record_definition [0, 0] - [3, 13]
    (record_statement [0, 0] - [0, 15]
      name: (identifier [0, 7] - [0, 15]))
    (ERROR [1, 2] - [1, 9]
      (identifier [1, 2] - [1, 6])
      (identifier [1, 7] - [1, 8]))
    (type_declaration [2, 2] - [2, 12]
      (integer_type [2, 2] - [2, 9])
      (identifier [2, 10] - [2, 11]))
    (_end_of_statement [3, 0] - [3, 13]
      (identifier [3, 4] - [3, 12]))))
```
</details>

<details>
<summary>highlights.scm</summary>

```scm
[
  "record"
  "end"
] @keyword
(real_type) @type.builtin
(integer_type) @type.builtin
(record_definition (record_statement) @type)
(record_definition (_end_of_statement) @type)
```
</details>

Is this a bug or am I'm doing something wrong?
I'm following the documentation [syntax-highlighting#unit-testing](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#unit-testing).

My language uses `//` as comments, but I don't have them included in the grammar rules yet.

**Comment by maxbrunsfeld** [comment]
I think you just need to add comments to your grammar rules. I think the tests work by looking for nodes in the syntax tree whose type contains `comment`.

**Comment by AnHeuermann** [comment]
But shouldn't the test fail in this case?

**Comment by amaanq** [comment]
no, because there are no assertions/tests without a known comment rule
