### ISSUE TITLE
Handle whitespace as syntax

### ISSUE THREAD

**Issue by wstevick** [tree-sitter/tree-sitter#2350]
I'm starting work on a grammar for [Futhark](https://github.com/diku-dk/futhark/). Its function call syntax is `f x`, and its array indexing syntax is `a[i]`. There's the potential for an ambiguity, because `a[i]` could either be interpreted as calling `a` with a one-element array `[i]` as an argument, or taking the `i`th element of `a`. The way it's resolved in the language is that if there's whitespace before the `[`, then it's a function call, and if not it's indexing. How do I do this in a tree-sitter grammar?

**Comment by ahelwer** [comment]
What happens when you try to add a space to the function call rule to disambiguate it?

**Comment by wstevick** [comment]
Just making sure, you mean something like
```javascript
choice(
prec.left(1, seq($.ident, "[", $.exp, "]")),
prec.left(2, seq($.ident, " ", $.exp)),
...)
````

I'm unfamiliar with writing grammars, and I want to make sure I understand.
Thanks.

**Comment by ahelwer** [comment]
Correct, although I don't know why you have static precedences defined.
