### ISSUE TITLE
Getting MISSING node or ERROR depending on string literal length

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter#2360]
I thought this was surprising and possibly interesting. I'm not bothered by it, so feel free to close. This happened in the tree-sitter-go parser with tree-sitter 0.20.8.

With the tree-sitter-go parser (git commit 3a3a8ee), we get different kinds of errors (ERROR vs. MISSING) depending on the length of the `_string_literal`:
```
~/tree-sitter-go $ npx tree-sitter parse <(echo 'import ("foooooo")')
(source_file [0, 0] - [1, 0]
  (import_declaration [0, 0] - [0, 18]
    (import_spec_list [0, 7] - [0, 18]
      (ERROR [0, 8] - [0, 17]
        (import_spec [0, 8] - [0, 17]
          path: (interpreted_string_literal [0, 8] - [0, 17]))))))
/dev/fd/63	0 ms	(ERROR [0, 8] - [0, 17])

~/tree-sitter-go $ npx tree-sitter parse <(echo 'import ("fooooooo")')
(source_file [0, 0] - [1, 0]
  (import_declaration [0, 0] - [0, 19]
    (import_spec_list [0, 7] - [0, 19]
      (import_spec [0, 8] - [0, 18]
        path: (interpreted_string_literal [0, 8] - [0, 18])))))
/dev/fd/63	0 ms	(MISSING "\n" [0, 18] - [0, 18])

~/tree-sitter-go $ npx tree-sitter --version
tree-sitter 0.20.8 (d4c1bf7ce78051b7f4a381d1508d68928512ed5f)
```

The original report is there: https://github.com/tree-sitter/tree-sitter-go/issues/121

Desired behavior: consistently getting either MISSING or ERROR regardless of length of string literal.

**Comment by amaanq** [comment]
Belongs (and fixed) in tree-sitter-go (fixed [here](https://github.com/tree-sitter/tree-sitter-go/pull/122))

**Comment by mjambon** [comment]
The question is why we're not getting the same error depending on the length of the string literal. I brought it up because it looks suspicious to me.

**Comment by amaanq** [comment]
Oh, yeah that is a good question actually...maybe something to do with calculating a node's complexity/weight

**Comment by SpontanCombust** [comment]
I can confirm this to not be an isolated case.
In both my own parser and then the main C parser I've noticed that with basic expressions the output is dependent on the length of tokens.

My parser:
<https://github.com/SpontanCombust/tree-sitter-witcherscript>(commit f451cb7)
Tested with 0.20.8 and 0.22.5 versions of tree-sitter-cli with the same result.

Case 1:
```js
function main() {
	abcd = abc
}
```
```pwsh
PS D:\Git-repo\tree-sitter-witcherscript> npx tree-sitter p test.ws
(script [0, 0] - [2, 1]
  (global_func_decl_stmt [0, 0] - [2, 1]
    name: (ident [0, 9] - [0, 13])
    params: (func_params [0, 13] - [0, 15])
    definition: (func_block [0, 16] - [2, 1]
      (ERROR [1, 1] - [1, 11]
        (assign_op_expr [1, 1] - [1, 11]
          left: (ident [1, 1] - [1, 5])
          op: (assign_op_direct [1, 6] - [1, 7])
          right: (ident [1, 8] - [1, 11]))))))
test.ws    0.21 ms         157 bytes/ms (ERROR [1, 1] - [1, 11])
```
 
Case 2:
```js
function main() {
	abcd = abcd
}
```
```pwsh
PS D:\Git-repo\tree-sitter-witcherscript> npx tree-sitter p test.ws 
(script [0, 0] - [2, 1]
  (global_func_decl_stmt [0, 0] - [2, 1]
    name: (ident [0, 9] - [0, 13])
    params: (func_params [0, 13] - [0, 15])
    definition: (func_block [0, 16] - [2, 1]
      (expr_stmt [1, 1] - [1, 12]
        (assign_op_expr [1, 1] - [1, 12]
          left: (ident [1, 1] - [1, 5])
          op: (assign_op_direct [1, 6] - [1, 7])
          right: (ident [1, 8] - [1, 12]))))))
test.ws    0.14 ms          18 bytes/ms (MISSING ";" [1, 12] - [1, 12])
```

<br></br>
And here are similar tests done using the latest version of C parser on master
<https://github.com/tree-sitter/tree-sitter-c> (commit 1aafaff)


Case 1:
```c
int main {
	abcd = abc
}
```
```pwsh
PS D:\tmp\tree-sitter-c> npx tree-sitter p test.c
(translation_unit [0, 0] - [2, 1]
  (function_definition [0, 0] - [2, 1]
    type: (primitive_type [0, 0] - [0, 3])
    declarator: (identifier [0, 4] - [0, 8])
    body: (compound_statement [0, 9] - [2, 1]
      (ERROR [1, 1] - [1, 11]
        (assignment_expression [1, 1] - [1, 11]
          left: (identifier [1, 1] - [1, 5])
          right: (identifier [1, 8] - [1, 11]))))))
test.c     0.18 ms         143 bytes/ms (ERROR [1, 1] - [1, 11])
```

Case 2:
```c
int main {
	abcd = abcd
}
```
```pwsh
PS D:\tmp\tree-sitter-c> npx tree-sitter p test.c
(translation_unit [0, 0] - [2, 1]
  (function_definition [0, 0] - [2, 1]
    type: (primitive_type [0, 0] - [0, 3])
    declarator: (identifier [0, 4] - [0, 8])
    body: (compound_statement [0, 9] - [2, 1]
      (expression_statement [1, 1] - [1, 12]
        (assignment_expression [1, 1] - [1, 12]
          left: (identifier [1, 1] - [1, 5])
          right: (identifier [1, 8] - [1, 12]))))))
test.c     0.17 ms         158 bytes/ms (MISSING ";" [1, 12] - [1, 12])
```

**Comment by SpontanCombust** [comment]
When viewing the debug log all state transitions are the same and the only difference aside from different sizes and columns printed is this line just before the `done` step:
`select_smaller_error symbol:script, over_symbol:script`

**Comment by amaanq** [comment]
Tree-sitter will pick stack versions that have a lower error cost than other ones, the number of skipped characters and skipped lines directly influences this error cost hence the discrepancy. This can be considered expected behavior so I'll close this out (you can take a look at the calculation [here](https://github.com/tree-sitter/tree-sitter/blob/a7484885967331ea2768a4c8cb1dfa79936c07c8/lib/src/parser.c#L1288)

**Comment by SpontanCombust** [comment]
Thanks for the info
