### ISSUE TITLE
Prevent keywords from being parsed at identifiers

### ISSUE THREAD

**Issue by wstevick** [tree-sitter/tree-sitter#2372]
Because the tree-sitter lexer only attempts to parse tokens that are valid, keywords that are in positions variables should be will be parsed as identifiers. How do I prevent this in the grammar?

**Comment by ahelwer** [comment]
You can't, that just means a syntax error has occurred and you rely on error recovery to get a semi-useful parse tree out of the text.

**Comment by ahlinc** [comment]
The above answer is not fully correct there is a technique to define identifiers like a `choice` with included identifier regex plus allowed keywords to allow identifiers with keywords names in languages where it's valid.

**Comment by wstevick** [comment]
To clarify, I want it so that tokens like `def` and `if` will never be parsed as identifiers. If someone does something like `if = 3`, that should error.

**Comment by amaanq** [comment]
If you want to completely ensure that check even during error recovery you could use the external scanner, I'm not sure about a regex that does *not* allow certain words

**Comment by ahlinc** [comment]
> To clarify, I want it so that tokens like `def` and `if` will never be parsed as identifiers. If someone does something like `if = 3`, that should error.

It's default Tree-sitter behavior because keywords defined as string literals have priority over regex tokens, could you show excerpts of relevant parts for your grammar?

**Comment by wstevick** [comment]
The grammar is
```javascript
module.exports = grammar({
    name: 'futhark',

    extras: ($, original) => [...original, /--.*\n/],

    word: $ => $.id,

    rules: {
        source_file: $ => repeat($._dec),
        _dec: $ => choice($.val_bind),
        val_bind: $ => seq(choice('let', 'def', 'entry'), $.id, '=', $._exp),
        _exp: $ => choice($.id),
        id: $ => /[a-zA-Z_][a-zA-Z0-9_]*/
    },
});
```
The test file is
```futhark
def let = entry
```

`tree-sitter parse` should error, but instead it outputs
```
(source_file [0, 0] - [1, 0]
  (val_bind [0, 0] - [0, 15]
    (id [0, 4] - [0, 7])
    (id [0, 10] - [0, 15])))
```

**Comment by wstevick** [comment]
Thank you.
