### ISSUE TITLE
javascript augmented_assignment_expression invalid operator query

### ISSUE THREAD

**Issue by raczosala** [tree-sitter/tree-sitter#2373]
I do not understand why the following query is invalid

```js
for(var i = 10; i >= 0; i-=1){}

(for_statement
  increment: 
    (augmented_assignment_expression
    	left: (identifier) @left
    	operator: ("-=") @operator
    	right: (number) @number
    )
)
```

the grammar has the [operator field](https://github.com/tree-sitter/tree-sitter-javascript/blob/5720b249490b3c17245ba772f6be4a43edb4e3b7/src/grammar.json#L3643), the [node-types](https://github.com/tree-sitter/tree-sitter-javascript/blob/5720b249490b3c17245ba772f6be4a43edb4e3b7/src/node-types.json#L507) as well.

**Comment by ahelwer** [comment]
Maybe remove parentheses around "-="

**Comment by amaanq** [comment]
Works fine for me with and without the parentheses:

![image](https://github.com/tree-sitter/tree-sitter/assets/29718261/47942984-f4c1-4821-bfdc-7e940c9c9dbd)

**Comment by amaanq** [comment]
The javascript grammar for the playground might be, it seems that operator isn't a field there, and just "-=" or "(-=)" works fine

**Comment by raczosala** [comment]
alright, I'll make sure to use the latest grammars. Thank you!

**Comment by raczosala** [comment]
🤔 I can't get it to work with `web-tree-sitter`

If you go to this [example sandbox](https://codesandbox.io/s/lingering-surf-svd4vq) which is using [tree-sitter.js](https://github.com/tree-sitter/tree-sitter/releases/download/v0.20.8/tree-sitter.js) and [tree-sitter.wasm](https://github.com/tree-sitter/tree-sitter/releases/download/v0.20.8/tree-sitter.wasm) from the latest [release v0.20.8](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.20.8) as well as `tree-sitter-javascript.wasm` generated following the [instructions here](https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web#generate-wasm-language-files) I keep getting

> Bad pattern structure at offset 104: 'operator: "-=" @operator'...

**Comment by raczosala** [comment]
seems like `operator` is not part of the `augmented_assignment_expression` grammar in the npm release `0.19.0`, it works using building it from master 👍
