### ISSUE TITLE
"Completely external" scanners?

### ISSUE THREAD

**Issue by rpjohnst** [tree-sitter/tree-sitter#2379]
I'm interested in using tree-sitter to parse a language which has a fairly involved lexing phase. As an example of what goes on here, imagine C-style macro expansion- so it's all done by the time tokens are produced, but it doesn't have any connection to the structure of the eventual syntax tree.

Secondarily, I have an existing lexer implementation that already handles I/O (including integration with text editor buffers), source file encoding, position tracking, etc. It would be nice to be able to keep using this stuff underneath a tree-sitter parser.

It looks like the existing tree-sitter API expects to "own" source character decoding and position tracking, so while clients can supply their own `TSInput` for I/O and their own scan function for advancing character-by-character, they cannot directly provide a sequence of tokens from some opaque input source.

(I can imagine some ~~hacks~~heroics that might make this doable- marking all token kinds as external, and then storing some extra state in the scanner and returning zero-width tokens when they don't come directly from the source file. But this would still require plumbing some sort of source buffer through tree-sitter, even if a "fake" one, and potentially reworking a lot of the existing lexer.)

So, I wonder if the project would be open to the idea of a "completely external" scanner API: an opaque interface that provides tokens (perhaps with their source positions, textual forms, etc) without going through the `TSLexer` `lookahead`/`advance`/`mark_end` API. I imagine there might be some features that would constrain the behavior of an API like this- incremental re-parsing, for example? I'd be willing to contribute to the implementation, I just want to see whether this is in-scope or whether there might be a better design first.

**Comment by ahelwer** [comment]
Wouldn't this essentially involve a program that translates the parse tree from your parser into a tree-sitter parse tree? Is this already possible, making a parse tree yourself?

**Comment by rpjohnst** [comment]
I'm not producing a parse tree, just a flat sequence of tokens to be parsed. Sometimes this does involve reading a chunk of source and doing some computation to produce a sequence of tokens that's not just a simple segmentation of the chunk, but the chunk/sequence boundaries aren't really related to the syntax tree I'd eventually like to produce with tree-sitter.

**Comment by ahlinc** [comment]
Tree-sitter doesn't expose such internal machinery and doesn't have an API for that, may be in the future it would make sense.

I've added and additional tag to review this in the future but closing for now because it's out of scope.
