### ISSUE TITLE
Help parsing after an error

### ISSUE THREAD

**Issue by trysten** [tree-sitter/tree-sitter#238]
Hello Max and friends. 😄 

See https://github.com/trysten/tree-sitter-sql/tree/simplified

I'm having trouble recovering from this erroneous comma in trying to make an SQL grammar:
```sql
SELECT Author, FROM Books;
             ^ this comma is an error in MySQL, I think
```
I'm sure blacklisting FROM isn't the answer, but I haven't able to get what I'm expecting in a few weeks so I need some help. Something like:
```
(statement
  (select_clause
    (column)
    (ERROR (delim))
  )
  (from_clause (table))
)
```
I've tried:
```javascript
prec(1,'FROM')
// doesn't work, I think because we're already 'in' a sequence expression?
prec.dynamic(1,'FROM')
// doesn't work, but does generate a "Missing FROM" error which is cool.
```
I've tried setting negative precedence on the sequence. I tried flattening the grammar so it wasn't 'inside' a sequence when it hits the 'FROM' but it doesn't get that flat. I think the answer is to use GLR on the sequence expressions but I can't figure out how. Can I get a little help or perhaps an example of how to handle an erroneous delimiter? 

p.s. where else could I have asked for help?

**Comment by maxbrunsfeld** [comment]
What output are you currently getting when you parse that erroneous query?
