### ISSUE TITLE
Update link to Lua grammar

### ISSUE THREAD

**Issue by ghost** [tree-sitter/tree-sitter#2439]
The Lua grammar listed on the website (https://github.com/Azganoth/tree-sitter-lua) doesn't seem to work with the latest tree-sitter. Neovim[1] and Emacs (WIP) are using https://github.com/MunifTanjim/tree-sitter-lua which is already packaged by Alpine[2] and NixOS[3] and is in the works for Debian[4].

Could the link be changed or have Munif Tanjim's grammar also listed?

1: https://github.com/nvim-treesitter/nvim-treesitter/blob/main/lua/nvim-treesitter/parsers.lua#L948
2: https://pkgs.alpinelinux.org/package/edge/community/x86/tree-sitter-lua
3: https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/tools/parsing/tree-sitter/grammars/tree-sitter-lua.json
4: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1034075

**Comment by theHamsta** [comment]
This repository is very open to list grammars in their website. A change is fastest integrated with a PR adding the additional parser.

You would need to do the appropriate change here https://github.com/tree-sitter/tree-sitter/blob/89c2ab926fda33a9ee6b2e70e3b4f02eb2fa196d/docs/index.md#L89 (e.g. listing both parsers)
