### ISSUE TITLE
Partial parser regeneration

### ISSUE THREAD

**Issue by B1Z0N** [tree-sitter/tree-sitter#2442]
Most of the time writing grammar one makes small changes and tests if it works. The `Tree-sitter` generation process might sometimes take too long, especially if we're talking about some small changes in a huge grammar(for example any `SQL` grammar). So speeding up the feedback loop might save lots of developers time.

I only propose to **think** about ways of making it more incremental instead of generating the parser from the ground up every time. But:

1. I am not yet sure how to do this, this is just a request for comments on the matter.
2. I am not sure if it's not already there. At least from a user perspective, it seems that it's not.
3. I don't know what are and whether the costs of the solution are bearable.

But I hope to get some info and potentially get things going. If it's possible, but no one has time for that, then I'll put it on my open-source to-do list. **PS: thx for the great tool.**

**Comment by ObserverOfTime** [comment]
This is not feasible since it's likely that a small change in `grammar.js` will actually result in many changes in `parser.c`.
