### ISSUE TITLE
Support non-syntactic type names in queries?

### ISSUE THREAD

**Issue by kevinushey** [tree-sitter/tree-sitter#2449]
As an experiment, I tried developing a grammar that uses the actual operator token text as the types for their nodes. So, for example, `a + b` might be parsed with:

```
seq(field("lhs", $._expression), field("operator", "+"), field("rhs", $._expression))
```

and so you get a node like:

```
(+
  lhs: (identifier)
  rhs: (identifier))
```

This, IMHO, feels more natural than giving names to nodes, especially in a dynamic language where `+` might mean "add numbers" or "concatenate strings" depending on the types of the operands.

The generated grammar does work, but runs into trouble when you try to query such nodes, since the following isn't accepted by the query parser:

```
(+ lhs: (identifier) @lhs)
```

As far as I know, there isn't a way to quote such non-syntactic names. I was hoping that this might work:

```
(`+` lhs: (identifier) @lhs)
```

Could quotation of such non-syntactic names be supported? Or, is there another approach I'm missing?

For reference, the grammar: https://github.com/r-lib/tree-sitter-r/blob/c55f8b4dfaa32c80ddef6c0ac0e79b05cb0cbf57/grammar.js

**Comment by kevinushey** [comment]
> Actually when you do language analysis you'd need that actual meaning like "add numbers" or "concatenate strings".
I don't think that such additional complexity for queries logic worth it.

Maybe I'm misunderstanding, but I'm thinking in our case we'd use queries to find nodes of interest, and then later use the tree-sitter API combined with semantic information about the code / runtime state that we have to perform further analysis (e.g. diagnostics). In other words, I don't think that semantic meaning could be encoded into the AST either way, and I don't think it's relevant for how queries are structured?

The use of aliases does help in our case, since we can then query nodes with something like:

```
(_ operator: (_) @op (#eq? @op "+"))
```

That is, match any nodes with a named 'operator' field, whose operator field has contents `+`. Still not at clean as just having a type name that matches the operator token value, but it does work... but I imagine it's going to be a fair bit slower than if we could just use something like:

```
(`+`)
```

to query any nodes of type `+`.

**Comment by ahlinc** [comment]
> but I imagine it's going to be a fair bit slower

If you have concerns about performance then you can reorganize your grammar to produce additional parent nodes according to the operation as I've shown on the above screenshot and match against such nodes directly without predicates.

**Comment by kevinushey** [comment]
Right, but my point is that this would be unnecessary if we could use non-syntactic names in queries. Of course, I could just name the node types like `plus` and `minus` instead of `+` and `-` to get the same effect, and query for nodes of type "plus" instead of type "+".

Either way, I get the impression that this is unlikely to be implemented so I'll close the issue.

**Comment by ahlinc** [comment]
You wanted something similar like in https://github.com/tree-sitter/tree-sitter/issues/2056 (see screenshot) but for queries, there I've described pros and cons of such _visual substitutions_ for node kinds and for queries would be similar situation. It's not always good to hide information just for a visual effect.
