### ISSUE TITLE
TreeCursor::goto_first_child_for_byte() unexpected behavior

### ISSUE THREAD

**Issue by helixbass** [tree-sitter/tree-sitter#2463]
Hi, I am running into what looks to me like a bug with the behavior of `TreeCursor::goto_first_child_for_byte()`

Here is a test case (if you run `cargo test` you see a test failing that seems like it should be passing): https://github.com/helixbass/tree-sitter-goto-first-child-for-byte-sanity-check

Here is debugging output from the failing test case:
```
walk_root_cursor_to_node() target node: {Node . (0, 33) - (0, 34)}
walk_root_cursor_to_node() current cursor node: {Node program (0, 0) - (0, 41)}
walk_root_cursor_to_node() current cursor node: {Node variable_declaration (0, 0) - (0, 41)}
walk_root_cursor_to_node() current cursor node: {Node variable_declarator (0, 4) - (0, 41)}
walk_root_cursor_to_node() current cursor node: {Node call_expression (0, 8) - (0, 41)}
walk_root_cursor_to_node() current cursor node: {Node member_expression (0, 8) - (0, 38)}
member_expression child: {Node function (0, 8) - (0, 33)}
member_expression child: {Node . (0, 33) - (0, 34)}
member_expression child: {Node property_identifier (0, 34) - (0, 38)}
walk_root_cursor_to_node() current cursor node: {Node function (0, 8) - (0, 33)}
walk_root_cursor_to_node() current cursor node: {Node statement_block (0, 19) - (0, 33)}
walk_root_cursor_to_node() current cursor node: {Node } (0, 32) - (0, 33)}
```
 This corresponds to the JS source code:
```
var a = function() { return 12; }.bind(b)
```
And it is trying to use `TreeCursor::goto_first_child_for_byte()` to go from the root node to the `.` node

So you can see that when it gets to the `member_expression` node it appears to pick the "wrong" child node

I thought maybe it was a simple off-by-one but another test case for going from the root node to the `}` node in that same source code passes

I don't know C well enough to read the underlying C library code and try and provide a fix

**Comment by amaanq** [comment]
Fixed in https://github.com/tree-sitter/tree-sitter/pull/3263
