### ISSUE TITLE
Does `tree-sitter highlight` evaluate predicates?

### ISSUE THREAD

**Issue by TomLebeda** [tree-sitter/tree-sitter#2469]
Greetings, 

does the CLI tool for highlighting evaluate predicates? I would like to use the more complex highlighting querries from nvim-treesitter repo, but it doesn't seem to capture the nodes with predicates. 

For example the `self` keyword in python isn't highlighted when using the CLI tool, but Neovim can differentiate it. 

The TreeSitter's website states that "Predicates are not handled directly by the Tree-sitter C library. They are just exposed in a structured form so that higher-level code can perform the filtering." but I don't know if the CLI tools is considered "higher-level"? 

For better context: I'm trying to write a LaTeX generator that would use TreeSitter's awesome highliting powers to generate pretty listings. Something like `minted` package. 

Thanks

**Comment by amaanq** [comment]
Neovim uses a different set of predicates.

**Comment by amaanq** [comment]
yes, I think it's just eq? match? and is? that are supported, as well as their complements

**Comment by sogaiu** [comment]
To add a tidbit, I think there is also `set!` for language injection:

```
You can also force the language using the #set! predicate. For example, this will force the language to be always ruby.

((heredoc_body) @injection.content
 (#set! injection.language "ruby"))
```

via https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection
