### ISSUE TITLE
`optional()` function silently accepts multiple arguments

### ISSUE THREAD

**Issue by Tombez** [tree-sitter/tree-sitter#247]
In `grammer.js`, I wrote:
```js
optional(
  "<",
  repeat1($._type),
  ">"
)
```
when I meant to write:
```js
optional(seq(
  "<",
  repeat1($._type),
  ">"
))
```
`tree-sitter generate` succeeded, and my parser had unexpected behavior which caused me confusion for longer than I'd like to admit.

Could the `optional()` function, (maybe `repeat()` and `repeat1()` too?), be changed to loudly cause an error if they are passed too many arguments?

I think that might save some debugging for others in the future.

**Comment by maxbrunsfeld** [comment]
This fix will go out in version `0.14.1`.
