### ISSUE TITLE
Adding vala bindings

### ISSUE THREAD

**Issue by albfan** [tree-sitter/tree-sitter#248]
Basic implementation is done on

https://gitlab.gnome.org/albfan/vala-tree-sitter

Let me know if there's any workflow to update docs, if not I can figure out myself

**Comment by drom** [comment]
:+1: Added you to the list https://github.com/drom/awesome-tree-sitter

**Comment by albfan** [comment]
Thanks. Will let you know if this gets into an official GNOME repo

**Comment by taozuhong** [comment]
> Basic implementation is done on
> 
> https://gitlab.gnome.org/albfan/vala-tree-sitter
> 
> Let me know if there's any workflow to update docs, if not I can figure out myself

the link can't be accessed.

**Comment by albfan** [comment]
@taozuhong it's available again, removing this noise

**Comment by albfan** [comment]
@taozuhong https://gitlab.gnome.org/albfan/vala-tree-sitter is available
