### ISSUE TITLE
Release process transparency

### ISSUE THREAD

**Issue by XVilka** [tree-sitter/tree-sitter#2501]
Currently it seems there is no way to know what is expected for the next release and how soon (roughly, obviously) it is planned to happen.

There is a [roadmap towards 1.0](https://github.com/tree-sitter/tree-sitter/issues/930) but it's far away and minor releases happen all the time before that.

Having something like milestones or rough description of the wishlist for the next minor release would be awesome.

**Comment by amaanq** [comment]
I agree milestones/a more scoped target list for the next release would be better. I actually do believe we are due for a release soon, but we want to first fix the error recovery regression (hopefully Max will see about fixing this week)

I'm shooting for end of month for a new release, but it could be delayed

**Comment by ahlinc** [comment]
I didn't finished all CI related things to be ready for the release yet.

**Comment by ahlinc** [comment]
* _Related:_ #2387

**Comment by ahlinc** [comment]
By the way, I've implemented latest CI improvements in a way that allow to open a **draft** release PR and keep it existing by re basing it from time to time on the master branch. I thought to maintain a list of what was added in such PR's description and may be even  use such list later in a changelog file and on the GH releases page. Such PR would allow to have discussion right on it and have a review of multiple times by multiple people for release notes maintained in its description. Such PR can be pinned on top of issues for visibility.

**Comment by pascalkuthe** [comment]
> I agree milestones/a more scoped target list for the next release would be better. I actually do believe we are due for a release soon, but we want to first fix the error recovery regression (hopefully Max will see about fixing this week)
> 
> I'm shooting for end of month for a new release, but it could be delayed

I just wanted to reach out and ask if you still plan to do a release this month. We have beeb blocking the helix release on the next TS update for a while. We currently pinned a git commit as the master branch contains some bugfixes that are very relevant to us.

We don't mind releasing with a pinned git version but downstream package managers usually have problems when we use git dependencies (instead of a crates.io release). If you think the release is still some ways off then it probably makes more sense for us to release with a git dependency anyway.

**Comment by ahlinc** [comment]
@pascalkuthe I don't want to make a new release without finished CI improvements and a clear components versioning policy + fixed https://github.com/tree-sitter/tree-sitter/labels/P-high issues. I'll try to manage all of that till the end of this month.

**Comment by dundargoc** [comment]
I've added milestones for next patch, next minor and next major based on roadmap issues. I'd say that would qualify. I've explicitly not added any dates for now as those can set incorrect expectations, but we could add them in later if we're feeling brave for some reason.
