### ISSUE TITLE
Blocks ESLint lints with flow language

### ISSUE THREAD

**Issue by gnoff** [tree-sitter/tree-sitter#253]
Likely not the repo for this but in case it is

in Atom i rely on ESLint and historically used language-babel for js files. One of the updates caused tree-sitter language implementations to take precedence and I installed language-typescript for unrelated reasons. After this change the default language for .js files that had @flow near the top was Flow Javascript (From language-typescript package)

After that, ESLint would not run or at least would not report in the Linter UI within Atom. If I changed the language type to Babel or to Javascript the errors would appear.

I would appreciate a redirect to whatever package is likely 'responsible' for this incompatibility and I'll take the report that way.

Thanks,
Josh

**Comment by Arcanemagus** [comment]
Duplicate of https://github.com/atom/language-typescript/issues/29.

Note that for `linter-eslint` you can simply add `source.flow` to the "Scopes" option to enable it for those files.

**Comment by gnoff** [comment]
Thanks!
