### ISSUE TITLE
Unsound FFI functions in `*/c_lib`

### ISSUE THREAD

**Issue by oskgo** [tree-sitter/tree-sitter#2537]
Disclaimer: This is closer to a nitpick than a serious vulnerability.

Many of the functions in `*/c_lib.rs` are unsound. Since these are part of the public API, even on the Rust side, I believe they should be marked `unsafe` if calling them from safe Rust can lead to UB.

As an example [ts_tagger_delete](https://github.com/tree-sitter/tree-sitter/blob/70766f53275612e363410f71f58ae8ef1351dd3e/tags/src/c_lib.rs#L70C58-L70C58) can lead to double free or out of bounds access in safe rust. A snippet demonstrating this in the playground, which can be checked with Miri: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b34b49cac043bf4101077d5a1ab7d786.

I've verified the same example locally using the actual function found in the `tree-sitter-tags` crate.

**Comment by amaanq** [comment]
I agree that the C functions that dereference raw pointers should be marked unsafe, thanks for the report
