### ISSUE TITLE
Using parsers in C++

### ISSUE THREAD

**Issue by Aerijo** [tree-sitter/tree-sitter#254]
I'm still new to this, so I'm not sure how to set it up.

I'm trying to use a Tree-sitter parser in C++. I've added `tree-sitter` and `tree-sitter-latex` as git submodules, and have run `script/configure`, `script/build` on `tree-sitter`. After some struggles (`runtime.c` existed but needed to be moved up a folder), I believe `tree-sitter` is working.

However, when I use
```
extern "C" {
    #include <parser.c>
}
```
I get a lot of `sorry, unimplemented: non-trivial designated initializers not supported` errors. I'm not sure if I can go on from here. 

This is my current CMakesList.txt file if it helps
```
cmake_minimum_required(VERSION 3.12)
project(latex_language_server)

set(CMAKE_CXX_STANDARD 17)

include_directories(src)

add_executable(latex_language_server
        src/main.cpp
        src/communications.cpp
        src/message_handler.cpp
        src/message_handler.h
        src/message.cpp
        src/message.h
        third_party/tree-sitter/libruntime.a
        third_party/tree-sitter/src/runtime.c)

target_include_directories(latex_language_server PRIVATE
        third_party/rapidjson/include
        third_party/tree-sitter/include
        third_party/tree-sitter/src
        third_party/tree-sitter/externals/utf8proc
        third_party/tree-sitter-latex/src
        )
```

**Comment by maxbrunsfeld** [comment]
> I get a lot of sorry, unimplemented: non-trivial designated initializers not supported errors.

Yeah, you want to compile `parser.c` as a separate file, rather than `#include` it into some C++ code. I believe in CMake, that means you add `parser.c` to the list of source files that you'd pass to the `add_executable` function.

```
add_executable(latex_language_server
  src/main.cpp

  path/to/tree-sitter-latex/src/parser.c
  path/to/tree-sitter-latex/src/scanner.cc

  ...
)
```

Then, to use the parser in a C++ file, you just declare it like this:

```cpp
extern "C" { TSLanguage *tree_sitter_latex(); }
```

To be clear, you still *do* need to `#include` header files like `tree_sitter/runtime.h`, it's just not the way to include `.c` files into a C++ project.

**Comment by Aerijo** [comment]
@maxbrunsfeld Thanks! It appears to be working now.

**Comment by apgrc** [comment]
I installed `tree-sitter` and `tree-sitter-cpp` (on arch using the aur) and to use them with cmake I added
```cmake
find_library(tree-sitter tree-sitter REQUIRED)
find_library(tree-sitter-cpp tree-sitter-cpp REQUIRED)

...

target_link_libraries(${executable} LINK_PUBLIC tree-sitter tree-sitter-cpp)

```
If someone else also prefers to not have the `tree-sitter` sources inside the project.

**Comment by Icyrockton** [comment]
```cmake
cmake_minimum_required(VERSION 3.23)
project(test)

message(STATUS "${CMAKE_CURRENT_SOURCE_DIR}")

set(CMAKE_CXX_STANDARD 14)

# add tree-sitter target lib 
add_library(tree-sitter  /path/to/tree-sitter/lib/src/lib.c)
target_include_directories(tree-sitter PUBLIC /path/to/tree-sitter/lib/src /path/to/tree-sitter/lib/include)


add_executable(test main.cpp)
target_link_libraries(test tree-sitter) # link tree-sitter
```
