### ISSUE TITLE
Makefile doesn't set pkgconfig file permission correctly

### ISSUE THREAD

**Issue by xuan-w** [tree-sitter/tree-sitter#2542]
When I clone the code, run "sudo make install" to install tree-sitter to system, the pkg-config file "/usr/local/lib/pkgconfig/tree-sitter.pc" is only readable by root. 

So when the user need to compile a program requiring tree-sitter, the user shall need to "sudo", which is not right.

**Comment by ahlinc** [comment]
@xuan-w Thank you for the report!
