### ISSUE TITLE
Newly added GCC pragma causes warning when building in non-GNU compilers

### ISSUE THREAD

**Issue by DennySun2100** [tree-sitter/tree-sitter#2548]
..\tree-sitter\tree-sitter\lib\include\tree_sitter\api.h(4,9): warning C4068: unknown pragma 'GCC'
..\tree-sitter\tree-sitter\lib\include\tree_sitter\api.h(1168,9): warning C4068: unknown pragma 'GCC'

Here is the way to suppress this warning:

```
#ifdef __GNUC__
#pragma GCC visibility push(default)
#endif
```

**Comment by DennySun2100** [comment]
The PR is out https://github.com/tree-sitter/tree-sitter/pull/2549

**Comment by ahlinc** [comment]
Thank you for the report and the PR!
