### ISSUE TITLE
get_column segfaults when called while lexer->eof(lexer) == true

### ISSUE THREAD

**Issue by Magmi183** [tree-sitter/tree-sitter#2563]
Calling `lexer->get_column(lexer)` will result in **Segmentation fault** if the condition of `lexer->eof(lexer)` is met.

In other words, when you try to get column when at the end of the file, it segfaults. Took me some time to figure that out, resolved the issue locally by creating a simple wrapper:

```c++
uint32_t get_column(TSLexer *lexer) {
        if (lexer->eof(lexer)) {
            return 0;
        }

        return lexer->get_column(lexer);

}
```

**Comment by Magmi183** [comment]
I did some more testing and I think it is a bug because **it does not always crash**, but rather behaves unexpectedly. For example, it never crashes when the source file ends with a newline. 

Here are simple steps to **reproduce** this behaviour:
1. Make a grammar with one external symbol so that the scanner will get called. Make the grammar one rule only, consisting of that external symbol. Like this:
```javascript
module.exports = grammar({
    name: 'woowoo',

    externals: $ => [
        $.test,
    ],
    
    rules: {
        source_file: $ => seq(
            $.test
        ),
    },
});
```
2. Paste this at the beginning of your `scan` function:
```c++
while(true){
   lexer->advance(lexer, false);
   lexer->get_column(lexer);
}
```

---

The parser will crash on `get_column` on this file:
```text

Hello
```

but **not** on this file:
```text
Hello
```

and also **not** this file:
```text

Hello

```

When parsing the first file, a segfault will occur. When parsing the second or third file, it will just loop forever (expected behavior IMO).

**Comment by amaanq** [comment]
I can reproduce this, thanks for the detailed report.

**Comment by Magmi183** [comment]
Thanks a lot. I really like Tree-sitter and appreciate your time working on this

**Comment by amaanq** [comment]
Very glad to hear, hopefully no more crashing for you now!
