### ISSUE TITLE
"zero or more spaces" fails

### ISSUE THREAD

**Issue by solfisher** [tree-sitter/tree-sitter#2572]
in gemini gemtext markup, a quote is defined by `>`, followed by zero or more spaces, followed by some text.

while trying to implement that, i stumbled upon a problem: only when `>` is followed by **one** or more spaces does the markup trigger, otherwise it just defaults to normal text.

here is a minimal example (the real problem spans across most gemtext tags):

```js
module.exports = grammar({
  name: 'gemini',
  // control whitespace explicitly, this is because gemtext works on a per-line basis
  extras: $ => [],

  rules: {
    source_file: $ => repeat(seq(
      choice(
        $._space,
        $.text,
        $.quote,
      ),
      '\n',
    )),

    _space: $ => repeat1(' '),
    _word: $ => /\S+/,
    text: $ => seq(optional($._space), repeat1(seq($._word, optional($._space)))),
    quote: $ => seq('>', $.text),
  }
});
```

when running this, one would expect `>hello` to parse as a quote, however it does not.
if i remove `$.text`, it does work, but now regular text doesn't parse and errors.
in this case i'd expect a conflict to happen? but for some reason it just Chooses `$.text`, no matter how much precedence i give it.

**Comment by amaanq** [comment]
A regex will match more greedily than strings, text can be anything *including* <, to fix that you change your _word rule like so:

`_word: $ => /[^>]\S+/`

So it can't start w/ a >

You can also give quote's '>' a higher lexical precedence (above regex). Note that lexical and parse precedence are *different*:

`quote: $ => seq(token(prec(1, '>')), $.text)`

**Comment by solfisher** [comment]
the first option wouldn't work since lookaround is disabled and some of the other options are multi-charactered, however the second option seems to work great, thanks!
