### ISSUE TITLE
MacOS 10.13, Visual Studio Code 1.3, Bash IDE, trying to install the bash-language-server

### ISSUE THREAD

**Issue by AUsernameWhichIsNotTaken** [tree-sitter/tree-sitter#259]
Hello everyone, just wanted to have this extension in VSCode and did what I was told:

npm i -g bash-language-server

and got:

configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bash-language-server/node_modules/tree-sitter-bash
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! tree-sitter@0.13.23 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter@0.13.23 install script.
npm ERR! This is most likely a problem with the tree-sitter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls tree-sitter
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 17.7.0
npm ERR! command "node" "/usr/local/bin/npm" "i" "-g" "bash-language-server"
npm ERR! cwd /Users/[...]
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE

[npm-debug.log](https://github.com/tree-sitter/tree-sitter/files/2723720/npm-debug.log)

**Comment by Arcanemagus** [comment]
You're running a version of Node.js from 2014-06-09, you'll want to update that to the latest version of Node.js v6 at a _minimum_, note that LTS support for that ends in 3 months though.

If you are still running into issues after fixing that you should file this on [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash) as this has nothing to do with the base `tree-sitter`.

Thanks for taking the time to file an issue!

**Comment by AUsernameWhichIsNotTaken** [comment]
> On 3. Jan 2019, at 19:19, Landon Abney <notifications@github.com> wrote:
> 
> You're running a version of Node.js from 2014-06-09, [...]
> 
Thank you for your help!

Stephan
