### ISSUE TITLE
webassembly (wasm) resolveGlobalSymbol returns undefined

### ISSUE THREAD

**Issue by jamra** [tree-sitter/tree-sitter#2610]
I've been working on a tree-sitter grammar and have been going back and forth between writing an external scanner and just using grammar rules. Finally, I settled on a very small external scanner in c++, but all of a sudden my wasm build is broken. It was working during each iteration previously. I'm not sure how it happened, but a couple of symbols are not being resolved. Printing the params that goes into `resolveGlobalSymbol`, I see that 
`_ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC2B6v15007IDnEEPKc`
`_ZNKSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7compareEPKc`
do not resolve. My guess is that this is a libc++ symbol. 
I'm running osx on an M1 mac and using tree-sitter 0.20.8. My node version is v18.5.0. I've tried using `tree-sitter build-wasm ./my-grammar` and `tree-sitter build-wasm --docker ./my-grammar` but neither work. Any suggestions would be appreciated. 

Edit: I realized after posting this that I didn't post the actual error thrown. `return r || (r = resolveSymbol(t)), r.apply(null, arguments)` is the error that is thrown from tree-sitter.js (when I appropriately format it).

**Comment by amaanq** [comment]
yeah it's a C++ symbol we don't include that compares strings, this is a nuisance we want to get rid of in the future but for the time being I *highly* recommend using C, imo using C++ reduces portability and the std::string container is overkill for logic that can be done by just using a simple char buffer in C. Look at bash, php, hcl, or racket for examples of a scanner using a simple string struct in C

**Comment by jamra** [comment]
Can I amend my C++ so that it doesn't include that symbol? I ran a lot of tests to make sure this works the way it is. I created a C alternative but keep running into issues with my poor C skills such as using strcmp and not getting proper outputs.

**Comment by amaanq** [comment]
Yeah, you can use c++filt to see what the actual symbol is demangled:

First one might have a typo or just fails, second one is:
`std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >::compare(char const*) const`

Which isn't pretty, but is more understandable. You can also just compile the scanner.c as a standalone shared object then run nm on it to see the symbols, and then keep recompiling while removing potential spots where the compare function might have been at.

I understand the aversion to C, it's not the easiest to use and properly handle, but I think my container in the grammars I mentioned above have good sanity macros/functions to help you use it properly - here's the one for php https://github.com/tree-sitter/tree-sitter-php/blob/ce2c73a8d84b5648e8792698dc9fd955e5f6a906/src/scanner.c#L86

**Comment by jamra** [comment]
After looking at the posted link, it became really easy to write this in C. Basically, the string manipulation functions completely replace the C++ ones. However, I am running into this issue [244](https://github.com/tree-sitter/tree-sitter-typescript/issues/244). Once that issue is resolved, I think this will be fine. I wish we had the ability to write the external scanners in Rust.

**Comment by amaanq** [comment]
> I think this will be fine. I wish we had the ability to write the external scanners in Rust.

But this kills the portability that tree-sitter intends to have ;)

**Comment by jamra** [comment]
In order to make this work in wasm with strcmp, I had to build web-tree-sitter from source on the `master` branch. I wanted to update that info here because your linked tree-sitter-php will have the same issue since you also use strcmp. But now it works. Thanks for all the support.
