### ISSUE TITLE
Copy-on-write TSTrees

### ISSUE THREAD

**Issue by davidbalbert** [tree-sitter/tree-sitter#2612]
I’m integrating Tree-sitter with some Swift code, and for reasons unrelated to this question, I’m not using the SwiftTreeSitter bindings. 

Ideally, I’d like to store a TSTree in a Swift struct. Structs have “value semantics” (i.e. in `var x = Tree(); var y = x;` y is a copy of x) and Swift doesn’t have copy constructors, so there’s no hook I can use to call ts_tree_copy every time a copy of the Swift struct is made.

The common pattern to deal with structs that share some sort of underlying resource is copy-on-write. It looks something like this:

```swift
// classes are heap allocated and passed by reference
class TreeStorage {
    var t: OpaquePointer // TSTree *t

    func copy() -> TreeStorage {
        TreeStorage(t: ts_tree_copy(t))
    }
}

struct Tree {
    var storage: TreeStorage

    func someNonmutatingOperation() -> Foo {
        return ts_tree_nonmutating_foo(storage.t)
    }

    mutating func someMutatingOperation() {
        if !isKnownUniquelyReferenced(&storage) {
            storage = storage.copy()
        }
        ts_tree_mutating_bar(storage.t)
    }
}
```

isKnownUniquelyReferenced is atomic, so in the above example, once a TreeStorage becomes shared, it becomes immutable. 

I’d like to figure out if this approach is feasible. 

Specifically, the docs say:

> Note that individual TSTree instances are not thread safe; you must copy a tree if you want to use it on multiple threads simultaneously.

Are there any non-mutating operations that are safe to perform on a TSTree that’s shared between threads, or are there truly no operations that are thread safe. 

There are definitely other ways to do this, so I’m not stuck if the answer is “no,” but this feels like the Swiftiest way to do it.

**Comment by maxbrunsfeld** [comment]
Sorry, I think that line in the docs is out of date. Non-mutating operations on `TSTree` are now safe to perform on multiple threads.

**Comment by davidbalbert** [comment]
Thank you! Very helpful.

I think this means that TSNodes and TSTreeCursors should be accessed from whichever thread their associated TSTree currently resides on, and if I need to have two copies of the same TSTree, one for each thread, the right thing to do to get nodes and cursors back is to copy the TSTree and then re-create the TSNode and TSTreeCursors that I need from the copied tree. Is this correct?

Also, are there any other types that work like TSTree in that they can have multiple concurrent readers but only a single writer and would thus benefit from the COW approach I outlined above?

**Comment by maxbrunsfeld** [comment]
Generally, there's no longer any hidden "interior mutability", and there's no mutable globals, so you use the const-ness of functions' parameters as a guide. You can use the Rust bindings as a reference.

**Comment by maxbrunsfeld** [comment]
> I think this means that TSNodes and TSTreeCursors should be accessed from whichever thread their associated TSTree currently resides on, and if I need to have two copies of the same TSTree, one for each thread, the right thing to do to get nodes and cursors back is to copy the TSTree and then re-create the TSNode and TSTreeCursors that I need from the copied tree. Is this correct?

I don't know. I'm not familiar enough with Swift to know how this is handled. I'm guessing that you need to treat nodes and cursors similarly to other "reference types", like iterators, which refer to an underlying resource.

In garbage-collected languages like JavaScript, we ensure that the JavaScript wrapper object for a `TSNode` contains a reference back to the wrapper object for the `TSTree`, in order to guarantee that the tree outlives the node.

**Comment by davidbalbert** [comment]
This is perfect. Thank you so much!
