### ISSUE TITLE
Library and release versions

### ISSUE THREAD

**Issue by casouri** [tree-sitter/tree-sitter#2613]
@ahlinc I noticed that the latest release version is 0.20.8, but the library version in the makefile is 0.20.10. Is that intentional? Are they version for different things?

**Comment by sogaiu** [comment]
May not answer the question, but for reference: https://github.com/tree-sitter/tree-sitter/issues/2387

**Comment by ahlinc** [comment]
> @ahlinc I noticed that the latest release version is 0.20.8, but the library version in the makefile is 0.20.10. Is that intentional? Are they version for different things?

In Makefile it's a version of the TS core lib that is written on pure C, that value in the Makefile wasn't properly maintained before for a long time.

For the next release there will be published a version policy between many TS components.

**Comment by casouri** [comment]
Ok, good to hear that! Then if we want the latest tree-sitter library, we should require 0.20.10, right?

**Comment by ahlinc** [comment]
> Then if we want the latest tree-sitter library, we should require 0.20.10, right?

Exactly, but there is no separate artifacts for the lib yet. You need to take a source code from the latest GH release or use packages from distros.
