### ISSUE TITLE
using end line as statement separator

### ISSUE THREAD

**Issue by APerricone** [tree-sitter/tree-sitter#262]
Hello, I have a problem, I want try to create a tree-sitter for harbour, it is a derivate of clipper, and uses new line as statement separator, so:
```
funcName(p1, p2,
         p3, p4)
```
is an error, but the semicolon is used as "continue statement", then this:
```
funcName(p1, p2, ;
         p3, p4)
```
is valid.
to complicate it, after semicolon is possible add comment, then this:
```
funcName(p1, p2, ; //p2 is the second parameter
         p3, p4)
```
is still valid.
to complete the semicolon can be used to separate statement in the same line, like:
` func1(a,b) ; func2(c,d) `
but it looks like I can not define these rules...

**Comment by APerricone** [comment]
I went ahead on this, I am near to resolve it, I am testing it.

I wrote on extras:
```js
  extras: $ => [
    /[ \t]/,
    $.comment,
    $._semicolonEndline,
  ],
```
then on rules:
```js
   _endline: $ => /[\r\n]{1,2}|;/,

    comment: $ => token(choice(
      seq('//', /.*/),  
      seq('&&', /.*/),
      // http://stackoverflow.com/questions/13014947/regex-to-match-a-c-style-multiline-comment/36328890#36328890
      seq(
        '/*',
        /[^*]*\*+([^/*][^*]*\*+)*/,
        '/'
      )
    )),
    
    _semicolonEndline: $ => token(seq(
      ";",
      /[\r\n]{1,2}/
    )),
```
and it looks working, but I am continuing

**Comment by maxbrunsfeld** [comment]
>  it looks working, but I am continuing

I'm going to close this out if you got it working. Let me know if you have other questions.
