### ISSUE TITLE
Ignore unicode whitespace

### ISSUE THREAD

**Issue by Mango0x45** [tree-sitter/tree-sitter#2621]
How can I ignore all whitespace characters in my grammar?  At the moment I have tried the following:

```js
_S: $ => /\s*/u
```

and I just throw in `$._S` everywhere.  This works for most forms of whitespace, but it breaks on things like a zero-width space.  Any ideas how to solve this?

**Comment by ThyThy2505** [comment]
_S: $ => /\s*/u

**Comment by Mango0x45** [comment]
> _S: $ => /\s*/u

As I stated in my previous message, I already tried this and it doesn't work.

**Comment by clason** [comment]
ignore the comment, it's spam (tree-sitter is plagued by those for some reason)

**Comment by bigquin99** [comment]
> How can I ignore all whitespace characters in my grammar?  At the moment I have tried the following:
> 
> 
> 
> ```js
> 
> _S: $ => /\s*/u
> 
> ```
> 
> 
> 
> and I just throw in `$._S` everywhere.  This works for most forms of whitespace, but it breaks on things like a zero-width space.  Any ideas how to solve this?

**Comment by sogaiu** [comment]
May be known already, but FWIW, for certain kinds of whitespace control, tweaking `extras` may be effective.

I don't know if that applies here though.

Some text from the official docs:

> In addition to the name and rules fields, grammars have a few other optional public fields that influence the behavior of the parser.

>    extras - an array of tokens that may appear anywhere in the language. This is often used for whitespace and comments. The default value of extras is to accept whitespace. To control whitespace explicitly, specify extras: $ => [] in your grammar.

via: https://tree-sitter.github.io/tree-sitter/creating-parsers#the-grammar-dsl

**Comment by Mango0x45** [comment]
For anyone who comes across this later, the regex to use is `/\p{White_Space}*/u`
