### ISSUE TITLE
[Feature Request] Add Gherkin (Cucumber) Parser

### ISSUE THREAD

**Issue by Drew-Daniels** [tree-sitter/tree-sitter#2630]
I use [Gherkin](https://cucumber.io/docs/gherkin/reference/) for writing Cucumber BDD tests. It'd be nice if there were a `tree-sitter` parser for this language.

I'd be interested in working on implementing this.

**Comment by ahlinc** [comment]
It would be awesome if you'd write such parser, after that you may open a PR to add to a list of parser in docs page.
But this issue is irrelevant for the Tree-sitter core, so I close it here.
