### ISSUE TITLE
feature: add --exclude to tree-sitter-test

### ISSUE THREAD

**Issue by 2ax3ax5** [tree-sitter/tree-sitter#2635]
It'd be nice if out of the box tree-sitter-test had a kind of exclude OPTION, a symmetric option to the already existing filter option.
```
$ tree-sitter test --help
tree-sitter-test 
Run a parser's tests

[...]

OPTIONS:
    -f, --filter <filter>       Only run corpus test cases whose name includes the given string
    -e, --exclude <filter>      Only run corpus test cases whose name does not include the given string
```

It'd be really cool if --filter and --exclude accepted a variable number of filters, instead of accepting only one.
```
    -f, --filter <filter>...    Only run corpus test cases whose name includes at least one of the given strings
    -e, --exclude <filter>...   Only run corpus test cases whose name does not include any of the given strings
```

**Comment by ahlinc** [comment]
Then it makes sense to rename the `--filter` to the `--include` for symmetry.

**Comment by sogaiu** [comment]
I prefer `--include` too as I think it's less ambiguous than `--filter`.  I think the latter could be interpreted as "filter to keep" or "filter to discard".
