### ISSUE TITLE
Creating a binary package

### ISSUE THREAD

**Issue by albfan** [tree-sitter/tree-sitter#265]
I'm using tree sitter on vala and I'm looking for a binary package for tree-sitter library.

It will be a library with core and all the parser generated from tars. Some parsers are not released so they will be builder from master tarball

There's a huge difference doing from tar (I get it now from tree-sitter as a submodule and clone it and all parsers take Gb)

Any official plans for that?

**Comment by maxbrunsfeld** [comment]
I don't have plans to do that; maintaining binary packages for different os distributions is a lot of work, and I probably won't have the bandwidth to do it anytime soon. If you're interested in creating one, that would be great!

**Comment by albfan** [comment]
Yes I will do as soon as I have a tree-sitter-xml parser, will reach you then, at least to mention somewhere.

**Comment by albfan** [comment]
@maxbrunsfeld after polish my AST workbench:

![tree-sitter-demo](https://user-images.githubusercontent.com/220968/62804443-9d43ea00-baed-11e9-97f6-fe5a9ce40ecc.gif)

I came out with this way to generate the library with all the bindings:

https://gitlab.gnome.org/albfan/gtk-code-folding-vala/blob/master/fetch-tree-sitter

It just fetch all the last stable releases and build using meson:

https://gitlab.gnome.org/albfan/gtk-code-folding-vala/blob/master/meson.build#L3

Maybe @Tingping (from meson) can suggest a better way to do it, I want to keep it simple to allow improvements.

I found some grammars (java, scala, css) do not have a stable release for last API so I open respective issues (like https://github.com/tree-sitter/tree-sitter-java/issues/50) just to avoid develop issues.

I'm still doing the vapi trick https://github.com/albfan/tree-sitter/tree/vala-binding2 because vala needs the new functions to return a pointer (I'm sure vala maintainer @ricotz knows how to bypass that but this is not my field really)

`meson.build` allow cross compiling and is multiplatform (windows, linux, mac, that I'm aware) It can be a project alone in future. Surely we will do a flatpak extension with it (can show how to use it on https://gitlab.gnome.org/albfan/gtk-code-folding-vala/issues/14) and if we do a code folding (and AST parser for GNOME Builder https://wiki.gnome.org/Apps/Builder) I'm sure many people will write more grammars for it without much problem. @chergert could jump in to suggest wrapping or better way to do it,

I should say that this mostly works and only needs new grammars if someone miss it. Maybe there're some further problems like absence of grammar versions (let's say java 5 java 6 java 7 java 9) but I'm sure this will fullfill most of the needs for everyone.

@maxbrunsfeld Just let me know if you want to do something about this (same for others mentioned) I think have an general AST tree parser deserve a couple of iterations

Thanks in advance for your time!

**Comment by albfan** [comment]
Currently, I moved all https://gitlab.gnome.org/albfan/gtk-code-folding-vala to use runtime and parsers from git submodules, so might be easier for anyone trying to use tree-sitter on vala and looking how to add a particular runtime and parser.

I'm inspecting https://github.com/nvim-treesitter/nvim-treesitter as it allows to do at execution:

    :TSInstall <language>

which is basically what I'm looking for. (looks like each language has a maintainer anyway, so basically what @maxbrunsfeld said)

**Comment by albfan** [comment]
I have to do  it: https://github.com/albfan/vim-tree-sitter
