### ISSUE TITLE
Missing parser for XML

### ISSUE THREAD

**Issue by albfan** [tree-sitter/tree-sitter#266]
I know tree sitter miss some parsers, but XML seems to me a big one.

Should I implement it or am I missing something really obvious?

**Comment by maxbrunsfeld** [comment]
Closing this out because we don't specifically plan to implement this, though anyone should be able to do it.

**Comment by XVilka** [comment]
There seem to be an NPM package, but wasn't able to find any sources for it https://www.npmjs.com/package/tree-sitter-xml

**Comment by unhammer** [comment]
@albfan I put the sources from the npm package at https://github.com/unhammer/tree-sitter-xml – I have no idea how to make tree sitter packages (or even use ones off npm) but perhaps this one could be a starting point for someone?

**Comment by albfan** [comment]
@unhammer I tested and works correctly for me. Just miss to parse prolog:

    <?xml version="1.0" encoding="UTF-8"?>

I will open issues on your repo

I miss tags for tree-sitter versions but master just works. @maxbrunsfeld is there a process to put parsers under this org. Cannot find anything under https://tree-sitter.github.io/tree-sitter/contributing

**Comment by albfan** [comment]
ping @unhammer about update tree-sitter-xml to latest runtime

**Comment by milahu** [comment]
another tree-sitter-xml: https://github.com/ObserverOfTime/tree-sitter-xml
