### ISSUE TITLE
require('nvim-treesitter.configs').setup delays startup of nvim test.cc by 185ms

### ISSUE THREAD

**Issue by AshrafMichail23** [tree-sitter/tree-sitter#2661]
## Describe the bug
For a config such as kickstart.nvim (https://github.com/nvim-lua/kickstart.nvim), wrapping the require('nvim-treesitter.configs').setup block in a vim.defer_fn(function()...end, 0) saves 185ms of startup time when I load a C++ file through the command-line with: nvim test.cc.

**Default init.lua:**
302.407  000.007: --- NVIM STARTED ---

**Adding vim.defer_fn around require('nvim-treesitter.configs').setup block:**
115.798  000.005: --- NVIM STARTED ---

The 185ms startup delay does not occur when loading a simple .txt file or .lua file.

Instead of each config needing to defer setup, should treesitter setup be async until after first render to improve the startup time of the "nvim test.cc" case?

## To Reproduce
0. Use kickstart.nvim init.lua (https://github.com/nvim-lua/kickstart.nvim)
1. Run nvim test.cc --startuptime default.log
2. Wrap the require('nvim-treesitter.configs').setup block in a vim.defer_fn(function()...end, 0)
3. Run nvim test.cc --startuptime defer_treesitter_setup.log

Notice the time delta to NVIM STARTED in logs.

## Neovim Version
v0.9.2

## Related issues
Proposal to defer treesitter setup in kickstart.nvim:
https://github.com/nvim-lua/kickstart.nvim/issues/435

**Comment by amaanq** [comment]
wrong repo
