### ISSUE TITLE
web-tree-sitter release

### ISSUE THREAD

**Issue by pokey** [tree-sitter/tree-sitter#2683]
Any timeline on a new release of web-tree-sitter? I'm hitting a bug on 0.20.8 that has been fixed on master

Thanks!

**Comment by pokey** [comment]
Would it be possible to give some insight into what's blocking the release process for web-tree-sitter? I'm sure you all have a lot on your plates, but from what I can tell, the artifacts are generated automatically in CI, so presumably there's some other hurdle here?

**Comment by amaanq** [comment]
There's a pre-release for 0.21.0 and 0.20.9 will be out pretty soon
