### ISSUE TITLE
[documentation] following instructions does not work for minimal grammar

### ISSUE THREAD

**Issue by tautologico** [tree-sitter/tree-sitter#269]
I'm following the documentation at https://tree-sitter.github.io/tree-sitter/creating-parsers and I install the tools as shown: `npm install --save nan && npm install --save-dev tree-sitter-cli`. I create the `grammar.js` file with the minimal grammar shown, and run `tree-sitter generate && npm install`. The latter step fails when compiling `parser.c`, complaining about a missing `parser.h`. There is no such file in the project tree.

As a workaround, I copy `parser.h` from this repo to a directory where the compiler was looking for includes, and it works. I do a `npm install tree-sitter` to see if it's the official way of fixing this; it does install a `parser.h` in `node-modules`, but compilation still fails. 

I may be missing something obvious because I'd expect this issue to be created sooner (sorry if this is the case), but if not, the documentation should include complete instructions to getting a grammar working.

**Comment by tautologico** [comment]
As per the instructions I just did `npm install tree-sitter-cli`. The version reported by npm is `tree-sitter-cli@0.14.0-beta3`

**Comment by maxbrunsfeld** [comment]
I'm surprised that `npm install` gave you a beta version 🤔 . That's for reporting that.

Anyway, I published a new beta release (`v0.14.0-beta4`) in which that bug is fixed. The 0.14 beta branch is almost ready for stabilization, so I'd recommend just upgrading to the latest beta (as opposed to reverting to 0.13).
