### ISSUE TITLE
Query result is empty when using `web-tree-sitter`

### ISSUE THREAD

**Issue by sangwoo-joh** [tree-sitter/tree-sitter#2699]
I'm using following settings:
 - node: v16.19.1

```
npm list      
...
├── @types/mocha@2.2.48
├── @types/node@8.10.48
├── jsonc-parser@2.1.0
├── tar@6.2.0
├── tree-sitter-cli@0.20.8
├── tree-sitter-cpp@0.20.1
├── tree-sitter-go@0.20.0
├── tree-sitter-javascript@0.20.1
├── tree-sitter-python@0.20.1
├── tree-sitter-ruby@0.19.0
├── tree-sitter-rust@0.20.1
├── tree-sitter-typescript@0.20.1
├── tslint@6.0.0
├── typescript@3.8.2
├── vscode@1.1.37
└── web-tree-sitter@0.20.8
```

 I've compiled one of the languages, say python, into `tree-sitter-python.wasm` file.

After that, I tried to figure out the query API with the following code: (using node interactive)

```javascript
Parser = require('web-tree-sitter')
await Parser.init()
Lang = await Parser.Language.load('tree-sitter-python.wasm')
parser = new Parser()
parser.setLanguage(Lang)

// sample code
code = 'x = 1 + 2'
tree = parser.parse(code)  // successfully parsed python code snippet

q = Lang.query('(expression_statement)')
q.matches(tree.rootNode)
```

The last statement, `q.matches(tree.rootNode)`, gave me this result: `[ { pattern: 0, captures: [] } ]`
I thought this would let me use the `captures` properly, but somehow it is empty.
Am I doing something wrong?

**Comment by sogaiu** [comment]
I think it's possible the following might work better:

```javascript
q = Lang.query('(expression_statement) @fun')
```

**Comment by sangwoo-joh** [comment]
@sogaiu Thank you very much!!!
I ran the code you gave me and got the results I was looking for.
So, if I understand correctly, I need to set the `name` with `@` to capture the matching results correctly?
Wow, that would allow me to use a query to capture the loose tree structure I want, while at the same time giving names to the specific nodes I want, which is really powerful.
Thanks for the answer. I'll look into it some more.
Have a great day!

**Comment by sogaiu** [comment]
> So, if I understand correctly, I need to set the name with @ to capture the matching results correctly?

That sounds about right.  In case you haven't seen it, may be you'll find [this bits of the docs](https://tree-sitter.github.io/tree-sitter/using-parsers#capturing-nodes) to be of some use.

Take care :)
