### ISSUE TITLE
Can’t use slashes in test names

### ISSUE THREAD

**Issue by robrix** [tree-sitter/tree-sitter#27]
While working on tree-sitter-ruby I tried naming a test `if/elsif/else` and later noticed that it wasn’t being run at all. Looks like it picked up later ones in the file alright tho.

**Comment by maxbrunsfeld** [comment]
Yeah, skipping tests is a really bad failure mode. Not sure why I wrote [this regexp](https://github.com/tree-sitter/node-tree-sitter-compiler/blob/master/lib/cli/test.js#L49) this way. Fixing...
