### ISSUE TITLE
Provide CLI flag to produce log.html without opening it

### ISSUE THREAD

**Issue by alanwsmith** [tree-sitter/tree-sitter#2709]
This is a feature request to add a flag to the command line tool that operates the same as `-D` but doesn't attempt to automatically open the `log.html` output file in the browser on macos. 

The HTML view is very useful for debugging but it's easy to end up with tons of tabs if/when the browser opens the file each time in a new one. 

Providing a flag to produce the file without opening it opens up the ability to use something like browser-sync to automatically update a single tab. It also allows for post-processing of the HTML before display (e.g. to add/apply a dark-mode stylesheet)

Since `-d` and `-D` are both used the new flag could be `-h` to represent the HTML without the attempt to open the file in the browser.

**Comment by amaanq** [comment]
Would you appreciate if it were an option to tweak in tree-sitter's `config.json`?

**Comment by alanwsmith** [comment]
Yeah, that would be great!

**Comment by amaanq** [comment]
Ok sorry, i think its better for this to be *opt in*, so the --open-log flag will enable this, and is now disabled by default on macos, and I've allowed every platform to open log.html with that flag. I overlooked this for a while since I work mostly on Linux :sweat_smile: sorry about that.
