### ISSUE TITLE
cicd: platform `linux-riscv64gc` failed - unsupported ISA subset `z`

### ISSUE THREAD

**Issue by ahlinc** [tree-sitter/tree-sitter#2712]
_Origin:_ https://github.com/tree-sitter/tree-sitter/actions/runs/6422575422/job/17475374284#step:16:162

CICD failed on master for the `linux-riscv64gc` platform, it seems there was something changed in a related cross-rs image.

_Needs more investigation._

**Comment by amaanq** [comment]
LLVM 17 broke cross cuz it uses an older GNU LD linker which doesn't recognize this `z` ISA subset that LLVM passes as a flag to LD. I don't think we want to consider risc-v testing as an issue until it's even possible.
