### ISSUE TITLE
I am attempting to build and use the `tree-sitter` .so library for Python 3.9 on my Mac with an M1 chip, and I am encountering an architecture compatibility issue.

### ISSUE THREAD

**Issue by rsagy** [tree-sitter/tree-sitter#2719]
Steps to Reproduce

1. Code used to build the library:
   ```python
   from tree_sitter import Language

   Language.build_library(
     'build/my-languages.so',
     [
       'vendor/tree-sitter-java',
       'vendor/tree-sitter-python'
     ]
   )
   
   2. 
   from tree_sitter import Language

   self.python_language = Language(my_languages_path, 'python')

**Comment by rsagy** [comment]
I encountered the following error:
'my-languages.so' mach-o file, but is an incompatible architecture, have 'x86_64', need 'arm64'

Environment Information:
Python Version: 3.9
Hardware:
Model Name: MacBook Pro
Model Identifier: MacBookPro18,2
Model Number: Z14X00072HB/A
Chip: Apple M1 Max
Total Number of Cores: 10 (8 performance and 2 efficiency)
Memory: 64 GB
System Firmware Version: 8422.141.2
OS Loader Version: 8422.141.2
Serial Number (system): M4460Q17KJ
Hardware UUID: 765E0845-A8D2-5026-985F-40A7C1C289FD
Provisioning UDID: 00006001-0018311E2685801E
Activation Lock Status: Disabled
Additional Information
Please provide any additional context or information that might be relevant to this issue. For example, have you tried any workarounds or solutions you found online?

Possible Solutions
If you have any ideas or potential solutions, please share them.

Screenshots or Error Logs
If applicable, include any relevant screenshots or error logs to help others understand the issue better.

Related Issues or References
If there are any related issues, pull requests, or external references related to this problem, please provide links to them.

arduino
Copy code

Make sure to fill in the relevant details such as your macOS version, Python version, and any additional context that may be helpful in diagnosing and solving the issue.




Thanks for any idea how to solve it

**Comment by amaanq** [comment]
You need to ensure your compiler is an arm/universal compiler, and not an x86 one on your mac. This seems like a path or installation issue on your end.
