### ISSUE TITLE
Add a `--test-input <test_number>` parameter for the CLI `parse` command

### ISSUE THREAD

**Issue by ahlinc** [tree-sitter/tree-sitter#2726]
It would be awesome if it would be easy to run `tree-sitter parse` command with a text input picked from any available test in the `test/` folder.

For this it's needed to:
* Implement a stable ordering for all tests stored in the test folder by sorting test files and sorting all inner test by titles. _I suppose tests already works in this way._
* Add a `--test-input <test_number>` flag the parse command that would list all test tree with numbers and when called with a test number would use that test source text as an input for the parse command.

Also it's possible to extend the test command with a list sub command for more comfortable tests listing and picking and it may be able optionally to list test inputs after test titles and may be even expected trees.

**Comment by sogaiu** [comment]
I can appreciate being able to do that especially to get more detailed info about failures.

May be you saw already, but to get that kind of result, I tried [putting my tests in an alternative form](https://github.com/tree-sitter/tree-sitter/pull/1536#issuecomment-1441512739).  Not suggesting any kind of change here, just pointing out for reference.
