### ISSUE TITLE
Memory leak in JavaScript parser (might affect all bindings)

### ISSUE THREAD

**Issue by stackmystack** [tree-sitter/tree-sitter#2731]
Hi,

I don't know whether this is the correct place to post the issue, or in the [JavaScript parser's repo](https://github.com/tree-sitter/tree-sitter-javascript), but given that I am trying to reproduce the example in your docs ([An Example Parser](https://tree-sitter.github.io/tree-sitter/using-parsers#an-example-program)), I figured I'd post it here first.

Edit: git bisect pointed at commit [`4f3fe20`](https://github.com/tree-sitter/tree-sitter-javascript/commit/4f3fe20cb518049f40752e1632a87a6960db73d9)as the culprit. Tag `v0.19.0` at [`efd8cc9`](https://github.com/tree-sitter/tree-sitter-javascript/commit/efd8cc9ee8eb919c2ca0f0eebaeb8f39557d8a8a) is good.

I am the maintainer of [ruby-tree-sitter](https://github.com/Faveod/ruby-tree-sitter) and this issue matters for all bindings; here's the minimum working example, compiled using the same instructions in the docs:

```c
#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <tree_sitter/api.h>

TSLanguage *tree_sitter_javascript();

int main() {
  TSParser *parser = ts_parser_new();
  ts_parser_set_language(parser, tree_sitter_javascript());

  const char *source_code = "a?.b";
  TSTree *tree = ts_parser_parse_string(
    parser,
    NULL,
    source_code,
    strlen(source_code)
  );

  TSNode root_node = ts_tree_root_node(tree);
  char *string = ts_node_string(root_node);
  printf("Syntax tree: %s\n", string);

  free(string);
  ts_tree_delete(tree);
  ts_parser_delete(parser);
  return 0;
}
```

*Expected*: to work and print the sexpression.
*Found*: the process just eats GBs of memory and hangs.

The problem is in the call to `ts_tree_root_node(tree);`, irrespective of the input. Actually, an empty input program also has the same effect.

Moreover, using the parser's tools, which go through `tree-sitter-cli`, work fine. It parses and produces the sexpression as expected, and the whole test suite passes. Which is another reason why I am compelled to report the bug here.

I'm using `tree-sitter v0.20.8`.

1. Is the example out of date?
1. Should the API be called differently?
1. Is it a bug in the grammar, and should I report it to the JavaScript parser maintainer?

**Comment by amaanq** [comment]
Seems to be a dupe of https://github.com/tree-sitter/tree-sitter-bash/issues/199

Do *not* link against stable tree-sitter with parsers generated from master

**Comment by stackmystack** [comment]
I can confirm it's related.

But what's puzzling me is that `TREE_SITTER_LANGUAGE_VERSION` and `TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION` seem to be superfluous in some sense.

Should there be another check to do before loading a parser?

**Comment by amaanq** [comment]
We're desperately due for a new release at the minimum because of this, I agree.

Please just rely on using TS master atm to generate if you notice this oddity - the issue arises from v0.20.8 installed to /usr/local/include or /usr/include and the include in grammars generated on 0.20.8 including it as <tree_sitter/parser.h>

**Comment by stackmystack** [comment]
Thanks. Actually regenerating with the latest tag fixes it, so I am closing the issue.
