### ISSUE TITLE
Pathetic 

### ISSUE THREAD

**Issue by Roguehal** [tree-sitter/tree-sitter#2740]
https://support.google.com/youtube/answer/6388789?nohelpkit=1&hl=en

**Comment by dundargoc** [comment]
no u

**Comment by Roguehal** [comment]
I mean God's a bit damn y'all went from stealing my repo last year they are
involved you lost then you still on here putting on for the put on with
Garrett Patterson song the rest of them stupid asses of get up that stupid
y'all pathetic let me tell you something fool I'm talking to you I say what
I want to now that I got that copyright if y'all keep on stealing my s***
I'm going to take your keys I said it don't give a damn you take me off I'm
going to come right back on you again any questions you better give SIXX
some respect I said that s***😘
