### ISSUE TITLE
Vue file can not open tree-sitter-mode.

### ISSUE THREAD

**Issue by arstum** [tree-sitter/tree-sitter#2754]
Emacs App.vue run tree-sitter-mode.Display error,(error "No language registered for major mode ‘vue-html-mode’")

**Comment by amaanq** [comment]
Not a tree-sitter issue

**Comment by arstum** [comment]
(vue-html-mode)

the same dispaly

**Comment by arstum** [comment]
tree-sitter did not support "vue" file?

**Comment by sogaiu** [comment]
The error message suggests that one of the contributing factors is in the configuration of the application.  It seems like that is Emacs in this case.

This is the repostiory for tree-sitter (the library and command line tool), so it probably doesn't make sense to start by asking here.

May be [this page](https://www.gnu.org/software/emacs/documentation.html) has some hints on where to ask.
