### ISSUE TITLE
tree-sitter-cli 0.20.8 parser generation varies across windows, macOS, and linux

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/tree-sitter#2755]
The tree-sitter-cli 0.20.7 package generates the exact same parser.c file on windows, macOS, and linux (modulo line-endings). You can see proof in [this](https://github.com/tlaplus-community/tree-sitter-tlaplus/actions/runs/6816957707/) recent CI run from tree-sitter-tlaplus, which includes steps checking that the committed parser.c file is the same as that generated by tree-sitter, across all three OSs.

This changes quite dramatically with 0.20.8, shown by [this](https://github.com/tlaplus-community/tree-sitter-tlaplus/actions/runs/6817049656) failing CI run. The parser.c file used in that CI run was generated & committed on a linux machine by tree-sitter 0.20.8. If I fetch that same branch on a macOS machine and again run `tree-sitter generate` with tree-sitter 0.20.8, it generates a very different parser.c file. If I run `git diff src/parser.c | wc` it shows that 43,240 lines changed.

I guess this isn't necessarily a bug, but given how tree-sitter grammars are packaged with generated files included in the repo I think it's really useful for the generation process to be deterministic across all platforms. This must have been a recent change because 0.20.7 works fine. Does anybody have any idea what change could have caused this divergence?

**Comment by ahelwer** [comment]
I'm trying to think about how I could whip up a git bisect script to isolate this. Would be somewhat difficult what with requiring the different OSs. Maybe a linux & macOS machine uploading files to a third server or something...

**Comment by sogaiu** [comment]
Just as a data point, I tried `generate` [1] with 6019b7c84cd5a7f580d57bb981315afd9afec826 on a Linux box and a Windows 10 machine but got the same result (checked the sha256 checksum).

I chose [a small grammar](https://github.com/sogaiu/tree-sitter-janet-simple) to test with.

---

[1] Using `--no-bindings` might speed things up a little bit -- that's what I did anyway.

**Comment by sogaiu** [comment]
I tried with [this commit](204e858899f7dd5713dea7b0148d6aa477d4a18f) of tree-sitter-tlaplus and the results were the same.

The sha256 checksum I got for `src/parser.c` was `143312507a72bd29800146bcd42f310cc4f6790714bb298bb43fc9f1e3002512`.

I should probably mention that I didn't follow all of [the steps in the README](https://github.com/tlaplus-community/tree-sitter-tlaplus#build--test).  I just cloned with `--recurse-submodules` and did `tree-sitter generate --no-bindings` after deleting `src/parser.c`.  So if the other steps could affect the outcome, this test was perhaps not so helpful.

**Comment by ahelwer** [comment]
@sogaiu that commit you pulled from tree-sitter-tlaplus uses tree-sitter-cli 0.20.7. Try the head of this branch https://github.com/tlaplus-community/tree-sitter-tlaplus/tree/ts-upgrade

**Comment by sogaiu** [comment]
For the test above, I built the tree-sitter cli from [this commit](https://github.com/tree-sitter/tree-sitter/commit/6019b7c84cd5a7f580d57bb981315afd9afec826) [1], removed `src/parse.c` in my locally cloned tree-sitter-tlaplus directory, and used the `generate` subcommand to create a new `src/parse.c`.

That seems like it should be enough -- or may be I'm missing something?

---

[1] The latest commit on the master branch of the tree-sitter repository.

**Comment by ahelwer** [comment]
Okay here's another weird data point - I checked out the head of that branch, generated the parser.c with 0.20.8 on macOS, and pushed *those* changes so they were picked up by the PR CI. It looks like 0.20.8 generates the same parser.c on both macOS and Windows, but not on Linux! https://github.com/tlaplus-community/tree-sitter-tlaplus/actions/runs/6825072048

I can also reproduce this locally. Perhaps try using the 0.20.8 release instead of the current tree-sitter repo head? On the other hand if this is already fixed in the head of main then there is no issue, I can just wait for the next release.

**Comment by sogaiu** [comment]
I'll try with 0.20.8, though I'm planning to build it.

**Comment by ahlinc** [comment]
```sh
# (main =) tree-sitter-tlaplus
> tree-sitter-0.20.7 g; git s; md5sum src/parser.c
## main...origin/main
ed2f67d328ba66221b57d09b73c3bdb8  src/parser.c

# (main =) tree-sitter-tlaplus
> tree-sitter-0.20.8 g; git s; md5sum src/parser.c
## main...origin/main
ed2f67d328ba66221b57d09b73c3bdb8  src/parser.c
```
I see no difference between mentioned Tree-sitter CLI versions. The same hash for the `src/parser.c` file produced on Linux and Windows platforms.
@ahelwer could you verify your committed `src/parser.c` file? It seems the problem is that it was generated by a mistake with some custom cli version or something similar.

**Comment by ahelwer** [comment]
@ahlinc how does that explain the CI runs? These are fresh checkouts & installs. Line endings are handled by running `git add . --renormalize`.

**Comment by sogaiu** [comment]
Just a side note, which may be irrelevant, but FWIW, I was building from the v0.20.8 tag, but that's not what 0.20.8 is based off of -- it's actually based off of [this commit](https://github.com/tree-sitter/tree-sitter/commit/0c49d6745b3fc4822ab02e0018770cd6383a779c) IIUC.

It's not likely the "older" short-lived version of 0.20.8 is being used somewhere in these tests, right?

**Comment by ahelwer** [comment]
The CI just runs `npm install` in the checked out repo, which downloads 0.20.8.

**Comment by ahelwer** [comment]
Okay here's another CI run with more diagnostic info added: https://github.com/tlaplus-community/tree-sitter-tlaplus/actions/runs/6825870927?pr=86

I printed out the tree-sitter version right before running generate (see the "Generate parser code" step) and printed out the md5 hash in the "List changes" step. Results:

| | Windows | macOS | Linux |
|-|-|-|-|
| TS version | 0.20.8 (0c49d67) | 0.20.8 (0c49d67) | 0.20.8 (d4c1bf7) |
| MD5 | ed2f67d328ba66221b57d09b73c3bdb8 | unknown/failed | 8c48646f85fad994105d801671d334f1 |

So this is important - it looks like there are multiple versions of 0.20.8 floating around that are being installed nondeterministically on the CI machines???

**Comment by sogaiu** [comment]
I got what you got on Linux for 0.20.7 and 0.20.8 [1]: `8c48646f85fad994105d801671d334f1`

That seems different from what @ahlinc mentioned above: `ed2f67d328ba66221b57d09b73c3bdb8`

---

[1] I built these both from source.

**Comment by ahelwer** [comment]
Okay so there are two npm packages floating around for 0.20.8: 0c49d67 and d4c1bf7. They generate a different parser.c file. How the heck does that happen!?

**Comment by sogaiu** [comment]
I don't see https://github.com/tree-sitter/tree-sitter/commit/d4c1bf7ce78051b7f4a381d1508d68928512ed5f on the master branch.  The date seems to be May 19th which is about a month or so later than https://github.com/tree-sitter/tree-sitter/commit/0c49d6745b3fc4822ab02e0018770cd6383a779c.

**Comment by ahlinc** [comment]
@ahelwer I can confirm that the problem exists with Linux CLI and it's related to https://github.com/tree-sitter/tree-sitter/issues/2272, I'll investigate it today later.

**Comment by ahlinc** [comment]
> Okay so there are two npm packages floating around for 0.20.8: https://github.com/tree-sitter/tree-sitter/commit/0c49d6745b3fc4822ab02e0018770cd6383a779c and https://github.com/tree-sitter/tree-sitter/commit/d4c1bf7ce78051b7f4a381d1508d68928512ed5f.

It  isn't related to an npm package, because the npm package is just a simple proxy package that downloads a CLI binary from Github releases page for the same version as it is. I made a manual CLI binary re-upload to fix an issue with overlooked GLIBC version, because before that moment it wasn't clear that we need to care about it for better portability.

**Investigation update:**
I tried to rebuild again the CLI binary for both https://github.com/tree-sitter/tree-sitter/commit/0c49d6745b3fc4822ab02e0018770cd6383a779c and https://github.com/tree-sitter/tree-sitter/commit/d4c1bf7ce78051b7f4a381d1508d68928512ed5f commits and look what they would generate for the TLA+ parser, but they produce no difference at all and they produce a file with the _8c48646f85fad994105d801671d334f1_ hash. And that exactly the hash that is incorrect and related to the problem in this issue.
Changes between mentioned commits were only related to CI configuration:

![image](https://github.com/tree-sitter/tree-sitter/assets/14666676/c3c3121b-10fc-48c9-8bba-ad52be3bad2e)

All above means that there is a problem with reproducible builds of Tree-sitter CLI for different versions.
Currently I don't know what Tree-sitter's dependency had an impact to change CLI's behavior and would it be enough to strictly pin all dependency versions or for the full reproducibility it also will be required to use specific Rust toolchain versions too.

**Comment by sogaiu** [comment]
Here is some rust toolchain-related info (before it changes on my Linux machine):

```
rustc --version
rustc 1.72.1 (d5c2e9c34 2023-09-13)
```

```
cargo --version
cargo 1.72.1 (103a7ff2e 2023-08-15)
```

**Comment by ahelwer** [comment]
The release of 0.20.9, assuming no similar issue exists for that release, means this issue has been superseded and can be closed unless someone starts to really care about build/release reproducibility.
