### ISSUE TITLE
New parser for kotlin leads to performance degradation

### ISSUE THREAD

**Issue by anthony-S93** [tree-sitter/tree-sitter#2758]
The problem is described in nvim-treesitter/nvim-treesitter#5657 along with videos demonstrating the issue. 

Basically, with the new kotlin parser, there is a noticeable delay in the opening of neovim buffers. The size of the file does not matter. The delay is noticeable even in a small kotlin file with only two lines of code.

**Comment by lucario387** [comment]
Not here. Tree-sitter-kotlin's repo.
