### ISSUE TITLE
css highlighting not complete

### ISSUE THREAD

**Issue by luv2hike** [tree-sitter/tree-sitter#276]
Color names and attributes not highlighting as they do in a standard CSS file.

CSS file:
![screen shot 2019-02-13 at 11 43 07 am](https://user-images.githubusercontent.com/47532767/52728314-115d6500-2f85-11e9-8630-61cd47ff5430.png)

Tree sitter in JS file:
![screen shot 2019-02-13 at 11 42 45 am](https://user-images.githubusercontent.com/47532767/52728315-115d6500-2f85-11e9-82c1-918774b27b98.png)

**Comment by Arcanemagus** [comment]
Assuming that you are using the Atom text editor, please file this in [language-css](https://github.com/atom/language-css), including the raw text used in your images to make the job of reproducing it easier.

Thanks!
