### ISSUE TITLE
How to make keyword precedence over identifier

### ISSUE THREAD

**Issue by B1Z0N** [tree-sitter/tree-sitter#2764]
### Discussed in https://github.com/tree-sitter/tree-sitter/discussions/2763

My grammar is the following. 

```js
module.exports = grammar({
    name: 'lang',
    rules: {
        program: $ => choice(
            $.literal, 
            $.identifier,
        ),

        identifier: $ => token(prec('identifier', /[a-zA-Z_][0-9a-zA-Z_]*/)),
        literal: $ => token(prec('literal', kw('true'))),
    },

    conflicts: $ => [],
    precedences: _ => [
        [
            'literal',
            'identifier',
        ]
    ],
    word: $ => $.identifier,
    extras: $ => [/\s\n/, /\s/],
});

function kw(word) {
    str = '';
    for (var i = 0; i < word.length; i++) {
      str += '[' + word.charAt(i).toLowerCase() + word.charAt(i).toUpperCase() + ']';
    }
    return new RegExp(str);
}
```

And even due to me specifying the lexer precedence here with `token(prec())` it won't parse `true` as `literal`, but as `identifier`. But if I change the order of definition of these two rules it works. 

This conflicts with what [docs say](https://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens) where the token precedence should be taken into account first instead of the order of definition.

**Comment by amaanq** [comment]
I could be mistaken, but I believe relative precedences (with strings) doesn't work in a token() context (which could be a bug, sure).

If you just use 1 and 2, e.g.

```js
identifier: $ => token(prec(1, /[a-zA-Z_][0-9a-zA-Z_]*/)),
literal: $ => token(prec(2, /true/i)),
``` 

that seems to parse `true` as a literal. Also, you can make it much easier on yourself by doing two things:

1. move literal above identifier so it'll be picked first always in the case of `true` without needing token(prec())
2. use tree-sitter-cli on master w/ the Rust crate to have support for the regex `i` flag (case insensitive, not required but it's a nice feature)

**Comment by B1Z0N** [comment]
Nice, thanks. It would be nice if relative precedences could work with `token`.

**Comment by ObserverOfTime** [comment]
Oh look, another case that `prec.lexical` (#2555) would solve.
