### ISSUE TITLE
Crash of `invalid memory reference` when using the cursor API

### ISSUE THREAD

**Issue by DavisVaughan** [tree-sitter/tree-sitter#2767]
I've been fighting a crash related to the cursor API (I thought it was #2766 but I was able to reproduce it without incremental parsing so I think it may be different). Specifically it seems to have to do with `goto_first_child()` and `goto_last_child()` when there isn't a child to move to (I think).

I'm working with the R grammar over in: (note the `next` branch)
https://github.com/r-lib/tree-sitter-r/tree/next

I haven't been able to reproduce this bug with a minimal Rust grammar test. I don't know if this is a bug on our end or not, but it seems unlikely (I wouldn't expect the Rust bindings to crash completely)? Any advice would be appreciated if you think it is our fault.

Since I couldn't easily reproduce on the Rust end, I ended up hooking our R grammar into your test infra in this branch, so I could add this as a failing test:
https://github.com/DavisVaughan/tree-sitter/commit/dc1f84266fca0857e5de1175d9f2e5eb636ca72c

```
scripts/fetch-fixtures
scripts/generate-fixtures
```

```rust
fn test_tree_cursor_r() {
    let mut parser = Parser::new();
    parser.set_language(get_language("r")).unwrap();

    // This is an `identifier`
    let text = "foo";

    let tree = parser.parse(text, None).unwrap();

    let mut cursor = tree.walk();
    assert_eq!(cursor.node().kind(), "program");

    // program -> identifier
    assert!(cursor.goto_first_child());
    assert_eq!(cursor.node().kind(), "identifier");
    assert_eq!(cursor.node().utf8_text(text.as_bytes()).unwrap(), "foo");

    // Doesn't move at all
    // (but I think the problem is here? i.e. the `ptr` is set to an invalid memory
    // location here when looking for a child)
    assert!(!cursor.goto_first_child());
    assert_eq!(cursor.node().kind(), "identifier");
    assert_eq!(cursor.node().utf8_text(text.as_bytes()).unwrap(), "foo");

    // Shouldn't move at all. But we get a panic
    assert!(!cursor.goto_last_child());
    assert_eq!(cursor.node().kind(), "identifier");
    assert_eq!(cursor.node().utf8_text(text.as_bytes()).unwrap(), "foo");
}
```

The call to `cursor.goto_last_child()` ends up completely crashing the Rust API with:

```
error: test failed, to rerun pass `-p tree-sitter-cli --lib`

Caused by:
  process didn't exit successfully: `/Users/davis/files/programming/tree-sitter/target/debug/deps/tree_sitter_cli-33314cc4549640fd 'tests::tree_test::test_tree_cursor_r' --exact --nocapture` (signal: 11, SIGSEGV: invalid memory reference)

 *  The terminal process "cargo 'test', '--package', 'tree-sitter-cli', '--lib', '--', 'tests::tree_test::test_tree_cursor_r', '--exact', '--nocapture'" terminated with exit code: 101. 
```

At some point along the way a `child` is created but it has a `ptr` that is "invalid" according to lldb, that's as far as I was able to get. I'll also note that it looks like the `identifier` node we get has a `child_count` of 1, which I found strange, I thought it would be 0.

**Comment by ObserverOfTime** [comment]
You can use the [fuzz action](https://github.com/tree-sitter/fuzz-action) in your CI to catch potential issues with the scanner. There's even a [recommended workflow](https://github.com/tree-sitter/workflows?tab=readme-ov-file#ci-workflow).

You can also add test cases to `bindings/rust/lib.rs` and run `cargo test` locally or let the CI run them (with `test-rust`).

**Comment by ObserverOfTime** [comment]
I do not get any errors when running the fuzzer locally and the panic has been resolved in the latest version.
I can submit a PR to your grammar for the test and worfklow.

**Comment by ObserverOfTime** [comment]
r-lib/tree-sitter-r#93
