### ISSUE TITLE
Mismatch between kind_id() in Rust bindings and grammar's enum value

### ISSUE THREAD

**Issue by WillLillis** [tree-sitter/tree-sitter#2768]
Hi! I'm new to treesitter and am currently working on a project that uses tree-sitter's Rust bindings along with the [tree-sitter-asm](https://github.com/rush-rs/tree-sitter-asm/tree/main) grammar. While debugging I noticed a mismatch between the node values presented in grammar's enum and the value returned by calling ``.kind_id()``. My code is as follows: 
```rust
use tree_sitter;
use tree_sitter_asm;

fn main() {
    let code = "movq    %rsp, %rbp";

    let mut parser = tree_sitter::Parser::new();
    parser
        .set_language(tree_sitter_asm::language())
        .expect("Failed to set language");
    let tree = parser.parse(&code, None).expect("Failed to parse");

    let query_str = "(instruction kind: (word) (ident (reg) @r1) (ident (reg) @r2)) @instr";
    let query = tree_sitter::Query::new(tree_sitter_asm::language(), query_str)
        .expect("Error creating query");

    let mut cursor = tree_sitter::QueryCursor::new();
    let matches = cursor.matches(&query, tree.root_node(), code.as_bytes());

    for match_ in matches.into_iter() {
        for cap in match_.captures.iter() {
            println!("Kind: {}, Kind id: {}", cap.node.kind(), cap.node.kind_id());
        }
    }
}

```

In tree-sitter-asm's [parser.c](https://github.com/rush-rs/tree-sitter-asm/blob/main/src/parser.c), an enum gives integer values for all the different node types. However, the values in the enum for a given node type are always 1 more than the value returned by calling ``.kind_id()`` on the same node type with the rust bindings. For example, the enum variant ``sym_reg`` has a value of ``32``, while ``kind_id()`` returns a value of ``31``. Similarly, the enum variant ``sym_instruction`` has a value of ``29``, but ``kind_id()`` returns ``28``.

Are the ``kind_id()`` values expected to be one less than the values in the enum? If not, what is the intended source for gathering ``kind_id`` information (e.g. in order to query a tree for a specific node type without having to resort to string literal comparisons). I apologize if I'm misunderstanding something or if this is an issue with the grammar instead of tree-sitter itself.

**Comment by maxbrunsfeld** [comment]
I think you can establish the mapping between kind strings and their numeric ids at runtime (hopefully once, during some initialization step) using the `Language::node_kind_for_id` and/or the `Language::id_for_node_kind` methods.

The intent is that you can treat the `parser.c` as a black box, as opposed to coding to any interface defined inside.

I'm not actually sure why you're seeing the ids differ from the enum by one, but there are differences between the public-facing ids and the internal enum. As I recall, the main differences can arise due to the use of *aliases* in the grammar.

**Comment by WillLillis** [comment]
That makes sense, thanks so much for the help! The ``Language::node_kind_for_id`` and ``Language::id_for_node_kind`` methods are exactly what I was looking for. :)

I'll go ahead and close this issue.
