### ISSUE TITLE
tree-sitter dump languages cannot find languages

### ISSUE THREAD

**Issue by ReggieMarr** [tree-sitter/tree-sitter#2771]
I installed my languages using doom-emacs management of the tree-sitter-langs package and they are found here:
```~/.config/emacs/.local/straight/build-29.1.90```

My config.json then looks like this:

```
{
  "parser-directories": [
    "/home/reggiemarr/.config/emacs/.local/straight/build-29.1.90/tree-sitter-langs/bin"
  ],
  "language-configs": {
    "python": {
      "load-path": "python.so"
    }
  }
}
```

but for some reason when I go to use tree-sitter parse on a simple file I get the following:
```
❯ tree-sitter dump-languages     

```

What am I missing here ?

**Comment by amaanq** [comment]
Parser-directories is for tree-sitter-xxx repositories, not the compiled parsers since it needs to extract data from package.json

**Comment by ReggieMarr** [comment]
Thank you !

**Comment by b7r3333** [comment]
))،
