### ISSUE TITLE
Include field names in test logs 

### ISSUE THREAD

**Issue by faldor20** [tree-sitter/tree-sitter#2772]
Tests don't currently include fields in the diffs/output, I find this pretty annoying because this means tests don't actually show what the user will see and don't make field changes visible. 
I suppose that's maybe useful because fields are only cosmetic rather than structural. but for me  tests are the major way i know the output of tree-sitter is how i want it and fields are a part of that.

PS: Tree-sitter is awesome and i wanted to express my profound appreciation for this awesome project, I'm still wrapping my head around how to write parsers well and i can't even imagine how complex the implementation must have been. So thankyou all :)

**Comment by sogaiu** [comment]
Possibly of interest: https://github.com/tree-sitter/tree-sitter/pull/1536

**Comment by b7r3333** [comment]
جواهر بنت عيادة قحبة زانية بنت حرام

**Comment by b7r3333** [comment]
جواهر بنت عيادة قحبة زانية بنت حرام

**Comment by ObserverOfTime** [comment]
If you include field names in the output section they will also be included in the diffs.

**Comment by ambroisie** [comment]
@ObserverOfTime could we get a way to _automatically_ get the field names? I don't usually write the output section by hand, instead relying on `--update` and checking that it matches what I was expecting.

**Comment by ObserverOfTime** [comment]
You can add a dummy field and rerun with `--update`.
