### ISSUE TITLE
tree-sitter query command results do not output some text

### ISSUE THREAD

**Issue by leebs0521** [tree-sitter/tree-sitter#2774]
hello.

I am trying to extract the function information part of parse using the tree-sitter query command.
Most of the time it prints well, but in some cases, the beginning and end are printed but the text is not printed.

Are there people in the same situation as me?
Also how do I solve this?

thank you
![query_result](https://github.com/tree-sitter/tree-sitter/assets/86824224/74951411-2558-44da-9b2d-94033594665c)

**Comment by sogaiu** [comment]
Hi,

I don't have a solution for you via the `tree-sitter` cli tool, but I think the reason this happens may be seen [here](https://github.com/tree-sitter/tree-sitter/blob/0ff28346be3d27f935d7cde8bbdf6b621c268e1a/cli/src/query.rs#L85-L101).

IIUC, when the start and end rows differ, no text is printed.

Assuming that's correct, I suppose you could either make a custom version of the cli or possibly use bindings from some programming language and obtain the results programmatically.

If the above is mistaken, perhaps some more knowledgeable person will be kind enough to point that out (and perhaps even suggest some better ideas).

**Comment by leebs0521** [comment]
@sogaiu
thank you
As you said, I solved it by modifying the source code and building it.

**Comment by ObserverOfTime** [comment]
Yes, the CLI cannot print multi-line matches.
