### ISSUE TITLE
Online playground doesn't output query errors

### ISSUE THREAD

**Issue by viniciusd** [tree-sitter/tree-sitter#2775]
I am trying to get acquainted with tree-sitter, so I went to the playground page and started testing a few queries.

However, the playground isn't outputting the result of queries or even errors. I quickly went over the front-end code and the functions seem te be called accordingly, but it fails to display feedback to the end user.

I am testing the following:
<img width="716" alt="Screenshot 2023-11-21 at 11 04 30 AM" src="https://github.com/tree-sitter/tree-sitter/assets/8950559/8864b2a9-dfee-467f-bbff-5c004f0b992d">

On the debugger, variables seem to get the correct values:
<img width="1094" alt="Screenshot 2023-11-21 at 11 06 23 AM" src="https://github.com/tree-sitter/tree-sitter/assets/8950559/86e3cf4b-cc65-4b31-86c0-5d5e339a7597">

Is it a bug on the online playground?

**Comment by ObserverOfTime** [comment]
It *is* underlined.

**Comment by viniciusd** [comment]
Do you mean the `module` root on the tree? That is highlighted due to clicking. I don't see any error message on the interface. I would expect the `"Bad node name 'c'"` to be visible for those writing queries

**Comment by viniciusd** [comment]
> It _is_ underlined.

Do you mean the module root on the tree? That is highlighted due to clicking. I don't see any error message on the interface. I would expect the "Bad node name 'c'" to be visible for those writing queries
