### ISSUE TITLE
No such file or directory (os error 2) when running 'tree-sitter generate'

### ISSUE THREAD

**Issue by francisdb** [tree-sitter/tree-sitter#278]
I'm following the tutorial at http://tree-sitter.github.io/tree-sitter/creating-parsers but on the generation step the executable fails with this.

```
➜  tree-sitter generate
No such file or directory (os error 2)
```

```
➜  ./node_modules/tree-sitter-cli/tree-sitter generate
No such file or directory (os error 2)
```

So what file or directory is missing?

MacOS 10.14.3 / zsh

**Comment by francisdb** [comment]
Looks like this is caused by a missing `src` folder

**Comment by maxbrunsfeld** [comment]
Ah, sorry about that; you shouldn't have to create the `src` folder manually. I'll push a fix shortly.

**Comment by maxbrunsfeld** [comment]
I published 0.14.5, which fixes this.

**Comment by matoous** [comment]
Hi 👋  I am sorry, I am having the same issue now.

I have clean install using rust:
```
tree-sitter-jsonnet [+] main ❯ which tree-sitter
/Users/matousdzivjak/.cargo/bin/tree-sitter
```

Version `0.20.2`:
```
tree-sitter-jsonnet [+] main ❯ tree-sitter
tree-sitter 0.20.2
Max Brunsfeld <maxbrunsfeld@gmail.com>
Generates and tests parsers
```

I am following the current version of the guide at: https://tree-sitter.github.io/tree-sitter/creating-parsers

Running `generate` fails with:
```
tree-sitter-jsonnet [+] main ❯ tree-sitter generate
No such file or directory (os error 2)
```

**Comment by yaegassy** [comment]
I am suffering from the same problem... :( 

I followed the instructions in [creating-pasers](https://tree-sitter.github.io/tree-sitter/creating-parsers), but `No such file or directory (os error 2)` is output.

Are there any steps or tools that I am missing?

---

**Command**:

```sh
mkdir -p tree-sitter-dummy
cd tree-sitter-dummy
npm init -y
npm install --save nan
npm install --save-dev tree-sitter-cli

cat <<EOF > grammer.js
module.exports = grammar({
  name: 'dummy',

  rules: {
    // TODO: add the actual grammar rules
    source_file: $ => 'hello'
  }
});
EOF

npx tree-sitter generate
```

**OUTPUT**:

```
$ npx tree-sitter generate
No such file or directory (os error 2)
```

**Comment by yaegassy** [comment]
Oh, I'm sorry. This comment thing has been resolved. 🙇

I had a typo in my file name. The correct file name is `grammar.js`, not `grammer.js`.
