### ISSUE TITLE
v0.20.7: example program hangs

### ISSUE THREAD

**Issue by x13pixels** [tree-sitter/tree-sitter#2782]
The example program given in the getting started guide hangs in `ts_parser_parse_string` when run with the latest released version (v0.20.7) of tree-sitter.

test.c:
```
#include "./tree-sitter/lib/src/lib.c"
#include "./tree-sitter-json/src/parser.c"

int main()
{
   TSParser *parser = ts_parser_new();
   ts_parser_set_language(parser, tree_sitter_json());

   const char *source_code = "[1, null]";
   TSTree *tree = ts_parser_parse_string(parser, NULL, source_code, strlen(source_code));

   return 0;
}
```

* In a directory containing the source file test.c, the latest released tree-sitter repo (at tag `v0.20.7`), and the tree-sitter-json repo (master), compile with MSVC (19.37.32824 for x64) as `cl /I.\tree-sitter\lib\include test.c`. This will generate test.exe.
* Run test.exe
Notice that the program hangs (infinite loop in `ts_parser_parse`)

* Instead of using the tagged version of tree-sitter, 0.20.7, checkout `master` and rebuild
* Run test.exe
Notice that the program no longer hangs.

Note that the hang no longer occurs starting with the commit 4a007259fc, which hasn't been tagged in an official release yet.

Maybe the [sample program](https://tree-sitter.github.io/tree-sitter/using-parsers) is wrong?

**Comment by jiseongg** [comment]
The same thing is happening here! 😢

**Comment by amaanq** [comment]
Please use 0.20.8 at the minimum, or ideally 0.20.9
