### ISSUE TITLE
Single-line comments in injected langs in markdown comment the whole injection

### ISSUE THREAD

**Issue by gushogg-blake** [tree-sitter/tree-sitter#2784]
I think this issue is to do with the way tree-sitter-markdown (https://github.com/ikatyang/tree-sitter-markdown) handles injection ranges and the way other parsers handle single-line comments.

It looks like tree-sitter-markdown doesn't include newlines in the injection ranges, and the inner parsers need a newline in order to terminate a single-line comment, so the whole code block ends up commented.

This happens when injecting e.g. javascript into a fenced code block in markdown, or scss into a `<style>` tag within html injected in markdown.

Is this something that can be solved at the tree-sitter/grammar level or does it require a workaround?

**Comment by clason** [comment]
Try https://github.com/MDeiml/tree-sitter-markdown instead.

**Comment by gushogg-blake** [comment]
Thanks @clason, got it working with that package. (Had rejected it before as my injection logic didn't have an option to excluding child nodes from the ranges, but wasn't too big of a change.)

**Comment by gushogg-blake** [comment]
Closing as the other package solved it. Note for anyone else switching that the main markdown parser from MDeiml/tree-sitter-markdown/tree-sitter-markdown must be statically linked to the main tree-sitter library if using the wasm version. See https://github.com/gushogg-blake/tree-sitter and https://github.com/tree-sitter/tree-sitter/issues/949 for more details.
