### ISSUE TITLE
Help parsing conflict error messages

### ISSUE THREAD

**Issue by wstevick** [tree-sitter/tree-sitter#2804]
I'm trying to write a grammar for futhark. When I run `tree-sitter generate`, I get this

```
Unresolved conflict for symbol sequence:

  'def'  name  '='  _atom  •  name  …

Possible interpretations:

  1:  'def'  name  '='  (_exp  _atom)  •  name  …
  2:  'def'  name  '='  (apply  _atom  •  apply_repeat1)

Possible resolutions:

  1:  Specify a higher precedence in `apply` than in the other rules.
  2:  Specify a higher precedence in `_exp` than in the other rules.
  3:  Specify a left or right associativity in `_exp`
  4:  Add a conflict for these rules: `_exp`, `apply`
```

I don't have much experience with parsers under-the-hood, and I certainly don't understand GLR parsers. How do I decode this? What does `•` mean? I don't have a rule named `apply_repeat1`, where did that come from? What are the parenthesize doing?

**Comment by sogaiu** [comment]
Others are more likely to have something relevant to say about the dot (I think it indicates a position under consideration / processing, but never quite cleared this up (^^; ).

As for `apply_repeat1`, my guess is that it may be related to [this line](https://github.com/wstevick/tree-sitter-futhark/blob/de4908f50ae43b04e085b8d024eb0fedc5b6ead2/src/parser.c#L71) in `parser.c` and that exists partly as the result of [this line](https://github.com/wstevick/tree-sitter-futhark/blob/de4908f50ae43b04e085b8d024eb0fedc5b6ead2/grammar.js#L22) in the `grammar.js` file.

**Comment by sogaiu** [comment]
Don't know if it woud be helpful, but FWIW, [this part of the docs](https://tree-sitter.github.io/tree-sitter/creating-parsers#using-precedence) has example code with somewhat similar output and there is some associated explanation provided.

**Comment by wstevick** [comment]
I have the code working now. Thanks.

**Comment by sogaiu** [comment]
Regarding the dot, I came across the following text:

>  The • (pink dot) marker shows where the parser is now, within some partially recognized grammar rules. The things to the left of • have been parsed, and the things to the right are expected soon. 

via: https://en.wikipedia.org/wiki/LR_parser#Parse_table_for_the_example_grammar (search for "pink dot")
