### ISSUE TITLE
Document external scanners

### ISSUE THREAD

**Issue by fcurts** [tree-sitter/tree-sitter#281]
Please document the API contract of external scanners. They seem to be required for parsing most general-purpose languages. Even after looking at other scanners, I haven't been able to figure out how exactly they work (i.e., I can't get my scanner to work correctly).

**Comment by fcurts** [comment]
My biggest question is what `mark_end` is for. Initially I thought that `mark_end` followed by `advance` could be used for multi-character lookahead, but this doesn't seem to be the case.
So far I haven't found a way to write a grammar for my language that produces the desired parse tree without looking ahead multiple characters in the scanner (which doesn't seem to be supported).

**Comment by Aerijo** [comment]
You can lookahead multiple characters by calling `advance`, like in [existing external scanners](https://github.com/tree-sitter/tree-sitter-html/blob/22e568ea752624791d795746c4c027969a65f182/src/scanner.cc#L119).

**Comment by fcurts** [comment]
@Aerijo By "looking ahead multiple characters" I mean that when I return `true`, none of these characters have been consumed. Is this possible, and if so, how?

**Comment by Aerijo** [comment]
If you 
- advance several times, 
- mark the end, 
- give it a node type, and
- return `true` from the scanning function

it should add the node to the tree and stay where it advanced to. If you return false, it will go back to where it started because the scan is considered a failure.

Do you have a link to your grammar I can look at to see what's happening?

**Comment by fcurts** [comment]
What you describe is not what I'm looking for (and doesn't seem to require calling `mark_end`).

I'd like to consume some characters, then look ahead multiple characters without consuming them, then return `true`, and it should proceed from the position after the last consumed character.

What I'm trying to parse is Swift 5 string literals with custom string delimiters (https://github.com/apple/swift-evolution/blob/master/proposals/0200-raw-string-escaping.md#customized-escape-delimiters). Unfortunately, I can't share my grammar.

**Comment by maxbrunsfeld** [comment]
Yeah this is exactly what `mark_end` does, and we use it for this purpose in several existing scanners.

The default behavior of an external scanner is that, when you return `true`, it will create a token whose type is given by `lexer->result_symbol`, and consume all of the characters for which you called `advance`. Sometimes you may want to look ahead at some characters without necessarily consuming characters. You can do this by calling `lexer->mark_end`.

If you call `martk_end` and then later call `lexer->advance` one or more times, the resulting token will *not* consume those characters, unless you call `mark_end` again later.

**Comment by maxbrunsfeld** [comment]
Examples:

* In JavaScript, creating a zero-character `automatic_semicolon` token by looking ahead at the *next* token (skipping over any comments of whitespace): https://github.com/tree-sitter/tree-sitter-javascript/blob/4213a6c331d068b67de17e2dac917a90968cd33c/src/scanner.c#L76-L142.

* In Python, creating zero-character `indent`/`decent` tokens by looking ahead at the amount of leading whitespace on the next line: https://github.com/tree-sitter/tree-sitter-python/blob/1f256b4fc5a934f0e6c8a2eb672a984e3a5c2c04/src/scanner.cc#L198-L264.

**Comment by fcurts** [comment]
Turns out that my very first solution was correct, except that the `TokenType` element order didn't match the `externals` element order. I had no idea this was relevant...

@maxbrunsfeld Thank you for your quick help. Some documentation would be extremely helpful.

@Aerijo https://gist.github.com/Aerijo/df27228d70c633e088b0591b8857eeef is a life saver. Perhaps it could be integrated into the docs?

**Comment by maxbrunsfeld** [comment]
Docs are up: http://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners.

**Comment by fcurts** [comment]
@maxbrunsfeld Looks great. Only thing that seems missing is the error recovery mode (which I would have never figured out without your help).

**Comment by danielo515** [comment]
This issue has several important bits and tips that are not documented in the current state of the docs. Please consider adding that information too to the existing document. Things that I miss in the docs is how to look ahead several times without consuming the characters, and what happens if you return false from the scanner.
