### ISSUE TITLE
feature request: support building wasm with podman in addition to docker 

### ISSUE THREAD

**Issue by SKalt** [tree-sitter/tree-sitter#2814]
**Context**: [`podman`](https://podman.io/) is a tool to run and manage containers. It's an alternative to docker that has most of the same command-line flags and arguments. I'd like [`tree-sitter build-wasm`](https://github.com/tree-sitter/tree-sitter/blob/660481dbf71413eba5a928b0b0ab8da50c1109e0/cli/loader/src/lib.rs#L571) to work with `podman` instead of complaining about the absence of docker.

I'd be happy to submit a PR for this!

**Comment by maxbrunsfeld** [comment]
Sounds like a good feature. I'd be open to that PR.
