### ISSUE TITLE
discussion: clarify rule name restrictions

### ISSUE THREAD

**Issue by SKalt** [tree-sitter/tree-sitter#2816]
Motivation: I'm experimenting with adding Clojure-style namespaces in tree-sitter rule names (e.g. `namespace/my_rule`). I'd like to know how cursed or blessed that approach is before I get too far. 

Context: As far as I can tell, `tree-sitter` will accept any unicode string as a rule name. 

<details><summary>demo of slashes, spaces, periods, emoji</summary>

A full demo is available at https://github.com/skalt/temp-tree-sitter-name-hack. Here's that repo's `test/corpus/statements.txt`:

```txt
=======
slashes
=======
/
---
(cursed_program (with/slashes))

=======
dots
=======
.
-------
(cursed_program (with.dots))

=======
spaces
=======
/_/
-------
(cursed_program
  (with/slashes)
  (with spaces) ; <-- looks odd but it works
  (with/slashes))

======
emoji
======
✨✅
------
(cursed_program (✨))
```
As of tree-sitter v0.20.8, this corpus passes `tree-sitter test`.

</details>

However, [`cli/src/generate/grammar-schema.json`](https://github.com/tree-sitter/tree-sitter/blob/0751736/cli/src/generate/grammar-schema.json#L20) restricts rule names to the regular expression `^[a-zA-Z_]\w*$`, which roughly corresponds to a javascript identifier name.

Tree-sitter queries are written in a scheme-like language, and scheme identifiers can ASCII symbols:

<details><summary>relevant excerpt of the scheme standard</summary>

> An identifier is any sequence of letters, digits, and "extended identifier characters" provided that it does not have a prefix which is a valid number.
>
> All implementations of Scheme must support the following extended identifier characters:
> ```txt
> ! $ % & * + - . / : < = > ? @ ^ _ ~
> ```
> Alternatively, an identifier can be represented by a sequence of zero or more characters enclosed within vertical lines (|), analogous to string literals.
> Any character, including whitespace characters, but excluding the backslash and vertical line characters, can appear verbatim in such an identifier. 
>
> -- https://standards.scheme.org/official/r7rs.pdf#section.2.1

</details>

Proposal: loosen [`cli/src/generate/grammar-schema.json`](https://github.com/tree-sitter/tree-sitter/blob/0751736/cli/src/generate/grammar-schema.json#L20)'s rule name pattern to reflect `tree-sitter`'s current and future behavior. Loosening the rule-name pattern to accept the ASCII symbols from scheme's "extended identifier characters" would improve the accuracy of the documentation without suggesting that whitespace or emoji won't result in problems in future `tree-sitter` versions.  

Proposal that I don't support but I'd like to discuss: adding validation for rule names. If other parts of `tree-sitter` required a specific name format, validation might be useful, but that doesn't seem to be the case.

**Comment by ObserverOfTime** [comment]
`/` is used for querying nodes with supertypes.
https://github.com/tree-sitter/tree-sitter-javascript/blob/master/queries/locals.scm#L15

**Comment by SKalt** [comment]
Good to know. @ObserverOfTime do `.`s or `:`s in identifiers currently have semantic meaning in scheme queries?

**Comment by ObserverOfTime** [comment]
No but rule names must be valid identifiers in JavaScript **and C**.

**Comment by SKalt** [comment]
Given that constraint, I'll go with c-style `__` namespace separators. I'd be curious why https://github.com/skalt/temp-tree-sitter-name-hack even vaguely worked!
