### ISSUE TITLE
basic example not working?

### ISSUE THREAD

**Issue by restlessronin** [tree-sitter/tree-sitter#2834]
I am trying to use tree-sitter to build a simple node library. I am having a lot of trouble just getting the basics working.

I installed the language modules and did a wasm_build. I am on an M1 mac and usied docker (the image is not arm64 and uses Rosetta) for the purpose. Here are the versions

Node for wasm build: v 20.10.0
Node at runtime: v18.19.0
tree-sitter: 0.20.8
tree-sitter-javascript: 0.20.1

The relevant parts of the test code 

Setup
```typescript
import Parser from 'web-tree-sitter';

async function main() {
  await Parser.init();
}

main().catch(console.error);
```
and the error happens at the very first line using Parser, either
```typescript
    const parser = new Parser();
 ```
with the output
```
    TypeError: Cannot read properties of undefined (reading 'ts_parser_new_wasm')

      at Object.Module._ts_parser_new_wasm (node_modules/.pnpm/web-tree-sitter@0.20.8/node_modules/web-tree-sitter/tree-sitter.js:1:33170)
      at Parser.initialize (node_modules/.pnpm/web-tree-sitter@0.20.8/node_modules/web-tree-sitter/tree-sitter.js:1:52266)
      at new Parser (node_modules/.pnpm/web-tree-sitter@0.20.8/node_modules/web-tree-sitter/tree-sitter.js:1:281)
```
or if the language is loaded before the parser creation
```typescript
    const languageWasm = await Parser.Language.load(wasmPath);
```
and the error output is
```
    TypeError: Cannot set properties of undefined (setting 'value')

      at getMemory (node_modules/.pnpm/web-tree-sitter@0.20.8/node_modules/web-tree-sitter/tree-sitter.js:1:12632)
      at loadModule (node_modules/.pnpm/web-tree-sitter@0.20.8/node_modules/web-tree-sitter/tree-sitter.js:1:15748)
      at node_modules/.pnpm/web-tree-sitter@0.20.8/node_modules/web-tree-sitter/tree-sitter.js:1:18265
```
What else can I try, to make this work? I have spent more than a week (and filed 2 PRs, [here](https://github.com/tree-sitter/node-tree-sitter/pull/182) and [here](https://github.com/tree-sitter/tree-sitter/pull/2821)) just to get this far.

**Comment by savetheclocktower** [comment]
You might want to dig into the [source code for the playground](https://tree-sitter.github.io/tree-sitter/playground) to see how they bootstrap. Or you can look at the [Pulsar source code](https://github.com/pulsar-edit/pulsar/blob/master/src/wasm-tree-sitter-grammar.js#L139). As one of the maintainers of the latter, I can confirm I've got 0.20.8 working locally.

You seem to be in a pure Node environment, so maybe that'd explain why you're having troubles in places where the playground (pure web environment) and Pulsar (Electron hybrid web/Node environment) aren't.

**Comment by restlessronin** [comment]
@savetheclocktower my eventual target is a vs-code extension, so it actually is for an electron environment. However, I was initially trying to use "node-tree-sitter" rather than "tree-sitter". For ease of testing, I used the node environment. When it came time to integrate with the vs code extension, I couldn't get it to work because the native binaries wouldn't run from electron. I'm a node newbie so I couldn't fix that problem.

I decided to try using this library instead, but as you can see, I'm having problems calling it from node. Perhaps if I call it from electron instead, as you seem to be suggesting, I might have better luck. Let me take a look at the polar code and see if I can use that as a starting point for electron usage. Do you have to do anything special to build/install an electron version of the library / grammar wasms?

**Comment by restlessronin** [comment]
@savetheclocktower Thank you very much. The sample code did the trick. I got it working in node. Now here's hoping I can get it working in electron. I will close this issue now.

**Comment by pokey** [comment]
In case helpful, in my case it turned out I wasn't awaiting `TreeSitter.init()` before trying to load a parser
