### ISSUE TITLE
Disable whitespace parsing on a method level

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#284]
Most of my methods are fine with whitespace, but there are some rules that basically require me to do a `seq("-", $.exression)` which shouldn't allow a whitespace.

Is there any way to do this rigth now?

**Comment by 314eter** [comment]
You can probably use `token.immediate` (#190), depending on the content of `$.expression`.

**Comment by Razzeee** [comment]
I don't think I can use that.

I basically want to use this here https://github.com/Razzeee/tree-sitter-elm/blob/master/grammar.js#L57-L68

Which tries to reimplement the bnf grammar done like this: https://github.com/klazuka/intellij-elm/blob/master/src/main/grammars/ElmParser.bnf#L134-L144

**Comment by 314eter** [comment]
You can do something like
```js
_immediate_upper_case_identifier: $ => alias(token.immediate(/[A-Z][a-zA-Z0-9_]*/), $.upper_case_identifier),

_immediate_dot: $ => alias(token.immediate('.'), $.dot),

upper_case_qid: $ => seq($.upper_case_identifier, repeat($._immediate_dot, $._immediate_upper_case_identifier)),
```

**Comment by Razzeee** [comment]
So according to my tests a construct like 
```
_immediate_dot: $ => alias(token.immediate('.'), $.dot),
```
doesn't lead to a node in the tree.

Seems like `alias` can't be done like that and needs to be in the calling function.

```
    _dot_without_leading_whitespace: $ => token.immediate("."),

    field_access_segment: $ =>
      prec.left(
        seq(
          alias($._dot_without_leading_whitespace, $.dot),
          $.lower_case_identifier
        )
      ),
```

**Comment by Razzeee** [comment]
I settled on https://github.com/Razzeee/tree-sitter-elm/commit/60582a69e8a125894f4cc0c3a85ce40d6cb786c5 for now. Still it would be nice to be able to use `alias` inside of a function. But that's probably another issue, not sure if https://github.com/tree-sitter/tree-sitter/issues/241 covers it.

**Comment by 314eter** [comment]
I think you're making it more complicated than necessary by using separate rules for every keyword and symbol. Things like `module`, `where` and `dot` are part of the syntax, but don't have to appear in the syntax tree.

The same argument applies to `lower_case_identifier`. For example in
```js
lower_type_name: $ => $.lower_case_identifier,
```
you don't need a separate node for `lower_case_identifier`.

**Comment by Razzeee** [comment]
your probably right, but for now I want to be somewhat compareable to the reference implementation

**Comment by maxbrunsfeld** [comment]
Note that you can also pass a string as the second argument to `alias`. For example: `alias($._dot_without_leading_whitespace, ".")`. This will make the `_dot_without_leading_whitespace` node appear identical to an unnamed `"."` node.

I'm going to close this out because it sounds like `token.immediate` solved the problem for you. Let me know if you're still having problems with disabling whitespace.

**Comment by Razzeee** [comment]
Yes, it seems to work for now.

But Iam confused by your statement, as I thought `alias` was buggy with a string? Pretty sure I tried that at a point. See: https://github.com/tree-sitter/tree-sitter/issues/241#issuecomment-456166703

**Comment by maxbrunsfeld** [comment]
I think `alias` works correctly with a string.

* `alias($.a, $.b)` means that you want the `a` to appear like a *named* node (`$.b`)
* `alias($.a, "b")` means that you want the `a` to appear like an anonymous node (`"b")`

**Comment by Razzeee** [comment]
for what usecase would I need to add an anonymous node? 

can we add that to the docs? I can probably send a PR later

**Comment by 314eter** [comment]
https://tree-sitter.github.io/tree-sitter/using-parsers#named-vs-anonymous-nodes
(which is what I meant when I said that you don't need named nodes for all your keywords)

Aliasing to anonymous nodes is less common. It's used in [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python/blob/a954c045cd5576c1c610b8318a638ef4b471ab0f/grammar.js#L731), but for that use case you can avoid the explicit aliasing, as in [tree-sitter-ocaml](https://github.com/tree-sitter/tree-sitter-ocaml/blob/cb1b1931eb037c63b11b2bef0b174e7c8996881a/grammar.js#L1694).

**Comment by Razzeee** [comment]
I do have to revert to external parsers to be able to parse cases where I can't make a token, right?

This is the problem I'm having, as I need to disallow the whitespace between minus and whatever follows. https://github.com/Razzeee/tree-sitter-elm/blob/add-lexer/grammar.js#L337

**Comment by 314eter** [comment]
I think so. But are you sure you can't allow whitespace there? Sometimes it's easier to make the tree-sitter parser more relaxed than the official parser, as long as all valid input can still be parsed.

**Comment by Razzeee** [comment]
There might be a way out, but having the whitespace there changes the ast that is generated. So it breaks my tree at the moment.
