### ISSUE TITLE
Discrepancy between query with Rust bindings and CLI tool

### ISSUE THREAD

**Issue by WillLillis** [tree-sitter/tree-sitter#2843]
Hi! I'm having some trouble using the [tree-sitter-asm](https://github.com/rush-rs/tree-sitter-asm/) grammar (the latest commit on the main branch) with the tree-sitter Rust bindings. This is the query I'm using:
```
(label (ident (reg (word) @label)))
(meta kind: (meta_ident)
(
        (int)
        ("," (int))*
    )
) @data
```

The results from the CLI tool and Rust bindings match when used on the following input file:

```asm
data_items:
    .long 1, 2, 3
```

The playground for this file looks like:

![image](https://github.com/tree-sitter/tree-sitter/assets/87077023/423d6a08-6db0-437d-9079-30f06dc4b0b8)

The tree looks like this:

![image](https://github.com/tree-sitter/tree-sitter/assets/87077023/a0a25b0c-1a5e-47d0-a2a1-ee63a49fb7f9)

Using the Rust bindings with the above query, I get these matches in response:

```
Matches: [
QueryMatch { id: 0, pattern_index: 0, captures: [QueryCapture { node: {Node meta (1, 4) - (1, 17)}, index: 1 }] }, 
QueryMatch { id: 1, pattern_index: 1, captures: [QueryCapture { node: {Node meta (1, 4) - (1, 17)}, index: 1 }] }
]
```

The CLI tool produces this output:

```
working.asm
  pattern: 0
    capture: 0 - label, start: (0, 0), end: (0, 10), text: `data_items`
  pattern: 1
    capture: 1 - data, start: (1, 4), end: (1, 17), text: `.long 1, 2, 3`
```

However the CLI tool and Rust bindings return different results on the next (very similar) input: 

```asm
data_items:
    .long 1, 2, 3

main:
    movq %rbp, %rsi
```

The playground for this file looks like this:

![image](https://github.com/tree-sitter/tree-sitter/assets/87077023/974e0849-a53c-4ea5-bd3f-153e5476ed37)

The tree looks like this:

![image](https://github.com/tree-sitter/tree-sitter/assets/87077023/ebac7b6a-941e-4b5b-a35a-63b085d01093)

Currently with the rust bindings,  using the above query and printing out the result from calling ``.matches()`` yields:

```
Matches: [
QueryMatch { id: 0, pattern_index: 0, captures: [QueryCapture { node: {Node word (3, 0) - (3, 4)}, index: 0 }] }, 
QueryMatch { id: 1, pattern_index: 1, captures: [QueryCapture { node: {Node word (3, 0) - (3, 4)}, index: 0 }] }, 
QueryMatch { id: 2, pattern_index: 0, captures: [QueryCapture { node: {Node word (3, 0) - (3, 4)}, index: 0 }] }
]

```

which is unexpected, as the ``    .long 1, 2, 3`` line isn't captured at all. When running the same grammar on the same file using the CLI tool, I get the following (more expected) output, which *does* capture the ``    .long 1, 2, 3`` line: 

```
broken.asm
  pattern: 0
    capture: 0 - label, start: (0, 0), end: (0, 10), text: `data_items`
  pattern: 1
    capture: 1 - data, start: (1, 4), end: (1, 17), text: `.long 1, 2, 3`
  pattern: 0
    capture: 0 - label, start: (3, 0), end: (3, 4), text: `main`
```

I'm not sure what's causing this difference, but if I'm misusing/ misunderstanding the Rust bindings I'd love to find out why/ how. This is all part of a larger project, but if it would be helpful to create a smaller, more self contained example I would be happy to throw that together in a separate repo. I'm fairly stuck, so any help on this would be greatly appreciated.

**Comment by DanielJoyce** [comment]
Seems related to #2847

**Comment by WillLillis** [comment]
I spent some more time on this and found some more interesting behavior. Currently, if I set a cursor's range to the entire document, some queries will repeatedly match  a single node and ignore/ not match with other nodes that should match. If I restrict the cursor's point range to a subset of the document, it will then match with the previously ignored nodes. I would expect the latter to matched with in both cases. I can provide a concrete example if that would be helpful. :)

Definitely seems to be related to #2847, nice catch @DanielJoyce!

**Comment by ObserverOfTime** [comment]
Does this only occur in the Rust bindings? Could you also try Node for one?

**Comment by WillLillis** [comment]
> Does this only occur in the Rust bindings? Could you also try Node for one?

I tried out the example from #2847 as follows:

```js
const Parser = require("tree-sitter");
const C = require("tree-sitter-c");
const { Query } = Parser

const source = `
void do_stuff() {
  int x = 42;
  char const *y = "Hello, world!";
  float z = 3.14159;
}
`

const parser = new Parser();
parser.setLanguage(C);
const tree = parser.parse(source);
const query = new Query(C, "(declaration type: (primitive_type) @t)");
const matches = query.matches(tree.rootNode);

for (const match in matches) {
    console.log(matches[match]);
}
```

which gives the following (correct) output:

```js
{
  pattern: 0,
  captures: [
    {
      name: 't',
      node: PrimitiveTypeNode {
        type: primitive_type,
        startPosition: {row: 2, column: 2},
        endPosition: {row: 2, column: 5},
        childCount: 0,
      }
    }
  ]
}
{
  pattern: 0,
  captures: [
    {
      name: 't',
      node: PrimitiveTypeNode {
        type: primitive_type,
        startPosition: {row: 3, column: 2},
        endPosition: {row: 3, column: 6},
        childCount: 0,
      }
    }
  ]
}
{
  pattern: 0,
  captures: [
    {
      name: 't',
      node: PrimitiveTypeNode {
        type: primitive_type,
        startPosition: {row: 4, column: 2},
        endPosition: {row: 4, column: 7},
        childCount: 0,
      }
    }
  ]
}
```

I believe the issue with the Rust bindings is that the `matches()` iterator holds a pointer to the underlying `TSQueryCursor` in the C library:

https://github.com/tree-sitter/tree-sitter/blob/dcb7acede4b31fedfc9d65b902fc95f6fe5ea099/lib/binding_rust/lib.rs#L2348-L2365

Each call to `.next()` on the iterator updates the state of underlying object in the C library, which is still referenced in items returned by previous calls to `next()`. It looks like calling `collect()` on the iterator simply calls repeatedly `next()`, creating copies of the `QueryMatch` object along the way that have their internal state overwritten with each next call. (The last item should be the one that "wins", which is the behavior shown in #2847) 

https://github.com/tree-sitter/tree-sitter/blob/dcb7acede4b31fedfc9d65b902fc95f6fe5ea099/lib/binding_rust/lib.rs#L2596-L2621

Just iterating through the matches one at a time (instead of calling `collect()` and iterating over the resulting `Vec`) does not exhibit this behavior, as you're only viewing one match at a time. I'm assuming the Node bindings are performing some kind of deep copy for each match that avoids this problem? I haven't spent much time with JS, so I wasn't super sure when I read through the bindings.

**Comment by ObserverOfTime** [comment]
In that case this is the same issue as #2847. I'll close that one since there's more info here.

**Comment by ObserverOfTime** [comment]
There are several related query issues and I wasn't sure which ones are duplicates or just similar.

**Comment by quentinLeDilavrec** [comment]
There are inconsistencies in the lifetimes:
https://github.com/tree-sitter/tree-sitter/blob/dcb7acede4b31fedfc9d65b902fc95f6fe5ea099/lib/binding_rust/lib.rs#L2354
https://github.com/tree-sitter/tree-sitter/blob/dcb7acede4b31fedfc9d65b902fc95f6fe5ea099/lib/binding_rust/lib.rs#L198
https://github.com/tree-sitter/tree-sitter/blob/dcb7acede4b31fedfc9d65b902fc95f6fe5ea099/lib/binding_rust/lib.rs#L2599
https://github.com/tree-sitter/tree-sitter/blob/dcb7acede4b31fedfc9d65b902fc95f6fe5ea099/lib/binding_rust/lib.rs#L190

I believe is might be part of the issue, especially the definition of `QueryCursor::matches` that do not "give" 'cursor to QueryMatches

**Comment by quentinLeDilavrec** [comment]
Btw, it might have something to do with https://smallcultfollowing.com/babysteps/blog/2013/10/24/iterators-yielding-mutable-references/ , but I am not sure.

**Comment by amaanq** [comment]
Fixed in https://github.com/tree-sitter/tree-sitter/pull/3504
