### ISSUE TITLE
`tree-sitter test` does not respect `CFLAGS` / `CXXFLAGS`

### ISSUE THREAD

**Issue by tgross35** [tree-sitter/tree-sitter#2849]
I would like to be able to test my scanner configuration with more warnings, but am unable to do so:

```sh
$ CC=banana CFLAGS=fake tree-sitter test
(output works)
```

Tree-sitter should respect CC/CXX on all files, and respect CFLAGS on files that aren't autogenerated. 

This isn't meant as a way to provide flags for downstream compilation, just an easier way to get the benefit of extra `Wall` output or similar.

As a workaround, I am using this crude command to check everything in `src/` with special flags:

```sh
$ find src/ -name '*.c' ! -name "parser.c" |
    xargs -IFNAME sh -c \
    'echo "\nCHECKING FILE FNAME" &&
    clang FNAME -c -Wall -Werror --pedantic -o/dev/null'
```

**Comment by clason** [comment]
Or at least provide a flag to force rebuild? That might be the easiest (and useful in other situations, e.g., where mtime check fails).

**Comment by tgross35** [comment]
Just for prior art - I believe that Make doesn’t detect env changed for rebuilds but Cargo always rebuilds if specific variables are set. A flag to force rebuild sounds reasonable, or maybe a flag to clean generated files.

Storing the hash of relevant env variables to a file could also work, but that might not be worth it if there isn’t already a cache/object location.

**Comment by ObserverOfTime** [comment]
#3188 adds support for environment variables but no rebuild flag yet.
