### ISSUE TITLE
Highlighting check doesn't verify multiple carat columns (`^`)

### ISSUE THREAD

**Issue by tgross35** [tree-sitter/tree-sitter#2854]
In the Sublime test specification, you should be able to repeat `^` characters, and each column gets checked. For example:

<img width="393" alt="image" src="https://github.com/tree-sitter/tree-sitter/assets/13724985/9f3eddb9-103a-4a3d-9b38-3694c491e945">

However, it doesn't seem like tree-sitter verifies this. If I add more carats so that the span should be invalid, the test still passes.

<img width="402" alt="image" src="https://github.com/tree-sitter/tree-sitter/assets/13724985/9783b621-b0d8-4057-9758-f639583105f5">

**Comment by amaanq** [comment]
pr welcome, would be cool to warn about this and either ignore that test or error out
