### ISSUE TITLE
`node.previousSibling` doesn't work on `MISSING` nodes

### ISSUE THREAD

**Issue by RedCMD** [tree-sitter/tree-sitter#2870]
Attempting to get the `previousSilbing` of a `MISSING` node results in `null`
even if you used `node.nextSibling` to get *to* the `MISSING` node. `previousSilbing` will still fail

**Comment by amaanq** [comment]
do you have a reproducer? I tried with a simple example using the JS grammar and could not reproduce this, I know this is old but it'd be nice if you had a reproducible example, this would be a good bug to fix

**Comment by RedCMD** [comment]
I can no longer seem to reproduce
currently using web-tree-sitter `0.23.0`
