### ISSUE TITLE
Bus error within `regexec`

### ISSUE THREAD

**Issue by tgross35** [tree-sitter/tree-sitter#2876]
I'm struggling with a very weird error that seems possibly related to tree-sitter's codegen. During testing, on some platforms there is a seemingly random SIGBUS within the call to `lexer->advance(lexer)`. This is proving awful to track down since for whatever reason it doesn't show up in CI, and only shows up on x86.

I'm wondering if it has something to do with glibc version since on my reproduction I am using 2.37, while github uses 2.35.

A minimal reproduction is with the source https://github.com/IndianBoy42/tree-sitter-just/tree/4c5c1f21ff871d57141d83dc606e433895698c42, parsing `foo := "abc"`. The expected tree is:

```scm
(source_file
  (item
    (eol))
  (item
    (assignment
      (identifier)
      (expression
        (value
          (string_literal)))
      (eol)))
  (item
    (eol)))
```

Output:

```
$ tree-sitter t -d -f 'assignment'
  statements:
new_parse
process version:0, version_count:1, state:1, row:0, col:0
lex_external state:2, row:0, column:0
  skip character:10
lexed_lookahead sym:_newline, size:1
shift state:92
process version:0, version_count:1, state:92, row:1, col:0
lex_external state:2, row:1, column:0
lex_internal state:11, row:1, column:0
  consume character:'f'
  consume character:'o'
  consume character:'o'
  consume character:'f'
lexed_lookahead sym:identifier, size:3
reduce sym:eol, child_count:1
reduce sym:item, child_count:1
shift state:100
process version:0, version_count:1, state:100, row:1, col:3
lex_internal state:0, row:1, column:3
  skip character:' '
  consume character:':'
  consume character:'='
lexed_lookahead sym::=, size:3
shift state:28
process version:0, version_count:1, state:28, row:1, col:6
lex_external state:3, row:1, column:6
  skip character:' '
Bus error
```

Backtrace:

```
$ lldb tree-sitter
(lldb) target create "tree-sitter"
Current executable set to '/home/tmgross/.cargo/bin/tree-sitter' (x86_64).
(lldb) r test
Process 77059 launched: '/home/tmgross/.cargo/bin/tree-sitter' (x86_64)
  statements:
    ✓ empty
Process 77059 stopped
* thread #1, name = 'tree-sitter', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x00007ffff7e7ff07 libc.so.6`__GI___regexec(preg=0x00007fffffffad58, string="\"", nmatch=1, pmatch=0x00007fffffffad30, eflags=2) at regexec.c:214:3
(lldb) f
frame #0: 0x00007ffff7e7ff07 libc.so.6`__GI___regexec(preg=0x00007fffffffad58, string="\"", nmatch=1, pmatch=0x00007fffffffad30, eflags=2) at regexec.c:214:3
(lldb) bt all
* thread #1, name = 'tree-sitter', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x00007ffff7e7ff07 libc.so.6`__GI___regexec(preg=0x00007fffffffad58, string="\"", nmatch=1, pmatch=0x00007fffffffad30, eflags=2) at regexec.c:214:3
    frame #1: 0x00007ffff7ef27ba libc.so.6`advance(string="\"", expbuf=<unavailable>) at regexp.c:78:7
    frame #2: 0x00007ffff7d74acc just.so`scan_string_start(lexer=0x0000555556084f10, state=0x0000555556069480, delim='\x03') at scanner.c:256:3
    frame #3: 0x00007ffff7d75157 just.so`tree_sitter_just_external_scanner_scan(payload=0x0000555556069480, lexer=0x0000555556084f10, valid_symbols=0x00007ffff7d7c0e4) at scanner.c:505:7
    frame #4: 0x0000555555893674 tree-sitter`ts_parser__lex + 820
    frame #5: 0x0000555555898f83 tree-sitter`ts_parser_parse + 723
    frame #6: 0x0000555555830616 tree-sitter`tree_sitter_cli::test::run_tests::hbee8e413547cad8e + 406
    frame #7: 0x000055555583097d tree-sitter`tree_sitter_cli::test::run_tests::hbee8e413547cad8e + 1277
    frame #8: 0x000055555583097d tree-sitter`tree_sitter_cli::test::run_tests::hbee8e413547cad8e + 1277
    frame #9: 0x000055555582db44 tree-sitter`tree_sitter_cli::test::run_tests_at_path::h50d732604d391ffc + 580
    frame #10: 0x00005555555de671 tree-sitter`tree_sitter::run::haefdda6aa769fe0a + 30497
    frame #11: 0x00005555555d6e1a tree-sitter`tree_sitter::main::hc534cfd99472cc91 + 10
    frame #12: 0x00005555555ce633 tree-sitter`std::sys_common::backtrace::__rust_begin_short_backtrace::h16f0b9334604a5f7 + 3
    frame #13: 0x00005555555e4349 tree-sitter`main + 953
    frame #14: 0x00007ffff7da5a90 libc.so.6`__libc_start_call_main(main=(tree-sitter`main), argc=2, argv=0x00007fffffffe0f8) at libc_start_call_main.h:58:16
    frame #15: 0x00007ffff7da5b49 libc.so.6`__libc_start_main_impl(main=(tree-sitter`main), argc=2, argv=0x00007fffffffe0f8, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007fffffffe0e8) at libc-start.c:360:3
    frame #16: 0x00005555555ca89e tree-sitter`_start + 46
```

I have some more digging to do, but any pointers are appreciated since I don't know why there would be a segfault within advance.

**Comment by tgross35** [comment]
This is pretty bizarre. I wrote up some more here: https://github.com/IndianBoy42/tree-sitter-just/issues/69#issuecomment-1909510387

**Comment by tgross35** [comment]
Yeah, I know that is most likely. I just can't figure out why it's showing up under `advance`. That could be due to optimizations since there are missing frames anyway - do you have any idea why the trace is incomplete even when running with `--debug-build`?

**Comment by tgross35** [comment]
More fuzzing keeps on pointing to a failure at the same spot unfortunately. I also wish I better understood why I can't replicate this with my own setup.

(this can be replicated with my branch at https://github.com/tgross35/tree-sitter-just/tree/ci-update, current head 37f28b271e0046ff78d20f2938f0157a01b4bfae. `just debug test/highlight/crash-assertion-simplified.just` completes successfully, but `tree-sitter parse test/highlight/crash-assertion-simplified.just` and `just fuzz` both fail)

**Comment by amaanq** [comment]
I'm not getting a bus error, I'm getting the assertf failing

**Comment by tgross35** [comment]
Definitely welcome! I’d recommend you base it on the `next` branch since it has what I think is the more correct scanner, that unfortunately segfaults.

If you can’t reproduce the issue, are you on x86 Linux? I couldn’t reproduce it at all on my main aarch development machine.

Fwiw I never used Just until about two months ago, now I have one for every project :) great replacement for the dozens of tiny shell and python scripts that accumulate

**Comment by amaanq** [comment]
yeah I'm on x86_64 Linux - platform shouldn't matter in this case imo

**Comment by amaanq** [comment]
I'll close this out since it's difficult to reproduce, is more about the grammar's scanner, and I've PRed a fix/improvement to it anyways
