### ISSUE TITLE
Unable to npm install tree-sitter-cli

### ISSUE THREAD

**Issue by dxxvi** [tree-sitter/tree-sitter#2877]
My computer at work needs to go to a proxy to go to the internet. I set this in powershell `$env:HTTPS_PROXY='http://10.0.88.11:8080'`. I can see that env var with `dir env:`.

I also have this in `.npmrc`:
```
https_proxy=http://10.0.88.11:8080
proxy=http://10.0.88.11:8080
```

I got this when running `npm install tree-sitter-cli`
```
npm ERR! code 1
npm ERR! path D:\Users\xyz\node\node_modules\tree-sitter-cli
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! Downloading https://github.com/tree-sitter/tree-sitter/releases/download/v0.20.8/tree-sitter-windows-x64.gz
npm ERR! Download failed
npm ERR!
npm ERR! url: https://github.com/tree-sitter/tree-sitter/releases/download/v0.20.8/tree-sitter-windows-x64.gz
npm ERR! status: 400
npm ERR! headers: {
npm ERR!   "cache-control": "no-cache",
npm ERR!   "x-xss-protection": "1",
npm ERR!   "connection": "close",
npm ERR!   "content-type": "text/html; charset=utf-8",
npm ERR!   "content-length": "1346",
npm ERR!   "pragma": "no-cache"
npm ERR! }
```

I guess `C:\Windows\system32\cmd.exe /d /s /c node install.js` didn't use the proxy although I already added `HTTPS_PROXY` to my windows account env variables.

Does anybody know how to fix this issue?

**Comment by amaanq** [comment]
I think this is fixed by #2824, let me know if not. I cannot test on a Windows machine using a proxy
