### ISSUE TITLE
[TSInput] looking for help on tree-sitter's C API

### ISSUE THREAD

**Issue by jiax1aobo** [tree-sitter/tree-sitter#2882]
I encountered some problems while writing a program:
`ts_parser_parse()` is called when generating a parse tree from a file (not a string). 
This function requires a variable of type `TSInput` as a parameter. 
The parameter contains a `read` function pointer defined as follows
```c
const char *(*read)(
    void *payload, 
    uint32_t byte_index, 
    TSPoint position, 
    uint32_t *bytes_read);
```
**Questions**
1. Is `TSPoint` both an input parameter and an output parameter? Do I need to update it (row, column) every time `read` is called?
2. Is the actual position of the file read from the position specified by `TSPoint` plus `byte_index`?

**Comment by amaanq** [comment]
It's an input parameter, you can use the TSPoint information as a guide to know where you are in the document, if relevant for your needs - this is advanced by the lexer and given to you as an input.

Byte index is the actual byte index (useful for you probably) in the file, you could seek to this to get the correct value. TSPoint is the (row, col) representation of the byte index.

**Comment by amaanq** [comment]
I'll assume your question was answered, if not, feel free to let me know and I'll reopen this, thanks

**Comment by jiax1aobo** [comment]
Thank you for your reply, it helped me!
No problem closing the issue.
