### ISSUE TITLE
Case-insensitive highlighting

### ISSUE THREAD

**Issue by sebastiaanspeck** [tree-sitter/tree-sitter#2883]
I have a keyword `_true` which is case insensitive. I wrote the rule as `true: $ => /_true/i`. 
I also have another keyword `_if` which is case insensitive as well. I wrote the rule as:

```
if: $ =>
    seq(/_if/i,
           ...
           /_endif/i,
    ),
```

This works okay, but how can I highlight this using `highlights.scm`? `"_if"` will result in `Invalid node type _if`.
I know you can do something like:
```
((if) @keyword
 (.match? @keyword "_if"))
```

But this will colour the whole sequence, I only want to colour the keywords `_if` and `_endif`.

**Comment by amaanq** [comment]
Regex nodes are not queryable because they could match potentially anything (there's no "term" to nail them down). A workaround to this is to alias it to a string literal, i.e.
```js
if: $ => seq(alias(/_if/i, '_if'), ....),
```
This allows you to query for "_if" now while still maintaining that the rule is a regex case-insensitive match
