### ISSUE TITLE
Confusion about the reported version of tree-sitter.

### ISSUE THREAD

**Issue by MadCatX** [tree-sitter/tree-sitter#2885]
Programs that link against tree-sitter may attempt to use pkg-config to check its version. It appears that the version of the tree-sitter library specified in the Makefile is not in sync with the version of tree-sitter as tagged in git. This leads to build failures when configuration scripts attempt to check which version of tree-sitter is available and erroneously attempt to build against wrong versions of tree-sitter. See, for example https://github.com/neovim/neovim/issues/27242

**Comment by clason** [comment]
(note that the linked issue is incorrect; Neovim does _not_ use pkgconfig to verify the tree-sitter version)

**Comment by MadCatX** [comment]
My apologies. It appears that Neovim is not doing any version check of the tree-sitter library. I assume this is intentional and expected to work like this. Please disregard.

**Comment by clason** [comment]
The makefile is still wrong and should be corrected...

**Comment by sukrosono** [comment]
kindly elaborate the wrong part and the correction, no experience on makefile but want to be involved if needed.
