### ISSUE TITLE
wasmtime dependency

### ISSUE THREAD

**Issue by 0323pin** [tree-sitter/tree-sitter#2886]
Hi,

Any reason to pull `wasmtime` dependencies from a [git-commit](https://github.com/tree-sitter/tree-sitter/blob/78c297e6edbb2afe069ec03f2a0f5fd9eb340abb/lib/Cargo.toml#L32)?

I've checked the repository and there are releases available with that specific commit already merged.

The reason I'm asking is that pulling from git breaks offline builds and requires package maintainers (me in this case) to patch this prior to build.

Thanks!

**Comment by amaanq** [comment]
The issue is wasmtime-c-api isn't published on crates.io, see https://github.com/bytecodealliance/wasmtime/issues/7735

We will resolve this sometime the coming week most likely via either checking it out locally here as a submodule, or something along those lines.

**Comment by 0323pin** [comment]
I see, thanks. It also explains why the latest `tree-sitter-cli` is not available from crates.io, as it's using an _unpublished_ crate.

As you mentioned, I hope this gets sorted soon. In the meantime, I'll see if I can update our package to 0.20.9 with a patch to pre-fetch the crate from github.

**Comment by 0323pin** [comment]
So, I've tried this patch,
```
--- lib/Cargo.toml.orig 2024-01-29 09:40:50.403835349 +0000
+++ lib/Cargo.toml
@@ -29,15 +29,17 @@ wasm = ["wasmtime", "wasmtime-c-api"]
regex = "1.9.1"

[dependencies.wasmtime]
-git = "https://github.com/bytecodealliance/wasmtime"
-rev = "fa6fcd946b8f6d60c2d191a1b14b9399e261a76d"
+path = "../../vendor/wasmtime-fa6fcd946b8f6d60c2d191a1b14b9399e261a76d"
+#git = "https://github.com/bytecodealliance/wasmtime"
+#rev = "fa6fcd946b8f6d60c2d191a1b14b9399e261a76d"
optional = true
default-features = false
features = ["cranelift"]

[dependencies.wasmtime-c-api]
-git = "https://github.com/bytecodealliance/wasmtime"
-rev = "fa6fcd946b8f6d60c2d191a1b14b9399e261a76d"
+path = "../../vendor/wasmtime-fa6fcd946b8f6d60c2d191a1b14b9399e261a76d"
+#git = "https://github.com/bytecodealliance/wasmtime"
+#rev = "fa6fcd946b8f6d60c2d191a1b14b9399e261a76d"
optional = true
package = "wasmtime-c-api-impl"
default-features = false
```

But it now fails with,
```
error: failed to get `ansi_term` as a dependency of package `tree-sitter-cli v0.20.9 (/usr/pkgsrc/wip/tree-sitter-cli/work/tree-sitter-0.20.9/cli)`

Caused by:
  failed to load source for dependency `ansi_term`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to update replaced source registry `crates-io`

Caused by:
  failed to load checksum `.cargo-checksum.json` of wasmtime-cli v15.0.0

Caused by:
  failed to read `/usr/pkgsrc/wip/tree-sitter-cli/work/vendor/wasmtime-fa6fcd946b8f6d60c2d191a1b14b9399e261a76d/.cargo-checksum.json`

Caused by:
  No such file or directory (os error 2)
```

Building it online with cargo works but, I see
```
cargo build --release
    Updating crates.io index
    Updating git repository `https://github.com/bytecodealliance/wasmtime`
    Updating git submodule `https://github.com/WebAssembly/wasm-c-api`
    Updating git submodule `https://github.com/WebAssembly/WASI`
    Updating git submodule `https://github.com/WebAssembly/wasi-nn`
    Updating git submodule `https://github.com/WebAssembly/testsuite`
    Updating git submodule `https://github.com/WebAssembly/wasi-testsuite.git`
    Updating git submodule `https://github.com/WebAssembly/wasi-threads`
  Downloaded tinyvec_macros v0.1.1
  [...]
  Downloaded 77 crates (6.2 MB) in 4.55s
   Compiling libc v0.2.149
   [...]
   Compiling tree-sitter v0.20.10 (/home/pin/Downloads/tree-sitter-0.20.9/lib)
   [...]
   Building [=======================> ] 115/116: tree-sitter(bin)
   Finished release [optimized] target(s) in 6m 01s
```

Would the upcoming fix also avoid the use of git submodules?
These are really a PITA when it comes to packaging.

**Comment by amaanq** [comment]
Yeah, we're hoping that wasmtime will publish the c api to crates, Max has opened a PR for that that seems to be positively received, so let's hope for that! Otherwise if in the off-chance that's shut down, we'd either publish it without the wasm feature, or just use the submodule option (both options we also don't want to resort to).

**Comment by 0323pin** [comment]
Thanks! I saw the PR, hopefully it gets merged soon.
I'm keeping an eye on it but, please do ping me in case I would miss it.

**Comment by 0323pin** [comment]
@amaanq Thanks!

https://mail-index.netbsd.org/pkgsrc-changes/2024/02/22/msg294021.html

**Comment by 0323pin** [comment]
Also, thanks to @maxbrunsfeld for https://github.com/bytecodealliance/wasmtime/pull/7837
