### ISSUE TITLE
Unicode regex range escaping lost in grammar.js

### ISSUE THREAD

**Issue by jmitchell** [tree-sitter/tree-sitter#289]
In a `grammar.js` I generated from an ABNF grammar `/[\u005E-\u007A]/` wasn't matching `z`, which happens to be the final character in the specified range. The generated `src/grammar.json` shows the range isn't escaped:

    {
      "type": "PATTERN",
      "value": "[^-z]"
    }

Coincidentally the unescaped `^` at the start of the range must be changing to negative matching semantics.

# Hacky workaround

When I manually use `/[\x5E-\x7A]/` instead the corresponding part of the `grammar.json` is `"[\\x5E-\\x7A]"`. The preserved escaping allows `z` to be recognized. If the upper bound of the range were beyond `\xFF` mixing `\x` and `\u` seems to work, e.g. `/[\x5E-\uD7FF]/`.

If unicode escapes were preserved this surprising edge case wouldn't be a problem. Unless the unescaping was intentional for some reason I can try implementing a fix if you'd like.

**Comment by maxbrunsfeld** [comment]
There's some explicit code for dealing with unicode escape sequences in regexes, which I added way back in https://github.com/tree-sitter/tree-sitter-cli/pull/3. I think this may not be needed anymore, now that we're using [`regex_syntax`](https://docs.rs/regex-syntax/0.6.5/regex_syntax/) to parse these regexes.

**Comment by maxbrunsfeld** [comment]
Thanks for the detailed info on this bug. Always good when you can fix a bug purely by deleting code.
