### ISSUE TITLE
Int types instead of string

### ISSUE THREAD

**Issue by alehander42** [tree-sitter/tree-sitter#292]
Hey, is it possible to easily tweak / add a flag so treesitter can generate int types instead of string ones? I see how string types are pretty useful, but for some cases having a grammar-specific optimized representation might be ok. mapping the node names to integers and generating a simple mapping array in the parser might be sufficient for this usecase: my question is is this currently possible and if not , does it make sense to add it upstream?

**Comment by maxbrunsfeld** [comment]
Yeah, you can already get an integer representation of a node's type using the [`ts_node_symbol`](https://github.com/tree-sitter/tree-sitter/blob/e6d6b4a70034f1433155649bf2ee9705eaf241d4/lib/include/tree_sitter/api.h#L111) function. If you want to convert between the `TSSymbol` (integer) values and the string values, you can use the [`ts_language_symbol_name` and `ts_language_symbol_for_name`](https://github.com/tree-sitter/tree-sitter/blob/e6d6b4a70034f1433155649bf2ee9705eaf241d4/lib/include/tree_sitter/api.h#L147-L148) functions.

Do those APIs solve your problem?

**Comment by Aerijo** [comment]
@maxbrunsfeld I use those with C++, but are they available in other languages? I don't recall seeing them be used in any docs or examples.

**Comment by maxbrunsfeld** [comment]
Oh yeah, I'm not sure what language @alehander42 is talking about. The term `int` made me think it was C/C++. These functions are also exposed in the Rust binding.

**Comment by alehander42** [comment]
yeah ts_symbol seems to work indeed: i am working with nim bindings to the c++ version, so i can use it, thanks
