### ISSUE TITLE
Local playground doesn't work

### ISSUE THREAD

**Issue by mingodad** [tree-sitter/tree-sitter#2977]
While testing `tree-sitter-c` and `tree-sitter-bash` and trying to use the local playground I'm getting the error shown bellow.

```
tree-sitter 0.20.9 (38cb60ccda32e87f2389ed1b5e6456c91c879ec6)
```
command:
```
tree-sitter build-wasm
tree-sitter playground
```
browser console:
```
payground.js:90 RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.
    at oe (tree-sitter.js:1:6761)
    at k (tree-sitter.js:1:4462)
    at he (tree-sitter.js:1:7991)
    at xe (tree-sitter.js:1:9810)
    at tree-sitter.js:1:47405
    at async handleLanguageChange (playground.js:88:44)
    at async playground.js:78:3
```

**Comment by sogaiu** [comment]
FWIW, with both:

```
tree-sitter 0.20.9 (98be227227af10cc7a269cb3ffb23686c0610b17)

tree-sitter 0.20.9 (38cb60ccda32e87f2389ed1b5e6456c91c879ec6)
```

and emsdk 3.1.37:

```
$ source ~/src/emsdk.3.1.37/emsdk_env.sh 
Setting up EMSDK environment (suppress these messages with EMSDK_QUIET=1)
Adding directories to PATH:
PATH += /home/user/src/emsdk.3.1.37
PATH += /home/user/src/emsdk.3.1.37/upstream/emscripten

Setting environment variables:
PATH = /home/user/src/emsdk.3.1.37:/home/user/src/emsdk.3.1.37/upstream/emscripten:/home/user/src/git-subrepo/lib:/home/user/.cargo/bin:/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/usr/lib/jvm/default-jdk/bin:/usr/lib/jvm/default-jre/bin
EMSDK = /home/user/src/emsdk.3.1.37
EMSDK_NODE = /home/user/src/emsdk.3.1.37/node/15.14.0_64bit/bin/node
```

the subcommands (`build-wasm` and `playground`) work for me for both `tree-sitter-c` (ecdd500806cf8154d944344f1df6418b32e0e9a7) and `tree-sitter-bash` (270c06b20567af619da1272dcd32ced9f42951d7).

What version of emsdk [1] are you using?

---

[1] Of interest might be [this](https://github.com/sogaiu/ts-questions/blob/c67b1611396e7190fb8d3a9ac80def65a6850f59/questions/which-version-of-emscripten-should-be-used-for-the-playground/README.md#versions).

**Comment by mingodad** [comment]
Here is my emsdk version:
```
emsdk-env emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.41 (71634e036d20209a5d81c2b2171e145b44de1e12)
clang version 17.0.0 (https://github.com/llvm/llvm-project 88421ea973916e60c34beb26597a5fc33f83dd8f)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /home/mingo/local/emsdk-git/upstream/bin
```

**Comment by amaanq** [comment]
How did you install tree-sitter?

**Comment by mingodad** [comment]
From a clone of this repository and `cargo build --release`.

**Comment by mingodad** [comment]
I have this https://mingodad.github.io/parsertl-playground/playground/ built with my actual emsdk (shown above) and it works fine.

**Comment by amaanq** [comment]
Ok, I was able to reproduce. When installing locally, your local server fetches the upstream `tree-sitter.js` which contains the interface for js <-> wasm parsers, that site's files are *very* outdated so it cannot locate some names/functions that were added or changed. I'll update that soon, but if you want to use a locally built `tree-sitter.js` by default, you can run `./script/build-wasm` then reinstall with cargo. We'll work on infra to keep the site's definitions updated more regularly automatically, the last push to it was 2yrs ago.

**Comment by mingodad** [comment]
When trying to install I'm getting this error:
```
cargo install
error: found a virtual manifest at `/home/mingo/dev/c/A_grammars/tree-sitter/Cargo.toml` instead of a package manifest
```

**Comment by sogaiu** [comment]
FWIW, when I build tree-sitter locally, I do something close to what amaanq mentioned:

```
bash script/build-wasm --debug
```

before `cargo build` / `cargo build --release`.

**Comment by mingodad** [comment]
Ok ! after doing another `git pull` and rebuild `./script/build-wasm` and `cargo build --release` I've got it to work locally.

Thank you !

**Comment by mingodad** [comment]
After doing a `git pull` today I'm getting the error shown bellow even after `script/build-wasm && cargo build --release`.
```
tree-sitter build-wasm
emcc: warning: EXPORTED_FUNCTIONS is not valid with LINKABLE set (normally due to SIDE_MODULE=1/MAIN_MODULE=1) since all functions are exported this mode.  To export only a subset use SIDE_MODULE=2/MAIN_MODULE=2 [-Wunused-command-line-argument]
```

**Comment by sogaiu** [comment]
Possibly related https://github.com/tree-sitter/tree-sitter/pull/3003.

**Comment by amaanq** [comment]
yes that linked PR fixed the warning
