### ISSUE TITLE
Case insensitive grammar support

### ISSUE THREAD

**Issue by richjyoung** [tree-sitter/tree-sitter#299]
I can't find a way in the API to implement a case-insensitive grammar. Whilst it is possible to include case insensitivity manually in any regex, the resulting parser fails when the case of a terminal in a source file is different from the grammar.js definition.

**Comment by maxbrunsfeld** [comment]
I think this is a duplicate of https://github.com/tree-sitter/tree-sitter/issues/261.

**Comment by richjyoung** [comment]
In terms of regexes I agree, but for anyone else who ends up here the solution from https://github.com/tree-sitter/tree-sitter/issues/122 for keywords works well. It would however be nice to have a top level flag to specify that the entire grammar is case insensitive.
