### ISSUE TITLE
Fail to generate wasm for tree-sitter Kotlin

### ISSUE THREAD

**Issue by juli1** [tree-sitter/tree-sitter#2991]
### Problem

The tree-sitter-kotlin grammar cannot be generated with WASM

### Steps to reproduce

```
git clone https://github.com/fwcd/tree-sitter-kotlin
git clone https://github.com/emscripten-core/emsdk.git
(cd emsdk && ./emsdk install latest && ./emsdk activate latest)
source ./emsdk/emsdk_env.sh
npm install -g tree-sitter-cli
tree-sitter build-wasm /path/to/tree-sitter-kotlin
```

### Expected behavior

The `tree-sitter-kotlin.wasm` should be created

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.21.0-pre-release-1 (76baf8152adada3a630bba9691fadb413a8e3783)

### Operating system/version

ubuntu 22.04 x86_64 x86_64 x86_64 GNU/Linux

**Comment by amaanq** [comment]
aha, seems like the kotlin grammar uses [exit(3)](https://man7.org/linux/man-pages/man3/exit.3.html), which we don't want to rely on, we'd probably prefer `abort` (https://github.com/tree-sitter/tree-sitter/issues/805), I'll fix that here to include abort in the exported symbols and submit a PR to ts-kotlin to use abort

**Comment by juli1** [comment]
> aha, seems like the kotlin grammar uses [exit(3)](https://man7.org/linux/man-pages/man3/exit.3.html), which we don't want to rely on, we'd probably prefer `abort` (#805), I'll fix that here to include abort in the exported symbols and submit a PR to ts-kotlin to use abort

Thank you for your help 🙏

**Comment by dundargoc** [comment]
https://github.com/fwcd/tree-sitter-kotlin/pull/111 has been merged. @juli1 could you confirm the problem has been fixed?

**Comment by juli1** [comment]
> [fwcd/tree-sitter-kotlin#111](https://github.com/fwcd/tree-sitter-kotlin/pull/111) has been merged. @juli1 could you confirm the problem has been fixed?

yes, fixed. Thank you!
