### ISSUE TITLE
tree-sitter highlights/injections/locals support ~

### ISSUE THREAD

**Issue by Freed-Wu** [tree-sitter/tree-sitter#3000]
### Problem

For example:

```json
{
  "tree-sitter": [
    {
      "highlights": "~/.local/share/nvim/repos/github.com/nvim-treesitter/nvim-treesitter/queries/XXX/highlights.scm",
    }
  ]
}
```

### Expected behavior

`~` will be treated as `$HOME`

**Comment by dundargoc** [comment]
I'm not strictly against it, but this feels like a low-value suggestion tbh. This file is rarely changed IIUC and you're not really saving much typing. Could you describe in more detail *why* this is a problem exactly?

**Comment by amaanq** [comment]
pr welcome

**Comment by Freed-Wu** [comment]
> Could you describe in more detail why this is a problem exactly?

Some tree-sitter-X doesn't provide `queries/*.scm` however `nvim-treesitter` provide them. So I want to change the path to `nvim-treesitter`.

**Comment by clason** [comment]
That doesn't answer the question why you can't use a full path for this.
