### ISSUE TITLE
command line option to assign config path

### ISSUE THREAD

**Issue by Freed-Wu** [tree-sitter/tree-sitter#3001]
### Problem

```sh
tree-sitter --config=/the/path/of/new/config.json highlight /the/path/of/a/file
```

will ignore `~/.config/tree-sitter/config.json`

**Comment by amaanq** [comment]
why would you need that instead of  just editing your current config

**Comment by Freed-Wu** [comment]
Sometimes I want to temporarily use another config (theme, parser-directories) without changing my personal config :smile:
