### ISSUE TITLE
Add schema for node-types.json and ~/.config/tree-sitter/config.json

### ISSUE THREAD

**Issue by Freed-Wu** [tree-sitter/tree-sitter#3004]
### Problem

We have schema for grammar.json: <https://raw.githubusercontent.com/tree-sitter/tree-sitter/master/cli/src/generate/grammar-schema.json>

Can we have schemas for other json files? It can help users to edit them.

**Comment by amaanq** [comment]
You're not supposed to edit that as opposed to grammar.json just being an evaluated grammar.js, after which the cli processes that.

**Comment by Freed-Wu** [comment]
So how about `~/.config/tree-sitter/config.json`? I think user can edit it.

**Comment by amaanq** [comment]
ehh that's a pretty niche one and I'd find that useless, there's only 2 keys what would be the point?

**Comment by Freed-Wu** [comment]
A completion should be useful for user, if it can be edited.

![Screenshot from 2024-02-12 15-45-47](https://github.com/tree-sitter/tree-sitter/assets/32936898/3a230993-4854-434f-b9bc-e1a72e9b4b3a)

**Comment by amaanq** [comment]
it's filled in on init-config, there is nothing to change or add at the top level.

**Comment by Freed-Wu** [comment]
User still need to edit some field to make it work. Such as <https://github.com/tree-sitter/tree-sitter/issues/732>

If the config have possibility to be edited, a schema is useful.

**Comment by amaanq** [comment]
What relation does the tree-sitter section of package.json fields have here? You're deviating from the point and not understanding how useless a schema for two fields which are pretty *clear* as to what data they hold, there is *zero* reason to add a schema for the config, and your comment about using ".." as a default directory also makes *zero* sense. Grammar devs are *not* always parsing/testing code in the repo of their grammar, *nor* is it implied that *all* grammar directories live in the parent directory of a given grammar dir.

**Comment by Freed-Wu** [comment]
Oh, the screenshot is just a demo for a completion, not for `~/.config/tree-sitter/config.json`.

Currently, `~/.config/tree-sitter/config.json` only has 2 fields. If it be added more editable fields in future, a completion should be more useful.

**Comment by amaanq** [comment]
It will *not* have fields added, and hasn't in years.
