### ISSUE TITLE
Change official YAML parser

### ISSUE THREAD

**Issue by LuisPatino92** [tree-sitter/tree-sitter#3005]
### Problem

In the [Introduction/parsers](https://github.com/tree-sitter/tree-sitter/blob/master/docs/index.md?plain=1#L169) section of the Tree-Sitter documentation, [this repository](https://github.com/ikatyang/tree-sitter-yaml) is referenced as the official YAML parser. However, this repository appears to be abandoned by its maintainers, with its last PR dating back to May 2021 and numerous issues and PRs left unattended.

Additionally, according to a comment on [this issue](https://github.com/ikatyang/tree-sitter-yaml/issues/15#issuecomment-753301068), the parser was implemented without focusing on recovery when the YAML file is in an invalid state. This approach may explain errors such as the one reported in [this issue](https://github.com/tree-sitter/tree-sitter.github.io/issues/9), where the Playground does not function correctly.

### Steps to reproduce

Follow the link related in https://tree-sitter.github.io/tree-sitter/ for YAML in parsers section and check the state of the repository.

### Expected behavior

It would be great if on the Tree-Sitter landing page we recognize [FluidAttacks' fork](https://github.com/fluidattacks/tree-sitter-yaml) as the official YAML parser.

This fork was based on the currently recognized official repository and has made some independent changes that favor the quality of parsing. However, not being the official version causes this fork to diverge from the one widely adopted by the community.

Fluid Attacks is committed to the Open Source philosophy and has its own open-source projects such as: [Makes](https://github.com/fluidattacks/makes) and [Universe](https://gitlab.com/fluidattacks/universe).

Fluid wants to start maintaining this YAML parser and continue building on what ikatyang has already built, with the goal of working together with the community on a robust and constantly evolving version of this project.

Initially, we would seek to reduce technical debt. At the moment, many tests fail, and we have identified a critical failure (we are already working on that).

Subsequently, our intention would be to improve recovery in the face of invalid states.

Thanks!

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.20.8

### Operating system/version

Linux (Ubuntu 23.04)

**Comment by clason** [comment]
That parser is still using a C++ scanner, which is unacceptable. There's a new fork being worked on in tree-sitter-grammars.

(But in general, there's no point in fighting over front page coverage here. It doesn't earn anyone any privileges.)

**Comment by LuisPatino92** [comment]
Hello @clason, thank you for your prompt response!

Could you please clarify the following for me, when you mention "There's a new fork being worked on in tree-sitter-grammars", are you referring to another project for tree-sitter-yaml that is active and is implementing the scanner in C? If so, could you share the link to that project with me? I haven't been able to find it.

I believe the parser listed on the Tree-Sitter landing page does have an effect on where the community's efforts are directed, as it is likely to attract issues and PRs. Therefore, it is not advisable to point to an abandoned project.

To illustrate the point further, I've encountered many issues in various projects, such as this one: [quarto-dev/quarto-cli#2737](https://github.com/quarto-dev/quarto-cli/issues/2737). This indicates that there is an intention within the community to collaborate on a single project, typically the one recognized on the Tree-Sitter landing page. However, due to the lack of responsiveness from maintainers in approving issues and PRs, separate forks are created where efforts are invested independently.

Thanks!

**Comment by dundargoc** [comment]
> If so, could you share the link to that project with me? I haven't been able to find it.

Unsure if it's public yet. I think @amaanq is working on it. He might be able to provide more context.

**Comment by LuisPatino92** [comment]
Thanks a lot!
