### ISSUE TITLE
Missing field 'value' error detail

### ISSUE THREAD

**Issue by richjyoung** [tree-sitter/tree-sitter#305]
Invoking tree-sitter CLI (v0.14.5 from npm) on a valid JS file that has an undefined value somewhere within it quite rightly results in:

`missing field 'value'`

I presume this error is generated whilst parsing the resulting `src/grammar.json`, therefore it would be very useful to also print out some context information at the point the error occurred. However, I have not been able to find this in the source.

For further background, I solved this error once after referencing an invalid member of a PREC constant object (exactly the same as is done in tree-sitter-javascript), thereby effectively calling:

`rule: $ => prec(undefined, ...`

However after merging into a much larger file the same error has reappeared and I am unable to locate the cause without knowing the approximate location of the error in the JSON or the JS.

**Comment by maxbrunsfeld** [comment]
Yeah, we should check for any undefined arguments in the JS later and throw exceptions, instead of letting any fields be omitted from the JSON that’s passed to the core library.
