### ISSUE TITLE
Add type definitions to language bindings

### ISSUE THREAD

**Issue by segevfiner** [tree-sitter/tree-sitter#3072]
### Problem

Add TypeScript type definitions to generated language bindings, so that TypeScript won't complain when importing them.

They can also include actual typing, so that TypeScript will only allow passing a proper language object to `setLangauge` and types for the exported `nodeTypeInfo`. Though that may be difficult, as TypeScript does structural typing and doesn't have a proper concept of a newtype, and emulating it using `unique symbol` will require importing the symbol from a shared place, which requires some new dependency.

### Expected behavior

For language grammars in Node to have TypeScript typings.

**Comment by ObserverOfTime** [comment]
Is there a type that can be used for the language pointer?

**Comment by segevfiner** [comment]
That's the whole new type thing I mentioned. We will need to create some unique type by using a `unique symbol`, but to get that to type check we will need to import it from somewhere in the language types. Otherwise we can use `unknown` I guess...

**Comment by ObserverOfTime** [comment]
Something like this would probably work. I'll let you figure out the rest.

```typescript
type BaseNode = {
    type: string;
    named: boolean;
}

type ChildNode = {
    multiple: boolean;
    required: boolean;
    types: BaseNode[];
}

type NodeInfo = BaseNode & {
    subtypes: BaseNode[];
} | BaseNode & {
    fields: {[name: string]: ChildNode};
    children: ChildNode[];
}

type Binding = {
    name: string;
    language: unknown;
    nodeTypeInfo: NodeInfo[];
}

declare const _exports: Binding;
export = _exports;
```
