### ISSUE TITLE
Add Node.js prebuilds to language grammars

### ISSUE THREAD

**Issue by segevfiner** [tree-sitter/tree-sitter#3073]
### Problem

Having prebuilds is useful as you then don't have to have a compiler to use them, and can use the prebuilds to generate distributions for different operating systems without having to do so on each target operating system due to having to compile binaries.

This can be done by providing a GitHub Actions workflow, possibly generated by the cli `generate` command and appropriate config/scripts to be included in the package.json.

This will be easier if we migrate to napi as then we will only really need one binary per OS/arch combination rather than also for each major version of Node.js.

### Expected behavior

For language grammar for Node to have prebuilds.

**Comment by ObserverOfTime** [comment]
I tried that for tree-sitter-cli in https://github.com/ObserverOfTime/tree-sitter/commit/d1eace26f099c026b750f5c781b2fe0a950ff89e but the package would be too large.
Although, parser libraries should be considerably smaller so it would be doable for those.

**Comment by segevfiner** [comment]
I meant using prebuild/prebuild-install, like already used in node-tree-sitter. This won't make the package larger as it downloads prebuilds from a GitHub release.

**Comment by segevfiner** [comment]
Continuing on from https://github.com/tree-sitter/tree-sitter/pull/3106#discussion_r1509952206, if we want to use prebuildify instead of prebuild.

* The [workflows](https://github.com/tree-sitter/workflows/blob/main/.github/workflows/package-npm.yml) are not generated by default by `generate` so how are language authors supposed to know about them?
* Do we want our own prebuildify workflow or is there any workflow/action that we can reuse?
* Not using `node-gyp-build` is troublesome, as you need to for the `install` command for unsupported targets, and the logic to import the right addon module is quite a bit more complex with prebuildify than with prebuild.

**Comment by segevfiner** [comment]
Anyhow, this is an example of adding prebuild: https://github.com/segevfiner/tree-sitter-hello/compare/main...prebuild
And this one is an example of adding prebuildify: https://github.com/segevfiner/tree-sitter-hello/compare/main...prebuildify

Let me know which one you want to turn into a PR. And whether you want to do something about what I wrote above. e.g. To let users know where the shared workflows are.

@amaanq @ObserverOfTime @verhovsky

**Comment by ObserverOfTime** [comment]
> The [workflows](https://github.com/tree-sitter/workflows/blob/main/.github/workflows/package-npm.yml) are not generated by default by generate so how are language authors supposed to know about them?

The workflows are still subject to change but a reference in the docs would be nice to have.
Alternatively, there's a (not entirely official) [template](https://github.com/tree-sitter-grammars/template) that includes them.

> Do we want our own prebuildify workflow or is there any workflow/action that we can reuse?

I will update the package-npm workflow accordingly.

> Let me know which one you want to turn into a PR.

prebuildifiy is definitely the better option.
I can add it to #3126 which has a few more npm stuff.
