### ISSUE TITLE
npm publish access for tree-sitter-haskell

### ISSUE THREAD

**Issue by tek** [tree-sitter/tree-sitter#3080]
Hello @maxbrunsfeld, could you add me as a maintainer for the [npm package](https://www.npmjs.com/package/tree-sitter-haskell) of the haskell grammar?

My account is [tryp](https://www.npmjs.com/~tryp). Thanks!

### Problem

Nobody's uploading artifacts.

### Expected behavior

I have unlimited power

**Comment by amaanq** [comment]
it's probably preferred to have a CI action do this via the org-wide token `NPM_TOKEN`

**Comment by amaanq** [comment]
some of those packages (on crates **and** npm) had people publish them to npm before we (Max) did, hence why they're there ;) but I wouldn't be averse to adding you, it's just easier to do via ci though instead of asking Max everytime

**Comment by tek** [comment]
yep sounds reasonable. I'd be happy to be responsible for the npm presence, if that's necessary.
