### ISSUE TITLE
Binding rust : Query wrapper doesn't take ownership of the source, or doesn't reference it with a lifetime

### ISSUE THREAD

**Issue by fitz35** [tree-sitter/tree-sitter#3090]
### Problem

The query wrapper take a string slice and convert it to a byte slice, then to a C pointer, without specifying a lifetime or taking the ownership of the String, potentially leading to a bug if the String is dropped.

```rust

let src_code_slice = "(source_file (function_item (identifier) (parameters) (block (expression_statement (identifier)))))"
let query = 
{
let src_code = String::from(src_code_slice);
Query::new(tree_sitter_rust::language(), src_code.as_str()).expect("Error creating query")
};

// query still valid here
```

### Expected behavior

```rust

let src_code_slice = "(source_file (function_item (identifier) (parameters) (block (expression_statement (identifier)))))"
let query = 
{
let src_code = String::from(src_code_slice);
Query::new(tree_sitter_rust::language(), src_code.as_str()).expect("Error creating query")
};

// query invalid here
```

**Comment by amaanq** [comment]
Are you sure it's a bug? It's only needed in `ts_query_new` when parsing the query source text, which is called in `Query::new`, and the C code doesn't take ownership of the string. Unless you can actually produce a sample that exhibits a bug or UB I'll close this out
