### ISSUE TITLE
Support :nth-last-child in syntax style sheets

### ISSUE THREAD

**Issue by cstrahan** [tree-sitter/tree-sitter#311]
I have a language in which an expression like this

```
lib.utils.add 1.0 24
```

is parsed like so:

```
(expression [0, 0] - [1, 0]
  (app [0, 0] - [0, 20]
    (app [0, 0] - [0, 17]
      (select [0, 0] - [0, 13]
        (identifier [0, 0] - [0, 3])
        (attrpath [0, 4] - [0, 13]
          (identifier [0, 4] - [0, 9])
          (identifier [0, 10] - [0, 13])))
      (float [0, 14] - [0, 17]))
    (integer [0, 18] - [0, 20])))
```

It would be nice to be able to refer to the last `identifier` under the `attrpath` so that I could give it the `function` scope.

Could we add support for the `:nth-last-child` pseudo selector for this?

**Comment by maxbrunsfeld** [comment]
👍 Yeah, this would be a great feature. In the JSON that we generate, maybe we could reuse the `index` field on the `transitions` objects, storing these indices as negative numbers.

**Comment by maxbrunsfeld** [comment]
Closing this one out since property sheets have been removed in favor of Tree Queries #444, #448.

**Comment by cstrahan** [comment]
@maxbrunsfeld Is this possible to implement with Tree Queries as they are implemented now, or should I open an issue for that?

**Comment by maxbrunsfeld** [comment]
Yes, good question. I haven't documented this yet, but there is a `.` operator in tree queries that lets you specify positional information.

The "immediate" operator `.` can be used in three similar ways:
1. Before the first child node in a pattern, it means that there cannot be any
   named siblings before that child node.
2. After the last child node in a pattern, it means that there cannot be any named
   sibling after that child node.
2. Between two child nodes in a pattern, it specifies that there cannot be any
   named siblings between those two child nodes.

So in your case, you could use this pattern to capture the *last* identifier within an `attrpath` with the name `@function`:

```
(attrpath (identifier) @function .)
```
