### ISSUE TITLE
"expected &Language, found Language" in generated rust bindings on 0.21.0

### ISSUE THREAD

**Issue by asvarga** [tree-sitter/tree-sitter#3118]
### Problem

The bindings generated by `tree-sitter-cli` give this error:

```rs
49  |             .set_language(super::language())
    |              ------------ ^^^^^^^^^^^^^^^^^ expected `&Language`, found `Language`
    |              |
    |              arguments to this method are incorrect
```

I'm using `0.21.0` for both crate and cli versions. I installed the cli with `cargo install tree-sitter-cli`. Did `Parser::set_language`'s signature change recently?

Many of the crate's [readme](https://github.com/search?q=org%3Atree-sitter%20.set_language(super%3A%3Alanguage())&type=code)s also have the borrow.

### Steps to reproduce

```sh
git clone https://github.com/tree-sitter/tree-sitter-python.git # for example
cd tree-sitter-python
rm bindings/rust/lib.rs # force regeneration
tree-sitter --version # 0.21.0
cargo test # fails
```

### Expected behavior

Expect `tree-sitter generate` to generated tests that pass.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.21.0

### Operating system/version

macOS 12.0.1

**Comment by asvarga** [comment]
Building the cli by cloning `tree-sitter` and doing `cargo install --path cli/` fixes it, so it seems like an issue with published cli.

**Comment by amaanq** [comment]
next release (very soon) will fix this, sorry about that.

**Comment by fikriauliya** [comment]
In my case, (temporarily) downgrading to `0.20.4` solve this

```
[dependencies]
tree-sitter = "0.20.4"
```

**Comment by LuisMorenoSerrano** [comment]
> In my case, (temporarily) downgrading to `0.20.4` solve this
> 
> ```
> [dependencies]
> tree-sitter = "0.20.4"
> ```

Maybe **0.20.10** would be better (version immediately before the latest **0.21.0**)

**Comment by pramatias** [comment]
Got bitten by this one. Downgrading solved it.

**Comment by ObserverOfTime** [comment]
This has been resolved.
