### ISSUE TITLE
Add `sym.deref` function for getting the actual node the symbol refers to

### ISSUE THREAD

**Issue by alexmozaidze** [tree-sitter/tree-sitter#3125]
### Problem

I wanted to write a pre-process function that takes in a list of nodes (`$._expr`) and modifies every string literal and regex inside it to be wrapped in `token.immediate`, effectively solving https://github.com/tree-sitter/tree-sitter/issues/2351. However, I realized I hit a road block the moment I realized that a symbol is just a name wrapped in a type, and there's no way to get the actual node structure it refers to, which is unfortunate.

### Expected behavior

Add `sym.deref`, which would take a symbol (`$.some_symbol` or `sym('some_symbol')`) and turn it into its underlying node structure, allowing people to operate on it and pre-process nodes conveniently:
```js
module.exports = grammar({
  name: 'foo',

  rules: {
    // ...

    _thing: $ => seq('1', '2', '3'),

    _immediate_thing: $ => make_immediate(sym.deref($._thing)),

    // ...
  }
});
```

**Comment by ObserverOfTime** [comment]
#1102 is a better solution (if revived).
