### ISSUE TITLE
tree-sitter.DLL is missing almost all exports

### ISSUE THREAD

**Issue by modersohn** [tree-sitter/tree-sitter#3127]
### Problem

After commit f1eecf9, when I build tree-sitter.dll with zig for Windows (either x86 or x86_64), the resulting DLL is *only* exporting these functions:

-   ts_current_malloc
-   ts_current_calloc
-   ts_current_realloc
-   ts_current_free

### Steps to reproduce

1. Edit build.zig to build a DLL: change `addStaticLibrary` to `addSharedLibrary`
2. run `zig build` with the x86 platform being default
3. Inspect exported DLL symbols with dumpbin, DepencyWalker etc.

Only the 4 methods listed above are exported.

### Expected behavior

The DLL should export the full API.

### Tree-sitter version (tree-sitter --version)

current master

### Operating system/version

Windows 10 x86

**Comment by amaanq** [comment]
can you try out #3128? Sorry about that

**Comment by modersohn** [comment]
No worries and thanks for the quick reply.

Just checked out your "windows-moment" branch and can confirm that everything gets exported again (tested x86 only for now).

**Comment by amaanq** [comment]
great, thanks. I never knew using `__declspec(dllexport)` would cause every other symbol to become hidden - I sorta wanted to use it as a "force export even if we want this hidden", but the default behavior of windows exporting everything is *fine*

**Comment by jcs090218** [comment]
I've tried to build the DLL file on Windows and doesn't find any exports. 😕  

`dumpbin` output:

```console
Dump of file tree-sitter.dll

File Type: DLL

  Summary

       57000 .data
        4000 .pdata
       4B000 .rdata
        B000 .reloc
      119000 .text
        1000 .tls
```

I'm building with the commit 5d9605a91e74f4ba6fcaa7c0533c82919fd52d0c.
