### ISSUE TITLE
Memory Leak When Using Rust

### ISSUE THREAD

**Issue by Bruce-Hopkins** [tree-sitter/tree-sitter#3129]
### Problem

When using Rust and Tree Sitter, memory is not released when dropping the `Tree` struct.

I ran the following test to confirm my suspicions:
```rust
fn main() {
    let source_code = "fn main() {}\n".repeat(100000).to_string();
    let mut parser = Parser::new();
    parser
        .set_language(tree_sitter_rust::language())
        .expect("Error loading Rust grammar");
    let tree = parser.parse(source_code, None).unwrap();

    drop(tree);
    drop(parser);
    loop {
        // Sleep every 10 milliseconds to prevent high CPU usage
        let ten_millis = std::time::Duration::from_millis(10);
        std::thread::sleep(ten_millis);
        
    }
}
```
Even though we drop both variables containing the `Tree` and the `Parser` the memory usage of the program still shows around 50MB.

### Steps to reproduce

Compile the provided Rust code.

Alternatively, you can run the following repo I created to reproduce the results: https://github.com/Bruce-Hopkins/memory_tests
 1.  Run `git clone https://github.com/Bruce-Hopkins/memory_tests.git`
 2.  If Rust is installed, run `cargo run --release` to start the program
 3.  Check the memory usage of the program. 

### Expected behavior

My system monitor should display that the program is not using any memory, since the string, `Tree` and `Parser` structs have all been dropped. However, this program uses 46.6MB on my computer.

### Tree-sitter version (tree-sitter --version)

0.20.10

### Operating system/version

Fedora Linux 38

**Comment by amaanq** [comment]
yeah there's no memory leak here, valgrind and massif report nothing and I don't think RSS is exactly something you can go off of, since it seems to be very different from what massif and kde's system monitor report to me (these 2 are similar, showing a drop to ~800kb-1.2mb after the calls to `free`)

I'd like to guess that it's the system either reserving that memory for further reuse for that process, or it could be some other OS-level oddity, not sure

**Comment by Bruce-Hopkins** [comment]
I managed to track down what the issue I'm seeing is. @amaanq You are right that this is not a memory leak. It seems that the memory is being free, but not released to the OS, which is why memory profilers do not see an issue.

If we change the program to this: 
```rust
use tree_sitter::{Parser};
use libc;

fn main() {
    let source_code = "fn main() {}\n".repeat(100000).to_string();
    let mut parser = Parser::new();
    parser
        .set_language(tree_sitter_rust::language())
        .expect("Error loading Rust grammar");
    let tree = parser.parse(source_code, None).unwrap();

    drop(tree);
    drop(parser);

    // Release free memory in the heap.
    unsafe {libc::malloc_trim(0);}

    loop {
        // Sleep every 10 miliseconds to prevent high CPU usage
        let ten_millis = std::time::Duration::from_millis(10);
        std::thread::sleep(ten_millis);
        
    }
}
```
We call `malloc_trim` to release the memory within the heap. Although far from an ideal solution due to the usage of `unsafe` code, almost all of the memory gets released to the OS and my System Monitor shows very low memory.

**Comment by amaanq** [comment]
The default allocator is libc's for tree-sitter, bu you can set your own allocator with `ts_set_allocator` if you prefer something that holds onto memory for reusage less aggressively. You can also avoid pulling in libc for `malloc_trim` by playing with the env var `M_TRIM_THRESHOLD` or `MALLOC_TRIM_THRESHOLD_` - https://www.gnu.org/software/libc/manual/html_node/Malloc-Tunable-Parameters.html
