### ISSUE TITLE
Logging from scanner.cc

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#313]
Is there a way to log some variables in order to make debugging simpler? As we can't attach a debugger to the process, right?

**Comment by maxbrunsfeld** [comment]
Yeah, you can attach a debugger like LLDB. Or you can use printf.

**Comment by Razzeee** [comment]
I tried `printf` for now, unfortunately that seems to be cut off at some  point? And it's not in the debug result but it's own log?

```
./examples/test.elm     3 ms    (ERROR [3, 0] - [17, 0])

indent 0 indent_length_stack 0runback 1fullfil runback 1 2indent 16 indent_length_stack 16runback 2fullfil runback 1 2indent 16 indent_length_stack 16runback 2fullfil runback 1 2indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 8runback 2fullfil runback 2 2indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 8runback 2fullfil runback 2 2indent 4 indent_length_stack 8runback 3indent 4 indent_length_stack 8runback 3indent 4 indent_length_stack 8runback 3fullfil runback 1 2npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-elm@1.1.1 parse-test: `tree-sitter parse --debug ./examples/test.elm`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-elm@1.1.1 parse-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/razze/.npm/_logs/2019-03-31T00_22_44_308Z-debug.log
The terminal process terminated with exit code: 1


```

**Comment by maxbrunsfeld** [comment]
> `indent 0 indent_length_stack 0runback 1fullfil runback 1 2indent 16 indent_length_stack 16runback 2fullfil runback 1 2indent 16 indent_length_stack 16runback 2fullfil runback 1 2indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 8runback 2fullfil runback 2 2indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 16runback 3indent 8 indent_length_stack 8runback 2fullfil runback 2 2indent 4 indent_length_stack 8runback 3indent 4 indent_length_stack 8runback 3indent 4 indent_length_stack 8runback 3fullfil runback 1 2`

Seems like you just need to put a newline at the end of your log message?

**Comment by Razzeee** [comment]
I did try `\n` but that just causes that log to not show up at all anymore

**Comment by Razzeee** [comment]
> Also, is there a way to get the log if it doesn't crash?

Nevermind, works on linux, might have overlooked it on windows.
