### ISSUE TITLE
`get_column` causing side effects

### ISSUE THREAD

**Issue by banacorn** [tree-sitter/tree-sitter#314]
I'm not sure if this is intended, however, triggering `get_column` would cause the lexer to advance: 

https://github.com/tree-sitter/tree-sitter/blob/49392c8502091eff4340e9318a5e84f16c5bb81c/lib/src/lexer.c#L141-L145

If this side effect is intended (or inevitable somehow), then I think it should be documented.

Note: I found this when I was working on a workaround for https://github.com/tree-sitter/tree-sitter/issues/312.

**Comment by banacorn** [comment]
After some tinkering, I think that this is a bug, intended or not.

Is there any plan to fix this?

**Comment by maxbrunsfeld** [comment]
Calling `get_column()` mutates the lexer internally, but it should leave the lexer in the same exact state as it was before: it moves to the beginning of the line and then advances back to the original position in order to count the number of unicode characters. I'm not sure how it could be causing side effects.

**Comment by banacorn** [comment]
I've managed to setup a minimal experiment for reproducing the issue.
Please checkout [this branch](https://github.com/tree-sitter/tree-sitter-agda/tree/tree-sitter%23314). 

```bast
git clone git@github.com:tree-sitter/tree-sitter-agda.git
cd tree-sitter-agda
git checkout tree-sitter#314
```

I've put the description in README.
(calling `lexer->get_column(lexer)` more `n` times would set the line numbers off by `n`)

**Comment by banacorn** [comment]
I want to fix this. 

I'm looking at directories like [this one](https://github.com/tree-sitter/tree-sitter/tree/master/test/fixtures/test_grammars/external_extra_tokens), trying to figure out how to setup a test that utilizes `get_column()`. 
That `grammar.json` should be generated from some `grammar.js, but I can't seem to find it. @maxbrunsfeld can you help me?

**Comment by maxbrunsfeld** [comment]
Yeah, for those tests you just write the `grammar.json` manually, and add a `scanner.c`.

**Comment by banacorn** [comment]
@maxbrunsfeld is there anyway of testing against the source location of the output syntax tree?

The corpus test only make sure that the generated abstract syntax tree looks right (without source locations), but the problem I'm trying to fix lies in those source locations.

**Comment by bglgwyng** [comment]
#589 I was trying to fix this issue and I found that when the token includes line break(In my case, this was for the line fold implementation), _rollback-and-re-advance_ in `get_column` increases `self->current_position.extent.row`.

**Comment by banacorn** [comment]
@bglgwyng thank you, it's great to hear some new progress!

**Comment by bglgwyng** [comment]
Any progress on this issue?
If its priority is low, I want to fix it myself. However, I don't get the point of `ts_lexer__get_column`  implementation yet. Why doesn't it just return `self->current_position.extent.column`? What makes the result different?

**Comment by ahelwer** [comment]
@bglgwyng I don't know the answer for sure but in unicode for a lot of characters there are two ways of writing them with an accent/umlaut: (modifier)(character) or (modified character), where the latter is a single special-purpose symbol (kept for backcompat reasons) and the former is two symbols. However, the displayed glyph will only be a single symbol, and so perhaps tree-sitter counts this as a single symbol for the purpose of `get_column`.

It's good to know there's an actual performance cost for calling `get_column` though, I'll be a bit more clever about it maybe.

**Comment by Razzeee** [comment]
Hrm, I think this has changed and the issue should have been closed.
While I still struggle with it and especially how it works via the the node bindings, it's now side effect free as far as I know.
