### ISSUE TITLE
Incorrect query captures

### ISSUE THREAD

**Issue by MyPingO** [tree-sitter/tree-sitter#3141]
### Problem

```js
const multilineString = `Line 1
Line 2
Line 3`;

const multilineString = processString`Line 1
Line 2
Line 3`;

const multilineString = "Line 1 \
Line 2 \
Line 3";
```

```
(lexical_declaration(variable_declarator([(string) (template_string) (binary_expression(string))]))) @stringAssignment
(lexical_declaration(variable_declarator((call_expression[(template_string) (binary_expression(string))])))) @stringCallAssignment
```

This is what I'm using in the playground and what I'm testing locally in a .js file

All three variables are being captured by @stringAssignment when only the 1st and 3rd variable should be.
The second variable should be captured by @stringCallAssignment which it is.

When debugging, I see that the second variable is being captured as both a @stringAssignment and a @stringCallAssignment 

Second capture
```json
"name": "stringAssignment",
"text": "const multilineString = processString`Line 1\r\nLine 2\r\nLine 3`;"
```
Third Capture
```json
"name": "stringCallAssignment",
"text": "const multilineString = processString`Line 1\r\nLine 2\r\nLine 3`;"
```

### Steps to reproduce

Do the above in a tree-sitter playground or locally.

### Expected behavior

The second variable should only be captured as a `@stringCallAssignment` and not a `@stringAssignment` because it does not contain a `(string)` `(template_string)` or a `(binary_expression(string))`

### Tree-sitter version (tree-sitter --version)

web-tree-sitter@0.21.0

### Operating system/version

Windows 10

**Comment by savetheclocktower** [comment]
I've also observed this behavior on Pulsar's custom build of `web-tree-sitter` that's basically identical to 0.20.8.

It behaves as though alternations are treated as optional — any tree structure that does not match any of the possible alternations nonetheless seems to be captured as though that clause weren't present at all.

I would expect

```scm
(foo
  (bar [(one) (two)])
) @capture
```

to produce a union of the results of

```scm
(foo
  (bar (one))
) @capture
```

and 

```scm
(foo
  (bar (two))
) @capture
```

…but it seems to be returning results identical to


```scm
(foo
  (bar)
) @capture
```

instead.

**Comment by ObserverOfTime** [comment]
> All three variables are being captured by @stringAssignment when only the 1st and 3rd variable should be.
> The second variable should be captured by @stringCallAssignment which it is.
> 
> When debugging, I see that the second variable is being captured as both a @stringAssignment and a @stringCallAssignment

Reverse your query order.

> I've also observed this behavior on Pulsar's custom build of `web-tree-sitter` that's basically identical to 0.20.8.

If you can reproduce this with the latest normal build, feel free to submit a new issue.
