### ISSUE TITLE
Bug in displaying field names in playground

### ISSUE THREAD

**Issue by jessejenks** [tree-sitter/tree-sitter#3145]
### Problem

I thought this was an issue with running locally, but the playground on the github page has this same problem.

<img width="712" alt="tree-sitter-playground" src="https://github.com/tree-sitter/tree-sitter/assets/12037240/33cf554b-f09b-4a98-bf05-2d805337f674">

Looking into it now, it seems to be a bug introduced by #3103.

### Steps to reproduce

Go to playground page: https://tree-sitter.github.io/tree-sitter/playground

### Expected behavior

Shows the field name or nothing

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.20.8

### Operating system/version

macOS 14.3.1

**Comment by amaanq** [comment]
thanks for the report - should be fixed now.
