### ISSUE TITLE
`token.immediate` stops working when there's a `$._whitespace` node

### ISSUE THREAD

**Issue by alexmozaidze** [tree-sitter/tree-sitter#3146]
### Problem

While I was converting my grammar from manual whitespace (empty `extras`) to a more normal grammar (populated `extras`), I stumbled upon a bug that made `token.immediate` not work at all.

The bug comes up whenever you have whitespace defined as a node with regex, and using the same regex in `extras`, leading to 2 competing regexes ultimately breaking `token.immediate` as if it wasn't even there.

### Steps to reproduce

1. Create a grammar repo
2. Put the following contents into `grammar.js`
```js
const SYMBOL = /[a-zA-Z]+/;
const WHITESPACE = /\s+/;

module.exports = grammar({
  name: 'test',

  extras: $ => [
    WHITESPACE,
  ],

  rules: {
    source_file: $ => repeat($._expr),

    // Comment $._whitespace to make the grammar work properly
    _whitespace: $ => WHITESPACE,

    _expr: $ => choice(
      $.multi_symbol,
      $.symbol,
    ),

    multi_symbol: $ => prec.dynamic(0, seq(
      $.symbol,
      repeat1(seq(
        token.immediate('.'),
        $.symbol_immediate,
      )),
    )),

    symbol: $ => SYMBOL,
    symbol_immediate: $ => token.immediate(SYMBOL),
  }
});
```
3. Compile the grammar and parse with incorrect input
```bash
npx tree-sitter generate
npx tree-sitter parse /dev/stdin <<< 'a . b.c'
```
4. See it **not** contain any errors
5. Comment out `$._whitespace` node in the grammar rules
6. Re-compile the grammar and parse with the same incorrect input
7. See it work properly (generate error nodes)

### Expected behavior

Not sure, but the problem is there.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.21.0 (1c55abb5308fe3891da545662e5df7ba28ade275)

### Operating system/version

Linux Mint 21.3

**Comment by ObserverOfTime** [comment]
Can't you just use `$._whitespace` in `extras` instead?

**Comment by ObserverOfTime** [comment]
I tested it on the latest version and it no longer results in an error so it doesn't need a warning either.
