### ISSUE TITLE
Possible off-by-one error when using `ts_node_field_name_for_child`

### ISSUE THREAD

**Issue by yilinwei** [tree-sitter/tree-sitter#3151]
### Problem

Full repro is [here](https://github.com/yilinwei/treesitter-bug).

To summarize using `ts_node_field_name_for_child` gives a different node than for `ts_node_child_by_field_name`. It looks as though it might be an off by one error from the (tiny) reproduction.

### Steps to reproduce

Full repro is [here](https://github.com/yilinwei/treesitter-bug).

Running the `main` program gives the following output:

```
Full syntax tree: (compilation_unit (function_definition name: (identifier) body: (indented_cases (case_clause pattern: (wildcard) body: (integer_literal)))))
node via `node_child_by_field_name`: (indented_cases (case_clause pattern: (wildcard) body: (integer_literal)))
node via `field_name_for_child`: ("=")
```

The first "node via" line is printed by using `ts_node_child_by_field_name` with the string `body`.
The second "node via" line is printed by getting the field index via `ts_node_field_name_for_child`, then using `ts_node_child` to get the node.

Using a different field, such as "name" gives the same result.

### Expected behavior

Both these should give the same result.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.20.9

### Operating system/version

Linux

**Comment by WillLillis** [comment]
Not sure when this was fixed, but the two outputs are identical when I tried running your program with the latest master branch of tree-sitter:

```
Full syntax tree: (compilation_unit (function_definition name: (identifier) body: (indented_cases (case_clause pattern: (wildcard) body: (integer_literal)))))
node via `node_child_by_field_name`: (indented_cases (case_clause pattern: (wildcard) body: (integer_literal)))
node via `field_name_for_child`: (indented_cases (case_clause pattern: (wildcard) body: (integer_literal)))
```

**Comment by amaanq** [comment]
#2104 fixed this a while ago - you are compiling against an old lib version (probably 0.20.8), so try again with 0.20.9 and later.

**Comment by yilinwei** [comment]
> #2104 fixed this a while ago - you are compiling against an old lib version (probably 0.20.8), so try again with 0.20.9 and later.

That is odd; I got the version from running `pkg-config`; and couldn't find anything in the changeset since `0.20.9` so assumed master would still be broken.

```shell
> pkg-config --modversion tree-sitter
> 0.20.9
```
Investigating further, the distro (NixOS) seems to be pointing towards [`0.20.8`](https://github.com/NixOS/nixpkgs/blob/44950aa5a109261d36fe2fafa5f3cdea94da6508/pkgs/development/tools/parsing/tree-sitter/default.nix#L25) so I wonder why `pkg-config` has different information,

**Comment by amaanq** [comment]
maybe you have a local install as well from running `sudo make install` but the linked lib in your program is using the globally installed lib instead?

**Comment by yilinwei** [comment]
That is not the case; the metadata seems to be wrong.

In NixOS the binary is stamped with the exact location which you can check by running:

```sh
> readelf -d main | rg RUNPATH
```

We get the following output:

```
0x000000000000001d (RUNPATH)            Library runpath: [/home/yilin/devel/github/treesit-bug/outputs/out/lib:/nix/store/11hggnbymzzf4dka74hgsn6pkpmza3dk-tree-sitter-0.20.8/lib:/nix/store/1x0h1rrgw1jap96lz3qq08xjb17d0rag-libtree-sitter-scala/lib:/nix/store/p3jshbwxiwifm1py0yq544fmdyy98j8a-glibc-2.38-27/lib:/nix/store/4zp05qkzh9s3c3k7pp9d36vhiz3x8h9l-gcc-13.2.0-lib/lib]
```

You'll notice that I am indeed linking with `0.20.8`. However, if we navigate to the directory to check the metadata:

```
prefix=/nix/store/11hggnbymzzf4dka74hgsn6pkpmza3dk-tree-sitter-0.20.8
libdir=${prefix}/lib
includedir=${prefix}/include

Name: tree-sitter
Description: An incremental parsing system for programming tools
URL: https://tree-sitter.github.io/
Version: 0.20.9
Libs: -L${libdir} -ltree-sitter
Cflags: -I${includedir}
```

The version is `0.20.9`. I haven't delved into how this was generated by the distro, but the inconsistency is solved.

**Comment by amaanq** [comment]
ah okay sorry, that might've just been a mistake on our end back then for that release.
