### ISSUE TITLE
Save tree-sitter object to physical object, such as Json or Pickle

### ISSUE THREAD

**Issue by bdqnghi** [tree-sitter/tree-sitter#3160]
### Problem

I have a use case where I need to save the tree-sitter object as a physical object to avoid having to reparse the code in our pipeline; is there a feature in tree-sitter that can do this? If not, do we plan to include this feature?

The problem is that i can have some work around to save into Json format, but when load the physical object back, i want to be in the Tree-sitter Node object like the original version.

**Comment by ObserverOfTime** [comment]
Essentially a duplicate of #2845. See also tree-sitter/py-tree-sitter#98.
