### ISSUE TITLE
web-tree-sitter const reassignment error (0.22.0, 0.22.1)

### ISSUE THREAD

**Issue by eyelidlessness** [tree-sitter/tree-sitter#3163]
### Problem

The built JavaScript for `web-tree-sitter` throws an error when attempting to reassign a `const`. This error is present in both:

- 0.22.0
- 0.22.1

The code in question is:

```js
const e=C._malloc(SIZE_OF_INT),t=C._ts_parser_included_ranges(this[0],e);e=getValue(e,"i32");
```

Note: I copied this from the source as available on [NPM](https://www.npmjs.com/package/web-tree-sitter?activeTab=code), to be extra sure I'm not seeing some artifact of my own local build (which I was separately fighting with, before updating `web-tree-sitter` itself and then encountering this error).

### Steps to reproduce

1. Install `web-tree-sitter`, either version 0.22.0 or 0.22.1
2. Initialize the library and a language as normal
3. [...?] the affected code is in the `getIncludedRanges` method of `ParserImpl`. It's unclear what code path is followed to reach this point, but hopefully this is helpful enough to track down the issue.

### Expected behavior

A `const` should not be reassigned.

### Tree-sitter version (tree-sitter --version)

N/A? As far as I can tell this is isolated to web-tree-sitter

### Operating system/version

N/A? As far as I can tell, the affected code is not platform specific

**Comment by amaanq** [comment]
ugh sorry, I added a test for the tree's getIncludedRanges but not parser's so I didn't catch this

**Comment by michenriksen** [comment]
Hi @amaanq, thanks for resolving this issue. 🙇 When will the fix be available as a new release on [npmjs.com](https://www.npmjs.com/package/web-tree-sitter)?
