### ISSUE TITLE
Could http://tree-sitter.github.io/ be made to redirect to /tree-sitter

### ISSUE THREAD

**Issue by marijnh** [tree-sitter/tree-sitter#317]
The [root URL](http://tree-sitter.github.io/) for that domain gives a generic GitHub 404, which confused me quite a bit the first time I ran into it. (Firefox has a habit of completing only the domain when you start typing something that matches it in the URL box, even if you've never visited that directly.)

**Comment by maxbrunsfeld** [comment]
According to the [GitHub Pages docs](https://help.github.com/en/articles/user-organization-and-project-pages#user-and-organization-pages-sites), I think I would need to move the docs to their own repository called `tree-sitter.github.io`.

I wish there was a way to designate this as the "main" repo in the org. Maybe that's a feature request that I can give to my colleagues.

**Comment by marijnh** [comment]
Ah, I see, that's a result of the website serving multiple repositories. If it's a pain to set up, feel free to just close this—it's not a big deal either way.

**Comment by maxbrunsfeld** [comment]
I solved this in a quick and dirty way: https://github.com/tree-sitter/tree-sitter.github.io/blob/master/index.html
