### ISSUE TITLE
Documentation: "Creating parsers" missing information

### ISSUE THREAD

**Issue by xfornari** [tree-sitter/tree-sitter#3170]
### Problem

The [Project setup](https://tree-sitter.github.io/tree-sitter/creating-parsers#project-setup) section does not indicate that `package.json` must be updated with a *tree-sitter* section. As result, the given steps do not work and the message:

*Failed to locate a package.json file that has a "tree-sitter" section, please ensure you have one, and if you don't then consult the docs*

is issued.

I found a fix by adding in `package.json` the text:

```
  "tree-sitter": [
    {"file-types": ["YOUR_LANGUAGE_NAME"]}
  ] '
```

### Steps to reproduce

Follow the steps of the  [Project setup](https://tree-sitter.github.io/tree-sitter/creating-parsers#project-setup) section until

`tree-sitter generate`

### Expected behavior

Generation of a grammar for the given example

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.1

### Operating system/version

Windows 11

**Comment by ckindermann** [comment]
Thank you! I had the same issue and the fix works. Just thought I'd mention a small typo above:
It should be  
 ```JSON
 "tree-sitter": [
    {"file-types": ["YOUR_LANGUAGE_NAME"]}
  ] 
```
instead of
 ```JSON
 "tree-sitter": [
    {"file-types": ["YOUR_LANGUAGE_NAME"]}
  ] '
```
Again, thank you.

**Comment by andyferris** [comment]
The tutorial also misses a step about running `init-config`:

```
$ tree-sitter parse example-file
Warning: You have not configured any parser directories!
Please run `tree-sitter init-config` and edit the resulting
configuration file to indicate where we should look for
language grammars.

(source_file [0, 0] - [1, 0])
```

**Comment by clason** [comment]
That's just a warning, though, not an error (and unrelated to the original issue).

**Comment by andyferris** [comment]
A good point. Nonetheless, I do file it under 

 > "Creating parsers" missing information
 
 though... since someone can look at it at the same time.
 
When it happened to me I didn't understand whether "Big warning... (source_file ...)" was an error or a warning-then-success or what?
