### ISSUE TITLE
`ts_node_parent` sometimes returns the wrong node

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#3185]
### Problem

`ts_node_parent` sometimes returns the preceding sibling node instead of the parent node.

This was originally reported at https://github.com/emacs-tree-sitter/elisp-tree-sitter/issues/274.

I could reproduce it with the Python bindings.

### Steps to reproduce

Build the Python grammar
```bash
git clone https://github.com/tree-sitter/tree-sitter-python
cd tree-sitter-python
git reset --hard b8a4c641
tree-sitter generate
tree-sitter build -o tree-sitter-python.dylib
```

Install the Python bindings. Current version is `0.21.0`.
```python
from tree_sitter import *
py = Language("tree-sitter-python.dylib", "python")

p = Parser()
p.set_language(py)

tree = p.parse("def dupa(foo):".encode('utf-8')); tree
# <tree_sitter.Tree at 0x10691a050>

tree.root_node.sexp()
# '(module (function_definition name: (identifier) parameters: (parameters (identifier)) body: (block)))'

fd = tree.root_node.child(0); fd
# <Node type=function_definition, start_point=(0, 0), end_point=(0, 14)>

blk = fd.child(4); blk
# <Node type=block, start_point=(0, 14), end_point=(0, 14)>

blk.parent
# <Node type=":", start_point=(0, 13), end_point=(0, 14)>
```

### Expected behavior

`blk.parent` should be the same as `fd`.

### Tree-sitter version (tree-sitter --version)

0.22.2

### Operating system/version

macOS 12.6.3

**Comment by amaanq** [comment]
Interesting, this seems similar to #2580
