### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by glyh** [tree-sitter/tree-sitter#3213]
### Problem

I'm using a tree-sitter grammar that depends on this package, and when running npm install, it seems to be running https://github.com/tree-sitter/tree-sitter/blob/master/cli/npm/install.js. And then everything stuck forever. I tried to set HTTP_PROXY and HTTPS_PROXY and that doesn't seem to be working. Doesn't npm wipe all your environment variables when running scripts?

### Steps to reproduce

```sh
git clone https://github.com/Nsidorenco/tree-sitter-fsharp
cd tree-sitter-fsharp
npm install
```

### Expected behavior

Install successfully

### Tree-sitter version (tree-sitter --version)

Globally installed: tree-sitter 0.22.2 (fc15f621334a262039ffaded5937e2844f88da61)

### Operating system/version

`Linux mechrevo 6.8.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000 x86_64 GNU/Linux`

**Comment by amaanq** [comment]
dependency in that grammar's package.json is outdated, this was fixed with #1643
