### ISSUE TITLE
web-tree-sitter does not work according to instructions

### ISSUE THREAD

**Issue by BrandonALittle** [tree-sitter/tree-sitter#3221]
### Problem

The instructions for working with web-tree-sitter do not work. Please revise

### Steps to reproduce

Follow the instructions for the use of web-tree-sitter. See that they don't work. wasm modules do not load correctly, and attempting to create a parser in a typescript module also does not work.

### Expected behavior

I would expect to be able to get started with tree-sitter in a web app. 

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.2

### Operating system/version

macOS 14.4

**Comment by rooney** [comment]
Hi @BrandonALittle

The instructions is a bit disjointed, I need to jump around between sections, but it works for me. What issue are you having?

Here's the steps that I did:
```
mkdir webts-example
cd webts-example
npm install web-tree-sitter tree-sitter-cli tree-sitter-javascript
node example.js
```
[example.js](https://github.com/tree-sitter/tree-sitter/files/14765823/example.js.zip)
Let me know if it works for you

**Comment by amaanq** [comment]
pretty vague issue, it'd be nice if you could actually explain what step/command/piece of code didn't work

**Comment by BrandonALittle** [comment]
I understand why you would be annoyed at a vague 'it doesn't work'
complaint. But that's the reality of the situation. Literally nothing I
tried worked as described in the instructions:
* using the CLI to build grammars (especially for typescript, which I
believe was mentioned in my original post)
* loading wasm js AND grammar files into the browser with script tags
(errors related to 'magic numbers' not matching)
* using tree-sitter in a module, importing from node module

I think your original instructions are incredibly vague. I am not a genius
engineer, but maybe when you read the instructions you're able to fill in
all of the gaps and so they sound clear to you. If there are complications
related to modules, magic numbers, dynamic require() invocations, the CLI,
building wasm files, and building/using grammars like
tree-sitter-typescript, you could make your software easy to use with a
little more description and explanation. I'm sorry that I don't know every
nuance of web development that might become a complication, but I didn't
write this software (which seems incredibly useful) or write the
instructions. If you could walk through the instructions yourself, and make
yourself aware of all of your assumptions or pre-acquired knowledge that
fills in all of the gaps, I think you might see all the ways in which you
are putting the onus on the user to figure things out.

I appreciate Ron's attempt at an example, and although it might work, I'm
trying to use tree-sitter to parse Typescript into an ast and traverse it.
