### ISSUE TITLE
tree-sitter-cli 0.22.1  break tree-sitter-typescript wasm build

### ISSUE THREAD

**Issue by bytemain** [tree-sitter/tree-sitter#3233]
### Problem

when using tree-sitter-cli 0.22.1 with docker
will encounter this issue:
- https://github.com/tree-sitter/tree-sitter/issues/3338

![CleanShot 2024-03-29 at 10 30 54@2x](https://github.com/tree-sitter/tree-sitter/assets/13938334/e5d20546-d225-4399-b959-9b86c1fc1656)

because it include a header file out of its src directory

### Steps to reproduce

```
npm install tree-sitter-cli tree-sitter-typescript

tree-sitter build --wasm --output ./tree-sitter-typescript.wasm ./node_modules/tree-sitter-typescript/typescript
```

### Expected behavior

tree-sitter-typescript.wasm can be output

### Tree-sitter version (tree-sitter --version)

tree-sitter-cli 0.22.1

### Operating system/version

macOS Sonoma 14.4

**Comment by sogaiu** [comment]
I think the [`build` subcommand may have been added between 0.22.1 and 0.22.2](https://github.com/tree-sitter/tree-sitter/commit/99b93d83a11a84ad9a23f5248e126fe45c1a61d3).

---

For tree-sitter 0.22.1 (locally built) I get an error if trying to use `build` as a subcommand name:

```
error: unrecognized subcommand 'build'

  tip: a similar subcommand exists: 'build-wasm'

Usage: tree-sitter <COMMAND>

For more information, try '--help'.
```

```
$ tree-sitter --version
tree-sitter 0.22.1 (1c38d34deac5ae7ea797a559f596fb4ec9008eb4)
```

---

For tree-sitter 0.22.2 (also locally built) I had success, though I'm not using `npm` and friends:

```
git clone https://github.com/tree-sitter/tree-sitter-typescript
cd tree-sitter-typescript/typescript
# ensure appropriate emsdk is available
source ~/src/emsdk.3.1.37/emsdk_env.sh
tree-sitter build --wasm --output tree-sitter-typescript.wasm
```

```
tree-sitter --version
tree-sitter 0.22.2 (fc15f621334a262039ffaded5937e2844f88da61)
```

**Comment by bytemain** [comment]
I forgot to mention, this should only appear when using docker

**Comment by ObserverOfTime** [comment]
> I forgot to mention, this should only appear when using docker

I suppose the container does not include the `common` folder.
