### ISSUE TITLE
Tree-sitter sometimes discards a perfectly valid branch, resulting in ERROR, where valid parse tree exists

### ISSUE THREAD

**Issue by yanok** [tree-sitter/tree-sitter#3243]
### Problem

<details>
<summary><b>NOTE</b>: I can only reproduce this issue using a very weird grammar so far</summary>
The grammar used to get this issue is very non-LRish, in fact I did what the tree-sitter docs explicitly say not to do: I took the existing ANTLR grammar and converted it to tree-sitter. This had two consequences:

1. lots of conflicts (all simply accepted, relying on GLR algorithm to resolve them at run-time).
2. output parse trees has lots of unnecessary nesting and a bit hard to read.

So far I failed to make an isolated example to illustrate this issue, so I'm filing this with the links to the real grammar.

That being said, I still think that since tree-sitter accepts the grammar, it is still a bug in the implementation to miss the correct parse.
</details>

The grammar itself is [here](https://github.com/yanok/tree-sitter-dart/blob/main/grammar.js).

The test showing the problem is [here](https://github.com/yanok/tree-sitter-dart/blob/main/test/corpus/record_literal_issue.txt).

The playground to try it online is [here](https://yanok.github.io/tree-sitter-dart/playground/playground.html).

I've found three examples so far:

```dart
f() {
  (x, x);
}
```

```dart
var v = f((x, x));
```

```dart
var v = [(x, x)];
```

but the underlying issue I believe is the same. In all these cases `(x, x)` should be parsed as a record literal, but is parsed as a record type (the first case) or as a record pattern (2 and 3 cases). Please note that `(x, x)` indeed **can** be a record literal, a record type, and a record pattern in Dart. That's certainly one component of the problem.

Another thing that I believe contributes to the problem is that `x` can be both an `identifier` and a `typeIdentifier`, but these are _different_ rules.

Here are the logs:

* https://yanok.github.io/tree-sitter-dart/records_issue/expression_statement/log.html
* https://yanok.github.io/tree-sitter-dart/records_issue/record_argument/log.html
* https://yanok.github.io/tree-sitter-dart/records_issue/record_in_list/log.html

I looked through them and I think the most interesting thing is this transition: https://yanok.github.io/tree-sitter-dart/records_issue/expression_statement/suspicious_transition.html (there are also https://yanok.github.io/tree-sitter-dart/records_issue/record_argument/suspicious_transition.html and https://yanok.github.io/tree-sitter-dart/records_issue/record_in_list/suspicious_transition.html for the two other cases, but they are mostly the same).

Look, there is a `recordField` branch (version 6), the one that would eventually bring us to the `recordLiteral` and the correct parse. But then `condense` happens and bam, this branch mysteriously disappears.

The other two cases are essentially the same: there is a `recordField` branch, but `condense` removes it.
 

### Steps to reproduce

git clone --depth=1 https://github.com/yanok/tree-sitter-dart
cd tree-sitter-dart
tree-sitter generate
tree-sitter test

### Expected behavior

tree-sitter continues with all versions, eventually getting enough look ahead to resolve the conflict.

Alternatively, terminating `tree-sitter generate` with a message "Your grammar does not satisfy the required property [property]" would also be an option.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.21.0

### Operating system/version

Debian GNU/Linux testing

**Comment by ObserverOfTime** [comment]
"I did what the tree-sitter docs explicitly say not to do and I'm surprised it doesn't work"

**Comment by yanok** [comment]
> "I did what the tree-sitter docs explicitly say not to do and I'm surprised it doesn't work"

Thanks for your helpful comment! It actually works surprisingly well, much better than I expected. Also, tree-sitter does accept the input and does generate the parser, so if the parser doesn't work correctly, that's a bug, regardless of what the input was, don't you think?

**Comment by maxbrunsfeld** [comment]
I think you are hitting a hard-coded limit on how much ambiguity Tree-sitter is willing to tolerate. The limit is there for performance reasons. Tree-sitter's GLR capabilities are designed to be used as an escape hatch, when LR is insufficient for parsing some particularly ambiguous grammar construct, but it's not intended to be used for highly ambiguous grammars like what you've written.

My read on your grammar is that *some* of the ambiguity is inherent in the language that you're modeling (e.g. an ambiguity between types and expressions in some positions), but there is additional ambiguity that is purely an artifact of how you've written the grammar (e.g. `recordTypeFields` vs `recordTypeField`, and `normalFormalParameter` vs `normalFormalParameters`). If you rewrote your grammar to avoid this incidental ambiguity, Tree-sitter would work better for you.

**Comment by yanok** [comment]
@maxbrunsfeld thanks a lot, that explains it! Is that limit documented anywhere? Did I miss it in the docs?

With the new knowledge about this by design limit, I'm convinced that's likely not a bug. Would it be possible to log a warning and/or mark it in the debug output, if the limit is hit during parsing?

Regarding the ambiguities in the grammar, you are totally right, the vast majority of the conflicts should be possible to resolve at the generation phase, by adding precedence and/or refactoring the rules. It's just we are in the early experimentation phase and it was too tempting to simply accept all the conflicts.

I guess it's fine to close this bug as infeasible then.
