### ISSUE TITLE
Node 12 doesn't compile

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#325]
So as I try to prebuild all variations I can, I encountered problems with the new node version.

Luckily someone figured out what to change, but as that's treated as a generated file, I shouldn't change it right?
https://github.com/Razzeee/tree-sitter-elm/pull/4/files

So it would be awesome to get upstream aligned.

More infos https://electronjs.org/blog/nodejs-native-addons-and-electron-5

**Comment by maxbrunsfeld** [comment]
Thanks for the report (and the link to the fix). This is fixed in Tree-sitter CLI version 0.14.7. You'll need to manually delete `binding.cc` and re-run `tree-sitter generate`.

**Comment by achekulaev** [comment]
How I could grab it as npm? It is still 0.14.0 there.

```
§ npm i tree-sitter -g

> tree-sitter@0.14.0 install /usr/local/lib/node_modules/tree-sitter
```

**Comment by maxbrunsfeld** [comment]
If you want to regenerate a parser, use the `tree-sitter-cli` module: `npm i tree-sitter-cli`.

The fix was to update the generator to generate a `binding.cc` file with some updated node APIs.

**Comment by achekulaev** [comment]
I am not sure I follow, right now `npm i tree-sitter` results in an error, that is described in #46, but you say there is no update required to the package so it will remain like this.

**Comment by maxbrunsfeld** [comment]
Oh, you're right. I thought that only the generated parsers were failing to compile. I'll publish a new version of the `tree-sitter` module itself later today.

**Comment by Razzeee** [comment]
which means you will push 0.14.7 of tree-sitter-cli to npm?

**Comment by maxbrunsfeld** [comment]
0.14.7 of `tree-sitter-cli` is already out.

**Comment by Razzeee** [comment]
weird, just started to show on npm, but says uploaded three hours ago.

I already checked 6 hours ago when you tagged the release on github. Seems like npm caching is getting more aggressive.

**Comment by maxbrunsfeld** [comment]
I do sometimes wait a little while between pushing a tag and publishing to npm, because I have to wait for CI to complete so that the CLI binaries are available for download.

**Comment by maxbrunsfeld** [comment]
Sorry @achekulaev, node 12 is turning out to be much more time consuming and painful than I thought. It's really an awful process this time 😬 . I may not have time to complete it for a while, but here is the work-in-progress branch: https://github.com/tree-sitter/node-tree-sitter/pull/45.

**Comment by achekulaev** [comment]
Ouch! Gotcha. Should the issue be re-opened to reflect the status then?

**Comment by maxbrunsfeld** [comment]
Since it's a `node-tree-sitter` issue, I'm gonna leave this closed. You can subscribe to this one though: https://github.com/tree-sitter/node-tree-sitter/issues/46.
