### ISSUE TITLE
Playground should show anonymous nodes

### ISSUE THREAD

**Issue by savetheclocktower** [tree-sitter/tree-sitter#3261]
### Problem

People ask pretty often in Discord about the concept of anonymous nodes. Since the playground doesn't show them alongside named nodes, there's not much visibility around them, and it's easy for an inexperienced Tree-sitter user to think that they just aren't there, or that they can't be queried against.

### Expected behavior

We implemented the playground inside of Pulsar as part of the [tree-sitter-tools](https://web.pulsar-edit.dev/packages/tree-sitter-tools) package, and I solved this by making a toggle:

<p><img width="468" alt="Screenshot 2024-04-05 at 7 23 00 PM" src="https://github.com/tree-sitter/tree-sitter/assets/3450/e5be962a-042a-4d10-b94c-287df8ce77fa"></p>

It could be off by default, but its presence would make it clearer that anonymous nodes aren't absent — they're just hidden from the tree by default.

I'll likely get around to contributing this myself as a PR, but maybe someone else might get to it first.

**Comment by amaanq** [comment]
Was fixed in #4032
