### ISSUE TITLE
Bad error message when an undefined rule is used as the `word` token

### ISSUE THREAD

**Issue by mathieucaroff** [tree-sitter/tree-sitter#328]
```
$ tree-sitter --version
tree-sitter 0.15.1 (a0390218a8fa66ea062bc211baf303b5fbcb0b3e)

$ cat grammar.js
module.exports = grammar({
  name: 'helloworld',

  word: $ => $.i_dont_exist,

  rules: {
    code: $ => "Hello world!\n"
  },
})
```

When `$ tree-sitter generate`, I'm getting the unhelpful error message
```
Undefined symbol `ReferenceError`
```

A very similar issue has already been raised and appears to be solved by `0.14.0-beta3`:

_Originally posted by @drom in https://github.com/tree-sitter/tree-sitter/issues/258#issuecomment-455467616_

**Comment by mathieucaroff** [comment]
The problem does not seem to happen when the error is made among the rules. With the below `grammar.js`, `tree-sitter generate` prints a helpful error message as expected.
```
$ cat grammar.js
module.exports = grammar({
  name: 'helloworld',

  rules: {
    code: $ => $.i_dont_exist,
  },
})
```

**Comment by maxbrunsfeld** [comment]
Thanks for the detailed report!

**Comment by amaanq** [comment]
Just fixed this now, thank you

**Comment by Jakobeha** [comment]
I believe this also happens if an undefined rule is used in `supertypes`.

**Comment by amaanq** [comment]
thanks, I've fixed this, but please in the future open a new issue that refers back to this one instead of necroposting so other people don't get unnecessary notifications.
