### ISSUE TITLE
`failed to rename wasm output file` on different Drive letter

### ISSUE THREAD

**Issue by RedCMD** [tree-sitter/tree-sitter#3281]
### Problem

Error is shown when attempting to build a wasm on a different drive letter than `tree-sitter-cli`

![image](https://github.com/tree-sitter/tree-sitter/assets/33529441/187bfd30-c27b-4fbb-8e7c-3c8f6bdf368a)
```
failed to rename wasm output file

Caused by:
    The system cannot move the file to a different disk drive. (os error 17)
```

(the wasm does build and runs perfectly fine)

old `tree-sitter-cli` version `0.20.8` worked correctly

### Steps to reproduce

install `tree-sitter-cli` on one drive (`C:`)
attempt to build the wasm on another driver (`D:`)
`tree-sitter build --wasm`
(latest emscripten)

### Expected behavior

wasm builds with no error

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.2 (fc15f621334a262039ffaded5937e2844f88da61)

### Operating system/version

Windows 11

**Comment by amaanq** [comment]
do you mind trying out master to see if that fixes it? (namely #3203)

**Comment by RedCMD** [comment]
can confirm its fixed (within the last 10 commits)

**Comment by amaanq** [comment]
nice, next release will be soon
