### ISSUE TITLE
Difference between tree-sitter playground and cursor.matches

### ISSUE THREAD

**Issue by Bennet-Sunder** [tree-sitter/tree-sitter#3319]
### Problem

I tried the following tree-sitter query in playground and it didn't show that the given code matched. 
<img width="1728" alt="image" src="https://github.com/tree-sitter/tree-sitter/assets/55491132/acfd2203-5c0f-41fc-a5d3-7730344d2891">

So I put this in my library and it actually found a match surprisingly.

### Steps to reproduce

[dependencies]
tree-sitter = "0.20.6"
tree-sitter-ruby = "0.20.1"

```
use tree_sitter::{Parser, Query, QueryCursor};

fn main() {
    let mut parser = Parser::new();
    let language = tree_sitter_ruby::language();
    parser.set_language(language).unwrap();
    let query = r#"
    (
        (method
        name: (identifier) @method_definition
        body: (body_statement 
          . ((return (argument_list)? @_arglist)) .
        ))
        (#not-match? @_arglist ".")
    )
  "#;
    let query = Query::new(language, query).unwrap();
    let source_code = "
        def try_sample_method(account, expiry_date, additional_args = {})
            just_a_method_call
            return
        end
    ";
    let tree = parser.parse(source_code, None).unwrap();
    let mut binding = QueryCursor::new();
    let query_matches = binding.matches(&query, tree.root_node(), source_code.as_bytes());
    for query_match in query_matches.into_iter() {
        if let Some(captured_node) = query_match.captures.first() {
            println!("captured node {}", captured_node.node.utf8_text(&source_code.as_bytes()).unwrap().to_string());
          } else {
            println!("No captured node");
        }
    }
    println!("Done")

}
```

This code returns this. 

```
captured node try_sample_method
Done
```

### Expected behavior

Can you help me understand why this shows a match while the playground doesn't. 

Although when I updated the tree-sitter-query to this

```
    (
        (method
        name: (identifier) @method_definition
        body: (body_statement 
          . (return (argument_list)? @_arglist) .
        ))
        (#not-match? @_arglist ".")
    )
```

This is working as expected that the method doesn't match as `return` isn't the sibling node. 

### Tree-sitter version (tree-sitter --version)

tree-sitter = "0.20.6"

### Operating system/version

macOS 14.3.1 (23D60)

**Comment by WillLillis** [comment]
Testing with `tree-sitter` 0.22.5 shows no captures, matching the behavior of the playground. I did have to depend on a local clone of `tree-sitter-ruby` with its `tree-sitter` dependency bumped to get the program to compile, though.

![image](https://github.com/tree-sitter/tree-sitter/assets/87077023/bc52333c-c7ba-4eb8-b194-061d34757081)

**Comment by ObserverOfTime** [comment]
Yeah, I'd say this is the expected behaviour.
