### ISSUE TITLE
centralized "version" number in config

### ISSUE THREAD

**Issue by kylegoetz** [tree-sitter/tree-sitter#3320]
### Problem

Currently, the Python, C(++?), and JavaScript build processes have grammar version numbers independent of each other. This is brittle, as it requires the same (semantic) value to be changed in three different places for consistency.

### Expected behavior

We need some centralized config file to hold this version (I propose they just all pull from `package.json`'s version property).

**Comment by ObserverOfTime** [comment]
Not possible. But the CLI will have a command that bumps all of them.
