### ISSUE TITLE
Alias not queriable

### ISSUE THREAD

**Issue by JoranHonig** [tree-sitter/tree-sitter#3331]
### Problem

I've defined an alias here: https://github.com/JoranHonig/tree-sitter-solidity/blob/master/grammar.js#L791

I'd expect to be able to query for binary_operator nodes as such:

```
  (binary_operator) @operator
```

### Steps to reproduce

git clone git@github.com:JoranHonig/tree-sitter-solidity.git
tree-sitter generate

cat "  (binary_operator) @operator" > example.scm
touch sample.sol
tree-sitter-query example.scm sample.sol

### Expected behavior

No query error 

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.4

### Operating system/version

=

**Comment by amaanq** [comment]
might be similar to #2641, don't remember exactly

**Comment by maxbrunsfeld** [comment]
thanks for the report; I thought this was handled

**Comment by amaanq** [comment]
your parser.c code is not up to date, that's the issue. it is currently using `binaryOperator` - see the diff of me generating using 0.20.6:

<img width="547" alt="Screenshot 2024-05-15 at 3 58 06 PM" src="https://github.com/tree-sitter/tree-sitter/assets/29718261/39f902b8-e620-479c-9055-047d9c4f8932">
