### ISSUE TITLE
How to package for electron

### ISSUE THREAD

**Issue by georgewfraser** [tree-sitter/tree-sitter#335]
I've written a VSCode extension that replaces the native syntax highlighting with tree-sitter: 

https://github.com/georgewfraser/vscode-tree-sitter

It works by replacing the builtin textmate grammars with simplified grammars that just color basic literals and keywords, and then running tree-sitter in the extension to add color to the tricky parts, like fields and functions. The results are excellent, and it will allow VSCode users to benefit from this great technology.

However, I am struggling with packaging the native tree-sitter modules with the extension. [electron-rebuild](https://github.com/electron/electron-rebuild) works for my Mac, but when windows and linux users try to use my extension the native modules fail to load (https://github.com/georgewfraser/vscode-tree-sitter/issues/3).

You've obviously figured out how to deploy this as part of Atom---can you give any guidance on the right technique to package tree-sitter and the grammars in a VSCode extension?

**Comment by maxbrunsfeld** [comment]
How are people installing the module currently, just with `npm`? If so, then they wood need to rebuild it using something like electron-rebuild. That should work fine on all platforms; I'm guessing some users don't know that they need to do it?

**Comment by maxbrunsfeld** [comment]
In Atom, there's a command line tool `apm` that wraps `npm` and builds native modules against the correct version of Electron by setting [some environment variables for npm](https://electronjs.org/docs/tutorial/using-native-node-modules#using-npm). We use this when we build the app itself, and users also use it to install third-party packages.

I'm not sure how package installation works for vscode, and if it provides any assistance in dealing with native modules.

**Comment by georgewfraser** [comment]
Unfortunately, VSCode requires everything to be prebuilt. It seems to me there's two options:

1. Build for each platform VSCode supports, similar to how you've [built a matrix](https://github.com/tree-sitter/tree-sitter/releases) for this repository. Then, select the correct binary at runtime.
2. Use WebAssembly.

Do you have a sense of which of these is likely to be easier/produce better results?

**Comment by georgewfraser** [comment]
I think I have solved this by building the extension on Mac, Linux, and Windows using Azure pipelines: 

https://github.com/georgewfraser/vscode-tree-sitter/blob/9fefcada466bb73a0ce39c2ab0299f224b62aa9e/azure-pipelines.yml

VSCode is apparently going to add support in June for distributing different builds of an extension for different platforms https://github.com/microsoft/vscode/issues/23251

So I think I've got a good plan here.

**Comment by lnicola** [comment]
@georgewfraser 

> WINDOWS AND LINUX USERS: Please download the appropriate .vsix file from here and install manually until https://github.com/microsoft/vscode/issues/23251 is complete.

Your download link is broken (points to the same issue).

I think other extensions ship all binaries and choose which one to use at run-time. Does that approach not work for you?

**Comment by georgewfraser** [comment]
@lnicola Whoops, thanks! I have fixed the link.

I don't know how to select a different binary at runtime. If VSCode is going to implement platform-specific extensions in a few weeks, I think I'll just wait for that, it seems like the "right way".
