### ISSUE TITLE
Split tree_sitter_cli::generate off into its own crate

### ISSUE THREAD

**Issue by taktoa** [tree-sitter/tree-sitter#3357]
### Problem

The tree-sitter-cli `generate` module is useful for tools like `rust-sitter`, but because it is part of tree-sitter-cli, it brings along lots of unnecessary dependencies like `webbrowser`.

### Expected behavior

It would be nice if there was a tree-sitter-generate package with more minimal dependencies.

**Comment by shadaj** [comment]
Oh, rust-sitter creator here! Was just about to open an issue for this; indeed it would be nice to have the core parser generator in a crate with fewer dependencies.

**Comment by WillLillis** [comment]
I think #3358 addressed this, but it [won't be revived until after the 0.24.0 release](https://github.com/tree-sitter/tree-sitter/pull/3358#issuecomment-2243458860).
