### ISSUE TITLE
Support negative/error syntax corpus tests

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/tree-sitter#3366]
### Problem

My understanding is that the location of error nodes in the parse tree is fairly unstable and can change over time as error recovery improves. It would be nice to have a type of corpus test that simply indicates a parse error of some kind occurs somewhere, so we can add tests for syntax that should be rejected and not have to worry about that test breaking in the future.

### Expected behavior

Instead of an expected S-expression in the corpus test, there should simply be a keyword like ERROR or INVALID. This indicates to the testing program that the test should succeed if `tree.root_node().has_error()` is true, and fail otherwise.

**Comment by amaanq** [comment]
the [`:error` attribute](https://tree-sitter.github.io/tree-sitter/creating-parsers) (scroll down a bit to attributes) is what you're looking for probably, see here for usage in a [grammar](https://github.com/tree-sitter-grammars/tree-sitter-xml/blob/master/test/corpus/errors.txt)

**Comment by ahelwer** [comment]
Thanks!!!

**Comment by sogaiu** [comment]
Nice feature :+1: 

I added [a question along with discussion](https://github.com/sogaiu/ts-questions/blob/master/questions/how-to-test-for-an-expected-error/README.md) to ts-questions referencing this issue.

---

Minor remark - the attributes section can be linked to directly like [this](https://tree-sitter.github.io/tree-sitter/creating-parsers#attributes).
