### ISSUE TITLE
rust api: recursivly print tree via Debug trait if alternate flag is set

### ISSUE THREAD

**Issue by lolbinarycat** [tree-sitter/tree-sitter#3367]
### Problem

the Debug trait only shows the root node of a tree, which is frequently unhelpful.

### Expected behavior

when printing `Tree` or `Node` with `{:#?}`, the implementation of Debug would recurse into child nodes and print the full AST.  this would allow easier debugging.

**Comment by ObserverOfTime** [comment]
Debug printing a node does recursively print the S-exp.

**Comment by lolbinarycat** [comment]
do you mean printing with Display? i didn't check that, but it seems unintuitive that using Debug would give less info than Display.

**Comment by lolbinarycat** [comment]
hmm.. i feel like i would want to use newlines and indentation to align things honestly... also it should print field names ideally.

**Comment by ObserverOfTime** [comment]
Well, you can submit a PR if you want. Maybe make it tree-like.

**Comment by lolbinarycat** [comment]
what about also making the alternate form of Display print in an indented way?

**Comment by ObserverOfTime** [comment]
Already done.
