### ISSUE TITLE
zig no longer works for builds in main branch of nvim-treesitter 

### ISSUE THREAD

**Issue by WillEhrendreich** [tree-sitter/tree-sitter#3368]
### Problem

In the main branch of nvim-treesitter the build is defaulting to treesitter build. It used to build via the detected c compiler from the env variable, but that's no longer going to be happening. Treesitter build also looks for that variable, but for whatever reason isn't calling zig correctly. It complains of '-02' not being recognized. 

### Steps to reproduce

Treesitter build with zig as cc

### Expected behavior

Compilation 

### Tree-sitter version (tree-sitter --version)

0.22.*

### Operating system/version

Windows 11

**Comment by ObserverOfTime** [comment]
Looks like zig can't work because its targets are non-standard. See https://github.com/rust-lang/cc-rs/issues/897 and https://github.com/ziglang/zig/issues/4911.

**Comment by WillEhrendreich** [comment]
This is officially past my level of c language compiler voodoo for sure.
