### ISSUE TITLE
Playground in offline mode

### ISSUE THREAD

**Issue by songhtdo** [tree-sitter/tree-sitter#3370]
### Problem

Thank you for providing a very useful tool.
I am on a new computer and experiencing a network outage. I am unable to use the playground function properly and will display an error message in the browser console.

The error message displayed in the browser's console is as follows:
![image](https://github.com/tree-sitter/tree-sitter/assets/22132121/6090ba15-4cd4-4892-ae12-64e038d80ef4)

Possible reason: In pages generated by tree sitter cli control, access to some network resources is required.

### Expected behavior

I hope to be able to use the tree sit playground feature in a completely offline state.
Thank you.

**Comment by Tc69Cabusog** [comment]
Icant log in

**Comment by Tc69Cabusog** [comment]
Who control my accounts?

**Comment by amaanq** [comment]
clone the repo, run `./script/build-wasm`, then run `cargo install --path cli` and it'll bundle in the locally built tree-sitter.js/wasm files, as for the others, I have no clue, I don't get what you're asking exactly

**Comment by songhtdo** [comment]
@amaanq 
Hello, thank you very much for your attention and reply.

Maybe I didn't express myself clearly, let me describe it again.
Normally, our computer will be connected to the Internet, and we can access tree-siter.github.io/tree-sitter/playground through the browser to test some syntax. Alternatively, test it locally through tree-sitter playground.
But in some cases, computers are completely separated from the Internet environment and physically isolated. At this point, to test some syntax with playground, I need to use the local tree sit playground command.

To run the tree-sitter program locally, I need to start from the https://cdnjs.cloudflare.com The website downloads some js/css files. This step is unsuccessful when the Internet cannot be accessed. cause http://127.0.0.1:8000 The page is not working properly.

I would like to ask if there is a way to solve this problem.
Thank you again.

**Comment by sogaiu** [comment]
I tested `tree-sitter playground` while disconnected from networks and at least for my setup, the result was not usable:

![tree-sitter-playground-offline-in-firefox](https://github.com/tree-sitter/tree-sitter/assets/33044872/4cc343c2-77b6-42bf-bee2-32fcc0912dc2)

After I re-established a network connection and reloaded, things started working:

![tree-sitter-playground-online-in-firefox](https://github.com/tree-sitter/tree-sitter/assets/33044872/fbc73ca4-a154-4496-8669-ad0ad9d287e2)

IIUC, the former of the two results is what is being described.

**Comment by songhtdo** [comment]
This issue has been resolved.
I have developed a small local application by combining the tree sitter and csharp tree sitter projects. You can skip using tree -sitter playground anymore.

The project source code has been uploaded to the GitHub project: [tree-sitter-play](https://github.com/songhtdo/tree-sitter-play.git)

The project screenshot is as follows:
![image](https://github.com/tree-sitter/tree-sitter/assets/22132121/b117c6ee-fb7f-4246-953d-f491126ac695)
