### ISSUE TITLE
Feat(query): include group + individual token 

### ISSUE THREAD

**Issue by ilan-schemoul** [tree-sitter/tree-sitter#3371]
### Problem

I want to select
"struct abc {
  int a;
   };"
struct_specifier in c does not include semicolon
I do not know if it's a bug or I don't know how to use the app or a feature lacks but :
((struct_specifier (_)) ";") @c
@c is not the struct with ";" but is the struct without semicolon
(struct_specifier (_) ";") @c gives error impossible pattern

### Expected behavior

((struct_specifier (_)) ";") @c to select struct with semicolo or something similar

**Comment by amaanq** [comment]
belongs in tree-sitter-c, but you can just do this

```
(translation_unit
  (struct_specifier (_))
  .
  ";") @c
```
