### ISSUE TITLE
Loading wasm language within a node environment fails on Windows

### ISSUE THREAD

**Issue by OriginalDecode** [tree-sitter/tree-sitter#338]
https://github.com/tree-sitter/tree-sitter/blob/ae41a78d3c074e8bb0f05bc96d61c5f3a88b37e6/lib/binding_web/binding.js#L571

```require('url').parse('c:/test').protocol``` returns c: which makes it go into the fetch path which doesn't work in a node environment. 
This is a windows specific issue since if you'd add / before c: it would result into null, but that would result into an invalid path on windows which still would fail.

**Comment by maxbrunsfeld** [comment]
🤦‍♂ Thanks for the report. That's probably the 3rd or 4th time that this problem of windows paths vs URLs has come up in my career.

**Comment by georgewfraser** [comment]
Are you going to publish a new version? I think this is breaking https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-tree-sitter

**Comment by maxbrunsfeld** [comment]
Yes! Sorry for the delay over the long weekend. This is published in [v0.15.3](https://www.npmjs.com/package/web-tree-sitter/v/0.15.3).
