### ISSUE TITLE
'tree-sitter parse the-file' throws error following tutorial "The system cannot find the file specified (os error 2)"

### ISSUE THREAD

**Issue by charliewynn** [tree-sitter/tree-sitter#339]
I'm having trouble getting through the [creating parsers tutorial](https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-3-creating-parsers.md).

`tree-sitter generate` works and creates the `/src` folder and `binding.gyp`

but trying to run
`tree-sitter parse the-file` gives me 
`The system cannot find the file specified (os error 2)`

This is on windows with visual studio 2017 installed if that matters.
I am able to get through this part of the tutorial on a macbook as expected.

I expect this is an error on my end, or some weird setup I have - but I can't figure out any more info around the error to know where to start.

**Comment by maxbrunsfeld** [comment]
Just checking - did you create a file called `the-file`?

**Comment by charliewynn** [comment]
![image](https://user-images.githubusercontent.com/2472894/58286093-9f5e9e00-7d73-11e9-84f7-ef78439dab02.png)

Yep!

**Comment by paulyoung** [comment]
I'm experiencing something similar on macOS with 0.14.7 except that instead of an error the `parse` and `test` commands both say "No language found".

**Comment by paulyoung** [comment]
Same thing with 0.15.1

**Comment by paulyoung** [comment]
In my case I needed to add a `package.json`:

```
{
  "private": true,
  "name": "tree-sitter-mylang"
}
```

The tutorial mentions this, but perhaps the error message could be improved?

**Comment by charliewynn** [comment]
No luck with `"private": true`
![image](https://user-images.githubusercontent.com/2472894/58564934-7f0b6500-81f3-11e9-9f85-fcf79ca9a233.png)

**Comment by maxbrunsfeld** [comment]
The new version of the CLI, 0.15.2 has more context in a lot of the error messages. Hopefully this will help us figure out what the problem is.

**Comment by charliewynn** [comment]
Unfortunately I get the same error with the newer CLI.
One strange thing I notice is that `tree-sitter -V` gives 15.1 despite installing @latest in a clean package
![image](https://user-images.githubusercontent.com/2472894/58724056-41e4d580-83a1-11e9-9169-6e04708b4a95.png)

**Comment by maxbrunsfeld** [comment]
>  tree-sitter -V gives 15.1

Yeah, it looks like npm just served you an old version. Caching maybe?

**Comment by charliewynn** [comment]
I think it might be something in the tree-sitter.exe. If I look in `/node_modules/tree-sitter-cli/package.json` I have `"version": "0.15.2"` but I still get 15.1 when I check the --version

**Comment by maxbrunsfeld** [comment]
Hmm, I can't reproduce that on my windows VM:

```
npm install tree-sitter-cli@latest
.\node_modules\.bin\tree-sitter --version
tree-sitter 0.15.2 (85877a1def714ed2c7c1300cef72ca6612248998)
```

What if you reinstall?

**Comment by charliewynn** [comment]
Strange, if I run it out of .bin I get 0.15.2.  If I run it out of the root of a fresh install I get 0.15.1

![image](https://user-images.githubusercontent.com/2472894/58727628-7b6e0e80-83aa-11e9-83cc-545fb9bea225.png)

**Comment by maxbrunsfeld** [comment]
I think that means that you have `0.15.1` somewhere else on your PATH. Maybe at some point you installed it with `npm install -g`? In any case, are the error messages any better? 🙏

**Comment by charliewynn** [comment]
I had an instance of 15.1 in my path from another install.
Removing that did give me the better error messages which did help me figure out it was the cpp compiler file not being found. Not my `the-file` file.

I think because I had vs2017 setup for c# I assumed I had the compiler stuff set up correctly.

Thanks so much for the help!

**Comment by maxbrunsfeld** [comment]
Oh, that's great to hear. Thanks!
