### ISSUE TITLE
Support nostd

### ISSUE THREAD

**Issue by cathaysia** [tree-sitter/tree-sitter#3391]
### Problem

Have you considered adding support for nostd? Or will similar PRs be allowed to be merged?

**Comment by amaanq** [comment]
no_std where? the lib? the cli? and why, what's the use case/benefit exactly?

**Comment by cathaysia** [comment]
no_std for the tree-sitter rust lib. This makes no_std environment can using tree-sitter parse text.

I use tree-sitter to parse grammar in my recent project. But my project runs on bare metal, if tree-sitter (rust) supports no_std, then tree-sitter can run in a wider range of environments.
Currently in my private fork, I have successfully compiled the into the no_std environment after make query-related code as a feature. So I think this work should be relatively simple.

**Comment by cathaysia** [comment]
In fact, the main blocker for no_std is the regex library referenced by the tree-sitter query.

**Comment by ObserverOfTime** [comment]
PR welcome if you make nostd an optional feature instead of the other way around.
You likely just need to disable the `#match?` predicates, rather than the entire query code.

**Comment by cathaysia** [comment]
I don't quite understand the difference between them. But I'll open a simple PR later to describe my thoughts. Please and welcome to comment it. :)
