### ISSUE TITLE
Assertion Failed on Terraform Files

### ISSUE THREAD

**Issue by la0bing** [tree-sitter/tree-sitter#3406]
### Problem

I am getting the following error when trying to navigate in the nvim editor, on a terraform file, either typing or basic operation throws this and returns me back to the shell:
```Assertion failed: (length <= TREE_SITTER_SERIALIZATION_BUFFER_SIZE), function ts_parser__external_scanner_serialize, file parser.c, line 404```

### Steps to reproduce

My configuration is just using the default AstroNVim installation.
```
git clone --depth 1 https://github.com/AstroNvim/template ~/.config/nvim
rm -rf ~/.config/nvim/.git
nvim
```
and from here on when i try editing a terraform file it just randomly starts crashing. I've tried using different distros of vim but seems to be still facing the same issue.

### Expected behavior

It should not crash.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.6

### Operating system/version

macOS 14.5

**Comment by amaanq** [comment]
that is a bug in *that* parser's scanner, please file an issue there with a reproducer.

**Comment by samuel-form3** [comment]
I was able to replicate this, happens sometimes.
