### ISSUE TITLE
[Language Request] Lua

### ISSUE THREAD

**Issue by Stanzilla** [tree-sitter/tree-sitter#341]
I have no real experience with this, but would it be possible to craft Lua support from an existing project like oxyc/luaparse?

**Comment by Arcanemagus** [comment]
You could potentially use it as a reference, but generally the language itself will have a better reference to use while building the grammar. If you mean could that be used _directly_, the answer is no, as even a grammar system that has the same style of parser would need some translation to be used as a Tree-sitter grammar.

If you were interested in creating a Lua grammar the documentation on getting started can be found here: [Creating Parsers](http://tree-sitter.github.io/tree-sitter/creating-parsers)

There also seem to be at least two other projects that started a Lua grammar, I would look there if you were simply looking for one to use:
* [Azganoth/tree-sitter-lua](https://github.com/Azganoth/tree-sitter-lua)
* [Reisz/tree-sitter-lua](https://github.com/Reisz/tree-sitter-lua)

**Comment by maxbrunsfeld** [comment]
Yeah, maybe we should just add Azganoth/tree-sitter-lua to the list; that one looks quite complete.

**Comment by maxbrunsfeld** [comment]
I added a link to [Azganoth's Lua grammar](https://github.com/Azganoth/tree-sitter-lua) in the docs.
