### ISSUE TITLE
Assertion `length <= TREE_SITTER_SERIALIZATION_BUFFER_SIZE' failed

### ISSUE THREAD

**Issue by reymondzzzz** [tree-sitter/tree-sitter#3416]
### Problem

Hi!

File https://github.com/WebVella/WebVella-ERP/blob/master/WebVella.Erp.Plugins.SDK/Services/CodeGenService.cs on the v0.20.9 parsed correctly, but in new versions(master, v0.22.6) broken

### Steps to reproduce

git clone https://github.com/tree-sitter/tree-sitter-c-sharp
tree-sitter playground
copy source from https://github.com/WebVella/WebVella-ERP/blob/master/WebVella.Erp.Plugins.SDK/Services/CodeGenService.cs
blank screen

### Expected behavior

see tree

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.6

### Operating system/version

any

**Comment by reymondzzzz** [comment]
Any progress?

**Comment by WillLillis** [comment]
Seems to be a problem with tree-sitter-c-sharp's external scanner. It looks like the [size check](https://github.com/tree-sitter/tree-sitter-c-sharp/blob/82fa8f05f41a33e9bc830f85d74a9548f0291738/src/scanner.c#L65) in `tree_sitter_c_sharp_external_scanner_serialize` doesn't take into account the possible modifications to `size` before entering the loop:

```c
unsigned tree_sitter_c_sharp_external_scanner_serialize(void *payload, char *buffer) {
    Scanner *scanner = (Scanner *)payload;

    if (scanner->interpolation_stack.size * 4 > TREE_SITTER_SERIALIZATION_BUFFER_SIZE) {
        return 0;
    }

    unsigned size = 0;

    buffer[size++] = (char)scanner->quote_count;
    buffer[size++] = (char)scanner->interpolation_stack.size;

    for (unsigned i = 0; i < scanner->interpolation_stack.size; i++) {
        Interpolation interpolation = scanner->interpolation_stack.contents[i];
        buffer[size++] = (char)interpolation.dollar_count;
        buffer[size++] = (char)interpolation.open_brace_count;
        buffer[size++] = (char)interpolation.quote_count;
        buffer[size++] = (char)interpolation.string_type;
    }

    return size;
}
```

Adding a `+2` to the check against `TREE_SITTER_SERIALIZATION_BUFFER_SIZE` seems to alleviate the issue. I'll open up a PR with the fix, but I'm not familiar with the project so I still may be missing something.
