### ISSUE TITLE
[Feature] hope to be able to replace or modify a specific Node.

### ISSUE THREAD

**Issue by songhtdo** [tree-sitter/tree-sitter#3419]
### Problem

Hello, thank you very much for providing a great library.
However, during my specific use, I found that there were occasional parsing errors, especially when parsing C++ due to the complexity of the syntax, which can easily lead to some inconsistencies with expectations.
This kind of problem usually occurs in a complex grammatical structure, and if the problematic node content is parsed separately, it is correct.

### Expected behavior

I hope you can provide a function that allows manual replacement of specific Node nodes. This method is equivalent to patching specific error results, which is easier to implement than directly modifying the language's grammar.js requirements.
Through the analysis of this patch method, it will be cleaner than the later conversion process.

**Comment by jeff-hykin** [comment]
You might want to look into this [discussion here](https://github.com/tree-sitter/tree-sitter/discussions/2553#discussioncomment-7296041)

They pretty much say, no but it is a feature that can be built on top of the tree-sitter

**Comment by amaanq** [comment]
Tree-sitter isn't designed to be able to replace nodes or merge trees, it doesn't really make a lot of sense and the use case is pretty limited when it comes to what the library is meant to be used for, however, as mentioned, you *can* build this functionality **on top of** tree-sitter.
