### ISSUE TITLE
Where can I see all node types?

### ISSUE THREAD

**Issue by yikengboy** [tree-sitter/tree-sitter#3420]
### Expected behavior

I want get all node tpye? Like
decimal_integer_literal
arithmetic_operator
line_comment
field_access
inferred_parameters
condition
logical_operator
constant_declaration
element_value_pair
import_statement
import
import_clause
named_imports

There is such an enumeration that can see all types？

**Comment by ObserverOfTime** [comment]
The node types change depending on the grammar.

**Comment by amaanq** [comment]
`src/node-types.json` has this info

**Comment by yikengboy** [comment]
thanks
