### ISSUE TITLE
Replace `sprintf()` with `snprintf()`

### ISSUE THREAD

**Issue by DavisVaughan** [tree-sitter/tree-sitter#3426]
### Problem

I noticed that you use `sprintf()` in one place for the logger, but the slightly safer `snprintf()` in a different place. Would it be possible to consistently use `snprintf()`?

https://github.com/tree-sitter/tree-sitter/blob/3da7deedd8e0a3decd2db32b76ea51513876914e/lib/src/parser.c#L26-L36

CRAN (for R packages) grumbles about the fact that `sprintf()` is used, since it "is not safe", requiring a manual patch on my end.

### Steps to reproduce

NA

### Expected behavior

Use `snprintf()` instead

### Tree-sitter version (tree-sitter --version)

main

### Operating system/version

macOS 13.6.5

**Comment by ObserverOfTime** [comment]
PR welcome.
