### ISSUE TITLE
Failure to parse a function as a function in C

### ISSUE THREAD

**Issue by igm503** [tree-sitter/tree-sitter#3437]
### Problem

I've been using tree-sitter to parse c source code, and have encountered a function definition that tree-sitter fails to parse as a "function_definition" type node. 

### Steps to reproduce

I'm using the tree_sitter_languages python package (source here: https://github.com/grantjenks/py-tree-sitter-languages)

[~/]$ python3      
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tree_sitter_languages import get_parser
>>> parser = get_parser("c")
>>> code = """static __printf(2, 3) int tipc_tlv_sprintf(struct sk_buff *skb,
...           const char *fmt, ...)
... {
...   int n;
...   u16 len;
...   u32 rem;
...   char *buf;
...   struct tlv_desc *tlv;
...   va_list args;
... 
...   rem = tipc_skb_tailroom(skb);
...   tlv = (struct tlv_desc *)skb->data;
...   len = TLV_GET_LEN(tlv);
...   buf = TLV_DATA(tlv) + len;
...   va_start(args, fmt);
...   n = vscnprintf(buf, rem, fmt, args);
... 
...   va_end(args);
...   TLV_SET_LEN(tlv, n + len);
...   skb_put(skb, n);
...   return n;
... }
... """
>>> tree = parser.parse(bytes(code, "utf-8"))
>>> for node in tree.root_node.children:
...     print(node)
... 
<Node type=declaration, start_point=(0, 0), end_point=(3, 8)>
<Node type=declaration, start_point=(4, 2), end_point=(4, 10)>
<Node type=declaration, start_point=(5, 2), end_point=(5, 10)>
<Node type=declaration, start_point=(6, 2), end_point=(6, 12)>
<Node type=declaration, start_point=(7, 2), end_point=(7, 23)>
<Node type=declaration, start_point=(8, 2), end_point=(8, 15)>
<Node type=expression_statement, start_point=(10, 2), end_point=(10, 31)>
<Node type=expression_statement, start_point=(11, 2), end_point=(11, 37)>
<Node type=expression_statement, start_point=(12, 2), end_point=(12, 25)>
<Node type=expression_statement, start_point=(13, 2), end_point=(13, 28)>
<Node type=expression_statement, start_point=(14, 2), end_point=(14, 22)>
<Node type=expression_statement, start_point=(15, 2), end_point=(15, 38)>
<Node type=expression_statement, start_point=(17, 2), end_point=(17, 15)>
<Node type=expression_statement, start_point=(18, 2), end_point=(18, 28)>
<Node type=expression_statement, start_point=(19, 2), end_point=(19, 18)>
<Node type=return_statement, start_point=(20, 2), end_point=(20, 11)>
<Node type=ERROR, start_point=(21, 0), end_point=(21, 1)>

### Expected behavior

The same code as above, but with a change in the first line, produces the expected behavior:

[~/]$ python3      
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tree_sitter_languages import get_parser
>>> parser = get_parser("c")
>>> code = """static int tipc_tlv_sprintf(struct sk_buff *skb,
...           const char *fmt, ...)
... {
...   int n;
...   u16 len;
...   u32 rem;
...   char *buf;
...   struct tlv_desc *tlv;
...   va_list args;
... 
...   rem = tipc_skb_tailroom(skb);
...   tlv = (struct tlv_desc *)skb->data;
...   len = TLV_GET_LEN(tlv);
...   buf = TLV_DATA(tlv) + len;
...   va_start(args, fmt);
...   n = vscnprintf(buf, rem, fmt, args);
... 
...   va_end(args);
...   TLV_SET_LEN(tlv, n + len);
...   skb_put(skb, n);
...   return n;
... }"""
>>> tree = parser.parse(bytes(code, "utf-8"))
>>> for node in tree.root_node.children:
...     print(node)
... 
<Node type=function_definition, start_point=(0, 0), end_point=(21, 1)>

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.20.4

### Operating system/version

macOS

**Comment by sogaiu** [comment]
Is it possible this is an issue with the [tree-sitter grammar for C](https://github.com/tree-sitter/tree-sitter-c)?

**Comment by ObserverOfTime** [comment]
For one, tree-sitter-languages is outdated. Install the tree-sitter-c package and if it still fails, submit an issue there.
