### ISSUE TITLE
Release and publish to npm?

### ISSUE THREAD

**Issue by paulyoung** [tree-sitter/tree-sitter#344]
There are changes since the last release that I'd like to depend on but it would be much easier if I could use the release binaries and npm. Thanks in advance 🙇

**Comment by paulyoung** [comment]
It turns out `web-tree-sitter` was already published to npm as `0.15.3` a day ago. A corresponding 0.15.3 GitHub release would be much appreciated 🙏

**Comment by paulyoung** [comment]
Actually, that version doesn't include the TypeScript definitions, so a 0.15.4 release would be great 👌

**Comment by paulyoung** [comment]
FWIW, I'm seeing `Error: "abort({}). Build with -s ASSERTIONS=1 for more info."` when using the latest release of `tree-sitter.js`, so that might be worth including too.

**Comment by maxbrunsfeld** [comment]
Sorry for the delay there. [Tree-sitter-cli 0.15.2](https://www.npmjs.com/package/tree-sitter-cli/v/0.15.2) is out.

**Comment by paulyoung** [comment]
Thank you!

**Comment by paulyoung** [comment]
Could we also get a version published to npm that includes the TypeScript definitions? Thanks again.

**Comment by maxbrunsfeld** [comment]
Published `web-tree-sitter@0.15.4`.

**Comment by paulyoung** [comment]
It appears that the TypeScript definitions are missing from that release too. I think perhaps the `.npmignore` needs to be updated.

**Comment by maxbrunsfeld** [comment]
Oh, ha. Doing that now.
