### ISSUE TITLE
Unable to query using tree-sitter-cli

### ISSUE THREAD

**Issue by pramatias** [tree-sitter/tree-sitter#3441]
### Problem

Hello, i was using tree-sitter-org [1] from the command line. It generated the AST fine, and i ran some queries with no problem.   

I decide to install the Rust grammar [2] and make some queries there. It parses the file correctly and generate the AST, but I cannot make any queries, it just outputs the name of the file.    

Then i `cargo uninstall tree-sitter-cli`, and try downloading and using some previous releases with no luck. I rebuilt the parser for each release, nothing works.

So i `cargo install tree-sitter-cli` again, and now i cannot make any queries to the org grammar which worked previously, neither to Rust grammar.

The query i used for the Rust grammar, is a very simple one (i try it out in the playground first), i put:  `((expression_statement) @a)` in an scm file, and run `tree-sitter query -q query.scm test.rs` . 

When there is an error to the query, the cli outputs the error, when it is correct it outputs just the filename and nothing else. The same is true for the org grammar. 

Also in either grammar it fails to build the wasm: `tree-sitter build --wasm`, although i do not care about wasm or the playground too much. It complains about not finding docker on PATH, which it is on PATH.  

In the Rust grammar, the commands `tree-sitter (build | generate | parse | test )` work fine. In the Org grammar everything is the same, except the test doesn't output something, it probably doesn't have tests.  

I tried in two Ubuntu OSes 22.04 and 23.04 with the same results, it doesn't run queries, and it doesn't build wasm. 

`$ tree-sitter dump-languages
scope: source.rust
parser: "/home/emporas/tree-sitter-src/tree-sitter-rust/"
highlights: Some(["queries/highlights.scm"])
file_types: ["rs"]
content_regex: None
injection_regex: Some(Regex("rust"))

scope: source.org
parser: "/home/emporas/tree-sitter-src/tree-sitter-org/"
highlights: None
file_types: []
content_regex: None
injection_regex: Some(Regex("^org$"))`

`$ docker -v`
Docker version 27.0.2, build 912c1dd

[1] https://github.com/milisims/tree-sitter-org
[2] https://github.com/tree-sitter/tree-sitter-rust

### Steps to reproduce

`$ git clone https://github.com/milisims/tree-sitter-org`
`$ z tree-sitter-org/`
`$ tree-sitter build`
`$ tree-sitter generate`
`$ echo "* test" > test.org`

`$ tree-sitter parse test.org`
(document [0, 0] - [1, 0]
  subsection: (section [0, 0] - [1, 0]
    headline: (headline [0, 0] - [1, 0]
      stars: (stars [0, 0] - [0, 1])
      item: (item [0, 2] - [0, 6]
        (expr [0, 2] - [0, 6])))))

`$ echo "((headline) @headline)" > query.scm`
`$ tree-sitter query -q query.scm test.org`
test.org

The same with the Rust grammar

### Expected behavior

It should query the AST, and get the result as it did at the start, for the org grammar. It never queried after cargo install for a second time.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.6

### Operating system/version

ubuntu 22.04 && 23.04

**Comment by sogaiu** [comment]
I used a tree-sitter cli built from source (but no wasm bits -- didn't do the emsdk thing), but checkout of `v0.22.6` and it seemed to work here (i.e. query worked).

[Here](https://github.com/sogaiu/tree-sitter-issue-3441) is a repository that summarizes what I did.

If interested, steps were:

```
git clone --recursive https://github.com/sogaiu/tree-sitter-issue-3441
cd tree-sitter-issue-3441
sh run.sh
```

Note, it uses submodules so the `--recursive` bit is important.

---

(On a side note, AFAICT, there are no tests for tree-sitter-org, at least I didn't see any.)

**Comment by pramatias** [comment]
Oh, very nice @sogaiu, I will try the solution some time later today, and i close the issue if it fixes it!

**Comment by pramatias** [comment]
So, the issue was i used the tree-sitter command incorrectly. I executed the query command like that: 
`tree-sitter query -q scm_file src_file`

instead of 
`tree-sitter query scm_file src_file`

@sogaiu 's run.sh script used the command correctly. Thank you very much, i was really stuck on that issue for a while.

**Comment by pramatias** [comment]
Issue is resolved.
