### ISSUE TITLE
Package cannot be vendored on case-insensitive filesystems

### ISSUE THREAD

**Issue by Samasaur1** [tree-sitter/tree-sitter#3442]
### Problem

I'm trying to build a Cargo project that depends on tree-sitter, but I want to use `cargo vendor` to vendor its dependencies. When tree-sitter is vendored, some files are not copied. I opened an issue (https://github.com/rust-lang/cargo/issues/14034) in the Cargo repo to address this, and was told that it's because there's [a `cargo.toml` file](https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/generate/templates/cargo.toml) in the directory that isn't copied, and I'm on a case-insensitive filesystem.

Would it be possible to rename this file (perhaps to `_Cargo.toml`) so that vendoring works?

### Steps to reproduce

1. `git clone https://github.com/andrewtbiehl/kramdown-syntax_tree_sitter`
2. `cd kramdown-syntax_tree_sitter/ext/tree_sitter_adapter`
3. `RUBY=/path/to/bin/ruby cargo build` (observe that this succeeds)
4. `cargo vendor` (observe that this appears to succeed)
5. Modify `.cargo/config.toml` as directed by the output of `cargo vendor`
6. `cargo build` (observe that this fails)
7. There will also be no folder `vendor/tree-sitter-cli/src/generate/templates`, although it does exist in the this repo

### Expected behavior

I expected that vendoring this crate would succeed.

### Tree-sitter version (tree-sitter --version)

N/A

### Operating system/version

macOS 14.5

**Comment by amaanq** [comment]
that file is a template file that's used in a grammar repo, and is copied when you run `tree-sitter generate` to expose Rust bindings for a grammar. It is not used in this repo whatsoever (except for running that `generate` command), and does not need to be included to vendor any of the crates here

**Comment by Samasaur1** [comment]
The issue isn't with that file itself, but its presence prevents the entire `templates` directory from being vendored, which causes errors such as the following:
```
error: couldn't read `/private/tmp/kramdown-syntax_tree_sitter/ext/tree_sitter_adapter/vendor/tree-sitter-cli/src/generate/./templates/py-binding.c`: No such file or directory (os error 2)
  --> /private/tmp/kramdown-syntax_tree_sitter/ext/tree_sitter_adapter/vendor/tree-sitter-cli/src/generate/grammar_files.rs:55:37
   |
55 | const PY_BINDING_C_TEMPLATE: &str = include_str!("./templates/py-binding.c");
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read `/private/tmp/kramdown-syntax_tree_sitter/ext/tree_sitter_adapter/vendor/tree-sitter-cli/src/generate/./templates/Package.swift`: No such file or directory (os error 2)
  --> /private/tmp/kramdown-syntax_tree_sitter/ext/tree_sitter_adapter/vendor/tree-sitter-cli/src/generate/grammar_files.rs:57:38
   |
57 | const PACKAGE_SWIFT_TEMPLATE: &str = include_str!("./templates/Package.swift");
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read `/private/tmp/kramdown-syntax_tree_sitter/ext/tree_sitter_adapter/vendor/tree-sitter-cli/src/generate/./templates/alloc.h`: No such file or directory (os error 2)
  --> /private/tmp/kramdown-syntax_tree_sitter/ext/tree_sitter_adapter/vendor/tree-sitter-cli/src/generate/mod.rs:45:32
   |
45 | pub const ALLOC_HEADER: &str = include_str!("./templates/alloc.h");
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)
```
