### ISSUE TITLE
The C++ parsing engine reports an error in the "https://tree-sitter.github.io/tree-sitter/playground"

### ISSUE THREAD

**Issue by StKali** [tree-sitter/tree-sitter#3469]
### Problem

I can't see the syntax tree for the C++ language in the playground. There are some errors in the browser console, and I still have problems trying to change browsers, clear caches, etc. And it has been going on for 2-3 days as far as I can see, and it was available before.

![Snipaste_2024-07-17_14-24-13](https://github.com/user-attachments/assets/6e5a8e83-1669-4e1a-810c-d75c6c4feb62)

### Steps to reproduce

1 Open the tree-sitter [palyground](https://tree-sitter.github.io/tree-sitter/playground) page and select the C++ language.
2 Type some code in the code input block.

### Expected behavior

C++ languages can parse syntax structures in playground just like C or Go or other languages

### Tree-sitter version (tree-sitter --version)

now website version

### Operating system/version

any OS

**Comment by cnzhujie** [comment]
+1

**Comment by cnzhujie** [comment]
https://marketplace.visualstudio.com/items?itemName=ConnorAdams.astronomer
I found a vscode plugin which can see treesiter parse tree in vscode

**Comment by amaanq** [comment]
thank you for the bug report, this is fixed now.
