### ISSUE TITLE
Allow grammar files to have other file extensions 

### ISSUE THREAD

**Issue by TheOnlyTails** [tree-sitter/tree-sitter#3478]
### Problem

Currently, since ESM grammars are not supported, the only way to include a grammar in an ESM project is to either use CJS in the entire project (which sometimes causes problems with ESM-only libraries), or to move the file to a separate package and import it using a monorepo setup.

### Expected behavior

Recognize the '.cjs' file extension, which forces a file to be a CommonJS file, overriding the `type` field in `package.json`.

**Comment by ObserverOfTime** [comment]
ESM grammars will be supported in 0.23.0 regardless of extension.
