### ISSUE TITLE
`test --update` doesn't work properly with test attributes

### ISSUE THREAD

**Issue by withamoliver** [tree-sitter/tree-sitter#3479]
### Problem

Multiple issues with test attributes when using `tree-sitter test --update`:

1. If you use `:skip` then the test is always deleted from the test file.
2. If you use `:error` then the test is always deleted from the test file.
3. If the `:platform` doesn't match then the test is deleted from the test file.
4. Test attributes are always deleted from the test file.

There are multiple paths through `run_tests` which return without pushing to the `corrected_entries`, e.g. for `:skip`:
https://github.com/tree-sitter/tree-sitter/blob/800f2c41d0e35e4383172d7a67a16f3933b86039/cli/src/test.rs#L343-L350

The test attributes look to be getting deleted because they are never included in the `corrected_entries` which gets written back to the test file.

### Steps to reproduce

`:skip` bug (similar for `:platform(x)` with a platform `x` which doesn't match the current platform):
1. Add `:skip` to a test.
2. Run `tree-sitter test -u`.
3. The test is deleted from the test file.

`:error` bug:
1. Add `:error` to a test.
2. Run `tree-sitter test -u`.
3. The test is deleted from the test file.

Test attributes deleted bug:
1. Add `:platform(x)` to a test where `x` matches the current platform.
2. Run `tree-sitter test -u`.
3. The `:platform(x)` attribute is deleted from the test file.

### Expected behavior

For `tree-sitter test --update` to be useful with test attributes, it should behave similarly to if a test attribute wasn't specified.

When a test is skipped due to `:skip` or a mismatched `:platform` then the test should be written back to the file with the same contents as before.

For `:error` it might make sense to write back the same content with an omitted parse tree after the `---` even if the original file contained one, as per the documentation. 

Test attributes shouldn't be deleted when writing back to the file.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.6 (800f2c41d0e35e4383172d7a67a16f3933b86039)

### Operating system/version

macOS 14.4.1

**Comment by withamoliver** [comment]
The same thing happens when a test is skipped due to not matching a `--filter <FILTER>`, `--include <INCLUDE>` or when matching an `--exclude <EXCLUDE>`.

**Comment by cathaysia** [comment]
As a supplement. test -u will also cause ||| to be lost. that is :

````
=================|||
test name
=================|||
```
will become:

```
==================
test name
==================
```
