### ISSUE TITLE
0.22.6 release broke semantic versioning

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter#3487]
### Problem

In https://github.com/tree-sitter/tree-sitter/commit/90ba5256d19f97fe854b999dcf65a6cbb66f166e, which was pushed directly to `master`, a `language_name` parameter was added to `ts_highlighter_add_language`, which is a breaking change to public API. We should push out a major release to reflect this. @maxbrunsfeld, can we `cargo yank` 0.22.6 and add branch protections to `master` so this doesn’t happen again?

@amaanq, can I ask what happened here? It looks like this was needed for your work on #2544, but you didn’t go through the PR process, and the changelog entry is filed under “Bug fixes”. It’s important that we don’t break semver, as it creates a lot of unexpected work (tree-sitter and its vended libraries are critical infrastructure for us). It’s really important that even small changes go through the PR process, as this would almost certainly have been noted in review.

**Comment by patrickt** [comment]
@amaanq Bump: any word on this?

**Comment by piero1100** [comment]
Diff:``

**Comment by maxbrunsfeld** [comment]
@patrickt - @dcreager is an owner of the crate. Are you guys able to do the yank and version publish?

**Comment by patrickt** [comment]
@maxbrunsfeld Sure thing.

**Comment by piero1100** [comment]
> @maxbrunsfeld Sure thing. Thoughts on branch protections for master?

Yes

**Comment by piero1100** [comment]
> @patrickt - @dcreager is an owner of the crate. Are you guys able to do the yank and version publish?

Yes dear

**Comment by maxbrunsfeld** [comment]
Ok, I set up a branch protection for master that requires a PR. Seems like a good idea.

**Comment by piero1100** [comment]
0.27,3

**Comment by clason** [comment]
> Open question: How are the neovim folks (or other editor communities) doing tree-sitter syntax highlighting? I have to assume if they were doing the above we would have had bug reports by now.

We are doing fine :) We have our own custom highlighter that is directly calling the tree-sitter library (we don't use anything else from this project), which was not affected by this. (And, yes, we would have complained loudly -- if we could not easily have worked around this...)

(If I may make so bold: The root problem here is that tree-sitter has so many independent moving parts that all live in a single mono repo, which is the only thing that implicitly couples them together. Having the lib, various crates, and CLI live all in their own repos with _explicit_ integration tests would make things much easier to reason about. Of course, disentangling everything and setting this up properly would be a _huge_ effort, and tree-sitter is already under-resourced for basic maintenance -- which, let's be honest here, is the _real_ root problem.)

**Comment by dcreager** [comment]
> I think a unit test that exercises `cbindgen` is a fantastic idea

Note that's only part of that suggestion — it depends on first switching to using `cbindgen` to create the header files in the first place

**Comment by dcreager** [comment]
> In fact, I don't know of any project directly using the `tree-sitter-highlight` crate, much less from C...

GitHub.com syntax highlighting does that for certain languages.  But we were pinned to an earlier version of `tree-sitter-highlight` and so were fine, until we tried to do an upgrade as part of a highlighting grammar bump
