### ISSUE TITLE
descendantsOfType missing from web-tree-sitter typescript definition

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#349]

**Comment by Razzeee** [comment]
These seem to be missing in total

```
      firstChildForIndex(index: number): SyntaxNode | null;
      firstNamedChildForIndex(index: number): SyntaxNode | null;

      descendantsOfType(
        types: String | Array<String>,
        startPosition?: Point,
        endPosition?: Point
      ): Array<SyntaxNode>;

      closest(types: String | Array<String>): SyntaxNode | null;

```

**Comment by Razzeee** [comment]
![Screenshot from 2019-06-01 23-59-53](https://user-images.githubusercontent.com/5943908/58754074-9b482400-84c9-11e9-92c3-7a5b8af702f7.png)

Running the test-suite with wasm also shows these three tests as pending, but not ever resolving.

**Comment by maxbrunsfeld** [comment]
Yeah, these aren't implemented yet for the wasm binding. I did port the tests over from `node-tree-sitter` and leave them pending, because I'd like to implement them. If anyone feels like implementing them, PRs welcome.

We might want to change `binding.c` to use C++, so that we can use `std::vector` while building up the Arrays.

**Comment by Razzeee** [comment]
Had a go at it yesterday, but felt way out of my depth :/
Editor wasn't really helping too.

I really just need `descendantsOfType` I think, as I don't use the others. But even for that it doesn't seem to be a copy and paste job.

**Comment by Razzeee** [comment]
This problem is getting bigger and bigger for my project.
I will probably try to get this to work. Not sure I can pull it off. Can you offer any additional advice?

What would I need to do to switch to C++?

**Comment by maxbrunsfeld** [comment]
I think I'll have time to do this soon.
