### ISSUE TITLE
tree-sitter/emscripten mismatch?

### ISSUE THREAD

**Issue by paulyoung** [tree-sitter/tree-sitter#350]
I'm seeing an issue that stems from `loadWebAssemblyModule` (apparently provided by emscripten's `support.js`) reading from my Wasm parser and calling `fetchBinary` with paths/URLs that don't make sense.

This currently looks something like the following:

```
fetch url:
fetch url:
fetch url: nv	tableBase
fetch url: ree_sitter_mylang
fetch url: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
fetch url: @
```

where:

```
global.fetch = (url, options) => {
  console.log("fetch url:", url);
  ...
};
```

I was able to learn some things by taking my `node_module/web-tree-sitter/tree-sitter.js` file and running it through [`prettier`](https://prettier.io/playground).

Specifically, [`neededDynLibs`](https://github.com/emscripten-core/emscripten/blob/4e4a7946964cb3d45cd2f1af4bcee38e585318c4/src/support.js#L571
) is the array of strings shown in the log output above.

I'll try to provide as much info as possible on my setup.

***

1. I'm essentially trying to use `tree-sitter` in a Node.js environment, so while the following helps with that:

https://github.com/tree-sitter/tree-sitter/blob/85877a1def714ed2c7c1300cef72ca6612248998/lib/binding_web/binding.js#L573-L581

Emscripten [still uses `fetch`](https://github.com/emscripten-core/emscripten/blob/1.38.31/src/support.js#L109), which isn't provided by default on Node.js so I'm essentially doing `global.fetch = ...`, checking for the `file:` URL scheme, and employing a similar workaround.

I don't think this is affecting anything, but wanted to point it out.

***

2. I'm using the [release assets of `tree-sitter` 0.15.2](https://github.com/tree-sitter/tree-sitter/releases/tag/0.15.2) but my Wasm parser was built using `tree-sitter build-wasm`. The `build-wasm` command apparently also uses emscripten, and I'm concerned that the version of emscripten's `support.js` included in `tree-sitter.js` is incompatible with the version of `emscripten` I used when invoking `tree-sitter build-wasm`

I'm using Nix so can't rely on `script/fetch-emscripten` (or rather haven't been able to figure out how to make that work as a fixed-output derivation yet) but based on [the Travis CI build for 0.15.2](https://travis-ci.org/tree-sitter/tree-sitter/jobs/540911905#L202) I'm using emscripten 1.38.31

I've tried different versions of emscripten and have seen different log output, which makes me think this is the issue.

For example, if I use 1.38.32 I see;

```
fetch url: 
fetch url: 
fetch url: nv	tableBase
fetch url: _mylang
fetch url: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
fetch url: @
```

**Comment by paulyoung** [comment]
I think I got confused by some release version differences, but the [Travis CI build for web: 0.15.5](https://travis-ci.org/tree-sitter/tree-sitter/jobs/539829942) says:

> Emscripten, llvm and clang build versions do not match, this is dangerous (1.38.33, 1.38.31, 1.38.31)

There's also a [Travis CI build for 0.15.4](https://travis-ci.org/tree-sitter/tree-sitter/jobs/539818386) (which looks like it may have been removed from releases?) that says the same thing.

**Comment by maxbrunsfeld** [comment]
Hmm, you definitely shouldn't have to define `global.fetch` to use `tree-sitter.js` within Node. On my machine (and on Travis), you just need to `require("tree-sitter.js")` with no special setup. I think this works because `emscripten` generates code that detects and uses node APIs when appropriate.

The tests are passing in Node on that CI build that you linked. Looking at what might be going on...

**Comment by maxbrunsfeld** [comment]
Oh, there's a bug where the library only works if you call `Parser.init` *right away* after loading the module. Maybe you're hitting that? I'll push up a fix to that soon.

**Comment by maxbrunsfeld** [comment]
Published a fix for that `Parser.init` thing in `web-tree-sitter` 0.15.6.

Maybe try 0.15.6, and avoid defining `global.fetch` beforehand, because that might be confusing emscripten's environment detection? Not sure.

**Comment by paulyoung** [comment]
Thanks, will give this a shot. FWIW, I resorted to that because I was getting a `fetch is not defined` error.

**Comment by paulyoung** [comment]
Here's what I'm seeing:

```
ReferenceError: fetch is not defined
	at fetchBinary (<redacted>/node_modules/web-tree-sitter/tree-sitter.js:1:4056)
	at loadLibData (<redacted>/node_modules/web-tree-sitter/tree-sitter.js:1:4240)
	at getLibModule (<redacted>/node_modules/web-tree-sitter/tree-sitter.js:1:4508)
	at loadDynamicLibrary (<redacted>/node_modules/web-tree-sitter/tree-sitter.js:1:4942)
	at <redacted>/node_modules/web-tree-sitter/tree-sitter.js:1:7889
	at Array.map (<anonymous>)
	at loadWebAssemblyModule (<redacted>/node_modules/web-tree-sitter/tree-sitter.js:1:7866)
	at load.t.then.e (<redacted>/node_modules/web-tree-sitter/tree-sitter.js:1:56224)
```

**Comment by maxbrunsfeld** [comment]
What version of node are you using? Do you have a minimal example script that causes this when executed?

I'm not sure why it's calling `fetchBinary` and not loading it with the Node APIs.

**Comment by paulyoung** [comment]
I'm on node v10.2.0.

I'm debugging further now that I understand more about this. It wasn't obvious from looking at minified code, but I'm now seeing that `flags` here is `{ loadAsync: true }` and going from there.

https://github.com/emscripten-core/emscripten/blob/1.38.31/src/support.js#L181

**Comment by paulyoung** [comment]
Which corresponds to this: https://github.com/tree-sitter/tree-sitter/blob/3a51b23f1a491f8192e329862e606d08d0620404/lib/binding_web/binding.js#L591

**Comment by paulyoung** [comment]
If I do this then it works as I would expect:

```js
.then(bytes => loadWebAssemblyModule(bytes, {
  fs: { readFile: require('fs').readFileSync },
  loadAsync: true,
}))
```

But then basically I get back to where I was before, with it being called with "paths" that don't make sense. The first time it's called with an empty string and then everything errors out.

**Comment by maxbrunsfeld** [comment]
I would expect there to never be any dynamic libraries associated with the language module. Maybe it is an emscripten version mismatch, and the main library is misinterpreting the bytes of the language wasm file, and thinking that there are library dependencies.

Does anything change if you build your language module with `tree-sitter build-wasm --docker`?  This will force it to use Docker to run emscripten instead of running your own emscripten install.

**Comment by paulyoung** [comment]
I'll give that a try but not sure what to expect trying to use Docker with Nix.

However, `tree-sitter build-wasm --docker tree-sitter-mylang` and `tree-sitter build-wasm tree-sitter-mylang --docker` both complain about `emcc`, which seems wrong:

```
Failed to run emcc command
Details:
  No such file or directory (os error 2)
```

**Comment by maxbrunsfeld** [comment]
With the `--docker` flag it should do exactly the same thing, but internally it will run `emcc` in a docker container in order to compile your parser to wasm.

It's probably a misleading error message - I think it can't find the `docker` command.

**Comment by paulyoung** [comment]
In any case I'll try this route and report back. Thanks for the help.

**Comment by paulyoung** [comment]
I managed to get things working with `--docker` (via hocker, for Nix) using the `sdk-tag-1.38.32-64bit` image.

**Comment by maxbrunsfeld** [comment]
Great! I'm not sure exactly what we can do to prevent this from happening; I thought that emscripten's compiled libraries would have some kind of versioning or interoperability. It's good to know that the emscripten version apparently *does* matter somewhat.
