### ISSUE TITLE
Rethink the purpose of injection.combined

### ISSUE THREAD

**Issue by ribru17** [tree-sitter/tree-sitter#3517]
### Problem

Full problem statement can be found here: https://github.com/neovim/neovim/pull/29601#issuecomment-2212737235. Other editors like helix have seen issues with the current implementation: https://github.com/helix-editor/helix/discussions/11157. 

**TLDR:** I would like to propose a new meaning for `injection.combined`. For

```
other NODETYPE other
other NODETYPE other
```

The query

```scheme
(NODETYPE)+ @injection.content
```

should inject:

```
other ******** other
other ******** other
```
and

```scheme
((NODETYPE)+ @injection.content (#set! injection.combined))
```
should inject:

```
other **************
************** other
```

---

Right now, even with `tree-sitter highlight`, it seems that injections with `injection.combined` are pretty buggy. At least in the CLI side, the regions don't always combine properly and just seem buggy in general. Injections with quantified captures also don't seem to apply properly. This is a separate bug report in and of itself, but I'd like to use the opportunity to request a change. I think most use cases of injection.combined could/should be solved with quantified captures of `@injection.content`. Instead of having global combined injection documents, they should be scoped to the quantified query to avoid undesirable injection highlighting bugs, specifically when there is text in-between two injected regions. In scenarios where you need the nodes **and** the text in-between to be part of the document, we can repurpose injection.combined to specify that. I think still makes sense (maybe makes more sense) given the name.

**Comment by maxbrunsfeld** [comment]
Combined is about parsing the content of all of the injection matches as one single document. It is needed for cases where it’s not possible for a single query match to capture all of the content nodes.

the new meaning that you proposed would not solve the same problem.

**Comment by amaanq** [comment]
I think this can be closed, the semantics of `combined` are not the same as using quantified captures on nodes tagged `@injection.content`. I would also disagree that the second example should repurpose combined to join the range between two nodes, and not as two disjunct ranges, and the quantified capture should match a sequence of uninterrupted nodes of the same kind.

**Comment by rafaelpirolla** [comment]
Hi @amaanq, would you know some workaround to achieve the desired result?
