### ISSUE TITLE
AST difference between parsing and testing

### ISSUE THREAD

**Issue by cpkio** [tree-sitter/tree-sitter#3527]
### Problem

I'm developing an Asciidoc parser and try to make tests. This is the parsed text:
```
[source,bash]
----
curl --location --request GET 'https://example.com' \
--header 'Authorization: Bearer Token' <.>
----
<.> Authorization token
```

This is the result of parsing with `tree-sitter parse`:
```
(document [0, 0] - [6, 0]
  (option_block [0, 0] - [1, 0]
    (block_option_marker_start [0, 0] - [0, 1])
    (block_type [0, 1] - [0, 7])
    (attribute [0, 8] - [0, 12])
    (block_option_marker_end [0, 12] - [1, 0]))
  (block_listing [1, 0] - [5, 0]
    (block_listing_separator [1, 0] - [2, 0])
    (callout_mark [3, 39] - [3, 42])
    (block_listing_separator [4, 0] - [5, 0]))
  (callout [5, 0] - [6, 0]
    (callout_mark [5, 0] - [5, 3])
    (paragraph [5, 4] - [6, 0])))
```

The test case is obviously no much difference:
```
====
Callouts
====
[source,bash]
----
curl --location --request GET 'https://example.com' \
--header 'Authorization: Bearer Token' <.>
----
<.> Authorization token

---
(document
  (option_block
    (block_option_marker_start)
    (block_type)
    (attribute)
    (block_option_marker_end))
  (block_listing
    (block_listing_separator)
    (callout_mark)
    (block_listing_separator))
  (callout
    (callout_mark)
    (paragraph)))

```
But the result of `tree-sitter test -f Callouts` is unexpected (it cannot detect second block listing separator):
```
correct / expected / unexpected

  1. Callouts:

    (document
      (option_block
        (block_option_marker_start)
        (block_type)
        (attribute)
        (block_option_marker_end))
      (block_listing
        (block_listing_separator)
        (callout_mark)
        (MISSING block_listing_separator)))
        (block_listing_separator))
      (callout
        (callout_mark)
        (paragraph)))
```

If I insert diagnostic messages into block that parses `block_listing_separator`, it turns out that  this block is called three time when parsing with `tree-sitter parse` and only two times when  `tree-sitter test -f Callouts` is called.

### Steps to reproduce

see https://github.com/cpkio/tree-sitter-asciidoc

### Expected behavior

Expecting parsed AST to matched test case AST.

### Tree-sitter version (tree-sitter --version)

0.22.6

### Operating system/version

Windows10

**Comment by ObserverOfTime** [comment]
Blank line.

**Comment by ObserverOfTime** [comment]
You need to add a suffix to the test headers to avoid confusing the test parser.

**Comment by cpkio** [comment]
@ObserverOfTime Thanks, but changing test header makes no difference. It fails even when it is called «test».

**Comment by cpkio** [comment]
🤦🏻 
thank you
