### ISSUE TITLE
[feature request][question] Is there a wrapper library for multiple grammars(eg. `tree-sitter-typescript`, `tree-sitter-go` and so on.) that can be used to implement operations for these programming languages? 

### ISSUE THREAD

**Issue by liaodalin19903** [tree-sitter/tree-sitter#3533]
### Problem

Is there already a wrapper library for multiple grammars(eg. `tree-sitter-typescript`, `tree-sitter-go` and so on.) that can be used to implement operations for these programming languages? 

For example: 
1、get the class inheritance chain of any programming language file,
2、get all properties/methods below the class.
3、method's params.

**Comment by lewis6991** [comment]
No

**Comment by clason** [comment]
Well, yes. It's called "Neovim" 😁

**Comment by liaodalin19903** [comment]
> No

Could you tell me the reason? Is it difficult to implement or takes a long time to implement?

**Comment by LadyE215** [comment]
> ### Πρόβλημα
> Υπάρχει ήδη μια βιβλιοθήκη περιτυλίγματος για πολλαπλές γραμματικές (π.χ. , και ούτω καθεξής.) που μπορεί να χρησιμοποιηθεί για την υλοποίηση λειτουργιών για αυτές τις γλώσσες προγραμματισμού;`tree-sitter-typescript``tree-sitter-go`
> 
> Για παράδειγμα: 1、λάβετε την αλυσίδα κληρονομικότητας κλάσης οποιουδήποτε αρχείου γλώσσας προγραμματισμού, 2、λάβετε όλες τις ιδιότητες / μεθόδους κάτω από την κλάση. 3、παράμετροι μεθόδου.
> 
> ### Αναμενόμενη συμπεριφορά
> _Καμία απάντηση_

**Comment by Mishap111** [comment]
> > ### Πρόβλημα
> > Υπάρχει ήδη μια βιβλιοθήκη περιτυλίγματος για πολλαπλές γραμματικές (π.χ. , και ούτω καθεξής.) που μπορεί να χρησιμοποιηθεί για την υλοποίηση λειτουργιών για αυτές τις γλώσσες προγραμματισμού;`` tree-sitter-typescript``tree-sitter-go ``
> > Για παράδειγμα: 1、λάβετε την αλυσίδα κληρονομικότητας κλάσης οποιουδήποτε αρχείου γλώσσας προγραμματισμού, 2、λάβετε όλες τις ιδιότητες / μεθόδους κάτω από την κλάση. 3、παράμετροι μεθόδου.
> > ### Αναμενόμενη συμπεριφορά
> > _Καμία απάντηση_

2ND die sind oder hat 🧢 in den

**Comment by clason** [comment]
@ObserverOfTime you can now ban these clowns. Click on the triple dots menu on the top right of the post for that.
