### ISSUE TITLE
link unavailable on introduction page

### ISSUE THREAD

**Issue by lie-yan** [tree-sitter/tree-sitter#3535]
### Problem

The link below on the [Introduction](https://tree-sitter.github.io/tree-sitter/) page is unavailable. Could any one update it? 

> https://what-when-how.com/compiler-writing/bottom-up-parsing-compiler-writing-part-13

### Steps to reproduce

Open https://tree-sitter.github.io/tree-sitter/
and click the link:

![image](https://github.com/user-attachments/assets/f86ee895-dde2-4010-ae6b-f339e5bd23e7)

### Expected behavior

<img width="1028" alt="image" src="https://github.com/user-attachments/assets/16932ebf-8304-45de-9fc4-0e3a7c5e7484">

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.20.9

### Operating system/version

macOS 11.5

**Comment by sogaiu** [comment]
It doesn't look like the site is currently available.

Don't know if the content has officially moved elsewhere, but in the mean time, [this](https://web.archive.org/web/20240302031213/https://what-when-how.com/compiler-writing/bottom-up-parsing-compiler-writing-part-13/) seems to be a way of getting at a recent version of the content.
