### ISSUE TITLE
Where to find tree-sitter support?

### ISSUE THREAD

**Issue by brupelo** [tree-sitter/tree-sitter#356]
Hi,

little bit of background first, I'm in the middle of creating an IDE in python using QScintilla and I've already tried different parsing libraries before considering tree-sitter (QScintilla lexers, pygments, antlr, syntect, pyparsing, qt syntax highlighter, ply).

I've wanted to try tree-sitter for ages but the fact it's fairly new tech and the ammount of existing parsers isn't big in comparison to another existing alternatives has always "scared" me of doing so. In any case, Since the first time I saw the Max [talk](https://www.youtube.com/watch?v=Jes3bD6P0To) at youtube I've been sold to this tech, sounds like an ideal parsing library.

Anyway, question here is, what are the official channels to find support here?

- Is there any channel at freenode?
- Any forum/google_group/stackoverflow channel?
- Is it alright to post questions at github issues?
- How large is the existing community?
- Books? Tutorials?

So far I've been reading a little bit the documentation, specially the section [creating parsers](http://tree-sitter.github.io/tree-sitter/creating-parsers). But I'm still wondering, how hard would be to adapt existing EBNF grammars to tree-sitter syntax?

For instance, let's say I'd like to convert this ANTLR [GLSL](https://gitrepos.virvig.eu/docencia/glcheck/blob/c96cf65bae5894af53af51535f321cf4823867b9/src/GLSL/GLSL.g4) one to tree-sitter format and start using it for syntax-highlighting, code-folding, etc with QScintilla, how hard could that be?

Hopefully you'll be able to clarify some of my concerns here.

Thanks in advance!

**Comment by Arcanemagus** [comment]
I think I can answer a few of the basic questions for you:
> * How large is the existing community?

Tree-sitter was originally developed for and is used by the [Atom text editor](https://github.com/atom/atom), among other projects at GitHub.

> * Is there any channel at freenode?

Currently at least your best bet here is likely to be the [Atom Slack instance](https://discuss.atom.io/t/join-us-on-slack/16638)

> * Any forum/google_group/stackoverflow channel?

Similarly, you are probably best posting over in [Atom's Discuss](https://discuss.atom.io/).

**Comment by Aerijo** [comment]
I don’t think Discuss will help much; I’ll be there, but I’d redirect most technical questions to making an issue here.

**Comment by brupelo** [comment]
Hey guys, thanks for the feedback! I've been reading the tree-sitter docs and also looked at the public API and I think github support will be more than good enough. Docs are good enough and the public API is minimal... so I think books or tutorials would be out of scope here :)

That said, I'll be opening issues/question at github each time I've got stuck... let's see how it goes.

Plus, I guess by using proper labelling having a single channel of communitcation may be also quite convenient.

**Comment by maxbrunsfeld** [comment]
I think that soon it'll be time to create some dedicated forum for Tree-sitter questions. I'll give an update on this issue if we do create one.

**Comment by zoechi** [comment]
Any news? Gitter room for example?

**Comment by sogaiu** [comment]
Perhaps this will be considered? https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions

**Comment by maxbrunsfeld** [comment]
There's now a discussion board.
