### ISSUE TITLE
build-wasm on Windows

### ISSUE THREAD

**Issue by zabel-xyz** [tree-sitter/tree-sitter#358]
I am the author of vscode extension for [language plsql](https://github.com/zabel-xyz/plsql-language)
I am trying to use tree-sitter for navigation, symbol list (alternative of current regExpParser I wrote) 

I encounter a problem with build-wasm: 
`node_modules/.bin/tree-sitter build-wasm "c:/develop/tree-sitter-plsql"`
System: Windows 10
Emscripten installed
No Docker

Error:  Failed to get get current user id {}

I use a .bat file to build wasm, and everything works fine:
```
call emsdk_env.bat
call emcc -o tree-sitter-plsql.wasm -Os -s WASM=1 -s SIDE_MODULE=1 -s TOTAL_MEMORY=33554432 -s "EXPORTED_FUNCTIONS=['_tree_sitter_plsql']" parser.c
```

**Comment by maxbrunsfeld** [comment]
Thanks for the report! I didn't know much about emscripten support on windows, so I hadn't tested it. It looks like this will be easy to fix; it's just a dumb mistake on my part: running unnecessary POSIX-specific code in that command.

**Comment by maxbrunsfeld** [comment]
Did you run `call emsdk_env.bat` before running `tree-sitter build-wasm`?

**Comment by zabel-xyz** [comment]
Yes, I tried to call emsdk_env.bat first, but I get the same error...

**Comment by maxbrunsfeld** [comment]
It looks like it's not able to execute `emcc` on your system? In the next version, the error message will be better and maybe it will help us determine more about what's going on.

**Comment by Razzeee** [comment]
Some experience report from me, even if that's from linux. I tried for about an hour to get everything to work with emscripten, really felt horrible.

Then tried with docker and it worked on the first try.

**Comment by maxbrunsfeld** [comment]
FWIW, the Travis CI build uses [this script](https://github.com/tree-sitter/tree-sitter/blob/master/script/fetch-emscripten) to install Emscripten from scratch, and then uses the `build-wasm` command as part of the build It only does so on Mac, and it uses Docker instead on Linux, but I think that script should run fine on Linux too.

**Comment by Razzeee** [comment]
Pretty sure that's roughly what I tried. But `emsdk_env` used something, that I had not installed on arch and didn't want to install. :)

**Comment by maxbrunsfeld** [comment]
Yeah, `emsdk_env` requires Python I think.

**Comment by Razzeee** [comment]
I think it did run fine, but compiling still failed. I ended up blaming the
source command that seems to be needed, but is not included in manjaro.

https://github.com/emscripten-core/emsdk/blob/master/emsdk_env.sh
