### ISSUE TITLE
Capture a node under multiple names

### ISSUE THREAD

**Issue by jmehnle** [tree-sitter/tree-sitter#3587]
### Problem

I would like to be able to do this:

```
(assignment_expression
  left: (identifier) @the-function-name @other-name
  right: (function))
```

Rationale: I'm parsing a number of different languages, and my queries look different for each language but attempt to capture equivalent elements across languages under the same capture names. In some languages a node serves multiple purposes, and so some of these names coincide on the same node in my queries. Alas, it appears that Tree Sitter's query language rejects this syntax.

**Comment by maxbrunsfeld** [comment]
That syntax should be accepted! That's implemented

**Comment by amaanq** [comment]
It is accepted and it definitely works

**Comment by jmehnle** [comment]
Thank you. Apologies, I had a typo in my query that made it fail, and I didn't resolve the "row X, column Y" coordinates correctly.
