### ISSUE TITLE
Thread-safety question

### ISSUE THREAD

**Issue by zajac** [tree-sitter/tree-sitter#359]
Documentation says the following: 

> You need to copy a syntax tree in order to use it on more than one thread at a time, as syntax trees are not thread safe.

I'm building a JVM library to work with TS trees. It is quite hard to reason about the thread which is reading the tree (think of thread-pool job or some co-routines engine).
I'd like to get more details about the specific destructive operations on trees performed by the runtime. Is it just `ts_tree_edit`? Is it safe to invoke the `ts_tree_copy` right before editing it and stop caring about threading issues?

**Comment by maxbrunsfeld** [comment]
Currently it’s not just the edit function. Some node retrieval APIs also perform caching, which mutates a cache that’s stored on the Tree.

The caching isn’t critically important, maybe an API could be added that disables it.

**Comment by zajac** [comment]
Could you please point me to that code?

**Comment by maxbrunsfeld** [comment]
Heres one instance:

https://github.com/tree-sitter/tree-sitter/blob/master/lib/src/node.c#L137

**Comment by zajac** [comment]
I'm using only TSTreeCursors to access the tree structure. As far as I understand it doesn't involve that caching, as it uses the stack instead. Am I right?

**Comment by maxbrunsfeld** [comment]
Yeah, that’s right. Those code paths that mutate the cache will not run.

**Comment by zajac** [comment]
oh BTW I see this:
```
TSTreeCursor ts_tree_cursor_new(TSNode node) {
  TSTreeCursor self = {NULL, NULL, {0, 0}};
  ts_tree_cursor_init((TreeCursor *)&self, node);
  return self;
}


void ts_tree_cursor_init(TreeCursor *self, TSNode node) {
  self->tree = node.tree;
  array_clear(&self->stack);
  array_push(&self->stack, ((TreeCursorEntry) {
    .subtree = (const Subtree *)node.id,
    .position = {
      ts_node_start_byte(node),
      ts_node_start_point(node)
    },
    .child_index = 0,
    .structural_child_index = 0,
  }));
}


bool ts_tree_cursor_goto_parent(TSTreeCursor *_self) {
  TreeCursor *self = (TreeCursor *)_self;
  for (unsigned i = self->stack.size - 2; i + 1 > 0; i--) {
    TreeCursorEntry *entry = &self->stack.contents[i];
    bool is_aliased = false;
    if (i > 0) {
      TreeCursorEntry *parent_entry = &self->stack.contents[i - 1];
      const TSSymbol *alias_sequence = ts_language_alias_sequence(
        self->tree->language,
        parent_entry->subtree->ptr->production_id
      );
      is_aliased = alias_sequence && alias_sequence[entry->structural_child_index];
    }
    if (ts_subtree_visible(*entry->subtree) || is_aliased) {
      self->stack.size = i + 1;
      return true;
    }
  }
  return false;
}
```

It implies that cursor created for some `node` will not be able to ascend to it's parent with `ts_tree_cursor_goto_parent`

That is kind of unexpected

**Comment by zajac** [comment]
What do you think of adding `ts_tree_cursor_copy` function?

**Comment by zajac** [comment]
I find the data structure to be quite interesting, it would be great to have some documentation or paper about it. Thank you for a great job.

**Comment by maxbrunsfeld** [comment]
Closing this one out. Let me know if you have other questions.
