### ISSUE TITLE
Missing Superclass Identifier: Function Declaration Mistakenly Recognized as Identifier

### ISSUE THREAD

**Issue by sho94os** [tree-sitter/tree-sitter#3595]
### Problem

this is my grammar:

`
  module.exports = grammar({
  name: "mycode",

    rules: {
    source_file: $ => seq(
      repeat($.func_stmt),
      repeat($.class_stmt),
      repeat($.package_stmt)
    ),

    package_stmt: $ => prec.right(
      seq(
        $.package_keyword,
        $.identifier,
        repeat(choice($.class_stmt)),  
        optional($.end_keyword)
      )
    ),

    class_stmt: $ => prec.right(
      seq(
        $.class_keyword,
        $.identifier,
        optional($.superclass_declaration),
        repeat($.class_member),
        repeat($.func_stmt),
        optional($.end_keyword)
      )
    ),

    superclass_declaration: $ => seq(
      $.from_keyword,
      $.identifier
    ),

    func_stmt: $ => prec.right(
      seq(
        choice($.func_keyword, $.def_keyword),
        $.identifier,
        optional($.end_keyword)
      )
    ),

    again_keyword: $ => /again/i,
    and_keyword: $ => /and/i,
    but_keyword: $ => /but/i,
    bye_keyword: $ => /bye/i,
    call_keyword: $ => /call/i,
    case_keyword: $ => /case/i,
    catch_keyword: $ => /catch/i,
    class_keyword: $ => /class/i,
    def_keyword: $ => /def/i,
    do_keyword: $ => /do/i,
    done_keyword: $ => /done/i,
    else_keyword: $ => /else/i,
    elseif_keyword: $ => /elseif/i,
    end_keyword: $ => /end/i,
    exit_keyword: $ => /exit/i,
    for_keyword: $ => /for/i,
    foreach_keyword: $ => /foreach/i,
    func_keyword: $ =>  /func/i,
    from_keyword: $ => /from/i,
    get_keyword: $ => /get/i,
    give_keyword: $ => /give/i,
    if_keyword: $ => /if/i,
    import_keyword: $ => /import/i,
    in_keyword: $ => /in/i,
    load_keyword: $ => /load/i,
    loop_keyword: $ => /loop/i,
    new_keyword: $ => /new/i,
    next_keyword: $ => /next/i,
    not_keyword: $ => /not/i,
    off_keyword: $ => /off/i,
    ok_keyword: $ => /ok/i,
    on_keyword: $ => /on/i,
    or_keyword: $ => /or/i,
    other_keyword: $ => /other/i,
    package_keyword: $ => /package/i,
    private_keyword: $ => /private/i,
    put_keyword: $ => /put/i,
    return_keyword: $ => /return/i,
    see_keyword: $ => /see/i,
    step_keyword: $ => /step/i,
    switch_keyword: $ => /switch/i,
    to_keyword: $ => /to/i,
    try_keyword: $ => /try/i,
    while_keyword: $ => /while/i,
    endfunc_keyword: $ => /endfunc/i,
    endclass_keyword: $ => /endclass/i,
    endpackage_keyword: $ => /endpackage/i,
    endif_keyword: $ => /endif/i,
    endfor_keyword: $ => /endfor/i,
    endwhile_keyword: $ => /endwhile/i,
    endswitch_keyword: $ => /endswitch/i,
    endtry_keyword: $ => /endtry/i,
    function_keyword: $ => /function/i,
    endfunction_keyword: $ => /endfunction/i,
    break_keyword: $ => /break/i,
    continue_keyword: $ => /continue/i,

    class_member: $ => $.identifier,
    superclass: $ => $.identifier,

    identifier: $ => /[a-z]+/,
    //identifier: $ => token(prec(-1, /[a-z]+/)),

  }

});`

**with this input** 

![image](https://github.com/user-attachments/assets/924fe5eb-5fca-44bb-afc7-9e36d0dac453)

**i get this output**

![image](https://github.com/user-attachments/assets/c52512d0-1e45-4a7b-bea0-e9e8ce0e9d8d)

### Steps to reproduce

tree-sitter generate && tree-sitter build --wasm && tree-sitter playground

### Expected behavior

sasa

### Tree-sitter version (tree-sitter --version)

last

### Operating system/version

linux

**Comment by ObserverOfTime** [comment]
Sounds like an issue with your grammar.
