### ISSUE TITLE
`tree-sitter fuzz` does not ignore `:skip` and `:error` tests

### ISSUE THREAD

**Issue by maloewe-ona** [tree-sitter/tree-sitter#3627]
### Problem

If I understand it correctly the new `tree-sitter fuzz` command which was added in 0.23.0 (#3385) is supposed to use the `test/corpus` directory as source for its fuzzing.

The problem is that it does not seem to consider the test attributes `:skip` and `:error`, and parses these tests as well which then fails with "Incorrect initial parse for ...".

Not sure if this negatively affects fuzzing, but it is definitely irritating to see these _expected_ parsing errors on the console.

### Steps to reproduce

1. Create a parser test under `test/corpus/` with attributes `:skip` or `:error` and expected parsing errors
2. Run
    ```
    tree-sitter fuzz
    ```

Bug: It reports
> Incorrect initial parse for ...

### Expected behavior

Tests marked with `:skip` or `:error` should be ignored by `tree-sitter fuzz`, or for `:skip` in case the fuzzer can still use it as input, it should at least not print an "Incorrect initial parse for ..." error.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.23.0

### Operating system/version

Windows 10, WSL 2 Ubuntu

**Comment by ObserverOfTime** [comment]
The fuzzer should definitely consider `:error` tests (but maybe not `:skip`), though it should not report them errors.
