### ISSUE TITLE
0.22.6 breaks test file suffix feature

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/tree-sitter#3643]
### Problem

For the [tree-sitter-tlaplus](https://github.com/tlaplus-community/tree-sitter-tlaplus) grammar, upgrading from tree-sitter 0.22.5 to 0.22.6 causes 61 corpus tests to fail (out of around 250).

### Steps to reproduce

```
git clone https://github.com/tlaplus-community/tree-sitter-tlaplus
cd tree-sitter-tlaplus
npm install
./node_modules/.bin/tree-sitter --version
./node_modules/.bin/tree-sitter test
git fetch origin
git checkout ts_0_22_6_upgrade
git diff main
npm install
./node_modules/.bin/tree-sitter --version
./node_modules/.bin/tree-sitter test
```

### Expected behavior

I expected tests that passed in one patch release to pass in the next patch release I suppose (the same failure occurs with 0.23.0). This might have to do with the external scanner, were there any breaking changes that happened around that?

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.6

### Operating system/version

linux

**Comment by ahelwer** [comment]
Further experimentation shows this is almost certainly due to the test file suffix feature; quoting https://tree-sitter.github.io/tree-sitter/creating-parsers#command-test

>If your language’s syntax conflicts with the === and --- test separators, you can optionally add an arbitrary identical suffix (in the below example, |||) to disambiguate them

As far as I know the TLA+ parser is the only one using this feature. The test file parser seemingly fails to find the terminating `----|||` test input marker.

**Comment by ahelwer** [comment]
Bisecting, I found the commit introducing the bug is 33045ee89803448700f7590cf427a1c3a3802d14 by @amaanq.

**Comment by maxbrunsfeld** [comment]
Thanks for the report and for investigating @ahelwer
