### ISSUE TITLE
lua binding request

### ISSUE THREAD

**Issue by yafacex** [tree-sitter/tree-sitter#365]
I am a game developer.use lua a lot.i used lpeg to create rule descript grammers to write game logic before.but to support ide highlight is not convenient.i tried to switch to tree sitter for both ast generation and highlight edit.

**Comment by maxbrunsfeld** [comment]
The Neovim team has made some progress on this: see https://github.com/neovim/neovim/pull/10124. 

@bfredl Do you think it makes sense to extract your Lua Tree-sitter bindings into a standalone library at some point?

**Comment by bfredl** [comment]
Sure. I have tried to keep references to nvim quite minimal in the lua API binding https://github.com/neovim/neovim/blob/ce4d57d1b600907039d7640950714d3cf95d583e/src/nvim/lua/tree_sitter.c
The external connections is mostly (1) use internal vim functions to read from a vim buffer and (2) use libuv wrapper for dlopen() parsers as dynamic libraries.

**Comment by ahlinc** [comment]
For now there is one https://github.com/euclidianAce/ltreesitter and it's mentioned in [Tree-sitter docs](https://tree-sitter.github.io/tree-sitter/#language-bindings).
And Neovim's integration contains useful code: https://github.com/nvim-treesitter/nvim-treesitter/tree/master/lua/nvim-treesitter
