### ISSUE TITLE
"emcc: error: parser.c: No such file or directory" when building WASM with Docker

### ISSUE THREAD

**Issue by joelspadin** [tree-sitter/tree-sitter#3657]
### Problem

On Windows 11, `tree-sitter build --wasm` fails saying it cannot find parser.c, even though a src/parser.c file does exist for the grammar being compiled.

```
> tree-sitter build --wasm node_modules/tree-sitter-devicetree

Unable to find image 'emscripten/emsdk:3.1.64' locally
3.1.64: Pulling from emscripten/emsdk
3713021b0277: Pull complete
c8f28c904a01: Pull complete
848f4f768be5: Pull complete
0e6596f05384: Pull complete
ca01719cbaa8: Pull complete
Digest: sha256:8847dad4171ebc8a53d9ae5cda86a2546ef5b2e68834c14dc1ba2b2962e125cc
Status: Downloaded newer image for emscripten/emsdk:3.1.64
emcc: error: parser.c: No such file or directory ("parser.c" was expected to be an input file, based on the commandline arguments provided)
emcc command failed
```

This is the same error as in #532, which was already fixed, so it looks like this got broken again somehow.

### Steps to reproduce

On Windows, with Docker installed, run
```
npm i -D tree-sitter-cli tree-sitter-devicetree
npx tree-sitter build --wasm node_modules/tree-sitter-devicetree
```

### Expected behavior

It should compile the grammar.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.23.0 (12fb31826b8469cc7b9788e72bceee5af1cf0977)

### Operating system/version

Windows 11 build 22631, Docker 27.1.1

**Comment by clason** [comment]
Did you mean

```
tree-sitter build --wasm -o node_modules/tree-sitter-devicetree
```

**Comment by clason** [comment]
Does it work without `tsx`?

**Comment by joelspadin** [comment]
I am not using `tsx` anywhere? If you mean `npx`, it gives the same error when run from npx and when run as an npm script.
