### ISSUE TITLE
grammar rules graph generation

### ISSUE THREAD

**Issue by cancerberoSgx** [tree-sitter/tree-sitter#366]
Hi, I just created [tree-sitter-grammar-to-dot](https://github.com/cancerberoSgx/univac/tree/master/tree-sitter-grammar-to-dot) that's able to "render" tree-sitter grammar rules to .dot files (https://graphviz.gitlab.io/ graph format). 

This  feature is pretty similar than antlr4 `-atn` argument. Basically for each rule in given grammar json file, it creates a .dot file representing the grammar rule's flow. 

.dot files can be rendered to many formats, but particularly SVG allows to build SYMBOL nodes with hrefs so user can **navigate** through symbols (click the SYMBOLS in the following examples): 

 * [rust.array_expression.svg](https://cancerberosgx.github.io/demos//tree-sitter-grammar-to-dot/rust/rust-grammar.json.array_expression.dot.svg)
 * [javascript.class_body.svg](https://cancerberosgx.github.io/demos//tree-sitter-grammar-to-dot/javascript/javascript-grammar.json.class_body.dot.svg) 

There still things to support: 

 * The rule type is missing is 'PREC' that I still need to understand, but the rest are done.
 * Support / consider other grammar elements beside just rules (?)
 * Probably the graph nodes and edge styles can be improved. 
 * group nodes in clusters / subgraphs (?)

I would like to know your opinion about contributing this project to tree-sitter perhaps, integrate it to tree-sitter-cli. I think it could be useful to enhance grammar documentation. 

The project, virtually, it has no dependencies and the [core is very little](https://github.com/cancerberoSgx/univac/blob/master/tree-sitter-grammar-to-dot/src/buildRule.ts).

Thanks

**Comment by maxbrunsfeld** [comment]
This is a cool project! Thanks for sharing it.

For now, I don't think that I want to take ownership of that code, so I think it's better to keep it as a separate project. If at some point other people besides you (the author) are finding it useful when developing grammars, I think we should add a link to it from the Tree-sitter docs.
