### ISSUE TITLE
TSInput raed function

### ISSUE THREAD

**Issue by vbogretsov** [tree-sitter/tree-sitter#370]
Hello!

I'm trying to provide a source code to a parser via TSInput which has the following function `read`:

```c
static char BUFF[BUFF_SIZE];

static const char* read(
    void*     payload,
    uint32_t  byte_index,
    TSPoint   position,
    uint32_t* bytes_read) {

    *bytes_read = fread(BUFF, sizeof(char), BUFF_SIZE, (FILE*)payload);
    return BUFF;
}
```

When the BUFF_SIZE is big enough to read a file (correct C file) at once, the parser returns a tree without errors, but when BUFF_SIZE is not so big and the `read` function should be called several times, the tree is different and contains error.

*NOTE*: the encoding is TSInputEncodingUTF8.

What is wrong with such `read` function and what are the overall guidelines for such function?

**Comment by bfredl** [comment]
The `position` or `byte_index` argument should be used, it defines what position in the source to read. In this case, seeking the file to `byte_index` byte position would probably help.

**Comment by vbogretsov** [comment]
Thank you!

`fseek` before `fread` solved the issue.

**Comment by jiax1aobo** [comment]
> Thank you!
> 
> `fseek` before `fread` solved the issue.

What is the reference for seek? Is it the current reading position of the file (`SEEK_CUR`) or the beginning of the file (`SEEK_SET`)?

**Comment by amaanq** [comment]
please don't necropost, no one wants notifications from a *5 year old* issue
