### ISSUE TITLE
[Feature Request] Hope playground support more languages.

### ISSUE THREAD

**Issue by liaodalin19903** [tree-sitter/tree-sitter#3715]
### Problem

Hope [tree-sitter/playground](https://tree-sitter.github.io/tree-sitter/playground) support language like below:
```
Objective-C
Swift
Dart
```

**Comment by sogaiu** [comment]
If you don't mind setting something up for yourself, there is some information about how that might be done [here](https://github.com/sogaiu/ts-questions/blob/6e0aac7ac565023bdc571db865c2ea582d6560d7/questions/how-can-a-custom-playground-be-hosted/README.md).

**Comment by amaanq** [comment]
I don't think we want to particularly add grammars that are outside of the upstream org - if we add these grammars, then other people will want us to add other grammars they'd like to see, and so on and so forth. You can always run the playground locally for these grammars.
