### ISSUE TITLE
Tree sitter test result order depends on platform

### ISSUE THREAD

**Issue by razzeee** [tree-sitter/tree-sitter#373]
So it seems running `tree-sitter test` is working differently on windows/macos vs linux.

In windows and macos the categories are ordered alphabetical:
https://ci.appveyor.com/project/Razzeee/tree-sitter-elm/builds/25599909/job/tn1uy8u5oqpurkqw
https://ci.appveyor.com/project/Razzeee/tree-sitter-elm/builds/25599909/job/jvqcokahmm06udtb
https://travis-ci.org/Razzeee/tree-sitter-elm/jobs/551541116

But in linux the don't seem to be ordered by category:

https://travis-ci.org/Razzeee/tree-sitter-elm/jobs/551541117

**Comment by maxbrunsfeld** [comment]
Yeah, I think we run the tests in the order that the OS (via [`std::fs::read_dir`](https://doc.rust-lang.org/std/fs/fn.read_dir.html)) returns the entries. We should probably sort them alphabetically manually.

**Comment by Razzeee** [comment]
I think https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/test.rs#L344 is the relevant one. But it seems like we need to rewrite the part. https://stackoverflow.com/a/40022060/2859813 suggests, that we need to push to a `Vec` first and I'm not sure how to do that and keep the wanted recursive nature.
