### ISSUE TITLE
`nextSibling` of ZWT returns 2nd next sibling

### ISSUE THREAD

**Issue by RedCMD** [tree-sitter/tree-sitter#3732]
### Problem

Running `.nextSibling` on a ZWT returns the sibling **after** the immediate next sibling

related: https://github.com/tree-sitter/tree-sitter/pull/3566

### Steps to reproduce

```js


module.exports = grammar({
	name: "nextsibling",
	extras: $ => [ ],

	rules: {
		source: $ => seq(
			'a',
			$._bc,
			'd',
			'e',
			'f',
		),

		_bc: $ => seq(
			'b',
			'c',
		),
	}
});
```

example text: `abdef`

locate the missing node `'c'` and run `node.nextSibling` on it

### Expected behavior

returns the immediate next sibling `'d'`

### Actual:
returns the 2nd next sibling `'e'`

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.24.1

### Operating system/version

Windows 11

**Comment by RedCMD** [comment]
TreeSitter `0.24.4` has reopened this @amaanq 

`node.nextSibling` now returns `null`
`node.previousSibling` returns `null` https://github.com/tree-sitter/tree-sitter/issues/2870
`node.parent` now returns itself

prob caused by https://github.com/tree-sitter/tree-sitter/commit/a498790a8271d18212d24b77c67b66af767e926c

**Comment by amaanq** [comment]
didn't forget about this - do you mind trying out #4097 to see if that fixed it? I would think it should

**Comment by RedCMD** [comment]
I believe it is fixed now
