### ISSUE TITLE
Document what needs to be included in repo to pass the package-npm workflow

### ISSUE THREAD

**Issue by kylegoetz** [tree-sitter/tree-sitter#3736]
### Problem

For my Unison TSG at https://github.com/kylegoetz/tree-sitter-unison I'm using teh package-npm workflow.

Everything succeeds except building for Windows, which spits out (snipped to the relevant part)

```
gyp info spawn args ]

  binding.cc
  parser.c
D:\a\tree-sitter-unison\tree-sitter-unison\src\parser.c(266,22): warning C4[56](https://github.com/kylegoetz/tree-sitter-unison/actions/runs/11174240115/job/31063609643#step:6:57)6: character represented by universal-character-name '\u2200' cannot be represented in the current code page (1252) [D:\a\tree-sitter-unison\tree-sitter-unison\build\tree_sitter_unison_binding.vcxproj]
  win_delay_load_hook.cc
     Creating library D:\a\tree-sitter-unison\tree-sitter-unison\build\Release\tree_sitter_unison_binding.lib and object D:\a\tree-sitter-unison\tree-sitter-unison\build\Release\tree_sitter_unison_binding.exp
parser.obj : error LNK2001: unresolved external symbol tree_sitter_unison_external_scanner_create [D:\a\tree-sitter-unison\tree-sitter-unison\build\tree_sitter_unison_binding.vcxproj]
parser.obj : error LNK2001: unresolved external symbol tree_sitter_unison_external_scanner_destroy [D:\a\tree-sitter-unison\tree-sitter-unison\build\tree_sitter_unison_binding.vcxproj]
parser.obj : error LNK2001: unresolved external symbol tree_sitter_unison_external_scanner_serialize [D:\a\tree-sitter-unison\tree-sitter-unison\build\tree_sitter_unison_binding.vcxproj]
parser.obj : error LNK2001: unresolved external symbol tree_sitter_unison_external_scanner_deserialize [D:\a\tree-sitter-unison\tree-sitter-unison\build\tree_sitter_unison_binding.vcxproj]
parser.obj : error LNK2001: unresolved external symbol tree_sitter_unison_external_scanner_scan [D:\a\tree-sitter-unison\tree-sitter-unison\build\tree_sitter_unison_binding.vcxproj]
D:\a\tree-sitter-unison\tree-sitter-unison\build\Release\tree_sitter_unison_binding.node : fatal error LNK1120: 5 unresolved externals [D:\a\tree-sitter-unison\tree-sitter-unison\build\tree_sitter_unison_binding.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
```

So it doesn't see the external scanner code. However, it's obviously there at the bottom of this file https://github.com/kylegoetz/tree-sitter-unison/blob/master/src/scanner.c

Is there some other thing that has to be configured for Windows builds to work? This process worked for me six months ago last time I implemented a new language feature, but now it's failing, and what's changed is Tree Sitter generated different files I needed to add to my project, so now I'm not sure what has broken things.

In particular, I noticed that package.json was updated by tree-sitter to add a peer dependencies thing, which I notice is the step that is failing `Run npm ci --legacy-peer-deps` but it's only failing for Windows.

### Steps to reproduce

1. have admin rights to my project
2. create new tag
3. push tag to master
4. wait for Workflow to fail

### Expected behavior

I expect the NPM publish workflow to succeed on the Windows step

### Tree-sitter version (tree-sitter --version)

0.22.5

### Operating system/version

macOS 12.0.1

**Comment by clason** [comment]
Have you tried using the latest tree-sitter version?

**Comment by ObserverOfTime** [comment]
Wrong repo, and read the `NOTE:` comments.

**Comment by kylegoetz** [comment]
@ObserverOfTime 

> read the NOTE: comments

where is this "NOTE: comments" that I'm supposed to read? Thanks.

**Comment by ObserverOfTime** [comment]
```sh
grep -Irn NOTE: --exclude-dir=node_modules
```
