### ISSUE TITLE
tree-sitter.pc.in is wrong in the version 0.24.1

### ISSUE THREAD

**Issue by SuChengHao** [tree-sitter/tree-sitter#3744]
### Problem

The short story: tree-sitter.pc.in is wrong, the prefix will be duplicated in the final tree-sitter.pc.

The long story: currently (v0.24.1) the tree-sitter.pc.in is
````
prefix=@CMAKE_INSTALL_PREFIX@
libdir=${prefix}/@CMAKE_INSTALL_LIBDIR@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
````
On my Mac, the generated tree-sitter.pc is
````
prefix=/opt/homebrew/Cellar/tree-sitter/0.24.1
libdir=${prefix}//opt/homebrew/Cellar/tree-sitter/0.24.1/lib
includedir=${prefix}//opt/homebrew/Cellar/tree-sitter/0.24.1/include

Name: tree-sitter
Description: An incremental parsing system for programming tools
URL: https://tree-sitter.github.io/tree-sitter/
Version: 0.24.1
Libs: -L${libdir} -ltree-sitter
Cflags: -I${includedir}
````
So `pkg-config` will output
````
-I/opt/homebrew/Cellar/tree-sitter/0.24.1//opt/homebrew/Cellar/tree-sitter/0.24.1/include -L/opt/homebrew/Cellar/tree-sitter/0.24.1//opt/homebrew/Cellar/tree-sitter/0.24.1/lib -ltree-sitter
````
and break everything

### Steps to reproduce

Just type `pkg-config --cflags --libs tree-sitter`

### Expected behavior

The outputed path should be correct

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.24.1

### Operating system/version

macOS 15.1

**Comment by clason** [comment]
@carlocab you had a similar issue in https://github.com/Homebrew/homebrew-core/pull/192792

**Comment by carlocab** [comment]
Yep, thanks for the ping. Realised this but hadn't gotten around to fixing it properly.

**Comment by carlocab** [comment]
I've opened #3745, but it seems there is an alternative fix at #3743.

**Comment by carlocab** [comment]
I've backported the fix at https://github.com/Homebrew/homebrew-core/pull/192890. You can do `brew update && brew reinstall tree-sitter` to pick it up.

**Comment by clason** [comment]
I would expect a quick 0.24.2 fixup release in the near future.

**Comment by carlocab** [comment]
I thought as much, but I figured it would be better to fix the formula sooner rather than later.
