### ISSUE TITLE
Tree Sitter failing when integrating with Atom

### ISSUE THREAD

**Issue by ncurtislinkeng** [tree-sitter/tree-sitter#377]
I get the following error message when I try to integrate my Tree Sitter parser with Atom:

`Failed to load a tree-sitter-Prolink2 package grammar
A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\n.curtis\github\tree-sitter-lcs\node_modules\tree-sitter-lcs\build\Release\tree_sitter_lcs_binding.node in C:\Users\n.curtis\.atom\packages\tree-sitter-lcs\grammars\lcs.cson`

Does anyone have any idea on why this is happening or how to fix this?

**Comment by maxbrunsfeld** [comment]
I believe you need to run `apm rebuild` in your Atom package directory. For more information, see the Atom documentation about using native modules: https://electronjs.org/docs/tutorial/using-native-node-modules.
