### ISSUE TITLE
Crate licenses not in crates.it

### ISSUE THREAD

**Issue by solomoncyj** [tree-sitter/tree-sitter#3773]
### Problem

 https://crates.io/crates/tree-sitter-language does not contain the LICENSES file

### Steps to reproduce

.

### Expected behavior

.

### Tree-sitter version (tree-sitter --version)

.

### Operating system/version

.

**Comment by ObserverOfTime** [comment]
The license is specified in the metadata.
![image](https://github.com/user-attachments/assets/e28db017-a7a0-4cfd-b5be-7444bfa31ce2)
What do you need the file for?

If the crate needs anything, it's a readme.
