### ISSUE TITLE
Creating a Tree Language to Generate Tree-Sitter Grammars?

### ISSUE THREAD

**Issue by breck7** [tree-sitter/tree-sitter#379]
Aloha,
I am very impressed by continued improvements to the Tree Sitter project. I'm looking for ways to better parse existing languages into a clean structure that I can then work with, and I think down the line I could benefit from Tree Sitter.

I was thinking I might try and write a Tree Language that generates Tree Sitter Javascript grammars. Tree Languages are very simple languages built on top of Tree Notation. Here's a sample grammar/language that generates JSON (http://treenotation.org/sandbox/build/#standard%20dug).

Does anyone have any initial thoughts on whether this would be helpful to folks? Reading the docs "Developing Tree-sitter parsers can have a difficult learning curve, " makes me think that a Tree Language that compiles to Tree-sitter Javascript might be useful. If we had a Tree-Sitter Grammar in Tree Notation, you'd get autocomplete, type checking, syntax highlighting, etc, right out of the gate.

If you have any thoughts before I start coding a prototype, let me know!

-Breck

**Comment by maxbrunsfeld** [comment]
> Reading the docs "Developing Tree-sitter parsers can have a difficult learning curve, " makes me think that a Tree Language that compiles to Tree-sitter Javascript might be useful.

My initial reaction is that I don't think that an alternative grammar DSL would be an improvement. 

Developing parsers can be challenging because you need to understand *conceptual* topics like LR parsers, ambiguity, what kind of grammar structure makes a useful syntax tree, etc. I think the existing surface syntax (based on JavaScript) is one thing that's actually **not** challenging at all for most people. JavaScript is the most widely-spoken programming language in the world.

> If we had a Tree-Sitter Grammar in Tree Notation, you'd get autocomplete, type checking, syntax highlighting, etc, right out of the gate.

I'm not sure I follow this. Wouldn't using a more niche language make syntax highlighting **more** cumbersome for people to configure? The existing DSL already allows syntax highlighting to work in every editor in existence out of the box.

Autocomplete also already works pretty well just based on the simple "words in the buffer" approach. What kind of autocomplete would you want to provide, and how would it be made easier by moving away from JavaScript?

**Comment by maxbrunsfeld** [comment]
Closing this out since I don't think this is something I want to incorporate into this repo. If you're still interested in exploring it, I'm all for it. It could be interesting!

**Comment by breck7** [comment]
Here's a tiny demo. Consider it more "psuedo-code" than actual code, but it might clarify the idea a bit more. Basically, I think we could create a simple DSL that compiles to the current TreeSitter JSON, that might make writing the parsers easier.

http://treenotation.org/sandbox/build/##grammar%0A%20nodeType%20treeSitter%0A%20%20root%0A%20%20inScope%20parser%0A%20%20compilesTo%20js%0A%20nodeType%20parser%0A%20%20firstCellType%20keywordCell%0A%20%20inScope%20rootNode%0A%20%20compiler%0A%20%20%20stringTemplate%20module.exports%20%3D%20grammar(%7B%0A%20%20%20closeChildren%20%7D)%0A%20%20%20joinChildrenWith%20%2C%0A%20cellType%20nameCell%0A%20%20highlightScope%20string%0A%20cellType%20regexCell%0A%20%20highlightScope%20string%0A%20cellType%20keywordCell%0A%20%20highlightScope%20keyword%0A%20cellType%20startCell%0A%20%20extends%20regexCell%0A%20cellType%20captureCell%0A%20%20extends%20regexCell%0A%20cellType%20endCell%0A%20%20extends%20regexCell%0A%20nodeType%20rootNode%0A%20%20firstCellType%20keywordCell%0A%20nodeType%20nameNode%0A%20%20extends%20rootNode%0A%20%20compiler%0A%20%20%20stringTemplate%20name%3A%20%22%7BnameCell%7D%22%0A%20%20match%20name%0A%20%20cells%20nameCell%0A%20%20description%20The%20Name%20of%20your%20Parser.%0A%20nodeType%20rules%0A%20%20extends%20rootNode%0A%20%20catchAllNodeType%20ruleNode%0A%20%20compiler%0A%20%20%20openChildren%20%7B%0A%20%20%20closeChildren%20%7D%0A%20%20%20stringTemplate%20rules%3A%0A%20nodeType%20ruleNode%0A%20%20abstract%0A%20%20firstCellType%20keywordCell%0A%20%20compiler%0A%20%20%20stringTemplate%20%7BkeywordCell%7D%3A%20%24%20%3D%3E%0A%20%20inScope%20match%0A%20nodeType%20match%0A%20%20firstCellType%20keywordCell%0A%20%20cells%20startCell%20captureCell%20endCell%0A%20%20compiler%0A%20%20%20stringTemplate%20seq(%7BstartCell%7D%2C%20%7BcaptureCell%7D%2C%20%7BendCell%7D)%2C%0Asample%0A%20parser%0A%20%20name%20html%0A%20%20rules%0A%20%20%20doctype%0A%20%20%20%20match%20%3C!doctype%20%2F%5B%5E%3E%5D%2B%2F%20%3E

**Comment by maxbrunsfeld** [comment]
I get some JavaScript errors when visiting that URL in chrome:

```
TypeError: Cannot read property '_getConstructorDefinedInGrammar' of undefined
    at GrammarProgram._getRootConstructor (jtree.browser.js:3921)
    at GrammarProgram.getRootConstructor (jtree.browser.js:3925)
    at GrammarIDEApp._getGrammarConstructor (grammarIde.js:187)
    at GrammarIDEApp._codeDidUpdate (grammarIde.js:216)
    at GrammarIDEApp._setGrammarAndCode (grammarIde.js:247)
    at GrammarIDEApp._restoreFromLocalStorage (grammarIde.js:165)
    at GrammarIDEApp.start (grammarIde.js:75)

grammarIde.js:217 Uncaught (in promise) TypeError: programConstructor is not a constructor
    at GrammarIDEApp._codeDidUpdate (grammarIde.js:217)
    at GrammarIDEApp._setGrammarAndCode (grammarIde.js:247)
    at GrammarIDEApp._restoreFromLocalStorage (grammarIde.js:165)
    at GrammarIDEApp.start (grammarIde.js:75)
```

**Comment by breck7** [comment]
Ah, thanks for the report! On my way way to the office, will get some fixes out. Until then, maybe try the link in incognito?

**Comment by breck7** [comment]
Thanks for the report @maxbrunsfeld. I pushed an updated version with tests to hopefully fix that issue. The tool isn't heavily user tested yet so still ironing out the bugs!
