### ISSUE TITLE
CURLY_BRACE_REGEX mangles regex properties

### ISSUE THREAD

**Issue by CAD97** [tree-sitter/tree-sitter#380]
(Side note: the exact intended supported flavor of regex should be made clearer.)

`/\p{XID_Start}/` is mangled into the regex `\p\{XID_Start\}`, which is an invalid regex ([and gives a very poor error message](https://github.com/rust-lang/regex/issues/594)).

The mangling at fault:

https://github.com/tree-sitter/tree-sitter/blob/d274e81d0df44334ec328958defa8631cefa4f35/cli/src/generate/prepare_grammar/expand_tokens.rs#L13-L16
https://github.com/tree-sitter/tree-sitter/blob/d274e81d0df44334ec328958defa8631cefa4f35/cli/src/generate/prepare_grammar/expand_tokens.rs#L48

Blame history:

- e2717a6ad14c6d1db056b55e89526b70eeb48a83: Preprocess regexes to allow non-standard escape sequences
Also allow unescaped curly braces to match literal curly braces when 
they don't form a valid repetition operator.
- b799b46f790ccfee6c3e77f98b9129c0d13a021e: Handle repetition range operators with commas in regexes
- 8c845f29e02763c94b2df0e22ff7536925dda66f: Allow hex characters in unicode code points

To be opinionated, I think that the regex-syntax library has the better behavior here. Definitely, trying to sneak by their filter will lead to unexpected results at best. If regex-syntax offered a "sloppy" mode that tried to parse correctly even in the face of what "strict" mode considers questionable, then I could see using that. But currently, you're changing the regex the user wrote to try to do guess what they meant based on an obviously imperfect regex heuristic.

**Comment by CAD97** [comment]
I agree, @issue-label-bot[bot], this is about 57% a feature request, and 43% a bug. Or maybe more a bug than a feature? In any case, it's in-between the two somewhere. Mis-feature removal request?

**Comment by maxbrunsfeld** [comment]
the idea behind the escaping is to match the behavior of JavaScript regexes. We want that behavior because the main grammar language is a JavaScript DSL.

In JavaScript regexes, curly braces that aren’t part of a valid repetition expression as treated as character literals.

So ‘a{foo}’ is a valid regular expression that just matches one literal string.

The problem here is that property escape sequences like that are not supported at all. I’d like to ad support for them, but I’m not sure when I’ll get around to it.

For right now, we should probably change the regex-processing code to at least acknowledge the existence of property syntax and give an error messsage saying that it isn’t supported.

**Comment by CAD97** [comment]
A switch to use `regex_syntax::Hir` rather than `regex_syntax::Ast`, if possible, will give all of the cool things (e.g. flags, "fancy" classes, class manipulation) for free, as they're partially "compiled" away in the lowering.

Having now [written](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1cd389a89c8e0cd84946496863e2af42) a preprocessing step that I think properly ignores `\\[pPuUx]?`-introduced brackets, I'm convinced ([and burntsushi agrees](https://twitter.com/burntsushi5/status/1148187796609425409)) that doing it via a preprocessing step is doomed to fall into a hundred different pitfalls. The proper path would be to write a new string->`regex_syntax::ast::Ast` parser that behaves like JS regex rather than using the default "strict" one, if that's really desired.

Here's the final regex I _think_ behaves as it would need to:

```regex
(?x) # captures: $1: lookbehind, $2 or $4: close bracket, $3 or $5: content
( ^[^\\\{]?? | \\[^pPuUx] | [^\\][^\\] )               # lookbehind is not \p, \P, \u, \U, \x, \
\{                                                     # followed by a openning bracket
(?: $ | (\}) |                                         # followed by eoi or close bracket, or
    ( (?:\\\}|[^}])*?(?:[^0-9,}]|\\\})(?:\\\}|[^}])*?  # content and
      [^\\] ) (\}) |                                   # a non-escaped close bracket, or
    ( (?:\\\}|[^}])*?(?:[^0-9,}]|\\\})(?:\\\}|[^}])*?)$# content and lacks a close bracket
)
```

> I find this outright [b҉a͡rb̢ari͞c͘](https://stackoverflow.com/a/1732454/1936422).

Avoiding messes like these is why we have proper parsers. I cannot be sure there aren't further edge cases where this regex transformation misbehaves, but [everything I threw at it seemed to behave correctly](https://regex101.com/r/IMh8jC/2).

**Comment by maxbrunsfeld** [comment]
I've added support for unicode property escapes like `/\p{XID_Start}/`, so I'm going to close this one out.

The more general problem that you pointed out still remains, but it's unclear to me how much it matters in practice. Let me know if you think there are other important cases that do have practical consequences.

I think it's definitely an option to simply remove the preprocessing; it'll be a minor breaking change for some grammars, but it'll be an easy thing to fix.

**Comment by CAD97** [comment]
`\P` is a lot less common, but probably not unreasonable to support now that `\p` is supported (as it's just the negation). `\u` and `\U` probably should be supported.

I still stand by my assertion that using regex to preprocess regex is fraught with peril and better avoided. The error messages referring to the mangled regex rather than the one the user wrote is not helpful when errors do happen.

But maybe I'll take another look at tree-sitter now that it supports unicode property character sets 😄

**Comment by maxbrunsfeld** [comment]
Ah yeah, thanks for the reminder about `\P`. I pushed up a fix for that.

I think `\u` already works because it already only contains hexadecimal digits within the curly braces. I actually don't know what `\U` is.

**Comment by CAD97** [comment]
`\u` has two forms: `\u{XXXXXX}` (any hex character code) and `\uXXXX` (exactly four digits). `\U` is the same (supports braces) but takes exactly eight digits in the unbracketed form (`\UXXXXXXXX`). Like how `\x` takes exactly two unbracketed hex digits.

Here's the regex crate's reference: https://docs.rs/regex/1.4.3/regex/#escape-sequences

**Comment by maxbrunsfeld** [comment]
Ok, that makes sense. I think all of those features work.
