### ISSUE TITLE
Reduce Size of Terminal Nodes

### ISSUE THREAD

**Issue by nordlow** [tree-sitter/tree-sitter#3801]
### Terminal Node Packing

Would it be possible to reduce memory usage of terminal (leaf) nodes as they don't need to store any child pointers?

If so can you give me guidance on where to inject such branching other than  in

```c
ts_node_new(const TSTree *tree, const Subtree *subtree, Length position, TSSymbol alias, bool is_terminal);
```

. Searching for leaf I get the hit

```c
bool is_leaf = ts_subtree_child_count(lookahead) == 0;
```

.

**Comment by amaanq** [comment]
Leaf nodes are already crammed into 8-byte "inline" (lives on the stack) nodes that look like [this](https://github.com/tree-sitter/tree-sitter/blob/ac37e60559cf1c8e778a34dd594787076ebe49b1/lib/src/subtree.h#L93), so long as it's [possible to inline](https://github.com/tree-sitter/tree-sitter/blob/ac37e60559cf1c8e778a34dd594787076ebe49b1/lib/src/subtree.c#L155)

**Comment by nordlow** [comment]
Thank you.
