### ISSUE TITLE
Support callbacks that return String instead of slice in Rust binding

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#386]
I'm writing a dynamic module for Emacs that exposes tree-sitter functionalities.

A dynamic module in Emacs can only access a buffer's text through `String` copies (of sub-ranges). It cannot access the internal data structure through `&[u8]`.

Can we add a new parse function to support this use case?

**Comment by ubolonton** [comment]
I made a prototype using a new `Input` trait [here](https://github.com/tree-sitter/tree-sitter/compare/master...ubolonton:rust-binding).

**Comment by maxbrunsfeld** [comment]
Hey, sorry for the slow turnaround. I've generalized `parse_with` and `parse_utf16_with` to take anything implementing `AsRef`.

**Comment by ubolonton** [comment]
Cool, thanks!
