### ISSUE TITLE
Consider adding backwards compatibility to tree-sitter-loader for loading older grammars where the metadata is in package.json

### ISSUE THREAD

**Issue by segevfiner** [tree-sitter/tree-sitter#3875]
### Problem

Currently if you upgrade to tree-sitter-cli>=0.24, all your grammars have to be migrated to have their metadata in `tree-sitter.json`. This is inconvenient to say the least, it would be nicer if tree-sitter-loader had backwards compatibility in-place to load such grammars.

### Expected behavior

tree-sitter-cli>=0.24 should be able to load older grammars as well

**Comment by ObserverOfTime** [comment]
I believe #3816 is what you need.
