### ISSUE TITLE
Bad error message for nonexistent nodes that aren't of the form [a-zA-Z0-9_-]+

### ISSUE THREAD

**Issue by ribru17** [tree-sitter/tree-sitter#3892]
### Problem

E.g. for an anonymous node `">"` that does not exist, the error will appear as:

```
Invalid node type ""
```

It should be

```
Invalid node type ">"
```

as with other anonymous (or named) nodes.

Problematic code is here:

https://github.com/tree-sitter/tree-sitter/blob/0f15779863131bbe9e8ae2e4d09348e9e5e70542/lib/binding_rust/lib.rs#L2357

### Steps to reproduce

Try to parse any query with a nonexistent non alphanumeric (or -, _) node name, e.g. something like

```scheme
"&^^%%$" @capture
```

### Expected behavior

Error messages should display incorrect node text, even if it is not alphanumeric/hyphen/underscore.

### Tree-sitter version (tree-sitter --version)

0.24.3

### Operating system/version

NixOS, linux kernel 6.11.0

**Comment by clason** [comment]
Note: This happens with the C lib, too (Neovim). I feel this is a regression but haven't had the time to bisect.
