### ISSUE TITLE
Incorrect indentation in JS if function formatted in specific way

### ISSUE THREAD

**Issue by tomaszferens** [tree-sitter/tree-sitter#3899]
### Problem

When I press `o` to create a new line, the new line is incorrectly indented:

```js
export const DoSomeVeryFancyLogicHere = function DoSomeVeryFancyLogicHere(
  props,
) {
  console.log("Hello, world!");
    // here is my new line
};
```

I noticed that it only happens when function is formatted in this specific format.

I'm using **prettier** for the default formatting.

### Steps to reproduce

1. Create dummy JS file
2. Paste the following content:
```js
export const DoSomeVeryFancyLogicHere = function DoSomeVeryFancyLogicHere(
  props,
) {
  console.log("Hello, world!");
};
```
3. Hover over the console.log line and press `o` to create new line
4. The new line is incorrectly indented (4 spaces instead of 2)

### Expected behavior

It should be indented correctly:

```js
export const DoSomeVeryFancyLogicHere = function DoSomeVeryFancyLogicHere(
  props,
) {
  console.log("Hello, world!");
  // here is my new line
};
```

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.22.6

### Operating system/version

macOS Sonoma 14.1

**Comment by amaanq** [comment]
wrong repo, file the issue with your editor.
