### ISSUE TITLE
Add a `$schema` property to generated `tree-sitter.json` files

### ISSUE THREAD

**Issue by Julian** [tree-sitter/tree-sitter#3903]
### Problem

When the `tree-sitter.json` file was proposed (in #3637) the comment has a (collapsed) [JSON Schema](https://json-schema.org/) which contains the expected schema of this file.

### Expected behavior

It would be useful for the pre-generated `tree-sitter.json` generated by `tree-sitter init` to include a [`$schema` property so that editors can automatically show completion and documentation when editing the file](https://code.visualstudio.com/Docs/languages/json#_json-schemas-and-settings).

Thanks!

**Comment by amaanq** [comment]
It does live here - https://tree-sitter.github.io/tree-sitter/assets/schemas/config.schema.json, which comes from the file [here](https://github.com/tree-sitter/tree-sitter/blob/master/docs/assets/schemas/config.schema.json). Though, we don't specify that at the top of the json file, PR welcome to update that

**Comment by Julian** [comment]
Aha! Thanks, somehow a search didn't find it, I guess because that's from another repo. OK, editing the title at least.
