### ISSUE TITLE
Please add to tree-sitter headers information about ABI version and/or Tree-sitter version

### ISSUE THREAD

**Issue by Eli-Zaretskii** [tree-sitter/tree-sitter#3925]
### Problem

Tree-sitter currently doesn't have any information in the header files it installs that allows applications to know which ABI to support and which version of shared library to load. However, the ABI sometimes changes in incompatible ways, which require an application which was compiled against a particular version of library headers to load at run time only the shared libraries which are compatible with those headers. Otherwise the application risks crashing due to ABI incompatibilities.

A case in point is Emacs built with tree-sitter support for MS-Windows. Emacs on Windows loads tree-sitter dynamically, at run time, and only when the tree-sitter functionality is first required. This allows users who don't us tree-sitter supported features to avoid installing the tree-sitter library on their systems. However, to find the library and load it, Emacs needs to know its name. The two names used currently are tree-sitter.dll and tree-sitter-0.dll. Crucially, they are both fixed, with no version information in the names. This means that upgrading the tree-sitter installation overwrites the previous library, and if the new library is ABI-incompatible with the old one, the programs which were compiled against the old version need to be recompiled, or will risk crashing.

This is in stark contrast to other libraries, which change their names when the ABI is changed in incompatible ways, and also have the version symbols defined in the headers. This allows an application which was built against version X.Y of a library to know in advance that it must load only libSOMETHING-X.dll, and reject any other libSOMETHING DLLs. For Emacs, you can see in the file w32-win.el in the Emacs source tree the data structure which allows Emacs to know, for example, that if it was compiled with giflib 5.x needs to look for libgif-7.dll, and will refuse to load libgif-6.dll.

There's nothing like that available with tree-sitter. It is simple to name the shared tree-sitter library libtree-sitter-0.24.4.dll (and similar for other versions), but since the library version is not available in the headers, the application will not be able to know that it needs to look for a library under that name, and for it alone.

(Actually, since the ABI is changed in incompatible ways relatively rarely, it would be better to have in the headers and in the Makefile the ABI version number, in which case the library could be named libtree-sitter-N.dll and the application would know to look for it because the version N is available in the header files. As things stand now, I couldn't even find which tree-sitter versions changed the ABI; the only exception is the known ABI breakage in 0.22.6, but I don't know how to verify that no further changes happened later.)

I'm therefore asking to add to the tree-sitter headers the ABI number or at least the library version number.

Thank you.

### Expected behavior

Addition of ABI or library version number will allow a program linked against tree-sitter to know which shared libraries to load at run time. That will allow to have on the same system older versions of the same program which were linked against older versions of tree-sitter, and safely run both old and new versions from the same directory tree.

**Comment by clason** [comment]
https://github.com/tree-sitter/tree-sitter/blob/18e4a2405b52ecd3cb9aefdd05d6554e76823473/lib/include/tree_sitter/api.h#L29

**Comment by clason** [comment]
The issue with the versioned soname is an issue you have to bring up with whoever builds and packages tree-sitter for you; the makefiles in this repo _do_ build versioned sonames.

**Comment by Eli-Zaretskii** [comment]
> The issue with the versioned soname is an issue you have to bring up with whoever builds and packages tree-sitter for you; the makefiles in this repo _do_ build versioned sonames.

My main request is not about the versioned soname: I can do that myself. My request is to add some version information to the header files installed by tree-sitter, so that the application could then be taught which soname to look for. Just producing a versioned soname without any way for the application to know which soname to look for doesn't solve the issue.

**Comment by Eli-Zaretskii** [comment]
> https://github.com/tree-sitter/tree-sitter/blob/18e4a2405b52ecd3cb9aefdd05d6554e76823473/lib/include/tree_sitter/api.h#L29

That's a language version, not the ABI version of the tree-sitter library itself, at least AFAIU.

Or are you saying that whenever the ABI of the library changes in incompatible ways, TREE_SITTER_LANGUAGE_VERSION is also bumped? It looks like this is not the case: e.g., the library version was bumped to 0.22.6 in May 2024, whereas TREE_SITTER_LANGUAGE_VERSION was bumped from 14 to 15 only in October 2024.

**Comment by Eli-Zaretskii** [comment]
> Yes, that's what I was saying. There were mistakes made in the past, but that doesn't change the fact that the ABI is versioned. And header changes need not be incompatible (API != ABI).

If TREE_SITTER_LANGUAGE_VERSION should always be bumped each time there are incompatible ABI changes in the tree-sitter changes, then that's good enough, thanks.

**Comment by ObserverOfTime** [comment]
It should.
