### ISSUE TITLE
What are supertypes?

### ISSUE THREAD

**Issue by rjmholt** [tree-sitter/tree-sitter#393]
I've been reading through some of the implemented grammars (in particular JavaScript) and noticed that is has a `supertypes` field which I didn't see [here](https://tree-sitter.github.io/tree-sitter/creating-parsers#the-grammar-dsl). What does that mean?

**Comment by ayazhafiz** [comment]
`supertypes` appear to broadly represent a group of semantic node subtypes (see [generate/node_types](https://github.com/tree-sitter/tree-sitter/blob/4151a428ec9059b70f3a7beecba8384b649eb621/cli/src/generate/node_types.rs#L312-L321)).
My guess is that in the JavaScript grammar, the [`$._expression` supertype](https://github.com/tree-sitter/tree-sitter-javascript/blob/a730b5c210904e2e3c1f601125a059fde1b35850/grammar.js#L43) may represent e.g. an entire expression like `1 + 2`, which has multiple subexpression types (two [`number`](https://github.com/tree-sitter/tree-sitter-javascript/blob/a730b5c210904e2e3c1f601125a059fde1b35850/grammar.js#L883)s, which are [`_constructable_expression`](https://github.com/tree-sitter/tree-sitter-javascript/blob/a730b5c210904e2e3c1f601125a059fde1b35850/grammar.js#L638)s, and a [`unary_expression`](https://github.com/tree-sitter/tree-sitter-javascript/blob/a730b5c210904e2e3c1f601125a059fde1b35850/grammar.js#L767)).

I may be wrong though :)

**Comment by maxbrunsfeld** [comment]
Finally pushed up some docs: http://tree-sitter.github.io/tree-sitter/using-parsers#static-node-types. Let me know if you think there's anything you think is unclear or should be added.

**Comment by Razzeee** [comment]
So using this would rely on us copying the `json` file to our build and then parsing that file on our own? Are you aware of anybody/project having implemented type inference in something javascript compatible?

**Comment by maxbrunsfeld** [comment]
Yeah the docs mention that it's being used in Haskell right now. The node's binding actually [uses it](https://github.com/tree-sitter/node-tree-sitter/blob/a6631070b3f94e3f1f116a1231049dfec2a70ef1/index.js#L433-L484) to define node subclasses with getter methods as well.

**Comment by Razzeee** [comment]
I'm struggling to understand what your saying, that's not type inference right?

**Comment by Razzeee** [comment]
I think I interpreted the docs wrong when I thought this might easily create a "type inference"-implementation.

**Comment by laxsjo** [comment]
> Finally pushed up some docs: http://tree-sitter.github.io/tree-sitter/using-parsers#static-node-types. Let me know if you think there's anything you think is unclear or should be added.

For anyone stumbling accross this Issue, this section was moved to a new URL:
https://tree-sitter.github.io/tree-sitter/using-parsers/6-static-node-types.html#supertype-nodes
