### ISSUE TITLE
v0.24.4 causes Neovim to freeze in some configurations

### ISSUE THREAD

**Issue by carlocab** [tree-sitter/tree-sitter#3930]
### Problem

When Neovim is used with the [nvim-treesitter-refactor](https://github.com/nvim-treesitter/nvim-treesitter-refactor) plugin and `highlight_current_scope` is enabled, Neovim can freeze when deleting text. This does not happen with v0.24.3.

See neovim/neovim#31163.

### Steps to reproduce

Steps are outlined in neovim/neovim#31163.

As a summary, run:
```sh
cd "$(mktemp -d)"
if [ "$(uname -s)" = Darwin ]; then
  download_url="https://github.com/neovim/neovim/releases/download/nightly/nvim-macos-$(uname -m).tar.gz"
else
  download_url=https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
fi

curl -L "${download_url}" | tar xz
nvim-*/bin/nvim -u minimal.lua minimal.lua # see below for minimal.lua
```
Then, after `nvim` has started, press `15gg` and then `dd`.

And `minimal.lua`:
```lua
for name, url in pairs {
  ['nvim-treesitter'] = 'https://github.com/nvim-treesitter/nvim-treesitter.git',
  ['nvim-treesitter-refactor'] = 'https://github.com/nvim-treesitter/nvim-treesitter-refactor.git',
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require'nvim-treesitter.configs'.setup {
  ensure_installed = { "cpp", },
  refactor = {
    highlight_current_scope = { enable = true },
  },
}
```

### Expected behavior

tree-sitter should not cause Neovim to freeze.

### Tree-sitter version (tree-sitter --version)

0.24.4

### Operating system/version

macOS 15.1

**Comment by carlocab** [comment]
I'll try to dig more into what's happening on the tree-sitter side to hopefully come up with a smaller reproduction soon.

**Comment by clason** [comment]
bisected to https://github.com/tree-sitter/tree-sitter/commit/a498790a8271d18212d24b77c67b66af767e926c @amaanq 

(Same issue on `master`, so not a faulty cherry-pick.)

**Comment by vanaigr** [comment]
I couldn't reproduce the issue, but can it be because `ts_node_parent()` calls `ts_node_child_containing_descendant()` and checks for null:

https://github.com/tree-sitter/tree-sitter/blob/a498790a8271d18212d24b77c67b66af767e926c/lib/src/node.c#L532-L543

but `ts_node_child_containing_descendant()` returns a node instead of null in some cases:

https://github.com/tree-sitter/tree-sitter/blob/a498790a8271d18212d24b77c67b66af767e926c/lib/src/node.c#L566-L568

**Comment by clason** [comment]
@carlocab can you test https://github.com/tree-sitter/tree-sitter/pull/3898? This fixes the hang for me.

**Comment by carlocab** [comment]
Tested #3898, also fixes it. Thanks!

**Comment by carlocab** [comment]
> I couldn't reproduce the issue

@vanaigr, where and how did you try to reproduce it? Because I can reproduce this on a Linux machine too.

**Comment by vanaigr** [comment]
> > I couldn't reproduce the issue
> 
> @vanaigr, where and how did you try to reproduce it? Because I can reproduce this on a Linux machine too.

In WSL.

```console
git checkout 7906532e08
make
VIMRUNTIME=runtime ./build/bin/nvim --clean -u minimal.lua test.cc
```

and then
```
6gg
dd
```

which deletes the `  cout << "hello, world!" << '\n';` line and doesn't freeze the editor.
