### ISSUE TITLE
Should Makefile install queries?

### ISSUE THREAD

**Issue by mavit** [tree-sitter/tree-sitter#3931]
### Problem

The Makefile created by `tree-sitter generate` does nothing with the `queries/*.scm` files.  However, my understanding is that these files are likely to be wanted for common use-cases such as syntax highlighting?

I notice that this is in contrast to the Python and Rust bindings, which both include them.

### Expected behavior

Perhaps these files could be installed to, say, `/usr/share/tree-sitter/LANG/queries/`.

**Comment by mavit** [comment]
(Prompted by https://rt.cpan.org/Ticket/Display.html?id=156984)

**Comment by ObserverOfTime** [comment]
> However, my understanding is that these files are likely to be wanted for common use-cases such as syntax highlighting?

Not by editors. They have their own.
