### ISSUE TITLE
Version Command doesn't seem to exist?

### ISSUE THREAD

**Issue by FourierTransformer** [tree-sitter/tree-sitter#3935]
### Problem

I was trying to use the version [command](https://tree-sitter.github.io/tree-sitter/creating-parsers#command-version) to update the version in the various files, but it doesn't seem to exist?

I tried installing the latest version via npm and via cargo, but no luck either way. Is it just too new a command that hasn't been released yet?

### Steps to reproduce

I tried the command as per the docs:

```terminal
$ tree-sitter version 0.1.0
error: unrecognized subcommand 'version'

Usage: tree-sitter <COMMAND>
```

It's also not listed under help

```terminal
$ tree-sitter --help
tree-sitter 0.24.4
Max Brunsfeld <maxbrunsfeld@gmail.com>
Generates and tests parsers

Usage: tree-sitter <COMMAND>

Commands:
  init-config     Generate a default config file
  init            Initialize a grammar repository
  generate        Generate a parser
  build           Compile a parser
  parse           Parse files
  test            Run a parser's tests
  fuzz            Fuzz a parser
  query           Search files using a syntax tree query
  highlight       Highlight a file
  tags            Generate a list of tags
  playground      Start local playground for a parser in the browser
  dump-languages  Print info about all known language parsers
  complete        Generate shell completions

Options:
  -h, --help     Print help
  -V, --version  Print version
```

### Expected behavior

The command exists and updates the json, cargo, Makefile, etc files.

### Tree-sitter version (tree-sitter --version)

tree-sitter 0.24.4

### Operating system/version

Ubuntu 22.04 LTS

**Comment by sogaiu** [comment]
It may be that it's [only available on the master branch](https://github.com/tree-sitter/tree-sitter/pull/3786) and not yet on the [release-0.24 branch](https://github.com/tree-sitter/tree-sitter/commits/release-0.24/).

**Comment by clason** [comment]
Yes, features are not backported to the release branch, only bugfixes. (In theory.)
