### ISSUE TITLE
How to use a parser in rust?

### ISSUE THREAD

**Issue by kedashoe** [tree-sitter/tree-sitter#395]
Hello, just started playing around with tree-sitter, so neat!

I've written a toy parser and I'm able to use it from node, thanks mostly to https://gist.github.com/Aerijo/df27228d70c633e088b0591b8857eeef (and some other articles which I can't currently find). However I cannot figure out how to build the parser for rust. I'm aware of https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_rust, but everything I've tried to build the parser and import it has failed. I'm running linux, fwiw.

Thanks in advance for any help!

**Comment by Razzeee** [comment]
Did you try to get it from npm? https://www.npmjs.com/package/tree-sitter-rust

This is how I did it, before I switched to the wasm version https://github.com/elm-tooling/elm-language-server/blob/1.1.1/src/util/rebuilder.ts

**Comment by kedashoe** [comment]
Hi @Razzeee , thank you for the reply. I think I did not phrase my question very well.. I'm not trying to use the rust tree sitter parser, but rather use my own grammar in another rust app.

I've created a repo to demonstrate:

https://github.com/kedashoe/tree-sitter-example-apps

I've created a (riveting) grammar [here](https://github.com/kedashoe/tree-sitter-example-apps/blob/e67ec525b6e45a90c3301bc404ddab516a172a4c/tree-sitter-hello/grammar.js)

[Here](https://github.com/kedashoe/tree-sitter-example-apps/blob/e67ec525b6e45a90c3301bc404ddab516a172a4c/tree-sitter-hello/bin/build-nodejs) is how we can build a parser from this grammar to prepare it to be used from another nodejs app.

From our app, we can now follow [these](https://github.com/kedashoe/tree-sitter-example-apps/blob/e67ec525b6e45a90c3301bc404ddab516a172a4c/hello-app-nodejs/README.md) instructions to import and use our parser.

Great! So now, how do we create a similar *rust* app that uses our grammar? In particular

1. What do we do [here](https://github.com/kedashoe/tree-sitter-example-apps/blob/e67ec525b6e45a90c3301bc404ddab516a172a4c/tree-sitter-hello/bin/build-rust#L5) to build a parser for rust?
2. What instructions go [here](https://github.com/kedashoe/tree-sitter-example-apps/blob/e67ec525b6e45a90c3301bc404ddab516a172a4c/hello-app-rust/README.md) to import the parser we created in step 1 and build a rust app using it?

**Comment by fkohlgrueber** [comment]
I created a small example that shows how to use tree-sitter's rust binding with a grammar (I chose json but using something else should be straight-forward). You can find the code here:

[https://github.com/fkohlgrueber/tree-sitter-example-rust](https://github.com/fkohlgrueber/tree-sitter-example-rust)

Does this help?

**Comment by kedashoe** [comment]
> Does this help?

Yes! Thanks a million @fkohlgrueber . On vacation so don't have time to properly play around with it but was able to get my example app to build using your work.
