### ISSUE TITLE
Indentation rules, javascript (and possibly more)

### ISSUE THREAD

**Issue by mariusk** [tree-sitter/tree-sitter#3950]
### Problem

I'm strugging to get "proper" indentation with javascript, e.g.
```javascript
function f(a,
  b) {
....someFunc();
```
or:
```javascript
if (clause1
  && clause2) {
....callSomeFunc();
```
Is there any way I can get TWO dots instead of FOUR (dots representing indentation spaces)?

These things used to be simple to customize earlier, but after tree-sitteer I'm having trouble finding ways of customizing this to my preference. Or docs on what needs to be done.

**Comment by clason** [comment]
I don't know the context (as you don't provide any, at all), but you're probably posting this in the wrong repo.

**Comment by mariusk** [comment]
Oh sorry, I probably wrongly assumed this was Emacs tree-sitter. I'm using Emacs `js-ts-mode`. Any idea what the right repo could be?

**Comment by clason** [comment]
Emacs itself. (This is the upstream tree-sitter library, which does not handle indentation.)

**Comment by sogaiu** [comment]
FWIW, there may not be a repository where meaningful discussion can take place (happy to be corrected on that account).

There are some "places" people discuss Emacs though.

The following are some (not comprehensive):

* https://www.reddit.com/r/emacs/
* https://lists.gnu.org/mailman/listinfo/help-gnu-emacs
* There is at least one matrix room (though I've only briefly glanced at it)
