### ISSUE TITLE
Assertion failed error with web-tree-sitter

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#398]
I'm getting this, when trying to parse or access a tree after this error happened https://github.com/tree-sitter/tree-sitter/issues/394

So it might be a follow up error. Feel free to close this.

```
Assertion failed: self.ptr->ref_count > 0, at: lib/src/./subtree.c,527,ts_subtree_retain
Assertion failed: self.ptr->ref_count > 0, at: lib/src/./subtree.c,527,ts_subtree_retain
abort("Assertion failed: self.ptr->ref_count > 0, at: lib/src/./subtree.c,527,ts_subtree_retain"). Build with -s ASSERTIONS=1 for more info.
abort("Assertion failed: self.ptr->ref_count > 0, at: lib/src/./subtree.c,527,ts_subtree_retain"). Build with -s ASSERTIONS=1 for more info.

c:\Users\John\.vscode\extensions\elmtooling.elm-ls-vscode-0.4.1\server\node_modules\web-tree-sitter\tree-sitter.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r=!1,a=!1,i=!1;r="object"==typeof window,a="function"==typeof importScripts,i="object"==typeof process&&"function"==typeof require&&!r&&!a,n=!r&&!i&&!a;var o,l,u="";i?(u=__dirname+"/",Module.read=function shell_read(e,t){var n;return o||(o=require("fs")),l||(l=require("path")),e=l.normalize(e),n=o.readFileSync(e),t?n:n.toString()},Module.readBinary=function readB
abort("abort(\"Assertion failed: self.ptr->ref_count > 0, at: lib/src/./subtree.c,527,ts_subtree_retain\"). Build with -s ASSERTIONS=1 for more info."). Build with -s ASSERTIONS=1 for more info.
```

**Comment by maxbrunsfeld** [comment]
This may be fixed in web-tree-sitter 0.15.9, but I'm not sure.

**Comment by Razzeee** [comment]
This can still happen, at least I've seen it today with the newest version. Will try to collect more data, seemed to be connected to not being able to load a text file, but I'm not seeing how that would affect the parser. (just writing this to remember)

**Comment by maxbrunsfeld** [comment]
Yeah, it'd be great to get a minimal example for this one.

**Comment by Razzeee** [comment]
Might take until this weekend, till I can take a look.

**Comment by georgewfraser** [comment]
I am also seeing this. Is there an alternative way to build web-tree-sitter to get a more detailed error message?

**Comment by maxbrunsfeld** [comment]
First thought - are you sure that you’re not using a Parser or a Tree or a TreeCursor after it has been deleted?

If so, I’d love to fix this but would need some fairly minimal reproduction script.

**Comment by Razzeee** [comment]
I can't figure out how to reproduce, so I would be willing to close this for now.

**Comment by georgewfraser** [comment]
It would be nice if it were possible to just get a more descriptive error message. I'm not an expert on WASM, maybe this is impossible, but that would help a lot in diagnosing this intermittent error.

**Comment by maxbrunsfeld** [comment]
If you're seeing the same thing that @Razzeee is seeing (`Assertion failed: self.ptr->ref_count > 0, at: lib/src/./subtree.c,527`) then I think that is the most description that exists.

I'd love to help fix this, so I don't think we should necessarily close it out. Maybe someone will be able to specify steps to reproduce it.

**Comment by maxbrunsfeld** [comment]
Is anyone still seeing this with the latest `web-tree-sitter`?

**Comment by georgewfraser** [comment]
I am still seeing this, specifically on windows. I will try to make a repro for you.

**Comment by Razzeee** [comment]
@georgewfraser any news on this?

**Comment by georgewfraser** [comment]
I'm no longer using tree-sitter. The VSCode language server support for syntax coloring has improved, and that is a better solution for improving syntax coloring for VSCode.
