### ISSUE TITLE
Document set!, is?, is-not?

### ISSUE THREAD

**Issue by mwhitworth** [tree-sitter/tree-sitter#3985]
### Problem

Since the Rust bindings support these operators (https://github.com/tree-sitter/tree-sitter/blob/8588c966917a7ced61f4ec3c9e00e6e50567a1fb/lib/binding_rust/lib.rs#L2580), it may be useful to describe this functionality in [the documentation](https://tree-sitter.github.io/tree-sitter/using-parsers#query-syntax). It's not clear to me if these operators are canonical though.

**Comment by amaanq** [comment]
Closed by #4032, forgot to link it in the PR. Though tbh, these directives and predicates are seldom used, with locals being kinda dead
