### ISSUE TITLE
Help with setting up an injection

### ISSUE THREAD

**Issue by ncurtislinkeng** [tree-sitter/tree-sitter#399]
I want to inject XML highlighting into my grammar, but the guide in the flight guide on how to do this is not very clear. Could someone give me some pointers?

**Comment by maxbrunsfeld** [comment]
I assume that you're talking about syntax highlighting in Atom. Can you open an issue on the [atom repo](https://github.com/atom/atom)? You'll need to add a lot more detail to your question. For example, what specific questions do you have? And which paragraphs to do you find unclear, and why? Good luck!
