### ISSUE TITLE
Error message regarding "word token" is a bit confusing, could be improved

### ISSUE THREAD

**Issue by kylegoetz** [tree-sitter/tree-sitter#3991]
### Problem

The following error message caused confusion on Discord today:

`Non-terminal symbol 'identifier' cannot be used as the word token`

Two users with Tree Sitter experience interpreted this as being about the use of `token` (i.e., `the word "token"`) as opposed to the use of the property `word` (i.e., `the "word" token`)

I suggest (drawing on my previous experience as an editor) that this be clarified by adding quotation marks around "word" to make it clear the issue is with a token having value `word` as opposed to a word having value `token`.

### Steps to reproduce

Unnecessary, as it's a rule of English punctuation.

### Expected behavior

I expect "word" to be in quotation marks.

### Tree-sitter version (tree-sitter --version)

0.24.3

### Operating system/version

macOS 15

**Comment by amaanq** [comment]
I would like to say, that because the error message stemmed from the word token being used as the start rule in the scenario that spurred this issue, this can be closed out as #4028 addresses the lack of documentation regarding how the start rule of a grammar is defined.
