### ISSUE TITLE
tree-sitter init email parsing behavior should change

### ISSUE THREAD

**Issue by kylegoetz** [tree-sitter/tree-sitter#3994]
### Problem

The current email parsing just warns the user if the email address entered during initialization is invalid. It doesn't explain why.

Furthermore, the current email validator requires two things: at least one `@` and a `.`. That's the whole validation scheme.

This technically produces false negatives. The RFC specification for email addresses requires the domain part to be a dot-separated list of DNS labels **or an IPv4 or IPv6 address** surrounded by brackets.

As such, a domain name like `jsmith@[IPv6:2001:db8::1]`, which contains no dots, is a valid email address that would be rejected by `tree-sitter init`.

### Steps to reproduce

`tree-sitter init`

for email address, input jsmith@[IPv6:2001:db8::1] (which is a valid email address)

### Expected behavior

Personally, because email validation is very complex, I would recommend not attempting any attempt to validate email addresses: if the validator isn't correct, to what end does one exist in the codebase?

But if we were to keep email validation, then I recommend getting rid of the dot requirement (because it's incorrect validation), keeping the @ requirement, and then updating the error message to mention that an `@` is required (so the user knows exactly what they did wrong).

Technically the `@` isn't even required, but without one, the address is assumed to be local, which makes no sense for any publicly-available package (although internal grammars for companies conceivably could be local-only).

For reference, here are some developers who have written about why one should not bother trying to validate email addresses (unless you're writing an email server):

* https://blog.sinjakli.co.uk/2011/02/13/email-address-validation-please-stop/
* https://davidcel.is/articles/stop-validating-email-addresses-with-regex/ (recommending only look for the `@`)
* https://news.ycombinator.com/item?id=11414749 (HackerNews discussion about why one shouldn't bother parsing email addresses with links to a few blogs written by participants in the discussion)

### Tree-sitter version (tree-sitter --version)

0.24.3

### Operating system/version

macOS 15.0.1

**Comment by kylegoetz** [comment]
I'm willing to do a PR for this if this is a desired fix.

**Comment by ObserverOfTime** [comment]
I'm OK with removing the validation.

**Comment by kylegoetz** [comment]
ok @ObserverOfTime I'll do a PR removing the validation soon (today or tomorrow?). Another option if you wanted it back could be to make it fancier, like have a few sanity checks that still can be overridden. Something like

"I see you didn't put an @ in the email address. Are you sure? Y/n"

But thinking about which checks you'd want (no @, no ., "gmal.com" -- did you mean "gmail.com"?, etc.) is a longer discussion.
