### ISSUE TITLE
Using tree-sitter within wasm client-side web app

### ISSUE THREAD

**Issue by fkohlgrueber** [tree-sitter/tree-sitter#400]
I'd like to use tree-sitter in a client-side web app I'm building in Rust using [Yew](https://github.com/DenisKolodin/yew). I tried a couple of things, but I can't make it work.

I think I could probably use js to glue the yew app and the js binding of tree-sitter together, but I'm wondering if that's the right way to go. Since both the web app and tree-sitter are compiled to wasm, I'm asking myself whether it's possible to compile them together to get rid of the js glue.

I'm not an expert in js / wasm unfortunately and I hope what I'm asking for does make sense. I'd be great if you could comment on how I could approach this problem. Thanks very much in advance!

**Comment by maxbrunsfeld** [comment]
I think that if your app is in Rust, you would not need to use the JS binding to Tree-sitter. You should be able to use the Rust binding. I don't have experience comping a mixture of Rust and C into Wasm, but I think it is doable. You may need to use the `wasm32-unknown-emscripten` target triple instead of the `wasm32-unknown-unknown`.

**Comment by fkohlgrueber** [comment]
OK, it's actually much simpler than I thought. When using `wasm32-unknown-emscripten` instead of `wasm32-unknown-unknown` and the `cc` crate to compile the grammars, it just works!

I created a small demonstration project which can be found [here](https://github.com/fkohlgrueber/tree-sitter-test) (including a [live demo](https://fkohlgrueber.github.io/tree-sitter-test/) 🤘)

**Comment by maxbrunsfeld** [comment]
That’s really cool! Thanks for sharing it.
