### ISSUE TITLE
Docs: update to clarify which rule is treated as the entry for a source file

### ISSUE THREAD

**Issue by kylegoetz** [tree-sitter/tree-sitter#4003]
### Problem

Docs don't explain this, which creates confusion. See [here](https://discord.com/channels/1063097320771698699/1063097321648312354/1316888006367383684) for discussion pursuant to a mistaken understanding about this.

### Expected behavior

Docs should clarify which rule is treated as the entry for a source file. As of now, my understanding is that it's the first rule, but it's unclear to me how "first" is defined. JavaScript has a counterintuitive definition of "first property" for JS objects that changed in 2015 from "there is no guaranteed ordering of properties in an object" to something different (ordering is integer keys sorted in increasing order, then string keys sorted by insertion order, then symbol keys sorted by insertion order.

**Comment by sogaiu** [comment]
I don't remember coming across this in the docs and agree that if it isn't mentioned by now, would be a good thing to have.

As a concrete data point, in [tree-sitter-clojure's case](https://github.com/sogaiu/tree-sitter-clojure/blob/f4236d4da8aa92bc105d9c118746474c608e6af7/grammar.js#L249), the start rule needed to be the first one that appeared in `rules` in the source file (so would you say "lexically"?) for things to work.

FWIW, brief mention of the "first" bit [here](https://github.com/tree-sitter/tree-sitter/issues/3574#issue-2499514753).

**Comment by amaanq** [comment]
Closed in #4028
