### ISSUE TITLE
Release notes for v0.24.5 are missing

### ISSUE THREAD

**Issue by keidax** [tree-sitter/tree-sitter#4006]
### Problem

The [latest Github release](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.24.5) has no associated release notes. Additionally, the CHANGELOG.md file has been removed. It seems the only way to understand what's changed in the latest release is by [reviewing the list of commits directly](https://github.com/tree-sitter/tree-sitter/compare/v0.24.4...v0.24.5).

This is a regression from past releases that introduces friction to users of tree-sitter. It's hard to understand quickly what's going on in the project.

### Expected behavior

Adding release notes or a changelog file would fix this. This behavior is expected, since it's the standard for previous releases.

**Comment by amaanq** [comment]
Added
