### ISSUE TITLE
Unclear alias() behavior (+ I would like to improve the documentation on this)

### ISSUE THREAD

**Issue by simonrepp** [tree-sitter/tree-sitter#401]
I'm kinda reopening https://github.com/tree-sitter/tree-sitter/issues/241 here because I'm not sure anyone would notice it if I posted to a terminally closed issue from >1y ago, apologies if this is somehow rude.

I'm basically facing the same issue described in issue #241 - the comments there also let me solve my problem - but given that tree-sitter's documentation (at least for me personally) does not explain what is really going on here, and neither do the comments in the referenced issue for me (some posts seems to be contradicting) I wanted to bring this up again so it can be clarified exhaustively and also in written form in the documentation (I'll gladly submit a patch as soon as I *understand* the problem, which I currently don't :))

## Step 1

This is the starting point, I've set up an $.escapedKey rule (which actually comes from an external scanner.cc implementation) and am confirming its functionality in a test:

**grammar.js**
```js
    ...
    _escapedOrUnescapedKey: $ => choice(
      $.key,
      seq(
        $.escapeOperator,
        $.escapedKey,    <-------------- this works
        $.escapeOperator
      )
    ),
    ...
```

**corpus**
```
(document
 (field (escapeOperator) (escapedKey) (escapeOperator) (elementOperator) (value)))
                          ^^^^^^^^^^
```

## Step 2

The $.escapedKey rule is technically handled differently than the $.key rule, but semantically they should be equal - only 'key' should show up ever in the parsing results. However, my usage of `alias($.escapedKey, 'key')` actually behaves like the thing I would have expected from `alias($.escapedKey, '_key')` and from the documentation it is not clear to me why:

**grammar.js**
```js
    ...
    _escapedOrUnescapedKey: $ => choice(
      $.key,
      seq(
        $.escapeOperator,
        alias($.escapedKey, 'key'),   <-------------- trying to alias now
        $.escapeOperator
      )
    ),
    ...
```

**corpus**
```
(document
  (field (escapeOperator) (escapeOperator) (elementOperator) (value)))
                         ^
          now it's gone instead of aliased?
```

## Elsewhere

Prior to facing the issue described here I've already used alias() in the same way as above - with success - which adds to my puzzlement, below's the excerpt.

There *are* in fact differences though:
- $.key exists in the grammar, while $.template does not
- alias(..., 'key') is only done once, alias(..., 'template') is done twice

However, I don't understand how these differences add up to the different behaviour (they shouldn't at all to my understanding).

**grammar.js**
```
  ...
  section: $ => seq(
    $._sectionDescend,
    $.sectionOperator,
    $._escapedOrUnescapedKey,  // TODO: Implement distinct, looser section key constraints
    optional(seq(
      choice($.copyOperator, $.deepCopyOperator),
      alias($.token, 'template')     <------- here it works the way i understand it?
    )),
    $._endOfLine,
    repeat($._instruction),
    $._sectionAscend
  ),
  ...
```

**corpus**
```
(document
  (section (sectionOperator) (key)
    (section (sectionOperator) (key)

    )
  )
  (section (sectionOperator) (key) (copyOperator) (template)
                                                   ^^^^^^^^
  )                                here it works the way i understand it?
)
```

## Possible clues to a clarification

In #241 there's mention of `anonymous` nodes, while the documentation (at least the `Creating a parser` section) mentions only `hidden` nodes - are these the same thing? Maybe this is a clue where my (and other people's) misunderstanding comes from?

## Reproducing the issue

The repository https://github.com/eno-lang/tree-sitter-eno/ at commit a1e583b0f9abd6a8779b1d708e5cf0c3628a7c53 serves as a reproduction/playing ground for this, but as I understand it from #241 this is not a technical issue per se.

**Comment by simonrepp** [comment]
I dug some more and found I am also doing `alias($.token, 'comment')` (once, with $.comment already being defined elsewhere) and `alias($.token, 'value')` (four times, with $.value **not** existing), here too things works as I imagined them to, just like when I did `alias($.token, 'template')`.

**Comment by maxbrunsfeld** [comment]
I think you want this:

```
alias($.escapedKey, $.key)
```

not this:

```
alias($.escapedKey, 'key')
```

The `alias` function allows you to make the node appear as either a [named node or an anonymous node](http://tree-sitter.github.io/tree-sitter/using-parsers#named-vs-anonymous-nodes). Anonymous (like punctuation and keywords) should not show up in the pretty-printed tree.

It looks like a bug that the word `(template)` showed up there. It shouldn't have showed up unless you did `alias($.token, $.template)`.

**Comment by simonrepp** [comment]
Hey thanks a lot for taking the time! :heart: 

- Your provided solution (also mentioned in #241) works indeed, thanks!
- Still puzzling me: *aliasing* to me is *assigning a different name to something*, that however only makes sense to me if the result is a named node. If `alias($.foo, 'bar')` essentially makes the node anonymous (=nameless?) why do I still provide a name? Somehow something like `anonymize($.foo)` would be more understandable to me in that case, and the `name` (if it is technically still required on an anonymous node) could then just be automatically set to whatever the node captured (or auto-generated if this only happens at compile time)? (just like 'if' captures 'if' in the docs paragraph you linked to) Anyway, just some thoughts to explain my thinking/confusion, I hope useful.

Possible actions:
- I will submit a PR to clarify the `alias` usage in the docs themselves (only if you'd like that of course) in the next days - I think I understand it well enough now to do that, thanks!
- If it would help you (and you have interest and time to look into this anyway) I could also try to set up a minimal reproduction repository to cleanly identify the suspected bug of anonymous nodes showing up in the s-expressions although they shouldn't. There seem to be some obvious constellations when this is happening both in my repo and in #241 so I think I'd know where to start.

**Comment by maxbrunsfeld** [comment]
> If alias($.foo, 'bar') essentially makes the node anonymous (=nameless?) why do I still provide a name?

Anonymous nodes are still accessible in the syntax tree - they just don't show up in the pretty-printed string. It makes the node act as if it had been specified as the string literal `"bar"` in the grammar. In JavaScript, `node.type` would return `"bar"` and `node.isNamed` would return `false`, exactly as if you had written `"bar"` in the grammar.

In the Ruby grammar, for example, there's an external token called [`binary_minus`](https://github.com/tree-sitter/tree-sitter-ruby/blob/db91c934ff9d3d4ea67111a0f581532c49c3a6b3/grammar.js#L59) that [we alias to `"-"`](https://github.com/tree-sitter/tree-sitter-ruby/blob/db91c934ff9d3d4ea67111a0f581532c49c3a6b3/grammar.js#L455), so that it looks just like a normal *minus* operator if you inspect the tree.

**Comment by simonrepp** [comment]
PR to fix the documentation issue: https://github.com/tree-sitter/tree-sitter/pull/405

Let me know in case you want the minimal repo to reproduce the suspected bug in the `alias` implementation.

**Comment by simonrepp** [comment]
Thanks for patching this! :+1:
