### ISSUE TITLE
Tests of various grammars fail in locales with "," decimal separator

### ISSUE THREAD

**Issue by th-we** [tree-sitter/tree-sitter#402]
This issue occurs in a number of grammars, so I'm raising it here first before creating pull requests for the individual repos.

When running `npm test` e.g. on the `tree-sitter-python` grammar, the test fails:

    script/parse-examples: Zeile 38: printf: 100.00000000000000000000: Ungültige Zahl.
    Successfully parsed 0,00% of examples/numpy (407 of 407 files)
    npm ERR! Test failed.  See above for more details.

This is my current setup:

    $ echo "$OSTYPE"
    linux-gnu
    $ echo "$LANG"
    de_DE.UTF-8
    $ echo "$BASH_VERSION"
    4.4.20(1)-release

The issue is caused by the `script/parse-examples` scripts of the Haskell, Ruby, Python, JavaScript, Rust, Go, Java and Julia grammars.

Options for fixing this:

1. set `LC_NUMERIC=C` in the script
2. in `package.json`, change the test script call to `tree-sitter test && LANG=C script/parse-examples`
3. at least document that tests should be run like `LANG=C npm test`

If there is an agreement, I'll create pull requests. Option 1 seems the most robust solution to me.

**Comment by maxbrunsfeld** [comment]
I'd be ok with adding `LC_NUMERIC=C`. I'd also be fine with just simplifying down to integer percentages, and avoiding floating point numbers entirely.

**Comment by maxbrunsfeld** [comment]
I'm going to close this out, since it's not an issue with this repo. If you're interested in opening PRs to fix the shell scripts, I'd merge them.
