### ISSUE TITLE
Suggestion: follow XDG on macOS for tree-sitter CLI

### ISSUE THREAD

**Issue by thecaralice** [tree-sitter/tree-sitter#4023]
### Problem

Currently, `xdg_config_file` uses `dirs::config_dir()`, which gives a rather unusable `$HOME/Library/Application Support/tree-sitter`. Granted, it is a standardized path on macOS, but this standard was intended for GUI apps and this convention is not well-suited for files which are supposed to be accessed by the user directly rather than through a certain GUI panel. tree-sitter is the only CLI following that convention I know of.

### Expected behavior

A solution would be to use XDG convention on both Linux and macOS; there are crates like `etcetera` that take a better approach at choosing config/data/etc paths compared to `dirs`/`directories`. Namely, `etcetera::base_strategy::choose_base_strategy` and `etcetera::app_strategy::choose_app_strategy` use Windows convention on Windows and XDG otherwise.

**Comment by WillLillis** [comment]
Simply swapping out the current implementation for XDG would lead to unnecessary breakage for any macOS user with an existing config. Maybe instead the XDG path could be used first and `$HOME/Library/Application Support/tree-sitter` could be checked afterwards if that directory doesn't contain the expected file? This would match with how the `$HOME/.tree-sitter/` config path was replaced in https://github.com/tree-sitter/tree-sitter/pull/1157.

This function should either be renamed to better reflect its behavior, or updated:

https://github.com/tree-sitter/tree-sitter/blob/90666c951d53c13cc6cf5002d971a6debed74244/cli/config/src/lib.rs#L52-L58

**Comment by thecaralice** [comment]
Yep, I'd expect it to respect legacy paths (note: the `etcetera` crate support all these conventions, the `.tree-sitter` thing is called `Unix` and the macOS thing is called `Apple`)
