### ISSUE TITLE
How to use Python to call a custom parser and perform syntax parsing?

### ISSUE THREAD

**Issue by UtOpiiAa** [tree-sitter/tree-sitter#4030]
### Problem

I have already customized a parser using the Tree-sitter CLI, but I don't know how to call it in a Python program. I referred to previous tutorials and used statements like `Language.build_library` and `MY_LANGUAGE = Language('build/my-languages.so', 'your_language')`. However, these cause errors in my program. I would like to know if there are updated tutorials available?

**Comment by ObserverOfTime** [comment]
[Previous tutorials are outdated.](https://github.com/tree-sitter/py-tree-sitter)

**Comment by UtOpiiAa** [comment]
> [以前的教程已过时。](https://github.com/tree-sitter/py-tree-sitter)

So how can I call my own parser in a python program？

**Comment by UtOpiiAa** [comment]
> [Previous tutorials are outdated.](https://github.com/tree-sitter/py-tree-sitter)

Thank you for your response! I noticed that the parser used in the tutorial is the pre-defined `tree-sitter-python`, but it doesn’t clearly explain how to import a custom parser. It seems like the process involves generating a `_binding.pyd` file through `setup.py`, but since I’m not very familiar with this workflow, I’m not sure if that’s the correct approach. Could you provide more detailed guidance on this?
