### ISSUE TITLE
New docs playground localStorage potential issue

### ISSUE THREAD

**Issue by iann0036** [tree-sitter/tree-sitter#4041]
### Problem

After using the new location for the playground, the "Tree" view showed many parsing errors despite the language dropdown being the default JavaScript. I suspect the localStorage has saved a preference for non-JavaScript and this wasn't reflected in the dropdown behaviour. After opening the language dropdown/selector and choosing the already set JavaScript option, the issue resolved itself. I suspect this is a one-off behaviour.

### Steps to reproduce

In the older playground, have your language set to anything that isn't JavaScript.

Navigate to the newer playground, observe that the default language of JavaScript is set, paste JavaScript code, and observe that the parser throws many errors (as if the language selector was set to something else).

### Expected behavior

Parser to always match what the dropdown says.

### Tree-sitter version (tree-sitter --version)

N/A

### Operating system/version

Chrome on macOS

**Comment by iann0036** [comment]
Probably relates to #4040

**Comment by amaanq** [comment]
Sorry about that, should be fixed now :sweat_smile:
