### ISSUE TITLE
descendantForPosition changes behavior

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#407]
It seems like `descendantForPosition` handles differently under certain circumstances. I originally thought it was connected to the end of the line, but I'm getting this problem in other cases too. But I figured we could start with this.

Based on https://github.com/tree-sitter/tree-sitter/blob/6bd311bddaa2bda72885bf8130e16509b6fd0e01/lib/binding_web/test/node-test.js#L190-L193 I would assume this test to be successful but it isn't:
```
      assert.equal(
        sumNode.namedDescendantForPosition({ row: 0, column: 10 }).type,
        "number"
      );
```
It seems to return the containing node in this case

I guess it's worth to mention that targeting the end of the first token works as you would expect
```
      assert.equal(
        sumNode.namedDescendantForPosition({ row: 0, column: 2 }).type,
        "identifer"
      );
```

**Comment by maxbrunsfeld** [comment]
I think the method is behaving consistently. It will return nodes that *start* at the given position, or *contain* the given position, but not nodes that *end* at the given position. It will fall back to the root node if nothing else matches.

> I would assume this test to be successful but it isn't:

That test should not pass. Column 10 is at the end of the number.

> I guess it's worth to mention that targeting the end of the first token works

Column 2 is not the end of the first token.

Am I missing anything? To get a feel for how `namedDescendantForPosition` works (both with a single position and with a range), you can go to the [web playground](http://tree-sitter.github.io/tree-sitter/playground) and move your cursor/selection around.

**Comment by Razzeee** [comment]
Sorry, your right. Had a wrong assumption about the `+` and your nodes, paired with a problem I need to workaround.

Thank you
