### ISSUE TITLE
Pre-built WASM languages

### ISSUE THREAD

**Issue by curran** [tree-sitter/tree-sitter#408]
I found myself frustrated with the process of compiling WASM languages using the steps outlined here https://www.npmjs.com/package/web-tree-sitter#generate-wasm-language-files

Might it be of interest to have pre-built WASM files for languages distributed via NPM? That would make the library more directly usable for JavaScript developers. This would eliminate the extra language compilation step. It would also relieve the burden on developers to manage the generated files.

This may well be out of scope for the project, and could live in a separate project entirely, but I thought I'd open the issue to see if anyone else thinks this would be useful.

**Comment by stereobooster** [comment]
There is https://github.com/Menci/tree-sitter-wasm-prebuilt

I also think that it would be a good idea to package wasm binaries in node modules, so you can install those packages without compilation step on any platform. I want to use those packages with node.js (it's now support wasm)

**Comment by cherryleafroad** [comment]
I just made / uploaded a whole bunch if anyone's also interested

**Comment by ahelwer** [comment]
I've noticed a few languages (mine included) have a pre-built wasm in their tree-sitter-lang NPM package.

**Comment by Gregoor** [comment]
FYI: I forked `tree-sitter-wasm-prebuilt` to includes TypeScript (and for some other customization reasons): https://github.com/Gregoor/tree-sitter-wasms
That one is published under `tree-sitter-wasms`

**Comment by devm33** [comment]
@ahelwer which languages have pre-built wasm in their npm packages?

**Comment by ahelwer** [comment]
@devm33 no idea, totally up to the package owner to decide to include it.

**Comment by sogaiu** [comment]
Did some searching on locally collected things.

Roughly 1 in 10 repositories (~30 out of 300) seem to have `.wasm` files and the locations for such files seems to vary across repositories.

<details>
<pre>
https://github.com/AbstractMachinesLab/tree-sitter-sexp/blob/master/tree-sitter-sexp.wasm
https://github.com/FoamScience/tree-sitter-foam/blob/master/tree-sitter-foam.wasm
https://github.com/Himujjal/tree-sitter-svelte/blobl/master/tree-sitter-svelte.wasm
https://github.com/MichaHoffmann/tree-sitter-hcl/blob/main/docs/tree-sitter-hcl.wasm
https://github.com/UserNobody14/tree-sitter-dart/blob/master/tree-sitter-dart.wasm
https://github.com/Ziemniakoss/tree-sitter-apex/blob/master/tree-sitter-apex.wasm
https://github.com/aheber/tree-sitter-sfapex/blob/main/docs/playground/js/tree-sitter-apex.wasm
https://github.com/aheber/tree-sitter-sfapex/blob/main/docs/playground/js/tree-sitter-soql.wasm
https://github.com/aheber/tree-sitter-sfapex/blob/main/docs/playground/js/tree-sitter-sosl.wasm
https://github.com/chipsalliance/tree-sitter-firrtl/blob/main/docs/tree-sitter-firrtl.wasm
https://github.com/elm-tooling/tree-sitter-elm/blob/main/docs/js/tree-sitter-elm.wasm
https://github.com/gbprod/tree-sitter-gitcommit/blob/main/tree-sitter-gitcommit.wasm
https://github.com/gbprod/tree-sitter-twig/blob/main/tree-sitter-twig.wasm
https://github.com/grantmacken/tree-sitter-xquery/blob/main/docs/tree-sitter-xquery.wasm
https://github.com/ikatyang/tree-sitter-markdown/blob/master/docs/assets/tree-sitter-markdown-0.7.1/tree-sitter-markdown.wasm
https://github.com/ikatyang/tree-sitter-toml/blob/master/docs/assets/tree-sitter-toml-0.5.1/tree-sitter-toml.wasm
https://github.com/ikatyang/tree-sitter-vue/blob/master/docs/assets/tree-sitter-vue-0.2.1/tree-sitter-vue.wasm
https://github.com/ikatyang/tree-sitter-yaml/blob/master/docs/assets/tree-sitter-yaml-0.5.0/tree-sitter-yaml.wasm
https://github.com/julienhenry/tree-sitter-souffle/blob/master/tree-sitter-souffle.wasm
https://github.com/m-novikov/tree-sitter-sql/blob/master/docs/tree-sitter-sql.wasm
https://github.com/mehmetoguzderin/tree-sitter-wgsl/blob/master/tree-sitter-wgsl.wasm
https://github.com/nvim-treesitter/tree-sitter-query/blob/master/tree-sitter-query.wasm
https://github.com/pleshevskiy/tree-sitter-d2/blob/master/tree-sitter-d2.wasm
https://github.com/rolandwalker/tree-sitter-pgn/blob/master/tree-sitter-pgn.wasm
https://github.com/stsewd/tree-sitter-comment/blob/master/tree-sitter-comment.wasm
https://github.com/stsewd/tree-sitter-rst/blob/master/tree-sitter-rst.wasm
https://github.com/takegue/tree-sitter-sql-bigquery/blob/main/playground/tree-sitter-sql_bigquery.wasm
https://github.com/the-mikedavis/tree-sitter-git-config/blob/main/tree-sitter-git_config.wasm
https://github.com/tree-sitter/tree-sitter-haskell/blob/master/tree-sitter-haskell.wasm
https://github.com/tree-sitter/tree-sitter-javascript/blob/master/tree-sitter-javascript.wasm
https://github.com/wasm-lsp/tree-sitter-wasm/blob/main/wast/tree-sitter-wast.wasm
https://github.com/wasm-lsp/tree-sitter-wasm/blob/main/wat/tree-sitter-wat.wasm
https://github.com/yagebu/tree-sitter-beancount/blob/main/tree-sitter-beancount.wasm
</pre>
</details>

FWIW, the searching was done via the data from [here](https://github.com/sogaiu/ts-questions/blob/master/ts-grammar-repositories.txt).

**Comment by amaanq** [comment]
By default, our template allows wasm files to be uploaded & our CI actions build & upload these wasm files, so this can be closed out.
