### ISSUE TITLE
Tests for ts_tree_edit

### ISSUE THREAD

**Issue by curran** [tree-sitter/tree-sitter#411]
In researching the expected behavior for `ts_tree_edit`, I was surprised to find there are no tests for it.

There appears to have previously been tests that cover it here https://github.com/tree-sitter/tree-sitter/tree/61327b627a575e2d47968fc2ac68a2073c4407f1/test/runtime

But now that directory is gone. Do the tests still exist somewhere?

**Comment by maxbrunsfeld** [comment]
The most basic unit tests are here: https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/tests/tree_test.rs. 

The editing/reparsing workflow is also tested quite thoroughly via randomized tests which perform random edits to each example snippet in the test suites of 5 or 6 popular languages. https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/tests/corpus_test.rs
