### ISSUE TITLE
Expose utility for computing (row, column) from index

### ISSUE THREAD

**Issue by curran** [tree-sitter/tree-sitter#412]
I'm in a position where I know the edit specification in terms of indices (byte offsets), but not in terms of the (row, column) "points". As I sit down to write a function that computes these, I thought I'd post this issue in case this logic is implemented internally within tree-sitter, and could possibly be exposed as part of its public API.

Related https://github.com/tree-sitter/tree-sitter/issues/397

>Is it possible to specify input edits and included ranges with byte offsets only?

**Comment by curran** [comment]
Here's what I've got in JavaScript for this:

```js
const positionFromIndex = (index, text) => {
  let row = 0;
  let column = 0;
  for(let i = 0; i < index; i++){
    row++;
    if(text[i] === '\n'){
      column++;
      row = 0;
    }
  } 
  return { row, column };
};  
```

**Comment by maxbrunsfeld** [comment]
The reason I don’t include this algorithm in Tree-sitter (aside from the fact that it’s trivial to write, as you point out) is that it isn’t very efficient. 

If you’re using ‘ts_tree_edit’, you’re doing incremental parsing, so you probably care about performance. This approach of scanning through every character until the edit position will be very slow for edits at the ends of large files. 

If you’re creating a text editor, you’ll already need to have a reasonably efficient way of dealing with code in a row/column oriented way, for many other reasons, so Tree-sitter leaves that responsibility up to the application.

If you’re just creating a prototype, then using a simple string is good enough, but I’d rather not make additions to Tree-sitter’s API just for the prototype use case.

Does that make sense?

**Comment by curran** [comment]
@maxbrunsfeld Yes, that makes perfect sense. Thanks for your response!

FWIW, I was trying to retrofit HTML's `textarea` with a syntax highlighting overlay. It's sort of a silly experiment, as `textarea` doesn't provide the granularity needed for a proper code editor, but I learned a lot! https://github.com/datavis-tech/codearea
