### ISSUE TITLE
Documentation about tree node fields

### ISSUE THREAD

**Issue by fwcd** [tree-sitter/tree-sitter#416]
There are several grammars that use a `field(...)`-function to produce labelled syntax tree nodes, including [Java](https://github.com/tree-sitter/tree-sitter-java/commit/bc7124d924723e933b6ffeb5f22c4cf5248416b7) and [JS](https://github.com/tree-sitter/tree-sitter-javascript/commit/ff948f88ee99690f391d7a41fe5c259018aef09f#diff-95fc33185b7215010b60f43469000a7a). The [Grammar DSL docs](https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-3-creating-parsers.md#the-grammar-dsl) do not mention it, however.

Am I missing something?

**Comment by maxbrunsfeld** [comment]
Yeah, I have a lot of documentation to write, after the last several months of changes. I guess I was waiting to write the docs until I've been using the feature internally for a while to get all of the problems worked out.

But it's pretty much done. So in the meantime, here's some info:

* The concept was introduced in https://github.com/tree-sitter/tree-sitter/pull/271.
* The only change to the Grammar API is the new `field` function which you pointed out.
* The new C library APIs for dealing with fields are [here](https://github.com/tree-sitter/tree-sitter/blob/d78204b71380421894e8d243e4aae540c962c07e/lib/include/tree_sitter/api.h#L457-L472) and [here](https://github.com/tree-sitter/tree-sitter/blob/d78204b71380421894e8d243e4aae540c962c07e/lib/include/tree_sitter/api.h#L554-L568).
* If you're using the Node.js binding, its new APIs are described [here](https://github.com/tree-sitter/node-tree-sitter/pull/39).
* If you're using the Rust binding, the new APIs are [here](https://github.com/tree-sitter/tree-sitter/blob/d78204b71380421894e8d243e4aae540c962c07e/lib/binding_rust/lib.rs#L532-L541) and [here](https://github.com/tree-sitter/tree-sitter/blob/d78204b71380421894e8d243e4aae540c962c07e/lib/binding_rust/lib.rs#L660-L680).

**Comment by fwcd** [comment]
@maxbrunsfeld Thanks for the quick response and the links!

**Comment by Razzeee** [comment]
As far as I can tell wasm only has field name? https://github.com/tree-sitter/tree-sitter/blame/master/lib/binding_web/tree-sitter-web.d.ts#L100

Will we get the id (no idea what's that for) and the child by field name function too?

**Comment by maxbrunsfeld** [comment]
> Will we get the id (no idea what's that for) and the child by field name function too?

Yeah, I added the remaining bindings in https://github.com/tree-sitter/tree-sitter/commit/82fab90c0b91cc57a949b9d96768d7f3b7a621e4.

**Comment by maxbrunsfeld** [comment]
Docs are up: here: http://tree-sitter.github.io/tree-sitter/using-parsers#node-field-names and here: http://tree-sitter.github.io/tree-sitter/creating-parsers#using-fields.

**Comment by your-diary** [comment]
> Docs are up: here: http://tree-sitter.github.io/tree-sitter/using-parsers#node-field-names and here: http://tree-sitter.github.io/tree-sitter/creating-parsers#using-fields.

LInk dead.

Latest link (auto-updated): https://tree-sitter.github.io/tree-sitter/index.html?search=field
