### ISSUE TITLE
Tree-sitter API: Obtaining field information

### ISSUE THREAD

**Issue by rfdonnelly** [tree-sitter/tree-sitter#417]
I'm using the Rust bindings and I'm trying to obtain node field information.

It seems field information is only available via a `TreeCursor`.  Field information cannot be obtained via a `Node` directly.

However, I've found that I cannot obtain the node field information from a `TreeCursor` that I've obtained from the node  (i.e. `node.walk().field_name()` always returns `None`).  It seems I must walk the tree using a `TreeCursor` to get valid field information.

This seems to be by design but I haven't dug deep enough to be certain.  Is it possible to access field information via a `Node`?

## Example

If I walk the tree using the `recurse` function below, `field_name()` always returns `None`.

If I walk the tree using the `walk` function below, `field_name()` works as expected.

```Rust
fn recurse<'a>(node: Node<'a>) {
    println!("{}:{}", node.walk().field_name().unwrap_or("null"), node.kind());

    node.children().for_each(recurse);
}

fn walk<'a>(cursor: &mut TreeCursor<'a>) {
    loop {
        println!("{}:{}", cursor.field_name().unwrap_or("null"), cursor.node().kind());

        if !cursor.goto_first_child() {
            if !cursor.goto_next_sibling() {
                loop {
                    if !cursor.goto_parent() {
                        return;
                    }

                    if cursor.goto_next_sibling() {
                        break;
                    }
                }
            }
        }
    }
}
```

**Comment by maxbrunsfeld** [comment]
Yeah, that's how it's (currently) intended to work. When you call `.walk()` on a `Node`, the returned `TreeCursor` can only access information about that node and its children and descendants, but not the node's *parent*, or any nodes "higher up" in the tree. Field names require knowledge of the parent - they are conceptually *named edges* between parent and child.

When using the `TreeCursor` APIs, I've always just started from the root of the tree, so this limitation has never been a problem for me in practice, but I can see how this might be somewhat unexpected.

It is possible to remove this restriction, but it wouldn't be as simple and fast as the existing `TreeCursor` implementation. Right now, all of the tree cursor methods are basically the most efficient possible way of interacting with the tree. So I'd have to think about whether it's worth it to make enable moving up the tree beyond where you started. It might be fine.

**Comment by maxbrunsfeld** [comment]
If you're not using `TreeCursor` otherwise, you might want to use the `node.child_by_field_name` method to retrieve nodes according to their field name.

**Comment by rfdonnelly** [comment]
Great response.  Thank you.  I had a feeling this was due to field information being stored in the parent.  

I don't think it makes sense to modify the implementation to support obtaining field name via `node.walk().field_name()` at the cost of compute resources.  That sounds like an anti-pattern.

It sounds like either of these approaches will work for me:

* Recursion + `child_by_field_name`
* `TreeCursor`

BTW I wrote an article on [using Tree-sitter parsers in Rust](https://www.reddit.com/r/rust/comments/cnqhgm/using_treesitter_parsers_in_rust/).  The Rust binding README was helpful but didn't have all the details.

**Comment by maxbrunsfeld** [comment]
Great writeup! Thanks for sharing that.

**Comment by Sarrus1** [comment]
If someone is looking for an implementation:

```rust
pub fn field_name(node: &tree_sitter::Node) -> Option<String> {
    let parent = node.parent()?;
    let mut cursor = parent.walk();
    parent.children(&mut cursor).find(|child| child == node)?;
    cursor.field_name().map(String::from)
}
```

This can probably be improved a bit.
