### ISSUE TITLE
Maintaining partial sums of children length in parent

### ISSUE THREAD

**Issue by zajac** [tree-sitter/tree-sitter#425]
What do you think of maintaining partial sums of children lengths in parent in order to navigate down by offset faster using binary search?
That could be useful for very wide syntax trees.

**Comment by maxbrunsfeld** [comment]
Very wide syntax trees are usually parsed via the `repeat` rule, which handles repetitive structure, and internally builds balanced binary trees.

For example, when parsing this Java class with 24 methods:

<details>
<summary>Class with 24 methods</summary>

```java
class Foo {
  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }

  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }

  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }

  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }

  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }

  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }

  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }

  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }

  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }

  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }

  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }

  T getBar() {
    return this.bar;
  }

  void setBar(T bar) {
    this.bar = bar;
  }
}
```
</details>

The resulting syntax tree looks like this:

![binary-syntax-tree](https://user-images.githubusercontent.com/326587/63045029-599e0700-be84-11e9-89db-2b7186cf3793.png)

So APIs based on document offsets like [`ts_tree_cursor_goto_first_child_for_byte`](https://github.com/tree-sitter/tree-sitter/blob/5e04daf483d1ce8344895c37bcec55cdbbef9a75/lib/include/tree_sitter/api.h#L489) and [`ts_node_descendant_for_byte_range `](https://github.com/tree-sitter/tree-sitter/blob/5e04daf483d1ce8344895c37bcec55cdbbef9a75/lib/include/tree_sitter/api.h#L500) should already have a cost that's logarithmic in their tree size (as opposed to linear).

Are there calls that you're seeing taking unexpectedly long in the case of wide syntax trees like this?

**Comment by zajac** [comment]
I didn't know that, thanks for the clarification! Is it limited to nodes with the same type? or is it anything in `repeat`? Will it work if methods would be interleaved by fields for example?

Nothing is slow right now, I'm just trying to assess the performance guarantees TS gives.

BTW, I'm curious about how does Atom handle syntax highlighting. Does it query the AST directly during rendering or is it syncing it with some sort of an interval tree?

**Comment by zajac** [comment]
I see the Pro of the approach with binary trees is that all the existing algorithms working with offsets are logarithmic out-of-the-box. 
But. It increases a tree height, hurts cache-locality and increases memory traffic. Partial sums would give the same performance for lookups by offset, being more cache-friendly and generally simple. What do you think?

**Comment by maxbrunsfeld** [comment]
> is it anything in `repeat`? Will it work if methods would be interleaved by fields for example?

Yeah, it happens anytime `repeat` is used in the grammar. Inside of the `repeat` there could be a `choice` between several different node types, so it works fine with intermixed methods and fields in Java.

> Partial sums would give the same performance for lookups by offset, being more cache-friendly and generally simple. What do you think?

There are other reasons why sequences are represented this way. In general, it fits much more directly into the normal LR parsing algorithm. Every `REDUCE` action builds a new subtree, instead of some `REDUCE` actions actually mutating existing subtrees somehow. This is especially important since the syntax trees need to be persistent, conceptually-immutable data structures.

Also, several other quantities besides size (e.g. `visible_child_count`, `node_count`, `error_cost`, `dynamic_precedence`) are aggregated on each node. If sequences were represented as flat arrays, we'd need to either maintain partial sums of *all* of these things or recompute all of these aggregate quantities when reusing part of a sequence.

**Comment by zajac** [comment]
That is very reasonable, thanks!
Still curious about Atom approach to syntax highlighting. Does it render data directly from AST?

**Comment by maxbrunsfeld** [comment]
It's a good point about the cache locality though. I've thought about creating a specialized `Subtree` representation just for nodes with *exactly* two children (which make up the internal structure of these binary trees). We could theoretically avoid one level of indirection for these nodes, which might speed things up and reduce the tree's memory footprint by a little bit. I might try this at some point.

**Comment by maxbrunsfeld** [comment]
Atom uses the `TreeCursor` API directly during syntax highlighting. It uses the `ts_tree_cursor_goto_first_child_for_byte` API to move the cursor to the region that it needs to highlight, and then it uses the stepwise walking APIs to walk the tree in that region. Most of the logic is in [this class](https://github.com/atom/atom/blob/e96ef678159b5dc3a32fe91cec1ce927160f21e0/src/tree-sitter-language-mode.js#L1080).

**Comment by maxbrunsfeld** [comment]
There's also a rust implementation in the [`tree-sitter-highlight`](https://github.com/tree-sitter/tree-sitter/tree/master/highlight) crate. It doesn't currently handle the editing use case though: just highlighting entire files.
