### ISSUE TITLE
tree-sitter test not running all tests

### ISSUE THREAD

**Issue by razzeee** [tree-sitter/tree-sitter#441]
So it seems like I can bring `tree-sitter test` to omit some tests. I'm not sure why, I changed some stuff in `scanner.cc` here.
https://github.com/Razzeee/tree-sitter-elm/commit/c9e889e14a38eefce39c6907aeb9d2dfdf7612ff

After these changes I only get a fraction of the tests I have, they are all successful. Nothing else gets listed.

With that commit 
![image](https://user-images.githubusercontent.com/5943908/64075918-cc99e100-ccbe-11e9-8402-dd41273791b7.png)

Without it the output is actually to high to screenshot in on my laptop.

**Comment by maxbrunsfeld** [comment]
What's the exit status of `tree-sitter test`. It looks like the parser is crashing - a segfault is happening in your external scanner? I would run it with a debugger using `lldb $(which tree-sitter) test`.

**Comment by Razzeee** [comment]
your probably right. anyway the exit code is `0`

lldb only gets me a prompt
![image](https://user-images.githubusercontent.com/5943908/64277990-f61b6c80-cf4b-11e9-93f9-1af7240b9e86.png)

**Comment by maxbrunsfeld** [comment]
Yeah, a prompt is normal. Check out the lldb docs for how to use the debugger.

I forgot, you have to pass `lldb` the actual executable, not the JS wrapper script, so it'd be

```sh
lldb node_modules/tree-sitter-cli/tree-sitter test
```

First guess - is your parser going into an infinite loop making no progress because you're returning tokens with zero size?

**Comment by Razzeee** [comment]
So while I could check that, my hope was to check if we're somehow able to let the test command recognize this and correctly produce an error. It's something that should let CI or scripts halt and report.

**Comment by Razzeee** [comment]
`tree-sitter test -d` confirms, that it's looping

**Comment by dundargoc** [comment]
Is this still a problem?

**Comment by amaanq** [comment]
I think it's not an upstream issue
