### ISSUE TITLE
Unicode Plane0 surrogates not supported

### ISSUE THREAD

**Issue by blinker29** [tree-sitter/tree-sitter#451]
Probably not critical, but regex values \uD800 to \uDFFF fail (see below), preventing a search for any non-BMP value pairs, i.e.,  /\uD834\uDD1E/.  There could be good reasons to avoid the complexities, but I thought I would point out the gap in case it was helpful.

> Error processing rule Pex_token1
> Details:
>   regex parse error:
>     \uD834\uDD1E
>       ^^^^
> error: hexadecimal literal is not a Unicode scalar value

**Comment by maxbrunsfeld** [comment]
Did you try writing the character itself in the regex (`/𝄞/`)?

Unlike JavaScript, Tree-sitter does not assume strings are represented as UTF16, so regex syntax that is UTF16-specific currently doesn't work. The regex engine itself should work fine for non BMP characters though.

**Comment by blinker29** [comment]
That worked, thank you.  I would prefer that the parser handle valid \u specs, but handling D800-DFFF is probably an edge case and not a priority.  I'm going to close.  At least there's a record for anyone else who happens to run into this limitation to resurrect as needed.  Cheers.
