### ISSUE TITLE
Generated parser.c includes '0x1a' literal which fails compilation on windows

### ISSUE THREAD

**Issue by blinker29** [tree-sitter/tree-sitter#452]
Code generator should avoid '0x1a' literals in source code because (I believe) standard IO libs for windows in non-binary mode interpret '0x1a' as EOF regardless of where it shows up, which causes compilation to fail.

> 1704]      if (lookahead == '<0x19>') ADVANCE(39);
> 1705]      if (lookahead == '<0x1a>') ADVANCE(40);
> 1706]      if (lookahead == '<0x1b>') ADVANCE(41);

> Details:
>   Parser compilation failed.
> Stdout: parser.c
> ...\src\parser.c(1705): fatal error C1004: unexpected end-of-file found

Converting to integer literal works around the problem.

> 1704]      if (lookahead == '<0x19>') ADVANCE(39);
> 1705]      if (lookahead == 26) ADVANCE(40);
> 1706]      if (lookahead == '<0x1b>') ADVANCE(41);

To automate, I needed to implement a post-processor after "tree-sitter generate".  I know this is not a problem on Linux, and I'm not a Windows guy, but this is a defect and should probably be fixed at some point when convenient for the maintainers.

**Comment by maxbrunsfeld** [comment]
I believe this was fixed by https://github.com/tree-sitter/tree-sitter/commit/5767bbc80626bc39432b08f729ceb872244532e1. The fix will go out in 0.15.13.
