### ISSUE TITLE
Compile tests with address sanitizer on CI

### ISSUE THREAD

**Issue by maxbrunsfeld** [tree-sitter/tree-sitter#456]
We [used to use](https://github.com/tree-sitter/tree-sitter/pull/82) the LLVM address sanitizer to compile the tests. This helped catch some undefined behaviors that did not cause problems under normal compilation.

Then, in https://github.com/tree-sitter/tree-sitter/pull/260, I ported the CLI and the test suite from C++ to Rust, and stopped using address sanitizer. Since then, there's been at least [one instance](https://github.com/tree-sitter/tree-sitter/commit/cb87b7b76e3ef1b3c624b5cc5fa2484051efc266) of undefined behavior caught using the address sanitizer.

We should restore the address sanitizer on CI, or at least when running tests locally. Fortunately, it is possible to use the address sanitizer with Rust (https://github.com/rust-lang/rust/pull/38699). There are just a few issues:
1. It only works with the nightly version of the Rust toolchain
2. You have to explicitly pass a `--target` to the `cargo build` command, rather than relying on the default target.
3. For some reason, the `lexical-core` crate doesn't compile with the address sanitizer.

The third issue will be fixed once https://github.com/tree-sitter/tree-sitter/pull/448 lands, because we'll remove the dependency on `rsass`, which depends on `lexical`. The other two issues are not a big deal.

/cc @bfredl @philipturnbull

**Comment by amaanq** [comment]
I've added it in CI (it builds Rust's stdlib with asan as well), and did catch one potential spot for a bug w/ it
