### ISSUE TITLE
Document supported Javascript Regexp capabilities

### ISSUE THREAD

**Issue by yagebu** [tree-sitter/tree-sitter#463]
I recently started playing around with tree-sitter. I've found it a pleasure to get started with, the documentation is easy to follow and I really like the integrated test system. Thank you!

One place where I found the documentation to be a bit lacking was when I tried to use some more advanced regex features (in particular Unicode property escapes like `\p{Ll}`). It's hard to figure out what the intended support of Javascript regexes and behaviour with certain given flags is. It would be nice to have some page listing the supported features (and differences in behaviour necessitated by the specific use-case and implementation of tree-sitter).

For [tree-sitter-beancount](https://github.com/yagebu/tree-sitter-beancount), I've resorted to using an additional build step using regexpu to compile it to an expression listing all characters separately. This makes it a bit harder to reason with in case of unicode-related grammar compilation errors as the build step itself might introduce more problems.

Regarding unicode escapes: it seems that the used regex_syntax crate has very complete [Unicode support](https://docs.rs/regex-syntax/0.6.12/regex_syntax/#crate-features), would it be hard to support them in tree-sitter as well?

**Comment by smackesey** [comment]
Yes, the documentation seemed very complete, but then I too started getting mysterious failures caused by using even quite basic JS regexp features. There is no mention that there are any limitations in the otherwise well-written [Creating Parsers](https://tree-sitter.github.io/tree-sitter/creating-parsers) tutorial.

For example, `/#####+/` works, but `/#{5,}/` does not (and the error message is totally opaque).

This should be very low-effort to fix (even temporarily, just a single sentence warning users that Regexp support is limited!) and can potentially save users a good deal of frustration.

**Comment by sogaiu** [comment]
I've gone through a bit of the [tests at the end of `expand_tokens.rs`](https://github.com/tree-sitter/tree-sitter/blob/8389ffd2a1cbae722ade99b262d9d6293d943f06/cli/src/generate/prepare_grammar/expand_tokens.rs#L564-L880) and written up some notes on what I found [here](https://github.com/sogaiu/ts-questions/tree/master/questions/what-regex-features-are-supported).

The hope is that this might make more of the details accessible to a wider audience (and get feedback to correct errors).  I definitely was not aware of a significant amount of what was in there.

If desired, you can jump over the wordy intro by going [here](https://github.com/sogaiu/ts-questions/tree/master/questions/what-regex-features-are-supported#features-that-have-tests) directly to examples with links to the corresponding tests.

I hope there aren't too many errors :)

**Comment by ahlinc** [comment]
For now it make sense to document current a subtle behavior:
* https://github.com/tree-sitter/tree-sitter/issues/2225

**Comment by sogaiu** [comment]
I see there is some change in the docs in #2475.  That's nice!

I hope that's good enough for most cases, I think the details can matter a lot though and I suspect it is quite tricky and time-consuming to be explicit about them.

**Comment by amaanq** [comment]
I think it should be okay for now, there are a lot of tiny details that could be added for sure but that's exhausting and might become overbearing

**Comment by sogaiu** [comment]
Oh, I remember that [this code](https://github.com/tree-sitter/tree-sitter/blob/5ea0dbf77a891df125d1b3ccc97f99c5e52899a1/cli/src/generate/prepare_grammar/expand_tokens.rs#L618-L943) seemed pretty nice from the perspective of seeing what might be intended to work.

Do you think that's a fair take?

If someone wants a certain behavior, does it help if they PR some test that exhibits that behavior?

**Comment by mingodad** [comment]
Is this project https://github.com/tree-sitter/tree-sitter-regex supposed to be specific to the `regex` accepted by `tree-sitter` ?
If so using this tool https://meimporta.eu/tree-sitter/json2ebnf.html can convert the `grammar.json` to a railroad diagram to help document/debug/develop it (see also https://github.com/tree-sitter/tree-sitter/discussions/2269).

**Comment by mingodad** [comment]
If it's not then probably should be a good idea to have one specific to the one that `tree-sitter` accept/implement !

**Comment by amaanq** [comment]
thats meant for javascript injections, so most closely follows ecma regex
