### ISSUE TITLE
Lexer bloat when supporting large character classes

### ISSUE THREAD

**Issue by yagebu** [tree-sitter/tree-sitter#464]
I'm writing [a tree-sitter grammar](https://github.com/yagebu/tree-sitter-beancount) that has one [unicode token](https://github.com/yagebu/tree-sitter-beancount/blob/master/account-token-es6.js) (which is compiled by regexpu), which leads to huge increases to the size of the parser. The language itself is not too complex, however due to this one token, the parser size blows up a lot when implementing some rules. The combination with the following token (that is, rules where both tokens might match):

     /[A-Z][A-Z0-9\'\._\-]{0,22}[A-Z0-9]/

instead of 

     /[A-Z][A-Z0-9\'\._\-]*[A-Z0-9]/

increases the parser.c size to 2.3MB from ~850KB and makes it uncompileable on my systems (or rather I give up after about two minutes). Since the language has a [lex/yacc parser](https://bitbucket.org/blais/beancount/src/default/beancount/parser/), ~~where the generated lexer.c is about 90KB which compiles almost instantly~~ (edit: this comparison isn't really fair, since that lexer doesn't distinguish between the character classes actually...), that seems a bit excessive.

In the larger file, ~49k of a total ~52k lines are taken up by the `ts_lex` function. Since the unicode classes like letters and uppercase letters consist of a lot of characters that are quite spread over the unicode range, which leads to or-chains of something like 650 lines (see, eg, start [here](https://github.com/yagebu/tree-sitter-beancount/blob/master/src/parser.c#L976)). The duplication of these lines seems to lead to the large file size.

I understand that unicode characters and bounded-length regexes will lead to a bigger parser, I think this could be handled better. Maybe for very large character classes, the conditions could be extracted to a function, so that they don't have to be duplicated (I guess the compiler could still inline it if it sees fit).

(On a somewhat related note - I'm not much of a low-level C programmer myself, but for such a large number of characters and large number of comparison expressions to check, it seems to be inefficient to walk through them in sequence, is there maybe a more efficient way like doing a binary search of the possible ranges of code points. If this is not really an issue with other parsers, it might not be worth the effort though...)

**Comment by maxbrunsfeld** [comment]
Yeah, we need to add support for [Unicode property escapes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes), but it'll take a significant amount of work, probably several weeks of focused time. I'm not sure when I'm going to prioritize it, but probably in the next few months.

Until then, I would not recommend expanding a property escape like `\p{L}` into its full character set. Instead, I would just include enough characters to match 99.9% of real-world use cases. That's what we currently do in the [golang grammar](https://github.com/tree-sitter/tree-sitter-go/blob/4d27a8ac79fdd9fa1e5240401df83968e9f2bf3a/grammar.js#L18).

**Comment by drom** [comment]
Any work is done towards adding Unicode character classes?
