### ISSUE TITLE
webpack with web-tree-sitter, Module not found: Error: Can't resolve 'fs' in 'node_modules/web-tree-sitter'

### ISSUE THREAD

**Issue by ericoporto** [tree-sitter/tree-sitter#466]
I am trying to use `npx webpack` but I get a weird error

```
$ npx webpack
Hash: d0027e2d20bd796df37b
Version: webpack 4.41.2
Time: 206ms
Built at: 10/19/2019 6:54:10 PM
 1 asset
Entrypoint main = main.js
[1] ./src/index.js 404 bytes {0} [built]
    + 4 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in ./node_modules/web-tree-sitter/tree-sitter.js
Module not found: Error: Can't resolve 'fs' in 'node_modules/web-tree-sitter'
 @ ./node_modules/web-tree-sitter/tree-sitter.js 1:625-638 1:54497-54510
 @ ./src/index.js
```

I tried building using browserify too, but then it will try to load the wasm of tree-sitter itself, and fails too.

```
bundle.js:497 Fetch API cannot load file:///home/user/tree-sitter.wasm. URL scheme must be "http" or "https" for CORS request.
```

Is there any working example of running tree-sitter on the web somewhere?

**Comment by ericoporto** [comment]
Even after manually bundling tree-sitter.wasm e doing things by hand, traversing a tree is not possible since `nodeText` is not defined in web-tree-sitter. 

```
const cursor = parser.parse(MyTextToParse).walk();
cursor.gotoFirstChild();
cursor.nodeText; //<--always undefined

```

**Comment by maxbrunsfeld** [comment]
Ok, `TreeCursor.nodeText` is added in 0.15.10.

As for the original issue, no I don't have an example of using Tree-sitter with webpack. On [the docs site], we just load Tree-sitter as a standalone `script` tag. If you find some changes that make it work better with webpack, please let me know.

**Comment by ericoporto** [comment]
Regarding webpack if I think on something I will throw another issue. 

Thanks for adding nodeText this is enough for me to go on now. This issue can be closed.

**Comment by char0n** [comment]
@ericoporto have you been able to resolve the issue in `Module not found: Error: Can't resolve 'fs' in ...`? When trying to use webpack I'm seeing the same

**Comment by ericoporto** [comment]
Hey thanks! I haven't, I was resorting to manually adding the wasm I think. I will try this fix later :)

**Comment by jburrow** [comment]
In webpack 5.46 the configuration object has changed -  you need to specify 
```

  resolve: {
    fallback: {
      fs: false
    }
}
```

**Comment by char0n** [comment]
> In webpack 5.46 the configuration object has changed - you need to specify
> 
> ```
> 
>   resolve: {
>     fallback: {
>       fs: false
>     }
> }
> ```

Yep, I actually needed to use following in order to bundle correctly:

```js
resolve: {
  fallback: {
    fs: false,
    path: false,
  }
}
```
