### ISSUE TITLE
Downloading a prebuilt binary of tree-sitter fails with tree-sitter-cli 0.15.12

### ISSUE THREAD

**Issue by jonhue** [tree-sitter/tree-sitter#470]
Immediately after `0.15.12` got published everything worked fine. But just recently my CI builds started failing with this weird error:

```
Downloading https://github.com/tree-sitter/tree-sitter/releases/download/0.15.12/tree-sitter-linux-x64.gz
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN github-production-release-asset-2e65be.s3.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'github-production-release-asset-2e65be.s3.amazonaws.com'
}
```

Apparently downloading the prebuilt binary for tree-sitter fails. Does anyone have an idea of what might be the reason? `0.15.9` is still working.

https://github.com/quik-lang/tree-sitter-quik/pull/72/checks?check_run_id=270501012#step:4:16

**Comment by maxbrunsfeld** [comment]
I'm able to download the linux binary successfully from [here](https://github.com/tree-sitter/tree-sitter/releases/tag/0.15.12). Maybe you just had a temporary network issue? I saw that the error is `EAI_AGAIN`, and comes from `getaddrinfo`, which is doing DNS name resolution for `github-production-release-asset-2e65be.s3.amazonaws.com`.

**Comment by jonhue** [comment]
That was it 🙈. Thanks!
