### ISSUE TITLE
Mention npx option in docs

### ISSUE THREAD

**Issue by idleberg** [tree-sitter/tree-sitter#476]
In the documentation, I stumbled across [the recommendation](http://tree-sitter.github.io/tree-sitter/creating-parsers#project-setup) to add the path of the _locally_ installed `tree-sitter-cli` to the `PATH` environmental. While this certainly works, I find this a bit unusual.

The way I see it, there are two better options

1. install the CLI globally (for better or worse)
2. make use `npx` to run the CLI

> npx is a tool intended to help round out the experience of using packages from the npm registry — the same way npm makes it super easy to install and manage dependencies hosted on the registry, npx makes it easy to use CLI tools and other executables hosted on the registry. It greatly simplifies a number of things that, until now, required a bit of ceremony to do with plain npm.
>
> [Source](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b)

Let me know what you think. If you agree, I'll gladly submit a PR for this change.

**Comment by maxbrunsfeld** [comment]
The concern with adding documentation about `npx` is that many folks reading these docs are not generally Node.js users. Many of them will likely know what `node` is, and know that `npm` is Node's package manager, but not have heard of `npx`.

I don't want the docs to give people the impression that Tree-sitter is too highly tied to the Node.js ecosystem, or confuse people by listing more dependencies than necessary. I figure that people who already *are* familiar with `npx` can choose to use it anyway, even without the docs suggesting it, but for non-Node-developers, the story is easier to understand if it's just "the tree-sitter executable is just installed in this folder".

Aside from that, `npx` seems like an oddly complex solution to a pretty trivial problem. It adds a bunch of JS files that need to be required every time you run a command, and it requires you to always type an extra word, even though `./node_modules/.bin` to `PATH` in your shell solves the problem really easily and efficiently. I recognize it's mostly a matter of taste though. But to my taste, the `PATH` solution is just better.

**Comment by idleberg** [comment]
I guess there aren‘t many people who work on multiple grammars. I‘m doing just that and that‘s why the PATH method wasn‘t suitable for me.

I mostly use scripts in my package manifests was to run CLI dependencies. I only learned about npx not too long ago and I‘ve had cases where it provided a welcome shortcut. So it‘s worth mentioning in the docs, as sort if a „bonus tip“?

**Comment by maxbrunsfeld** [comment]
Just to clarify, the `PATH` method should work great for developing multiple grammars. Whichever grammar directory you're in, it will use the locally installed `tree-sitter`, just like `npx` would.
