### ISSUE TITLE
tree-sitter cli broken and missing debug information.

### ISSUE THREAD

**Issue by HFSDev** [tree-sitter/tree-sitter#477]
I'm running Windows 7 with MinGW as C/C++ compiler. 
Tree-sitter version:
**tree-sitter 0.15.12 (80008b0bccbddffc8e68f66a5f173ef71fd125e3)**
I'm following the first example in http://tree-sitter.github.io/tree-sitter/creating-parsers. 
My grammar file:
```
module.exports = grammar(
  {
    name: 'entcob',
    rules: {
      source_file: $ => 'hello'
    }
  }
)
```

The cli generates all files but when I issue **tree-sitter parse** I get the following error:
**Failed to load language in current directory
Details:
  Failed to execute C compiler
  O sistema não pode encontrar o arquivo especificado. (os error 2)**

"O sistema não pode encontrar o arquivo especificado" means "File not found".

I missed some debugging info (--debug flag) in the cli so I could pinpoint the error.

**Comment by maxbrunsfeld** [comment]
Tree-sitter couldn't find a C compiler to execute. Do you have `cc` available on your `PATH`? If not, then you need to set the `CC` environment variable to the path to your C compiler.

**Comment by stsewd** [comment]
I found this as well (fedora 31). I fixed it by installing clang, and setting it as my compiler `export CC=/usr/bin/clang`
