### ISSUE TITLE
Repeated named children

### ISSUE THREAD

**Issue by Timmmm** [tree-sitter/tree-sitter#480]
I have a grammar that contains what I would think is a typical sort of thing:

```
    struct: $ =>
      seq(
        "struct",
        field("name", $.identifier),
        "{",
        field("field", repeat($.field)),
        "}",
      ),
```

It generates a tree like this:

```
 (struct [7, 0] - [11, 1]
    name: (identifier [7, 7] - [7, 10])
    field: (field [8, 2] - [8, 45]
      ...
    field: (field [9, 2] - [9, 11]
      ...
    field: (field [10, 2] - [10, 11]
      ... )))
```

So it seems like there can be multiple children with the same name. Fair enough. But [the API](https://docs.rs/tree-sitter/0.3.10/tree_sitter/struct.Node.html#method.child_by_field_name) only lets you get *one* field by name. There's no `children_by_field_name()`.

I thought I could get around it by just looping through all the children and checking their names, but there's not even a way to get the field name of a node! How is this supposed to work?

Some documentation for the API would be nice!

**Comment by maxbrunsfeld** [comment]
Individual syntax nodes don't know their own field names, since that information lives on the parent node. To get the field names of these nodes, you can use `TreeCursor::field_id` or `TreeCursor::field_name`.

Yeah, the rust binding needs docs. I'll copy over the C API docs to the Rust binding soon.

**Comment by Timmmm** [comment]
What if I'm not using the `TreeCursor` though?

Actually in my case I realised I can just loop through all the children and filter on `Node::kind()`, but I still think it would make sense for there to be a `children_by_field_name()` method.

**Comment by maxbrunsfeld** [comment]
Docs are updated: https://docs.rs/tree-sitter/0.4.0/tree_sitter.

If you're accessing multiple child nodes in a loop of any kind, the recommended approach is to use a `TreeCursor`. In higher-level languages like JavaScript, we define helper methods like `children_by_field_name` that use a global `TreeCursor` under the hood, and allocate an Array, but in Rust, I don't really think it makes sense to do that.

Maybe it'd make sense to add a method like this:

```rust
fn children_by_field_name(
    &self,
    field_name: &str,
    cursor: &mut TreeCursor,
) -> impl Iterator<Item = Self>;
```

That way, the caller could be in charge of how/whether to reuse the cursor, and how to store the resulting nodes.

**Comment by maxbrunsfeld** [comment]
https://docs.rs/tree-sitter/0.5.0/tree_sitter/struct.Node.html#method.children_by_field_name.

**Comment by Timmmm** [comment]
That was fast, thanks!
