### ISSUE TITLE
Unexpectedly failed parsing

### ISSUE THREAD

**Issue by SergeevPavel** [tree-sitter/tree-sitter#485]
Hello, I have simple piece of grammar:
```
    source_file: $ => $._symbol
    symbol_namespace: $ => NS_SYMBOL,
    symbol_name: $ => SYMBOL,
    immediate_symbol_name: $ => token.immediate(SYMBOL),
    simple_symbol: $ => $.symbol_name,
    namespaced_symbol: $ => seq($.symbol_namespace,
                                token.immediate("/"),
                                alias($.immediate_symbol_name, $.symbol_name)),
    _symbol: $ => choice($.namespaced_symbol, $.simple_symbol),
```
that as I expect should accept inputs like `foo/bar` as 
```
(source_file [0, 0] - [0, 7]
  (namespaced_symbol [0, 0] - [0, 7]
    (symbol_namespace [0, 0] - [0, 3])
    (symbol_name [0, 4] - [0, 7])))
```
 and `bar` as
```
(source_file [0, 0] - [0, 3]
  (simple_symbol [0, 0] - [0, 3]
    (symbol_name [0, 0] - [0, 3])))
```
but for `bar` I get:
```
(ERROR [0, 0] - [0, 3]
  (symbol_namespace [0, 0] - [0, 3]))
```
Could you explain me, what I do wrong, and why parser does not try to apply `simple_symbol` alternative?
Thank you for your great work.

**Comment by maxbrunsfeld** [comment]
When parsing `foo`, the parser cannot know if `foo` is a `symbol_namespace` or a `symbol_name` until it looks further in the input. It is picking `symbol_namespace` arbitrarily, probably because it is listed earlier in the grammar.

The normal way to do this is use the same fundamental token for both:

```js
namespaced_symbol: $ => seq($.symbol, '/', $.symbol),
symbol: $ => YOUR_SYMBOL_REGEX
```

If you want, you can alias it:

```js
namespaced_symbol: $ => seq(
  alias($.symbol, $.namespace),
  '/',
  $.symbol
)
```

Also, I wouldn't start introducing other restrictions like `token.immediate` unless you determine that you definitely need them.

**Comment by SergeevPavel** [comment]
My guess was that in case of failure with `symbol_namespace` parser will rollback and try another variant.

Unfortunately approach with same symbol for `symbol_namespace` and `symbol_name` is not working for me, because it has different [regexes](https://github.com/SergeevPavel/tree-sitter-clojure/blob/b37314702b2bc3c3af5daa643bed42298a47c4cf/grammar.js#L1).

Also for me is totally unclear, why presence(sic) of  ` _namespaced_symbol` changing the grammar behaviour:
```
const SYMBOL = /[\/\-+.]|([\-+.][a-zA-Z*!_?$%&=<>'\-+.#:][a-zA-Z*!_?$%&=<>'\-+.#:0-9]*)|([a-zA-Z*!_?$%&=<>][a-zA-Z*!_?$%&=<>'\-+.#:0-9]*)/;
const NS_SYMBOL = /[\-+.]|([\-+.][a-zA-Z*!_?$%&=<>'\-+.#:][a-zA-Z*!_?$%&=<>'\-+.#:0-9]*)|([a-zA-Z*!_?$%&=<>][a-zA-Z*!_?$%&=<>'\-+.#:0-9]*)/;

module.exports = grammar({
  name: 'clojure',
  extras: $ => [/[\s,]/],
  rules: {
    source_file: $ => $.symbol,
    _namespaced_symbol: $ => seq(NS_SYMBOL, "/", SYMBOL),
    symbol: $ => choice(SYMBOL, seq(NS_SYMBOL, "/", SYMBOL)),
  }
});
```
When presence, I get error on `foo`, when there is no I get `(symbol [0, 0] - [0, 3])`

**Comment by maxbrunsfeld** [comment]
No, that’s not how LR parsing works. In general, efficient parsing algorithms don’t have this kind of rollback behavior. At the level of tokenization, you need to define things in a way that’s unambiguous.
