### ISSUE TITLE
Whitespace as node

### ISSUE THREAD

**Issue by Kevin-Prichard** [tree-sitter/tree-sitter#497]
I'm looking into using `tree-sitter` for code analysis, and in trying out grammar `tree-sitter-python` via `py-tree-sitter`, I noticed that the whitespace between symbols does not appear as nodes.

For example, in order to reconstruct source from a `tree_sitter.Node`, it appears that, in addition to walking the tree, one must spot the gaps from `end_byte` to `start_byte`, between two `Node`s, and then append those uncaptured strings to your reconstruction buffer.

Am I looking at that correctly?  Is there a better way?  I imagine that extending the grammar to elevate whitespace to be symbols might do the job? (How does Atom reflow source from a `TS` node if whitespace isn't captured??)

Separate-but-related, is `tree-sitter` ideal for code-analysis? What drew me here is the large family of grammars, under the assumption that using the project abstractly (as discussed in docs) could result in a project that can be applied to multiple languages.

Cheers,
Kevin

**Comment by maxbrunsfeld** [comment]
Can you expand on what larger task you're trying to accomplish when you say 'reconstruct source'? In general, you can't reconstruct the source code from the `Tree`, because nodes don't make a copy of their text. So, for example, in order to know the text of an `identifier`, you'd have to consult the original source code using the node's `start_byte` and `end_byte`, as you said.

**Comment by maxbrunsfeld** [comment]
> Separate-but-related, is tree-sitter ideal for code-analysis?

At GitHub, we use Tree-sitter for some kinds of code analysis. I think that it's ideal for the kind of fast, multi-language code analysis that we require. If you're just working with one language/runtime, you may find it simpler to use a more focused tool that is more tightly integrated with that language. But if you are indeed targeting support for multiple languages, and especially if you may not have detailed knowledge about the files that you're analyzing (e.g. Python 3.3 or Python 3.8? C++14 or C++11? Ruby 1.9 or Ruby 2? JavaScript with Babel or plain JavaScript?), then Tree-sitter might be very well suited.

**Comment by Kevin-Prichard** [comment]
> Can you expand on what larger task you're trying to accomplish when you say 'reconstruct source'?

Static analysis and linting. I've got a working engine, which abstracts out how code queries are performed. That is a task internally dependent upon a given AST/CST's data structure, and possibly the backend providing it (like TS queries).  (Separately, a transformation layer to a common [C]UST is also under consideration.)

Refactoring is a secondary goal, hence an interest to 'reconstruct source.'  Another use-case would be format checking, along the lines of `black`, but not as a primary motivation.

The project initially targets the Python languages.  Our current Python CST backend is `redbaron`, which delivers space and line-ending as nodes, permits tree modification, and their trees render back into identical source -including whitespace.

> > is tree-sitter ideal for code-analysis?
>
> ... and especially if you may not have detailed knowledge about the files that you're analyzing (e.g. Python 3.3 or Python 3.8? ...

Differentiating and identifying a source's language version would be very helpful, yes.  I am here because of the breadth of `tree-sitter`.  I'm looking for such a project on which mine can depend.  It looks so close, it appears that positively capturing whitespace is one of the few outstanding questions. I'll probably have a few more as I work on an integration.

**Comment by Kevin-Prichard** [comment]
I have tried both ways- a) inferred whitespace nodes (start_byte/end_byte differences), and b) explicit whitepsace nodes (modifying `tree-sitter-python`'s grammar).

The problems are now obvious:
- a) Inferred whitespace spans produce no nodes, of course, only useful for reproducing source identically. But we could insert whitespace nodes post-hoc.
- b) Adding whitespace to grammar we end up with whitespace nodes everywhere which causes all unit tests fail, and is not of much use for symbolic analysis, but would most likely be ignored in queries.  Plus, it takes 

Third approach: insert whitespace nodes as shadow nodes, appearing alongside siblings of concrete symbol nodes, but as a different type: could they be ignored by iterators and such? That probably means modifying upstream `tree-sitter` source, undesirable.

I could see whitespace being an optional production, configured at build-time, disabled by default to maintain existing behavior.  Are CLI-configured optional symbols possible, @maxbrunsfeld ?

**Comment by maxbrunsfeld** [comment]
I think that you should be able to get all of the information you need from the current API, using start and end positions. Explicit whitespace nodes wouldn't give you any new information.

> But we could insert whitespace nodes post-hoc.

Tree-sitter syntax trees aren't mutable, so refactoring/structural editing would always be something you'd have to build yourself as a separate layer. So I still don't think there would be any advantage of having explicit nodes for every span of whitespace. Am I missing something there?

> I could see whitespace being an optional production, configured at build-time, disabled by default to maintain existing behavior. Are CLI-configured optional symbols possible, @maxbrunsfeld ?

No, I don't think that Tree-sitter should take on that form of complexity for that purpose.

**Comment by Kevin-Prichard** [comment]
Well, in the same

**Comment by Kevin-Prichard** [comment]
> I think that you should be able to get all of the information you need from the current API, using start and end positions. Explicit whitespace nodes wouldn't give you any new information.

They would become queryable, and that is of value for asking format-related questions. Having a common representation for all text would become ideal, in the context of structured queries.

e.g. Asking questions about whitespace that is non-space symbol-adjacent (i.e. for languages having significant whitespace, but not exclusively), using a common query language, with uniform tree node types, would be nice.

You're only getting part of the picture, and I have some thoughts to work out here, clearly.  I'll spend some time working things out, and if anything seems applicable in a generalized way for `tree-sitter`, I'll come back with a PR to better represent what my intents are.  There is more to the picture, and I'll fill that in at another time.

Thanks for being a good sport, Max, and hearing me think out loud. :-)
