### ISSUE TITLE
Don't force local browser to open with web-ui

### ISSUE THREAD

**Issue by thoughtpolice** [tree-sitter/tree-sitter#506]
When using `tree-sitter` over a remote SSH terminal, I'd like to be able to use `tree-sitter web-ui` in order to test my grammar in the browser of my *host* operating system, that is, the system that am using `ssh` from.

Currently, `web-ui` uses the `webbrowser` crate in order to attempt to open the browser on the host tree-sitter is executing on, and it forces this behavior. Because my server is headless and does not run X11, this fails, because `xdg-open`, etc do not work.

I believe this is a relatively simple fix: `webbrowser::open` is simply called with `.unwrap()` here in the [web_ui.rs](https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/web_ui.rs#L40) module, which causes the panic. I believe simply handling this error case rather than `.unwrap`'ing will fix it.

**Comment by maxbrunsfeld** [comment]
That makes sense. Want to open a PR? I think that if the `open` fails, we can just log that same message but move on instead of aborting.
