### ISSUE TITLE
http://tree-sitter.github.io/tree-sitter/ should have a front-and-center link to this repo

### ISSUE THREAD

**Issue by fcurts** [tree-sitter/tree-sitter#508]
The only link I can find is buried under Contributing/Published Packages.

**Comment by SKalt** [comment]
I definitely agree.  Turns out the logo image is a link to this repo too, but there's no way to tell.

Want to reopen this issue [in the tree-sitter.github.io repo](https://github.com/tree-sitter/tree-sitter.github.io/issues)?

**Comment by maxbrunsfeld** [comment]
Good suggestion. Fixed by @kramred in #535.
