### ISSUE TITLE
TCL grammar

### ISSUE THREAD

**Issue by drom** [tree-sitter/tree-sitter#512]
Is anybody interested in joining forces in writing TCL grammar?

**Comment by maxbrunsfeld** [comment]
I'm going to close this one out since I mostly want to use this Issues page as a place to track work that needs to be done on Tree-sitter itself. Let me know if you get a working TCL grammar and I will add it to the docs. Thanks!

**Comment by hinell** [comment]
Ping me out if interested.

**Comment by sogaiu** [comment]
FWIW, seems there is [this](https://github.com/lewis6991/tree-sitter-tcl) these days.
