### ISSUE TITLE
Semantic modifiers

### ISSUE THREAD

**Issue by jonhue** [tree-sitter/tree-sitter#515]
In pretty much all programming languages there exists the notion of modifiers. The most prominent example is probably Java:

```java
private class Test {}
```

Now, with tree-sitter, it is easy to write a grammar to parse this. What is not that easy (or at least not that nice looking) is to extract this information from an abstract syntax tree built by the tree-sitter generated parser.

A while ago a feature was added to make child nodes more easily accessible through named fields. I would love if there were to exist something similar for modifiers.

For example, it would be nice if the string `private` could be marked as a modifier named `private`:

```javascript
class: $ => seq(
  optional(modifier('private', 'private')),
  // ...
)
```

Then if this modifier was used could be made accessible through a field on the belonging node:

```javascript
classNode.isPrivate // == true/false

// or alternatively
classNode.modifiers['private']
```

What do you think?

**Comment by maxbrunsfeld** [comment]
In general, the concept of 'modifiers' is a part of the *semantics* of a language, not its syntax, so I don't think that it is related to Tree-sitter's functionality.

You could use the `field` API to mark the modifiers like this:

```js
class: $ => seq(
  repeat(field('modifier', 'private')),
  // ...
)
```

Then, you could determine if there is a `private` token as follows:

Node.js:

```js
classNode.getModifierNodes().some(n => n.type === "private")
```

Rust:

```rust
class_node.children_by_field_name("modifiers", &mut tree_cursor).any(|c| c.kind() == "private")
```

**Comment by jonhue** [comment]
@maxbrunsfeld won't there be problem when the field is not a node but a string literal instead? E.g. if I wrap literals in fields, those fields won't show up in the output that is used for corpus tests.

**Comment by maxbrunsfeld** [comment]
Even though they don't show up in the corpus tests, they are still accessible via the API. The corpus tests just show the [named nodes](http://tree-sitter.github.io/tree-sitter/using-parsers#named-vs-anonymous-nodes) to make them easier to read, but there are nodes for every string literal.
