### ISSUE TITLE
get_column causes infinite loop

### ISSUE THREAD

**Issue by worudso** [tree-sitter/tree-sitter#516]
I tried `get_column` but it didn't work as I expected.
So I just put `lexer->get_column(lexer);` at the beginning of scan function to check the behavior.
```c
bool tree_sitter_cham_external_scanner_scan(
    void *payload,
    TSLexer *lexer,
    const bool *valid_symbols)
{

  lexer->get_column(lexer);
```
But then for every input it never stops and gives any result neither.
My `tree-sitter-cli` version is 0.16.2.

**Comment by worudso** [comment]
I think I figure out when it happens.
It happens when the lexer reaches EOF.

```c
bool tree_sitter_cham_external_scanner_scan(
    void *payload,
    TSLexer *lexer,
    const bool *valid_symbols)
{
  if(!lexer->eof) {
    lexer->get_column(lexer);
  }
```

After I put a guard before `get_column` call, it worked well.

**Comment by maxbrunsfeld** [comment]
Interesting. Note that `lexer->eof` is a [function](https://github.com/tree-sitter/tree-sitter/blob/ee7c29346ade3de764015b38d562fe5f71bda0b6/lib/include/tree_sitter/parser.h#L49) though, so with that code, `get_column` will never be called.

Try this:

```c
bool tree_sitter_cham_external_scanner_scan(
    void *payload,
    TSLexer *lexer,
    const bool *valid_symbols)
{
  if(!lexer->eof(lexer)) {
    lexer->get_column(lexer);
  }

  // ...
}
```

**Comment by worudso** [comment]
@maxbrunsfeld I've checked it and it's working. If my guess is right, then I think this is a common mistake for beginners and it would be better to document.

**Comment by Razzeee** [comment]
Just stumbled over this again.

```
if (valid_symbols[VIRTUAL_OPEN_SECTION])
  {
      indent_length_stack.push_back(lexer->get_column(lexer));

      lexer->result_symbol = VIRTUAL_OPEN_SECTION;
      return true;
  }
```

Get's stuck causing apps to hang and consume cpu. Running my test case, that gets stuck debug prints this right before `  consume character:0`.

So fixing it like mentioned above works.
