### ISSUE TITLE
Conflicts in RegExp

### ISSUE THREAD

**Issue by worudso** [tree-sitter/tree-sitter#517]
When I made conflicts with the two exactly same RegExps
```javascript
rules: {
    source: $ =>choice($.a, $.b),
    a: $ => /\d+/,
    b: $ => /\d+/,
}
```
Then the error message was as I expected
```
Unresolved conflict for symbol sequence:

  'a_token1'  •  EOF  …

Possible interpretations:

  1:  (a  'a_token1')  •  EOF  …
  2:  (b  'a_token1')  •  EOF  …

Possible resolutions:

  1:  Specify a higher precedence in `a` than in the other rules.
  2:  Specify a higher precedence in `b` than in the other rules.
  3:  Add a conflict for these rules: `a`, `b`
```

But in the cases below, tree-sitter didn't report conflicts.
1. two RegExp which look different but express the same
```javascript
rules: {
    source: $ =>choice($.a, $.b),
    a: $ => /\d+/,
    b: $ => /[0-9]+/,
}
```
2. two RegExp which can match the same string. In this case, '12' for instance.
```javascript
 rules: {
    source: $ =>choice($.a, $.b),
    a: $ => /\d+/,
    b: $ => /\d{1,3}/,
}
```

I'm not sure it's a bug or just an intended behavior.

**Comment by Aerijo** [comment]
Detecting equivalence or subset-ness for arbitrary regular expressions is infeasible. 

Detecting the specific case when they are equal is trivial, and still likely to be useful (e.g. copy and paste that wasn’t fixed up).

**Comment by matthuszagh** [comment]
I'm facing a similar issue. Additionally, tree-sitter uses whichever terminal rule I specify first, and I can't figure out how to force a conflict and use GLR parsing. @Aerijo would you mind expanding on your explanation a bit? I don't quite understand what you mean. Why is it not possible to branch on two rules that both match a token and then discard the failing branch?

I'll provide an additional MWE to show a real use case for this:
grammar.js:
```js
module.exports = grammar({
    name: 'mwe',

    conflicts: $ => [
        [$.a, $.b],
    ],

    rules: {
        source_file: $ => choice(
            $.a,
            seq($.b, $.a),
        ),

        b: $ => /[a-zA-Z]+/,
        a: $ => /[^ \t\n]+/,
    }
})
```
corpus/statements.txt:
```
======================================================================
Test
======================================================================
bfirst a

---
(source_file
  (b)
  (a))
```
If I run `$ tree-sitter generate && tree-sitter test` this works. However, if I change the order of the definitions of `a` and `b` like so,
```js
module.exports = grammar({
    name: 'mwe',

    conflicts: $ => [
        [$.a, $.b],
    ],

    rules: {
        source_file: $ => choice(
            $.a,
            seq($.b, $.a),
        ),

        a: $ => /[^ \t\n]+/,
        b: $ => /[a-zA-Z]+/,
    }
})
```
It fails. The use of `conflicts` does nothing here. `a` and `b` are similar but not identical regexes so I can't make them the same.

**Comment by Aerijo** [comment]
I wasn’t referring to how Tree-sitter handles expressions, I was just explaining why it can detect identical expressions, but not equivalent or subsets. 

Your issue appears to be different to the one originally posted, which just asks about why it handles detecting equivalence the way it does (with no reference to how it uses the expressions to parse anything).

**Comment by matthuszagh** [comment]
Thanks for the reply @Aerijo. I've opened a new issue for it [here](https://github.com/tree-sitter/tree-sitter/issues/518#issue-546054199).

**Comment by maxbrunsfeld** [comment]
GLR parsing isn't applicable to the matching of individual regexes. The process for matching conflicting tokens is described in the docs here: http://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens.

If you want, you could describe in more detail the problem you're trying to solve and *why* you need to have two conflicting tokens like that; I might be able to help suggest a different solution.
