### ISSUE TITLE
GLR parsing for similar regexs

### ISSUE THREAD

**Issue by matthuszagh** [tree-sitter/tree-sitter#518]
I'm experiencing an issue where I'm unable to force GLR parsing for similar (but non-identical) regexs. tree-sitter uses whichever terminal rule i specify first and does not raise a conflict with the other terminal rule. Here's a MWE:

grammar.js:
```js
module.exports = grammar({
    name: 'mwe',

    conflicts: $ => [
        [$.a, $.b],
    ],

    rules: {
        source_file: $ => choice(
            $.a,
            seq($.b, $.a),
        ),

        b: $ => /[a-zA-Z]+/,
        a: $ => /[^ \t\n]+/,
    }
})
```
corpus/statements.txt:
```
======================================================================
Test
======================================================================
bfirst a

---
(source_file
  (b)
  (a))
```
If I run `$ tree-sitter generate && tree-sitter test` this works. However, if I change the order of the definitions of `a` and `b` like so,
```js
module.exports = grammar({
    name: 'mwe',

    conflicts: $ => [
        [$.a, $.b],
    ],

    rules: {
        source_file: $ => choice(
            $.a,
            seq($.b, $.a),
        ),

        a: $ => /[^ \t\n]+/,
        b: $ => /[a-zA-Z]+/,
    }
})
```
It fails. The use of `conflicts` does nothing here. `a` and `b` are similar but not identical regexes so I can't make them the same. Is there a way to use GLR parsing here? Why don't they conflict? Thanks.

**Comment by worudso** [comment]
I posted #517. My original problem was exactly the same as yours indeed.
I knew two tokens are conflicting but there was no way to tell tree-sitter do GLR things(I don't know what exactly they are) on it.
I'm not sure if explicit declaration of conflicts is valid in GLR parsing.

**Comment by maxbrunsfeld** [comment]
The GLR algorithm doesn't apply to ambiguities *within* individual tokens. Tokens are matched by the lexer by a separate process. This matches the normal specification of programming languages - token matching is generally treated as a separate "phase", with its own semantics. The documentation for Tree-sitter's token-matching behavior is here: http://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens.
