### ISSUE TITLE
Infinite memory allocation occured

### ISSUE THREAD

**Issue by bglgwyng** [tree-sitter/tree-sitter#520]
I was working on #519 trying some rules and I found tree-sitter didn't stop and keep allocating memory.
Here is the source code
https://github.com/bglgwyng/tree-sitter-sandbox/tree/infinite-memory-allocation
> The branch is `infinite-memory-allocation`!

Could you try
```shell
tree-sitter generate && tree-sitter parse example-file-1
```
and check the memory usage of tree-sitter?

Is that a bug or the problem of my grammar definition?

**Comment by dundargoc** [comment]
Seems to work fine now when I tested it.

**Comment by amaanq** [comment]
I can confirm this issue no longer occurs.
