### ISSUE TITLE
prec not behaving as expected

### ISSUE THREAD

**Issue by Srekel** [tree-sitter/tree-sitter#522]
Not sure if I'm simply not understanding how to use prec, or if there's a bug, but... Here's the relevant part of my grammar:

```
        list_item: $ => seq(
            choice(
                $.value_str,
                $.keyword
            ),
            $.newline
        ),
        value_str: $ => prec(-10, /[^@].*/),
        keyword: $ => /@\S+/,
```

Given this:
```
  lol asd
  @LOL
  lolasd
```

It correctly resolves it as value_str, keyword, value_str.

But if I remove the [^@], it thinks all three are value_str. I feel like it should "pick" `keyword` first, if possible...? :)

**Comment by Srekel** [comment]
Ah, prec doesn't mean what I thought, and I suppose that makes sense! 

I thought it was precedence as in "these two rules match, which one gets picked", but I guess it's "_in the actual language_, which of these has precedence"

Follow-up question: Are rules guaranteed to be evaluated in the order they are specified? If I switched the order to this, it works:


        value_str: $ => /.*/,
        keyword: $ => /@\S+/,

**Comment by maxbrunsfeld** [comment]
Check out this section of the docs: http://tree-sitter.github.io/tree-sitter/creating-parsers#lexical-analysis; it explains some of this. Let me know if you are still having problems.

**Comment by maxbrunsfeld** [comment]
Ok, I'm going to close this one out for now, as I think Tree-sitter is behaving as expected, but if you are seeing behaviors that still might be bugs, we can definitely reopen. Thanks!
