### ISSUE TITLE
grammar-schema.json does not allow `type: "FIELD"`

### ISSUE THREAD

**Issue by SKalt** [tree-sitter/tree-sitter#523]
[tree-sitter-bash's grammar.json](https://github.com/tree-sitter/tree-sitter-bash/blob/master/src/grammar.json) has many nodes like 
```
{
  "type": "FIELD",
  "name": "body",
  "content": {
    "type": "SYMBOL",
    "name": "_statement"
  }
}
```
Nothing in to [grammar-schema.json](https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/generate/grammar-schema.json) allows for `type: "FIELD"`. Should I add extend the definition of `rule` to include
```JSON
{
  "field-rule": {
    "required": ["name", "type", "content"],
    "properties": {
      "name": { "type": "string" },
      "type": {
        "type": "string",
        "pattern": "^FIELD$"
      },
      "content": {
        "$ref": "#/definitions/rule"
      }
    }
  }
}
```
?

**Comment by maxbrunsfeld** [comment]
Yes!
