### ISSUE TITLE
Document supertypes in the parser creation page and in grammar-schema.json

### ISSUE THREAD

**Issue by SKalt** [tree-sitter/tree-sitter#524]
Looks like supertypes defined in [the JS DSL](https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/generate/dsl.js#L344) are missing from the [grammar creation docs](https://github.com/tree-sitter/tree-sitter/blob/master/docs/section-3-creating-parsers.md) and [grammar-schema.json](https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/generate/grammar-schema.json) as well.

Creating a separate ticket from the inspiration, #393, since that was a question and these are bug/doc fixes.

**Comment by maxbrunsfeld** [comment]
Fixed via #542.
