### ISSUE TITLE
Wish: CHANGELOG

### ISSUE THREAD

**Issue by Hocdoc** [tree-sitter/tree-sitter#527]
Thanks for creating Tree-Sitter, it's really useful for our project.

Would it be possible to create a CHANGELOG or add a release note what has changed in a new version?

**Comment by WhyNotHugo** [comment]
+1 on this.

0.19 seems to have changed how tree-sitter behaves, but I can't quite figure out _what_ or _how_.

**Comment by stevenbarragan** [comment]
I suggest to automate it by [git cliff](https://github.com/orhun/git-cliff) using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by ahlinc** [comment]
@stevenbarragan Thanks! That's one of the options I've discovered, but it requires some work for adaptation.

**Comment by Wilfred** [comment]
I'd find this super useful too.

Skimming the 97 commits in https://github.com/tree-sitter/tree-sitter/compare/v0.19.5...v0.20.0 it looks like 0.20.0 added:

* a bunch of CLI fixes and improvements
* some additional APIs on Query, QueryCursor
* one additional API on TSNode: https://github.com/tree-sitter/tree-sitter/commit/dffee22736ef89f606f0d02241f0dcb754890edf

**Comment by dundargoc** [comment]
I assert that consistently generating meaningful changelogs is impossible unless the treesitter project starts using and enforcing the use of conventional commits. It will not happen otherwise because it's too much manual work that is too boring for anyone to bother.
