### ISSUE TITLE
🎨 Diffrent `Syntax Highlighting` for each language... Is that possible?

### ISSUE THREAD

**Issue by rediffusion** [tree-sitter/tree-sitter#529]
✌️ Hi! 
🔌 Interesting expansion.

As an example, I'll take the IDE called «[NotePad++](https://notepad-plus-plus.org/downloads/)».
 _See screenshots below_:

![image](https://user-images.githubusercontent.com/30071027/71870673-e2fdf080-3127-11ea-8c28-428853d86fee.png)

Now I put here some `code`, then I switch to other languages...

## C#

![image](https://user-images.githubusercontent.com/30071027/71933856-2605a580-31b4-11ea-903e-b45e1b6573c9.png)

## JavaScript

![image](https://user-images.githubusercontent.com/30071027/71934009-8268c500-31b4-11ea-94f3-b53dbf21d421.png)

## AutoHotkey

![image](https://user-images.githubusercontent.com/30071027/71934110-c78cf700-31b4-11ea-935c-e5f74da6bfba.png)

## C++

![image](https://user-images.githubusercontent.com/30071027/71934169-ee4b2d80-31b4-11ea-8277-a71d5d36a757.png)

## CSS

![image](https://user-images.githubusercontent.com/30071027/71934273-25b9da00-31b5-11ea-93bf-65b363112661.png)

## HTML 

![image](https://user-images.githubusercontent.com/30071027/71934407-687bb200-31b5-11ea-9fc9-ce945acc25f0.png)

 Different syntax, color, style, font, weight, brackets... etc.
 I want to see some good manuals to do these for «VS Code».

 Best Regards! 🍻👍

**Comment by patrickt** [comment]
Hi there. Tree-sitter is indeed a tool that you can use to build syntax highlighting support for a text editor, but integration into an existing editor is a process that depends much more on the editor than tree-sitter itself. As such, we’re not really in a position to provide detailed manuals on how to integrate your text editor, beyond the [official documentation](http://tree-sitter.github.io/tree-sitter/using-parsers) on using the parser API.

If you’re looking for VS Code integration, you might want to look at the [extension for VSCode on the Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-tree-sitter). The [issue tracking native support](https://github.com/Microsoft/vscode/issues/50140) may also be of interest to you. Please note that [Atom](https://atom.io) already provides its highlighting through tree-sitter.

**Comment by patrickt** [comment]
I’m going to close this issue for now, but please feel free to leave further comments in this thread.

**Comment by rediffusion** [comment]
@patrickt 

> but integration into an existing editor is a process that depends much more on the editor than tree-sitter itself. 

I don't need for "Notepad++" I need for «VS Code». It was just an example cuz in "Notepad++" I can do with `Syntax Highlighting` everything what I want.

**Comment by Arcanemagus** [comment]
The second paragraph of the post you are quoting goes over current support in VS Code for Tree-sitter.
