### ISSUE TITLE
Dropping `QueryCursor` leads to dangling pointers

### ISSUE THREAD

**Issue by Ryan1729** [tree-sitter/tree-sitter#530]
Shortly after integrating tree-sitter into a rust program of mine I ran into illegal memory access issues and sometimes just getting ridiculous numbers out of `Node` methods like `end_byte`. 

After some time I was able to narrow it down to the fact I wrote code of this rough form:

```rust
let nodes: Vec<&Node> = Vec::new();

if let Some(r_t) = rust_tree.as_ref() {
    let mut query_cursor = QueryCursor::new();

    nodes = query_cursor.matches(
        &query,
        r_t.root_node(),
        text_callback,
    ).flat_map(|q_match| 
        q_match.captures.iter().map(|q_capture| &q_capture.node)
    ).collect();
}

// ... do stuff with `nodes`
```

and if I move `query_cursor` outside of the `if let` block so it is not droped quite so soon the issues seem to disappear.

I have a small program that reproduces this issue in [this repo](https://github.com/Ryan1729/tree-sitter-dangling-pointers).

Obviously it would be nice if doing something like this did not result in dangling pointers/other weirdness. Or if `QueryCursor` had a marked lifetime such that the rust compiler prevented this kind of bug.

But on the assumption that doing something like that would be difficult, I think at least some kind of warning in the `QueryCursor` docs would be appropriate. Something like "Warning: This must live at least as long as the `QueryMatches` or `QueryCaptures` produced by its methods."

**Comment by maxbrunsfeld** [comment]
Wow, my apologies for the mistake, an I really appreciate the report. I’ll let you know when this is fixed.

**Comment by maxbrunsfeld** [comment]
In the meantime, I’d recommend storing the nodes by value (as opposed to keeping a vector of node references) as they are small, cheap objects which are meant to be passed around by value.

**Comment by maxbrunsfeld** [comment]
Ok `0.6.1` has the lifetimes fixed.

**Comment by Ryan1729** [comment]
Just to be sure I tried compiling the old incorrect version of my code with `0.6.1` and it gives me a nice, descriptive, compile error. 

Thank you for fixing it, and for all your other work on tree-sitter!
