### ISSUE TITLE
The build-wasm subcommand does not work within Docker on windows

### ISSUE THREAD

**Issue by meakbiyik** [tree-sitter/tree-sitter#532]
Hi, I am trying to build the .wasm file for a custom parser, on Windows 10 with Docker. I failed to find proper documentation on that but from what I saw it should be pretty straightforward, just running `tree-sitter build-wasm` after `tree-sitter generate` in the language folder. Generate command works perfectly, the tests are running without an error, but when it comes to the building part I get this error:

`emcc command failed - shared:ERROR: src\parser.c: No such file or directory ("src\parser.c" was expected to be an input file, based on the commandline arguments provided)`

Beware that this is not a file or directory issue as I would also encounter the error during the generate or test step, and also the error is different if I enter the path in a wrong way, e.g.:

`Failed to read grammar file "C:\\Users\\---\\Documents\\GitHub\\---\\src\\server\\---_server\\---_tree_sitter\\error\\src\\grammar.json"
Details:
  The system cannot find the path specified. (os error 3)`

I suspect that it has something to do with emcc but I can't be sure. Any help would be appreciated.

**Comment by maxbrunsfeld** [comment]
If you just run `emcc -o test.wasm src/parser.c` directly, what do you get? There are more flags used in reality (see [here](https://github.com/tree-sitter/tree-sitter/blob/ee7c29346ade3de764015b38d562fe5f71bda0b6/cli/src/wasm.rs#L65-L82)). It'd be useful to see if you get the same "no such file" error that way.

**Comment by meakbiyik** [comment]
Hm got something interesting:

`src/parser.c:1:10: error: 'tree_sitter/parser.h' file not found with <angled> include; use "quotes" instead
#include <tree_sitter/parser.h>
         ^~~~~~~~~~~~~~~~~~~~~~
         "tree_sitter/parser.h"
1 error generated.
shared:ERROR: 'C:/Users/ErenAkbiyik/Documents/GitHub/emsdk/upstream/bin\clang.exe -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRIPTEN_tiny__=6 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystemC:\Users\ErenAkbiyik\Documents\GitHub\emsdk\upstream\emscripten\system\include\libcxx -Xclang -isystemC:\Users\ErenAkbiyik\Documents\GitHub\emsdk\upstream\emscripten\system\lib\libcxxabi\include -Xclang -isystemC:\Users\ErenAkbiyik\Documents\GitHub\emsdk\upstream\emscripten\system\include\compat -Xclang -isystemC:\Users\ErenAkbiyik\Documents\GitHub\emsdk\upstream\emscripten\system\include -Xclang -isystemC:\Users\ErenAkbiyik\Documents\GitHub\emsdk\upstream\emscripten\system\include\libc -Xclang -isystemC:\Users\ErenAkbiyik\Documents\GitHub\emsdk\upstream\emscripten\system\lib\libc\musl\arch\emscripten -Xclang -isystemC:\Users\ErenAkbiyik\Documents\GitHub\emsdk\upstream\emscripten\system\local\include -Xclang -isystemC:\Users\ErenAkbiyik\.emscripten_cache\wasm-obj\include -DEMSCRIPTEN src/parser.c -Xclang -isystemC:\Users\ErenAkbiyik\Documents\GitHub\emsdk\upstream\emscripten\system\include\SDL -c -o C:\Users\ERENAK~1\AppData\Local\Temp\emscripten_temp_pycklc00\parser_0.o -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr' failed (1)`

And by the way, for the exact same structure build-wasm ran without any problems via WSL-Ubuntu on the machine.

**Comment by maxbrunsfeld** [comment]
Ok, that new error just means that some flags are missing, in particular the `-I` flags, which add header directories. Try adding `-I src`, and maybe the rest of the flags from that link I posted. That means that it *is* successfully finding `src/parser.c` at least.

I think this has to do with the path delimiter: `/` for posix and `\` for windows. Does it work if you use backslashes as the path delimiter? I'm not very familiar with docker on windows.

**Comment by meakbiyik** [comment]
Oh well, after running more than a thousand variations of the command, here's the only one that works (not including other params of course, they do not cause any issue) :

``emcc -o test.wasm -I src src/parser.c``

Agony to work with windows on these topics, really...

**Comment by meakbiyik** [comment]
Yup it worked:

``emcc -o test.wasm -I src src/parser.c``

Agony to work with windows on these topics, really... But thanks a lot!

**Comment by maxbrunsfeld** [comment]
Hmm, I wonder if your shell is automatically converting one path delimiter to the other, but that is not working when spawning `emcc` directly from rust. I think that if we wanted to fix this, we may have to add some retry logic on windows that will try with both `/` and `\`.

**Comment by meakbiyik** [comment]
That certainly can be the case. Let me know if you need any more information, tree-sitter surely requires some Windows support :)

**Comment by jeremyong** [comment]
This bug is still an issue and it's compounded by the fact that other build environments with recent Emscriptem installs fail due to https://github.com/tree-sitter/tree-sitter/issues/1560

**Comment by Remco-Schoeman** [comment]
On windows 11 / Visual Studio Code this error might be due to the emscripten SDK not being properly installed

# Symptoms

In the embedded VS Code terminal below error appeared after 
```
PS C:\dev\tree-sitter-test> tree-sitter build-wasm
emcc command failed - emcc: error: src\parser.c: No such file or directory ("src\parser.c" was expected to be an input file, based on the commandline arguments provided)
```
however, this seems to be a misleading error, because this also happens in that same terminal:
```
PS C:\dev\tree-sitter-test> emcc
emcc: The term 'emcc' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
# Possible Solution

If you've just installed emscripten using `choco install emscripten` VS Code might not have picked up the newly adjusted PATH variables or choco might not have updated the PATH variable properly.

the output of `($env:Path).split(";")` should include these paths:
```
C:\<path>\<to>\emsdk 
... some more emsdk paths ...
C:\<path>\<to>\emsdk\upstream\emscripten
```
if not: the PATH environment variable is what needs fixing. 

You might need to do one or more of the following:

* Restart the embedded terminal in VS Code
* Restart VS Code
* Restart Windows
* Update the PATH environment variable manually so that `emcc` can be found on the path

**Comment by mnpenner** [comment]
Why is this closed? Looks like it's still an issue:

```
> npx tree-sitter build --wasm --docker
emcc: error: parser.c: No such file or directory ("parser.c" was expected to be an input file, based on the commandline arguments provided)
emcc command failed
```

Tried that in PowerShell. If I try from WSL, I get a different error:

```
❯ npx tree-sitter build --wasm --docker
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: spawn .../tree-sitter-kram/node_modules/tree-sitter-cli/tree-sitter ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn .../tree-sitter-kram/node_modules/tree-sitter-cli/tree-sitter',
  path: '.../tree-sitter-kram/node_modules/tree-sitter-cli/tree-sitter',
  spawnargs: [ 'build', '--wasm', '--docker' ]
}

Node.js v20.17.0
```

**Comment by sogaiu** [comment]
This particular error:

> emcc: error: parser.c: No such file or directory ("parser.c" was expected to be an input file, based on the commandline arguments provided)
emcc command failed

suggests that `parser.c` is missing.  Many grammar repositories provide this but some don't.

It's possible this might be addressed by executing `tree-sitter generate` for the grammar in question.

There is a bit more about this topic [here](https://github.com/sogaiu/ts-questions/blob/98536e18af4da0560a543aab63f4bffa9ca2dbe2/questions/should-parser-source-be-committed/README.md) if interested.

**Comment by mnpenner** [comment]
It's my own repository. I'm trying to create a language. `parser.c` exists under `src/`, where tree sitter put it.

I did eventually get it working with [Remco-Schoeman](https://github.com/Remco-Schoeman)'s instructions, but not with Docker. Had to install emscripten on Windows. Perhaps the Docker solution isn't mounting the files?

**Comment by sogaiu** [comment]
Glad to hear you managed via a work-around.

I was totally off, sorry about that (^^;
