### ISSUE TITLE
Parser fails on for loop syntax with line continuation

### ISSUE THREAD

**Issue by flandraco** [tree-sitter/tree-sitter#539]
Consider the simple example:
```
#!/bin/bash

for w in\
  NAME PLACE\
  ;do
  echo $w
done
```

This will fail with:
`/!\ Syntax error: expected "word" somewhere in the file [4, 13]`

The code should be equivalent (just disolve 2nd line continuation) to:
```
#!/bin/bash

for w in\
  NAME PLACE ;do
  echo $w
done
```

Yet there is no error flagged in this case.
The error also disappears when inserting a space right in front of the line continuation:
```
#!/bin/bash

for w in\
  NAME PLACE \
  ;do
  echo $w
done
[test.sh.txt](https://github.com/tree-sitter/tree-sitter/files/4207833/test.sh.txt)


```

**Comment by maxbrunsfeld** [comment]
This repository is for the Tree-sitter, the core parsing library.

It looks like you've found in `tree-sitter-bash`, the bash parser. Can you open this issue on that repository? http://github.com/tree-sitter/tree-sitter-bash.
