### ISSUE TITLE
Feature request: typescript definition for the DSL

### ISSUE THREAD

**Issue by SKalt** [tree-sitter/tree-sitter#541]
**Why**: to give earlier, more informative feedback when writing a `grammar.js` in an IDE that understands typescript. Feedback might come in the form of error messages on incorrect DSL usage or hover-over documentation of specific DSL functions.

**How**: Either provide a typescript stub file as in PR #479 or rewrite the DSL in typescript as I've done at [github.com/skalt/ts-dsl-tree-sitter](https://github.com/skalt/ts-dsl-tree-sitter).  Note that the port of the DSL exactly reproduces the current behavior of the DSL (see the [test setup](https://github.com/SKalt/ts-dsl-tree-sitter/blob/91294bcd55fd2b99296d17a2ce280065d1656666/test/test.js) and [test results](https://travis-ci.com/SKalt/ts-dsl-tree-sitter/jobs/287620918)).

Adding stubs would require:
- including the .d.ts file in the NPM deploy of `tree-sitter-cli`
- trusting that the stub file correctly represents the activity of `dsl.js`.

Adopting the TypeScipt port of the DSL would involve:
- adding a build step to the NPM deploy of `tree-sitter-cli`
- adopting the tests of that the ported DSL creates `grammar.json`s as expected by other `tree-sitter-$LANG` packages.

I'm hoping the port and its test suite will make tweaking the JS DSL easier in the future.

**Comment by jacobwgillespie** [comment]
I've opened #658 to implement stubs, as a place to start. 🙂

**Comment by SKalt** [comment]
closed by PR #658
