### ISSUE TITLE
Compiling a tree-sitter parser that defines cpp source will break on linking a rust object file due to name mangling

### ISSUE THREAD

**Issue by alyssaverkade** [tree-sitter/tree-sitter#543]
Hello!

I should start off by saying that I have a potential fix for this, but I wanted to make sure my approach is correct before I submitted a PR!

#### Repro
I was trying to use the `tree-sitter-ruby` parser in a rust program on MacOS `10.14.6` with the following contents using `cc` version `1.0.50` and `tree-sitter` version `0.6.1` (and clang `1100.0.33.12`):

`git submodule add --depth 1 https://gitub.com/tree-sitter/tree-sitter-ruby`
`cd tree-sitter-ruby && npm i && cd -`

```rust
// build.rs
use std::path::PathBuf;

fn main() {
    let dir: PathBuf = ["tree-sitter-ruby", "src"].iter().collect();

    cc::Build::new()
        .include(&dir)
        .file(dir.join("parser.c"))
        .file(dir.join("scanner.cc"))
        .compile("treesitter-ruby");
}

```

```rust
// main.rs
use tree_sitter::{Language, Parser};

extern "C" {
    fn tree_sitter_ruby() -> Language;
}

fn main() {
    let src = "def foo; end";
    let mut parser = Parser::new();
    let ruby = unsafe { tree_sitter_ruby() };
    parser.set_language(ruby).unwrap();
    let tree = parser.parse(src, None).unwrap();
    println!("{:?}", tree);
}
```

Compiling this spawns the cthulhu of c-based ffi:
```
 Undefined symbols for architecture x86_64:
            "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__grow_by(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)", referenced from:
                std::__1::enable_if<(__is_forward_iterator<char const*>::value) && (__libcpp_string_gets_noexcept_iterator<char const*>::value), std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&>::type std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::assign<char const*>(char const*, char const*) in libtreesitter-ruby.a(scanner.o)
            "___cxa_allocate_exception", referenced from:
                std::__1::__throw_length_error(char const*) in libtreesitter-ruby.a(scanner.o)
# ...
 NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
            "operator delete(void*)", referenced from:
                _tree_sitter_ruby_external_scanner_create in libtreesitter-ruby.a(scanner.o)
                _tree_sitter_ruby_external_scanner_destroy in libtreesitter-ruby.a(scanner.o)
                std::__1::_DeallocateCaller::__do_call(void*) in libtreesitter-ruby.a(scanner.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Upon seeing this I figured that the problem was the `cc` crate passing something akin to `-x c` and encountering the `scanner.cc` file. Subsequently I amended the `build.rs` to the following:
```rust
// ...
    cc::Build::new()
        .include(&dir)
        .file(dir.join("parser.c"))
        .cpp(true)
        .file(dir.join("scanner.cc"))
// ...
```
Recompiling yielded:
```
 = note: Undefined symbols for architecture x86_64:
            "_tree_sitter_ruby", referenced from:
                the_gay_agenda::main::h999ead092fe89c90 in the_gay_agenda-42dd7df84d8eb28e.2uu9kkrawj6105ln.rcgu.o
               (maybe you meant: _tree_sitter_ruby_external_scanner_scan, _tree_sitter_ruby_external_scanner_destroy , _tree_sitter_ruby_external_scanner_create , _tree_sitter_ruby_external_scanner_serialize , _tree_sitter_ruby_external_scanner_deserialize )
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
 So now I knew _some_ symbols were being (un)mangled correctly, so wondering what was actually being emitted, I ran `cargo clean && cargo b -q && find target -name "libtreesitter-ruby.a" | xargs nm` which gave me:
```
 ./target/debug/build/the_gay_agenda-d324970c780ea84e/out/libtreesitter-ruby.a(parser.o):
0000000000000000 T __Z16tree_sitter_rubyv
                 U __Z38tree_sitter_ruby_external_scanner_scanPvP7TSLexerPKb
                 U __Z40tree_sitter_ruby_external_scanner_createv
                 U __Z41tree_sitter_ruby_external_scanner_destroyPv
                 U __Z43tree_sitter_ruby_external_scanner_serializePvPc
                 U __Z45tree_sitter_ruby_external_scanner_deserializePvPKcj
# ...
./target/debug/build/the_gay_agenda-d324970c780ea84e/out/libtreesitter-ruby.a(scanner.o):
# ...
0000000000000000 T _tree_sitter_ruby_external_scanner_create
0000000000000c40 T _tree_sitter_ruby_external_scanner_deserialize
0000000000000ee0 T _tree_sitter_ruby_external_scanner_destroy
0000000000000080 T _tree_sitter_ruby_external_scanner_scan
```
Which made it plain that `parser.c` was not being demangled like `scanner.cc` was. Upon investigation, `scanner.cc` was `extern "C"`ing its prototypes whereas `parser.c` was not.

Applying the following patch to `tree-sitter-ruby` will make the program compile (assuming HEAD is pointing to `eb2b6225bfb80010f2e4cbd27db8c6f3775230b5`):
```
diff --git a/src/parser.c b/src/parser.c
index 427f9b5..de21519 100644
--- a/src/parser.c
+++ b/src/parser.c
@@ -193945,17 +193945,19 @@ static TSParseActionEntry ts_parse_actions[] = {
   [4573] = {.count = 1, .reusable = true}, SHIFT(1457),
 };
 
+extern "C" {
 void *tree_sitter_ruby_external_scanner_create(void);
 void tree_sitter_ruby_external_scanner_destroy(void *);
 bool tree_sitter_ruby_external_scanner_scan(void *, TSLexer *, const bool *);
 unsigned tree_sitter_ruby_external_scanner_serialize(void *, char *);
 void tree_sitter_ruby_external_scanner_deserialize(void *, const char *, unsigned);
+}
 
 #ifdef _WIN32
 #define extern __declspec(dllexport)
 #endif
 
-extern const TSLanguage *tree_sitter_ruby(void) {
+extern "C" const TSLanguage *tree_sitter_ruby(void) {
   static TSLanguage language = {
     .version = LANGUAGE_VERSION,
     .symbol_count = SYMBOL_COUNT,
```

#### A possible solution

After reading the source of the cli (which, from what I understand, is what generates the `parser.c` file), I discovered that I _could_ amend the `Generator::add_parser_export` method  in `cli/src/generate/render.rs` to recreate output akin to the preceding patch (eg `#ifdef __cplusplus`). 

However, with this chain being the only interaction I've ever had with the project, I wanted to get some feedback on whether the generator was the appropriate layer to be targeting a fix for this issue. For example I could also handle this by amending the `binding_rust` docs to make `cc` compile the files independently and then update the archive (which was what was recommended here: https://github.com/tree-sitter/tree-sitter/issues/429#issuecomment-522693333) I'm not sure how I would do this with the `cc` api due to the builder being applicative-esque)).

What do y'all think about this? I'm also wondering if I am completely misunderstanding something, please tell me if that is the case!

**Comment by maxbrunsfeld** [comment]
Typically, when using these parsers from Rust, I just create two separate ‘cc’ Build objects: one for all of the C sources, and one for all of the C++ sources.

As far as I understand, this is not avoidable. The parser.c files are not valid C++ because they use ‘designated initializer’ syntax. Clang may allow this as a C++ extension, but in general it is only part of the C language, not C++. I’m reluctant to migrate away from this syntax because it improves readability in some cases, but I may be open to it.

Does that make sense? I don’t think that adding an extern “c” qualifier, because the file is not currently valid c++.

**Comment by maxbrunsfeld** [comment]
Thanks for bringing this up though; it probably needs to at least be documented, since several of the parsers contain C++ code, and it requires using cc::Build in a way that differs from most of the ‘cc’ docs (two separate ‘compile’ calls).

**Comment by alyssaverkade** [comment]
Thank you and yeah that does makes sense!

I didn't know that designated initializers were non-standard until you pointed it out (thanks!), so I went and looked up what compilers support it (if any). It turns out that designated initializer support (with the caveat of the members having to be initialized in the order they're declared) has been supported in [clang++ since 4.7, g++ since 3.0, and msvc relatively recently with 16.1 (the first patch release of VS 2019)](https://en.cppreference.com/w/cpp/compiler_support)! It also turns out that designated initializers are officially in the C++ 20 standard as a means of aggregate initialization (the previous caveat still applies though)!!

I'm not sure what version of the standard/what compilers you want to support, but if that's doesn't cover the footprint you're looking for -- I can experiment with the two compilation instances tomorrow (later today) and submit a patch for the docs after that!

Also thank you for making this!

**Comment by maxbrunsfeld** [comment]
Oh wow, I had not heard about the C++20 thing; that's awesome. And also those details about gcc and msvc are super helpful. In that case, I'd be open to a PR that makes `parser.c` link correctly when compiled as C++. That'd be a nice simplification, especially for rust projects using `cc`.

**Comment by maxbrunsfeld** [comment]
Fixed via #548. Nice work!

**Comment by jessegrosjean** [comment]
I'm generating with tree-sitter-cli-0.16.5 on macOS. I see `#ifdef __cplusplus` in generated parse.c file, so I think I'm getting this fix. I then compile in rust `build.rs` like this:

```
    cc::Build::new()
        .cpp(true)
        .include(&dir)
        .file(dir.join("scanner.cc"))
        .file(dir.join("parser.c"))
        .compile(&grammar);
```

And it works, but gives a warning:

```
warning: clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
```

Is that expected/avoidable?

**Comment by jessegrosjean** [comment]
Just found that if I add `-xc++` then the warning goes away:

```
cc::Build::new()
    .cpp(true)
   .flag("-xc++")
   ...
```

**Comment by Timmmm** [comment]
@jessegrosjean Actually your solution works for Clang, but not for GCC. You get a load of errors like this:

> sorry, unimplemented: non-trivial designated initializers not supported

However this worked for me (thanks @maxbrunsfeld  for the tip):

```
    cc::Build::new()
        .cpp(true)
        .include(&dir)
        .file(dir.join("scanner.cc"))
        .compile("tree_sitter_yaml_scanner");

    cc::Build::new()
        .cpp(false)
        .include(&dir)
        .file(dir.join("parser.c"))
        .compile("tree_sitter_yaml_parser");
```
