### ISSUE TITLE
Give nodes a unique identifier?

### ISSUE THREAD

**Issue by Gregoor** [tree-sitter/tree-sitter#544]
My use case is out of the ordinary, so feel extra free to just close this. But since this has been a headscratcher for me for a while, I thought I'd at least write it down:

Given an arbitrary AST node, I'd like to find its position in the grammar's rules and iterate from there in any direction. I've ripped out the grammar/rule code and just copied it into my project (as those weren't exposed). Unfortunately I think I'd currently have to implement something like breadth-first search to find a node kind's position in the rules. So that's where I had the thought "what if nodes were uniquely tagged such that the grammar could just pull up the relevant position within the rules?".

Now again, this is probably more of a sanity-check than a feature request, as I doubt this is close to any of GHs use-cases. If I were to fork tree-sitter and add the feature myself, do you have some pointers for me?

**Comment by maxbrunsfeld** [comment]
Do you mean find the line number of a given rule in grammar.js?

**Comment by Gregoor** [comment]
While trying to answer (in the negative) I noticed that my thinking about what I want is flawed. For posterity here's what I thought I wanted, but I'm just gonna close this again as I clearly have more things to figure out:

Given code,
```javascript
n = 23;
```
an AST and
```json
program [0, 0] - [1, 0])
  expression_statement [0, 0] - [0, 7])
    assignment_expression [0, 0] - [0, 6])
      left: identifier [0, 0] - [0, 1])
      right: number [0, 4] - [0, 6])
```
the related rules
```javascript
rules = {
  expression_statement: $ => seq(
    $._expressions,
    $._semicolon
  ),
  _expression: $ => choice(
    $.assignment_expression,
  ),
  assignment_expression: $ => prec.right(PREC.ASSIGN, seq(
    field('left', choice($.parenthesized_expression, $._lhs_expression)),
    '=',
    field('right', $._expression)
  ))
}
```
I thought I wanted to have an API that returns an iterator from within a certain rule. For example:

```rust
let grammar: InputGrammar = parse_grammar(&grammar_string);
let rule = grammar.variables.iter().find(|variable| variable.name == "assignment_expression")?;
// new API:
let iter = rule.iter_from(ast_node_assignment_right.unique_id)?;
assert!(iter.clone().rev().next()? == Some(Rule::String("=")));
```
But that doesn't make any sense, as the right assignment node is just a regular ol' number node, with no relation to the `assignment_expression` rule.

Anyway thanks for entertaining my rubberducking and for the great parser!
