### ISSUE TITLE
Alias not being applied to seq

### ISSUE THREAD

**Issue by anhangaba** [tree-sitter/tree-sitter#545]
The grammar:

```
module.exports = grammar({
    name: 'issue545',

    rules: {
        source_file: $ => seq(
            '=>',
            alias(seq(
                optional($.foo),
                optional($.bar),
            ),$.foobar),
            '.'
        ),

        foo: $ => 'foo',
        bar: $ => 'bar',

    }
});
```

I would expect the alias `$foobar` to be applied to the `seq` rule. Instead it is being applied to each `optional` rule.

The input:

```
=> foo bar.
```

Produces:

```
(source_file [0, 0] - [1, 0]
  (foobar [0, 3] - [0, 6])
  (foobar [0, 7] - [0, 10]))
```

I was expecting:
```
(source_file
  (foobar
    (foo) (bar)))
```

Is that the expected behavior? If it so, how can achieve the expected result (notice it can be an empty rule)? Do I need to write a rule that matchs either one and both (or there is a simple way to achieve that?).

**Comment by maxbrunsfeld** [comment]
Yeah, that is the expected behavior. Alias is just for giving a rule a different name. If you want a foobar node in the syntax tree, you can just add a separate rule for foobar, which matches either foo or bar or both. Just a regular ‘choice’ rule should do it.
