### ISSUE TITLE
Feature request - add support to generate Rust code instead

### ISSUE THREAD

**Issue by XVilka** [tree-sitter/tree-sitter#546]
I searched through issues and wasn't able to find anything similar surprisingly.

It would be awesome to be able to reuse the same corpus in both C and Rust languages.

**Comment by maxbrunsfeld** [comment]
There's no need to generate Rust code to use Tree-sitter from Rust. It's very easy to use the C parsers. That's what the Tree-sitter CLI itself does, and we do the same thing for syntax highlighting at GitHub (via the `tree-sitter-highlight` crate). Am I missing something? Do you want to explain your use case more?
