### ISSUE TITLE
Get TSSymbol for many names

### ISSUE THREAD

**Issue by ret2libc** [tree-sitter/tree-sitter#552]
I have a grammar like:
```
command: $ => choice(
  $.command1,
  $.command2,
  ...
  $.commandN,
),
```
of course with slightly different names. While parsing the source code, I want to do different things based on the kind of command I'm working with, so the code looks something like:
```C
const char *type = ts_node_type (node);
if (strcmp (type, "command1") == 0) {
   handle_command1 (node);
} else if (strcmp (type, "command2") == 0) {
  handle_command2 (node);
} ... {
  ...
}
```
I feel like this is not ideal for performance and I would like to instead compare TSSymbols, however I am not aware of a way to get TSSymbols at compile time, so I would have to do:
```C
TSSymbol command1sym = ts_language_symbol_for_name(lang, "command1", ...);
TSSymbol command2sym = ts_language_symbol_for_name(lang, "command2", ...);
TSSymbol command3sym = ts_language_symbol_for_name(lang, "command3", ...);
TSSymbol nodesym = ts_node_symbol (node);
if (nodesym == command1sym) {
  handle_command1 (node);
} else if (nodesym == command2sym) {
  handle_command2 (node);
} ... {
  ...
}
```

However, by looking at the source code, `ts_language_symbol_for_name` iterates over all symbols, so if I have to do this for ~100 names, I would still have a problem.

My question is: is there a better way to use the parser and identify different kinds of rules?

If not, what do you think about a new API (I could send a PR) like:
```C
struct TSSymbolNameMapEntry {
  TSSymbol symbol;
  const char *name;
};

struct TSSymbolNameMap {
   uint32_t n_symbols;
   TSSymbolNameMapEntry *entries;
};

TSSymbolNameMap *ts_language_named_symbols(lang);
TSSymbolNameMap *ts_language_symbols(lang);
void ts_symbol_name_map_free (TSSymbolNameMap *map);
```
These functions would just iterate one time over all the symbols and return the right structure, instead of requiring to call `ts_language_symbol_for_name` for each name needed.

**Comment by maxbrunsfeld** [comment]
I think that you just need to call `ts_language_symbol_for_name` at the beginning of your analysis, and save the results in variables:

```c
// run once at the beginning of the task
TSSymbol command1_symbol = ts_language_symbol_for_name(lang, "command1", 8, true);
TSSymbol command2_symbol = ts_language_symbol_for_name(lang, "command2", 8, true);
TSSymbol command3_symbol = ts_language_symbol_for_name(lang, "command3", 8, true);
```

As long as you're not calling these in a very tight loop, the cost of `ts_language_symbol_for_name`  should be negligible. Have you measured it taking significant time, even when only called once for a given rule name?

If you want to avoid multiple loops, though, you don't need to add any new APIs, or allocate a separate map object. You can use the existing APIs:

```c
TSSymbol command1_symbol = 0;
TSSymbol command2_symbol = 0;
TSSymbol command2_symbol = 0;

for (TSSymbol i = 0, n = ts_language_symbol_count(language); i < n; i++) {
  if (!ts_language_symbol_type(language, i) != TSSymbolTypeNamed) continue;

  const char *name = ts_language_symbol_name(language, i);
  if (!strcmp(name, "command1")) {
    command1_symbol = i;
  } else if (!strcmp(name, "command2") {
    command2_symbol = i;
  } else if (!strcmp(name, "command3") {
    command3_symbol = i;
  }
}

assert(command1_symbol);
assert(command2_symbol);
assert(command3_symbol);
```

But I would recommend the first approach unless you really are seeing `ts_language_symbol_name` show up in your profiles.

Does this make sense?

**Comment by ret2libc** [comment]
Thank you @maxbrunsfeld I'm using the first approach so far, but also the second looks interesting. Thanks for sharing it!
