### ISSUE TITLE
Add flag to output css classes for CLI tree-sitter highlight

### ISSUE THREAD

**Issue by kramred** [tree-sitter/tree-sitter#553]
Hello,

tree-sitter seems to be a great project that can also be used to overcome the limitations of regex based highlighting.

I'm trying to use it as a (drop-in) replacement for e.g. [Prism](https://github.com/PrismJS/prism/) or [Pygments](https://pygments.org/)/[Chroma](https://github.com/alecthomas/chroma).

__It would be great to have a flag to output CSS classes instead of inline styles.__  
I've looked at the source code but my Rust knowledge is not sufficient to fully implement this – but I think it should not be too hard.

Inline style
```html
<span style='color: #5f00d7;'>function</span>
```

With CSS classes
```html
<span class='keyword'>function</span>
```

Ideally, there could be additional CLI flags for `tree-sitter highlight` to 
* output only a HTML snippet or a standalone HTML page (see https://github.com/tree-sitter/tree-sitter/pull/551) and to 
* have a table layout or alternatively a `<pre><code><spans…>` layout w/o line-numbers (see the other issue I opened: https://github.com/tree-sitter/tree-sitter/issues/554)

What do you think about adding a flag to output CSS classes instead of inline styles to generate output similar to the one above?

**Comment by fcurts** [comment]
Sounds like this would make theme config in `~/.tree-sitter/config.json` obsolete, which would be awesome. Instead just specify which CSS file to link to.

**Comment by maxbrunsfeld** [comment]
The reason we use a JSON theme is that one of the main uses for `tree-sitter highlight` is visually inspect syntax highlighting at the command line, so we need to know what ANSI color codes to use for each highlight.

I'd be open to adding something like this though; it'd be nice if there was some way to combine it with the existing theme concept, so we don't just end up with a ton of configuration and flags.

**Comment by notusknot** [comment]
This looks really cool and is exactly what I was looking for. By the way you phrased it, you made it seem like it's already possible to spit out the html with inline styles... is that true? That would be really cool.
