### ISSUE TITLE
Tree from tab indented text?

### ISSUE THREAD

**Issue by jessegrosjean** [tree-sitter/tree-sitter#557]
Is anyone aware of a grammar that will create an "outline" tree structure from tab indented text?

For example given:

```
one
    two
        three
        four
```

Would give a tree like:

```
(source_file
  (item
    (block
      (item
        (block
          (item)
          (item)))))
)
```

If this doesn't yet exist, any hints on best way to create such a grammar?

I've read through the docs once... retained a little! :) I think for this to work I need a custom `scanner.cc`. I've copied and pasted parts of the python grammar implementation. I can get things working if I hardcode text in input file, ie each line needs to be either `parent\n` or `(\t)*child\n`, but I'm having a hard time making it generic to create tree from arbitrary text.

Any hints appreciated.

**Comment by Leftium** [comment]
Really need more specifics; I can only guess what you mean by "arbitrary text."

But this is my best guess: the grammar you made does not support white space, yet. (Or the grammar supports white space, but doesn't know what to do when there are multiple tokens like "child" and "parent" before a newline.) Either case, you should modify the grammar to handle white space between tokens as you expect.

Take a look at https://lezer.codemirror.net/docs/guide/. Lezer grammars are very similar to Treesitter grammars and this guide starts with a simple grammar that only supports expressions like "(a+1)" or "(100-(2+4))." No white space is allowed, and the parentheses are required.

Then it explains how to modify the grammar so white space is allowed and the parentheses are optional. I think that's what you meant by "arbirary text."

**Comment by jessegrosjean** [comment]
I've got a mostly working example here:

https://github.com/jessegrosjean/tree-sitter-outline

Two questions:

Fist question, please take a look and let me know how to make it better. I'd like to build other more complex grammars off this base... want to make sure I have this working as clean efficient as possible.

Second question, the biggest problem that I'm aware of is I'm not sure how to handle a file that starts with indentation. For example consider this outline where two spaces equals one level of indentation:

```
    one
  two
three
```

Right now I'm handling this by just ignoring all leading whitespace in the file. This means the first item in a file is always considered to be at level zero indentation. So the above gets parsed as:

```
one
  two
three
```

Any better ideas?

**Comment by Arcanemagus** [comment]
Wouldn't that be better handled by the error handling in Tree-sitter? Not all samples will parse correctly.

**Comment by maxbrunsfeld** [comment]
I think you can have some external token that is required at the very start of your grammar, and just matches leading whitespace, in order to allow the external scanner to see the leading whitespace at the beginning of the file, and to update its internal state accordingly.

**Comment by jessegrosjean** [comment]
> Wouldn't that be better handled by the error handling in Tree-sitter? Not all samples will parse correctly.

The problem with that option is that the error recovery doesn't seem to happen as soon as I would like. For example if I take out the leading whitespace from the grammar and then try to parse this content:

```
  one
two
  three
  four
  five
```

The result that I get is a flat list:

```
(outline [0, 2] - [10, 0]
  (ERROR [0, 2] - [0, 2])
  (item [0, 2] - [2, 0]
    (text [0, 2] - [2, 0]))
  (item [2, 0] - [4, 2]
    (text [2, 0] - [4, 2]))
  (item [4, 2] - [6, 2]
    (text [4, 2] - [6, 2]))
  (item [6, 2] - [8, 2]
    (text [6, 2] - [8, 2]))
  (item [8, 2] - [10, 0]
    (text [8, 2] - [10, 0])))
```

I don't want to lose the fact that "three, four, five" are children of two. Any ideas how I could get around that?

**Comment by jessegrosjean** [comment]
> I think you can have some external token that is required at the very start of your grammar, and just matches leading whitespace, in order to allow the external scanner to see the leading whitespace at the beginning of the file, and to update its internal state accordingly.

Ok, hadn't thought of adding the new token to the scanner, that makes sense and I think I could make it work. I'll try to now figure out if I want to go that route or if it should generate an error.

**Comment by jessegrosjean** [comment]
@Arcanemagus @maxbrunsfeld @Leftium  Thanks for your help.

I've combined an external `start` token together with error case to get the behavior that I want. The external `start` token requires no indentation in first item. If that token is being looked for and fails to match then I make sure to remove any parsed indentation... and that fixes things so the rest of the document gets parsed correctly.

It's a little weird because the scanner logic depends on fact that grammar will only ask for start token at start of document... I guess that's OK? Anyway if you see improvements to be made let me know, seems to work for me so I'm closing this issue.
