### ISSUE TITLE
Question: Multiple highlight names single query 

### ISSUE THREAD

**Issue by jeff-hykin** [tree-sitter/tree-sitter#560]
Is there a way to assign multiple highlight names in an scm query? For example a variable being assigned to a function in JavaScript is both @function and @variable.

Something like
```
; highlights.scm

(variable_declarator value: (function) name: (identifier) @function @variable)
```

And as usual; thank you for all your contributions! Your work is incredible.

**Comment by maxbrunsfeld** [comment]
Yes, this is possible; I only added support for it fairly recently. It's in the latest `web-tree-sitter`, and it works on the web playground.
