### ISSUE TITLE
Using function results in errors

### ISSUE THREAD

**Issue by loicmarie** [tree-sitter/tree-sitter#574]
I may be misunderstanding something, but when I use any function, I have strange results. This simple example :

```js
module.exports = grammar({
  name: 'DataLang',

  rules: {
    source_file: $ => choice($.a, $.b),
    a: $ => 'hello',
    b: $ => 'world'
  }
});
```
with only the word `world` in a `test.datalang` file, gives me the following result

```
(ERROR [0, 0] - [1, 0]
  (ERROR [0, 0] - [0, 5]))
test.datalang	0 ms	(ERROR [0, 0] - [1, 0])
```
when I `tree-sitter parse test.datalang`.

Same with other functions, with other errors

**Comment by maxbrunsfeld** [comment]
I can't reproduce this.

```
$ cat grammar.js 
module.exports = grammar({
  name: 'DataLang',

  rules: {
    source_file: $ => choice($.a, $.b),
    a: $ => 'hello',
    b: $ => 'world'
  }
});

$ tree-sitter generate
$ echo world > test.datalang
```

I get the expected result:

```
$ tree-sitter parse test.datalang 
(source_file [0, 0] - [1, 0]
  (b [0, 0] - [0, 5]))
```

**Comment by loicmarie** [comment]
Ok, so that's very weird. I suspected an auto-newline when I save in my editor, but even with :
```
$ echo world > test.datalang
$ tree-sitter generate
$ tree-sitter parse test.datalang
```
or
```js
module.exports = grammar({
  name: 'DataLang',

  rules: {
    source_file: $ => seq(choice($.a, $.b), '\n'),
    a: $ => 'hello',
    b: $ => 'world'
  }
});
```
I get the exact same error. With some functions, the first operations works, for example if I change for :
```js
module.exports = grammar({
  name: 'DataLang',

  rules: {
    source_file: $ => seq($.a, $.b),
    a: $ => 'hello',
    b: $ => 'world'
  }
});
```
I get :
```
(source_file [0, 0] - [1, 0]
  (ERROR [0, 5] - [0, 10]
    (ERROR [0, 5] - [0, 10])))
test.datalang	0 ms	(ERROR [0, 5] - [0, 10])
```

**Comment by maxbrunsfeld** [comment]
Maybe try running `tree-sitter parse test.datalang -d`. That will output a log of what the parser and lexer are doing, which might tell us something.

Is the `.datalang` file encoded as ACII/UTF8, or are you using some other encoding?

**Comment by loicmarie** [comment]
Thanks it was probably the encoding, I don't exactly know why, but I changed my IDE and it works now...

Very cool project, thank you for reactivity
