### ISSUE TITLE
Oxidize core lib

### ISSUE THREAD

**Issue by dodomorandi** [tree-sitter/tree-sitter#575]
It could be interesting to port the core lib to Rust, in order to increase the maintainability of the project and to gain more safety.

Instead of creating the lib from ground up, it should be possible to use [C2Rust](https://github.com/immunant/c2rust) in order to convert the existing C code into unidiomatic and unsafe Rust, then gradually convert the functions to safe and idiomatic versions, one by one.

It is also reasonable to integrate [cbindgen](https://github.com/eqrion/cbindgen) in order to automatically create the C header files and keep a 100% API/ABI compatibility respect to the current state of the project.

If I am not wrong, there are some tests available, but they only relate to the CLI tool. Maybe it is interesting to create unit tests for the ported Rust code, in order to easily detect the source of regressions during the oxidation process.

**Comment by maxbrunsfeld** [comment]
The core library is tested pretty thoroughly with unit tests as well as randomized tests. All the tests use the Rust binding (and the CLI's functionality for dynamically loading generated parsers). They are located [here](https://github.com/tree-sitter/tree-sitter/tree/master/cli/src/tests).

I think this may be worth pursuing, but currently it's very convenient to be able to build Tree-sitter with nothing but a C compiler. It may make more sense to do this work once Rust has become a little bit more ubiquitous, so that that tools like Node.js, Python, Ruby and Haskell are all able to compile Rust code automatically.

**Comment by dodomorandi** [comment]
Thank you for your feedback!

Pardon me if I could be misunderstood -- I noticed that the library is well tested and there is a very nice work behind it! What I just wanted to say is that with Rust it is straightforward to create tests for each function. This obviously does not give less importance to the actual tests, it just give another layer of reliability over the single functions, hopefully easing the detection of specific regressions.

About the 'nothing but a C compiler' point: my personal objection is that the project already uses a full Rust ecosystem in order to build the C library. I knew that, in theory, one could just perform a `cc lib.c -o lib.so --shared` (or similar) on the source directory, but in practice I think that people interested in the project will just use cargo to build everything.

In any case, these are obviously just my opinions :smiley:. Just let me know if you will accept an eventual contribution focused on the oxidation of the C lib, or if you consider it premature for the current state of the project. Nevertheless, thank you for your work and your time :wink:!

**Comment by maxbrunsfeld** [comment]
> in practice I think that people interested in the project will just use cargo to build everything

In practice, most users of the project are not using Rust; they're relying on build systems which have built-in support for C code:

* NeoVim, [via Cmake](https://github.com/neovim/neovim/blob/6c5bbf07d988ef55e5e8ba8d70b62c1f0885261b/src/nvim/CMakeLists.txt#L90)
* the node binding, [via gyp](https://github.com/tree-sitter/node-tree-sitter/blob/master/binding.gyp), used by Atom
* the haskell binding, [via cabal](https://github.com/tree-sitter/haskell-tree-sitter/blob/7af0c79fffac3f9bffbf139034c91d5545a74225/tree-sitter/tree-sitter.cabal#L71-L72), used by GitHub's Semantic library* the python binding, [via setuptools](https://github.com/tree-sitter/py-tree-sitter/blob/63b88bfce475931488e6b90b095ee7aacc261bc8/setup.py#L34-L40), used by some of GitHub's ML projects
* the ruby binding, [via mkmf](https://github.com/tree-sitter/ruby-tree-sitter/blob/master/ext/tree-sitter/extconf.rb)
* the go binding, [via cgo](https://github.com/smacker/go-tree-sitter/blob/22251d53a5064c7ae5120462592df5fb21e6f626/bindings.go#L3)

In all of these cases, I'm sure that it's possible to link in some Rust code that exposes a C ABI, but the build systems don't just support it automatically; the downstream projects would have to add some complexity to their build process to allow it.

**Comment by maxbrunsfeld** [comment]
That said, I think that in the future, more people will adopt Rust, and more widely-used software will be developed in Rust, and build systems will start to ship with built-in support for including Rust code. As that starts to happen, I think it will be more worthwhile to convert the core library to Rust.

**Comment by lu-zero** [comment]
Since cargo-c can produce a nice pkg-config file, both static and dynamic libraries and the C header file, it might make the process a little nicer or not depending on what the downstreams prefer to do regarding embedding a private copy or linking a system copy.

**Comment by lu-zero** [comment]
To clarify since I just noticed @dodomorandi forgot to mention it in the issue: as part of a remote-due-covid-19 Turin-Milan-Rome meetup, we were planning to study the process of oxidizing and then bind-back-to-C a project.

I considered tree-sitter since it seems a good fit and would give us a chance to also see if wasm-pack + cargo-c + maturin would work well enough to provide a compatible bindings.

The issue was opened to see if there is interest in keeping the experiment assuming it shows viability.

**Comment by dodomorandi** [comment]
Thank you for your patience @maxbrunsfeld and for your time. I was not expecting other projects to directly compile the library (instead of using a packaged version from a distro), completely bypassing the current build system. Now that I have a better overview, I totally understand your point.

If it is ok, we will create a fork just to study the oxidation process of the core library, as @lu-zero already explained. We won't open a PR, because I totally understand that it is not the right time to perform these kind of changes to the lib, but at the same time I will share the link to the repo. If we will be able to do something useful, feel free to do some backporting :grin:

Thank you again for your time. If you agree, we can close the issue.

**Comment by maxbrunsfeld** [comment]
That sounds like a very interesting project, and I'll be curious to hear how it goes.

> at the same time I will share the link to the repo. If we will be able to do something useful, feel free to do some backporting 😁

That sounds great; I hope it works out! Maybe you'll even find some correctness issues in the C library on the way.

**Comment by dodomorandi** [comment]
Unfortunately we did not have enough time to prepare the _C2Rust_-ed repo to work with during the meetup. Instead we focused on a much smaller C library, extremely valuable point of view for a meetup 😉 

Before I close this issue, I want to ask you: would you consider the idea of migrating the bash scripts to something integrated with cargo? For instance, I noticed that it is necessary to run 'build-wasm' and 'fetch-fixtures' in order to successfully run 'cargo test'.
This kind of _migration_ would improve the overall build system of the project, but I don't know if it is something wanted. What do you think?

**Comment by eli-schwartz** [comment]
> Thank you for your patience @maxbrunsfeld and for your time. I was not expecting other projects to directly compile the library (instead of using a packaged version from a distro), completely bypassing the current build system. Now that I have a better overview, I totally understand your point.

There is no current build system, and distros cannot package tree-sitter, therefore other projects cannot depend on a packaged version and have no *choice* but to directly compile it.

See #467 for more details.

**Comment by lu-zero** [comment]
I prepared a quick and quite dirty example of the oxidation [here](https://github.com/lu-zero/tree-sitter-core), possibly we'll polish/refactor/reshape it over time.
