### ISSUE TITLE
Using tree-sitter + grammar from atom package does not seem to work

### ISSUE THREAD

**Issue by dschwen** [tree-sitter/tree-sitter#577]
I have created [a grammar](/dschwen/tree-sitter-hit) and am trying to use it in my [autocomplete-moose](/dschwen/autocomplete-moose) package. I have added `tree-sitter` and `tree-sitter-hit` to my `package.json`, but if I run `npm install` and restart atom I get 
```
`The module '/home/daniel/Programs/autocomplete-moose/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).`
```
and if I run `apm install` I immediately get
```
> tree-sitter@0.16.0 install /home/daniel/Programs/autocomplete-moose/node_modules/tree-sitter
> prebuild-install || node-gyp rebuild


prebuild-install WARN install No prebuilt binaries found (target=4.2.7 runtime=electron arch=x64 libc= platform=linux)
Aborted
Aborted
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.3.0-40-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/daniel/Programs/autocomplete-moose/node_modules/tree-sitter
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! tree-sitter@0.16.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the tree-sitter@0.16.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.atom/.apm/_logs/2020-03-13T01_19_33_422Z-debug.log
```

What am I missing?

**Comment by Aerijo** [comment]
This is an Atom issue, in particular with `apm`.

`apm` bundles a copy of NodeJS, and I've seen a system installed node interfere in a similar way before. That it can happen is obviously still a problem, but can you confirm whether you installed node through nvm or not? I found the issue doesn't happen when I use nvm.

Alternatively, there is my [`apx`](https://www.npmjs.com/package/@aerijo/apx) module that doesn't bundle node, so shouldn't have any problems.

**Comment by dschwen** [comment]
Hm, thank you, I suspected something along those lines. But even if I make it work for myself wouldn't this still be an issue for other people who don't carefully control their Atom/node installation and who would expect a package install to *just work*?

**Comment by dschwen** [comment]
Ok, installing a conda environment with python2 and using nvm to install the exact same version Atom is using I can get the module built and working with `apm install` (`npm install` still gives the `NODE_MODULE_VERSION` discrepancy).

Will this work seamlessly for users once I publish the package changes (since the install/build will happen in the atom environment)?

**Comment by maxbrunsfeld** [comment]
People who install the package with `apm install` or through the Atom UI should have no problem (assuming that they have a c compiler installed, which most developers do). The `NODE_MODULE_VERSION` problem is only something you'd run into if you're developing the module and you accidentally run `npm install` instead of `apm install`.

I'm going to close this one out since it's about Atom instead of Tree-sitter.
