### ISSUE TITLE
Move parser api into the parser header

### ISSUE THREAD

**Issue by Luni-4** [tree-sitter/tree-sitter#582]
It would be helpful to move parser's API into the `parser.h` file instead of leaving them in a more general `api.h` file.

**Comment by maxbrunsfeld** [comment]
The `parser.h` file doesn't contain public APIs; it's just included by the generated parsers. So applications that use Tree-sitter should never include `parser.h`, just `api.h`.

**Comment by Luni-4** [comment]
Oh, I see, thanks for the explanation!
