### ISSUE TITLE
Encoding trees as XML: any preferred namespace URL?

### ISSUE THREAD

**Issue by AlbertoGP** [tree-sitter/tree-sitter#587]
My program outputs the parse tree as XML, like this:
```xml
<?xml version="1.0"?>
<source_file xmlns="https://tree-sitter.github.io/ns/grammar/rust" version="11">
  <line_comment>// Author: Alberto González Palomo https://sentido-labs.com</line_comment>
  ...
</source_file>
```
As seen there, the namespace URL I made up is ```https://tree-sitter.github.io/ns/grammar/``` + grammar name. Please note that an XML namespace URL does not need to point to any existing file, it is just a namespace identifier.

I use ```grammar``` instead of ```language``` because there could, in theory, be different grammars for the same language, and they might use different node names.

I guess nobody else is doing this, and thus nobody cares, but does anyone have any reason not to use this namespace identifier?

**Comment by sogaiu** [comment]
Sorry, not an answer to your question, but when working on a support for Clojure, the idea of having different specialized grammars has come up repeatedly so accounting for that possibility sounds reasonable here.

In fact, there have already been at least 3 separate attempts at a grammar for Clojure.  For practical purposes I'm just using an author's handle as a way to distinguish among them, but that just happens to work in these particular cases.

**Comment by AlbertoGP** [comment]
I see, that makes sense. I’ve been trying different methods, and at the end decided that the best way is to use the link to the release, or commit if not using a release version.

What I have is a table in my `build.rs` that lists properties for each language: name, version, download URL (exact .zip file for that version), and XML namespace URL.
For parsers without releases like your Clojure grammar, I use the git hash with prefix `git:` as version.

It then generates a Rust module that loads the parsers (`extern "C" {...}` etc.) and has a function that, given a language name string, gives you the parser instance, version, and namespace. That’s used when producing the XML version of the parse tree.

Two examples, rust and lua:
```xml
<?xml version="1.0"?>
<source_file version="0.16.0"
  xmlns="https://github.com/tree-sitter/tree-sitter-rust/releases/tag/v0.16.0"
  xmlns:t="https://tree-sitter.github.io/ns/grammar" abi="11">
  <line_comment>// Author: Alberto González Palomo https://sentido-labs.com</line_comment>
  ...
</source_file>
```
```xml
<?xml version="1.0"?>
<program version="1.6.0"
  xmlns="https://github.com/Azganoth/tree-sitter-lua/releases/tag/v1.6.0"
  xmlns:t="https://tree-sitter.github.io/ns/grammar" abi="10">
  <comment>-- Copyright 2007-2017 Mitchell mitchell.att.foicica.com. See LICENSE.</comment>
  ...
</program>
```

I can not use your Clojure parser or any other without pre-made parser.c etc. because tree-sitter-cli does not install on this CPU architecture yet, but it would look like this:
```xml
<?xml version="1.0"?>
<source_file version="git:5a5bf409f12eb79a7d6613a1c740f354beb5916c"
  xmlns="https://github.com/sogaiu/tree-sitter-clojure/tree/5a5bf409f12eb79a7d6613a1c740f354beb5916c"
  xmlns:t="https://tree-sitter.github.io/ns/grammar" abi="11">
  ...
</source_file>
```

**Comment by sogaiu** [comment]
> at the end decided that the best way is to use the link to the release, or commit if not using a release version.

That sounds sensible -- I guess I shouldn't force-push too much :)

Thanks for the examples, they were helpful in checking and improving my understanding of your prose description.

> I can not use your Clojure parser or any other without pre-made parser.c etc. because tree-sitter-cli does not install on this CPU 
architecture yet, 

Ah, which one would that be?

**Comment by maxbrunsfeld** [comment]
Thanks for checking in about this. I don't think our team has a preference on it.
