### ISSUE TITLE
Each call of get_column increase the line number of tokens by 1

### ISSUE THREAD

**Issue by bglgwyng** [tree-sitter/tree-sitter#589]
https://github.com/bglgwyng/tree-sitter-sandbox/tree/get-column-increases-line-no
Here is my simple example.
You can find `lexer->get_column(lexer);` on the line 35 of `scanner.c`.
Each time I add the function call, the result span's line number increases by 1.

**Comment by maxbrunsfeld** [comment]
Thanks for taking the time to create these reproduction steps. This is very very helpful. I will try to take a look at this bug later this week.

**Comment by bglgwyng** [comment]
@maxbrunsfeld As I mentioned in #314, I think it happens when the token includes newline character.
