### ISSUE TITLE
Could it be Used as code generation from one language to another

### ISSUE THREAD

**Issue by CedricDumont** [tree-sitter/tree-sitter#594]
Great tool.

If I understood correctly, Tree-sitter generates a kind of common AST among different programming languages.
I found a lot of stuff and plugins on syntax highlight, but I was wondering if it could be used to generate code from one language to another (probably with some limitation).
For instance, what about code generation from Ocaml to javascript and back. 
Do you have some work following that path or do you know any project of that kind?

**Comment by maxbrunsfeld** [comment]
Thanks! I'm not sure, but I imagine it would be possible to use Tree-sitter for parsing as part of a source-to-source transpiler. I'm going to close this one out, but if you want to ask other Tree-sitter users more about it, you could make a post in the *Discussion* board: https://github.com/tree-sitter/tree-sitter/discussions.

**Comment by li-maisiliym-xyz** [comment]
Isn't @maxbrunsfeld the original author of treesitter? Hasent it taken him years to polish? If so, he must have considered this amazing and obvious use-case in depth. Or has he posted his thoughts in the 'discussions' repo? If so, Li could not find it by searching some key words. Perhaps he could link his thoughts on this subject here for discoverability?
Li is already planning to use this as a universal-pseudo-code (C,rust,js,etc) to true-code (sajban for exemple- warning semi-vaporware) de/serializer. This could immortalize treesitter as the layer which glued the dark-computer-ages to the evolved-systems of a possibly surviving humanity. This is big. Now back to trying to build this thing correctly ... ;)
