### ISSUE TITLE
How do you get token text?

### ISSUE THREAD

**Issue by valtron** [tree-sitter/tree-sitter#595]
E.g., for an identifier or number token.

**Comment by maxbrunsfeld** [comment]
Tree-sitter doesn't copy your source code, but you can retrieve tokens' text from the original source code using [APIs](https://tree-sitter.github.io/tree-sitter/using-parsers#syntax-nodes) such as `ts_node_start_byte`, `ts_node_end_byte`, `ts_node_start_point`, and `ts_node_end_point`.
