### ISSUE TITLE
Render or Main Process of  Electron

### ISSUE THREAD

**Issue by PitterL** [tree-sitter/tree-sitter#596]
Hi, Tree-Sitter:
I use Electron 8.0 as platform to embedded tree-sitter, when all call it in 

import { Tree } from 'tree-sitter'
const { ipcRenderer } = require('electron');

const requireFunc = typeof __webpack_require__ === "function" ? __non_webpack_require__ : require;
const Parser = requireFunc('tree-sitter');
const CLang = requireFunc('tree-sitter-c');

The warning come out through it could work:
(node:121804) Electron: Loading non-context-aware native module in renderer: '\\?\D:\Users\xxx\vscode\js\reactronts\node_modules\tree-sitter-c\build\Release\tree_sitter_c_binding.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

Could you please suggest how to use the tree-sitter in electron?

Thanks.

**Comment by maxbrunsfeld** [comment]
Since this is a Node.js-specific issue, could you report it here? https://github.com/tree-sitter/node-tree-sitter
