### ISSUE TITLE
Build compatibility with Alpine

### ISSUE THREAD

**Issue by AlexGustafsson** [tree-sitter/tree-sitter#597]
Using the Node Docker image for Alpine I am unable to run the cli installed via NPM.

Running `ldd node_modules/tree-sitter/tree-sitter-cli` yields the following output:

```
bash-5.0# ldd node_modules/tree-sitter-cli/tree-sitter 
	/lib64/ld-linux-x86-64.so.2 (0x7f9758f2e000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f9758f2e000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f9758f2e000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f9758f2e000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f975886e000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f9758f2e000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f9758842000)
Error relocating node_modules/tree-sitter-cli/tree-sitter: __snprintf_chk: symbol not found
Error relocating node_modules/tree-sitter-cli/tree-sitter: __fprintf_chk: symbol not found
Error relocating node_modules/tree-sitter-cli/tree-sitter: __res_init: symbol not found
```

It is of my understanding that the issue is that the binary available via NPM is dynamically linked towards `glibc`, something that Alpine does not support.

I've tried workarounds such as https://github.com/sgerrand/alpine-pkg-glibc without any progress.

Is there any plan on supporting Alpine in published builds?

**Comment by maxbrunsfeld** [comment]
Not in the published builds that we maintain, but I think you should be able to build the `tree-sitter` CLI from source on Alpine. You'll just need C and Rust compilers, and optionally either Docker or Emscripten (for the webassembly build).
