### ISSUE TITLE
Pretty print correct code from tree-sitter parse tree

### ISSUE THREAD

**Issue by aquaktus** [tree-sitter/tree-sitter#603]
Hi,

Tree sitter is absolutely amazing! The fact that it has so many languages available is fantastic.

I would like to use it to also build the parse tree according to the grammar specified by a language, and then to pretty print that generated tree as code.

I was wondering if there is functionality in the library to do this at the moment. So that I know not to re-invent the wheel.

What I'm looking for is:
- A way to generate nodes from scratch in a safe way according to the grammar. My current thought process for this is to use the `grammar.json` from each language to constrain generation for each node. This still requires the ability to generate blank nodes at some point though.
- A way to print the tree (which is in the same format as that given by tree-sitter) into a code string. Potentially executable later. I can see how this could this be done given the expressive parse tree given, so I could also code this myself.

Many thanks for all the work on this.
Glad to move the question elsewhere if it's the wrong place to ask it.
(• ◡•)

**Comment by patrickt** [comment]
We’ve given some thought to this, but it’s somewhat complicated. Comments, for example, have to be stored in the syntax tree if you want to correctly round-trip some commented code, which means you’d have to create an explicit node type for comments, associate clauses with their comments (an inexact science). I’d say that the best way forward is to write a pretty-printer for the nodes in your grammar yourself, but we should keep this open and think about it.

**Comment by maxbrunsfeld** [comment]
The Tree-sitter syntax tree does store comments in a lossless way (at least, no lossier than any other part of the syntax tree).

The main difficulty with transforming a tree back into source code is that Tree-sitter does not store text. Syntax nodes store their byte offsets and row/column coordinates in the source code, but they do not store copies of source code.

**Comment by aquaktus** [comment]
Given that the idea is to generate code (this is for an ML research application), generating comments shouldn't be necessary. If there are other pitfalls though, please do elaborate as I can work around them easier since I'm only a few days into tree-sitter.

As for the trouble with the leaf nodes in the tree as coordinates, maybe the best option is to subclass the node type to include a string representation as the node is generated.

I'm working in python using py-tree-sitter, is there a class for each node type I could use to start off with?

**Comment by aquaktus** [comment]
Thinking along the lines of something like this:
```python
from tree_sitter import Language, Parser, Node

Language.build_library(
  'build/my-languages.so',
    ['src/tree-sitter/tree-sitter-python'])

PY_LANGUAGE = Language('build/my-languages.so', 'python')
parser = Parser()
parser.set_language(PY_LANGUAGE)

n = Node() # <- Make some kind of root node here, and following subtypes
```

Just running the above gives this
```
TypeError: cannot create 'tree_sitter.Node' instances
```
Which makes sense since `Node` isn't tied to any language as such.
But that's the idea I want to convey.

**Comment by aquaktus** [comment]
Any thoughts @patrickt ? (• ◡•)

**Comment by maxbrunsfeld** [comment]
There is not a separate class for each node type currently.

I think the best approach would be to build your own node classes, possibly based on the grammar.json and/or the node-types.json. The py-tree-sitter classes will not really be useful for the purpose of building a syntax tree manually and generating code from it.

**Comment by aquaktus** [comment]
Excellent! 
I'll post in the thread how it goes then.

**Comment by maxbrunsfeld** [comment]
I'm going to close this one out, since I don't think there is work to do on the Tree-sitter side. Let us know how your exploration goes though!

**Comment by abtExp** [comment]
@aquaktus did you find any solution? I'm also working on a text to code ML application.
