### ISSUE TITLE
Grammars for wasm text formats

### ISSUE THREAD

**Issue by darinmorrison** [tree-sitter/tree-sitter#605]
@maxbrunsfeld I've been working on [tree-sitter grammars for wasm](https://github.com/wasm-lsp/tree-sitter-wasm) text formats (`.wat`, `.wast`, `.wit`, and `.witx`) and wanted to start a discussion to see if there's interest in moving the repo over to the tree-sitter org and mentioning it in the documentation in order to increase visibility, etc. Not sure what the process is for contributing new grammars.

These wasm grammars were mainly developed for use in a [wasm language server](https://github.com/wasm-lsp/wasm-language-server). I haven't announced the server yet since I'm still working on editor extensions to release alongside but the grammars are working nicely for powering error reporting, symbol extraction, etc. 

The `.wat` and `.wast` grammars are currently able to parse all of the test files in the [WebAssembly/spec](https://github.com/WebAssembly/spec/) repo without errors. They are "complete" but have not been heavily tested outside of casual use while developing the server. I intend to work on a more exhaustive testing configuration soon.

Let me know what you think.

And by the way, thanks for making tree-sitter! Very impressed with the functionality provided and how easy it was to get everything to work.

**Comment by maxbrunsfeld** [comment]
Thanks! These look great. I will a link to them from the docs website.
