### ISSUE TITLE
Allow MISSING in tree queries

### ISSUE THREAD

**Issue by AlexGustafsson** [tree-sitter/tree-sitter#606]
When using tree queries, types added by tree-sitter itself, such as `ERROR` are fine in a query like `(ERROR) @error`.

Using the type `MISSING` as in `(MISSING) @missing`, however, results in an error (at least on the Python and Web binding, but it should likely be the same for the core, since they're just bindings).

The error I get is:

```
...
File "../venv/lib/python3.8/site-packages/tree_sitter/__init__.py", line 92, in query
    return _language_query(self.language_id, source)
NameError: Invalid node type MISSING
```

There doesn't seem to be any direct error thrown by the web binding, but it isn't working as with other node types.

**Comment by Et9797** [comment]
Any updates on this? Would be very useful for language server diagnostics

**Comment by Caradhrass** [comment]
Related: I am trying to match error nodes with queries but ran into some limitations: 
`(ERROR (name) ) @error_name`  works  but  `(expr (ERROR (name) )) @error_inside_expression` doesn't.
This would be very useful for language server stuff.
