### ISSUE TITLE
subtree.c:518: ts_subtree_release: Assertion `self.ptr->ref_count > 0' failed.

### ISSUE THREAD

**Issue by mcuadros** [tree-sitter/tree-sitter#611]
We are facing this error at a high concurrency model, so it's really hard to debug, we use queries and also we traverse the nodes. To make this even complex to debug we use it through [`go-tree-sitter`](https://github.com/smacker/go-tree-sitter).

The tree-sitter version is 0.16.5

Any hint to solved the bug will be highly appreciated. 

```
analyzer: subtree.c:518: ts_subtree_release: Assertion `self.ptr->ref_count > 0' failed.
analyzer: stack.c:96: stack_node_release: Assertion `self->ref_count != 0' failed.
SIGABRT: abort
PC=0x7f49966507bb m=10 sigcode=18446744073709551610
analyzer-5d8b6dd9c-vvpfz analyzer
goroutine 0 [idle]:
runtime: unknown pc 0x7f49966507bb
stack: frame={sp:0x7f4956ffc960, fp:0x0} stack=[0x7f49567fd288,0x7f4956ffce88)
00007f4956ffc860:  0000000000000000  0000000000000000
00007f4956ffc870:  0000000000000000  0000000000000000
00007f4956ffc880:  0000000000000000  0000000000000000
00007f4956ffc890:  0000000000000000  0000000000000000
00007f4956ffc8a0:  0000000000000000  0000000000000000
00007f4956ffc8b0:  0000000000000000  0000000000000000
00007f4956ffc8c0:  0000000000000000  0000000000000000
00007f4956ffc8d0:  0000000000000000  0000000000000000
...
```

**Comment by maxbrunsfeld** [comment]
```
analyzer: subtree.c:518: ts_subtree_release: Assertion `self.ptr->ref_count > 0' failed.
analyzer: stack.c:96: stack_node_release: Assertion `self->ref_count != 0' failed.
```

I'm not sure how to interpret that double error message. It looks like there are two different assertion failures happening? Are these happening on two different threads?

It seems like some Tree-sitter object is getting used after it is freed. Does this only happen with multiple threads? One possible problem is sharing a `Tree` (or its nodes) between threads. A tree is not thread-safe, but can be cheaply copied via `ts_tree_copy` in order to allow sharing between threads.

**Comment by mcuadros** [comment]
Yes, it's really complex to replicate since is inside of a big process, and the error only happens when we scale up to several routines, but the thing is that are always different trees. Most likely will be a problem inside of the wrapper. 


```
analyzer-86c7959876-vfbxs analyzer analyzer: stack.c:408: ts_stack_state: Assertion `(uint32_t)version < (&self->heads)->size' failed.
analyzer-86c7959876-vfbxs analyzer SIGABRT: abort
analyzer-86c7959876-vfbxs analyzer PC=0x7f758011e7bb m=14 sigcode=18446744073709551610
analyzer-86c7959876-vfbxs analyzer
analyzer-86c7959876-vfbxs analyzer goroutine 0 [idle]:
analyzer-86c7959876-vfbxs analyzer runtime: unknown pc 0x7f758011e7bb
analyzer-86c7959876-vfbxs analyzer stack: frame={sp:0x7f752e7fb8f0, fp:0x0} stack=[0x7f752dffc288,0x7f752e7fbe88)
```

Another example, ok, don't worry Max.

**Comment by maxbrunsfeld** [comment]
Actually, another guess is that your program may accidentally be using a single `Parser` from multiple threads at the same time. You might want to double check that each `Parser` is only used on one thread.

**Comment by mcuadros** [comment]
Oh! You are the spot, we initialize only one parser for the full worker.

**Comment by maxbrunsfeld** [comment]
Great, hopefully that is the only problem. The `Parser` isn't thread safe either, since it carries the internal mutable state that is needed for parsing.

**Comment by mcuadros** [comment]
Problem solved, thanks Max you were very helpful
