### ISSUE TITLE
Panic when a regex contains an invalid unicode code point

### ISSUE THREAD

**Issue by stephe-ada-guru** [tree-sitter/tree-sitter#621]
The attached file (after renaming to .js; github would not let me attach a .js!) gives an error:

tree-sitter generate /c/Projects/tree-sitter-ada/ada_annex_p.js
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli\src\generate\nfa.rs:80:28

[ada_annex_p.txt](https://github.com/tree-sitter/tree-sitter/files/4639846/ada_annex_p.txt)

I tried to run tree-sitter under gdb, but even using the target/debug executable, there are no debug symbols. I compiled tree-sitter from github master, on Mingw64.

**Comment by stephe-ada-guru** [comment]
compiling tree-sitter on Debian gives me debug symbols; apparently rustc is less function on Mingw64?

**Comment by stephe-ada-guru** [comment]
The problem is the large character ranges in the regular expressions for identifier, string_literal, character_literal; reducing the max char to \uFF fixed this problem (and gives a different error about order).

Just FYI, the re2c lexer handles the full 32bit Unicode range with no problem.

**Comment by maxbrunsfeld** [comment]
Thanks for the report!

You don't need to restrict things to `\uFF`. But with the current code (see https://doc.rust-lang.org/std/char/fn.from_u32.html), you do need to restrict things to valid unicode *code points* (not all 32-bit integers are valid unicode). I will change this code to return a more helpful error message, instead of crashing.

**Comment by stephe-ada-guru** [comment]
Max Brunsfeld <notifications@github.com> writes:

> You don't need to restrict things to `\uFF`. But with the current code
> (see https://doc.rust-lang.org/std/char/fn.from_u32.html), you do need
> to restrict things to valid unicode *code points* (not all 32-bit
> integers are valid unicode). 

Hmm. So I need to find a list of all the valid ranges, or generate that
list by writing code that calls from_u32.

> I will change this code to return a more helpful error message,
> instead of crashing.

Ok.

-- 
-- Stephe

**Comment by maxbrunsfeld** [comment]
Is your grammar open source? I'm not very familiar with Ada, so I'd be curious what the use case is.

I'm open to changing this behavior to allow arbitrary 32-bit integers, but I haven't thought hard about it because the current behavior has been fine so far.

**Comment by stephe-ada-guru** [comment]
Sorry for the late reply. My current grammar is in the Gnu Savannah project Emacs ada-mode, branch org.emacs.ada-mode, file ada_annex_p.wy (https://savannah.nongnu.org/projects/ada-mode/). It uses re2c regular expressions (https://re2c.org/manual/manual.html#regular-expressions). For instance, an Ada string literal is:

%token <string-double> STRING_LITERAL %[ (["][\x20-\x21\x23-\U0010FFFF]*["])+ ]%

The regular expression is inside the %[  ]%.

I have code that automatically translates the .wy file to a tree-sitter grammar .js file, except for the regular expressions.

I found a list of valid Unicode ranges at 
https://en.wikipedia.org/wiki/Unicode#Code_point_planes_and_blocks
I'm assuming a blocks are fully populated (that may not be true). There is also https://codepoints.net/ that provides a REST API for querying Unicode info.

However, I still can't represent a 32 bit character in a JavaScript regular expression; the hex format \uhhhh only supports 16 bit.

In Emacs. there is a character class named [:alnum:] which matches characters whose Unicode ‘general-category’ property indicates they are alphabetic or decimal number characters. Can tree-sitter provide something like that?

In general, I don't think it's the lexer generator's job to check for valid Unicode. For one thing, it's table of Unicode info could easily be out of date. For another, I might be using a new character set that is not yet in Unicode.

**Comment by stephe-ada-guru** [comment]
On whether the lexer should limit chars to those defined by Unicode; the Ada language defines it's input character set as (http://www.ada-auth.org/standards/rm12_w_tc1/html/RM-2-1.html paragraph 3.1/3):

     A character is defined by this International Standard for each cell
     in the coding space described by ISO/IEC 10646:2011, regardless of
     whether or not ISO/IEC 10646:2011 allocates a character to that
     cell.

**Comment by stephe-ada-guru** [comment]
I found the section on Unicode property escapes in the JavaScript regexp cheatsheet, so I tried:
IDENTIFIER: $ => /[\p{General_Category="Letter, Uppercase"\p{General_Category="Letter, Lowercase"}][0-9\p{General_Category="Letter, Uppercase"\p{General_Category="Letter, Lowercase"}]*/,

However, that gave:

Error processing rule IDENTIFIER
Details:
  Regex error: Unsupported character class syntax Unicode(ClassUnicode { span: Span(Position(o: 87, l: 1, c: 88), Position(o: 166, l: 1, c: 167)), negated: false, kind: NamedValue { op: Equal, name: "General_Category", value: "\"Letter, Uppercase\"\\p{General_Category=\"Letter, Lowercase\"" } })

**Comment by maxbrunsfeld** [comment]
Yeah, I'd like to add support for JavaScript's `\p{}` syntax in regexes. I don't think it should be too complex, and it would be useful in a number of grammars.

**Comment by Razzeee** [comment]
Any news on this, I'm trying to replace 

```
    lower_case_identifier: ($) => /[a-z][a-zA-Z0-9_]*/,
```

with 

```
    lower_case_identifier: ($) => /\p{Ll}[_\d\p{L}]*/,
```

which would be more accurate in my grammar

**Comment by AntonyBlakey** [comment]
If you go here

https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3AAlphabetic%3DYes%3A%5D&abb=on&esc=on&g=&i=

You can get the escape sequence suitable to put into a regex, once you remove everything above `\uFFFF`. The above shows alpha, but you can do it for any class. Select 'Abbreviate' and 'Escape'.  This works for me in tree-sitter.

**Comment by Razzeee** [comment]
Thank you, I've tried that before but it didn't work for some reason. Seems fine now, but will be very hard to maintain due to bad readability.

**Comment by AntonyBlakey** [comment]
Yep, it's awful, and likely poor performance compared to a lookup of a Unicode property. My generate now takes 4 times as long, and the parser is slower. But it removed a blocking issue for me, so ... needs must.

**Comment by maxbrunsfeld** [comment]
I'm working on support for unicode property escapes: #906.

**Comment by amaanq** [comment]
Seems to generate fine now on master
