### ISSUE TITLE
Add docs on how to query injected nodes

### ISSUE THREAD

**Issue by resolritter** [tree-sitter/tree-sitter#625]
While the [Language Injection](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection) section explains what the configuration does, it does not hint at how one would do querying inside of the injected content.

I've tried to base myself in the following files:

- https://github.com/tree-sitter/tree-sitter-html/blob/master/queries/injections.scm
- https://github.com/tree-sitter/tree-sitter-embedded-template/blob/master/queries/injections-erb.scm

They're written slightly differently. The **embedded** repository defines those two opaque "code" and "content" node types, which seemingly serves no purpose other than naming the range, while the **HTML** reaches the raw_text in a nested manner. This caused me some slight confusion because, in the former, the `#set` rules are written as siblings of the affected node, while, in the HTML case, the injected content is nested inside of something else. I guess it does not matter either way.

Regardless, the most important question for me is: are we supposed to take those injected node ranges and query them separately or is the query API supposed to accommodate for this use-case as well? I am aware of the [Multi-language Documents](http://tree-sitter.github.io/tree-sitter/using-parsers#multi-language-documents) section, but would like to be able to do this through the CLI.

Example: Vue files can have JS and CSS inside of them. I would like to do:

`tree-sitter query -q:vue /path/to/vue-query.scm -q:javascript /path/to/js-query.scm File.vue`

**Comment by maxbrunsfeld** [comment]
> Are we supposed to take those injected node ranges and query them separately or is the query API supposed to accommodate for this use-case as well? I am aware of the Multi-language Documents section, but would like to be able to do this through the CLI.

Right now, the behaviors described in the [syntax highlighting docs](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection) (including the handling of language injection queries) are implemented as part of the syntax highlighting library, `tree-sitter-highlight`, which is used by the `tree-sitter highlight` CLI command.

The `tree-sitter query` CLI command is much simpler. It just runs one query against a source file and prints out the matches. It does not process language injections, or do any of the things described in the Syntax Highlighting documentation. It isn't really *useful* for anything except for debugging queries.

I can't tell exactly what you are trying to do. It sounds like you are trying to test that your language injection query is working correctly, but not through the `tree-sitter highlight` command. Is that right? Currently, there is no CLI command that performs language injection except for `tree-sitter highlight`.

**Comment by maxbrunsfeld** [comment]
> the `#set` rules are written as siblings of the affected node, while, in the HTML case, the injected content is nested inside of something else. I guess it does not matter either way.

Yeah, they can appear anywhere within a pattern.

**Comment by resolritter** [comment]
> It does not process language injections, or do any of the things described in the Syntax Highlighting documentation. It isn't really useful for anything except for debugging queries.

I didn't know that. I am currently using the `query` command as the "back-end" for highlighting in the editor, as a stopgap measure. Parsing the rows, columns and node types is all done in a background thread, so it never blocks the editor.

I know it's inefficient to not reuse the trees and spawn a new sub-shell every time the file changes but, as already mentioned, it's a temporary measure.

Anyways, thanks for the clarification on the `query` command's purpose! If it's the intended way, then I don't see this as an issue anymore.
