### ISSUE TITLE
/script/reproduce is a symlink and that a bit inconvenient for building on Windows

### ISSUE THREAD

**Issue by ignatov** [tree-sitter/tree-sitter#627]
Hi! Thanks for the lib!

I'm trying to build tree-sitter on Windows downloading a tar archive, but https://github.com/tree-sitter/tree-sitter/blob/master/script/reproduce is a symlink and symlinks behavior on Windows a bit fuzzy. Is there any way on how we may replace that symlink with a read file?

**Comment by maxbrunsfeld** [comment]
Can you explain what you are trying to use `script/reproduce` for? That file shouldn't be needed by any users of the library.

**Comment by ignatov** [comment]
I'm trying to extract tar.gz on Windows and it's impossible due to symlinks.

**Comment by maxbrunsfeld** [comment]
What program are you using to extract the archive? If you're not using 7-zip, can you try with 7-zip?

In general, I don't think I want to avoid having any symlinks in the repo, as long as there exists *some* windows program available that can handle such archives correctly.

**Comment by gavinbeatty** [comment]
Msys cmake's tar (`cmake -E tar xfz`), and msys' bsdtar (`bsdtar -xf`) both exit with errors on Windows when trying to extract https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.20.6.zip. This is a bit annoying when trying to build neovim in msys, for example. Neovim's third-party/CMakeLists.txt and third-party/cmake/DownloadAndExtractFile.cmake has logic to download, extract, and build external dependencies. My workaround so far is to patch the latter to ignore all errors during extraction.
