### ISSUE TITLE
Question: Possible to re-use a capture in multiple sub queries?

### ISSUE THREAD

**Issue by tjdevries** [tree-sitter/tree-sitter#629]
I have a query that looks like this:

```

(
	(variable_declaration
        variable: (field_expression (identifier) @table))

	(module_return_statement
		(table
    		(field
        		(identifier) @export (identifier) @export_original))
        )

    (#eq? @table @export_original)
)

(
	(variable_declaration
        variable: * @variable)

	(module_return_statement
		(table
    		(field
        		(identifier) @export (identifier) @export_original))
        )

    (#eq? @variable @export_original)
)
```

Where I'm trying to "scoop up" all the things return by a module in Lua (working on some stuff for Neovim) and I'd like to re-use the 

```
	(module_return_statement
		(table
    		(field
        		(identifier) @export (identifier) @export_original))
        )
```

between the two queries. Is that possible? Maybe this doesn't even make sense. I'm just getting acquainted w/ tree-sitter. Thanks :)

**Comment by maxbrunsfeld** [comment]
Right now there isn't a capability of code reuse within queries. They're pretty dead simple. I think it's possible that we'll add one at some point, but probably not too soon.

Good luck!

**Comment by tjdevries** [comment]
Cool, just wanted to make sure. Perhaps I will just use some templating to drop them in ;)
