### ISSUE TITLE
What is the precedence in highlighting queries?

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#632]
When a node is associated with multiple capture names, by multiple patterns, which patterns or capture names are prioritized for highlighting?

The context is I'm writing custom highlighting queries for Emacs. I don't use the queries included in grammar repositories, as they are a little bit too bare-bone, and don't entirely fit Emacs's current highlighting classification. I think it's a good idea to keep the precedence consistent among different highlighting implementations. (The current emacs-tree-sitter's implementation prioritizes patterns appearing earlier in the query.)

**Comment by maxbrunsfeld** [comment]
Yeah, the rust crate, ‘tree-sitter-highlight’ prioritizes patterns appearing earlier in the query.

**Comment by ony** [comment]
Today I learned that `tree-sitter highlight` have one order and Neovim plugin have it reversed. I hate that I cannot use same highlighting that would be shared among multiple highlighters/editors.
