### ISSUE TITLE
Unused rules in grammars cause incorrect parser generation

### ISSUE THREAD

**Issue by maxbrunsfeld** [tree-sitter/tree-sitter#64]
@joshvera and I discovered this while working on https://github.com/tree-sitter/tree-sitter-typescript. Unused rules in the grammar causes crazy stuff to happen.

**Comment by Meai1** [comment]
I think I have that same problem, I get this error: 
prog: src/runtime/parser.c:1085: parser__advance: Assertion `(uint32_t)0 < (&reduction.slices)->size' failed.

**Comment by maxbrunsfeld** [comment]
Yeah, it's one possible cause. @Meai1 curious what you're doing. If you can share your grammar, I could take a look.

**Comment by Meai1** [comment]
[grammar and testfile.zip](https://github.com/tree-sitter/tree-sitter/files/817460/grammar.and.testfile.zip)

**Comment by maxbrunsfeld** [comment]
Ah ok, so it probably is the unused rules issue. I'll put out a fix for that soon.
