### ISSUE TITLE
Document how MISSING nodes work

### ISSUE THREAD

**Issue by Timmmm** [tree-sitter/tree-sitter#650]
If I parse a file that contains a couple of errors using `tree-sitter parse corpus/medium.rpc` I get this:

```
...
    (structField [25, 2] - [25, 32]
      structFieldName: (fieldName [25, 2] - [25, 25])
      structFieldType: (type [25, 27] - [25, 31]))
    (ERROR [26, 2] - [26, 33]))
  (enum [29, 0] - [32, 1]
    enumName: (userTypeDeclaration [29, 5] - [29, 8])
    (enumVariant [30, 2] - [30, 4]
      enumVariantName: (variantName [30, 2] - [30, 3]))
    (enumVariant [31, 2] - [31, 7]
      enumVariantName: (variantName [31, 2] - [31, 3])
      enumVariantType: (userTypeUse [31, 4] - [31, 5]))))
corpus/medium.rpc       0 ms    (MISSING "," [24, 39] - [24, 39])
```

The first `ERROR` makes sense to me (although I have no idea how to get an actual error message from it). But I can't figure out the `MISSING` node. It doesn't seem to be part of the tree itself, and I can't find it using a query like `(MISSING) @missing`. Is there any way to access it so I can show a VSCode diagnostic?

**Comment by maxbrunsfeld** [comment]
Thanks for writing this up. I agree that there are some problems around `MISSING` nodes. I think we should make two changes:

* Always show `MISSING` nodes in the `tree-sitter parse` output (even if the node wouldn't normally be shown because it is anonymous).
* Allow tree queries to match against missing nodes.

**Comment by MixusMinimax** [comment]
For me, it doesn't really seem to be working at all sometimes.

For example, I have this rule:

```js
x: $ => seq(
  'let',
  field('name', $.identifier),
  '=',
  field('value', $._expression)
)
```

With the example code:

```
let = 1
```

You would expect this result:

```sexpr
(source_file
  (x
    (MISSING
      (identifier))
    (decimal)))
```

But I get

```sexpr
(source_file [0, 0] - [0, 7]
  (ERROR [0, 0] - [0, 7]
    (decimal [0, 6] - [0, 7])))
```

**Comment by ahlinc** [comment]
Tree-sitter doesn't create missing nodes with children nor create a `MISSING: ` field. The missing is a special status for a node that currently can be checked only over API. It would be good if the missing start to behave like a normal `MISSING:` field.

**Comment by MixusMinimax** [comment]
It seems like `MISSING` nodes only get created when the missing node is the last of a sequence.

I have a minimal case:

```js
f: $ => seq(
  $.let_identifier,
  '=',
  $._expression,
),

let_identifier: $ => seq('let', $.identifier),
```
```
let = 1
```

Here, the result is

```sexpr
(source_file [0, 0] - [0, 7]
  (f [0, 0] - [0, 7]
    (let_identifier [0, 0] - [0, 3]
      (identifier [0, 3] - [0, 3]))
    (decimal [0, 6] - [0, 7])))
example-file    0 ms    (MISSING identifier [0, 3] - [0, 3])
```

I of course want to parse a source file as well as possible, even with errors in it. The only solution I can find is to use a lot of intermediary non-terminals (like I just did), or make a lot of fields optional, and then check their existence manually.

**Comment by ahlinc** [comment]
> It seems like `MISSING` nodes only get created when the missing node is the last of a sequence.

No, it's just a bug in that representation.

**Comment by MixusMinimax** [comment]
I don't really care if they are nodes or not, my point is more about whether it is marked as missing or an error. I am not talking about there being a `MISSING` type or field name.

In the representation of the `parse` command it doesn't matter whether that is a bug or not; fact is tree-sitter was able to detect that something was missing, whereas it was not when I did not have these intermediary anonymous rules.
