### ISSUE TITLE
adding 'comment' to grammar always gives parse-time error.

### ISSUE THREAD

**Issue by stephe-ada-guru** [tree-sitter/tree-sitter#651]
The attached files demonstrate the bug: I'm trying to add an Ada-style comment to a trivial grammar, but I'm getting one error or another at parse time. Run 'make' and look at the *.parse files.

debug_comment_1.js was my first try; it has  /--.*/ in extras. In debug.input, the comment is "--  fcoo"; the 'c' is recognized as a token, which is wrong.

I found https://github.com/tree-sitter/tree-sitter-javascript/blob/master/grammar.js which has C++ style comments; that led me to debug_comment_2.js. That works better, but it still reports an error, because the 'comment' token is returned to the parser, which is not expecting it. The error is corrected by ignoring the token, and the rest of the parse succeeds, but it's not what I'm expecting.

I don't understand why /--.*/ is not the same as "seq('--', /.*/)".

Since 'comment' is in extras, I expect that either the lexer does not return 'comment', or the parser ignores it.

[debug_comment.tar.gz](https://github.com/tree-sitter/tree-sitter/files/4807067/debug_comment.tar.gz)

**Comment by maxbrunsfeld** [comment]
The grammar author is in control of the divide between the lexer and the parser. Normally, each string literal or regex literal is treated as a separate token by the lexer. You can wrap an arbitrary rule with the `token()` function to indicate that it should all be treated as a single token. So these two are equivalent:

1. `/--.*/`
2. `token(seq('--'), /.*/))`

**Comment by maxbrunsfeld** [comment]
Closing this out because I *think* this answers your question ☝️ , but feel free to reopen if there are other issues with comments.

**Comment by stephe-ada-guru** [comment]
Thanks, that helped. Just for the record, this grammar works as expected:

module.exports = grammar({
    name: 'Debug_Comment_2',
    extras: $ => [
        /[ \t\n]/,
        $.comment
    ],
    rules: {
        upper_s: $ => seq($.upper_c, $.upper_c),
        upper_c: $ => choice(seq("c", $.upper_c),"d"),
        comment: $ => token (seq('--', /.*/)),
    },
});
