### ISSUE TITLE
Parser creation doc instructions fail on Windows 10

### ISSUE THREAD

**Issue by ahelwer** [tree-sitter/tree-sitter#652]
I was following [these docs](https://tree-sitter.github.io/tree-sitter/creating-parsers) on Windows 10. Came to this step:

> You can test this parser by creating a source file with the contents “hello” and parsing it:
> 
> ```
> echo 'hello' > example-file
> tree-sitter parse example-file
> ```
> This should print the following:
> 
> (source_file [1, 0] - [1, 5])

But if I run these exact commands on Windows 10 in PowerShell, I get the following error:

```
(ERROR [0, 0] - [1, 1]
  (ERROR [0, 0] - [1, 1]))
.\example-file  0 ms    (ERROR [0, 0] - [1, 1])
```

This is tricky and frustrating because the file *looks* as expected. Creating a new blank file and manually typing in "hello" results in the file parsing just fine. The `echo` command in PowerShell just inserts some weird invisible garbage characters at the start of the file. Even WinMerge can't tell the two files apart, I had to use `fc`:

```
>fc /b example-file-fail example-file-succeed
Comparing files example-file-fail and EXAMPLE-FILE-SUCCEED
00000000: FF 68
00000001: FE 65
00000002: 68 6C
00000003: 00 6C
00000004: 65 6F
00000005: 00 0D
00000006: 6C 0A
```

I think it has to do with windows-1252 vs iso-10646 character encodings.

Also: if you instead run the echo command in cmd instead of PowerShell you'll get a file containing the string "'hello'" (single quotes included).

I don't really know of a good cross-platform way to write this step, but figure it's worth reporting because it frustrated me for a good bit before figuring it out, and hopefully by reporting it I can give someone else a great experience with the tutorial!

**Comment by maxbrunsfeld** [comment]
Ah yeah, sorry for the poor experience.

I am somewhat familiar with Windows, but didn’t know about this power shell behavior. If you find a simple way to make this cross platform, let me know. It’s fine if we need to change the example grammar in some way, to allow for more white space characters, or change the English text to domain anything better.

**Comment by ahelwer** [comment]
I've found a command that works in PowerShell:

```
"hello" | Out-File example-file -Encoding ascii
```

I can binary-reproduce the file that fails using this command:

```
"hello" | out-file example-file -Encoding unicode
```

So it definitely seems like an ascii/unicode thing. Which raises the question - does treesitter parse unicode files?

**Comment by maxbrunsfeld** [comment]
Yeah, the library supports both utf8 and UTF16. For the CLI, files need to be utf8. For basic Latin characters, ascii is the same as utf8.

“Unicode” is not an encoding, so I’m not sure what that failing command is doing. It makes sense that ascii works, because it is also valid utf8.

**Comment by ahelwer** [comment]
Following the method [here](https://stackoverflow.com/a/13464816/2852699), I found the encoding for the file that succeeds is UTF-8, and the encoding for the file that fails is UTF-16 LE. I've attached the two files.
[example-file-success.txt](https://github.com/tree-sitter/tree-sitter/files/4808567/example-file-success.txt)
[example-file-fail.txt](https://github.com/tree-sitter/tree-sitter/files/4808568/example-file-fail.txt)

**Comment by maxbrunsfeld** [comment]
Yeah, makes sense. The files need to Be UTF8 (or ascii). I’d be open to adding some kind of encoding detection to the CLI. That would solve this, and I think you can reliably detect if a file is UTF16 or UTF8.

**Comment by sirxyzzy** [comment]
It's all down to the BOM, you can see it above, for UTF-16 

00000000: FF 68
00000001: FE 65

UTF-16 *usually* does have a BOM, whereas UTF-8 may or may not have a BOM of  EF BB BF

Here is a description of all Microsoft recommended BOM codes... https://docs.microsoft.com/en-us/windows/win32/intl/using-byte-order-marks.

**Comment by ahlinc** [comment]
@ahelwer please,  don't close the uncompleted issue,  I plan to fix it soon. It's fixed in my fork discussed in a Discord channel, but final solution for upstream needs to be improved.

**Comment by ahelwer** [comment]
This has been fixed.
