### ISSUE TITLE
Explore verbosity settings for `tree-sitter parse`

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter#657]
While @maxbrunsfeld and I were revving the `tree-sitter-ql` grammar, we found some grammar weirdnesses that (we assume) were instituted to work around the fact that `tree-sitter parse` is reluctant to show a tremendous amount of information about the nodes in question (e.g. no text slices are printed). Max and I agreed that a `-v` mode might be useful for grammar development.

**Comment by WillLillis** [comment]
Addressed by #3762
