### ISSUE TITLE
Composability of alternations and field names in query patterns

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#659]
Can an alternation be put under a field name?

Using 2 separate patterns works as expected:

```clojure
(assignment_expression
 left: (identifier) @variable)
(assignment_expression
 left: (member_expression property: (property_identifier) @variable))
```
![2-patterns](https://user-images.githubusercontent.com/198359/85550111-d411e880-b64a-11ea-920c-8f684c88c99d.png)

Putting the field name in alternatives also works:

```clojure
(assignment_expression
 [left: (member_expression property: (property_identifier) @variable)
  left: (identifier) @variable])
```

When an alternation is put under a field name, the field name seems to be applied only to the first alternative:

```clojure
(assignment_expression
 left: [(identifier) @variable
        (member_expression property: (property_identifier) @variable)])
```
![field-alternations](https://user-images.githubusercontent.com/198359/85550116-d5431580-b64a-11ea-9d8f-553310793090.png)

```clojure
(assignment_expression
 left: [(member_expression property: (property_identifier) @variable)
        (identifier) @variable])
```
![field-alternations-1](https://user-images.githubusercontent.com/198359/85551002-bee98980-b64b-11ea-9c35-4fcec6bd1a9a.png)

**Comment by maxbrunsfeld** [comment]
Thanks for the report. This is a great example to use in the unit test.

**Comment by Vichugo1995** [comment]
Aceptando contra
