### ISSUE TITLE
Document `queries/tags.scm`

### ISSUE THREAD

**Issue by Neppord** [tree-sitter/tree-sitter#660]
While looking for examples of how to do highlights properly I found the `tags.scm` file in the `tree-sitter-python` repository. If this is what i think it is, a way to create ctags (or better, has to do wit tree-tags). Then it would be really nice to mention it in the documentation. Since this feature would be awesome!

I have searched, and not found any documentation.

**Comment by maxbrunsfeld** [comment]
Yeah, this is something we're intending to power code navigation on GitHub.com, but the design is not settled yet. We'll document it similarly to [syntax highlighting](https://tree-sitter.github.io/tree-sitter/syntax-highlighting) once it is shipped and the interface is stable.

**Comment by Razzeee** [comment]
I would love if you could keep this open and update us, when it's gone
stable :)

**Comment by maxbrunsfeld** [comment]
Oh yeah, you’re right; that makes sense.

**Comment by maxbrunsfeld** [comment]
The `tags` queries are now being used to power all code navigation on GitHub.com, so we are close to having a stable schema now.

I'm still going to hold off on committing to stability of the current schema (and documenting it) for a little bit longer, in case we find we need to make some changes.

**Comment by Razzeee** [comment]
So, is this considered stable now? It's also missing from the typescript typings it seems.

**Comment by Razzeee** [comment]
Can we also get these (and highlighting) via the wasm binding? As far as I understood that's not possible at the moment.

**Comment by Razzeee** [comment]
Can we get an update on this? Or is there anything the community can do to push this along?

**Comment by patrickt** [comment]
Will be fixed with https://github.com/tree-sitter/tree-sitter/pull/1649.

**Comment by bew** [comment]
#1649 is merged, close?
