### ISSUE TITLE
build.rs sample in readme for rust bindings

### ISSUE THREAD

**Issue by sirxyzzy** [tree-sitter/tree-sitter#662]
The readme for the rust bindings mention a build script containing

```rust
cc::Build::new()
    .include(&dir)
    .file(dir.join("parser.c"))
    .file(dir.join("scanner.c"))
    .compile("tree-sitter-javascript");
```

However, scanner.c does not appear to get generated, I get an error on cargo build, maybe it only exists in some cases? I had to comment that line out

**Comment by maxbrunsfeld** [comment]
Yeah, `scanner.c` is a hand-written. It is an [external scanner](https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners). Not all parsers will have these files. Maybe the docs should call this out more explicitly.

**Comment by sirxyzzy** [comment]
Thanks, I feel as newcomers to the library are unlikely to realize this, it would be reasonable to simply amend the doc to make build.rs work in the default case, then those who add an external scanner probably already know enough depth to augment the build.rs as required (or there could be a hint to that effect in the external scanners section)

Its no a big thing though, I worked it out quickly enough anyway, it just struck me that I might mention it hence the issue. I'm sure there are "bigger fish to fry"!

**Comment by RRethy** [comment]
Can the README also include build.rs steps for compiling parsers that have a `scanner.cc` or if there is an easier way to compile the parsers without having to check whether the repo has `scanner.c`, `scanner.cc`, or neither. For example, there is `npm install` that works in any of the tree-sitter repos.

I've been trying to get tree-sitter-cpp compiled using the `cc` crate but because the scanner is in c++, I've been having issues.

**Comment by maxbrunsfeld** [comment]
Recently, we've started generating `Cargo.toml` and `build.rs` files as part of `tree-sitter generate`, and keeping these files checked into the grammar repos.

**Comment by Razzeee** [comment]
@maxbrunsfeld any idea which dll windows might be missing? do I need to have that in the git repo?
https://github.com/elm-tooling/tree-sitter-elm/pull/96

Can you point out a project where your using the new generated bindings?

**Comment by Razzeee** [comment]
The error seems to be due to the `parser.lib`, `parser.exp` and `parser.obj` somehow colliding in windows, as we try to call compile on "parser". Are these old files, can they be omitted? Same question for `scanner.obj`
