### ISSUE TITLE
Three CodeQL warnings

### ISSUE THREAD

**Issue by XVilka** [tree-sitter/tree-sitter#664]
![image](https://user-images.githubusercontent.com/203261/86198904-47f04b80-bb8b-11ea-831c-b14dbe5b4a32.png)
![image](https://user-images.githubusercontent.com/203261/86198808-0bbceb00-bb8b-11ea-9cb6-beeb4c65595f.png)
![image](https://user-images.githubusercontent.com/203261/86198865-2a22e680-bb8b-11ea-8a45-5978bd758cc4.png)

**Comment by amaanq** [comment]
I think I fixed these recently, along w/ 7 others
