### ISSUE TITLE
How to iterate over all nodes at in a given range ?

### ISSUE THREAD

**Issue by vigoux** [tree-sitter/tree-sitter#665]
Hi I am experimenting things with treesitter, and I am trying to iterate over every single named node in a given range.
I was trying to use the `TSTreeCursor` thing but did not quite got it so I decided to dive a bit into treesitter code.

The solution I found was using a dummy `(_) @dummy` query to capture every node in here, but that's not really nice to do in the end.

How should I proceed then ?

PS: to give a bit of background I am working on treesitter integration with neovim, and especially syntax highlighting with it, but don't quite succeed...

**Comment by tjdevries** [comment]
@vigoux you should link the PR here as well I think so it's easier to get a bit more context (and maybe some recommendations about where we went wrong :laughing: )

**Comment by vigoux** [comment]
Oh yeah of course, here is the PR that causes trouble : https://github.com/neovim/neovim/pull/12502.
The thing we are concerned about here is performance.
The problem we want to address is to find what we call the _match stack_ at a given point, and this really quickly.
The way highlighting works is that we are drawing one line at a time, and thus for some overlapping queries (like lua `function ... end` and `if .. then ...end`), if we query only the current line, where the `end` is, it will not be matched at all. Thus our problem.

**Comment by maxbrunsfeld** [comment]
The "dummy" query shouldn't be *too* inefficient, actually.

But it might be more direct and slightly faster to write your own depth-first traversal with a `TSTreeCursor`.This takes a little bit of code, but it's not too complex. There are a few examples of this pattern in the Tree-sitter codebase. One is in the query implementation itself, in the private function [`ts_query_cursor__advance`](https://github.com/tree-sitter/tree-sitter/blob/de53b82e2c48d6221af9881e50cc57d961de3365/lib/src/query.c#L1524). But that function has a lot of additional complexity. A simpler example is [`ts_node_descendants_of_type_wasm`](https://github.com/tree-sitter/tree-sitter/blob/de53b82e2c48d6221af9881e50cc57d961de3365/lib/binding_web/binding.c#L477), from the WASM binding.

At a high level, you just need two variables: the tree cursor, and a boolean flag that indicates whether you're descending or ascending (in the two examples above, it's called either `ascending` or `already_visited_children`). 

---

@vigoux At a higher level, could you explain in more detail (or maybe just share a link to an existing explanation) of what the problems are with the Tree-sitter highlighting on the master branch of Neovim? I took a look at neovim/neovim#12502, but I am missing some background on what problem you're trying to solve there. I'm can't tell what the `match_stack` concept is needed for, or what it represents.

I don't have much knowledge of Neovim's internals, but there's a chance that I might be able to help with the problems you're facing with syntax highlighting.

**Comment by vigoux** [comment]
I finally got it to work and [here](https://github.com/neovim/neovim/pull/12502/files#diff-5ee91216d7ccd53f980bbf60ffcc29a6R755) is our implementation. We are using the `TSTreeCursor` and it seems to work quite well.

---

I don't think we have an clear explanation, so I will try to be as clear as possible with my non native English.
In the aforementioned PR, we are actually solving two things, but only one is related to TreeSitter.
The thing is overlapping matches within the highlight query, let's take en example here.
The example lua code we are going to use will be the following
```lua
function foo(...)
  for val in ipairs(...) do
    if val > 0 then print(val) end
  end
end
```
## The current implementation

In the current implementation, `function` and its corresponding `end` are highlighted in a different color than `for` `if` or `end`.

Here is an example (simplified) query that overlaps, and that we want to be able to support:
```scheme
[
 "if"
 "for"
 "end"
] @keyword

("function" @function "end" @function)
```

The problem here is the `end` keyword, which we have trouble finding the _appropriate_ capture for.

My example is not that great because in the very case, here is a way to fix this 
```scheme
(
  [
    "if"
    "for"
  ] @keyword
  "end" @keyword
)

( "function" @function "end" @function)
```

But you get my point, we have trouble matching these kind of things. And as we are going to see later, this query will not work in our case either.

## Why this is not working

When drawing a screen in neovim, I think that we do it _line by line_ (@tjdevries might want to correct me here).
So the first implementation used to use the query over one line only. The becomes a problem when you hit on of the `end`, when using the query on here, it will logicaly match either `@keyword` in the first query, or nothing in the second, as we never _crossed_ any `if` nor `for`.

So an easy solution comes: query over the whole tree everytime, not only the current line. But the performance cost is astonishing because we will to a full pass over the tree for _every line in the screen_. You may think about some tiny optimisations here, like not doing the whole tree but only on some children of the root, or anything, but that's not my point either.

## Where we are now

Then here is what we currently do, we are trying to find which nodes are on that very line, and then what we will do is, by matching the query, determine _in one go_ which capture matches those nodes. But that's no good either.

The direction we are exploring now is redrawing the ranges that treesitter said have changed when editing. This is causing us some troubles but that is really on nvim's side and does not really need to be discussed here.
One important thing to note though is that redrawing on treesitter changes should be fine, because we will be sure to actually redraw an actual node as a whole.

**Comment by vigoux** [comment]
Update: I have a PR open : https://github.com/neovim/neovim/pull/12590 which attempts to move from the current line based implementation to a node based implementation. Some things are not working now and I need to figure out why, but the first results look promising (especially on performances side).

**Comment by maxbrunsfeld** [comment]
I'm going to close this one out, since it seems like your Neovim PR is working. Thanks!
