### ISSUE TITLE
Use of tree-sitter CST in LSP servers/compilers.

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#667]
I have today discovered tree-sitter project and I have some thoughts. After reading some materials in the Internet and watching https://www.youtube.com/watch?v=Jes3bD6P0To I get a feeling that people treat it as a tool for better highlighting and folding experience. I have started asking myself if there are benefits for using tree-sitter in my case. To be honest, I have never experienced the highlighting to take too long time for me. In case of folding, I am not a fan of it, and I do not use it at all.
So tree-sitter looked to me like an another useless tool for increasing load of my CPU. Now instead of running single parser in the LSP, I also have to run second parser for syntax highlighting, so I end up with increased overall parsing time, not decreased.

Then, it struck me, that tree-sitter has huge potential that no one talks about. I see tree-sitter as a language for implementing parsers in declarative way, and a tool for generating CST. If I could somehow pass the CST data to the LSP, then strip it into AST in the LSP, I wouldn't have to implement/maintain 2 parsers, but only single one. The overall performance gain would probably be significant. What is more, the CST generated by the tree-sitter can be also used for compiler and formatter/beautifier. At the end of the day I end up with bunch of tools and only single parser! This is insane, especially in case of languages, where very few people work on open source tools.

Have you thought about such usage? Have you thought how tree-sitter can be integrated with LSP servers/compilers?

**Comment by maxbrunsfeld** [comment]
> So tree-sitter looked to me like an another useless tool for increasing load of my CPU. Now instead of running single parser in the LSP, I also have to run second parser for syntax highlighting

As an aside, the idea is that Tree-sitter is significantly *faster* than the regex-based system that you're probably already using for syntax highlighting.

> Have you thought how tree-sitter can be integrated with LSP servers/compilers?

I think incremental highlighting is definitely useful for implementing LSP servers. Some LSP servers have been built this way:
* [bash](https://github.com/bash-lsp/bash-language-server)
* [ruby](https://github.com/rubyide/vscode-ruby/tree/master/packages/language-server-ruby)
* [elm](https://github.com/elm-tooling/elm-language-server)
* [wasm](https://github.com/wasm-lsp/wasm-language-server)

I think there may be some others in development.

**Comment by m-kru** [comment]
What about passing CST to the LSP server? It looks like the biggest issues to me right now.

**Comment by maxbrunsfeld** [comment]
I don't think it is worthwhile to exchange the CST between processes. It is a much larger data structure than the source code itself, and it can be derived from the source code (which is already needed in both processes) very efficiently.

**Comment by m-kru** [comment]
But then you need to parse the source code twice. The question is what would be faster. Exchanging CST or parsing the source code.

**Comment by dcreager** [comment]
The parsing is really quite efficient — have you benchmarked it and found it wanting?  As @maxbrunsfeld said, the CST would be quite large, and you'd still have to parse its JSON representation on the other side if you're sending it over a JSON-RPC channel such as LSP.

**Comment by maxbrunsfeld** [comment]
Adding onto that: exchanging the CST is much more complex, because that concept is not part of an existing standard like LSP, so it entails more coupling between the editor and the server.

The purpose of incremental parsing is to make parsing so fast that it's not a performance concern at all, either in your editor or in your language server.

**Comment by Razzeee** [comment]
But be aware, that none of the lsp implementations, that I'm aware of seem to be running in incremental mode.

I can only speak for the Elm server, but I don't think it has been a problem so far.

**Comment by m-kru** [comment]
The most important thing from my point of view is not the incremental parser per se, but single source of the syntax tree (single parser). Parsers are hard to write, maintaining multiple parsers, for the same language, in different tools is time-consuming. With tree-sitter I see a chance to have single parser. What is more, implemented in declarative way.
