### ISSUE TITLE
grammar.js for case insensitive language

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#668]
Is there any way to declare in grammar.js, that the language is case insensitive? I know, that I can use regex in multiple places, but I would prefer some single line configuration, and then just use lowercase everywhere.

**Comment by maxbrunsfeld** [comment]
Just today I did [something related](https://github.com/tree-sitter/tree-sitter-php/commit/9e576b80aef33d84ca9fbd10feda619eaaa7c0e2) for PHP. There's no built in functionality for it, so I had to just write a helper function.

**Comment by m-kru** [comment]
If I understand correctly I need to copy `keyword` function? What is the purpose of `aliasAsWord` parameter?

**Comment by m-kru** [comment]
@maxbrunsfeld ping

**Comment by maxbrunsfeld** [comment]
Normally, there won't be syntax nodes created for regexes in the grammar (like `/[fF][oO][rR]/`), but there are [nodes for string literals](https://tree-sitter.github.io/tree-sitter/using-parsers#named-vs-anonymous-nodes).

But you can use `alias` to make a syntax node *appear* in the syntax tree as if you had used a string literal in the grammar:

```js
alias(/[fF][oO][rR]/, 'for')
```
