### ISSUE TITLE
20+ minutes for a 262 byte C++ file

### ISSUE THREAD

**Issue by intrigus-lgtm** [tree-sitter/tree-sitter#669]
Hi, I've been fuzzing `tree-sitter` recently and I did not find any crashes so far, but timeouts.

The file is 262 bytes big and it is running for at least 20 minutes now.
(I'm testing the file with the generated `cpp_fuzzer` that is based on https://github.com/tree-sitter/tree-sitter/blob/master/test/fuzz/fuzzer.cc I guess)
Should this be considered a bug? If yes, should I simply post the offending file here or should I share this privately?

**Comment by maxbrunsfeld** [comment]
Yes, I'd say this is a bug. It's ok to share the offending file, but thank you for checking.

**Comment by intrigus-lgtm** [comment]
````cpp
*ss<s"ss<sqXqss<s._<s<sq<(qqX<sqss<s.ss<sqsssq<(qss<qssqXqss<s._<s<sq<(qqX<sqss<s.ss<sqsssq<(qss<sqss<sqss<s._<s<sq>(qqX<sqss<s.ss<sqsssq<(qss<sq&=ss<s<sqss<s._<s<sq<(qqX<sqss<s.ss<sqs
````

**Comment by maxbrunsfeld** [comment]
Thanks very much, this was a pretty serious bug.

I'm surprised that our internal fuzzing didn't catch it. Maybe it doesn't happen as readily in languages other than C++. There also may be some limitations to our fuzzing process.

**Comment by intrigus-lgtm** [comment]
That was a fast fix :+1: 
It took about 2 hours to find this on a 8core/16thread machine.

Would you be interested in me integrating this with https://google.github.io/oss-fuzz/ ?
The goal of that would be this (taken from https://opensource.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html):
> Fuzz targets are checked into their upstream repository and integrated in the build system with sanitizer support (up to $5,000).
> Fuzz targets are efficient and provide good code coverage (>80%) (up to $5,000). 
> Fuzz targets are part of the official upstream development and regression testing process, i.e. they are maintained, run against old known crashers and the periodically updated corpora (up to $5,000).

**Comment by maxbrunsfeld** [comment]
/cc @philipturnbull @dcreager for thoughts on this ☝️ .

I'm personally very in favor of fuzzing, but have not myself done much of the work of setting it up.

**Comment by philipturnbull** [comment]
👋   Sorry, I missed this original ping. We're not currently running the fuzzing internally because of some infrastructure changes.

@intrigus-lgtm, feel free to work on the upstream integration with oss-fuzz. I don't know if the tree-sitter meets this requirement though:

> To qualify for these rewards, a project needs to have a large user base and/or be critical to global IT infrastructure.
