### ISSUE TITLE
Will this Keyword Extraction work

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#673]
Will following keyword extraction work:
```javascript
    identifier: $ => choice(
      $.basic_identifier,
      $.extended_identifier,
    ),
    
    word: $ => $.identifier,

    basic_identifier: $ => /([A-Z]|[a-z]|[0-9]|_)+/,

    extended_identifier: $ => /\\([A-Z]|[a-z]|[0-9]|_|\\)+\\/,
```
or do I rather need to define it in some different way, so that `word: $` refers explicitly to the `basic_identifier` and `extended_identifier`?

**Comment by maxbrunsfeld** [comment]
No, the `word` needs to be a single token (`basic_identifier`), not a parent node (`identifier`). Also, `word` is separate from the `rules` object. In your example, it looks like you've included `word` as the name of a rule. See https://tree-sitter.github.io/tree-sitter/creating-parsers#keyword-extraction.

**Comment by m-kru** [comment]
@maxbrunsfeld 
Is following correct?
```javascript
 word: $ => [$.basic_identifier, $.extended_identifier]
```
or maybe
```javascript
 word: $ => $.basic_identifier,
 word: $ => $.extended_identifier,
```
As you can see, I need to support 2 types of identifiers.

**Comment by maxbrunsfeld** [comment]
There can only be one word token. So you'll have to figure out which one makes sense to use. Unless it's very important do distinguish `extended_identifier` from `basic_identifier`, you may just want to combine them into one token.

**Comment by m-kru** [comment]
I need to distinguish them.  The `basic_identifier` is more often used, so I will chose it for word token.
