### ISSUE TITLE
[Question] How to handle different versions of a language?

### ISSUE THREAD

**Issue by Neppord** [tree-sitter/tree-sitter#674]
When using advanced editors / IDEs I really like the feedback I get on what constructs are only allowed in one version or dialect. I have tried to view already existing grammars for languages such as PHP and Python to see how it is normally treated in tree-sitter.

I have so far not seen any mechanism used to determine the version of the language and pick the correct grammar. Is the correct way to write a tree-sitter grammar to just allow every variation of the language in the same grammar?

For very different versions of a language should I create more then one tree-sitter package/grammar?

**Comment by Neppord** [comment]
might be related to #646

**Comment by maxbrunsfeld** [comment]
Tree-sitter is largely focused on use cases like text editors (and github.com) where you can’t reliably know the version of a language in advance. All you know is a file name. So in our projects, It wouldn’t be useful to create separate grammars for each version of a language.

It’s not a policy that’s built into Tree-sitter though. It would work fine to make a grammar for a specific language version.
