### ISSUE TITLE
'multiple' field in node-types.json incorrect for fields with repeated elements

### ISSUE THREAD

**Issue by tgascoigne** [tree-sitter/tree-sitter#676]
I'm attempting to consume the generated node-types.json to auto-generate structures in another language. I'm seeing some behavior I wasn't expecting when making use of fields within my grammar. It looks like the `multiple` flag is not set correctly when the field refers to a repeated rule.

For the following grammar:
```js
module.exports = grammar({
    name: 'test',

    rules: {        
        node_with_field: $ => seq(
            field('foos', repeat($.number)),
        ),

        number: $ => /\d+/
    }
});
```

It produces this node-types.json:
```json
[
  {
    "type": "node_with_field",
    "named": true,
    "fields": {
      "foos": {
        "multiple": false,
        "required": false,
        "types": [
          {
            "type": "number",
            "named": true
          }
        ]
      }
    }
  },
  {
    "type": "number",
    "named": true
  }
]
```

For reference, [here's the corresponding output](https://gist.github.com/tgascoigne/49922996d17ce7015d5c2ba1aaa58ed3) when not using a field. The repeated rule has `multiple: true` as expected.

```
$ tree-sitter -V
tree-sitter 0.16.8 (9a82dcc666d06617cbab3061467075019fae0b0d)
```

Update: As a workaround I've just discovered that putting the field on the inside of the repeat seems to generate the correct output: `repeat(field('foos', $.number))`. Perhaps this is the expected way to do this kind of thing?

**Comment by maxbrunsfeld** [comment]
Ideally, both would work, but the workaround you found looks good for now. Thanks for the great reproduction procedure; I'll try and fix this when I get a chance.

**Comment by maxbrunsfeld** [comment]
This will be fixed in the next version of the Tree-sitter CLI.
