### ISSUE TITLE
Cannot generate on a mac

### ISSUE THREAD

**Issue by fgmccabe** [tree-sitter/tree-sitter#677]
Tried following installation instructions.

When I execute tree-sitter generate
I get:
[stdin]:43
function choice(...elements) {
                ^^^

SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:425:26)
    at node.js:589:27
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)

Node process exited with status 1

Since I am new to this, I have no idea of what is going on. I tried prepping for some of the strings in this message and found nothing.

Trying to install and use on mac os 10.15.5

Help would be awesome!

Francis
P.S. The version I installed was 0.16.8

**Comment by maxbrunsfeld** [comment]
What version of node.js do you have installed?

**Comment by fgmccabe** [comment]
node -v says v5.1.0

**Comment by maxbrunsfeld** [comment]
Ok, I think you’ll just need to upgrade to a more recent version of node. Node 5 is many years old and doesn’t support modern JavaScript features.

**Comment by maxbrunsfeld** [comment]
I tried to make the built-in JavaScript code compatible with fairly old versions of Node.js, but there is one construct (Proxies) that is fairly important, and that requires Node.js >= 6.0 (which is still very old). I've documented that requirement now.
