### ISSUE TITLE
The rule matches the empty string.

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#679]
Take a look at following rules:
```typescript
    entity_declaration: $ => prec.right(seq(
      'entity', $.identifier, 'is',
      $.entity_header,
      $.entity_declarative_part,
      optional(seq('begin', $.entity_statement_part)),
      'end', optional('entity'), optional($.entity_simple_name),
      $.semicolon
    )),

    entity_header: $ => seq(
      optional($.formal_generic_clause),
      optional($.formal_port_clause)
    ),
```

During generation I get following error:
```
The rule `entity_header` matches the empty string.

Tree-sitter does not support syntactic rules that match the empty string
unless they are used only as the grammar's start rule.
```

I understand the error, but what I have defined exactly resembles the standard:
![image](https://user-images.githubusercontent.com/26227737/87079943-1deff680-c227-11ea-979d-4ea934b18dd9.png)
![image](https://user-images.githubusercontent.com/26227737/87079996-35c77a80-c227-11ea-9ff3-37483311dce2.png)

I know, that I can fix this issue by removing `entity_header` rule and moving 
```typescript
      optional($.formal_generic_clause),
      optional($.formal_port_clause)
```
to the `entity_declaration` rule.
However, then it does not reflect the standard.
Is there anyway to generate without error, and keep the structure from standard?

**Comment by maxbrunsfeld** [comment]
No. Matching a language spec exactly is not a goal. Language specifications are not designed to be used verbatim for producing useful syntax trees. You'll need to make some adjustments like this, and that is normal and expected.

**Comment by stephe-ada-guru** [comment]
Max Brunsfeld <notifications@github.com> writes:

> No. Matching a language spec exactly is not a goal. Language
> specifications are not designed to be used verbatim for producing
> useful syntax trees. You'll need to make some adjustments like this,
> and that is normal and expected.

In general, it is possible to generate an LR parse table from a grammar
with syntactic rules that match the empty string (aka nullable
productions, empty productions). Why is tree-sitter imposing this
restriction?

-- 
-- Stephe

**Comment by maxbrunsfeld** [comment]
> Why is tree-sitter imposing this restriction?

Yeah, that's a good question. There are two reasons.

The initial reason is that empty productions make incremental parsing more complex. It's definitely possible to handle them, but forbidding them simplifies the node-reuse logic.

The second reason is that Tree-sitter produces concrete syntax trees, and these CSTs are intended to be structured in a predictable, intuitive way, to simplify code analysis. Having syntax nodes that represent *nothingness* can be somewhat weird and counterintuitive, so it's helpful to have a consistent policy about how optional constructs should be structured. By forbidding empty productions, we ensure that the same policy is used everywhere, and add an invariant that you can rely on when consuming a syntax tree.

So for me, it's a case where internal simplicity and API simplicity align with each other.

**Comment by stephe-ada-guru** [comment]
Max Brunsfeld <notifications@github.com> writes:

>> Why is tree-sitter imposing this restriction?
>
> Yeah, that's a good question. There are two reasons.
>
> The initial reason is that empty productions make incremental parsing
> more complex. It's definitely possible to handle them, but forbidding
> them simplifies the node-reuse logic.

That's a good reason. Simpler logic is more likely to be correct, and
have fewer corner cases.

> The second reason is that Tree-sitter produces concrete syntax trees,
> and these CSTs are intended to be structured in a predictable,
> intuitive way, to simplify code analysis. Having syntax nodes that
> represent *nothingness* can be somewhat weird and counterintuitive, so
> it's helpful to have a consistent policy about how optional constructs
> should be structured. By forbidding empty productions, we ensure that
> the same policy is used everywhere, and add an invariant that you can
> rely on when consuming a syntax tree.

Meh.

I suggest this rationale should be in the docs; somewhere near the top
of the Writing Grammars section. You could also mention a simple
algorithm to remove an empty rule;

    1. Make the rule non-empty
    2. Change all occurances of the rule to be optional.

-- 
-- Stephe
