### ISSUE TITLE
Unit testing highlighting

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#680]
Hey, 

I started toying with the highlighting, but I'm struggling to get the unit tests working.

1. I tried to reference the import string via `"import" @keyword`, but that didn't work. What's needed for that? Instead this worked (which is also fine I guess) https://github.com/Razzeee/tree-sitter-elm/commit/626ed40e85cd22391e961bb6c9e6e081a8ca9df7#diff-33e4205820b08cfede793a8bbcba3921R3

2. I'm getting this when running the tests
```
syntax highlighting:
  ✓ basic.elm (0 assertions)
```
Which I don't understand, as there should be assertions. https://github.com/Razzeee/tree-sitter-elm/commit/626ed40e85cd22391e961bb6c9e6e081a8ca9df7#diff-65b4373276cdd33af660d4d8898bf510R4

Is it a problem/bug, if my language doesn't use `//` to comment, but consumes these? I would expect `// <-` and `// ^` to be removed before highlighting and testing.

**Comment by maxbrunsfeld** [comment]
You should be able to just use your language’s comments.

**Comment by Razzeee** [comment]
can you answere 1.?

the solution seems to work for 2.

but can I test comment highlighting somehow?

**Comment by Razzeee** [comment]
Also, should having locals in place lead to underlining like shown in https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables

**Comment by Razzeee** [comment]
Found an answere to 1. in https://github.com/tree-sitter/tree-sitter/issues/572#issuecomment-596682059

**Comment by maxbrunsfeld** [comment]
Yeah, you can test comment highlighting just like any other node. Comments are only treated as assertions if the comment text begins with the `<-` or `^` characters.
