### ISSUE TITLE
What are the differences between an inline named rule and a rule written inline?

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#683]
I'm adding [support for omitting parentheses](https://github.com/ubolonton/tree-sitter-scala/commit/18180e8fcc082b7ea59ee69738869deb25de6ad7#diff-95fc33185b7215010b60f43469000a7aR420) in Scala's `function_type`.

In this example code, there's a conflict between `parameter_types` and `tuple_type`:
```scala
type A = (B, C) => D
```

If I write the rule directly inline, it works as expected, with a `select_higher_precedence` that chooses the `parameter_types` fork.

```javascript
    function_type: $ => prec.right(-2, seq(
      choice(
        // Prefer parameter_types over a single tuple_type.
        prec.dynamic(-1, $._annotated_type),
        $.parameter_types,
        $.compound_type,
        $.infix_type,
      ),
      // Prefer function_type.parameter_types over infix_type.tuple_type.
      prec.dynamic(1, '=>'),
      field('return_type', $._type)
    )),
```

```clojure
(compilation_unit [0, 0] - [1, 0]
  (type_definition [0, 0] - [0, 20]
    name: (type_identifier [0, 5] - [0, 6])
    type: (function_type [0, 9] - [0, 20]
      (parameter_types [0, 9] - [0, 15]
        (type_identifier [0, 10] - [0, 11])
        (type_identifier [0, 13] - [0, 14]))
      return_type: (type_identifier [0, 19] - [0, 20]))))
```

However, if I extract that rule into a named inline rule, it chooses `tuple_type` by a `select_earlier`.

```javascript
  inline: $ => [
    $._function_arg_type,
  ],
  
  rules: {
    function_type: $ => prec.right(-2, seq(
      $._function_arg_type,
      // Prefer function_type.parameter_types over infix_type.tuple_type.
      prec.dynamic(1, '=>'),
      field('return_type', $._type)
    )),

    _function_arg_type: $ => choice(
      // Prefer parameter_types over tuple_type for LHS.
      prec.dynamic(-1, $._annotated_type),
      $.parameter_types,
      $.compound_type,
      $.infix_type,
    ),
  }
```

```clojure
(compilation_unit [0, 0] - [1, 0]
  (type_definition [0, 0] - [0, 20]
    name: (type_identifier [0, 5] - [0, 6])
    type: (function_type [0, 9] - [0, 20]
      (tuple_type [0, 9] - [0, 15]
        (type_identifier [0, 10] - [0, 11])
        (type_identifier [0, 13] - [0, 14]))
      return_type: (type_identifier [0, 19] - [0, 20]))))
```

Here are the log files:
https://gist.github.com/ubolonton/2c5462d5b23524562a30c673dfc2f884#file-log-written-inline-html
https://gist.github.com/ubolonton/2c5462d5b23524562a30c673dfc2f884#file-log-inline-rule-html

It seems that the "condensed branches" are "uncondensed" in the first case, not the second case (I don't know what are the correct terminologies).

**Comment by maxbrunsfeld** [comment]
Hmm, I’ll have to look more later. It seems like they should behave the same, but dynamic precedence is not being respected correctly by the inlined rule.

**Comment by maxbrunsfeld** [comment]
Ok, I'm guessing you already found a workaround for this, but the next Tree-sitter CLI version will have this bug fixed.
