### ISSUE TITLE
Range-restricted query execution returns fewer results when there are more patterns

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#685]
This is the C code:

```c
DEFUN ("safe-length", Fsafe_length, Ssafe_length, 1, 1, 0)
```

I used the `--byte-range` flag from #684 to test it:
```bash
tree-sitter query --byte-range 0:27 --captures test.scm test.c
```

With this query, `.captures` returns the correct results:

```clojure
(string_literal) @string
```
```
test.c
    pattern: 0, capture: string, row: 0, text: "\"safe-length\""
```

With this additional pattern, `.captures` returns no result:
```clojure
(call_expression
 function: (identifier) @function
 arguments: (argument_list (string_literal) @string.arg))

(string_literal) @string
```

Querying with `.matches` returns the correct results.

```
test.c
  pattern: 0
    capture: function, start: (0, 0), text: "DEFUN"
    capture: string.arg, start: (0, 7), text: "\"safe-length\""
  pattern: 1
    capture: string, start: (0, 7), text: "\"safe-length\""
```

Will #644 also fix this?

**Comment by maxbrunsfeld** [comment]
Thanks for the report. I think this is a totally separate bug. Looking now...

**Comment by maxbrunsfeld** [comment]
Ok, there's a pretty simple bug that has to do with early termination when exceeding the max byte in the range. I still need to write up a unit test (probably using your example verbatim), but the fix shouldn't take long.
