### ISSUE TITLE
Highlighing and tagging apis?

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#687]
Hey there,

if I understand correctly highlighinig only got a Rust/C library?

Is there more on the roadmap, as I was able to consume everything from JS so far? What will be the deal with tagging?

Cheers

**Comment by maxbrunsfeld** [comment]
For highlighting (and tagging) most of the work is done by the query API, which is already exposed to JavaScript.

There is some additional work around tracking local variables and performing language injection, which is currently implemented in the `tree-sitter-highlight` Rust crate. That crate doesn't handle *editing* source code, or highlighting specific ranges of a file; it just operates on entire files. It is mostly designed for:
* syntax highlighting on GitHub
* testing syntax highlighting at the command line

For now, I don't plan on developing additional highlighting functionality. Other applications that want to do highlighting will have to build directly upon the query API. But you can get pretty good highlighting using just that!

Tagging (when it is finished) will probably be the same: there will be a rust crate which implements the entire thing, for use on GitHub and testing via the CLI. Tagging is even simpler though. It's almost entirely just running a tree query.

**Comment by Razzeee** [comment]
Do we have docs about working with queries?
I would have expected to at least find something in https://github.com/tree-sitter/node-tree-sitter/blob/master/tree-sitter.d.ts that says query? Am I looking in the wrong place?

Nevermind, I guess that this needs merging first https://github.com/tree-sitter/node-tree-sitter/pull/62

**Comment by Razzeee** [comment]
For reference, we started extending the typescript definition file https://github.com/elm-tooling/elm-language-server/blob/6d794a8e994accebf7d6078c7cfacac483fe2f3c/src/typings/tree-sitter-web.d.ts

I'm still not sure how to query for highlighting stuff, but I haven't really played around with it yet.
