### ISSUE TITLE
Rule functions with the same name don't collide

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#689]
Hey there,

shouldn't rules collide in some way, if they have the same function name?

I seem to have two functions of the same name:
https://github.com/Razzeee/tree-sitter-elm/blob/master/grammar.js#L77
https://github.com/Razzeee/tree-sitter-elm/blob/master/grammar.js#L223

Which is easily fixable, but it would be nice to not allow this in the first place.

**Comment by maxbrunsfeld** [comment]
Because we're using JavaScript to evaluate your grammar, we can't really detect this. The earlier key has no visible effect on the output. One option is to run a linter (or typescript) on your `grammar.js` before running `tree-sitter generate`, via some kind of script.

**Comment by Razzeee** [comment]
But aren't you solving the conflict at generate time? That's why the first one won't matter isn't it? I would have expected, that we could error during generate.

**Comment by Aerijo** [comment]
The point is it doesn't get past the JS engine. `const foo = {a: 5, a: 4}` is valid JS, where `foo === {a: 4}`. That's why a linter was suggested, as it looks at the source code.

**Comment by Razzeee** [comment]
So I guess the next version including https://github.com/tree-sitter/tree-sitter/pull/658 would have surfaced that problem.
