### ISSUE TITLE
Problem with decimal literal parsing.

### ISSUE THREAD

**Issue by m-kru** [tree-sitter/tree-sitter#691]
Following rules from LRM define decimal literal:
```javascript
    decimal_literal: $ => seq(
      $.integer,
      optional(seq('.', $.integer)),
      optional($.exponent)
    ),

    // TODO: Fix regex for 123_12312_, '_' is not allowed at the end.
    integer: $ => /\d([\d|_])*/,

    exponent: $ => choice(
      seq('E', optional('+'), $.integer),
      //seq('E', '-', $.integer),
    ),
```

`1E 10` is parsed correctly. `1 E 10` is also parsed correctly. However `1E10` gives an error.
Is there something I am missing? Like for example. there must a white space before regex?

**Comment by Razzeee** [comment]
I think you need to use token.immediate as an additional choice in your
exponential function

**Comment by m-kru** [comment]
What does `token.immediate` do? I can't find it in [Creating parsers](https://tree-sitter.github.io/tree-sitter/creating-parsers) documentation.

**Comment by Razzeee** [comment]
I think normally after each element tree-sitter wants a whitespace or something similar to keep elements apart. This basically allows, that you can match without a whitespace.

**Comment by maxbrunsfeld** [comment]
Usually, whitespace (and any other `extras`, such as comments) is optional before each token. The `token.immediate` function means that the token will only match if there is *no* whitespace.

@m-kru The normal approach with parsing things like decimal literals is to treat them as one single token, not a tree that contains many tokens. This can be done in two ways:
* write the rule as a single regex (like `integer`)
* wrap the rule in a call to `token()` (or `token.immediate`, if you want to disallow whitespace).

Does that make sense?
I would use `token()`. Inside of that though, you can't have child rules (e.g. `$.integer`). You'll need to write it somewhat differently.

**Comment by m-kru** [comment]
@maxbrunsfeld Let's assume I want to later compile the code. Which approach do you think is more appropriate? With regex I would later still need to parse it, to get to know if it is positive/negative, and to get the value.

**Comment by Vehmloewff** [comment]
@maxbrunsfeld Do you think that it would be practical to put that explanation of `token.immediate` in the "Creating parsers" documentation?  It would've liked to find it there a few hours ago... :)

Are there any other undocumented grammar functions that I should know about?

**Comment by sogaiu** [comment]
FWIW, one place I found mention of some behavior of token.immediate is here: https://github.com/tree-sitter/tree-sitter/blob/1dcbd21bbefe5a68546b368a64eabd2bedbbe05f/test/fixtures/test_grammars/immediate_tokens/readme.md

**Comment by Vehmloewff** [comment]
Ahh.  Thanks @sogaiu.  The `test/fixtures/test_grammars` folder is a good recourse to have handy.

I still think that adding in that one short paragraph about the definition of `token.immediate` into the official docs would help out newcomers.
