### ISSUE TITLE
Context-aware associativity?

### ISSUE THREAD

**Issue by ubolonton** [tree-sitter/tree-sitter#697]
I'm trying to add `function_expression` to the Scala grammar.

It seems like the associativity of its body (`_block`) should be context-aware.

Inside a `block`, it should be right associative:
```scala
object X {
  val y = { (b: Int) => b
    f()
  }
}
```
```clojure
(compilation_unit
  (object_definition (identifier)
    (template_body
      (val_definition (identifier)
        (block
          (function_expression
            (function_parameters
              (identifier) (type_identifier))
            (identifier)
            (call_expression (identifier) (arguments))))))))
```

Inside a `template_body`, it should be left associative:
```scala
object X {
  val x = (b: Int) => b
  f()
}
```
```clojure
(compilation_unit
  (object_definition (identifier)
    (template_body
      (val_definition (identifier)
        (function_expression
          (function_parameters
            (identifier) (type_identifier))
          (identifier)))
      (call_expression (identifier) (arguments)))))
```

The second example failed to parse, because I couldn't figure out how to make associativity context-aware. Is that possible, or should the rules be reorganized somehow? (I don't want to have 2 separate visible node types for "function expression".)

The current state of the grammar is [here](https://github.com/ubolonton/tree-sitter-scala/commit/1646a3ca5ba6e2254b41bcf12d416e50366e1419). These are the relevant rules:

```javascript
{
    // Block
    _block: $ => seq(
      sep1($._semicolon, choice(
        $._expression,
        $._definition_in_block,
      )),
      optional($._semicolon),
    ),

    // '{' Block '}'
    block: $ => seq(
      '{',
      optional($._block),
      '}'
    ),

    function_expression: $ => seq(
      field('function_parameters', $.function_parameters),
      '=>',
      field('body', prec.right($._block)),
    ),
}
```

Note: The EBNF for this part seems to be incorrect. I checked the above code snippets with IntelliJ, `scalac` and the online scalameta-based [AST explorer](https://scalameta.org/docs/trees/astexplorer.html).

**Comment by ubolonton** [comment]
My current thinking is having the scanner return different semicolon tokens, based on the context:

```javascript
{
  externals: $ => [
    $._block_start,
    $._block_end,
    $._function_expression_arrow,
    // Not $._automatic_semicolon, because real semicolons are ambiguous too.
    $._semicolon_l,
    $._semicolon_r,
  ],
  
  conflicts: $ => [
    // Will be resolved by the scanner, instead of dynamic precedences.
    [$._block_l, $._block_r],
  ],
  
  rules: {
    block: $ => seq(
      $._block_start,
      optional($._block_l),
      $._block_end,
    ),
    
    _block_l: $ => prec.left(seq(
      sep1($._semicolon_l, choice(
        $._expression,
        $._definition,
      )),
      optional($._semicolon_l),
    )),

    // Only used in $.function_expression.
    _block_r: $ => prec.right(seq(
      sep1($._semicolon_r, choice(
        $._expression,
        $._definition,
      )),
      optional($._semicolon_r),
    )),

    function_expression: $ => seq(
      field('function_parameters', $.function_parameters),
      $._function_expression_arrow,
      field('body', choice(
        $._block_l,
        $._block_r,
      )),
    ),
  }
}
```

Is this approach reasonable, or am I missing something?

**Comment by maxbrunsfeld** [comment]
> Inside a `block`, it should be right associative:

> Inside a `template_body`, it should be left associative:

Wow, that's a very strange aspect of the scala language.

Having two separate `_block` rules seems like a reasonable way to model this. I can't tell why the separate `semicolon` tokens are needed, but I haven't checked out the code myself yet.

> I don't want to have 2 separate visible node types for "function expression"

This *might* be a simpler solution. You could have a `function_expression_within_block` rule, which would have a different associativity to its body. You could then *alias* that rule so that appears as a `function_expression`, in order to avoid adding complexity to the output tree.

**Comment by ubolonton** [comment]
> Having two separate `_block` rules seems like a reasonable way to model this. I can't tell why the separate `semicolon` tokens are needed, but I haven't checked out the code myself yet.
> 
The lexer would disallow `_semicolon_l` in a `block` context, and disallow `_semicolon_r` in a `template_body` context.



> This _might_ be a simpler solution. You could have a `function_expression_within_block` rule, which would have a different associativity to its body. You could then _alias_ that rule so that appears as a `function_expression`, in order to avoid adding complexity to the output tree.
> 
Thanks, I totally overlooked this. In fact, I checked the EBNF again, and it actually uses separate rules for these.
