### ISSUE TITLE
Rule order matters but is not documented

### ISSUE THREAD

**Issue by smackesey** [tree-sitter/tree-sitter#702]
This simple grammar behaves differently depending on whether `alpha` is defined before `content` or vice-versa:

```javascript
module.exports = grammar({

  name: 'test',

  rules: {

    source_file: $ => repeat1(choice(
      $.content,
      $.alpha,
    )),

    alpha: _$ =>  /abc\n/,

    content: _$ => prec.right(repeat1(/.+\n/)),

  },

});
```

Consider this input:

```
xxx
abc
xxx
```

If `alpha` is defined first, this parses to:

```
(source_file [0, 0] - [3, 0]
  (content [0, 0] - [1, 0])
  (alpha [1, 0] - [2, 0])
  (content [2, 0] - [3, 0]))
```

If `content` is defined first, we get:

```
(source_file [0, 0] - [3, 0]
  (content [0, 0] - [3, 0]))
```

The importance of rule order is not mentioned in the [Creating parsers](https://tree-sitter.github.io/tree-sitter/creating-parsers) docs.

**NOTE** This is a contrived example that illustrates a similar situation I ran into where I was trying to have an `alpha`-like rule take precedence over a generic-line-matching `content` rule. Still not sure how to do it, setting `prec` on `alpha` does not make it override `content`, only changing the order does from what I can tell.

**Comment by maxbrunsfeld** [comment]
Thanks for pointing this out. I've now mentioned in the docs that rule order is used as a fallback criteria for resolving lexical ambiguity.

In your case, I think you may want to use lexical precedence (item 2 in [the docs](https://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens) for conflicting tokens).
