### ISSUE TITLE
Adding a not quantifier to the tree query syntax

### ISSUE THREAD

**Issue by vigoux** [tree-sitter/tree-sitter#705]
It would be awesome to have some kind of `not` operator within queries. 

As discussed [here](https://github.com/nvim-treesitter/nvim-treesitter/pull/252#discussion_r464537827), the proposal we have is a regex-like implementation looking like this :

```
[^ (node1) (node2) ] ; This will match anything but node1 and node2
```

For implementation purposes, it would not be allowed (in the first place) to have things like this :

```
[^
  (node1 (node2)) ;; ERROR : You can't match subtrees
]
```

**Comment by tazjin** [comment]
A strange use-case I have where this would be very useful is "find all public members of a struct/class in C++". Basically you want a query listing all siblings that are *not* an access-specifier. Right now I have to hard-code a list of possible children (extra difficult because I have to include stuff like `comment`), whereas what I really want is to say `[^ (access_specifier)]`.

**Comment by ahlinc** [comment]
@amaanq could you look on to this issue? I suppose [recently added](https://github.com/tree-sitter/tree-sitter/pull/2532) by you additional query predicates like `any-not-match?` may cover this case?

**Comment by tazjin** [comment]
@ahlinc I think those are slightly different, in that they don't match on nodes but their textual content (if I understood them correctly). So in my example, you'd have to write a non-match against every possible access specifier (which might end up being less text to write for the query, but it might end up being slower as these predicates are not part of the query language itself).

**Comment by amaanq** [comment]
Yeah, match is to evaluate a regex on the content of the node, but any-not-eq? can be used to compare node types

**Comment by ahlinc** [comment]
So I suppose this can be closed?

**Comment by tazjin** [comment]
I'd just note that this isn't core support in tree-sitter, just two of the tree-sitter binding libraries.

**Comment by amaanq** [comment]
I plan on adding it to Python/Node's bindings as well but of course not every binding is maintained upstream
