### ISSUE TITLE
Graphviz generation sometimes fails with syntax error for dot

### ISSUE THREAD

**Issue by smackesey** [tree-sitter/tree-sitter#709]
I think it has something to do with whitespace literals-- probably something needs to be escaped in the dot input. Here's a small example that causes failure:

Grammar:

```javascript
module.exports = grammar({

  name: 'memexwiki',

  extras: _$ => [],

  rules: {

    source_file: $ => repeat1(seq(
      $.paragraph,
      repeat(seq(
        '\n\n',
        $.paragraph,
      )),
    )),

    paragraph: $ => seq(
      $.plain_text,
      repeat(seq(
        $.space,
        $.plain_text,
      )),
    ),

    space: _$ => ' ',

    plain_text: $ => prec.right(seq(
      $.word,
      repeat(seq(
        $.space,
        $.word,
      )),
    )),

    word: _$ => token(prec(-1, /\S+/)),

  },

});
```

Test input (test.txt):

```
Lorem ipsum domini
```

Command:

```
$ tree-sitter parse test.txt -D
```

Output:

```
(source_file [0, 0] - [1, 0]
  (paragraph [0, 0] - [0, 18]
    (plain_text [0, 0] - [0, 18]
      (word [0, 0] - [0, 5])
      (space [0, 5] - [0, 6])
      (word [0, 6] - [0, 11])
      (space [0, 11] - [0, 12])
      (word [0, 12] - [0, 18])))
  (ERROR [0, 18] - [1, 0]
    (ERROR [0, 18] - [1, 0])))
test.txt	0 ms	(ERROR [0, 18] - [1, 0])
Error: <stdin>: syntax error in line 522 near '"'
Dot failed:
error Command failed with exit code 1.
```

**Comment by maxbrunsfeld** [comment]
Thanks for the report!

The relevant functions are [these](https://github.com/tree-sitter/tree-sitter/blob/55030afd13e6db6f016ea0d7a0dd0b1c7c332ecf/lib/src/stack.c#L722) [two](https://github.com/tree-sitter/tree-sitter/blob/55030afd13e6db6f016ea0d7a0dd0b1c7c332ecf/lib/src/subtree.c#L914). Are you interested in debugging this and submitting a PR?

**Comment by amaanq** [comment]
seems to be from outputting the `nul` character when the subtree is an error, I think the character should not be outputted  in this case where it's 0, it doesn't add value and we can see it's the `end` anyways in the graph output
