### ISSUE TITLE
Generated files in git repos are too big for us

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter#710]
[Here is a copy](https://github.com/returntocorp/tree-sitter-javascript-slim) of tree-sitter-javascript from which `src/parser.c` was removed. On my machine, it reduces the time to clone the repo from 12 s down to 1 sec. This is significant for us because we are going to work with a large number of the tree-sitter-* projects [as submodules](https://github.com/returntocorp/semgrep-grammars/tree/master/src).

Our solution consisting in automatically keeping a slimmed-down copy of each tree-sitter grammar repo will work, but it's not ideal because these "slim repos" are not compatible with the original ones, they don't benefit from the github fork features, commit IDs are different, etc; they're more like tarballs with a list of commit messages. A better setup would allow us to use the original repos as submodules, making it easier to create and test branches. But also we don't want to spend 2+ minutes of every CI job to just clone repos.

Questions:

* Is there any plan to permanently drop `parser.c` from all the tree-sitter-* repos?
* Any suggestion on how to deal with many tree-sitter grammars?

**Comment by patrickt** [comment]
Dropping the generated .c files would be a mistake, as the various client libraries in other languages depend on the presence of parser.c in the repository. Are there steps you can take to make your clones faster? Can you avoid checking out the submodules in CI and download tarballs from GitHub directly, or can you specify shallow submodule checkouts, or perhaps cache more aggressively?

**Comment by mjambon** [comment]
We're going to deal with 20+ grammars, so we'll be fine with a 10x speedup but not with 2x. The goal is fast CI and easy contributions back to the original repos.

Have you considered having source-only repos and secondary repos containing the generated code for user's convenience? For what it's worth, here's the code I used to rewrite the git history: https://github.com/returntocorp/semgrep-grammars/blob/5c7e5bff8752f9b3b54a095982b3fcc70976bccb/scripts/update-slim-repos . It's kind of sketchy.

**Comment by stephe-ada-guru** [comment]
Martin Jambon <notifications@github.com> writes:

> Questions:
>
> * Is there any plan to permanently drop `parser.c` from all the tree-sitter-* repos?
> * Any suggestion on how to deal with many tree-sitter grammars?

I'm not familiar with git submodules, but git worktrees solve this
problem in other cases; they have one copy of the repo serving several
checkouts. Do they work here?

-- 
-- Stephe

**Comment by maxbrunsfeld** [comment]
Do your CI builds use caching? At GitHub, we have a number of projects that use large numbers of grammars as submodules, but submodule cloning time has never been significant at all.

You also don't need to download the git repository. Like @patrickt said, you can just download a zip file of any commit. This is very fast.

```
time curl -sL https://github.com/tree-sitter/tree-sitter-typescript/archive/${TYPESCRIPT_SHA}.zip > typescript.zip

real	0m0.672s
user	0m0.026s
sys	0m0.021s
```

Removing `parser.c` from the repositories would inconvenience almost all consumers of these git repositories by requiring them to also download the `tree-sitter` command-line program and run `tree-sitter generate` as part of their build.

**Comment by mjambon** [comment]
@stephe-ada-guru wrote:
> I'm not familiar with git submodules, but git worktrees solve this problem in other cases; they have one copy of the repo serving several checkouts. Do they work here?

Git worktrees tackle the problem of dealing with multiple views of the same repo. This is the reverse of what we're interested in. We want access to unrelated repos as "sub-repos" of one project.

**Comment by mjambon** [comment]
@maxbrunsfeld I'll keep you up to date about performance after adding more grammars but it's not looking good.
 
I'll probably end up making slimmed-down clones of all the tree-sitter-* repos so we can work fast and comfortably on our end. It was just a heads-up, in case you were interested in having tree-sitter-src-* repos that contain only source code.

**Comment by maxbrunsfeld** [comment]
> My tests locally indicate that git clone --depth=1 is more than twice as fast on the tree-sitter-javascript repo than is a full clone.

This is a great point. In fact, for a larger repo like `tree-sitter-ruby`, it's more than 30x faster:

```
git clone -q --depth 1 https://github.com/tree-sitter/tree-sitter-ruby ruby-copy-$i

real	0m0.769s
user	0m0.098s
sys	0m0.091s
```

Shallow clones are very efficient for these repositories, because the `master` trees of these repositories are already very small. It's only the *history* that is large, because Tree-sitter's generated files used to much (sometimes 10x) larger than they are today, and we didn't always do squash merges on PRs.

Some day in the future, I might consider truncating the git histories of some of the larger repositories, because the generated file sizes have decreased so dramatically. But for the time being, I'd like to leave it intact, because the history is still somewhat useful, and shallow cloning seems to completely eliminate any slowness when cloning the repositories.

@mjambon I'm going to close this out for now, since the repo size problem can be addressed by either shallow clones, zip-file downloads, or caching.

**Comment by mjambon** [comment]
I just tried shallow cloning with `git submodule update --init --recursive --depth 1` and it works very fast indeed (1.3 s instead of 28 s for tree-sitter-typescript).

(I still think there will be more problems down the line, but I'll point them out as I encounter them and I'd love to be wrong)
