### ISSUE TITLE
Parsing the empty string twice, while trying to use the previous tree leads to an assert failure

### ISSUE THREAD

**Issue by Ryan1729** [tree-sitter/tree-sitter#712]
In the rust program I mentioned in #530, I recently started trying to actually pass down the properly-edited previous tree to tree-stiter, instead of always passing `None`. After doing that I started to run into assert failures with the following message:
```
src/./parser.c:863: ts_parser__accept: Assertion `ts_subtree_is_eof(lookahead)' failed.
```

I was able to reproduce the assert failure by simply attempting to parse the empty string twice, as is done in the following code:

```rust
    let mut parser = Parser::new();

    parser.set_language(rust_lang).unwrap();

    let to_parse = "";

    let mut tree = None;

    tree = parser.parse(to_parse, tree.as_ref());

    parser.parse(to_parse, tree.as_ref());
```

There's a complete program containing the above code, that reproduces the assert failure, in [this repo](https://github.com/Ryan1729/ts_subtree_is_eof_lookahead_assert_failure).

**Comment by Ryan1729** [comment]
As a guess, I tried calling `edit` on the tree in my small example program, passing an `&InputEdit` with all default values. This seems to have prevented the assert from failing, at least in this case. I pushed the change to [this branch](https://github.com/Ryan1729/ts_subtree_is_eof_lookahead_assert_failure/tree/workaround) in case that interests anyone.

**Comment by maxbrunsfeld** [comment]
Thanks for the good reproduction steps.
