### ISSUE TITLE
C trigraphs need to be escaped on some platforms

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter#714]
Summary: we should escape C string literals in a way that avoids two consecutive `?`. 

The C# grammar contains `??=` which becomes a C string literal `"??="`. It turns out this is a trigraph, which the C preprocessor may or may not turn into `"#"`.

* on my machine, with gnu cpp, I get a warning but the string is preserved.
* in my colleague's setup (tbd: which setup?), there's also a warning but the trigraph is expanded. In this case, `"??="` becomes `"#"` which is not intended and causes a parser bug.

The trigraph substitution presumably causes a self-generated [csharp](https://github.com/tree-sitter/tree-sitter-c-sharp) parser.c to fail to parse `??=`. In any case, we'd like to get rid of the warning.

Here's the original error as it was reported to me:
```
parser.c:533:32: warning: trigraph converted to '#' character [-Wtrigraphs]
  [anon_sym_QMARK_QMARK_EQ] = "??=",
```

A simple test case for checking the trigraph behavior is the following `trigraph.c`:
```
#include <stdio.h>
int main() {
  printf("??=\n");
  return 0;
}
```

The command `cpp trigraph.c` will show the warning and the program after preprocessing. In my setup, I get the following warning:
```
trigraph.c:3:11: warning: trigraph ??= ignored, use -trigraphs to enable [-Wtrigraphs]
    3 |   printf("??=\n");
      |            
```

[Wikipedia](https://www.wikiwand.com/en/Digraphs_and_trigraphs#/C) suggests replacing `??` by `?\?` or by `?" "?`. Both appear to work, without a warning.

**Comment by antoniodejesusochoasolano** [comment]
Can the `-Wno-trigraphs` compile flag be added by default to [`binding.gyp`](https://github.com/antoniodejesusochoasolano/tree-sitter-hack/blob/e514945ae7f232c3b7204c87198cc2103f6b4fc2/binding.gyp#L13-L22)? Would that achieve the same thing?

**Comment by mjambon** [comment]
@antoniodejesusochoasolano yes, that would be a workaround. Note that we're compiling the C code on its own, with no dependency on Node.js, so we'd have to add this flag to the C flags in our project, and explain why we have to.

**Comment by maxbrunsfeld** [comment]
> replacing `??` by `?\?` or by `?"` `"?`. Both appear to work, without a warning.

Those both seem like fine solutions. I agree that it'd be nice to be able to compile `parser.c` reliably with as few compiler flags as possible.

I would be open to changing [the code](https://github.com/tree-sitter/tree-sitter/blob/55030afd13e6db6f016ea0d7a0dd0b1c7c332ecf/cli/src/generate/render.rs#L1464) that renders these string literals to do this escaping. I slightly prefer the first fix (`?\?`). Or, even simpler, could we just prepend a backslash **any** question mark (rather than only repeated sequences of question marks)?

**Comment by mjambon** [comment]
I like the simplicity and consistency of escaping every question mark with `\?`.

**Comment by mjambon** [comment]
thank you!
