### ISSUE TITLE
"cargo build" fails on master

### ISSUE THREAD

**Issue by bfredl** [tree-sitter/tree-sitter#718]
I get this failure on master, tried both latest stable and nightly rust (or rather a few nights ago):
```
error: couldn't read cli/src/../../lib/binding_web/tree-sitter.js: No such file or directory (os error 2)
  --> cli/src/web_ui.rs:30:17
   |
30 |                 include_bytes!(concat!("../../", $path)).to_vec()
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
43 | posix_resource!(get_lib_js, "lib/binding_web/tree-sitter.js");
   | -------------------------------------------------------------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read cli/src/../../lib/binding_web/tree-sitter.wasm: No such file or directory (os error 2)
  --> cli/src/web_ui.rs:30:17
   |
30 |                 include_bytes!(concat!("../../", $path)).to_vec()
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
44 | posix_resource!(get_lib_wasm, "lib/binding_web/tree-sitter.wasm");
   | ------------------------------------------------------------------ in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

error: could not compile `tree-sitter-cli`.
```

**Comment by patrickt** [comment]
You’ll need to run `script/build-wasm` first.

**Comment by bfredl** [comment]
Thanks, but I suppose you could do a proper error message? it is not obvious that wasm is needed for the cli tool..

**Comment by maxbrunsfeld** [comment]
Just writing down my thoughts on the ideal solution here:

1. In a `build.rs` file for the `cli` target, check for the existence of the wasm binding files `tree-sitter.js` and `tree-sitter.wasm`.
2. If those files are present, set a compile-time variable `TREE_SITTER_EMBED_WASM_BINDING`
3. In `web_ui.rs`, define the `get_lib_js` and `get_lib_wasm` functions in two different ways, dependingo on the value of ☝️ this compile time variable.
    1. If it is set, then embed the file contents via `include_bytes!`, as it is done now on posix systems
    2. If it is *not* set, then return empty vectors, as is already done on windows

There is already logic (which is currently only included on windows) for redirecting to https://tree-sitter.github.io/tree-sitter.wasm in the case where the wasm file is not embedded.

This way, if you build the CLI with a plain `cargo build --release`, it will still work. But the `tree-sitter web-ui` command just won't work without an internet connection.

**Comment by patrickt** [comment]
I’ll take a run at this.

**Comment by maxbrunsfeld** [comment]
Fixed via https://github.com/tree-sitter/tree-sitter/pull/723.
