### ISSUE TITLE
Potential for generating LSPs?

### ISSUE THREAD

**Issue by SirJosh3917** [tree-sitter/tree-sitter#726]
I was wondering if it was feasible for tree-sitter to auto generate LSPs, or auto generate extensions in VS Code so that after writing a grammar, it's usable in modern text editors. Would this be a feasible goal to implement into tree-sitter? Or is the scope of this far too large, and should be delegated to the developer? In the case of the latter, I'd think it might be helpful to include some docs on how to make a LSP and VS Code extensions for a tree-sitter language.

**Comment by Razzeee** [comment]
you can cover some basics with three sitter, but it get's language specific quiet fast after this, if you ask me

**Comment by ralpha** [comment]
Was wondering the same. I also found this https://github.com/bash-lsp/bash-language-server It uses Tree Sitter to create language server info. So maybe this is useful for anyone in the future.

**Comment by maxbrunsfeld** [comment]
I don't think we'll quite get to the point of generating entire language servers, but some day, more code-navigation functionality might be included as part of Tree-sitter.
