### ISSUE TITLE
Custom memory allocation function

### ISSUE THREAD

**Issue by IvanRibakov** [tree-sitter/tree-sitter#739]
I would like to use Tree-sitter in a multi-process application and "cache" parsed Tree in the shared memory to allow multiple child processes to independently walk the tree without the need to repeatedly parse the input.

I had a look at 
- https://docs.rs/tree-sitter/0.16.1/tree_sitter/
- https://github.com/tree-sitter/tree-sitter/blob/master/lib/include/tree_sitter/api.h

but couldn't find any mention of custom allocator functions, only mention of `malloc`.

Does latest Tree-sitter version provide such functionality?

**Comment by ikrima** [comment]
There was a small addition to allow you to ifdef override the allocation. It's runtime wide, not granular but may suffice.
The macros are
```cpp
#define ts_malloc(_sz)      
#define ts_calloc(_cnt,_sz) 
#define ts_realloc(_ptr,_sz)
#define ts_free(_ptr)       
```
