### ISSUE TITLE
Allow `tree-sitter parse` to collect information about error percentages when parsing multiple files

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter#741]
It’s often useful to run `tree-sitter parse -q somedir/** | wc -l` to see how many files in a given directory failed to parse, and then to divide that by the number of total files parsed to get error percentages. Totally doable on a user side, but it would be cool to be able to run `tree-sitter parse --stat somedir/**` or whatnot.

**Comment by sogaiu** [comment]
Enhancing the built-in capabilities of the `parse` subcommand sounds like it might benefit certain Windows setups too.

On a related note, I imagine others have done so as well, but I sometimes use `find` in combination with `xargs`.  For somewhat over 100,000 files, that takes about 1m23s or so here.

Though it's specific for Clojure atm, for a bit more speed, I currently use: https://github.com/sogaiu/a-tsclj-checker (this works recursively and can also look inside `.jar` files).  It currently takes about 24s for the same collection of files.
