### ISSUE TITLE
Unexpected behaviour of ts_node_child_by_field_name

### ISSUE THREAD

**Issue by IvanRibakov** [tree-sitter/tree-sitter#755]
# Given

Tree-sitter grammar - https://gist.github.com/IvanRibakov/d57c1fa129c3681c4d07bc40584c7304

Sample input:
```
// example.txt
if (condition(c1)) {
    action(a1);
} else {
    action(a2);
}
```

```
$ tree-sitter parse example.txt
(source_file [0, 0] - [5, 1]
  (branch_statement [1, 0] - [5, 1]
    condition: (condition_function [1, 4] - [1, 17]
      id: (id [1, 14] - [1, 16]))
    consequence: (block [1, 19] - [3, 1]
      (action_function [2, 4] - [2, 14]
        id: (id [2, 11] - [2, 13])))
    alternative: (block [3, 7] - [5, 1]
      (action_function [4, 4] - [4, 14]
        id: (id [4, 11] - [4, 13])))))
```

# When

Accessing `branch_statement` child by field name `condition`:

```
TSNode conditionNode = ts_node_child_by_field_name(branchNode, "condition", 9);
cout << ts_node_type(conditionNode));
```

# Expected

Expecting to see `condition_function` printed

# Actual

Instead getting `(` printed.

---

Is this a bug or am I doing something wrong? 
Could this be because `ts_node_child_by_field_name` doesn't deal with named node only? If so, it would be really useful to have a "named" flavour of `ts_node_child_by_field_name`.

**Comment by maxbrunsfeld** [comment]
Yes, field names can be associated with both named and anonymous nodes. I think you just need to ensure the field is associated with only one node: either by making `parenthesized_expression` visible, or by moving the field inside of that rule.
