### ISSUE TITLE
Sparql grammar is slow to generate

### ISSUE THREAD

**Issue by BonaBeavis** [tree-sitter/tree-sitter#763]
I am writing a grammar for [sparql](https://github.com/BonaBeavis/tree-sitter-sparql) and generating a parser takes too much time.
How do I now which rules are causing this? 
Can I profile somehow the generate process?

**Comment by stephe-ada-guru** [comment]
BonaBeavis <notifications@github.com> writes:

> I am writing a grammar for
> [sparql](https://github.com/BonaBeavis/tree-sitter-sparql) and
> generating a parser takes too much time.
> How do I now which rules are causing this?
> Can I profile somehow the generate process?

I can't help with these questions, but you might try WisiToken
(https://stephe-leake.org/ada/wisitoken.html); it handles large grammars
better.

--
-- Stephe

**Comment by BonaBeavis** [comment]
Found the underlying issue #778.
