### ISSUE TITLE
field not generated?

### ISSUE THREAD

**Issue by panlina** [tree-sitter/tree-sitter#767]
I have this:
```
module.exports = grammar({
	name: 'a',
	rules: {
		a: $ => seq(
			field('a', 'a'),
			field('b', 'b')
		)
	}
});
```
but when I `tree-sitter parse` `ab`, I get `(a [0, 0] - [0, 2])`, no field generated.
Why is this?

**Comment by sogaiu** [comment]
Not sure if this is the case here, but I think I've seen cases where the field does not show up in the s-expression output but can be confirmed to exist programmatically.

I failed to determine whethere "no field generated" is part of the output above -- I don't recall having seen that before though.

**Comment by alemuller** [comment]
I think this is the expected behavior for anonymous nodes.

The expression on [tree-sitter/tree-sitter-c](https://github.com/tree-sitter/tree-sitter-c) have a "operator" field that doesn't show on with `parse` but can be matched with queries.

**Comment by panlina** [comment]
@sogaiu I confirmed what you said. "no field generated" is my description, not its output. Thanks.

**Comment by panlina** [comment]
@alemuller OK. Thanks.
