### ISSUE TITLE
Testing strategies for tree-sitter queries

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter#770]
Right now we’re testing all queries by hand; @tclem points out that this isn’t a great state of affairs, and I agree. We should figure out some sort of fixture syntax that we can run with `tree-sitter query-test` or some sort of Makefile shenanigans.

**Comment by Razzeee** [comment]
Not sure about queries, but I would really like something like this for tags
https://github.com/elm-tooling/elm-language-server/blob/master/test/definitionProviderTests/importDefinition.test.ts#L20

We lifted this from the elm-intelliJ plugin and they were inspired by the rust language server I think?

**Comment by amaanq** [comment]
This seems like it was filed before queries were actually analyzed in the core library, and as such `tree-sitter test` actually lets us know if a query file is valid or not now, so I'll close this out.
