### ISSUE TITLE
Document dot operator in queries

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter#771]
The `.` operator in queries can be used to capture the first occurrence of a node in a sequence, or the last, or two side-by-side occurrences. This is useful and thus far undocumented.

**Comment by alemuller** [comment]
@patrickt could you provide an example? Documenting here is better than no documentation at all.

**Comment by theHamsta** [comment]
@alemuller see https://github.com/tree-sitter/tree-sitter/pull/549

**Comment by maxbrunsfeld** [comment]
This was fixed in https://github.com/tree-sitter/tree-sitter/pull/779.
