### ISSUE TITLE
How to get the field name of the tokens when parsing java using python interface?

### ISSUE THREAD

**Issue by yuanyehome** [tree-sitter/tree-sitter#773]
When I'm using python interface to parse a java code, I've found that `root_node.is_named` is `True` but `root_node.walk().current_field_name()` returns `None`. Was I using it in a wrong way?

Example java code:
```java
public void class {
    public void testRole(String[] args, int x) {
        for (String arg : args) {
            System.out.println(arg);
        }
        for (int i = 0; i < args.length(); ++i) {
            System.out.println(args[i]);
        }
        int z = 0;
        while (z > 0) {
            System.out.println(args[z]);
            z++;
        }
        for (int i = 0, j = 0; i < 100 && j < 100; ++i, ++j) {
            System.out.println(i + j);
        }
        List<Integer> numbers = Arrays.asList(1, 2, 34, 56);
        Integer[] filtered = numbers.stream().filter(p -> p > 4).toArray(Integer[]::new);
        System.out.println(filtered[0]);
        return;
    }
}
```
And I have executed the scripts below:
```python
Language.build_library(
    'build/languages.so',
    ['tree-sitter-java']
)
JAVA_LANGUAGE = Language('build/languages.so', 'java')
parser = Parser()
parser.set_language(JAVA_LANGUAGE)
tree = parser.parse(wrap(example_func))
root_node = tree.root_node
```

In jupyter, I have founded that
![image](https://user-images.githubusercontent.com/36473484/96696125-00513200-13bd-11eb-8af0-cad3cd3feb85.png)

So how to get the filed name of each node in python interface?

**Comment by yuanyehome** [comment]
I have realized that perhaps I should ask in py-tree-sitter repo. Sorry for bothering.

**Comment by sogaiu** [comment]
@yuanyehome FWIW, `is_named` indicates whether a node is [named or anonymous](https://tree-sitter.github.io/tree-sitter/using-parsers#named-vs-anonymous-nodes).  IIUC, that is a separate thing from whether the node has a [field name](https://tree-sitter.github.io/tree-sitter/using-parsers#node-field-names).
