### ISSUE TITLE
Unable to match anonymous node `"`

### ISSUE THREAD

**Issue by stsewd** [tree-sitter/tree-sitter#776]
I'm unable to match this node

https://github.com/tree-sitter/tree-sitter-python/blob/71bdaf651bb7cb844dce8f974819681eeb36cfe0/grammar.js#L827-L831

I have tried `""""` `"""` `'"'` `"\""`, those queries error or don't match. When changing the name of the node in the grammar itself to `'` I'm able to match it (`"'"`). I'm not sure if this is a bug or there is another way to escape the `"` symbol.

**Comment by maxbrunsfeld** [comment]
Thanks for the report! This is fixed on the master branch.
