### ISSUE TITLE
Create a gitter and/or reddit sub

### ISSUE THREAD

**Issue by alemuller** [tree-sitter/tree-sitter#788]
I had some time consuming issues writing a tree-sitter grammar that could be averted with some guidance from people who already wrote or is writing a ts grammar. Also, I found a couple of bugs on a large grammar that I struggled to write a MWE, someone with a stronger knowledge on compiler theory probably could replicate the without 3k lines of code.

I usually ask my questions on nvim-treesitter gitter, but haven't had much luck so far.

**Comment by sogaiu** [comment]
@alemuller It's not a chat-based thing, but have you seen: https://github.com/tree-sitter/tree-sitter/discussions ?

**Comment by alemuller** [comment]
@sogaiu  I haven't. Thanks for pointing it out.

**Comment by maxbrunsfeld** [comment]
I'm going to close this out because we want to try to use the GitHub discussions. If you have feedback on the Discussion forum itself, maybe start another discussion thread. We're open to ideas about how to improve the communication.
