### ISSUE TITLE
Last-named-child operator not always working working

### ISSUE THREAD

**Issue by theHamsta** [tree-sitter/tree-sitter#806]
Please excuses in advance. I'm not sure whether what I experienced is actually a bug or I just don't understand fully how queries work.

I'm having problem matching the last named child. It does not seem to work in all occasions (test with last master November 16 and tree-sitter webplayground).

I can match `c=3;` using the "." last child operator (using the neovim bindings)
```c
void main() { a = 0; b = 2; c = 3; }
```
With this query (without the `.` three matches for the three statements).
```
(compound_statement (_)  @end .)
```
But not when I specify another node (does not matter which one, could also be an existing concrete node  instead of a wild card)
```
(compound_statement (_) (_)  @end .)
```
On the web playground I can't match it with either of the variants.

In Lua (https://github.com/nvim-treesitter/tree-sitter-lua), I can match the  last statement of a function using the dot operator.

```lua
function()
  if not valid_args("nth?", pred, 2, true) then return end

  local node = match[pred[2]]
  local n = pred[3]
  if node and node:parent() and node:parent():named_child_count() > n then
    return node:parent():named_child(n) == node
  end

  return false
end)
```

```
(function_definition 
 (_) @parameter.outer .)
```
matches `return false`. But not this query

```
(function_definition .
  (_)
 (_) @parameter.outer .)
```
or this one
```
(function_definition 
 (_) ; or any other node spec
 (_) @parameter.outer .)
```

Same applies for Python
```
def foo():
    a = 1
    b = 2
    c = 3
```

```
(block (_)  (_) @end . )
```

This would only match the second `b=2` but not the last?
```
(block (_)  . (_) @end )
```

We would like to match the first and last node of a `compound_statement` C/C++
```
(compound_statement . (_) @start (_)  @end .)
```

**Comment by maxbrunsfeld** [comment]
Thanks for the report! Very helpful. The new library is uploaded to the web playground.
