### ISSUE TITLE
[tracking] Bugs found with -fsanitize=memory

### ISSUE THREAD

**Issue by philipturnbull** [tree-sitter/tree-sitter#81]
Tracking issue for crashes found with oss-fuzz, using libFuzzer and `-fsanitize=memory`. The bugs are found by fuzzing different languages but the crashes are typically in the core `tree-sitter` runtime.

`tree-sitter-javascript`:

| fixed in issue # | Type | halt_on_error? | minimized base64 reproducer |
|---|:---|:---:|:---|
| #101 | timeout | no | `bGVha2NyX292ZXI8PDw8azy8PHMPPDoyMHV1dXV1bm59bm5+fn5SfmVijX5+fn5+fn5+djItLS0tLS0tLS0tLT09PT09Njf5LWVl` |
| #101 | crash | no | `Nm4KOzQoZCE0` |
| #101 | crash | no | `On19fX0zNy0tLS0tLS0tLS0tLTMtLS0tLS0tLS0tLS0t` |
| #101 | crash | no | `fXt7e3t7D319fX04fWY=` |
| #101 | crash | no | `aChf//////+VaJWVlZWVaGxoKF9oymhoIWhoaGg7aGiVYjc0Mls3NDJkMzA0MtE3NWI0MCBlMTAyOTh9MjKVlZU3LTKVLDQyNjU3MjFmlWKhaGhoaGg7aGhoaApobCkoX2ho6WhoIWhoaGg7aGiVYjc0Mls3NDJkMzA0MtE3NWI0MAoKMjYKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoK` |
| #101 | crash | no | `Yjc2OWI0ZbNmYWRhNjMyOTFjMzRidGoKbDJrbWVudWVucilpbWVudWV4cGWqaXJpO7CwsLCwsLAzsP9v////eHBlcmk/ZWopAmJzeHBlZfhwZXJpP2VudApqb2JzcmltZW51bnQKamV4ZWpvYnN4//////////////9pO5uRiztyZX5+fn5+fn5+fn5yaT9lZQ==` |

`tree-sitter-ruby`:

| fixed in issue # | Type | halt_on_error? | minimized base64 reproducer |
|---|:---|:---:|:---|
| #101 | crash | yes | `JCQkJCQkJCQkMjEze2U6ZjYkN2U6NGYNDQ04` `CmQKZWMoZTU6dChzITRkCjgA` `KCQ2ZDk6MGYwMDs1YzJmM2I7YjQhZDM1OmYyOTZhYik` `XyhfO18yKDY5Ywox` |
| #101 | timeout | yes | `IWNbOyF0CX50PXI/dD1yP3RjfnR0Zml4PXI/dHR0PTI1LT8/LT8/Pz8/` `djghZTg6NHQ9IT9pbSFlcyF1IXYsbSFtIXQ9MjUsIXUhdixtIXQ9MjUsLCE=` |

/cc @maxbrunsfeld

**Comment by amaanq** [comment]
This is quite old and not actively maintained, while it is a cool list I think it can be closed
