### ISSUE TITLE
Incorrect build setup

### ISSUE THREAD

**Issue by maisiliym** [tree-sitter/tree-sitter#810]
When using a correct build system (ie *not* cargo, the worst thing that happend to rust), crates are fetched individually, therefore, all the ducktaped-and-haywired build scripts and assets become unavailable in one way or another. Li can help, but hard choices have to be made. Li suggests keeping the assets separate since multiple crates need them(to avoid keeping multiple copies), leveraging build.rs, and passing the asset's paths to the build as env-vars. Nix/guix veterans are invited to chip in.

**Comment by maxbrunsfeld** [comment]
Can you share the specific problem that you're experiencing? In other words, which crate are you building, what tools and commands are you using to build it, and what error are you seeing?

**Comment by li-maisiliym-uniks** [comment]
The main problem is the wasm object which is built at build-time using assets which are not available in every crate. The correct way to do dependencies is to build them, like any other dependencies, and *then* pass them to the build which requires it. Perhaps this wasm object deserves its own crate?
