### ISSUE TITLE
Allow creating a `Language` from dynamically loaded parsers

### ISSUE THREAD

**Issue by osa1** [tree-sitter/tree-sitter#813]
I scanned the API and as far as I can see currently it's not possible to create a `Language` from a dynamically loaded (from `.so`) parser library. It would be good if I could do something like:

```rust
let parser_lib = unsafe { libc::dlopen(so_file_path, ...) };
let parser_sym = unsafe { libc::dlsym(parser_lib, "tree_sitter_my_lang") };
let parser = tree_sitter::Parser::from_dynamic_lib(parser_sym);
```

As far as I can see this is currently not possible to do.

**Comment by maxbrunsfeld** [comment]
Here is the current code in the CLI codebase that does this, using the `libloading` crate to load shared libraries in a cross-platform way:

https://github.com/tree-sitter/tree-sitter/blob/b5d2aa7102f6f9dcfaa8f6b58eb642a49c9a9546/cli/src/loader.rs#L349-L361

It actually doesn't require any Tree-sitter specific APIs, since Tree-sitter doesn't care where the `Language` object comes from.

**Comment by osa1** [comment]
Thanks. I was considering doing something like that, but `Language` is an opaque type (field type is not exposed) so I wasn't sure how to initialize it with the pointer I got from a parser compiled to `.so`. Your code does exactly that. It would still be good to have a function for this in the library (maybe `Library::load_from_shared_lib`) but no big deal.

**Comment by maxbrunsfeld** [comment]
It appears in the README, phrased like this:

> To then use languages from rust, you must declare them as extern "C" functions and invoke them with unsafe. Then you can assign them to the parser.
>
>    ```rust
>    extern "C" { fn tree_sitter_c() -> Language; }
>    extern "C" { fn tree_sitter_rust() -> Language; }
>    extern "C" { fn tree_sitter_javascript() -> Language; }
>
>    let language = unsafe { tree_sitter_rust() };
>    parser.set_language(language).unwrap();
>    ```

But it's not explicitly explained. Where do you think the explanation should live? Maybe in a doc comment on the `Language` type?

**Comment by amaanq** [comment]
I think the ergonomics for this have been improved, as we now use a [`LanguageFn`](https://docs.rs/tree-sitter-language/*/tree_sitter_language/struct.LanguageFn.html
) to avoid issues with mismatched core library versions in the language crate and the core library, and it's really easy to [create a `LanguageFn` from a raw pointer](https://docs.rs/tree-sitter-language/latest/tree_sitter_language/struct.LanguageFn.html#method.from_raw), so I'll close this out
