### ISSUE TITLE
add tree-sitter-parser-common as base package for parsers

### ISSUE THREAD

**Issue by milahu** [tree-sitter/tree-sitter#821]
im fixing some general stuff in tree-sitter-html
and would like to push these fixes to other parsers

i could not find a ready-made solution
so here is my (slightly verbose) brainstorm

possible solution:

create a package tree-sitter-parser-common
with all the common files like scripts, configs ..

the actual parsers
include parser-common as dependency

its like a "self-updating template", or an "auto-rebasing fork" which means
the parser-common's post-install script
will copy-or-replace config files to the project root, like .travis.yml
except user-created files exist
(user files do not have a special header like auto-generated files)
or except the files are set to "ignore" in package.json
like `"config": {"tree-sitter-parser-common": {"ignore-files": [".travis.yml"]}}`
challenge: dynamically merge base and fork files with the same file path

also .gitignore is kept in sync
to ignore any auto-generated/post-installed files

also parts of package.json can be patched this way

.gitignore and package.json
are the only files who are commited to the fork repos
= the only redundant files across forks

goal:
automatically propagate changes to all parsers
make "parallel maintenance" much easier
keep forks in sync without using github forks
avoid redundant commits across many git repos

alternative solutions:
move all parsers to one monorepo - con: drastic change
https://github.com/koj-co/update-template
https://github.com/mateodelnorte/meta
or find some way to auto-rebase forks to upstream
downside: redundant commits

**Comment by maxbrunsfeld** [comment]
I don't think there's enough duplication to make this kind of complexity worthwhile. The only duplication is the `.gitignore`, the CI config files like `appveyor.yml`, and some keys of the the `package.json`, right? These are all pretty simple files, and it's pretty normal in open source for many repos to have similar content in these files. IMO, there's no need to build some custom inheritance mechanism to avoid remove this duplication.

**Comment by milahu** [comment]
> to avoid this duplication

the goal is rather to keep these files up-to-date

another downside: more NPM dependencies

alternative:
maintain a tree-sitter-parser-template
to show 'best practices' for parser packages

in that case, the inheritance would work manually
pro: less need to trust the template maintainers
con: more work for parser maintainers

**Comment by ahlinc** [comment]
A partial solution for this would be provided by #2438, details in a comment: https://github.com/tree-sitter/tree-sitter/pull/2438#issuecomment-1679820893

> goal:
> automatically propagate changes to all parsers

I think only Tree-sitter's CLI can be a real origin of propagation of changes to parser repos.

**Comment by amaanq** [comment]
This can be closed out, as there's the template [here](https://github.com/tree-sitter-grammars/template) as well as an `init` command for setting up all the bindings/manifest files.
