### ISSUE TITLE
replace the abandoned difference library

### ISSUE THREAD

**Issue by milahu** [tree-sitter/tree-sitter#823]
low priority

the difference library is used in cli/src/test.rs

seems [abandoned](https://github.com/johannhof/difference.rs/issues/45) for 3 years now
there is at least [one bug](https://github.com/johannhof/difference.rs/issues/47)
is using some LCS algorithm - could be [better](https://github.com/johannhof/difference.rs/issues/46)

some [alternatives](https://crates.io/keywords/diff) with recent updates

* https://crates.io/crates/dissimilar  
Myers' diff algorithm
201,898 Downloads  
27.9 kB crate size
* https://crates.io/crates/treediff  
tree differ  
201,898 Downloads
* https://crates.io/crates/diffus  
Longest Common Subsequence (LCS) algorithm  
27,346 Downloads  
6.66 kB crate size
* https://crates.io/crates/diffs ([source](https://nest.pijul.com/pijul/pijul:main/SXEYMYF7P4RZM.Y45AY))  
multiple algos (myers, patience ("tends to give more human-readable outputs"))  
low level ([sample use](https://docs.rs/crate/diff-rs/0.2.3/source/src/lib.rs))  
6,183 Downloads  
5.24 kB crate size
* https://crates.io/crates/differ  
1,459 Downloads
* https://crates.io/crates/line_diff  
914 Downloads

here is a summary with more algos
https://github.com/Wilfred/difftastic

small bundle size would be nice

performance: histogram > myers >> patience ([source](https://stackoverflow.com/questions/32365271/whats-the-difference-between-git-diff-patience-and-git-diff-histogram))

**Comment by dundargoc** [comment]
Are you dependabot?

**Comment by dundargoc** [comment]
This reads like a dependabot report or something. Is there an actual problem with the current diff implementation that affects *your* usage of tree-sitter?

**Comment by milahu** [comment]
> Is there an actual problem with the current diff implementation that affects _your_ usage of tree-sitter?

i dont remember

i guess it produced some weird/ugly diffs, but no wrong diffs

**Comment by amaanq** [comment]
Replaced with similar
