### ISSUE TITLE
New --update flag does not converge on all cases

### ISSUE THREAD

**Issue by leostera** [tree-sitter/tree-sitter#835]
`tree-sitter test -u` does not update the corpus correctly when it finds outputs including quotes. Example:

```clojure
(source_file (expression (function_call (computed_function_name (atom (unquoted_atom)))))
  (ERROR (ERROR (UNEXPECTED ' ')) (atom (unquoted_atom)))) 
```

Running `tree-sitter test -u` several times detects the corpus as out of date, and updates incorrectly. So there should be a small bug somewhere in the corpus update code (possibly some character escaping that's gone rogue? Need to have a look)

Reporting here in case anyone else finds it.

Ref: #828 #442

**Comment by maxbrunsfeld** [comment]
Thanks for catching this @ostera.
