### ISSUE TITLE
Timing how long parsing/highlighting takes, like playground does?

### ISSUE THREAD

**Issue by jasonhan-vassar** [tree-sitter/tree-sitter#839]
Hi, is it possible to benchmark tree-sitter and record the time (in ms) it takes to perform actions like parsing or highlighting a file? This seems to be done in the [playground](https://tree-sitter.github.io/tree-sitter/playground) already, is this a built-in feature or is something external timing it? Thanks!

**Comment by sogaiu** [comment]
For parsing, do you mean something different from the following?
```
npx tree-sitter parse --time <your-favorite-file>
```

**Comment by jasonhan-vassar** [comment]
Nope, `—time` was exactly what I was looking for. I didn't realize I had to use `tree-sitter help` for additional flags of each subcommand. Thank you!

**Comment by sogaiu** [comment]
@jasonhan-vassar No problem.

I didn't know that `highlight` also had a `--time` flag, so I learned something :)
