### ISSUE TITLE
Hex colors are unsupported in theme when using CLI tool

### ISSUE THREAD

**Issue by jason5122** [tree-sitter/tree-sitter#841]
Hi, I get the "Unsupported color type" error when I use a hex color (e.g., "#e45649" as specified right in the [theme documentation](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#theme)). This is with the Rust CLI tool. Is this intentional? I believe another user experienced this in #758 and it seems they're also using the CLI tool.

The full error is `thread 'main' panicked at 'Unsupported color type', cli/src/highlight.rs:272:14
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace`.

**Comment by alemuller** [comment]
Duplicated #758
