### ISSUE TITLE
Fields of NewRegex

### ISSUE THREAD

**Issue by alemuller** [tree-sitter/tree-sitter#848]
Trying to query a field of RexExp causes an error:

`grammar.js`:
``` grammar.js
module.exports = grammar({
    name: 'test',

    rules: {

        top: $ => repeat1(seq('assert', $.expr, ';')),

        expr: $ => seq(
            field('left',$.number),
            field('operator',seq(new RegExp('and|or'))),
            field('right',$.number),
        ),

        number: $ => new RegExp('[0-9]+'),

    },
})
```
`queries/highlights.scm`:
``` queries/highlights.scm
(expr
  operator: _ @error)
```
Command line:
```
$ tree-sitter highlight file.test
Query error at highlights.scm:2. Impossible pattern:
  operator: _ @error)
  ^
```

Same error happens with:
``` js
field('operator',seq(new RegExp('and|or'))),
```
and:
```js
field('operator',token(new RegExp('and|or'))),
```
---

The query works when RegExp is aliased:
``` js
field('operator',alias(new RegExp('and|or'), "")),
```

But it does *not* work creating a new rule:
``` js
field('operator',$._op),
// ...
_op: $ => new RegExp('and|or'),
```

**Comment by maxbrunsfeld** [comment]
Regexes are treated as hidden nodes. If you want it to appear in the tree, you’ll need to give it a name that does not begin with underscore, or alias it.

**Comment by alemuller** [comment]
I don't want them to appear on the tree produced by parse, but I want to be able to target them on highlight scheme. 

Aliasing them to a string works but it kinda hacky.

Feel free to move this to discussion (since it is an expected behavior).

**Comment by maxbrunsfeld** [comment]
Yeah, I see what you mean. You would want regexes to behave just like strings, rather than being made hidden. That does make sense. The only reason they are hidden now is that it wasn’t clear to me what to return as the node’s “type”. I guess we could return the regex itself. That seemed a bit unintuitive to me, but you may be right that it would ultimately be more useful.

I’m not sure if there would be any problems with changing this behavior. Some grammar authors might be surprised by the change.

**Comment by alemuller** [comment]
I can see your reasoning (returning `assertion_statement_token2` or a long regex don't seem ideal). The documentation could suggest using fields to address them, instead of the token name, when possible. Or to use aliases when they can be referenced by names, such in the cases insensitive keywords.

By the way, tangent to this topic, I'd suggest updating the snippet you originally posted on #122 to include an alias to the keyword. This is something that I imagine most people describing a case insensitive language has to deal with it when writing the highlight scheme.
