### ISSUE TITLE
Is there a similar api in C to Node node.text?

### ISSUE THREAD

**Issue by marcel0ll** [tree-sitter/tree-sitter#849]
Is there a similar API to get a node text?

Something like `char * ts_node_text(TSNode)` ?

Looking at the implementation of the [node bindings](https://github.com/tree-sitter/tree-sitter/blob/5008700735be65bb81cf3de5b292708778c3562a/lib/binding_web/binding.js#L1020) I see that node.text calls getText that takes tree, startIndex, endIndex and somehow returns the text.

I believe one would use ts_node_start_byte and ts_node_end_byte to get the text from the tree, but I am not sure where to find the source code inside the tree or how I would convert from byte to char index.

**Comment by patrickt** [comment]
The accepted way to do this is by retaining the source code that you fed into the parser function, and then slicing/copying the associated text out of your original source code. (At least, this is [the way we do it](https://github.com/github/semantic/blob/a44e3c40cc120b8efccb4908e3142482ea46577f/semantic-ast/src/AST/Unmarshal.hs#L175-L178) in Semantic). I believe the reason for this (I think) is to avoid overhead within the tree and the memory/time consumption/careful thinking about sharing required to slice text out of the original source code, especially given that many applications will not need to retain the original text.

**Comment by marcel0ll** [comment]
I see.
What is the reasoning behind providing this as a node API?

**Comment by patrickt** [comment]
The fact that JS is GC’d and has closures allows the `textCallback` callbacks within the tree to refer to the original source code associated with the context in which it was defined, so it doesn’t entail any additional costs or memory management complexity to refer to the original source text if needed (and leave the details of string slicing and deallocation up to JS’s string classes). Such is not the case for the fast path, which needs to be cross-platform C (so even the variants of C that support similar capturing).

**Comment by patrickt** [comment]
I think the Python bindings provide a similar API.
