### ISSUE TITLE
error while processing nvim-treesitter.vim after update 

### ISSUE THREAD

**Issue by siduck76** [tree-sitter/tree-sitter#855]
I updated all the plugins yesterday and today I get this error : 

![image](https://user-images.githubusercontent.com/59060246/102702945-9525be00-428e-11eb-89d1-30a04aedfdcc.png)

**Comment by theHamsta** [comment]
You have to update your nightly Neovim (this function is missing in your old function).

Please don't post Vim issues to the tree-sitter repo!

**Comment by siduck76** [comment]
oh , that fixed it !
