### ISSUE TITLE
A syntax to keep extras from matching?

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#861]
I'm trying to parse this, it's just a multiline string and shouldn't include a comment.

```js
string5 =
        """
        {- block comment -}

        """
```

But it matches as:
```
(file [0, 0] - [4, 11]
  (value_declaration [0, 0] - [4, 11]
    functionDeclarationLeft: (function_declaration_left [0, 0] - [0, 7]
      (lower_case_identifier [0, 0] - [0, 7]))
    (eq [0, 8] - [0, 9])
    body: (string_constant_expr [1, 8] - [4, 11]
      (block_comment [2, 8] - [2, 27]))))
```

Here is my string_constant_expr definition (only the first choice should matter):

```js
    string_constant_expr: ($) =>
      choice(
        seq(
          '"""',
          repeat(
            choice(
              token.immediate(
                prec(PREC.STRING, choice(/[^\\"]/, /"[^"]/, /""[^"]/))
              ),
              $.string_escape,
              $.invalid_string_escape
            )
          ),
          '"""'
        ),
        seq(
          '"',
          repeat(
            choice(
              token.immediate(prec(PREC.STRING, /[^\\"\n]/)),
              $.string_escape,
              $.invalid_string_escape
            )
          ),
          '"'
        )
      ),
```

I do have these extras:

```js
  extras: ($) => [
    $.block_comment,
    $.line_comment,
    /[\s\uFEFF\u2060\u200B]|\\\r?\n/,
  ],
```

For some reason block_comment is able to get between the tokens, it's also an external rule, if that matters.

So what am I missing? Do we need new syntax or context for the scanner?

**Comment by maxbrunsfeld** [comment]
Since `block_comment` is external, you need to add logic to your external scanner so that it will not match block comments when one of those string content rules is valid. For example, you could add `string_escape` to your list of `externals`, and then check its validity in your external scanner:

grammar:

```js
externals: $ => [
  // ...
  $.block_comment,
  $.string_escape,
],
```

scanner:

```c
enum Token {
  // ...
  BLOCK_COMMENT,
  STRING_ESCAPE,
}

// ...

bool tree_sitter_my_language_external_scanner_scan(
  void *payload,
  TSLexer *lexer,
  const bool *valid_symbols
) {
  if (
    valid_symbols[BLOCK_COMMENT] &&
    !valid_symbols[STRING_ESCAPE] // don't allow block comments inside of strings
  ) {
    scan_block_comment(lexer);
  }
}


```

**Comment by Razzeee** [comment]
That's what I'm trying to get away from, as it turned out to make the scanner way more complex (I might be able to not parse the string in the scanner) https://github.com/Razzeee/tree-sitter-elm/blob/master/src/scanner.cc#L432

Looking at my parser over christmas really showed me how close it is to being perfect, yet it seems to just need one comment (extra) somewhere inbetween to cause everything to collapse. As there are for example some rules in the scanner, that look for the next token, but now they find the extra instead of the correct next token.

**Comment by maxbrunsfeld** [comment]
Just to clarify - there’s no need to parse the string escape in the external scanner. You don’t need to do anything else with string escapes; just check that they aren’t valid before matching a block comment.

**Comment by Razzeee** [comment]
but your code above isn't complete is it? `string_escape` still needs to show up somewhere else in the grammar?

**Comment by maxbrunsfeld** [comment]
You can leave the definition of `string_escape`, and all other usages of it, exactly as they are. You just need to add it to the `externals` list so that your external scanner can *check* whether it is currently valid or not.

**Comment by Razzeee** [comment]
Thanks, works and I've now understood what you've come up with 👍🏻 

However, I'm having a follow up problem, will investigate and maybe create another issue/discussion down the line.

**Comment by maxbrunsfeld** [comment]
No problem, glad that it is working. Also, let me know if you think there's a documentation change that would have helped make this less confusing.

**Comment by Razzeee** [comment]
Yeah, I'm not sure what get's priorized when. I can write a grammar rule and have it implemented in the external scanner, I guess the external scraper will win in that case. But I guess an error would have been better, as it's pretty unintuitive and probably not meant to happen? Then again, it might keep a fix like the one we did from working as we probably can't detect if a certain symbol has a happy path in the scanner.

To clarify, this commented in:
https://github.com/Razzeee/tree-sitter-elm/pull/71/files#diff-919ac210accac9ecc55a76d10a7590e3d85ca3f0e165b52d30f08faee486d0cbR51
While also parsing it via:
https://github.com/Razzeee/tree-sitter-elm/pull/71/files#diff-9909dee3c193cae2049a1f7e4f11165e21678149a9e9848f019144987614b7d4R20

**Comment by maxbrunsfeld** [comment]
This is an intentional behavior, in order to make this kind of behavior possible. To me it makes sense, but I haven’t explicit given an example in the docs.
