### ISSUE TITLE
Support for emacs org mode?

### ISSUE THREAD

**Issue by sucrecacao** [tree-sitter/tree-sitter#864]
Emacs org mode is a great way to organize text file, but is only available for emacs editor.

Being able to parse org mode file with tree sitter would help making org mode plugins in other editors

**Comment by maxbrunsfeld** [comment]
A while back, @patrickt started work on a parser for org mode: https://github.com/patrickt/tree-sitter-org. I don't think it's done yet, but it's worth contributing to it if you're interested.
