### ISSUE TITLE
Does tree-sitter support code-doc nodes?

### ISSUE THREAD

**Issue by josteink** [tree-sitter/tree-sitter#868]
I've searched around for similar issues, and also searched in what I thought would be the most obvious places.

That said, I can't seem to find any mention of the concept of inline code-doc in the existing tree-sitter docs, nor implementations.

For instance, both these examples (C# and TypeScript) only shows the nodes as "comment" not as code-doc:

C#
````c#
public class DemoClass
{
    /// <summary>
    /// A class to do stuff with
    /// </summary>
    /// <param name="value">Some doc</param>
    public void DemoMethod(string value)
    {
    }
````

TypeScript:
````typescript
export class DemoClass {
    /**
     * Example-class for issue-purposes
     * @param value Does stuff with thing
     */
    demoMethod(value: string) {

````

Are simply these language-implementations incomplete wrt full tree-sitter support, or is it tree-sitter itself which does not have a concept of code-doc?

**Comment by patrickt** [comment]
Whether or not a grammar recognizes and distinguishes docstrings of this sort is up to the grammar itself. Tree-sitter has no concept of what is or isn’t a comment (beyond the `extras` field that is often used to ignore parsed comments, but which is not mandatory to use). The above bug would be best submitted to the https://github.com/tree-sitter/tree-sitter-c-sharp repo.

**Comment by josteink** [comment]
Thanks for the feedback. It seems there's [already an issue registered for it](https://github.com/tree-sitter/tree-sitter-c-sharp/issues/18), but no work done so far.

Aaand I guess that answers my question, in full, so indeed lets close this issue :smile:

**Comment by maxbrunsfeld** [comment]
The approach we use, at least for JavaScript/typescript, is to handle the JSDoc in a separate pass, using the tree-sitter-jsdoc parser.

We do this because jsdoc is not really part of the JS language. JS projects are free to use other documentation formats. So we don’t want to bake it into the parser. But for the purpose of syntax highlighting, we do want to respect the convention of highlighting the documentation.
