### ISSUE TITLE
Failed to load grammar package

### ISSUE THREAD

**Issue by ganezdragon** [tree-sitter/tree-sitter#869]
Hi, I'm working on a tree-sitter for perl, and I'm trying to load it in my nodejs vs code client code. And it's throwing me the following error
```
Error: The module '<PATH_TO_MY_PROJECT>/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 85. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.<anonymous> (internal/modules/cjs/loader.js:1081:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at internal/modules/cjs/loader.js:774:14
    at Function._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ganez/Documents/working/projects/perl-language-server/server/node_modules/tree-sitter/index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
[Error - 8:40:25 pm] Connection to server got closed. Server will not be restarted.
```
the tree-sitter-perl code - https://github.com/ganezdragon/tree-sitter-perl
the vs code client code - https://github.com/ganezdragon/perl-language-server

I tried the `electron-rebuild` mentioned here - https://github.com/tree-sitter/tree-sitter/issues/143, but it doesn't seem to be working.

Could you guys help me out here?

**My vscode info:**
```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-59-generic snap
```

**Comment by sogaiu** [comment]
Would you mind sharing the precise steps attempted?

Though not for tree-sitter, I have followed a similar series of steps before with some success: https://gist.github.com/sogaiu/d14a12502aacaede16b0db90e5dca1bb -- it seemed important there to have a specific version of Electron, which according to the VSCode output you provided appears to be 9.3.5.

From one of the links posted, one can reach: https://github.com/onmyway133/blog/issues/69 -- this has a more detailed explanation including some significant bits about ferreting out necessary versions of things.

**Comment by maxbrunsfeld** [comment]
This error isn't specific to Tree-sitter, it has to do with using any native module with multiple different versions of Node.js. Electron-rebuild should do the trick. See the docs for that tool, and for Electron.
