### ISSUE TITLE
Issue with last child operator

### ISSUE THREAD

**Issue by muhmud** [tree-sitter/tree-sitter#872]
Code: 
```
import static java.util.UUID.randomUUID;
```
Query:
```
(import_declaration) @import ((identifier) @static .)
```
What I want is to match `import static` so that I can use it in a predicate. If it contains `static` then `randomUUID` should be coloured. I figure I could use this with locals to get formatting for Java static imports.

I messed with it in the playground, but if I have `@import` in there, `@static` won't match `randomUUID`.

**Comment by maxbrunsfeld** [comment]
This seems to work in the playground today:

```
(import_declaration
  "static"
  (scoped_identifier
    name: (identifier) @name))
```

I don't think you need the last child operator, because of the way that the `scoped_identifier` nodes are nested. I'm going to close this one out, but let me know if you think you're seeing bugs.
