### ISSUE TITLE
Issue with web-tree-sitter@0.18.0

### ISSUE THREAD

**Issue by char0n** [tree-sitter/tree-sitter#873]
With this version of web-tree-sitter I'm not able to use any grammar. I've build the grammar first with latest tree-sitter-cli@0.17.3 and try to load the grammar via web-tree-sitter. But always getting the same issue:

Code to reproduce:
```html
<html>
    <head>
        <script src="https://unpkg.com/web-tree-sitter@0.18.0/tree-sitter.js"></script>
        <script>
            (async () => {
                const Parser = window.TreeSitter;
                await Parser.init();
                const JavaScript = await Parser.Language.load('http://127.0.0.1:3001/tree-sitter-json.wasm');
                parser.setLanguage(JavaScript);
            })();
        </script>
    </head>
    <body>test</body>
</html>
```

```
scratch.html:10 Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #4 module="env" function="table" error: table import requires a WebAssembly.Table
async function (async)
(anonymous) @ scratch.html:7
(anonymous) @ scratch.html:10
```

**Comment by Razzeee** [comment]
I don't think the correct cli for that was released, been holding back
updating for that reason. You can use the previous one fine, I think it's
0.17.1

**Comment by char0n** [comment]
@Razzeee yep, that's what I did, used 0.17.1 for now, as it was the latest one working.

**Comment by Razzeee** [comment]
Has been pushed now, but I'm seeing problems with node 10 https://github.com/elm-tooling/elm-language-server/runs/1675204085?check_suite_focus=true

Tree sitter really needs a changelog :/

**Comment by char0n** [comment]
You mean using web-tree-sitter in node.js env?

**Comment by Razzeee** [comment]
Yes, revisiting your error, it seems similar to some degree:
```
TypeError: WebAssembly.Global is not a constructor
```

**Comment by maxbrunsfeld** [comment]
I have upgraded to a recent version of Emscripten, whereas we were using a pretty old version before.

@char0n I think your error is just because you need to regenerate your language's `.wasm` file by running `tree-sitter build-wasm` with Tree-sitter CLI 0.18.

@Razzeee I don't know what's going on with `WebAssembly.Global`. Maybe the new version of Emscripten is not backwards compatible with old JS engines like Node 10?

**Comment by maxbrunsfeld** [comment]
I think it's because of this Emscripten change: https://github.com/emscripten-core/emscripten/commit/13493fd0a200e809e1d0b45a1dd77ed89683a93c.

**Comment by stsewd** [comment]
> I'm not sure what to do. I don't really want to be stuck on an old Emscripten version, and an older non-standard ABI. Is Node 10 still commonly used? I know VS Code uses Node 12.

I think ubuntu installs that version when using `apt`... Personally I use nvm.

**Comment by Razzeee** [comment]
> I'm not sure what to do. I don't really want to be stuck on an old Emscripten version, and an older non-standard ABI. Is Node 10 still commonly used? I know VS Code uses Node 12.

we have had some users, that were using the language server with node 10 (non vscode) - but it's end of life early this year anyway, so I meant to drop it. I'll do one more release with the old dep. Then drop it for the next version, so don't change anything. Thanks, for investigating.

**Comment by char0n** [comment]
> @char0n I think your error is just because you need to regenerate your language's .wasm file by running tree-sitter build-wasm with Tree-sitter CLI 0.18.

Thanks, I'll try that, at the time of creating this issue only tree-sitter-cli@0.17.3 was available.

**Comment by char0n** [comment]
I can confirm, web-tree-sitter@0.18.0 now works properly with tree-sitter-cli@0.18.0 a not errors in console appears.

**Comment by c4lliope** [comment]
Piling on error behind error here.
Using @char0n's same approach, I see:

`"tree-sitter-cli": "^0.18.1"`
```
Uncaught (in promise) RuntimeError:
abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0).
Build with -s ASSERTIONS=1 for more info.
```

* Could this be a similar emscripten versioning error?
* Is there a way to pass that `-s ASSERTIONS=1` flag through during `tree-sitter build-wasm ...` compile?

**Comment by maxbrunsfeld** [comment]
Closing this out since everything should be using the new emscripten now.
