### ISSUE TITLE
Web-tree-sitter drops fields

### ISSUE THREAD

**Issue by char0n** [tree-sitter/tree-sitter#874]
Hi,

I've noticed that when working with `web-tree-sitter`, "FIELDS" defined in grammar are not presented in resulting Tree. It can be seen on for example [tree-sitter-yaml](https://github.com/ikatyang/tree-sitter-yaml/blob/master/src/grammar.json) grammar where in node.js binding I can see and work with the `keyNode` and `valueNode`, but these properties doesn't exist in Tree from web-tree-sitter.

**Comment by maxbrunsfeld** [comment]
I think this may be fixed in web-tree-sitter 0.19. Can you try it again?

**Comment by char0n** [comment]
@maxbrunsfeld thanks, looking into it just now.

**Comment by char0n** [comment]
@maxbrunsfeld no unfortunately `keyNode` and `valueNode` are still not available in web-tree-sitter@0.19.0

Node itself:
![image](https://user-images.githubusercontent.com/193286/110114921-9fe3ef80-7db5-11eb-9b92-fb40a7164e1c.png)

Node proto:
![image](https://user-images.githubusercontent.com/193286/110115012-c144db80-7db5-11eb-9049-e9ed78995509.png)

**Comment by maxbrunsfeld** [comment]
The fields would not show up in the node's prototype. You would need to check for the fields using an API like  `Node.childByFieldName` or `TreeCursor.currentFieldName`.

**Comment by char0n** [comment]
Yep the workaround with `Node.childForFieldName` works. Unfortunately I have to branch the code according the the environment where it runs:

```js
      const valueNode = 'valueNode' in node ?
        node.valueNode
        : 'childForFieldName' in node
        ? node.childForFieldName('value')
        : null;
```

**Comment by char0n** [comment]
I've created a helper that looks like this:

```ts
    const getFieldFromNode = (fieldName: string, node: SyntaxNode): SyntaxNode | null => {
      return hasIn(`${fieldName}Node`, node)
        ? // @ts-ignore
          prop(`${fieldName}Node`, node)
        : hasIn('childForFieldName', node)
        ? invokeArgs(['childForFieldName'], [fieldName], node)
        : null;
    };
```

**Comment by amaanq** [comment]
I think this is expected and can be closed out - the Node struct in the C side does not contain the field information, so it'd make sense that they don't appear in web-ts too.

**Comment by char0n** [comment]
@amaanq I can be worked around. It's more an inconvenience that we have to work with the same API differently depending on wheter tree-sitter or web-tree-sitter is used.

**Comment by amaanq** [comment]
Hm wdym you work with the same API differently? What do you have available/ready to use in tree-sitter but not web-tree-sitter?
