### ISSUE TITLE
`isNamed` behave differently between js and wasm

### ISSUE THREAD

**Issue by bobzhang** [tree-sitter/tree-sitter#881]
under JS, `isNamed` is a getter so that you can use `x.isNamed`
under JS bindings for wasm, it is a function so that you have to use `x.isNamed()`

**Comment by maxbrunsfeld** [comment]
Yes, this was definitely a mistake 🤦 .

I'm not sure which one to change now. And when we do it, we'll need to communicate it well.

**Comment by bobzhang** [comment]
whatever makes your implementation easier -- but consistency is important, took me a while to figure out

**Comment by amaanq** [comment]
The node and wasm bindings are now aligned - it is a property. I think aligning two JS bindings make sense, but Python does not need to consider what rust, js, wasm, etc do since it's a different language.
