### ISSUE TITLE
Bindings for direct access to the lexer

### ISSUE THREAD

**Issue by RRethy** [tree-sitter/tree-sitter#885]
Are there any bindings to access the lexer and avoid any parsing? I don't see it in the docs but wasn't sure if there was something I was missing. If not, are the any plans to expose the lexer?

**Comment by maxbrunsfeld** [comment]
The lexers that Tree-sitter generates are pretty coupled to the parsers. The parser invokes the lexer with a specific state number that allows it to only attempt to match the subset of tokens that are valid in the current parse state.

I'm not sure how we would expose that in a useful way as a public API. Maybe I'm missing something though; let me know if you still think it'd be useful, and how you might expose it.

**Comment by RRethy** [comment]
Didn't realize it was so coupled to the parser, was looking for a generic lexer for languages that produces a sequence of tokens given a string. I'll close this and keep looking for alternatives, thanks.

**Comment by maxbrunsfeld** [comment]
You can just parse a string and then grab the tokens from the leaves of the syntax tree though.

**Comment by RRethy** [comment]
That's what I was planning as a placeholder solution, but I imagine the performance hit from the unnecessary parsing will be noticeable so I was still hoping for a solution that only lexes.

**Comment by stephe-ada-guru** [comment]
"Adam P. Regasz-Rethy" <notifications@github.com> writes:

> Didn't realize it was so coupled to the parser, was looking for a
> generic lexer for languages that produces a sequence of tokens given a
> string. I'll close this and keep looking for alternatives, thanks.


Wisitoken (https://stephe-leake.org/ada/wisitoken.html) generates a
stand-alone lexer. But if used that way it's just a complicated wrapper
around re2c (https://re2c.org/) which is a nice lexer generator.

-- 
-- Stephe

**Comment by RRethy** [comment]
Thanks Stephe, I took at a look at re2c and while it would work, I'm looking for a more *out-of-the-box* experience where I don't have to specify the lexical syntax for a language myself but rather can use existing syntax files (like treesitter's grammer.js files, or sublime's syntax files like syntect uses). I'll stick with treesitter for now, then maybe when I have more time write a lexer generator which uses these existing syntax files.
