### ISSUE TITLE
golang bindings

### ISSUE THREAD

**Issue by c4lliope** [tree-sitter/tree-sitter#916]
[A quick search](https://duckduckgo.com/?q=c+language+bindings+golang) yields:

* https://github.com/xlab/c-for-go
* https://golang.org/cmd/cgo/
* http://akrennmair.github.io/golang-cgo-slides/#1

**Comment by maxbrunsfeld** [comment]
I haven't used it myself, but there is this: https://github.com/smacker/go-tree-sitter.

**Comment by heeko** [comment]
@smacker, @maxbrunsfeld thanks for that golang binding, it's working well! Would it be a good idea to add it in the official bindings list of the tree sitter website?
