### ISSUE TITLE
Can tree-sitter parse binary format?

### ISSUE THREAD

**Issue by cireu** [tree-sitter/tree-sitter#924]
Just like ELF, tarball and etc. ts_parser_parse_string can accept a string pointer and its length, so we can pass string contains NUL byte, but it also assume that given string is a UTF-8 string.

**Comment by patrickt** [comment]
Input to tree-sitter parsers has to be UTF-8 or UTF-16. I don’t think that binary parsing is within the scope of this project.

**Comment by cireu** [comment]
Thanks for your answer!
