### ISSUE TITLE
Error loading `tree-sitter.{js,wasm}` in browser

### ISSUE THREAD

**Issue by c4lliope** [tree-sitter/tree-sitter#925]
Instead of relying on `Parser.Language.load()` to properly load in `.wasm` parsers, having an option like https://github.com/ballercat/wasm-loader for webpack users would give a second, battle-hardened approach to begin using tree-sitter on the web.

Needed because I am experiencing an error where `Parser.Language.load` is looking in the wrong path for my `.wasm` file.
`Parser.Language.load("/tree-sitter-javascript.wasm")` sends a web request for `/tree-sitter.wasm`. No fix is applicable.

**Comment by maxbrunsfeld** [comment]
The web request for `tree-sitter.wasm` is part of loading the main tree-sitter library; it's not related to calling `Language.Load`.

**Comment by c4lliope** [comment]
Oh, cool. Should I be having my server respond to that request with some
precanned response?

**Comment by c4lliope** [comment]
...because since I'm using a webpack setup the response is a copy of my
index.html .

**Comment by maxbrunsfeld** [comment]
Yeah, the `tree-sitter.wasm` is expected to be available from the same base URL as `tree-sitter.js`.

**Comment by c4lliope** [comment]
Oh, perhaps my error is I'm using
`import Parser from "web-tree-sitter"` in webpack.

I'm missing any `tree-sitter.wasm`; how do I build one?

**Comment by c4lliope** [comment]
Hm, same error using:
`const Parser = require('web-tree-sitter');`

I'll grab `tree-sitter.js`, `tree-sitter.wasm` from your releases and rig up the old fashioned approach. d=

**Comment by c4lliope** [comment]
Huh.
![Screen Shot 2021-02-16 at 1 20 23 PM](https://user-images.githubusercontent.com/30454698/108104855-d0a7f300-7059-11eb-95a0-8f191e31883d.png)

**Comment by maxbrunsfeld** [comment]
It looks like your `tree-sitter.wasm` file is not getting served correctly.

**Comment by c4lliope** [comment]
Roger, I'll check. ⏰

**Comment by c4lliope** [comment]
No, seems like checking `https://0.0.0.0:3000/tree-sitter.wasm` downloads a file on my machine, which is identical to the file in `./public/tree-sitter.wasm`.

```
diff ~/Downloads/tree-sitter.wasm public/tree-sitter.wasm
```
displays no response.
`public/tree-sitter.wasm` had been pulled from [v0.18.1 releases](https://github.com/tree-sitter/tree-sitter/releases/tag/v0.18.1)

**Comment by maxbrunsfeld** [comment]
Are you getting the matching `.js` and `.wasm` files from the same place?

**Comment by c4lliope** [comment]
Yes indeed. I'm baffled.

**Comment by c4lliope** [comment]
Place = https://github.com/tree-sitter/tree-sitter/releases/tag/v0.18.1

**Comment by c4lliope** [comment]
Hm, dug around and looks like earlier releases are lacking `...js` and `...wasm` bundles.
Any remarks on building from source? Cheers.

**Comment by c4lliope** [comment]
aha. https://github.com/tree-sitter/tree-sitter/blob/master/script/build-wasm

**Comment by c4lliope** [comment]
Same problem; 

```bash
./script/build-wasm
rm ../hierarch/public/tree-sitter.*
cp lib/binding_web/tree-sitter.* ../hierarch/public/
```

-> `Bad magic number`

on 699af842 (current HEAD)

**Comment by c4lliope** [comment]
Same error on v0.18.1 (28fd8b33) and v0.18.0 (1dc127e5),
so I'm thinking this is more likely a problem with my webpack eviron;
an odd thing is that the message "Bad magic number" is appearing in the web HTTP response,
instead of the browser console as I'd expect.

**Comment by c4lliope** [comment]
Confirmed; the issue is with loading, the binaries are fine.

I ran a program `wasm.js` in Node [as described here](https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/README.md#running-wasm-in-nodejs)

```js
const Parser = require('web-tree-sitter');

(async () => {
  await Parser.init();
  const parser = new Parser();
  const Lang = await Parser.Language.load('tree-sitter-javascript.wasm');
  parser.setLanguage(Lang);
  const tree = parser.parse('let x = 1;');
  console.log(tree.rootNode.toString());
})();
```

and also changed the require to use my local `tree-sitter.js`.
The process is flawless using WASM-in-node.

So, I'm back to the `Parser.Language.load()` problem.

**Comment by c4lliope** [comment]
Superseded.
