### ISSUE TITLE
All web bundlers mangle `tree-sitter.wasm`

### ISSUE THREAD

**Issue by c4lliope** [tree-sitter/tree-sitter#927]
When `tree-sitter.wasm` is requested by the browser from a `webpack` server,
the HTTP response reads only "Bad magic number".

Confirmed using `create-react-app`, and also in `Rails` using `webpacker`.
Superceding #925 .

**Comment by c4lliope** [comment]
![snakes on every plane](https://imgs.xkcd.com/comics/snakes_on_a_plane_2.jpg)

**Comment by c4lliope** [comment]
* ❌ webpack
* ❌ parcel
* ❌ snowpack

**Comment by c4lliope** [comment]
😭 
Seems like there needs to be a way to manually load the `.wasm`, without `tree-sitter.js` jumping the gun.

**Comment by maxbrunsfeld** [comment]
Yeah, last time I looked into this, web bundlers like webpack and parcel just did not handle coupled js + wasm files at all. I'm not sure what work there is to do for this on the Tree-sitter side. If there is some clear convention for how these files should be packaged, I am open to a PR that adopts it.

**Comment by c4lliope** [comment]
So I'm reading our situation clearly;

* Tree-Sitter is coded in C, and that C code [is compiled] into a `tree-sitter.wasm` binary.
* `tree-sitter.js` is compiled, mainly from [binding.c], to expose the `.wasm` API to the browser.

I'm unclear on...

* Where in `tree-sitter.js` does the code load in and depend upon `tree-sitter.wasm`?
* Once `tree-sitter.js` is loaded you can access `window.TreeSitter`; is there a similar global variable defined once the `.wasm` bundle is loaded?

[is compiled]: https://github.com/tree-sitter/tree-sitter/blob/master/script/build-wasm
[binding.c]: https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/binding.c

I can imagine [wasm-loader](https://github.com/ballercat/wasm-loader) loading in the `.wasm`,
and perhaps exposing a global variable (`window.TreeSitterBundle`)
which `tree-sitter.js` could then access and rely on.

This approach would roughly equal (in pseudocode):

```html
<script>
  fetch("/tree-sitter.wasm")
  .then(response => response.binary())
  .then(response => window.TreeSitterBundle = response)
</script>
<script src="/tree-sitter.js" />
```

Disclaimer: I'm a newbie on webassembly, only a couple days' research behind my ideas.

**Comment by c4lliope** [comment]
Gah-damn.

I remained curious, so I placed my Ruby cap on and made a quick Rack app; roughly:

`rack.rb`
```ruby
require "rubygems"
require 'sinatra'

get '/tree-sitter.js' do
  send_file File.join("ts", "tree-sitter.js")
end

get '/tree-sitter.wasm' do
  send_file File.join("ts", "tree-sitter.wasm")
end

get "/" do
  File.read("index.html")
end
```
`index.html`
```html
<head>
  <script src="/tree-sitter.js"></script>
</head>
<body>
  <script>
    const Parser = window.TreeSitter
    debugger
  </script>
</body>
```

and tree-sitter files in `./ts/`

...and same error! "Bad magic number".

So, this isn't an issue with Node package bundlers, huh?
I changed from Chrome -> Firefox,
and bam. Success.

Back to the Webpack build?
`<script src="/tree-sitter.js" ></script>` inside `public/index.html`, alongside TS files?
In Firefox -> Bam. Success.

Back to Chrome – the official Playground page displays the bug! Though the exercise does indeed run properly.
![Screen Shot 2021-02-18 at 4 46 56 PM](https://user-images.githubusercontent.com/30454698/108426172-6fbf1d00-7209-11eb-9f85-cbcfd800cf03.png)

So this seems to be an error in Chrome's DevTools,
an error which doesn't break WASM but is very misleading
when you load a WASM resource.

Sorry for the hullaballoo,
seems like there is no breaking error here.
I'm glad I can keep making progress using your library,
and glad we can close some issues.
Cheers! 🥂

**Comment by maxbrunsfeld** [comment]
Wow, that's really interesting. Thanks for sharing your debugging process!

**Comment by c4lliope** [comment]
Eh, I'm glad I'm able to hold my own, is all. If you need a pair of eyes
and hands on any similar problems, I'll be coding in a similar head space
this coming season.

I really admire your codebase, seems like the more you dig the cooler it
becomes.
Keep breaking barriers.
