### ISSUE TITLE
ts_tree_delete takes a long time to run

### ISSUE THREAD

**Issue by invrainbow** [tree-sitter/tree-sitter#929]
Say I'm crawling through a directory of files and parsing each one to get some info. The procedure looks something like:

```c
char *files[] = ...; // crawl all files
for (int i = 0; i < files_len; i++) {
  int len;
  char *data = mmap_file(files[i] ,&len);
  if (data != NULL) {
    auto tree = ts_parser_parse_string(parser, NULL, data, len);
    if (tree != NULL) {
      // do something with tree
      ts_tree_delete(tree);
    }
    mmap_free(data);
  }
}
```

The problem is that `ts_tree_delete` takes a long time to run. This adds up over the course of parsing a whole directory tree. Is it possible to make it faster, combine calls, anything like that?

**Comment by maxbrunsfeld** [comment]
Are you on Linux? You might try using [jemalloc](https://github.com/jemalloc/jemalloc) in your application instead of the default `malloc`/`free` implementation that comes with the system libc. It can make a very big difference.

**Comment by invrainbow** [comment]
Nope, I'm on Windows.

On that note, my application actually has a custom memory allocator that allocates a big chunk of memory at the beginning and frees it all at the end. However, when I tried to replace malloc/calloc/realloc with my own allocator, I started getting memory errors. I'll keep debugging, but other than the usual pitfalls, is there anything else I need to know? Or should it just work as long as Tree-sitter is provided with memory whenever it asks for it?

**Comment by maxbrunsfeld** [comment]
No, as far as I understand, Tree-sitter just expects the usual `malloc` interface.

**Comment by invrainbow** [comment]
Ok, this is super bizarre, but when I swap out malloc for my own allocator, I fail this assert in `ts_subtree_summarize_children`:

https://github.com/tree-sitter/tree-sitter/blob/2f28a35e1b118e17ab2fb6236a24c7b557e3c8a9/lib/src/subtree.c#L373

I see this is called from `ts_subtree_new_node`:

https://github.com/tree-sitter/tree-sitter/blob/2f28a35e1b118e17ab2fb6236a24c7b557e3c8a9/lib/src/subtree.c#L499-L517

So `ts_subtree_summarize_children` checks `.data.is_inline`, but `ts_subtree_new_node` assigns `.ptr`. I check the type of `MutableSubtree` and it's a union containing `data` (a struct) and `ptr` (a pointer). So basically this assert will fail whenever the the last bit of the address of `ptr` is a 1? Meaning `ptr` has to be aligned on an even-numbered address?

Is this a bug, a known requirement of the memory allocator, something else?

**Comment by dcreager** [comment]
> Is this a property of malloc Tree-sitter depends on by design? (Has everyone who swapped out malloc just gotten lucky that they happened to only return even-numbered addresses?)

I think that’s a requirement of any `malloc` implementation — not just that the result is even but that it’s [aligned to the largest possible alignment of the platform](https://stackoverflow.com/a/62773923).

**Comment by maxbrunsfeld** [comment]
I think I'll close this out, because I don't know of any optimizations that we plan to do to address this, aside from allowing custom allocators.
