### ISSUE TITLE
Query pattern only matches with extra capture

### ISSUE THREAD

**Issue by felixwilhelm** [tree-sitter/tree-sitter#937]
Hi,

first of all, thanks for writing tree-sitter. I'm a big fan!

For the following C code 
```
struct test {
        bool a;
        union {
                bool b;
                bool c;
        } val;
};
```
the query 
```
((struct_specifier body: (field_declaration_list (field_declaration type: (union_specifier))))@1)
``` 

does not return any matches. 
However, the query 
```
((struct_specifier body: (field_declaration_list (field_declaration type: (union_specifier)@2)))@1)
```  
correctly matches the struct and the union: 
```
test.c
  pattern: 0
    capture: 1, start: (0, 0), end: (6, 1)
    capture: 2, start: (2, 8), end: (5, 9)
```

The only difference is the addition of the capture @2 for the union field.
I think that's a bug and I can get the expected result for the first query (a capture match for the whole struct) by 
removing the step->contains_captures condition before state splitting in lib/src/query.c : 
```
diff --git a/lib/src/query.c b/lib/src/query.c
index bf0598ce..e26d4c1e 100644
--- a/lib/src/query.c
+++ b/lib/src/query.c
@@ -2711,7 +2711,7 @@ static inline bool ts_query_cursor__advance(
         // parent, then this query state cannot simply be updated in place. It must be
         // split into two states: one that matches this node, and one which skips over
         // this node, to preserve the possibility of matching later siblings.
-        if (later_sibling_can_match && step->contains_captures) {
+        if (later_sibling_can_match) {
           if (ts_query_cursor__copy_state(self, &state)) {
             LOG(
               "  split state for capture. pattern:%u, step:%u\n",
```

**Comment by maxbrunsfeld** [comment]
Thanks for the report, and for the great debugging! Your findings make perfect sense. I think I can incorporate them into a fix this week.

**Comment by maxbrunsfeld** [comment]
This is fixed on master.

I just realized though, that it would have been smarter to land this fix this *before* merging https://github.com/tree-sitter/tree-sitter/pull/943, which bumps the parser ABI version, requiring parsers to be regenerated. I plan to release a new CLI version and regenerate all of the parsers in the `tree-sitter` org (including `tree-sitter-c`) in the next couple of days, so the fix should be usable via the master branch soon (though not now).

In the meantime, [this temporary branch](https://github.com/tree-sitter/tree-sitter/tree/library-fixes-before-abi-changes) contains this fix, but does *not* incorporate the ABI changes.

Thanks for your investigation!
