### ISSUE TITLE
Ignore folders in `queries` for "tree-sitter test"

### ISSUE THREAD

**Issue by tjdevries** [tree-sitter/tree-sitter#938]
I'm writing my own grammars for nvim-treesitter and we use the format `queries/<filetype>/<query>.scm` to store queries.

When I run `$ tree-sitter test` in my grammar directory, it will always fail with:

```
Error reading query file "lua"
Details:
  Is a directory (os error 21)
```

Perhaps instead of erroring, it could just ignore folders? This makes it difficult to have CI run the tests since it will always fail.

**Comment by patrickt** [comment]
Maybe we should recursively enumerate `.scm` files?

**Comment by tjdevries** [comment]
That also would work fine with me -- I'm actually not sure what the test is trying to do with the queries (my guess is that is checks to make sure that the queries can be parsed and have valid nodes?).

Thanks for the reply :)

**Comment by maxbrunsfeld** [comment]
> my guess is that is checks to make sure that the queries can be parsed and have valid nodes

Yeah, exactly. I think it makes sense to recursively walk that directory as you said.
