### ISSUE TITLE
tree-sitter-haskell rewrite

### ISSUE THREAD

**Issue by tek** [tree-sitter/tree-sitter#944]
Hi there, since the project hasn't been touched in a few years I thought it might be sensible to cross-post this here.

https://github.com/tree-sitter/tree-sitter-haskell/pull/29

I'd volunteer to take over as maintainer, please advise!

**Comment by ahlinc** [comment]
@tek Did you try to contact with repository contributors?
Also please note there is [discussions](https://github.com/tree-sitter/tree-sitter/discussions) tab here in this repo what may be a better place for such questions that aren't directly related to the tree-sitter core behavior. If you can, I would ask you try to convert this to the discussion.

**Comment by tek** [comment]
I don't see any controls to convert the issue! maybe someone with permissions can do that.
