### ISSUE TITLE
Make it easy to define identifiers that allow unicode character

### ISSUE THREAD

**Issue by tclem** [tree-sitter/tree-sitter#95]
Many languages (e.g. Ruby and Go) allow identifiers to include unicode characters, but right now there's not an easy way to define these in the grammar. [tree-sitter-go](https://github.com/tree-sitter/tree-sitter-go/blob/master/grammar.js#L18) manually allows some greek characters and tree-sitter-ruby fails to parse valid code like this constant assignment: `C😀 = 1` because it just matches ascii character classes with it's [regexes](https://github.com/tree-sitter/tree-sitter-ruby/blob/master/grammar.js#L30).

**Comment by maxbrunsfeld** [comment]
Since ruby allows *any* character in its identifiers, we might actually not need any special unicode-related features. It seems like what ruby is doing is just treating any character that's not whitespace or a known operator/separator character as part of the identifier. So the right solution would probably be to define `identifier` as something like this:

```js
/[a-z][^\s\.+-*/%=()\[\]{}]*/
```

a letter followed by any number of characters that are neither whitespace nor operators/separators like `.`, `+`, `-`, `[`, etc.

**Comment by axelson** [comment]
I'd like to second this request for in the context of creating an Elixir parser. Elixir qualified calls can include unicode. Here's one example:

> Qualified calls, such as Math.add(1, 2), must start with an underscore or a Unicode letter that is not in uppercase or titlecase.

Note that the `add` portion of the example is the part that is considered the qualified call.

Source: https://hexdocs.pm/elixir/master/syntax-reference.html#qualified-calls-remote-calls

I'm unclear how this could reasonably be described in Tree-Sitter currently, but if I'm missing something then please let me know.

**Comment by Tuxified** [comment]
I concur with @axelson, there doesn't seem to be a straightforward way to parse Elixir atoms, for example `:tonći` is a valid atom, I'm trying to parse it using `seq(":", /[_0-9\p{L}]/u, repeat(/[@_0-9\p{L}]/u), optional(choice("?", "!")))` as a rule, but tree-sitter seems to shield it:

> Error processing rule atom
Details:
  Regex error: Unsupported character class syntax Unicode(ClassUnicode { span: Span(Position(o: 6, l: 1, c: 7), Position(o: 9, l: 1, c: 10)), negated: false, kind: OneLetter('\\') })

`\p{L}`  Matches any character in the 'Letter' unicode category 

I presume other languages like Swift, Ruby, Go, Python etc could also benefit from this

**Comment by maxbrunsfeld** [comment]
Unicode property escapes like `\p{L}` are now supported.
