### ISSUE TITLE
Parse a single expression in middle of file?

### ISSUE THREAD

**Issue by invrainbow** [tree-sitter/tree-sitter#950]
If I know there's an expression node at a certain position, can I start at that position and only parse that expression?

```go
func main() {
	x := foo.bar()
}
```

I'd like to tell Tree-sitter to start at row 1, column 6, and get the node corresponding to `foo.bar()`.

**Comment by ahlinc** [comment]
It's not possible for now cause it isn't enough to just tell starting position a rule that will be used also need to be specified.
There are several tickets about to have such feature in tree-sitter: https://github.com/tree-sitter/tree-sitter/issues/711 https://github.com/tree-sitter/tree-sitter/issues/870

**Comment by maxbrunsfeld** [comment]
Yeah, the current suggestion would be to parse the whole file, and then take the syntax node at the given position.

**Comment by maxbrunsfeld** [comment]
I'm going to close this out in favor of those other issues that @ahlinc mentioned.
