### ISSUE TITLE
Problems with new version

### ISSUE THREAD

**Issue by Razzeee** [tree-sitter/tree-sitter#960]
Our smoke test CI pipeline seems to fail with the new version. My rust is not very good, so I'm still investigating (or waiting for help), but I thought it might make sense to let you know.

Failing code: https://github.com/elm-tooling/tree-sitter-elm/pull/87

Example pipeline: https://github.com/elm-tooling/tree-sitter-elm/pull/87/checks?check_run_id=2008127837

Test line that fails: https://github.com/elm-tooling/tree-sitter-elm/blob/master/rust/lib.rs#L45

**Comment by maxbrunsfeld** [comment]
The new library is only compatible with parsers generated with the new CLI. If you upgraded to the latest commit of the library, you should just need to regenerate your parser with the newest version of the CLI.

**Comment by maxbrunsfeld** [comment]
Oh, I see; it's the reverse. You have regenerated the parser, but are not able to get the latest library version.

**Comment by maxbrunsfeld** [comment]
Tree-sitter 0.19 is published to crates.io.

**Comment by maxbrunsfeld** [comment]
I'm gonna close this out but we can reopen it if there are still similar problems after upgrading.

**Comment by Razzeee** [comment]
Should be fixed now, let me just change the title instead.

Thank you for the swift response.
