### ISSUE TITLE
Version incompatibility

### ISSUE THREAD

**Issue by char0n** [tree-sitter/tree-sitter#964]
tree-sitter@0.18.1 is not compatible with tree-sitter-json@0.19.0. I'm getting: ` RangeError: Incompatible language version. Compatible range: 9 - 12. Got: 13`

**Comment by theHamsta** [comment]
This is expected. Please read: https://github.com/tree-sitter/tree-sitter/pull/943

**Comment by char0n** [comment]
Hm I did regenerate the parser, but still getting this.

**Comment by char0n** [comment]
I've updated all tree-sitter-* packages to latest versions and regenerated the grammar but I cannot get it to work except dongrading tree-siiter-json@0.16.0

**Comment by maxbrunsfeld** [comment]
It sounds like you are using an older version of the tree-sitter library, with a newer version of some grammar. The library version 0.19 works with language ABI version 13.

**Comment by char0n** [comment]
Right, I was problem in my setup. Thanks!
