### ISSUE TITLE
Unable to capture extra node in "parent" node

### ISSUE THREAD

**Issue by stsewd** [tree-sitter/tree-sitter#967]
After re-generating the grammar of https://github.com/nvim-treesitter/tree-sitter-query with ts-cli 0.19.x we no longer can't use this query:

```
(program (comment) @capture)
```

This query works

```
(program (named_node) @capture)
```

The only difference is that `comment` is a node from "extras"

**Comment by maxbrunsfeld** [comment]
Yeah, thanks for the report. The workaround right now, for *extra* nodes, would be to match them with no parent context. I can fix this next week.
