### ISSUE TITLE
Allow "tree-sitter parse " to omit token positions in parse tree output

### ISSUE THREAD

**Issue by PBug90** [tree-sitter/tree-sitter#970]
Currently, running `tree-sitter parse <filename>` does produce a valid parse tree with token positions in brackets. 
I would like to use it to generate a parse tree that I can paste into my corpus testfiles since the `tree-sitter test` command expects a syntax tree without token position information.

**Comment by alemuller** [comment]
You can use sed to remove the brackets. I have this snippet on neovim:

```
map <F5> :.!tree-sitter parse filename.ext \| sed 's/\[[^][]*\] - \[[^][]*\]//g' \| sed 's/ $//g' \| sed 's/ )/)/g'<CR>
```

**Comment by Razzeee** [comment]
You can call `tree-sitter test -u` to update all your tests to whatever they return

**Comment by PBug90** [comment]
> You can call `tree-sitter test -u` to update all your tests to whatever they return

That works like a charm. I did check the `tree-sitter test --help` output but it did not cross my mind that "update" refers to update the fixtures. Maybe that can be added to the help output?

**Comment by PBug90** [comment]
Updated the help output. #986

Therefore the feature request is covered by the test/filter combination.
