### ISSUE TITLE
web/wasm bindings should allow passing a URL to the WASM file

### ISSUE THREAD

**Issue by NullVoxPopuli** [tree-sitter/tree-sitter#972]
looks like `init` tries to load tree-sitter.wasm, https://github.com/tree-sitter/tree-sitter/tree/master/lib/binding_web
but, I would like to put tree-sitter.wasm in a different location than `/tree-sitter.wasm`

**Comment by danechitoaie** [comment]
See:

- https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/tree-sitter-web.d.ts#L7
- See https://emscripten.org/docs/api_reference/module.html#creating-the-module-object

`Parser.init()` can receive a moduleOptions object where you can specify a custom `locateFile(filePath, _filePrefix)` function.

So something like:
```
    const Parser = require("web-tree-sitter");
    await Parser.init({
        locateFile(filePath, _filePrefix) {
            if (filePath === "tree-sitter.wasm") {
                return "tree-sitter-abcd.wasm";
            }

            throw new Error("Unexpected file! " + filePath);
        },
    });
```

**Comment by maxbrunsfeld** [comment]
Yeah, this got implemented in https://github.com/tree-sitter/tree-sitter/pull/1367.
