### ISSUE TITLE
Future...

### ISSUE THREAD

**Issue by quang423** [tree-sitter/tree-sitter#976]
I have this idea in head really vivid:

**_Translator_**

Translates OP codes, between specific languages. There would be, despite special things like array and dictionary handling, a compatibility level, which delivers something with same meaning, that is compilable, like e.g. javascript's array for cpp. First it can be extracted from JS parser, and secondly, it can be in database, so when we convert JavaScript to C or Cpp or vice versa, it can come handy. So some specific constructions can have some of their equalities in another languages, which they are replaced by and structure keeps the same changes.

It's easy in AST, to even flip e.g. array pop and push, to be compatible with C++ vector, or similar things. I can code this array thing, but I would first need some contact layer of two languages. And thing like other... With specific translation to translation, something like dictionary and transmissable like installable package, the subdictionaries. Database of AST shapes, that can fit your project, or changes in code structure, that can be vital for your code.

But I need something like:

```
let tree = parser.parse(PY)
tree.translateTo(JS)
fs.writefile('codetobeexec.js', tree.root.toString())

```
I can explain all the language differences, but I need something like framework, where I can already have elements of one another, I know I can quickly mod this myself, but I just want somebody to know to do this to.

This project should be focused around translation.

And there should be graphical interface for NODES and CONNECTIONS.

I can make both in javascript, but I'm so poor, I would need some little budget for that, if anybody got some BTC from the long past.

I want to make graphical connector to OP code layer to.

**Comment by maxbrunsfeld** [comment]
These are great ideas, but they are not in scope for this project. Let me know if you implement something like this on top of Tree-sitter; it sounds very interesting!

**Comment by quang423** [comment]
I mean... Search and replace patterns of AST trees are required for translation. I'll translate at least one lang to another, or some universal language of tree should be established... And then to specific language....

Universal Language Tree

Maybe... Would you like to do something about that? I could create platform, and some other people will help me with translation issuses...

Do you preffer writting or clicking when programming?
