### ISSUE TITLE
Segmentation Fault when opening a non-vim file

### ISSUE THREAD

**Issue by Alby407** [tree-sitter/tree-sitter#984]
I get a segmentation fault using tree-sitter with neovim when opening a non-vim file (e.g. a Python file). 
```
[1]    12966 segmentation fault (core dumped)  nvim ~/.zshrc
```
Running dmesg gives me the following output on neovim:

```
[ 1730.912128] nvim[11786]: segfault at 32 ip 00007f311682bed3 sp 00007ffe2a7c55f0 error 4 in libtree-sitter.so.0.0[7f311682a000+20000]
[ 1730.912195] audit: type=1701 audit(1615591209.958:185): auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=11786 comm="nvim" exe="/usr/bin/nvim" sig=11 res=1
```

When I remove tree-sitter, everything works as expected. Any ideas, why this is the  case?

**Comment by maxbrunsfeld** [comment]
Hi, to report Neovim bugs, please open an issue on the Neovim repo. If at some point you are able to isolate the bug so that you can reproduce it with a minimal example *outside* of Neovim, then you should report it here. Good luck!
