### ISSUE TITLE
Parser generation can run into an infinite loop

### ISSUE THREAD

**Issue by Cu3PO42** [tree-sitter/tree-sitter#990]
I have created a grammar for which `tree-sitter generate` seems to run indefinitely. This appears to be related to the `_comment` rule, for which inclusion is allowed anywhere in the tree. I have removed all other rules and the grammar is as follows:
```js
module.exports = grammar({
  name: 'bug-reproduction',

  rules: {
    source_file: $ => repeat(choice($.foo, $._comment)),

    _comment: $ => choice(
      /\/\/.*\n/m,
      $._blockComment,
    ),
    _blockComment: $ => seq(
      "/*",
      $._blockCommentContents,
      repeat(seq(
        optional("/"),
        $._blockComment,
        $._blockCommentContents,
      )),
      optional("*"),
      "*/",
    ),
    _blockCommentContents: $ => /([^\/\*]|\/[^\*]|\*[^\/]|\\\/|\*\\\/)+/,

    foo: $ => 'foo',
  },
  extras: $ => [$._comment],
});
```

I have also trimmed down the comment rule in a way that preserves this issue:
```js
module.exports = grammar({
  name: 'bug-reproduction',

  rules: {
    source_file: $ => repeat(choice($.foo, $._comment)),

    _comment: $ => choice(
      /\/\/.*\n/m,
    ),

    foo: $ => 'foo',
  },
  extras: $ => [$._comment],
});
```
The top-level declaration includes `_comment` as a choice as a work-around to issue #768. At this point removing the `choice` in the `_comment` rule fixes the problem.

I have found the following fixes to this problem so that the grammar including both types of comments generates as expected:
* Renaming the rule from `_comment` to `comment`. Unfortunately this also implies the inclusion of the comment nodes into the tree and I would rather not handle them in every possible location.
* Renaming the rule to `comment` and introducing a new rule `_commend: $ => seq($.comment, '')`. This seems to imply the problem is somehow related to the use of choice. I have read in other issues that empty tokens can cause problems with error recovery, so this doesn't seem like a true fix either. Defining the rule as `seq($.comment)` does not fix the issue.
* I can factor out the leading slash from line and block comments and rewrite the grammar as follows:
```js
module.exports = grammar({
  name: 'bug-reproduction',

  rules: {
    source_file: $ => repeat(choice($.foo, $._comment)),

    _comment: $ => seq("/", choice(
      /\/.*\n/m,
      $._blockCommentWithoutSlash,
    )),
    _blockComment: $ => seq('/', $._blockCommentWithoutSlash),
    _blockCommentWithoutSlash: $ => seq(
      "/*",
      $._blockCommentContents,
      repeat(seq(
        optional("/"),
        $._blockComment,
        $._blockCommentContents,
      )),
      optional("*"),
      "*/",
    ),
    _blockCommentContents: $ => /([^\/\*]|\/[^\*]|\*[^\/]|\\\/|\*\\\/)+/,

    foo: $ => 'foo',
  },
  extras: $ => [$._comment],
});
```
~~While this works as a temporary work-around, I would hardly consider it a fix.~~ I believe this isn't a complete fix since this would now allow inserting whitespace between the first slash and (second slash OR `*`).

With some debugging I have managed to track the indefinitely running step to be `remove_unit_reductions`, specifically [this loop](https://github.com/tree-sitter/tree-sitter/blob/master/cli/src/generate/build_tables/minimize_parse_table.rs#L102-L115). Looking at this code I can see how it could get stuck in an infinite loop, but I'm not really sure why the name would influence this behavior.

**Comment by ahlinc** [comment]
As I understand, it's current tree-sitter limitation. `extras` currently allow only tokens and not rules, it somehow allows to include rules but behaviour is strange and unexpected, which I also saw in a grammar.
Try to define your `_comment` like
```
_comment: $ => token(...),
```

**Comment by maxbrunsfeld** [comment]
It actually is allowed to have non-terminals as extras now, though there are some restrictions. I think the problem is probably that `_comment` is:
* non-terminal (it has children)
* used *both* as an extra, and also as a part of a non-extra rule

I can try to look into this soon.
