### ISSUE TITLE
Support "generic" erroring tests

### ISSUE THREAD

**Issue by Julian** [tree-sitter/tree-sitter#992]
A few times early on whilst writing a parser, I've wanted to be able to write a test that said the parsed code errors, but without specifying the precise s-expression, because that changes as I evolve the parser, and until / unless #255 is implemented in my parser, I don't have a ton of control anyhow if the ERROR isn't in a very logical spot.

It seems like it'd be nice to be able to say `(foo (ERROR *))` and have that ignore whatever error is in that spot, even nested. Or at least instead perhaps a generic top-level s-expression to say "this parse should error" without specifying any other details.

Obviously if there's an entirely better way to do this feel free to close and/or let me know!

**Comment by amaanq** [comment]
The `:error` attribute is what you're looking for now :slightly_smiling_face: this was added a while ago but I just saw this issue - sorry!

**Comment by Julian** [comment]
Fantastic, thanks for letting me know!
